### ISSUE TITLE
Versioning weirdness on readthedocs

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1110]
There are several related problems here, which will have to be managed by @DRMacIver (or delegated to someone else with authorised logins).

1. https://readthedocs.org/projects/hypothesis/versions/ is missing everything since version 3.1.0 - that's a *lot* of releases without version-tagged docs.
2. Because the sidebar does not scroll, on most screens it is literally impossible to select a recent version of the docs (click the little green `v: latest` and weep) - improving that UI may be an upstream issue for the Sphinx RTD theme.
3. Related, I'd also like to only have online docs for the latest patch of each minor release to keep the number down - possibly an issue for the theme (display/build option?) or RDT itself.  For discussion and manual intervention: do we really need to keep Hypothesis 0.x docs online?  Or any before 3.0?

**Comment by dchudz** [comment]
It's even worse: 

- if you're looking at any of the versions older than 3.1 (e.g. [this](http://hypothesis.readthedocs.io/en/w.3.0_a/)), you get a message`You are not using the most up to date version of the library. 3.1.0 is the newest version.`
- the message has a link to 3.1.0 which is broken

**Comment by Zac-HD** [comment]
Now fixed by deselecting old versions - we only support the latest release, and earlier docs are available via version control.  (in practice they haven't been working anyway, so I'm not worried that anyone will complain)
