### ISSUE TITLE
RFC: A timeline for the next two major Hypothesis versions

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis#1134]
From discussion in IRC:

* We're getting a new Rust backend at some point. We could add this behind a feature flag in a minor version, but making it the default would be a major version.
* Said Rust backend is fairly close, quoting David “ ideally the timeline […] is in the order of a single digit number of months from now, probably not later than end of June”.
* We've accumulated a number of deprecated features in the public API, which we'd like to expunge at some point.

So the proposal is we have two major versions in the next six months:

- **Episode IV *A New Hypothesis* – around March.**

  - This release has all our source-breaking changes, removing anything that's deprecated in the API.  
  - It *may* *[ETA: at some point]* include a feature flag for using the new Rust backend, but it will always use the existing Python backend by default. This is beta quality, and would mature over the course of the release.
  - So a user might need to edit their 3.x code to run in 4.x, but it installs on the same systems as before.

- **Episode V *The Oxide Strikes Back* – whenever the Rust backend is mature.**

  - This release has no source-breaking changes. Anything we deprecate in 4.x remains deprecated, not removed, in 5.x.
  - It uses the Rust backend by default, which requires a Rust compiler.
  - So a user doesn't need to edit any of their 4.x code to run 5.x, but they do need to install a Rust compiler.

Two major versions mean we separate two potentially complicated changes, which should make the debugging easier for everyone.

---

Assuming nobody objects, I’ll create a v4.0 branch in a week’s time, enable Travis runs for that branch, and open a long-running PR against master. We can create additional PRs to remove deprecated code and merge them into that branch, and when all the deprecated code is gone, we can merge the v4.0 branch into master.

@HypothesisWorks/hypothesis-python-contributors Thoughts? Comments? Suggestions?

**Comment by DRMacIver** [comment]
I am 👍 on the idea. I don't think we should constrain the timing of 4.0 for the Rust back-end though.

I do think sadly that we should probably not turn *all* the deprecation warnings into errors and, say, anything that has been deprecated in the last six months at point of release should probably not become an error yet.

One thing to consider that might argue for us holding off on this: If we are going to be changing the name of strategies and a bunch of the strategy names to line up with `hypothesis-ruby`, we probably want to consider whether to do it before, during, or after 4.0. Either way it would (as per above) not involve actually turning the old names into errors, but if we're going to deprecate all the things then doing it in a major relase is probably a good time to do it.

**Comment by alexwlchan** [comment]
> I don't think we should constrain the timing of 4.0 for the Rust back-end though.

I’m not sure what you mean. Do you mean we shouldn’t *wait* for the Rust back-end or that we shouldn’t get it out *before* the Rust back-end, or something else? (Because I wasn’t suggesting either of the first two, but I might have been unclear.)

> anything that has been deprecated in the last six months at point of release should probably not become an error yet.

Yeah, I could agree with that – but then anything that stays deprecated in 4.0 also stays deprecated in 5.0?

> we probably want to consider whether to [rename strategies] before, during, or after 4.0

My vote would be for introducing the new names in 4.0, deprecating the old names, and then there's a third major release (6.0?) which eventually drops the old names – but I think those need to stick around for longer than the six months proposed above, as the old names are so intrinsic and widely-used.

**Comment by DRMacIver** [comment]
> (Because I wasn’t suggesting either of the first two, but I might have been unclear.)

I wasn't 100% if you were suggesting one of those so thought I would clarify that it's very unlikely we'll have a rust backend in March and I don't think that should affect the plan.

> Yeah, I could agree with that – but then anything that stays deprecated in 4.0 also stays deprecated in 5.0?

Yeah (or if the timeline slips a lot we do a 5.0 without rust backend).

> My vote would be for introducing the new names in 4.0, deprecating the old names, and then there's a later, third major release (6.0?) which eventually drops the old names.

One thing to consider is that the new names might not be 100% baked in for march, so we may want to think about even more major releases.

> I think those need to stick around for longer than the six months proposed above, as the old names are so intrinsic and widely-used.

100% agreed. Deprecating them is *so* invasive TBH that I'd even consider not introducing deprecation warnings for the first six months, or just adding one on module import or something, and being more aggressive later.

Of course, if we're doing that then adding them in to the public API doesn't require a major release. There's some precedent: The `hypothesis.strategies` module wasn't introduced until 1.3.

**Comment by alexwlchan** [comment]
The idea behind the 4.0 release is that we get it out of the way *well before* the Rust backend is ready, so we can do another release which is *just* the Rust backend.

**Comment by DRMacIver** [comment]
> It may include a feature flag for using the new Rust backend,

This is what I was commenting on: It may in the sense that it is permitted, but the chances of it doing so are basically zero.

**Comment by alexwlchan** [comment]
>> It may include a feature flag for using the new Rust backend,
>
>This is what I was commenting on: It may in the sense that it is permitted, but the chances of it doing so are basically zero.

Ah, so I’ve been unclear here.

By “may include” I mean “may introduce a feature flag in some minor revision after 4.0.0, when it’s good enough for trying but not good enough to be the default”.

**Comment by DRMacIver** [comment]
Cool. We're on the same page then!

**Comment by Zac-HD** [comment]
In general, I like this plan :sparkling_heart: 

IMO *everything* deprecated in 3.x should be gone in 4.0 - it's going to save us a lot of grief later, and I don't mind encouraging users to pin `hypothesis>=3.x,<4` in their requirements (it's a good habit anyway).

So I would stick exactly with Alex's plan above, and add the following:

**Episode 6: Return of the Gem-API** - After hypothesis-ruby has been at 1.x for a few months, and we're confident that we've discovered any unclear names or user confusion, introduce the new names to hypothesis-python in 5.x with a gentle deprecation pathway; and a year or so later go to 6.0 as another remove-all-the-deprecated-stuff release.

**Comment by Zac-HD** [comment]
Oh, and once we settle on a plan we should add it to our docs: https://hypothesis.readthedocs.io/en/latest/development.html#project-roadmap

**Comment by dchudz** [comment]
It sounds like this means that if there are any breaking changes we'd want to make when switching to the Rust backend (anything user-facing we do that it makes us want to change or stop supporting), we need to make that breaking change in 4.0 (and ideally deprecate it now).

I have no idea if there's anything like that, but it seemed like it was worth noting explicitly.

**Comment by Zac-HD** [comment]
I've created [a milestone](https://github.com/HypothesisWorks/hypothesis-python/milestone/5) to track issues that we should fix before the next major version (ie new deprecations or warnings that will then turn into errors).

- I have open PRs for four out of seven.  #1072 is ready to go, but the decimals fixes in #955 needs work.
- The remaining issues have assignees but no pulls yet
- This issue should be closed by documentation explaining the agreed plan

**Comment by dchudz** [comment]
Nice! The unanswered questions I see are:

- how much of the deprecated stuff can we remove in 4.0? (if it's not everything, doesn't that mean it's staying deprecated until 6.0?)
- is there anything we need to deprecate in 4.0 to avoid breaking changes in the rust-backed 5.0?

**Comment by Zac-HD** [comment]
- @DRMacIver wants to keep recent (~6 months) warnings as warnings.  My strong preference is to make them all errors though - it promotes good versioning habits downstream (pin to `<4`!), and will be much easier for us to deal with.  This is probably partly due to what we're working on - he spends relatively more time in internals, I spend relatively more on UX and surface API; and errors are a stronger check that nobody is misusing things.

- I really hope 5.0 won't break anything at all (except maybe build processes)

**Comment by Zac-HD** [comment]
Ooh, we should fix at least some of the things in [our catalogue of style guide violations](https://github.com/HypothesisWorks/hypothesis-python/blob/master/guides/api-style.rst#a-catalogue-of-current-violations):

- remove `average_size` arguments to collections strategies (see also #217 re capped geometric distribution)
- make the `elements` argument to collections strategies required
- make `extra.numpy.arrays` accept a strategy but not a value for `dtype` and `shape` (or vice-versa).  I favor the strategy option, because `just(...)` is trivial (and can be documented inline), but flatmap is relatively painful and would be necessary in most of my usage (see eg pydata/xarray#1972)

I don't think we have time to design a non-class-based stateful API, but these three changes are fairly simple - and what's the point of a style guide if we don't clean up the violations?

**Comment by Zac-HD** [comment]
@DRMacIver, just a quick clarification: are you OK with making things that have *never* worked into errors with less than six months notice?  Taking recent examples: I can understand and live with waiting to make the `elements` argument mandatory, but not for leaving misuse of the settings decorator (eg double-use silently overrides!) as a warning for possibly years when we next take out the old stuff.

-------------

More generally, I'm sure there's good reason for your antipathy to removing recently-deprecated things, and I'd like to know what it is so I can make better decisions.  Something about usage patterns in industry?  For OSS and particularly new users, I tend to think that a clean and consistent API is more important than stability in excess of semver.

**Comment by DRMacIver** [comment]
> @DRMacIver, just a quick clarification: are you OK with making things that have never worked into errors with less than six months notice?

I think case-by-case basis on what "never worked" means.

> Taking recent examples: I can understand and live with waiting to make the elements argument mandatory, but not for leaving misuse of the settings decorator (eg double-use silently overrides!) 

I think I might be OK with a shorter deprecation period where the change that you need to make to adapt to it is literally just delete some code. Do we have any evidence that this is a mistake that people make in the wild? What's the benefit of making it an error over making it a warning?

> @alexwlchan and I will probably need to start over on #1156, but that's OK 😄

Sorry. 

> as a warning for possibly years when we next take out the old stuff.
> Finally, if we document a six-month delay policy, I'd like another chance to remove stuff in Hypothesis 5.0!

Why not just do a major release every six months or so? It's being a lot of work *now* but that's mostly because this is the first one we've really done in earnest in ages, and on the principle of making changes cheap...

**Comment by Zac-HD** [comment]
Hi @HypothesisWorks/hypothesis-python-contributors - we seem to have lost all our momentum towards Hypothesis 4.

Do we actually need to do this now?  Put another way, *what value do our users get from 4.0 that they can't have in 3.x?*

IMO this comes down to:

1. Breaking changes (obviously)
  - which for us means removing deprecated stuff to make the API more consistent
  - much more valuable if we pair it with #1139 and thus automatic reference docs
  - I hereby propose v3.37 (2017-11-12) as the earliest cutoff, meaning a mid-May release for six months grace.  There are significant deprecations leading up to and in that (double-given, health checks) and little for a while afterwards.

2. Marketing!
  - Everyone knows that the *real* purpose of a major release is to get people to use your software, right?
  - We *really, really* need a logo (and related strategy; see #692) if we want this to be effective.
  - Too many major releases makes you look unstable, and as a testing library we want to look conservative and stable (especially to users who might be suspicious of the whole PBT thing), so it's better to delay and do it right later when we have the messaging lined up.
  - We should consider linking this to Rust and/or Ruby announcements

So: if we definitely have a major version launching late this year, I'm inclined to make *that* 4.0 and get all our shiny PR & UX ducks in a row first.

**Comment by Zac-HD** [comment]
Closing this because we've missed basically all the proposed timelines.  The parts we *have* decided on (e.g. deprecation policy) are now documented; for the rest we should open a new issue when someone wants to do a major release and discuss it afresh then.
