### ISSUE TITLE
Examples database keeps changing even when no failures are found

### ISSUE THREAD

**Issue by flyingmutant** [HypothesisWorks/hypothesis#1142]
Is this intended? It makes it hard to version-control the database.

**Comment by Zac-HD** [comment]
Yes, it's intentional - we maintain a set of examples that gives good branch coverage of your function, and this may change if Hypothesis discovers new examples that do not fail.

We should document it better though!

**Comment by flyingmutant** [comment]
Maybe it makes sense to separate the folder in two, one of which will only contain failures, and be suitable for version control?

Having an automatic shared database of all failures happened is an important feature which gives a lot of peace of mind out of the box.

**Comment by Zac-HD** [comment]
They are equally suitable for version control - the coverage entries are used to spread our effort evenly through the code under test, which helps find more bugs.  If you do choose to store the example database in version control, it's worth storing both.

**Comment by flyingmutant** [comment]
The problem is that examples database changes on every test run. If you test the code on every commit, and want to version control the database, that means that every commit from every team member now has to include the examples folder as well. Speaking from experience, people just put the examples database in the `.gitignore` instead, which of course completely defeats the purpose.

To be suitable for version control in a team setting, examples database should change only occasionally. Changing only on new failures discovered sounds as the most practical approach, which is easy to explain to people and gives users an important safety feature of "no failure is ever forgotten".

**Comment by Zac-HD** [comment]
https://hypothesis.readthedocs.io/en/latest/database.html

> You shouldn’t rely on [the example DB] for correctness ... we therefore recommend using the example database locally and possibly persisting it between CI builds, but not tracking it under version control.

We *do not* promise that "no failure is ever forgotten", nor that it's suitable for version control in any setting at all (just that you *can* track it).  

Hypothesis itself has the example directory in `.gitignore` - this doesn't defeat the purpose at all, and indeed it's why we have several [ways to reproduce failures](https://hypothesis.readthedocs.io/en/latest/reproducing.html).

**Comment by flyingmutant** [comment]
I understand that there is no promise of file format compatibility between versions (among other things). To have a guarantee, you have to use `@example` (which does not work for stateful tests, right?), or some other form of explicit manual tracking.

My point of view is that a major feature of Hypothesis is freeing people from many of the chores associated with testing. Automatically keeping track of failures is in line with this vision. Yes, it is a "best effort" approach with no guarantees, but this is exactly the approach Hypothesis takes with testing in general, IMHO.
