### ISSUE TITLE
The current CircleCI API is going away - upgrade to v2

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1145]
In short, we've got to rewrite and move our config file 🙄 

See: [this blog post](https://circleci.com/blog/sunsetting-1-0/), the [general migrations page](https://circleci.com/sunset1-0/), and [specific config docs](https://circleci.com/docs/2.0/migrating-from-1-2/).

**Comment by DRMacIver** [comment]
Orrrr we could just turn it off. I don't think running builds on OSX has ever actually been useful for us.

**Comment by alexwlchan** [comment]
Confession time!

Double check, but I think it’s been broken since I implemented short-circuit builds, and it seemed unimportant so I never got around to fixing or mentioning it. 🙈

**Comment by DRMacIver** [comment]
Though I guess we could consider just running more of our build on OSX rather than Linux to get some spare horsepower. It's typically been a *lot* faster than Travis

**Comment by DRMacIver** [comment]
> Double check, but I think it’s been broken since I implemented short-circuit builds, and it seemed unimportant so I never got around to fixing or mentioning it. 🙈

Are you sure? It seems to be working fine in e.g. https://circleci.com/gh/HypothesisWorks/hypothesis-python/2957

**Comment by alexwlchan** [comment]
I meant checking it, even. It definitely looked broken at one point, but maybe I was just pessimistic?

Re: running more of the build on Circle, IIRC you can’t get the parallelism with Travis that you get on Circle, at least not on the free plan.

**Comment by Zac-HD** [comment]
We should seriously just ask Travis to sponsor us for a high-tier plan (ie all the jobs at once) - I'm sure we gain them enough business to be worth it!

**Comment by Zac-HD** [comment]
Closed by #1286 🎉
