### ISSUE TITLE
The shrinker can get stuck on indexes into lists

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1187]
Rather controversially I was using Hypothesis to test a thing rather than just working on Hypothesis, and I noticed that the stateful testing sometimes shrinks absolutely dreadfully. I believe this issue writ large is the culprit.

If you run the following code:

```python
import hypothesis.strategies as st
from hypothesis import settings, find
from collections import Counter


@st.composite
def list_and_value(draw):
    ls = draw(st.lists(st.integers()))
    v = draw(st.sampled_from(ls))
    return (ls, v)


if __name__ == '__main__':
    c = Counter()
    for i in range(1000):
        ls, v = find(
            list_and_value(), lambda t: t[1] > 0,
            settings=settings(database=None)
        )
        c[len(ls)] += 1
    print(c)
```

You will see something like `Counter({1: 987, 3: 10, 4: 2, 5: 1})`

The issue is that Hypothesis's heuristics for when to delete and lower simultaneously are specialised for length parameters, and it's not able to notice that it would be useful to do that here too, so sometimes you end up drawing an excessively long list. The minimal example here is `([1], 1)`, but sometimes we see things like `([0, 0, 1], 1)` because we're unable to remove the zero. It works *most* of the time (I actually don't know why. I expected this to get stuck much more often) but sometimes it gets stuck.

I'm not formally putting this under #1093, but if anyone wants to work on it before I get around to it (which may or may not be soon), do pipe up and I'd be more than happy to hand it over to you and offer advice.

**Comment by Zac-HD** [comment]
I'm closing this because after four years I don't expect a volunteer to take it on soon - and as we said in #1099:

> At present there is literally no good reason to improve the Hypothesis shrinker except enjoyment and weird aesthetic obsessions: due to the combination of better underlying model and a truly disproportionate amount of invested effort, it is currently so good that everyone else's shrinking looks comedically bad in comparison.
