### ISSUE TITLE
Improve documentation of stateful testing

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1190]
As per discussion in #1189, the documentation of stateful testing is currently a bit of a shambles.

Specific issues I'm aware of:

* [x] autoclass documentation for `GenericStateMachine`
* [x] autoclass documentation for `RuleBasedStateMachine` (but do we actually need this? It doesn't introduce any new members!)
* [x] It's totally unclear why you would ever want to use `GenericStateMachine`
* [ ] `Bundle` is very underdocumented (the docs don't even say it's a strategy!)
* [ ] Better examples
* [ ] More examples. e.g.
    * [ ] Example of `RuleBasedStateMachine` that doesn't use bundles.

There's also the general problem that the documentation is weird because the API is weird, but that's out of scope for this issue.

**Comment by DRMacIver** [comment]
Note that some of this will involve deciding what exactly is and isn't public API in the stateful testing. e.g. see discussion of the new printing methods in #1189.

**Comment by Zac-HD** [comment]
#1205 helps a bit but doesn't close this issue :smile:

**Comment by Zac-HD** [comment]
Per #1785, we should note that using `run_state_machine_as_test` will prevent statistics reporting for that run.  This is because Pytest never sees an item with the data to report.

Perhaps we should deprecate `run_state_machine_as_test` in favor of `@initialize` methods?
