### ISSUE TITLE
Use leading underscore for all internal interfaces

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1193]
[PEP8 has some useful advice about distinguishing public or private code](https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces), including:

> Even with \_\_all\_\_ set appropriately, internal interfaces (packages, modules, classes, functions, attributes or other names) should still be prefixed with a single leading underscore.

(By convention, traversing one prefixed name makes all inner names private too - ie we should rename the `internal` directory `_internal` but don't also need to edit the code.)

We should move or rename private interfaces accordingly, to make accidental reliance on our internals less common.  I would make this a minor release despite the lack of any change to the public API, to give any (mis)users an easier transition.

This is also tagged `docs`, because this would make it practical to use the `flake8-docstrings` settings to check that all public APIs are documented ([`ignore=D1` in `tox.ini`](http://www.pydocstyle.org/en/latest/error_codes.html)).  We can also rely on Sphinx autodoc to document all and only public members of classes and modules, meaning we can ditch the easily-outdated member lists (historically problematic for e.g. settings).  In the limit, we could generate an entire API reference (part of #774) with zero configuration.

**Comment by dchudz** [comment]
It seems to me like this is saying we should do two things:

1. internal modules should be named `_something`, and then we don't have to worry about any `_`s inside those modules
2. any internal stuff defined in public modules should be `_`'d. (And shouldn't be imported elsewhere. If we want that, we should move it to one of the internal modules. Then we're also following the rule that `_`'d stuff is private to the module it's in.)

Is that right?

(Note that I'm just clarifying in case that helps anyone. I'm going on vacation for a couple weeks, so won't be working on this any time soon.)

**Comment by Zac-HD** [comment]
Yes, exactly right.

**Comment by Zac-HD** [comment]
Closing for now in favor of #1250 (`__all__ = []` for private modules).  That should be enough for tools, and we can revisit the issue for users if it seems useful.
