### ISSUE TITLE
RuleBasedStateMachine randomized parameters

### ISSUE THREAD

**Issue by bukzor** [HypothesisWorks/hypothesis#1214]
My datastructure has a 'maxlen' constructor, but I can't see how to vary this value (and search for associated errors) in a RuleBasedStateMachine test. A facility to derive the constructor's arguments from strategies would fill this role nicely. Something like this?

```
def MyQueueStateMachine(RuleBasedStateMachine):
    def __init__(self, maxlen=st.integers(min_value=0)):
        self.queue = myqueue(maxlen=maxlen)
```

**Comment by Zac-HD** [comment]
I *think* the idiomatic way to do this is to have a `rule()` which constructs your queue and adds it to a `Bundle`, which is in turn used by other rules.

@DRMacIver:
- Is this correct?  The docs for Bundle are still pretty sparse.
- Should we support (or have a healthcheck for) `@given` on the \_\_init\_\_ of a stateful test?

**Comment by DRMacIver** [comment]
> Is this correct? The docs for Bundle are still pretty sparse.

Probably not ideal if you only want one instance of the value. Another way is to define a rule that runs only once using `@precondition`, and assign the value in that.

> Should we support (or have a healthcheck for) @given on the __init__ of a stateful test?

We definitely shouldn't support `@given` on the `__init__` of a stateful test. Having a health check that asserts that `@given` is never applied to an `__init__` might be reasonable.

I have been thinking that we should probably add some API level support for e.g. an `@initialize` decorator that works like `@rule` but each initialize is run exactly once before any rules are, but it's been in the long tail of things that might happen at some point. I'll make a tracking ticket for it.

**Comment by Zac-HD** [comment]
Closed as duplicate.
