### ISSUE TITLE
Provide a timezones() strategy based on dateutil.tz

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1245]
I would like Hypothesis to provide `hypothesis.extra.dateutil.timezones()`, based on [`dateutil.tz`](https://dateutil.readthedocs.io), as our recommended timezone strategy.

- The officially recommended source of [`tzinfo` objects](https://docs.python.org/3/library/datetime.html#tzinfo-objects) is `dateutil.tz`
- Hard dependency of Pandas, and preferred by the pydata stack
- Compatible with all the obvious ways to use timezone objects!

Implementation: take the values from `dateutil.zoneinfo.get_zonefile_instance().zones`, sort them according to some ordering\*, and apply `sampled_from`.  Note that this requires `dateutil >= 2.7` (recent); we'll need to either find an older way to get this info or else provide informative errors as well as correct version requirements.

Ordering of timezones for useful shrinking is... tricky - the best we can do is probably a partial ordering by "seems more likely to cause bugs".  For [pytz (here)](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/extra/pytz.py) we sort 'UTC, fixed offsets by abs(offset), variable offsets by name'.

<details>
<summary>Why isn't pytz enough?</summary>

I want to keep `hypothesis.extra.pytz.timezones()` indefinitely, but following [PEP 495](https://www.python.org/dev/peps/pep-0495/) `pytz` has a "weird" interface and is very easy to use incorrectly.

Just go read [*The Fastest Footgun in the West*](https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html) by Paul Ganssle, and you'll have a decent idea.  Hypothesis actually has [special logic](https://github.com/HypothesisWorks/hypothesis/blob/1ae8830483fcb748cae2c708c0d0c1c24b71858a/hypothesis-python/src/hypothesis/searchstrategy/datetime.py#L62-L68) to support `pytz`, while every other source follows Python's standard model.

</details>

**Comment by DRMacIver** [comment]
I certainly have no objections.

I think it would probably make sense to stick to the same ordering as we use for pytz. It's a bit anglocentric (but so is the whole system!), but shrinking by offset from some zero point is a pretty natural default and UTC is basically the only zero point that makes sense.

**Comment by sushobhit27** [comment]
@Zac-HD Can I work on this issue. I have looked over the code and think that I can do it.

**Comment by Zac-HD** [comment]
Hi @sushobhit27 - we're actually about to open a PR from the Pylondinium sprints for this one :cry: 

However, it would be awesome if you'd like to contribute- I suggest starting with #162 or #1317 as good issues to start with.

**Comment by sushobhit27** [comment]
@Zac-HD NP, I would have a look at other issues mentioned by you.
