### ISSUE TITLE
"This should be impossible" error

### ISSUE THREAD

**Issue by bukzor** [HypothesisWorks/hypothesis#1247]
I'm having trouble reproducing this without using the entirety of my codebase, so I'm hoping the debug log is enough to debug, or at least to tell me what further information is necessary.

I'll show both the edits to Hypothesis I've done to "enhance" the log, as well as the log.

https://gist.github.com/bukzor/883fa20679a497ea5aec1b55509e05b8

**Comment by alexwlchan** [comment]
Which version of Hypothesis are you using?

Notably, that _“This should be impossible. If you see this error, please report it as a bug”_ assertion in your diff got expunged from the codebase several months back. PR #1052, released as 3.44.11.

Can you reproduce the error with the latest version?

**Comment by bukzor** [comment]
I assume not! Time to upgrade.

Thanks.
