### ISSUE TITLE
Seed not always printed on failure

### ISSUE THREAD

**Issue by matthijskooijman** [HypothesisWorks/hypothesis#1256]
I'm a bit confused on when the seed is printed and when it is not. I've seen it printed at some moments, but at other times it is unexpectedly missing.

Looking at the code, it seems that the printing happens here:

https://github.com/HypothesisWorks/hypothesis/blob/c877d1d7690c73a793bbaa02c1d9dd62e99aa9d0/hypothesis-python/src/hypothesis/core.py#L1049-L1059

In a case where the seed is not printed, debug printing shows that `state.failed_normally` is True, which suppressed the seed printing.

Digging more, I found that commit 6aadcc02694dfea2aca008e751f367956c5cf64a introduces this `failed_normally` check. Apparently the ide is that for "normal" failures, a reproduction blob is printed for each individual failure, which (I guess) removes the need for printing the seed. However, blobs are not printed in all cases, which (at first sight) leaves you with nothing.

In my case, the blob isn't printed because `can_use_repr` is true, which I guess means that I could just paste the failing test description and put it into an @example decorator (this does not seem [documented](https://hypothesis.readthedocs.io/en/latest/reproducing.html)). Also, I guess the failure database should make sure that a failure is retried on the next run, making it less essential to keep the seed.

Still, I was a bit confused by not (always) seeing the seed after failures. Would it not be more consistent to just always print it (unless it was explicitly set), reverting part of the above linked commit? The only downside of this that I can imagine is that people will assume the seed is the only way to reproduce, and not realize there is a database and you can also use @example...

**Comment by Zac-HD** [comment]
> In my case, the blob isn't printed because can_use_repr is true, which I guess means that I could just paste the failing test description and put it into an `@example` decorator (this does not seem documented). Also, I guess the failure database should make sure that a failure is retried on the next run, making it less essential to keep the seed.

We should document this - possibly adding a TLDR listing the ways to reproduce a failure and the order you should try them in - but I'm not personally inclined to start printing more details than are actually needed.
