### ISSUE TITLE
Add decorator version of `register_type_strategy()`

### ISSUE THREAD

**Issue by matthijskooijman** [HypothesisWorks/hypothesis#1258]
A common pattern (I suppose) is to do:

```python
@composite
def foos(draw):
    ...
    return Foo(...)
register_type_strategy(Foo, foos())
```

E.g. define a custom strateg for some type as a function and the composite decorator, and then, marking it as the default strategy for the type using `register_type_strategy()` function. Having a decorator for this might be a useful addition. E.g.:

```python
@register_type_strategy(Foo)
@composite
def foos(draw):
    ...
    return Foo(...)
```

One caveat is that this must be the first decorator in the list, so it is passed the final function. Also, I'm not sure if overloading the `register_type_strategy()` name here is a good idea (you can detect whether a strategy is passed as a second argument and if not, assume that you're called as a decorator, but that might be fragile). I don't directly have any great ideas for alternative names, though, since the meaning of the decorator is essentially the same as of the original function.

Of course, a decorator only works for strategies defined as a function using the `@composite` decorator, not for strategies directly compose of other strategies. If the `register_type_strategy()` function is modified to return the passed strategy, you could also shorten those using e.g. instead of:

```python
foos = sampled_from(list_of_foos)
register_type_strategy(Foo, foos)
```

you could write:

```python
foos = register_type_strategy(Foo, sampled_from(list_of_foos))
```

Though I'm not entirely sure if that's really much nicer.

**Comment by Zac-HD** [comment]
I think this is better as a user-defined extension:

```python
def composite_register(typ):
    # assert typ not in hypothesis.searchstrategy.types._global_type_lookup  # avoid duplicates
    def inner(func):
        decorated = composite(func)
        register_type_strategy(typ, decorated)
        return decorated
    return inner

# Then use it like this:
@composite_register(Foo)
def foos(draw):
	return Foo(...)
```
