### ISSUE TITLE
Make settings.define_setting a private method

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1269]
By renaming it to have a leading underscore, `_define_setting`.

That will stop it showing up [here](https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings), which should only be listing the settings attributes!

Implementing this change should be very simple, just find-and-replace the name in `_settings.py` and write a small changelog entry.  If you would like to try fixing this issue, feel free to ask me any questions about getting set up, or for help with making the actual fix :smile:

**Comment by grantbachman** [comment]
Hey @Zac-HD I'd be interested in working on this! Looks pretty simple but I want to make sure I follow the guidelines and can build the docs locally to test :)

**Comment by Zac-HD** [comment]
Awesome!  Let me know if you need any help :smile:  
Tips:
- `pip install -r requirements/tools.in` (`.txt` in a virtualenv to get pinned versions), then `pip install -e hypothesis-python`
- `cd hypothesis-python/docs` then `sphinx-build . _build` to make the docs
- If you're on Linux and don't mind automatically downloading some stuff, `make docs` will do everything including creating a reproducible environment to do it in.
- Don't forget to add yourself to the list of contributors in `CONTRIBUTING.rst`, and to write a changelog entry (see `guides/documentation.rst`)
- Have fun!
