### ISSUE TITLE
Problem with test in 3.56.10

### ISSUE THREAD

**Issue by jochym** [HypothesisWorks/hypothesis#1289]
Testing on py2.7 and py3.6 with following report:
```
Falsifying example: test_can_create_a_series_of_any_dtype(data=data(...))
Draw 1: dtype('>M8[ns]')
Draw 2: 0   1970-01-01
dtype: datetime64[ns]

You can reproduce this example by temporarily adding @reproduce_failure('3.56.10', 'AAUBCAEAAAAAAAAAAAAA') as a decorator on your test case
```

**Comment by jochym** [comment]
Seems to be intermittent. Rerunning the same jobs on travis "fixed" the outcome. But still - this seems problematic.

**Comment by Zac-HD** [comment]
It *is* problematic!  Unfortunately I haven't been able to reproduce this - do you have a traceback and/or the exact versions of Numpy and Pandas you were using?

**Comment by DRMacIver** [comment]
This looks like it's probably a bug in the test to me - [pandas doesn't support non-native byte order](https://pandas.pydata.org/pandas-docs/version/0.18/faq.html#byte-ordering-issues), so the test probably shouldn't be trying to create a little-endian dtype. I wonder why we're seeing this so rarely?

**Comment by DRMacIver** [comment]
I think the answer must be that something has changed recently in the pandas end, as we're now seeing this on our build too: https://travis-ci.org/HypothesisWorks/hypothesis/jobs/379586593
