### ISSUE TITLE
Is it possible to run hypothesis based pytests in a Jupyter notebook?

### ISSUE THREAD

**Issue by fkromer** [HypothesisWorks/hypothesis#1293]
I would like to run `hypothesis` tests with `pytest` in a Jupyter notebook? Running `pytest` tests in a notebook is possible with [`ipytest` (examples)](https://github.com/chmp/ipytest#examples). I got `hypothesis` based tests not working in a notebook so far. (It is very probable that I mixed something up :sweat_smile: .) Is it possible at all?

**Comment by DRMacIver** [comment]
It certainly should be! I've not tried it with ipytest, but I've regularly written Hypothesis based tests in Jupyter notebooks and run them by just calling the function. I don't know hat ipytest does beyond that though.

Could you give more details of what you're doing and what goes wrong?

**Comment by fkromer** [comment]
Finally I got it working like follows. But there is probably a better approach.

First cell:
```
%%writefile test.py

import pytest
from hypothesis import given
from hypothesis.strategies import integers

@given(integers())
def test_pass(generated_value):
    assert generated_value == 42
```

Second cell:
```
!pytest test.py
```

**Comment by Zac-HD** [comment]
That works!  I'd also expect the `ipytest` magics to work, and happy to help debug if you want to share details of how that failed.  Otherwise, closing as solved :smile:
