### ISSUE TITLE
Hypothesis badges

### ISSUE THREAD

**Issue by endrebak** [HypothesisWorks/hypothesis#1315]
[![hypothesis tested](https://img.shields.io/badge/hypothesis-tested-brightgreen.svg)](http://hypothesis.readthedocs.io/)

`[![hypothesis tested](https://img.shields.io/badge/hypothesis-tested-brightgreen.svg)](http://hypothesis.readthedocs.io/)`

I don't use them to promote hypothesis really, but to show that my project has been more thoroughly tested than many.

**Comment by Zac-HD** [comment]
Nice! What do you think we should do with this - add it to the docs? (if so, where?) Something else?

And would you like to open a pull request to do it?

**Comment by endrebak** [comment]
I currently just use it like shown above in my READMEs. In the docs, I guess we could encourage people to use it in their hypothesis-tested projects. This would be a win for both afaics.
