### ISSUE TITLE
Improve error for from_type(an_empty_Enum)

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1317]
Currently, we have this code:

https://github.com/HypothesisWorks/hypothesis/blob/0e55a7059f5b38ba48e9b560e2c46856c2c24449/hypothesis-python/src/hypothesis/strategies.py#L1205-L1207

However, this code could be triggered from reasonable use (ie passing an `Enum` instance which does not have any values) - while assertions are disabled if Python is run in `-O` mode.  We - that is, **you** - should replace this assertion with an if-statements and `raise InvalidArgument(...)`.

Finally, we should add a test to [`tests/cover/test_type_lookup.py`](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/tests/cover/test_type_lookup.py) that uses `with pytest.raises(InvalidArgument)` to check that the correct error is raised when we attempt to call `from_type` on an empty enum.

If you would like to work on this issue, comment below and I'll help out in whatever way I can :smile:

**Comment by DRMacIver** [comment]
> However, this code could be triggered from reasonable use 

One thing that might be worth considering is whether it would be better to be consistent with `sampled_from`'s behaviour on empty collections, which is to return a strategy equivalent to `nothing` that never succeeds.

I'm on the fence here and would happily accept either option.

**Comment by Zac-HD** [comment]
> I'm on the fence here and would happily accept either option.

Likewise.  To implement this option, you would just delete the assertion - passing the enum to `sampled_from` will do the rest.

**Comment by juliahou** [comment]
Hello! I'd like to work on this issue if it's still open.

**Comment by Zac-HD** [comment]
Awesome!  This issue will be reserved for you at least through to the end of June - just let me know if you need a hand with anything; otherwise I'll leave you to it until you open a PR I can review :smile:

**Comment by Zac-HD** [comment]
Here's a checklist for anyone who would like to work on this issue:

- Delete the line with the assertion
- Add your name to the list of authors in `CONTRIBUTING.rst`
- Add a test to `./hypothesis-python/tests/cover/test_type_lookup.py` to `assert from_type(EmptyEnum).is_empty`
  (you will need to import the `enum` module and define `class EmptyEnum(enum.Enum): pass` too)
- Create a new file `./hypothesis-python/RELEASE.rst`, with the first line `RELEASE_TYPE: patch` and a short description of the change below using rst syntax for cross-references.
  (full details in guides/documentation.rst, or see docs/changes.rst for examples)

And that's it!  Once reviewed, approved, and merged your change will automatically be released to the world within an hour :tada:

**Comment by whatevergeek** [comment]
DONE: Delete the line with the assertion
DONE: Add your name to the list of authors in CONTRIBUTING.rst
DONE: Add a test to ./hypothesis-python/tests/cover/test_type_lookup.py to assert from_type(EmptyEnum).is_empty
(you will need to import the enum module and define class EmptyEnum(enum.Enum): pass too)
DONE: Create a new file ./hypothesis-python/RELEASE.rst, with the first line RELEASE_TYPE: patch and a short description of the change below using rst syntax for cross-references.
(full details in guides/documentation.rst, or see docs/changes.rst for examples)

IN PROGRESS: Pull Request

**Comment by whatevergeek** [comment]
PR sent
https://github.com/HypothesisWorks/hypothesis/pull/1515

**Comment by Zac-HD** [comment]
Closes by #1515 :tada:
