### ISSUE TITLE
Deprecate the use of settings objects as context managers

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1327]
This API was a bad idea and should be removed, leaving settings to be determined by global state or decorators only.  Using a settings object as a context manager is somewhat ambiguous (should it happen when the test is defined, or executed? certainly not *within* a test...) and just plain unnecessary.

**Comment by Zac-HD** [comment]
I tried just adding `note_deprecation(...)` to `settings.__enter__` in `_settings.py`, and running the tests to see what breaks - the main task of this issue is to mechanically fix (or delete) our tests anywhere we're using this, and write a minor release note to explain to users that they should stop too.

Of our tests: 1115 failed, 743 passed.  Not recommended for new contributors :sob:

**Comment by Zac-HD** [comment]
If you have some time I'd love a review for my open PRs, and after (or before) that this one is all yours.

**Comment by alexwlchan** [comment]
👍

Any particular order, or oldest first?

**Comment by Zac-HD** [comment]
Whatever works for you, but I'd suggest #1295, #1270, #1304, #1282 as a value-for-effort order.  Thanks!

**Comment by alexwlchan** [comment]
I’m going to have a quick look at this.

**Comment by alexwlchan** [comment]
Ah, we use settings as a context manager in `engine.py`, where I think we do want to scope it to within a single `run()` method. That seems to be the root of most of the test breakages,

It’s not immediately obvious to me how we unpick it from there, but it’s been a while since I‘ve had to think about this code…

**Comment by Zac-HD** [comment]
The obvious option to me would be to add a private context manager function `_with_settings(s)`, which does exactly the same thing but isn't public API - the alternative would be to manually pass the object around everywhere, and that gets ugly (and unmaintainable) very quickly..  Then it's just a matter of removing the context manager use from our docs and tests...

**Comment by alexwlchan** [comment]
> Do you still want to do this, or shall I?

I’m doing it. Hopefully at least a WIP PR by the end of the day.
