### ISSUE TITLE
Add CI test to check whether Cargo.toml and Gemfile.lock agree on Helix version

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1337]
Helix (the library we use to bind to Rust from Ruby) has two components: A crate and a rubygem. Each of these has their own version number, but we should always use the same version number on each side.

The version number for our dependency on them is (inextricably) specified in two places - the Cargo.toml and the Gemfile.lock. When these get out of sync we end up with confusing and non-obvious errors in tests like #1322. 

It would be nice to have a test in `whole-repo-tests` which checks for this and fails with a more meaningful error when this happens.

**Comment by sponster-au** [comment]
looking at this
