### ISSUE TITLE
Unsatisfiable when inside a st.lists.  Runs fine on its own.

### ISSUE THREAD

**Issue by spott** [HypothesisWorks/hypothesis#1340]
I have a set of fairly complex `composite` strategies, which culminate in a strategy that generates a specific type.  I call this strategy `sequence_ds`.  This strategy generates examples just fine using the `sequence_ds().example()` function.
 
When I try to generate a list of this strategy (`st.lists(sequence_ds(), min_size=2, max_size=10).example()`), I get an `Unsatisfiable` error.  I have no `assume` statements in any of my code, so I'm not sure what the issue is.

Any ideas how to debug this?

**Comment by Zac-HD** [comment]
`Unsatisfiable` can arise in a few ways that don't involve `assume`, but I can't help much more without seeing the code!  

I would try running as a test with `@given` (which is much better than `.example()` for funding bugs), and if that doesn't work try converting the strategy code from a composite function to a test using the `st.data()` strategy for interactive drawing.
