### ISSUE TITLE
Avoid "impossible" ZeroDivisionError we keep seeing

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1346]
https://github.com/HypothesisWorks/hypothesis/blob/592bc7cd2c642bf273113083457444b4823021c9/hypothesis-python/src/hypothesis/statistics.py#L88-L95

This snippet occasionally leads to problems, when `total_drawtime` is nonzero but `total_runtime` *is* zero, causing test failures [like this one](https://ci.appveyor.com/project/DRMacIver/hypothesis/build/1.0.458/job/hl2d74810901ttf5#L926).  I'm not sure why this happens - it's been observed on Python 2 (without) and Python 3 (with) a monotonic clock, so there might be multiple causes - but the solution is pretty simple.  All you need to do to fix this is to change the first conditional to

```python
if total_drawtime <= 0.0 or total_runtime <= 0.0:
```

Then write up a short changelog (see guides/documentation.rst), add your name to the contributors list (in - and read! - contributing.rst), and open a pull request!  If you have any questions, just let me know and I'd be happy to help out.

**Comment by alexwlchan** [comment]
My inclination would be not to fix this until we have a reproducible test case, or we’re just hiding the error.

Not sure if that disqualifies it for [good-first-issue].

**Comment by Zac-HD** [comment]
It's easy (or at least straightforward) to reproduce by mocking the global clock, but otherwise it only comes up *often* on shared VMs such as free CI where the time is screwy.

Given that the logic is OK and the measurements are weird, I'm OK with just displaying the "we're not sure" value of `~ 0%` when things go wrong - it's at least as accurate as any other number we could display.
