### ISSUE TITLE
Python deployment did not remove RELEASE.rst

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1349]
In c216ddca8155cdb05053bcfe2ac51814447aac4f, which blocks further merges.  @DRMacIver, I think cb84c3ad4dfdecfcf947ccd24bfdee111083645b shouldn't have taken out the `git rm RELEASE.rst`...  

AFAICT ea6bb819143d5c6b4e4c43aa2436a9f70d129872 would be a decent fix.  (and is now in all my open PRs)

**Comment by DRMacIver** [comment]
I agree ea6bb81 looks reasonable. @Zac-HD could you open a PR with just that cherry-picked into it and I'll approve it?
