### ISSUE TITLE
the 3.64.x release has problems on py3.5

### ISSUE THREAD

**Issue by jochym** [HypothesisWorks/hypothesis#1366]
The builds on conda forge for 3.64.x fail internal tests on all platforms for python 3.5. 
Build logs:
Linux: https://circleci.com/gh/jochym/hypothesis-feedstock/284
OSX (3.64.0): https://travis-ci.org/conda-forge/hypothesis-feedstock/jobs/397619120
OSX (3.64.2): https://travis-ci.org/conda-forge/hypothesis-feedstock/jobs/397836319 (queued)
Windows: https://ci.appveyor.com/project/conda-forge/hypothesis-feedstock/build/1.0.223/job/2sen81r9mc9215ni

Is 3.5 still supported?

**Comment by DRMacIver** [comment]
Yup, 3.5 is still supported. Looks like the reason we didn't catch this is that a lot of these tests are in our `py3` folder which cleverly looks like we only run it as part of the coverage tests (which run on 3.6). 😢 

@Zac-HD this failure looks like it's in the new attrs inference work. Can you take a look? I'll take on sorting out the build side of things.

**Comment by Zac-HD** [comment]
Yep, I'll take this one on (the feature is my puppy now...).

From a first glance this looks like a problem getting the return type annotation of a function.  Given the general state of static typing on 3.5, and our best-effort / latest only approach, I might just split it out into a separate test that can be skipped before Python 3.6

**Comment by DRMacIver** [comment]
> Yep, I'll take this one on (the feature is my puppy now...).

I *may* have had the exact same framing in my head when I asked you to look into it, but decided not to voice it. 😉

**Comment by jochym** [comment]
3.65 still has problems on py3.5 on linux and windows. The OSX seems fixed:
Linux: https://circleci.com/gh/conda-forge/hypothesis-feedstock/338
Windows: https://ci.appveyor.com/project/conda-forge/hypothesis-feedstock/build/1.0.225/job/a7xe0qrwxrnc6hc8

**Comment by Zac-HD** [comment]
Which commit are you building?  This fix hasn't made into a release yet, so I'd expect the 3.65.0 tag to keep failing (including on OSX).

**Comment by jochym** [comment]
OK. The scripts are building out of releases. So I'll just keep waiting for the release that builds, and I will keep informing you here (?) of the status.

**Comment by Zac-HD** [comment]
3.65.1 is now out, with the test fixes, and should build.

**Comment by jochym** [comment]
OK. Thanks. I'll report on the results.
