### ISSUE TITLE
py3 tests are only run in coverage job

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1367]
Based on some investigation in response to #1366 it looks like the tests in `tests/py3` are actually only running under coverage, and not under other versions of Python 3. Ideally they should be running on all of our `check-py3x` jobs.

Worse (except in the sense that we seem to have got away with it) is that as far as I can tell the py2 tests aren't running *anywhere*.

**Comment by Zac-HD** [comment]
You might want to check out #863 at the same time, since it seems related.
