### ISSUE TITLE
test_explore_an_arbitrary_language found a bug

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1380]
https://travis-ci.org/HypothesisWorks/hypothesis/jobs/399408345#L1111

Assigning to @DRMacIver, who added this test in #1302.  (:dog::wink:)

**Comment by DRMacIver** [comment]
In fact, this is not an example of flakiness, but of Hypothesis behaving how it's supposed to and occasionaly finding new bugs in the code!

**Comment by alexwlchan** [comment]
🎉
