### ISSUE TITLE
RuleBasedStateMachine doesn't use example on initialize

### ISSUE THREAD

**Issue by pckroon** [HypothesisWorks/hypothesis#1384]
Here's a minimal example that should produce a failing test, but doesn't. Am I simply trying something silly?

```python3
from hypothesis import strategies as st
from hypothesis.stateful import RuleBasedStateMachine, rule, invariant, initialize
from hypothesis import example


class HypoTest(RuleBasedStateMachine):
    @example(i=0)
    @initialize(i=st.sampled_from([-3, -2, -1, 1, 2, 3]))
    def setup(self, i):
        self.i = i

    @rule()
    def f(self):
        pass

    @invariant()
    def do_test(self):
        if not hasattr(self, 'i'):
            return
        assert self.i

testrunner = HypoTest.TestCase
```

**Comment by DRMacIver** [comment]
`@example` doesn't work with Hypothesis's stateful testing at all (and I'm not keen to make it do so - you run into a version of the mutable default argument problem). Would be useful to error or warn on this misuse though!

**Comment by Zac-HD** [comment]
Related to #1300.

**Comment by pckroon** [comment]
Hmmn, ok. Is there any other way to still get the desired result?

**Comment by DRMacIver** [comment]
Depends what the desired result is! There's no way to get something that behaves exactly like `@example` for `@given`, but the output from a RuleBasedStateMachine failure is (usually, though probably not in your case because NetworkX doesn't have good reprs for values 😞) you can run, and you can just instantiate the state machine object and call its methods in a test.

Beyond that, depends what you're trying to do. It's not obvious to me what the semantics of `@example` on a `@rule` even should be.

**Comment by pckroon** [comment]
That's fair. What I think I want/expect is that it runs at least with that input for initialize (or any rule) as well. I don't know about the other rules it runs. There's currently no way to specify those is there? For me it would be ok if it's not completely reproducible, but at least tries a few things with my provided example.

Can I give `@example`s to `invariant`s?

**Comment by DRMacIver** [comment]
> For me it would be ok if it's not completely reproducible, but at least tries a few things with my provided example.

The easiest thing to do here is probably just to specify those arguments you want tried in a `sampled_from` as part of the strategies that feed the rule TBH. That + writing specific tests that just construct and call some methods on your state machine probably cover most of the space of things that `@example` would do.

> Can I give @examples to invariants?

No, invariants don't take any arguments, and `@example` .

**Comment by pckroon** [comment]
Cheers. I can work with that :)
