### ISSUE TITLE
Measuring coverage of custom hypothesis strategies

### ISSUE THREAD

**Issue by pckroon** [HypothesisWorks/hypothesis#1392]
Hi all,

I'm back again with more questions. I made a strategy for generating NetworkX graphs (https://github.com/pckroon/hypothesis-networkx) but I'm having issues testing it.

The tests (eventually) pass, but the measured coverage points to 47 missed lines (all the code in the actual strategy). I have the feeling this is a side effect of hypothesis using coverage, or otherwise obfuscating what code is actually run. Any advice?

**Comment by Zac-HD** [comment]
This could be related to #1085? Pinging @DRMacIver who might have a better idea of what's happening.

**Comment by Zac-HD** [comment]
Nope, that didn't fix it.  Your guesses sound reasonable but I have no solid ideas.

**Comment by pckroon** [comment]
I can confirm 3.71.3 resolves this issue. Thanks!
