### ISSUE TITLE
Performance degradation from 3.30.0 to 3.66.1 due to many "invalid examples"

### ISSUE THREAD

**Issue by pckroon** [HypothesisWorks/hypothesis#1393]
Hi all,

I wrote a strategy for generating NetworkX graphs (https://github.com/pckroon/hypothesis-networkx), but testing that code is super slow. Previous issues here made me look at some older versions of hypothesis, and 3.30.0 in particular. It seems that the current version produces many many more invalid examples for some reason. Here's the statistics for both versions I tried:

For 3.66.1:
```bash
> pytest --hypothesis-show-statistics
========================================== test session starts ==========================================
platform linux -- Python 3.7.0, pytest-3.6.2, py-1.5.4, pluggy-0.6.0
rootdir: /home/peterkroon/python/hypothesis-networkx, inifile:
plugins: cov-2.5.1, hypothesis-3.66.1
collected 1 item                                                                                        

tests/test_graph_builder.py .                                                                     [100%]
========================================= Hypothesis Statistics =========================================

tests/test_graph_builder.py::test_graph_builder:

  - 50 passing examples, 0 failing examples, 558 invalid examples
  - Typical runtimes: 2-206 ms
  - Fraction of time spent in data generation: ~ 99%
  - Stopped because settings.max_examples=50

====================================== 1 passed in 100.56 seconds =======================================


```

And for 3.30.0:
```
> pytest --hypothesis-show-statistics
========================================== test session starts ==========================================
platform linux -- Python 3.7.0, pytest-3.6.2, py-1.5.4, pluggy-0.6.0
rootdir: /home/peterkroon/python/hypothesis-networkx, inifile:
plugins: cov-2.5.1, hypothesis-3.30.0
collected 1 item                                                                                        

tests/test_graph_builder.py .                                                                     [100%]
========================================= Hypothesis Statistics =========================================

tests/test_graph_builder.py::test_graph_builder:

  - 50 passing examples, 0 failing examples, 16 invalid examples
  - Typical runtimes: 3-149 ms
  - Stopped because settings.max_examples=50

=========================================== warnings summary ============================================
tests/test_graph_builder.py::test_graph_builder
  hypothesis_temporary_module_48747864dcb868d4a70431dab33048ce95993982:25: HypothesisDeprecationWarning: Test took 846.48ms to run. In future the default deadline setting will be 200ms, which will make this an error. You can set deadline to an explicit value of e.g. 900 to turn tests slower than this into an error, or you can set it to None to disable this check entirely.

-- Docs: http://doc.pytest.org/en/latest/warnings.html
================================= 1 passed, 1 warnings in 38.02 seconds =================================

```

**Comment by DRMacIver** [comment]
>  3.30.0 in particular

Could you elaborate on why 3.30.0 in particular? Is this the last release with good behaviour or just something you happened to try?

There are quite a lot of releases between the two. My guess would be https://hypothesis.readthedocs.io/en/latest/changes.html#v3-51-0 is the most likely culprit, but it could be almost anything.

**Comment by pckroon** [comment]
I picked it at semi-random based on previously reported performance issues (those mostly dealt with coverage).

I tried with a few versions now. For 250 passing examples, every version produces this many invalid examples. If you have any more suspect versions I'm happy to try. Here I bisected untill less than half of the examples were invalid.
```
3.66.1 - 536
3.51.0 - 609
3.50.0 - 710
3.45.0 - 577
3.42.0 - 322
3.41.0 - 241
3.40.0 - 174
3.30.0 - 97
```

I'm a little confused as to what's causing this, since I don't have any `assume` or `filter` in my code. I am generating quite some lists that have to have unique elements.

**Comment by Zac-HD** [comment]
> I'm a little confused as to what's causing this, since I don't have any assume or filter in my code. I am generating quite some lists that have to have unique elements.

The implementation for unique lists can use an internal equivalent of `assume()`, so that's probably the immediate cause.  Tracking down the root cause (ie what changes increased the number of invalid examples) is likely to be low priority.

In general, I'd suggest using `unique` as lightly as possible - for example, you could just make a list of node keys and then draw the node data only as you add each node to the graph (reducing the cost of invalid attempts).  

More importantly, you could make the "unique edges" list much more efficient by maintaining a list of nodes that could have an edge added, drawing one, and sampling the other end of the edge from the nodes not already connected to it.  This would entirely avoid the filtering effect for edges, and you may be drawing large numbers of them!

**Comment by pckroon** [comment]
Hi @Zac-HD,

Genius. That solved it. Your solution even allows me to enable all health checks again. Thanks a lot!

```
============================= test session starts ==============================
platform linux -- Python 3.7.0, pytest-3.6.2, py-1.5.4, pluggy-0.6.0
rootdir: /home/peterkroon/python/hypothesis-networkx, inifile:
plugins: cov-2.5.1, hypothesis-3.66.20
collected 4 items                                                              

tests/test_errors.py ...                                                 [ 75%]
tests/test_graph_builder.py .                                            [100%]
============================ Hypothesis Statistics =============================

tests/test_graph_builder.py::test_graph_builder:

  - 250 passing examples, 0 failing examples, 370 invalid examples
  - Typical runtimes: 1-12 ms
  - Fraction of time spent in data generation: ~ 85%
  - Stopped because settings.max_examples=250
```

**Comment by Zac-HD** [comment]
Fantastic! Glad I could help :smile:
