### ISSUE TITLE
one_of(none(), text()) provides no example as None

### ISSUE THREAD

**Issue by shuoli84** [HypothesisWorks/hypothesis#1396]
```python
from hypothesis import strategies
x = strategies.none() | strategies.text()
for i in range(1000):
    if x.example() is None:
        print("Got None")
```

No matter how I tweak the range(xxx), it never prints "Got None".

**Comment by shuoli84** [comment]
Though, (strategies.text() | strategies.none()).example() works.

**Comment by Zac-HD** [comment]
This is because `.example()` does not give a representative distribution of outputs - it aims to produce diverse examples that are simple, but not *too* simple, and therefore excludes the absolute minimal case (`None` in your first example, or the empty string in the second).

**Comment by shuoli84** [comment]
@Zac-HD Got it. Thanks.
