### ISSUE TITLE
note should print when verbosity is set to at least verbose 

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1410]
We have the `note` function that prints its argument only on the final example, but actually it should probably print it for *every* example when `verbosity >= Verbosity.verbose`, so that people can actually see the tests as they run.

**Comment by xynazog** [comment]
Hey @DRMacIver can I work on this issue?

**Comment by Zac-HD** [comment]
@xynazog - this issue is all yours for the next week (our standard reservation time).  Tips: read `CONTRIBUTING.rst` and the `guides/` files, and feel free to ask if you have *any* trouble at all or just want a hand.  We're here to help!
