### ISSUE TITLE
Compulsory `draw` argument of decorated composite strategies causes Pylint to complain

### ISSUE THREAD

**Issue by willfrey** [HypothesisWorks/hypothesis#1420]
The first `draw` argument to a strategy decorated with `@hypothesis.strategies.composite` triggers a  `no-value-for-parameter` Pylint error. This is because the decorator automagically takes care of the compulsory `draw` argument but Pylint doesn't understand this.

Is there any way to tell Pylint what's going on here? Perhaps the `composite` decorator could dig into the internals and alter the signature so that `astroid` picks it up and Pylint doesn't complain?

Thank you!

**Comment by Zac-HD** [comment]
Unfortunately there's nothing we can do - the upstream issue is PyCQA/pylint#259.

**Comment by GiorgioBalestrieri** [comment]
silly/potentially dangerous proposal: what about passing a default arguement?

```python
@hypothesis.strategies.composite
def foo(draw=None) -> hypothesis.strategies.SearchStrategy[Bar]:
    ...
```

**Comment by DRMacIver** [comment]
> silly/potentially dangerous proposal: what about passing a default arguement?

The problem with this is that functions passed to `composite` can take other arguments after the call to `draw`, which need not have defaults.

**Comment by GiorgioBalestrieri** [comment]
right, I also suspect that mypy would complain seeing that `None` is used as a callable (since we use `draw(...)`.
