### ISSUE TITLE
integers(min_value=0) shrinks very slowly

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1452]
I've been investigating a lot of test timeouts recently and these seem to be the source of a lot of them.

The root of the problem is the `geometric` helper in conjecture utils, which ends up mapping quite complicated values to quite simple integers. We should change that format, and generally avoid things that look like the `geometric` helper.

(But not yet, I need to get this evaluation done before we change any formats)

**Comment by Zac-HD** [comment]
*Potentially* related to #909, #1212, and #1387.
