### ISSUE TITLE
Strange behavior of the floats strategy with allow_infinite and min_value or max_value

### ISSUE THREAD

**Issue by Hendrikto** [HypothesisWorks/hypothesis#1476]
When using `allow_infinity` in conjunction with `min_value` or `max_value`, it does not work correctly.

Repro:

```
from hypothesis import given
from hypothesis.strategies import floats 

inf = float("inf")


@given(floats(allow_infinity=False, min_value=-1))
def repro_min(value):
	assert value != inf


@given(floats(allow_infinity=False, max_value=1))
def repro_max(value):
	assert value != -inf


def run(f):
	try:
		f()
	except:
		pass


if __name__ == "__main__":
	run(repro_min)
	run(repro_max)
```

Output:

```
Falsifying example: repro_min(value=inf)
Falsifying example: repro_max(value=-inf)
```

In the [documentation](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.floats) it says

> If both min_value and max_value are not None, it is an error to enable allow_infinity

but I am not using both, just one at a time.

**Comment by alexwlchan** [comment]
I can reproduce this with 3.66.30; investigating.

@Hendrikto, thanks for the report! You get an extra gold star for providing a repro script without using `.example()`.

**Comment by alexwlchan** [comment]
Some version bisecting suggests this bug has been around since Hypothesis 3.0, but didn't affect 2.0.

**Comment by alexwlchan** [comment]
@Hendrikto I’ve got a pull request for this (#1477), but I’m going to hold it until the end of the week – David is doing some shrinker work for a deadline, and I don’t want to merge anything that might interfere with his experiments.

**Comment by Hendrikto** [comment]
Great, thank you.

Workaround for reference: `assume(not math.isinf(value))`
