### ISSUE TITLE
"You can reproduce this example..." doesn't respect Verbosity.quiet

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1486]
Since 3.44.0 we have the message "You can reproduce this example by temporarily adding `@reproduce_failure(...)" for failing tests, which is nice.

What's less nice is that it shows up even if you have `verbosity=Verbosity.quiet` in your settings, but this should suppress all output from Hypothesis.

`Verbosity.quiet` is [supposed to be enforced by report](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/reporting.py#L72) so my guess is that we're running this line outside of the current settings for the test.

**Comment by Cameron-JM** [comment]
Happy to have a look at this.

**Comment by Cameron-JM** [comment]
PR submitted.
