### ISSUE TITLE
from_regex() Strategy Generates Unexpected Newline

### ISSUE THREAD

**Issue by kidomine** [HypothesisWorks/hypothesis#1487]
Using from_regex() to generate a set of examples, I keep randomly obtaining newlines.<br>
Below is a simple example to reproduce. I added single quotes to show the presence of a newline character:
```python
expr = '^[A-Za-z0-9_\-\.]+$'
for n in range(0, 5):
    sample = from_regex(expr).example()
    print('%d %d \'%s\'' % (n, len(sample), sample))
```

Sample output (notice items [0] and [1]:
```
0 13 '-Z0-G..-F--l
'
1 15 '-.Y.Y-.S0-n-e-
'
2 7 '-...JJ0'
3 4 '-.c5'
4 9 '-OyH00g.N'
```

Based on the expression, there should be no newlines in the result.

Environment:
```
Python 3.6
hypothesis 3.45.1
```

Thanks!

**Comment by DRMacIver** [comment]
This is because `$` matches either the end of the string or right before a newline, so adding a single `\n` to the end of the string still results in a match for `$`. If you want to match only the end of the string you need `\Z`.

e.g.

```pycon
import re
>>> re.match("^foo$", "foo\n")                                                                                                                                                                                                           
<_sre.SRE_Match object; span=(0, 3), match='foo'>
```
