### ISSUE TITLE
Flaky test: test_large_data_will_fail_a_health_check

### ISSUE THREAD

**Issue by felixonmars** [HypothesisWorks/hypothesis#1492]
```
You can add @seed(338412295970389942002041176490929560425) to this test to reproduce this failure.
...
=================================== FAILURES ===================================
___________________ test_large_data_will_fail_a_health_check ___________________
[gw14] linux2 -- Python 2.7.15 /usr/bin/python2
Traceback (most recent call last):
  File "/build/python-hypothesis/src/hypothesis-3.68.0-py2/hypothesis-python/tests/cover/test_health_checks.py", line 127, in test_large_data_will_fail_a_health_check
    test()
  File "/usr/lib/python2.7/site-packages/_pytest/python_api.py", line 667, in __exit__
    fail(self.message)
  File "/usr/lib/python2.7/site-packages/_pytest/outcomes.py", line 97, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE <class 'hypothesis.errors.FailedHealthCheck'>
===Flaky Test Report===
```

A simple retry passed it, so I assume it's a flaky test.

**Comment by Zalathar** [comment]
I was able to reproduce this, or something like it, by running just this one test repeatedly in a loop:

```sh
while pytest tests/cover/test_health_checks.py -k large_data ; do : ; done
```

(This typically fails within single-digit minutes on my laptop.)

After setting `Verbosity.debug` and manually adding some additional debug statements, it appears that the test occasionally manages to hit 10 valid draws (to turn off these health checks) before it hits 20 overrun draws (to trigger the health check).

**Comment by Zalathar** [comment]
Oh, it looks like the `lists` strategy is using `biased_coin`, so the first byte in the buffer can be anything, and the tree has no idea that most of those values end up producing the same two results.
