### ISSUE TITLE
CONTRIBUTING.rst has outdated references to the Makefile-based build system

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#1501]
I noticed that the build instructions in [CONTRIBUTING.rst](https://github.com/HypothesisWorks/hypothesis/blob/cdfc98e5e8f6d342bb22e343b39cf796ea037bad/CONTRIBUTING.rst) refer to the Makefile-based build system, not the new system introduced in #1227.

I was originally planning to submit a quick PR to fix this, but soon found that it was more subtle than simply replacing `make` with `./build.sh`. So it could use some attention from someone who knows more about the build system than I do.

**Comment by alexwlchan** [comment]
>  was originally planning to submit a quick PR to fix this, but soon found that it was more subtle than simply replacing `make` with `./build.sh`.

I'd have expected that to work, so apparently I don't know the build system as well as I thought!

**Comment by DRMacIver** [comment]
> I'd have expected that to work, so apparently I don't know the build system as well as I thought!

Uh, same TBH. Actually I'd have expected all of the make based instructions to still work as we have a makefile that just passes to `build.sh`. Maybe some of the tasks have been renamed or otherwise bitrotted?
