### ISSUE TITLE
Run bandit - PyQCA's security linter- in CI

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1511]
*Note: someone will need to implement #1512 before this can be added.*

@tleeuwenburg gave [a great talk this afternoon on security tools](https://www.youtube.com/watch?v=Wa2pgDihWaw&index=85&list=PLs4CJRBY5F1KrUr7z_2mur2QdAKXyh-k3) which we should be using.  We already use Pyup and generally handle dependencies well so I don't think we need `safety`.

We should run [`bandit`](https://pypi.org/project/bandit/) in CI though!  Based on some quick experiments, I think the following call is appropriate:

    bandit --skip B101,B102,B110,B303,B311 --recursive hypothesis-python/src/

This would actually be run via a new test in `./whole-repo-tests/test_security.py`; see the other files in that directory for examples of how to call a tool that can be installed with `pip`!

**Comment by alexwlchan** [comment]
FWIW, I gave a lightning talk about Bandit at CamPUG a year or so ago, and David ran Bandit against Hypothesis as I was speaking!

I think there were just two uses of `eval()`, and we thought they were both okay, but more checks can’t hurt.

**Comment by Zac-HD** [comment]
https://github.com/HypothesisWorks/hypothesis/blob/026fa3598e10be651178c035272c1016a329ad45/hypothesis-python/src/hypothesis/internal/charmap.py#L62

It now also points out that we're using `pickle`, and this is... not ideal, even for data that (we think!) we wrote.  Since it's a dict of a few strings (category names) to n-tuples of two-tuples of integers, we could easily use json instead and tuplize it manually (we only use tuples to ensure there's no accidental mutation, but IMO it's worth continuing).

The major advantage is really that we run new checks automatically when they're released!

**Comment by Zac-HD** [comment]
And FWIW I think our use of `eval`, `assert`, `except \w+: pass`, `random`, and `md5` (for function digests) are all fine too, hence the ignore list :smile:
