### ISSUE TITLE
PyCon Australia 2018 Sprints!

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1513]
Hello to everyone at the sprints!  This issue is the place to get started, comment to claim an issue (please talk to me first), and so on.  Thanks for helping out!

The "what is Hypothesis" pack: [my talk](https://www.youtube.com/watch?v=U_KhEi2vRT8) if you like videos, [the docs](https://hypothesis.readthedocs.io/) as a general overview, and [these quick excercises](https://github.com/Zac-HD/hypothesis-workshop) to try it out.

All of the following are valued contributions: reading docs or trying to use hypothesis and telling me what you found confusing; adding Hypothesis tests to other open-source projects (e.g. Pandas, dateutil, Xarray, etc - ask me!); new documentation or blog posts or artwork; and of course traditional code whether bugfixes or new features!

General checklist:

1. Talk to Zac about what you want to do - I can help you find the right issue ([start here](https://github.com/HypothesisWorks/hypothesis/labels/good%20first%20issue)) or other way to contribute :smile: 
2. (optional): read [`CONTRIBUTING.rst`](https://github.com/HypothesisWorks/hypothesis/blob/master/CONTRIBUTING.rst) and check what's in the [`guides/`](https://github.com/HypothesisWorks/hypothesis/tree/master/guides) directory for tips.
3. Comment below so people don't work on the same issue by accident!
4. Do the thing :snake: 
5. Open a PR :tada:

**Comment by Zac-HD** [comment]
reserved

**Comment by whatevergeek** [comment]
adding here as @Zac-HD  advised...
i'll be helping on the following issue one my machine is setup:
https://github.com/HypothesisWorks/hypothesis/issues/1317

**Comment by vidyarani-dg** [comment]
I am working on "replace pickle with json" issue 
#1512

**Comment by tkcranny** [comment]
I'll be helping on #1115 – "Consider adding a simple subsets / subsequences strategy".

**Comment by BexDunn** [comment]
I'm having a look at #1238 :)

**Comment by garyd203** [comment]
I will have a look at #356 (capture logging)

**Comment by whatevergeek** [comment]
PR sent for issue #1317 

https://github.com/HypothesisWorks/hypothesis/pull/1515

**Comment by Cameron-JM** [comment]
Having a look at #1486

**Comment by banool** [comment]
Gonna take a geez at #848.

**Comment by 00willo** [comment]
Going to look at #1383

**Comment by whatevergeek** [comment]
any quick patch that can be done in around 1.5hrs? 
![image](https://user-images.githubusercontent.com/7351683/44640665-522ce600-aa06-11e8-9cb2-eee649918b8f.png)

**Comment by whatevergeek** [comment]
Is this still a problem?
https://github.com/HypothesisWorks/hypothesis/issues/1493

I'm able to setup and debug in Visual Studio 2017.
I can try check VS Code if it's still an issue there.

**Comment by 00willo** [comment]
Working on #1311

**Comment by whatevergeek** [comment]
Please don't close the issue. 
I'm able to reproduce it in Visual Studio 2017.
I'm able to confirm the following:

- Debugging using custom decorator works
- Debugging using @given doesn't work. It runs, but doesn't stop on breakpoint.

I'll try to investigate further.

**Comment by nbgl** [comment]
I've claimed #840.

**Comment by pazzarpj** [comment]
I've claimed #847

**Comment by massey101** [comment]
Looking at #1223

**Comment by 00willo** [comment]
Also, working on #1520

**Comment by 00willo** [comment]
@Zac-HD I've got a branch ready to make a PR. I created the `RELEASE` file and updated `CONTRIBUTING.rst`.  If you wanted to check out the branch it's https://github.com/00willo/hypothesis/tree/improve-setup.py . If that looks all good, am I good to make a PR?

**Comment by Zac-HD** [comment]
@00willo - looks great!  I'd use the following patch note, but with that it's time to open a PR :tada:

```
This patch improves the packaging of the Python package by adding
``LICENSE.txt`` to the sdist (:issue:`1311`), clarifying the minimum
supported versions of :pypi:`pytz` and :pypi:`dateutil <python-dateutil>`
(:issue:`1383`), and adds keywords to the metadate (:issue:`1520`).

Thanks to ...
```

**Comment by 00willo** [comment]
Sweet, I'll update and submit the PR in the next few mins

**Comment by 00willo** [comment]
@Zac-HD Ah, sorry, I just realised that my branch is behind upstream master, do your merge checks handle that automagically in the PR process?

**Comment by Zac-HD** [comment]
Yep, should all be fine - it tests the result of merging your branch into master.

**Comment by massey101** [comment]
Looking at #1223

**Comment by CuriousLearner** [comment]
PR up: https://github.com/HypothesisWorks/hypothesis/pull/1536 💯  🎉

**Comment by garyd203** [comment]
Looking at #1085

**Comment by sponster-au** [comment]
I'm looking at #1337

**Comment by vidyarani-dg** [comment]
PR #1522 up for review

**Comment by 00willo** [comment]
I worked out how to run invoke the various tests locally.  I'll drop a comment in the documentation issue.

**Comment by Zac-HD** [comment]
> PR #1522 up for review

Approved!  I'll start merging stuff after 6pm ish, to avoid CI conflicts for those still pushing changes :smile:

**Comment by pazzarpj** [comment]
I'm not claiming #847 anymore. It's most likely a maintainer level issue

**Comment by Zac-HD** [comment]
Thanks so much everyone for working on Hypothesis at the sprints - I had a great time and hope you did too.  It's also been fantastic for the project - **nine releases so far**, another five expected in the near future, and other important contributions from better testing to gorgeous artwork.

From here on, we're back in normal development mode - so while this issue will be closed, you can `@`-mention me and I'll help out if I can.

:tada: :snake: :heart_eyes:
