### ISSUE TITLE
Guarantee is_empty() for zero-length sequence strategies

### ISSUE THREAD

**Issue by tkcranny** [HypothesisWorks/hypothesis#1517]
I've run into an unexpected case where a (list) sequence strategy with the `max_size` constraint set to zero returns `True` for the `.is_empty` flag:

```python
def test_sequence_is_empty():
    strat = st.lists(st.none(), max_size=0)
    assert strat.is_empty
```

**Comment by Zac-HD** [comment]
`.is_empty` will *always* be False if the strategy can generate values, and will *usually* be True (but might still be False) if it cannot.  This is basically a performance optimization, which sometimes allows us to give nicer error messages.

However, in this case the strategy `lists(none(), max_size=0)` can validly generate `[]` - so the *strategy* is not empty (even though the list it generates is).
