### ISSUE TITLE
Check for existing breakpoints when asserting absent sys.gettrace

### ISSUE THREAD

**Issue by tkcranny** [HypothesisWorks/hypothesis#1518]
While developing a new strategy for hypothesis, I've run into the case where the code can't be debugged, at least by simply running pytest in a debugger. This is due to an `assert` in the `conftest` file:

https://github.com/HypothesisWorks/hypothesis/blob/026fa3598e10be651178c035272c1016a329ad45/hypothesis-python/tests/conftest.py#L80-L83

Personally I'm not sure on the meanings behind its existence and operation, but via a chat with @Zac-HD, it came up that if the (coverage) tests have a breakpoint, then they should allow the tests to proceed.

**Comment by Zac-HD** [comment]
The idea here is that we are testing that there is no trace function *unless* we are running everything under coverage in CI, to check that the internal use of coverage metrics isn't leaking.

As a developer experience thing, we should avoid raising AssertionError if an explicit trace function has been set by e.g. `pdb`.

**Comment by Zac-HD** [comment]
```python
# This condition is to allow contributors to run our test suite under a
# debugger, without giving up the check for a leaky coverage system in CI.
IN_LOCAL_DEBUGGER = all([
    sys.gettrace() is not None,  # probably needs to specify that it's not coverage either
    os.environ.get('CI') != 'true',  # We're never using a debugger in CI!
])

if not (IN_COVERAGE_TESTS or IN_LOCAL_DEBUGGER):
```
