### ISSUE TITLE
New Hypothesis Dragonfly branding

### ISSUE THREAD

**Issue by libbyberrie** [HypothesisWorks/hypothesis#1519]
:wave: 
@Zac-HD 
I have volunteered myself to create some new branding for hypothesis as the current 'limited edition' branding is not Hypothesis' intellectual property. I've created a couple of sketches of a dragonfly that might work and am beginning to do some rough vectors of them for use. Please provide feedback if you have any! I only have a few hours i can dedicate to it today during the sprint so hopefully i can get something completed by then. If not i'll be working on it off-and-on probably for the net week. 
Below are some preliminary sketches: 

![img_2174](https://user-images.githubusercontent.com/6201161/44640158-64f1eb80-aa03-11e8-8747-7d05c4b6531c.JPG)

Thanks in advance for your input!

**Comment by Zac-HD** [comment]
Thanks so much @libbyberrie - really exciting to have some lovely art for Hypothesis :sparkling_heart: :dragon::bug:

CC @HypothesisWorks/contributors; comments welcome especially from @DRMacIver.  I'm fairly set on replacing the circle with *something* though, even if we replace that in turn eventually as part of a larger brand overhaul.  I'm also pretty keen on sticking with the dragonfly concept, since it's quite distinct from the BSD dragonfly and we're not using it in a name.

**Comment by libbyberrie** [comment]
Hey Zac - No problem! 😄 
Can you link me to the BSD dragonfly you're referencing so I can make sure the branding remains distinct? 
I would also be interested in getting feedback on general style guides -- colours or fonts you would like me to stick to. I'm currently using a combination of #44425F and #A3E9FF for the main dragonfly (see attached preview)
Thanks :) 

![image](https://user-images.githubusercontent.com/6201161/44640960-05e2a580-aa08-11e8-817f-4ff41951b7c5.png)

**Comment by libbyberrie** [comment]
Flats are in. need to add some cel-like detail shading to add more definition to the 'tail'* cause at the moment the segments looks a little messy. 
![image](https://user-images.githubusercontent.com/6201161/44641421-3592ad00-aa0a-11e8-83e6-5df2acfe5ecb.png)

*Apparently it's called an intersegmental annulus

**Comment by Zac-HD** [comment]
https://www.dragonflybsd.org/ has ![this](https://www.dragonflybsd.org/images/small_logo.png)

As to brand and colour guidelines, we don't have any!  I suggest creating 2-3 options for consideration by @DRMacIver and myself :smile:

**Comment by libbyberrie** [comment]
![image](https://user-images.githubusercontent.com/6201161/44643491-11d46480-aa14-11e8-977d-1ecc56ceb7c9.png)
🎉 I think it's pretty much there! I was tossing up adding details to the wings but i think that may be overkill. 
I'll work on the text/colour styles now but i doubt i'll get that done before the end of my time in Sydney. Do you guys want the SVGs now?

**Comment by libbyberrie** [comment]
What would be the best way to deliver an SVG to people? Gitub doesn't support SVg uploads in comments. In the meantime, here's a PNG.
I will be heading home in 20 mins so i'll leave it there for now. I'd love to hear feedback on what colours people would like. Are we set on the blue?

![hypothesis-dragonfly](https://user-images.githubusercontent.com/6201161/44644587-ff5c2a00-aa17-11e8-898e-3602b75c5a61.png)

**Comment by DRMacIver** [comment]
These are cute! I'd be happy to stick with the blue, but if you've got other colour schemes in mind I'd be up for seeing them.

**Comment by Zac-HD** [comment]
Same here - I love it, but would also love to see some colour options like e.g. a darker blue body and green legs?  Not a visual artist though :blush:

**Comment by pjdelport** [comment]
This looks pretty awesome! :)

**Comment by libbyberrie** [comment]
Hello! Attached are a couple more colour experiments for the dragonfly. I am also looking into font branding for you now. I think for simplicity we should stick with the base body font (Lato) but we can incorporate a google font pretty easily for h1-h3s. The attached screenshot is a decent suggestion: [M PLUS Rounded 1c](https://fonts.google.com/specimen/M+PLUS+Rounded+1c)

![screen shot 2018-08-29 at 10 01 19 pm](https://user-images.githubusercontent.com/6201161/44786540-d08cb200-abd7-11e8-8d7c-6554bf563576.png)
![screen shot 2018-08-29 at 9 33 56 pm](https://user-images.githubusercontent.com/6201161/44786549-d71b2980-abd7-11e8-92c8-48c63518b2f0.png)
![screen shot 2018-08-29 at 10 07 09 pm](https://user-images.githubusercontent.com/6201161/44786592-f6b25200-abd7-11e8-8459-d008aa91b29c.png)
![screen shot 2018-08-29 at 10 07 17 pm](https://user-images.githubusercontent.com/6201161/44786599-fc0f9c80-abd7-11e8-97f5-43dcf7b43b83.png)

**Comment by Zac-HD** [comment]
@libbyberrie these look fantastic!  I (and everyone I've shown them to) especially love the shading on the last example, though opinions on the colours of the purple and yellow dragonflies are mixed.  Further ideas:

- do a version of the original color scheme with two changes: body shading similar to the last, and the wings with a thin dark outline for visibility on stickers and other white backgrounds?
- ~~shamelessly rip off~~ take inspiration from the [Beeware Pride](https://twitter.com/pybeeware/status/955552735260172294) stickers.  Rainbow wings maybe?

Finally, so we can calibrate our expectations: how much would you like to do for Hypothesis' branding?  You've drawn some beautiful stuff and we're now talking about fonts too - should we also be thinking about a website touchup, varieties of swag (e.g. I'd love the T-shirt...), etc?  No pressure intended at all but knowing the rough scope would be great :heart_eyes:

**Comment by touilleMan** [comment]
Great work @libbyberrie !

I really love the last one (as @Zac-HD said, shading effect make it sooo cool ^^)

> varieties of swag (e.g. I'd love the T-shirt...)

Need :laughing:

**Comment by Zac-HD** [comment]
We would be delighted by whatever and whenever you want to contribute!  Personally I'm more excited about the art than anything else, and I don't think we have anyone offering to do a website overhaul earlier anyway 😄 

And I'm super excited for pin/patch/sticker/shirt/other amazing ideas!

**Comment by libbyberrie** [comment]
Hello~
Here is a modified version of the first dragonfly, the gradient has been deepened and I also added a small outline on the top of the wing. I had tried outlining the whole wing but when zooming out, as the wings are transparent it just looked too cluttered when it got to smaller sizes. 
And here is a potential rainbow wing design also!

![image](https://user-images.githubusercontent.com/6201161/44953411-86a61380-aed8-11e8-8105-37fe13f355b2.png)

**Comment by DRMacIver** [comment]
👋 Hi just want to say that I'm sorry I've not been more involved with these discussions. I'm super-excided by these @libbyberrie (and very grateful for the offer to help fix our website branding! Whenever you have time, energy, and motivation is of course fine and November or later is no problem at all) and really like the new dragonfly.

As far as variants go, personally I really like the slight colour contrast in the last one as well as the shading. Having a different base colour for the wings and the body works well for me.

(Big fan of the idea of having a 🌈 variant too)

**Comment by Zac-HD** [comment]
I ❤️❤️❤️ the most recent one so much! It's literally better than I was imagining 😍

For the rainbow variant... can we do *more rainbows?*  eg shade the whole area of the large wing (or every wing?) from purple at base to red at tip - I just worry that the current :rainbow: is a bit small and could look like an addition rather than a variation.

**Comment by libbyberrie** [comment]
How's this for a gradient? 
![image](https://user-images.githubusercontent.com/6201161/44954065-c113ae80-aee0-11e8-9b40-49008f42b5ca.png)

**Comment by Zac-HD** [comment]
Shift a little so we get more red and less purple?

But I love it so much I'm wondering about ditching the plain wings.  Probably a bad idea for visual design reasons, but tempting!

**Comment by Zac-HD** [comment]
:heart_eyes: I love it!

**Comment by Zac-HD** [comment]
Sounds great! If you're changing the wings I'd do a *little* less purple and more red, so the area of each is more similar.  A version of each with the text `hypothesis.works` or just "Hypothesis" might be useful but again I trust your judgement. 

In terms of sending things over, we're going to want them in the repo so a PR seems appropriate!  I'd suggest a new top-level directory `logos/`, with all the source and final files plus a one-paragraph readme (so we link of e.g. print on demand swag later). And add yourself to the contributors list!

**Comment by libbyberrie** [comment]
Hello! Just letting you know that I'm not dead :P 
made some favicons for you today. Decided to limitthe favicon to just the head as anything more would be too cluttered. Here is it zoomed into 2x actual size (White background won't be there. will be saved with transparency)

Need to work on logotyping and a styleguide next! still not sure what else to do in terms of branding and swag...

![screen shot 2018-09-17 at 9 59 37 pm](https://user-images.githubusercontent.com/6201161/45623597-3c718480-bacb-11e8-996a-d8bc57eca930.png)

**Comment by Zac-HD** [comment]
> ![image](https://user-images.githubusercontent.com/6201161/44954065-c113ae80-aee0-11e8-9b40-49008f42b5ca.png)

Can you please send over the SVG(s) for this?  The wing top-line looks fine to me, and **anything** is better than our current logo...

![our current logo](https://avatars3.githubusercontent.com/u/18481919?s=200&v=4)

(you're obviously welcome to keep tweaking it in future!  Nothing needs to be final but we would really like to have a better logo in time for Hypothesis 4.0 (#1696) in a few weeks 😸)

**Comment by vdwees** [comment]
The best sticker in my collection.

![image](https://user-images.githubusercontent.com/24944371/171578815-22b452ca-8789-4f6d-91f5-b1f287a24fec.jpeg)
