### ISSUE TITLE
example doesn't respect verbosity

### ISSUE THREAD

**Issue by sponster-au** [HypothesisWorks/hypothesis#1521]
If using the `@hypothesis.example` decorator, the `settings.default.verbosity` is changed to `Verbosity.normal`.

The following test case currently fails:

```python
def test_example_respects_verbosity():
    @settings(verbosity=Verbosity.verbose)
    @example(x=99)
    @given(integers())
    def test(x):
        assert settings.default.verbosity == Verbosity.verbose
    test()
````

**Comment by Zac-HD** [comment]
This is probably a subtle problem somewhere in our internal scoping, similar to #944.
