### ISSUE TITLE
Funding, thanks and other project_urls

### ISSUE THREAD

**Issue by 00willo** [HypothesisWorks/hypothesis#1527]
While also optional like the keywords, these could be good for the project to add. Other projects are starting to hook in and use this information.
```
    project_urls={ 
        'Bug Reports': 'https://github.com/HypothesisWorks/hypothesis/issues',
        'Funding': 'https://<funding_link_here>',
        'Say Thanks!': 'http://saythanks.io/',
        'Source': 'https://github.com/HypothesisWorks/hypothesis/',
    },
```
It would need a funding and a thanks link setup.

**Comment by Zac-HD** [comment]
Considering these four links: links to specific GH pages don't add much value, and we already have documented email addresses or the issue tracker for contacts (and I'd rather avoid KR's drama).

The current funding arrangements are "get in touch about training or development consulting, or donate to the PSF with a note that you like Hypothesis".  We may change this eventually, but basically collecting small donations is not worth the trouble it would cause us with e.g. legal structures, group dynamics, and tax.
