### ISSUE TITLE
Vagrantfile needs updating

### ISSUE THREAD

**Issue by 00willo** [HypothesisWorks/hypothesis#1529]
Executing a `vagrant up` currently fails as the Vagrantfile utilises bootstraps env with Makefile and triggers a `build.sh install-tools`.  This no longer exists.

**Comment by Zac-HD** [comment]
Alternatively, I'd prefer to simply delete and de-document the vagrant system as there are no active users or maintainers - fixing it would probably just re-break next time we change the build system :cry:

**Comment by 00willo** [comment]
Easy done. The first step is deciding the purpose of Vagrant, and what OS's are required to be the supporting host. 

While the different host OS's are mostly irrelevant, depending on how it's configured, it can make a difference, the speed of the share, for instance, can be dramatically different. How to do the provisioning, shell scripts, ansible etc?

**Comment by Zac-HD** [comment]
I think the entire reason that's in here is that someone in 2015 once used Vagrant to get Hypothesis working on Windows.  There *is* no ongoing reason to use it, so I'm considering this as part of #1514.
