### ISSUE TITLE
Tests fail on OSX for v3.69.3 and v3.69.4

### ISSUE THREAD

**Issue by jochym** [HypothesisWorks/hypothesis#1532]
See runs on conda-forge builder:
https://travis-ci.org/conda-forge/hypothesis-feedstock/builds/421092094

**Comment by Zac-HD** [comment]
Upstream bug in Pytest 3.7.3: pytest-dev/pytest#3888

**Comment by jochym** [comment]
Shall we pack the release anyway? Will it fix itself after fixing pytest?

**Comment by Zac-HD** [comment]
You just need to force pytest to 3.7.3 and it will pass, this isn't a hypothesis problem.

**Comment by jochym** [comment]
Ok. Thanks

**Comment by jochym** [comment]
Should it be >= 3.7.3 or above 3.7.3?

**Comment by jochym** [comment]
It seems there is still some problem with this release. After pinning pytest to !=3.7.2 tests on all platforms now fail. And the failure is different. Would you care to take a look @Zac-HD ?
https://github.com/conda-forge/hypothesis-feedstock/pull/130

**Comment by Zac-HD** [comment]
I doubt I'll have time to fix it tonight, but it looks like the new test from #1524 is failing.  Can you open a new issue for that?

**Comment by jochym** [comment]
Sure. When I get home.
P.

wt., 28.08.2018, 15:38 użytkownik Zac Hatfield-Dodds <
notifications@github.com> napisał:

**Comment by jochym** [comment]
Done (https://github.com/HypothesisWorks/hypothesis/issues/1543)
