### ISSUE TITLE
v3.69.6 fails even under pytest != 3.7.3

### ISSUE THREAD

**Issue by jochym** [HypothesisWorks/hypothesis#1543]
Our build still fails one test on all platforms after pinning to non-buggy pytest.
See: https://github.com/conda-forge/hypothesis-feedstock/pull/13

**Comment by Zac-HD** [comment]
Ah, this all makes sense now!  It was a database issue, so it didn't show up in the first build on the PR or on master, but only rebuilds.  PR to fix opened :smile:
