### ISSUE TITLE
HypothesisDeprecationWarning gives no indication of which test is slow

### ISSUE THREAD

**Issue by inglesp** [HypothesisWorks/hypothesis#1547]
I have a handful of tests that sometimes trigger the `HypothesisDeprecationWarning` about tests being slow to run:

```
hypothesis_temporary_module_cba4de053ba62cfcdec02732278778740d129479:154: HypothesisDeprecationWarning: Test took 778.72ms to run. In future the default deadline setting will be 200ms, which will make this an error. You can set deadline to an explicit value of e.g. 800 to turn tests slower than this into an error, or you can set it to None to disable this check entirely.
```

However, the warning doesn't indicate which test is slow.  Is this fixable?

PS Thanks for Hypothesis!  It's second only to the Rust borrow checker for restoring in me a rightful sense of humility.

**Comment by Zac-HD** [comment]
Well, running with warnings as errors would make it show in the traceback :wink: 

We can also fix this on our end, by adding `self.test.__name__` to all deprecation messages in `core.py`.  This would be a good issue for anyone who wants to get started with Hypothesis, or wants a fix released sooner!

(and thanks for the lovely PS!  mind if I add it to the testimonials page?)

**Comment by inglesp** [comment]
It hadn't occurred to me to run with warnings as errors, but adding the test name to the message would be helpful in the case of nondeterministic warnings.

And yes about the testimonial.

**Comment by CuriousLearner** [comment]
I'm looking into this issue 🥇

**Comment by CuriousLearner** [comment]
Hey @Zac-HD I've made the changes. What is the quickest way to test them out?
