### ISSUE TITLE
SIGSEGV in shellcheck in CI

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#1553]
As seen in #1552:
- https://travis-ci.org/HypothesisWorks/hypothesis/jobs/422942355

Also observed yesterday in the merge tests for 091e1311c887f926995742390deb67c01f1b5fe5:
- https://travis-ci.org/HypothesisWorks/hypothesis/jobs/422514430

**Comment by DRMacIver** [comment]
Have I mentioned recently that I hate computers? 😭 

My general diagnostic procedure for these sorts of problems is to clear the cache and rerun it and see if it persists before looking into it in too much detail. It's not exactly a, err, principled approach, but it works surprisingly often.

One possibility though is that we're hitting https://github.com/koalaman/shellcheck/issues/1053 though I'm not sure.

**Comment by Zac-HD** [comment]
This appears to ~~have been a transient issue~~ be fixed.  (let's keep our happy illusions for now...)
