### ISSUE TITLE
Report separate statistics for test cases in reuse, generate, and shrink phases

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1555]
As discussed in #1554, merging all of these phases into one set of statistics makes them quite difficult to interpret if a test is or recently has been failing.  The count of invalid examples tends to be higher, and it would be nice to distinguish generated, replayed, and shrunk test cases.

This will involve changes to the recording in `hypothesis.internal.conjecture.engine`, and to the reporting in `hypothesis.statistics`.  Only phases with more than zero examples should be reported, to avoid e.g. pointless lines of statistics for passing tests.

**Comment by Zalathar** [comment]
I'm working on some engine changes to make this happen.

(Haven't decided whether I'll do the front-end work as well, but I'll probably get around to it.)

**Comment by Zalathar** [comment]
I've since been distracted by other things, and might not get back to this myself.

**Comment by Zac-HD** [comment]
The reporting side of this should be relatively easy to build on top of #1577, and after that's merged I can have a go at the collection side too... but if anyone else wants to try go for it, and I'll post again before I start.
