### ISSUE TITLE
3.70.0 fails on py3.5 on all platforms

### ISSUE THREAD

**Issue by jochym** [HypothesisWorks/hypothesis#1558]
See the logs:
OSX: https://travis-ci.org/conda-forge/hypothesis-feedstock/jobs/423298695
Win: https://ci.appveyor.com/project/conda-forge/hypothesis-feedstock/build/1.0.315/job/l8qn1pf6l36abb8d
Linux: https://circleci.com/gh/conda-forge/hypothesis-feedstock/606?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

It seems to be a single zip test.

**Comment by jochym** [comment]
Sorry. Still fails:
https://github.com/conda-forge/hypothesis-feedstock/pull/133

**Comment by Zac-HD** [comment]
Looks like that build is using the old source code; compare the failure in decompression on line 179, which is now within the try-block and on line 180:

https://travis-ci.org/conda-forge/hypothesis-feedstock/jobs/423822601#L935

https://github.com/HypothesisWorks/hypothesis/blob/6de22634caef67e95bdf621400da4f3ff242ed28/hypothesis-python/src/hypothesis/core.py#L179-L183
