### ISSUE TITLE
cached_test_function should not execute test function when it would overrun

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1566]
As @Zalathar pointed out in #1540 (and is now commented), currently `cached_test_function` will re-execute the test function in some cases where it knows that it cannot work because it's a strict prefix of a previously evaluated test.

In these cases it should avoid that re-execution and should instead return a fake `ConjectureData` object of some sort that indicates it overran.

(In theory it could synthesise a picture perfect accurate one with all the right data, but I don't think we actually need to do that - it's probably better if it's *not* a real ConjectureData object and errors if you try to do anything other than access its status and buffer)

**Comment by Zac-HD** [comment]
Closed by #1745.
