### ISSUE TITLE
Making sure a value came from a hypothesis strategy

### ISSUE THREAD

**Issue by pckroon** [HypothesisWorks/hypothesis#1568]
Hi all,

I made a moderately complex strategy and am currently working on testing it. Is there any way to see whether a value (e.g. `dict` or `int`) could have been generated by a specified hypothesis strategy (e.g. `fixed_dictionaries`, `dictionaries`, `integers`)? This goes beyond just the type, and should include e.g. dict keys, lengths and bounds.

**Comment by DRMacIver** [comment]
I'm afraid it's explicitly impossible to do this in the Hypothesis model - because a strategy only knows how to construct an object (which is why things like `@composite` can work), it's logically impossible to "run the strategy backwards" to determine if a value is valid.

**Comment by pckroon** [comment]
That makes sense, thanks. I'll find another solution.
