### ISSUE TITLE
Move our CI to Azure Pipelines

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1571]
https://azure.microsoft.com/en-us/services/devops/pipelines/ - TLDR for open source: 10 parallel jobs, identical to $40/month jobs so probably fast, and supports Windows, Linux, and OSX.  

I'd be interested in replacing Appveyor's serialised jobs with identical-but-parallel jobs, and we'd have enough space capacity to replace CircleCI too and still be faster than the status quo.

Tactically, this is probably one PR to add the new CI, wait until it's been working stably for a few weeks, and then a second PR to turn off the old CI.  This also makes reverting the experiment really cheap, because we can just disable the new one instead if we don't want to stick with it.

**Comment by vtbassmatt** [comment]
Hi there, I'm a PM on Azure Pipelines. Let me know if there's anything I can do to help out here.

**Comment by Zac-HD** [comment]
#1854 ported our main build stages from Travis to run on Azure pipelines, and it looks like it's going pretty well so far!  As a checklist for future work:

- [ ] Our CI scripts rely on the `travis_event_type` envvar being present.  They shouldn't.
- [ ] Move deployment from Travis to Pipelines.  Wait a while, then stop using Travis.
- [ ] Publish fat binaries for Ruby, i.e. #1842
- [ ] Make `check-whole-repo-tests` non-concurrent (i.e. part of the normal prechecks) once Pipelines supports build caching.
- [ ] Investigate Pipeline's story for auto-cancelling redundant builds (cc @vtbassmatt?) - important for efficient use of machines when we can fail early or have several pushes to a PR in quick succession.  In particular we may want more stages again once caching is a thing and jobs are faster.

On the more speculative side:

- [ ] Consider migrating our Windows and OSX builds to Pipelines too.  Cons: decreased concurrency.  Pros: simpler to manage, avoid potential bugs (i.e. merge to master, only Linux works, deploy happens anyway).  Personally I think it's worthwhile as a small slowdown for improved correctness - and probably net faster than present once Pipelines has caching.

Anything else we should do or consider in moving over?

**Comment by vtbassmatt** [comment]
New commits appearing on a PR will cancel running pipelines for that PR. We don't support fail-fast behavior (e.g. where one leg of a matrix fails, cancel the pipeline) today, but it's on my wishlist for Q2.

Also, if concurrency becomes an issue moving over your Windows and macOS builds, I can make that problem go away.

**Comment by Zac-HD** [comment]
> New commits appearing on a PR will cancel running pipelines for that PR. We don't support fail-fast behavior (e.g. where one leg of a matrix fails, cancel the pipeline) today, but it's on my wishlist for Q2.

Awesome!

> Also, if concurrency becomes an issue moving over your Windows and macOS builds, I can make that problem go away.

:heart_eyes:

We don't currently have a concurrency *problem*, but increased contention is literally the only reason not to move those builds IMO.  We've been living with Travis because there wasn't a better alternative, but for CI quicker is always better - especially with e.g. PyCon US sprints coming up.

**Comment by vtbassmatt** [comment]
Feel free to start moving your Win/Mac pipelines over. I'll get concurrency sorted today.

Will you be at PyCon? I'm going (my first time!) and would love to have you stop by the Pipelines booth.

**Comment by Zac-HD** [comment]
:tada: 

I am - it'll be my first PyCon US too, andI'dlove to catch up in person!  As well as [sprints](https://us.pycon.org/2019/community/sprints/), I'll be [presenting a poster](https://us.pycon.org/2019/schedule/presentation/136/), [giving a talk](https://us.pycon.org/2019/schedule/presentation/217/), and [teaching a tutorial](https://us.pycon.org/2019/schedule/presentation/91/).  I really wanted to justify the trip from Australia, but didn't anticipate all my proposals being successful - fortunately I can draw on the talks and workshops I've done at Pycons AU, APAC, and London :sweat_smile:

**Comment by vtbassmatt** [comment]
... I think your trip is justified! I'll try to catch at least one of those editions of your talk, and for sure we should catch up in person.

**Comment by Zac-HD** [comment]
We have everything but deployment running on Pipelines now (:tada:), so I've created a more focussed issue 2043 for that last push.  Thanks to everyone who was involved in this!
