### ISSUE TITLE
Warnings in Python 3.8 (CPython master)

### ISSUE THREAD

**Issue by tirkarthi** [HypothesisWorks/hypothesis#1576]
Trying to install hypothesis shows the following warning in CPython master. I searched for the related warning and master branch but I couldn't find any issue so I am reporting it here.

> /home/karthi/pandas-venv/lib/python3.8/site-packages/hypothesis/strategies.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sequence

Thanks

**Comment by Zac-HD** [comment]
Thanks for reporting this!  Would you like to open a PR and fix it?

The patch will consist of deleting that import, prepending `abc` to the names imported from `hypothesis.internal.compat` (line 42), and replacing the only runtime use of `Sequence` with `abc.Sequence` (line 973).  Then add a `RELEASE.rst` for a patch release (copy from one of my open PRs, and see the changelog for message style), add your name to the list of authors in `CONTRIBUTING.rst`, and we're done!

**Comment by tirkarthi** [comment]
Sure, thanks for the information. I will raise a PR by the weekend.

Thanks
