### ISSUE TITLE
Mark all nodes beyond a discarded example as dead

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#1579]
*This issue is a negative result, describing an attempted improvement that I eventually decided to abandon.*

---

Inspired by #1574, I wanted to improve the novelty-generator's poor handling of this test:

```python
@given(st.integers(min_value=0, max_value=2))
def test_foo(x):
    pass
```

Intuitively, we would expect Hypothesis to find all three legal examples, and then stop.

But what actually happens is that we quickly find all three base cases, and then spend the rest of our execution budget chasing increasingly-convoluted invocations of the rejection sampler, all of which produce values that we've already seen.

My plan was to find the first discarded example in each result, and mark all bytes beyond that point as dead, so that the novelty-generator knows not to explore them.

I then realized that this could perhaps cause a weird bias in the probability distribution of samples that are longer than a single byte, because the novelty-generator can only backtrack by one byte.

However, the single-byte case is still quite common when generating small integers (like in the example above), especially since these are the only draws that are likely to be exhausted before reaching the test limit.

**Comment by Zalathar** [comment]
But then I encountered a less obvious obstacle. 

I had been assuming that it was safe to mark these nodes as dead, to prevent the novelty-generator from exploring them.

However, the shrinker uses dead nodes in a slightly different way: if `prescreen_buffer` finds that a candidate buffer is dead, it is rejected as a potential shrink improvement, and never runs.

This unfortunately means that it's not necessarily safe to mark a node as dead if we haven't *actually* explored all of the explorable values beyond it, because doing so could cause us to miss legal intermediate shrinks (which will then be shrunk again by the discard pass).

**Comment by Zalathar** [comment]
Perhaps there's a reasonable way to get past this obstacle (or declare it a non-problem), but it's seeming less likely that that is the case.

**Comment by Zac-HD** [comment]
> *This issue is a negative result, describing an attempted improvement that I eventually decided to abandon.*

Thanks for posting the negative results too!  As well as being interesting and educational reading, it's the best way to avoid duplicating each other's work :smile:
