### ISSUE TITLE
Don't flatten branches in biased OneOfStrategy

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1600]
In #1502/#1595 we ran into the fact that flattening of branches in `OneOfStrategy` could cause weird behaviour when `bias` was not None. @Zac-HD fixed the weird behaviour, but I wondered whether we should be flattening at all in this case.

I think this issue admits one of two possible fixes:

* change the logic of `OneOfStrategy` to not flatten when there is bias. In doing this it might make sense to remove the laziness and just put everything in the constructor (when calculating `element_strategies` and `sampler`) to simplify the logic.
* remove the idea of `bias` from `OneOfStrategy` altogether and just make `recursive` actually recursive. The logic that allows `deferred` to work should also allow this to work.

Neither fix should be very hard on the face of it - the big difficulty is going to be in finding, debugging, and fixing whatever tests this causes to fail.

**Comment by Zac-HD** [comment]
@math2001 is looking at this issue; as usual it's reserved for one week.

**Comment by math2001** [comment]
Hey, I've gotta to do a fair bit of maths, at least until the summer holidays. So, if any one wants to take up this issue, go ahead.

To fix this issue, I'm going to need some of time to actually understand what's going on. I want to make sure I use this bug to get the big picture.

**Comment by mjsir911** [comment]
I'll have a go at this one

**Comment by Zac-HD** [comment]
Closed by #1957.
