### ISSUE TITLE
min_size arguments should default to zero instead of None

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1618]
We default arguments to `None` where we don't have a known bound (e.g. `integers()`), or where a non-`None` default argument would require us to weaken our checks for consistency (e.g. if `min_value` defaulted to `-inf` for `floats()`, we couldn't warn a user who passed `min_value=-inf, allow_infinity=False`).  For strategies such as `dates()` we don't accept `None` at all!

It turns out that neither of these reasons apply to minimum sizes!  We should therefore:

- Set `min_size=0` as the default for all size arguments
- In [`hypothesis.internal.validation.check_valid_size`](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/internal/validation.py#L103), add a check `if name == 'min_size' and value is None:` and use `note_deprecation` to warn users that they should use `min_size=0` instead.
- Search for any remaining cases in our codebase where *we* use this argument, with [`git grep --line-number --perl-regexp "min_size ?= ?None"`](https://git-scm.com/docs/git-grep)
- Write a test in `hypothesis-python/tests/cover/test_validation.py` that uses `@checks_deprecated_behaviour` and passes `min_size=None` to `lists()`.

**Comment by lgoeller** [comment]
I'm going to take this one on!
