### ISSUE TITLE
Pytests are stuck on 77% with all hypothesis versions since 3.71.10

### ISSUE THREAD

**Issue by tankoyarik** [HypothesisWorks/hypothesis#1620]
On our project which is running on Flask and pytests we have an issue with the test. Test have been stuck at 77% from since hypothesis 3.72.0 was released. Actually, all tests are passing in case we have hypothesis version 3.71.10 and lower. The issue keeps occurring when we run tests locally, in Travis CI, in Docker.
We think that it could be a problem with cache data of the hypothesis library.
![screenshot from 2018-10-03 18-20-20](https://user-images.githubusercontent.com/37215092/46420793-6f598080-c739-11e8-96f0-84ed531934b8.png)

![screenshot from 2018-10-03 18-25-21](https://user-images.githubusercontent.com/37215092/46420936-be9fb100-c739-11e8-9844-be97b9768fc5.png)

**Comment by Zac-HD** [comment]
Try disabling the database, e.g. by putting the following in `conftest.py`:

```python
from hypothesis import settings
settings.register_profile('no_db', database=None)
settings.load_profile('no_db')
```

Do any tests execute at all?  Can you share a link to a Travis log?

**Comment by Zalathar** [comment]
The intervening PRs that touch released Python code are #1594 and #1572.

In theory neither of those should be able to cause a successful test suite to hang, but I can't rule out the possibility completely.

**Comment by tankoyarik** [comment]
Attaching the file with travis logs as per your request.
[Travis log](https://github.com/HypothesisWorks/hypothesis/files/2446161/Travis.log)

**Comment by Zac-HD** [comment]
```
$   $TEST_MIGRATIONS || pytest -vv --cov-report xml
============================= test session starts ==============================
platform linux -- Python 3.7.0, pytest-3.8.2, py-1.6.0, pluggy-0.7.1
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(...)
plugins: cov-2.6.0, hypothesis-3.74.0

collected 154 items
...
tests/guestlist/fields_tests.py::TestGuestlistFields::test_add_multiple_option_min_bigger_than_max PASSED [ 77%]

No output has been received in the last 10m0s, ...
The build has been terminated
```

I'd guess that the next test is hanging forever - can you try running just that test to see if it hangs?  What is [`$PYTEST_CURRENT_TEST`](https://docs.pytest.org/en/latest/example/simple.html#pytest-current-test-environment-variable)? when it hangs?

**Comment by tankoyarik** [comment]
If I run the test separately, it passes without any issues. Moreover, all tests associated with guestlists are located in 1 module: "
![screenshot from 2018-10-04 15-28-10](https://user-images.githubusercontent.com/37215092/46474122-bd7a8c80-c7ea-11e8-8aeb-2db21fcc491b.png)
guestlist". So the last test from field_test.py is running (77%) and the next one should run in get_test.py...but for some reason, it's hanging.

**Comment by Zac-HD** [comment]
Check the environment variable - I suspect it's the next one hanging.

**Comment by Zac-HD** [comment]
@tankoyarik - we really need a reproducible example in order to tell if this even has anything to do with Hypothesis, either a simplified version of the hanging test or the actual original code.

**Comment by Hultner** [comment]
@Zac-HD This problem exists in our private codebase so we can't provide the source code. Our cron-run tests on travis-ci started suddenly failing one day and when I started diffing the logs between the failing run and the working run on the same commit I could only find one difference. 

The failing ones were using hypothesis 3.72.0 (this started happening on the day of the release) and the successful ones were running on hypothesis 3.71.10.

However, I just got a successful build on hypothesis-3.74.2 on travis-ci.

**Comment by Hultner** [comment]
@Zac-HD Seems like we're still having some issues, @tankoyarik is currently investigating. 

As for the reproducible sample, the problem is that we're not exactly sure what's causing it but we know we can solve it by pegging certain versions of Hypothesis. It certainly seems to be related to the hypothesis version but since we're not getting any errors (it just freezes) it's a bit difficult to know why.
