### ISSUE TITLE
Lifecycle API

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#163]
One of the things you need for testing is a bunch of hooks into the life-cycle – setup and teardown for example. Hypothesis currently has the executors API which nobody including me likes. It’s a bit weird, very limited, and ties you to class based testing.

I’d like to expose a detailed lifecycle API that lets you hook into a number of events. In particular I need to be able to insert code around just the test body (executors currently treat value creation and test execution identically). Combining this with the better `@given` configuration above makes it easy to ditch the dependence on class based testing.

I’d still like to be able to support some sort of auto derivation of life cycle events for class based tests (unittest setup and tear down for example).

I’d also like to integrate this with py.test function level fixtures, but that’s currently impossible.

**Comment by tomprince** [comment]
It would also be nice to be able to play well with deferred using tests, for example

**Comment by Zac-HD** [comment]
Related to #59.

**Comment by Zac-HD** [comment]
#1343 added the ability to insert a decorator 'under' `@given` around the test body.

**Comment by Zac-HD** [comment]
#1343 added the ability to insert a decorator 'under' `@given` around the test body, and there are more specific issues for unittest setup/teardown and pytest fixtures.  I'm going to close this, but feel free to open a new issue if you have a related problem!
