### ISSUE TITLE
Allow warnings-as-errors to be disabled when running tests

### ISSUE THREAD

**Issue by seifertm** [HypothesisWorks/hypothesis#1630]
Sorry to pull this issue out again… I am currently trying to package a more recent version of Hypothesis (Python) for Gentoo Linux. When running the tests with Python3, I get a DeprecationWarning (from `pluggy-0.5.2`) that is treated as an exception (the same error was described and solved in https://github.com/HypothesisWorks/hypothesis/issues/969). Previously, it was possible to configure the behaviour of Python's `warnings` module. However, the env var `PYTHONWARNINGS` seems to have no effect, nor does the `-W` switch for pytest or the interpreter.

By the looks of it, [this line](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/tests/common/setup.py#L32) overrides all warning configuration for the tests. If I remove the offending line, tests run just fine.

Is there a configuration option to disable the fact that warnings are treated as errors? I feel that this would be useful for other downstream packagers as well.

**Comment by Zac-HD** [comment]
No worries!  We don't currently have such an option because it tends to be a pain to maintain, but I'd be happy to add ignore lines for the specific warning(s) you're seeing if you can post them.  Alternatively you could just patch that line out!

**Comment by Zac-HD** [comment]
```python
# Fixed in recent versions but allowed by pytest=3.0.0; see #1630
filterwarnings('ignore', category=DeprecationWarning, module='pluggy.__init__')
```

should work, and I'd accept a PR to add it to our test config if it does - or a wider filter so long as it only catches warnings from old versions of indirect dependencies.

**Comment by seifertm** [comment]
It works with `module='pluggy'`, thank you! Python's warnings module is quite powerful.
I filed a PR accordingly.
