### ISSUE TITLE
Cannot infer from numbers ABCs

### ISSUE THREAD

**Issue by astronouth7303** [HypothesisWorks/hypothesis#1636]
Trying to use `infer` when the annotation is from the `numbers` module ABCs fails, saying:

```
TypeError: Can't instantiate abstract class Real with abstract methods __abs__, __add__, __ceil__, __eq__, __float__, __floor__, __floordiv__, __le__, __lt__, __mod__, __mul__, __neg__, __pos__, __pow__, __radd__, __rfloordiv__, __rmod__, __rmul__, __round__, __rpow__, __rtruediv__, __truediv__, __trunc__
```

The behavior I expected is that it would just plug in a `float`.

**Comment by Prsna23** [comment]
I would like to work on this issue. Can you please elaborate a little more on this?

**Comment by Zac-HD** [comment]
Hi Prasana - unfortunately if the problem is not obvious from reading the docs on `numbers.Real` and `hypothesis.strategies.from_type` and the solution obvious from reading the code linked above, this is probably not a good issue for you :confused:

**Comment by SuperStormer** [comment]
I'm working on this issue
