### ISSUE TITLE
Check for settings assigned as attribute on StateMachine class

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1643]
#1638 allows `@settings(...)` to be used as a class decorator on state machine classes, which substantially improves the ergonomics.  However, the old mechanism of assigning an attribute is still supported.  #1642 points out a fairly subtle trap in this behavior though, by fixing it in the docs:

```python
DatabaseComparison.settings = settings(...)  # Wrong!  This doesn't have any effect.
DatabaseComparison.TestCase.settings = settings(...)  # The right way to do it.
```

Fortunately we can use essentially the same solution as in #1572, defining a custom `__setattr__` on a (new) metaclass of `GenericStateMachine` that will turn the incorrect usage from silent failure into an explicit error with a helpful message (which can also suggest the decorator form).

This should error when the `.settings` attribute on the class is assigned an instance of `settings`, but allow other types to be assigned to minimize false-positives.  We should not restrict attributes on instances if we can avoid it.

**Comment by Zac-HD** [comment]
This issue would be a good introduction to Hypothesis for an intermediate programmer who understands metaclasses, or at least can follow the example of `hypothesis.settings` to customise the behaviour of the class object but not instances thereof.

**Comment by Zac-HD** [comment]
I would simply copy the implementation of `settingsMeta`, which provides the `__setattr__` for the `settings` class object.

https://github.com/HypothesisWorks/hypothesis/blob/dd46aca7e521fccc81ef619704dfd363ebbe8c3a/hypothesis-python/src/hypothesis/_settings.py#L99-L135

As far as I'm aware this is compatible with both Python2 and Python3, though I could be wrong!

**Comment by nmbrgts** [comment]
Thanks for clarifying, Zac. I misunderstood how `settingsMeta` worked to create a metaclass. This avoids the compatability error that I was thinking of which was 3.x's metaclass keword argument vs 2.7's __metaclass__ property.
