### ISSUE TITLE
No value for argument 'draw' in function 'arrays'

### ISSUE THREAD

**Issue by mi-s** [HypothesisWorks/hypothesis#1654]
I try to use the function hypothesis.extra.numpy.arrays in the following way:
` @given(img=arrays(dtype=np.float32, shape=(3, 3, 3, 3)))   `                                                                                                                       
   `       def test_split_multi_channel_image(self, img): pass  `   

My linter raises the following error:
E1120 No value for argument 'draw' in function call [pylint]

What's the problem?

**Comment by Zalathar** [comment]
It seems like the linter is interacting poorly with some internal implementation details of the `arrays` strategy.

Which version of Python are you running, and what is the name and version number of your lint tool?

**Comment by DRMacIver** [comment]
This is a known limitation of pylint I'm afraid - https://github.com/PyCQA/pylint/issues/259. There's not much we can do about it other than suggesting disabling that warning in your linter.
