### ISSUE TITLE
__init__ inherited from object fails required_args() on Python-2.7

### ISSUE THREAD

**Issue by ccxcz** [HypothesisWorks/hypothesis#1656]
On Python 2.7 `getargspec()` fails on default `__init__` method. This in turn triggers bug #1655. The `required_args()` function can use `target.__init__ is object.__init__` to detect this case.
Test for checking correct result is provided in https://github.com/ccxcz/hypothesis/tree/check-default-init

**Comment by Zac-HD** [comment]
Thanks for reporting this!

**Comment by ccxcz** [comment]
Another way this breaks is on old-style classes that don't have to have __init__ attribute at all. Checking with `hasattr(target, '__init__')` would work in that case.

**Comment by Zac-HD** [comment]
Gah, I'm so sick of Python 2... thanks for the report though :+1:
