### ISSUE TITLE
How can we help users to find strategy implementing packages?

### ISSUE THREAD

**Issue by fkromer** [HypothesisWorks/hypothesis#1661]
Via [libraries.io](https://libraries.io/search?languages=Python&q=hypothesis) and [basic PyPi search for "hypothesis"](https://pypi.org/search/?q=hypothesis) it's not possible to distinguish between (A) packages which use hypothesis for testing, (B) packages which implement integration of hypothesis with other frameworks and (C) packages which implement generic strategies based on hypothesis.

Probably it's possible to get `hypothesis` added to the [PyPi classifiers](https://pypi.org/classifiers/) (e.g. `Framework :: hypothesis`) somehow?

- (A) `Framework :: hypothesis`
- (B) `Framework :: hypothesis :: integration`
- (C) `Framework :: hypothesis :: extension`

**Comment by Zac-HD** [comment]
Per [the PyPI FAQ](https://pypi.org/help/#new-classifier), I've opened pypa/warehouse#4973 to request a new trove classifier `Framework :: Hypothesis`.  Based on the number of packages, and the PyPI issue guidelines, I've only requested the single classifier - they're reasonably conservative to avoid namespace pollution, and IMO the distinction between integration and extension will be unclear to many readers (e.g.: integration with what?).

Let's move any further discussion to that issue!

**Comment by Zac-HD** [comment]
And the `Framework :: Hypothesis` classifier is now a thing!  See #1663 :tada:

**Comment by fkromer** [comment]
[PyPI search for packages which have Hypothesis classifier set.](https://pypi.org/search/?c=Framework+%3A%3A+Hypothesis)

**Comment by Zac-HD** [comment]
Soon!
