### ISSUE TITLE
integers(x, x) can generate (x-1) if x is an int64

### ISSUE THREAD

**Issue by dycw** [HypothesisWorks/hypothesis#1667]
Hi,

Just stumbled upon this by accident. Using hypothesis 3.68.0 and numpy 1.15.2:

```python
from hypothesis import given
from hypothesis.strategies import data, integers
from hypothesis.extra.numpy import from_dtype, integer_dtypes

@given(data=data(), dtype=integer_dtypes())
def test_numpy_integers(data, dtype):
    x = data.draw(from_dtype(dtype))
    assert data.draw(integers(x, x)) == x
```

For example, with the int64 type we can fail with `x = 9007199254740993`, with `integers()` generating `x - 1`. I've not seen examples of anything other than `x - 1` being generated.

**Comment by Zalathar** [comment]
I had a quick look into this, and was surprised to find that `floor(x) != x` for some values of `x` that are `numpy.int64`.

I haven't had a chance to figure out why that happens.

**Comment by Zac-HD** [comment]
The [return type of `numpy.ceil` is `float64`](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.ceil.html), just like `math.ceil` in Python 2.  Apparently there is also an intermediate cast to `float` in the `__ceil__` method of integer dtype values - for example `x = 9007199254740993 = 2 ** 53 + 1`, and `np.ceil(x) == 9007199254740992.0`.  This is actually also the Python2 behaviour of `math.ceil` (which we work around in Hypothesis), so it's certainly not unprecedented!

I've added a comment to the upstream issue, but for us the best option is probably to use the Python 2 implementation on all versions for now.

**Comment by dycw** [comment]
Thanks Zac-HD, so efficient!!
