### ISSUE TITLE
Ensuring known and desired failures

### ISSUE THREAD

**Issue by Midnighter** [HypothesisWorks/hypothesis#1675]
I've read a couple of issues on integration between hypothesis and pytest fixtures or parametrize and have come to realize that it's not really possible. So what about the other way around? Basically, what I'm looking to do:

I often make use of the excellent [pytest-raises](https://github.com/Lemmons/pytest-raises) package to ensure that certain cases fail in expected ways. A silly example:

```python
import pytest

@pytest.mark.parametrize("denominator", [
    1,
    pytest.param(0, marks=pytest.mark.raises(exception=ZeroDivisionError))
])
def test_division(denominator):
    result = 1 / denominator
    assert result * denominator == 1
```

So if I wanted to do the same with hypothesis, I'd have to split up that test into two tests. One using a strategy and another documenting the desired failures. What I'm asking is, could we extend the `example` to include this. Something like:

```python
import hypothesis.strategies as st
from hypothesis import example, given


@given(denominator=st.integers())
@example(0, exception=ZeroDivisionError)
def test_division(denominator):
    result = 1 / denominator
    assert result * denominator == 1
```

The original [pytest-raises](https://github.com/Lemmons/pytest-raises) allows both an `exception` and a `message` argument, checking that `message` occurs in the error message.

**Comment by Zac-HD** [comment]
I'd rather keep this out of `@example` actually - adding it in would make the design less orthogonal, and could cause some serious issues in the long term if we want to change the underlying model.  We simply don't have a large enough team to let Hypothesis grow features of a test runner - providing everything you need to write the test functions is quite enough work!

Here's how I'd write this test with Hypothesis:

```python
import hypothesis.strategies as st
from hypothesis import example, given

@given(denominator=st.integers())
@example(0)  # ensure that both failures
@example(1)  # and successes are attempted
def test_division(denominator):
    if denominator == 0:  # if should_fail(...)
        with pytest.raises(ZeroDivisionError):
            1 / denominator
    else:
        result = 1 / denominator
        assert result * denominator == 1
```

This *is* more verbose, but the general pattern works really well when you have some way of checking which branch the input *should* take.  Alternatively, you can write a separate test function for each and use `assume(not should_fail(x))` or `the_strategy.filter(should_not_fail)`.  If there are only a few cases that should fail, I'd even just write traditional or parametrised unit tests for them - Hypothesis is great, but not *always* the right tool for the job!

So in fact I'd write a different test:

```python
import hypothesis.strategies as st
from hypothesis import assume, example, given

def test_division_by_zero():
    with pytest.raises(ZeroDivisionError):
        1 / 0

@given(denominator=st.integers())
def test_division(denominator):
    # If you have multiple arguments, filtering individual strategies can be
    # more efficient, but in this case we'll use `assume` for readability.
    assume(denominator != 0)
    result = 1 / denominator
    assert result * denominator == 1
```

Closing this issue as "won't add feature", but very happy to answer any followup questions you might have :smile:

**Comment by Midnighter** [comment]
No, this is fair. Thank you for the examples.
