### ISSUE TITLE
Confusion about mutliple `targets` in `rule`

### ISSUE THREAD

**Issue by alexjg** [HypothesisWorks/hypothesis#1681]
I'm slightly confused about how one is intended to populate multiple targets from the `rule` annotation. I have some code that looks like this:

```python
class MyStateMachine(RuleBasedStateMachine):

    vehicles = Bundle("vehicles")
    users = Bundle("users")

    @rule(targets=(vehicles, users))
    def create_user(self):
        user = somehow_create_user()
        return (user, user.vehicle)
```

i.e I want to have two separate bundles to draw values from but there is only one step to generate those values.

What I would expect to happen here is that the bundles are populated by values from the retuend tuple in the same order that they are writte in the `targets=...` argument. In actual fact the returned tuple is used to populate both the `vehicles` and `users` tuple. This means that in subsequent rules I need to do something like this:

```python
@rule(user_info=users)
def my_other_rule(self, user_info=None):
    user = user_info[0]
```

This is a bit clunky. Am I misunderstanding something here?

**Comment by Zac-HD** [comment]
It *is* a bit clunky, but I don't think you're missing anything - [a single return value is added to each bundle in `targets`](https://hypothesis.readthedocs.io/en/latest/stateful.html#rules).  @DRMacIver might have some more useful advice?

We also agree that `hypothesis.stateful` can be confusing; see issues #1190 and #1300.  Basically we want to find the time to make the API cleaner and expand the docs, and ideally also find better ways to describe and teach the concepts involved.  It just hasn't happened yet 😢

**Comment by DRMacIver** [comment]
>  @DRMacIver might have some more useful advice?

Unfortunately my answer is much the same. 😢

I agree that in retrospect your suggested usage pattern is much nicer. Unfortunately it's very hard to change that behaviour in a backwards compatible way for a variety of reasons good and bad.

One thing you could do which is still quite clunky but at least contains the clunkiness is that you could define unpack rules? So something like the following:

```python
class MyStateMachine(RuleBasedStateMachine):

    vehicles_with_users = Bundle("vehicles_with_users")
    vehicles = Bundle("vehicles")
    users = Bundle("users")

    @rule(target=vehicles_with_users)
    def create_user(self):
        user = somehow_create_user()
        return (user, user.vehicle)

   @rule(target=vehicles, source=vehicles_with_users)
   def get_vehicle(self, t):
       return t[1]

   @rule(target=users, source=vehicles_with_users)
   def get_user(self, t):
       return t[0]
```

That way at least if you're defining many rules using the inputs you don't have to duplicate the logic with each? I'm definitely not claiming this is an ideal solution though...

**Comment by alexjg** [comment]
That's a nice solution, I'll give it a shot.

It's interesting that you feel that `stateful` in general is confusing. So far I've been having a pretty plain sailing experience with it and am finding it dramatically more productive than example based testing I had been doing before. For context I'm using it to drive some black box testing of an HTTP API.

I'll close this issue because my question has been answered. Really appreciate all the input here.

**Comment by DRMacIver** [comment]
>  am finding it dramatically more productive than example based testing I had been doing before.

Oh yeah, it's mostly great once you get the hang of it, it just has a bunch of slightly weird corner cases and limitations.

**Comment by Zac-HD** [comment]
> It's interesting that you feel that `stateful` in general is confusing. So far I've been having a pretty plain sailing experience with it and am finding it dramatically more productive than example based testing I had been doing before.

Glad to hear it's been working for you 😄 

My concern isn't really "`stateful` *is* confusing", more "*can be* confusing" for new users (especially if they've never been introduced to state machines).  The main things I'd like to do are finish #1609 so it's more like `@given`, deprecate `GenericStateMachine` in favor of inline `st.data()` so there's only one way to do that, and split the docs into a tutorial section and a reference section so that concepts and API bits can be introduced in a sensible order.  Maybe over the austral summer, though I've got a lot of existing PRs to merge first.
