### ISSUE TITLE
 The floats strategy with allow_infinite set to False returns infinity if min_value is large

### ISSUE THREAD

**Issue by vitalbmcdonald** [HypothesisWorks/hypothesis#1683]
Similar to issue #1476, when `allow_infinity` is set to `False` in conjunction with `min_value` set to a large value, infinity still can be returned. 

The following code reproduces the error for on my computer, but I think the `min_value` may have to change depending on the system being used. 
```python
from hypothesis.strategies import floats
from hypothesis.errors import NoExamples
import math

strategy = floats(min_value=1e+302, allow_infinity=False, allow_nan=False).filter(lambda x: math.isinf(x))

try:
    strategy.example()
except NoExamples:
    print("Expected result")
else:
    raise Exception("Strategy returned infinity")
```

I think the culprit is [this map](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/strategies.py#L535).  I believe according to that code any positive `min_value` could result in infinity being returned, it is just more likely the larger the value provided. 

A workaround is adding a `.filter(lambda x: not math.isinf(x))` to any strategy.

**Comment by Zac-HD** [comment]
(whoops, wrong button - issue will close when the PR is merged, not before)
