### ISSUE TITLE
Average size argument in list generator should be of type int

### ISSUE THREAD

**Issue by MichalKononenko** [HypothesisWorks/hypothesis#1689]
Shouldn't the type declaration [here](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/strategies.py#L633) for ``average_size`` be ``  # type: int`` instead of ``  # type: None``?

**Comment by Zac-HD** [comment]
The `average_size` argument has been deprecated since before type hints were added - you should never be passing an integer (or other value) for it, so `type: None` reflects correct usage.  And if you *do* pass a value, it's silently ignored!
