### ISSUE TITLE
Extremeley poor randomness when sampling numpy arrays

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [HypothesisWorks/hypothesis#1691]
It seems that there are *many* repeated values when sampling. Did I do anything wrong ?

```python
Counter(arrays(np.float, (10000), elements=floats(0, 1)).example())                                   
>> Counter({0.5006141457173886: 9749,
         0.541344240996854: 1,
         0.6560771405101827: 1,
...})
```

hypothesis version: 3.83.0
numpy version: 1.15.4

**Comment by Zac-HD** [comment]
This is expected - the `.example()` method produces simple examples only, and the fill argument means that's mostly a sibgk background value.
