### ISSUE TITLE
Clean up extra.django namespace

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1695]
The Django extra has a few issues and inconsistencies, which are basically all because it predates our style guide and `st.from_type` respectively.  It would be nice to:

- replace `hypothesis.extra.django.models.models` with `hypothesis.extra.django.from_model`, deprecating the former.  #35 would then obviously add `from_form`.
- ~~replace all the field-related inference with "just use `st.from_type`, and `st.register_type_strategy` for custom fields", because we really don't need two copies of that machinery and converting would trivially handle most of #1116.~~  Nope, most of the detail lives on *instances*, not the types.  Darn.
- do nothing for optional fields by default, unless passed `infer` (`models.models` always infers unless passed `use_default`, unlike everything else)

**Comment by GrigoriosGiann** [comment]
Hello!
I'd love to try this one out :)

**Comment by GrigoriosGiann** [comment]
> replace all the field-related inference with "just use st.from_type, and st.register_type_strategy for custom fields", because we really don't need two copies of that machinery and converting would trivially handle most of #1116.

I presume you mean the types should still be registered by us using `st.register_type_strategy`, and the end user wouldn't have to register any `dm` types themselves, correct?
Or do you mean we should drop inference and make it the user's responsibility?

**Comment by Zac-HD** [comment]
Hi @GrigoriosGiann - this one is actually going to be a big and complicated change.  I'd suggest starting with one of the ['good first issues'](https://github.com/HypothesisWorks/hypothesis/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) - perhaps one of the Django ones! - and then coming back to this once you've got a bit more experience working on Hypothesis :smile:

**Comment by GrigoriosGiann** [comment]
Thanks for the heads up @Zac-HD!
I'll try my luck at an easier issue as you recommended! 😄

**Comment by thismatters** [comment]
That looks really great. I think that will be really easy to implement #35 into that framework!

**Comment by Zac-HD** [comment]
That's the plan!
