### ISSUE TITLE
Pytest 3.0 build failing on master

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1702]
https://travis-ci.org/HypothesisWorks/hypothesis/jobs/469236645 started failing after we merged #1699, so I suspect this is down to the Tox or pytest update.

Personally I'd be happy to bump this to check a more recent version of pytest - 3.1 at minimum to support the 3.x idioms; 3.4 for "all of 2018", 3.6 for "relatively modern".  After all - pytest is now at 4.0!

**Comment by Zac-HD** [comment]
Nope, [pytest 3.1 also fails](https://travis-ci.org/HypothesisWorks/hypothesis/jobs/469303286).  I've just disabled this build in 06b709ca888649b6cc43a125c007138a6ba1c267 until we can investigate properly.

**Comment by patchedwork** [comment]
#1699 updated pytest-xdist to version 1.25.0, and if you look at it's changelog it says 
`Pytest versions older than 3.6 are no longer supported.`

If you look at your outputs and search for pytest-xdist you'll in your first test on line 836:
`pytest-xdist 1.25.0 has requirement pytest>=3.6.0, but you'll have pytest 3.0.0 which is incompatible.`

And in the second test on line 946:
`pytest-xdist 1.25.0 has requirement pytest>=3.6.0, but you'll have pytest 3.1.0 which is incompatible.`

line 1000:
`_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'xdist' could not be loaded: (pytest 3.1.0 (/home/travis/build/HypothesisWorks/hypothesis/hypothesis-python/.tox/pytest31/lib/python3.6/site-packages), Requirement.parse('pytest>=3.6.0'))!`

Perhaps the minimum pytest version should be 3.6.0? Or you could roll back pytest-xdist to version 1.24.1? I'm new to this, so apologies in advance if my suggestions seem juvenile!

**Comment by Zac-HD** [comment]
Sounds like you've solved the mystery!  If you'd like to make a PR to close this issue, just add `pip install pytest-xdist==1.24` in `tox.ini` and uncomment the line in `travis.yml`.

https://github.com/HypothesisWorks/hypothesis/blob/848b49a1e402d395e56a1ac6e1bbac682bead559/.travis.yml#L62-L63

https://github.com/HypothesisWorks/hypothesis/blob/848b49a1e402d395e56a1ac6e1bbac682bead559/hypothesis-python/tox.ini#L131-L136

And thanks for taking the time to investigate :heart_eyes:
