### ISSUE TITLE
Move over to new pytest plugin API

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1708]
We're currently using `pytest.mark.hookwrapper` in our pytest plugin. According to @RonnyPfannschmidt this API is soon to be deprecated and we should be using ` pytest.hookimpl(hookwrapper=True)` instead.

Hopefully this should be a simple matter of changing the code over to use the new decorator, but it's Hypothesis development so I'm sure something exciting will break. 😆 😢

**Comment by RonnyPfannschmidt** [comment]
unrelated - https://github.com/pytest-dev/pytest/blob/master/CHANGELOG.rst#280-2015-09-18 introduced the new api in pytest 2.8.0

**Comment by Zac-HD** [comment]
(maybe I'm being too optimistic, but I think this might well be a nice self-contained change :smile:)

**Comment by patchedwork** [comment]
Hello! I've given this issue my first attempt, and I'm willing to try again! Please let me know if there's anything I can do!
