### ISSUE TITLE
Provide Django Stateful testing examples.

### ISSUE THREAD

**Issue by bukowa** [HypothesisWorks/hypothesis#1725]
I am just trying to run stateful testing with Django. Basically to test an API. Documentation lacks any examples for that. While i will be figuring out how to handle that, maybe someone already has some examples. If not i will provide them once i actually make them work.

For example, how to write such a test that will make it possible to create thousands of users that perform random interactions with the API. Asserting errors based on the user permissions and more.

**Comment by Zac-HD** [comment]
Hi @bukowa - we'd love to include any examples of this you write up, but I'm going to close this issue for now as there's no action that the maintainers can take to fix it.

**Comment by Lerrrtaste** [comment]
@bukowa Did you find a way to run Stateful Tests with the Django Test Framework?

**Comment by Zac-HD** [comment]
@Lerrrtaste - you might find https://github.com/schemathesis/schemathesis useful 😌
