### ISSUE TITLE
Is there a recommended way to set deadline value in settings depending on whether tests are being run under coverage or not?

### ISSUE THREAD

**Issue by mulkieran** [HypothesisWorks/hypothesis#1758]
I decided to do a run of CI on my Hypothesis-using projects now that 4.0 is out to make sure I'd really taken care of all the deprecations and I hit a deadline error fairly soon in my coverage tests: https://travis-ci.org/stratis-storage/dbus-signature-pyparsing/jobs/452443242.

Obviously, this failure can be a bit unreliable. My guess is that it showed up intermittently among the more reliable deprecations, so ultimately I missed taking care of it.

Is there any established way to handle this problem? I'ld rather not set deadline to None on the tests when they're not running under coverage, 'cause I'ld like to be alerted if they start running slowly.

**Comment by Zac-HD** [comment]
```python
settings.register_profile("normal", ...)
settings.register_profile("coverage", parent=normal_settings, deadline=None)

if sys.gettrace() is None:
    settings.load_profile("normal")
else:
    settings.load_profile("coverage")
```

Conveniently this will also disable deadlines when non-coverage tracing tools are running, which is a good thing since they cause very similar slowdowns 😄

**Comment by mulkieran** [comment]
> ```python
> settings.register_profile("normal", ...)
> settings.register_profile("coverage", parent=normal_settings, deadline=None)
> 
> if sys.gettrace() is None:
>     settings.load_profile("normal")
> else:
>     settings.load_profile("coverage")
> ```
> 
> Conveniently this will also disable deadlines when non-coverage tracing tools are running, which is a good thing since they cause very similar slowdowns smile

Thanks, that's ideal.

**Comment by Zac-HD** [comment]
Glad to hear it - we should probably document the trick too :smile:
