### ISSUE TITLE
maximum recursion depth

### ISSUE THREAD

**Issue by martin-volf** [HypothesisWorks/hypothesis#1765]
Is there anything like a *maximum recursion depth*, or can it be tuned?  I'm observing the following:

My test expects data that is valid if:

 * it is a list where each element is valid data
 * it is a dictionary with a key `'value'` and the corresponding entry is valid data
 * it is `None`.
 
Now the strategy is something like
```python
lists(fixed_dictionaries(
    {'value': fixed_dictionaries(
        ...
        {'value': fixed_dictionaries(
            {'value': one_of(none(), just(''))})})}))
```

The `fixed_dictionaries` nesting depth is given by a parameter passed to `value_wrap`.  If the depth is 9 or less, Hypothesis finds the obvious minimal falsifying example:

```python
data=[{
    'value': {'value': {'value': {'value': {'value': {'value': {
        'value': {'value': {'value': ''}}}}}}}}}]
```

But with depth 10 or more it is somehow unable to use the second branch of the `one_of` strategy.

If I use `tuples` for nesting, it seems to work fine (or I have not found the critical depth); the construction with dictionaries can be rewritten to `tuple(X).map(lambda tpl: {'value': tpl[0]})` but this "fails to fail" with an empty example database too, looks like `map` is using the *maximum recursion depth* too (if there's such thing).

I looked at several settings parameters, `buffer_size` looked promising, but it does not seem to have any effect.  Is there anything else I can try to tweak?

See this [gist](https://gist.github.com/martin-volf/772eb167d12d83346523577281c9d331), run it like
```
$ python -m unittest wrapped
```

**Comment by Zac-HD** [comment]
I would suggest using an explicit [`st.recursive` strategy](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.recursive), and perhaps turning up the `max_leaves` parameter.

**Comment by DRMacIver** [comment]
There is internally a maximum recursion depth, yes. It's not currently tunable, because it's set to near the largest value that it can be before Hypothesis starts running into problems with Python's absurdly small stack sizes. 

The reason for the difference in the different strategies that you're seeing is basically the number of layers of nesting of strategies - the recursion depth is set by number of recursive calls to `draw`, which can vary between otherwise equivalent strategies.

**Comment by martin-volf** [comment]
@DRMacIver Thanks for the explanation. For the record, using composite strategies helps a little bit, seems that using `draw` directly instead of nesting `fixed_dictionaries` eats the stack slower, but it hits the bottom nevertheless.

By the way, I'm afraid this problem applies to all schema-driven strategies, such as @Zac-HD's `hypothesis_jsonschema.from_schema`: once the schema tree is deep enough, the variants at the tree leaves become to be ignored.
