### ISSUE TITLE
Provide support for storing data in other SQL databases

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#177]
There is currently the SQLite adapter. It uses a fairly standard API ([pep 0249](https://www.python.org/dev/peps/pep-0249/)) and I think reasonably portable SQL. It would be useful to extract this into its own thing and provide a generic API for an SQL backed example storage.

My particular priority here is PostgreSQL but it would be nice if it were generic and other databases were also supported, each with their own extra module.

**Comment by Zac-HD** [comment]
@DRMacIver - do we actually want this now that the SQLite example DB is on its way out?

**Comment by DRMacIver** [comment]
> @DRMacIver - do we actually want this now that the SQLite example DB is on its way out?

"maybe"

I think lets close the ticket and reopen it as part of some future hypothetical rethink of storage in Hypothesis. I *do* think we want to provide better support for some sort of centralised storage mechanism, but "just dump it in an SQL database" is probably not a sensible mechanism for that support.
