### ISSUE TITLE
Stack trace on ill-formed strategy

### ISSUE THREAD

**Issue by mulkieran** [HypothesisWorks/hypothesis#1794]
The stack trace itself is here:
https://travis-ci.org/stratis-storage/into-dbus-python/jobs/488523255

The problem is obviously that the flatmap function doesn't actually return a strategy.

```
    @given(dbus_signatures(
        min_complete_types=1,
        max_complete_types=1,
        blacklist="h").flatmap(lambda s: (strategies.just(s), STRATEGY_GENERATOR.parseString(s, parseAll=True)[0])))
```

I'm not certain whether it is a regression or not, I haven't tried it on previous versions of Hypothesis.

The version I'm using is 4.5.0.

**Comment by mulkieran** [comment]
This error is a tiny bit more interesting: https://travis-ci.org/stratis-storage/into-dbus-python/jobs/488538352, because I don't think that the value it complains about is actually a function, although that's what the error says.

**Comment by Zac-HD** [comment]
The two functions in these calls to flatmap return a tuple and a (lambda) function, respectively:

```python
lambda s: (
    strategies.just(s), 
    STRATEGY_GENERATOR.parseString(s, parseAll=True)[0]
)
lambda strat: (
    lambda sig: strategies.tuples(
        strategies.just(sig), 
        STRATEGY_GENERATOR.parseString(sig, parseAll=True)[0]
    )("(%s)" % strat)
)
```

I think some judicious placement of `tuples`, `one_of`, or just plain ol' parentheses would fix this.

**Comment by Zac-HD** [comment]
https://github.com/HypothesisWorks/hypothesis/blob/d879f8277ed7398ec4e45d56d50cc55d42e7161b/hypothesis-python/src/hypothesis/searchstrategy/flatmapped.py#L41-L43

Validating that `self.expand(source)` returns a SearchStrategy using `hypothesis.internal.validation.check_type` would be a good first contribution!

- Add this validation step to `hypothesis.searchstrategy.flatmapped.FlatMapStrategy.do_draw`
- Add a test in `tests/cover/test_searchstrategy.py`, using `with pytest.raises(InvalidArgument):`
- Add your name to the alphabetised list of authors in `CONTRIBUTING.rst`
- Write a RELEASE.rst file for a patch release (see open PRs and our changelog for examples)
- And open a PR for review :sparkles:

**Comment by mulkieran** [comment]
> The two functions in these calls to flatmap return a tuple and a (lambda) function, respectively:
> 
> ```python
> lambda s: (
>     strategies.just(s), 
>     STRATEGY_GENERATOR.parseString(s, parseAll=True)[0]
> )
> lambda strat: (
>     lambda sig: strategies.tuples(
>         strategies.just(sig), 
>         STRATEGY_GENERATOR.parseString(sig, parseAll=True)[0]
>     )("(%s)" % strat)
> )
> ```
> 
> I think some judicious placement of `tuples`, `one_of`, or just plain ol' parentheses would fix these tests.

You must have missed

> The problem is obviously that the flatmap function doesn't actually return a strategy.

in my statement of the issue. I'm glad we are agreed on the cause of the problem and that a stack trace is not the best response.

**Comment by Zac-HD** [comment]
Sorry @mulkieran - I do know (and appreciate) that you've been a contributor to Hypothesis for ages!  Turns out that I don't write my clearest comments first thing in the morning... I meant to agree with your diagnosis, and suggest improving this error message as a good first PR for someone else to take on.  Did you have a different resolution in mind?

**Comment by mulkieran** [comment]
Good morning! Why don't you or I just open a separate issue for this minor, but perhaps somewhat confusing for newcomers, problem? I'ld do it right now, but it's evening for me, and I have to catch a bus on the hour.

**Comment by Zac-HD** [comment]
Done (and good evening!); it's now issue 1796 😄
