### ISSUE TITLE
Improve error message if flatmap function doesn't return a strategy

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1796]
`.flatmap` is a method on strategies which takes a function, and the function must return another strategy.  If it does, all is well.  If it *doesn't*, you get an internal error - because we don't have any validation in there yet!

https://github.com/HypothesisWorks/hypothesis/blob/d879f8277ed7398ec4e45d56d50cc55d42e7161b/hypothesis-python/src/hypothesis/searchstrategy/flatmapped.py#L41-L43

Validating that `self.expand(source)` returns a SearchStrategy using `hypothesis.internal.validation.check_type` would be a good first contribution!

- Add this validation step to `hypothesis.searchstrategy.flatmapped.FlatMapStrategy.do_draw`
- [optional] Check that `callable(expand)` in `FlatMapStrategy.__init__`, and raise `hypothesis.errors.InvalidArgument` if it is not callable
- Add a test in `tests/cover/test_searchstrategy.py`, using `with pytest.raises(InvalidArgument):`
- Add your name to the alphabetised list of authors in `CONTRIBUTING.rst`
- Write a `RELEASE.rst` file - see open PRs and our changelog for examples.  This can be a patch release because we're not adding a new error, just improving existing errors.
- And open a PR for review :sparkles:

**Comment by jks7743** [comment]
Hey, since no one else seems to be working on this I'm going to take a shot at it, I'll let you know if I hit any snags.

**Comment by Zac-HD** [comment]
Awesome - I'm looking forward to it! Feel free to post a WIP pull request too, it doesn't have to be done to get a helpful review 😉

**Comment by kx-chen** [comment]
@jks7743 are you still working on it? I'd love to give this a shot if not.

**Comment by Zac-HD** [comment]
@kx-chen - go for it!  We only consider issues reserved for one week, so it's yours for the next seven days - after that we'll accept the first PR again :smile:
