### ISSUE TITLE
Implement a cmdline tool

### ISSUE THREAD

**Issue by sametmax** [HypothesisWorks/hypothesis#1799]
Fuzzying is something that is generally very useful, not just for function testing, and we could use hypothesis like afl.

Beside, ideas like hypothesis-pip (https://twitter.com/vorpalsmith/status/1093346524367474688) would be easier to implement.

**Comment by Zac-HD** [comment]
@njsmith's `hypothesis-pip` concept could be implemented like this actually: a custom strategy that finds "allowed but probably invalid" dependency combinations, and a function that shells out to install them and run the tests.  A really nasty option would be to do this to transitive dependencies too!  But that's not really in scope for the core Hypothesis project; it's two functions and a pile of shell scripting.

We do have #171 for a long-running fuzzing mode, but it will still be running functions just like the current Hypothesis API!  If it's not running Python functions (which can of course "shell out" to other programs...), a classic fuzzer like AFL might be better for the job than a property-based testing library like Hypothesis.  What use-case did you have in mind?

**Comment by sametmax** [comment]
Just having an afl equivalent in pure Python: it would work anywhere python is available, and not just Linux.

**Comment by Zac-HD** [comment]
That's quite a distinct project from Hypothesis unfortunately - it would probably be easier to start from scratch, though I guess you could use Hypothesis as part of the project.  Closing the issue as out of scope :confused:
