### ISSUE TITLE
Support generating Python code (via Lark)

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1806]
A subticket of #1804 both because there are a number of idiosyncracies of the Python examples and because I particularly care about supporting generating Python.

This ticket will be complete when we have a `python` strategy somewhere in the codebase, probably in `hypothesis.extra.lark` initially.

**Comment by Zac-HD** [comment]
I have a prototype I call [Hypothesmith](https://github.com/Zac-HD/hypothesmith), from PyCon US and AU sprints.  I'm keeping it outside the main Hypothesis repo for now, to be free of compatibility and version support issues without complicating our messaging about support here.  It works though, and has already found several issues in CPython parsing!
