### ISSUE TITLE
Remove use of doctest from documentation

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1823]
As of #1822 we no longer run doctests in CI. This means that we have a bunch of doctest based documentation that will gradually drift out of date. We should fix that by removing it.

Much of this will just be a case of deleting examples from documentation (😢) but it requires a certain amount of rewriting and checking of documentation as we go to makes ure it still makes sense.

**Comment by Zac-HD** [comment]
Closed by #1822.
