### ISSUE TITLE
Replace usage of `getrandbits` with calls to `draw_bits`

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#1827]
In `hypothesis.internal.conjecture.utils` we have a `getrandbits` method which takes a `ConjectureData` and a number of bits to draw. On `ConjectureData` we have a method `draw_bits` which takes a number of bits to draw.

You might reasonably assume that these functions do the same thing. Certainly I did. However, you would be wrong! 

For reasons that I am currently unaware of, if you make the following replacement:

```python
def getrandbits(data, n):
    return data.draw_bits(n)
```

then the endpoint tests in `tests/cover/test_float_nastiness.py` start failing.

The source of this difference is the setting of the mask in `ConjectureData`. If you comment out the line `self.masked_indices[self.index] = mask` then this starts working.

Why? Beats me.

There are basically two possibilities:

1. There's a really subtle bug somewhere.
2. This is basically just working by coincidence at the moment, as a result of some interaction between the strategies and our weird mutator.

My hunch is that it's the latter.

**Comment by Zalathar** [comment]
A large factor seems to be the code that splices the novel prefix over part of the mutator's output:

https://github.com/HypothesisWorks/hypothesis/blob/35b2c3cbad2e7eafb7bd3e18271d383cb3624698/hypothesis-python/src/hypothesis/internal/conjecture/engine.py#L479-L490

I see lots of cases where `draw_max` produces bytes that *should* find the desired endpoint (lots of `0xff`), but then the prefix bytes get spliced over the top and the opportunity is lost.

I haven't fully determined why this isn't also hurting with the existing `getrandbits` implementation, but it's plausible that the lack of normalization gives the novel-prefix generator more chances to stumble across a suitable prefix while `draw_max` is in use.

**Comment by Zalathar** [comment]
The prefixer and the mutator are both doing their respective jobs, so the underlying problem looks like a design hurdle rather than an implementation slip-up.

I suspect the long-term solution is to integrate prefix-generation and mutation, so that we first consult the mutator, and only override it if it produces something that has already been exhausted.

That sounds like a hassle, but maybe it will be easier once the block-based tree is in place.

**Comment by Zalathar** [comment]
I can reproduce this effect in endpoint tests for `st.integers(0, 2 ** n - 1)` for values of `n` in the low 20s or so.

**Comment by Zac-HD** [comment]
Possibly related to #909?  I thought that was fixed, but maybe it just got harder to trigger...

**Comment by DRMacIver** [comment]
> I suspect the long-term solution is to integrate prefix-generation and mutation, so that we first consult the mutator, and only override it if it produces something that has already been exhausted.

I have a plan, outlined [here](https://notebook.drmaciver.com/posts/2019-02-15-14:37.html) that would let us do away with the prefixer entirely I think, by allowing us to cache interactions against arbitrary `ConjectureData` objects instead of just buffers, which will mean we can write fairly complex mutators and still cache them without worrying about the prefixes.

All that being said, the current mutator code is basically trash. The only reasons it still exists are:

* It works *slightly* better than not having it in some cases (including our test suite, unsurprisingly).
* Any attempt to replace it should start with a serious think about how to evaluate the difference, and we/I haven't done that.
