### ISSUE TITLE
Off-by-one in step generation for block programs

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#1839]
This is the code that generates indices to run each block program at:

https://github.com/HypothesisWorks/hypothesis/blob/931796887bfb2f498d5e017215a9c755670efa1c/hypothesis-python/src/hypothesis/internal/conjecture/shrinker.py#L1322-L1326

For example, if our shrink target has 100 blocks (indices 0–99), and the block program has 2 steps, then we'll generate indices `hrange(98)`, i.e. 0–97.

This means that we will never try running the block program against at block 98, covering blocks [98,&nbsp;99]. In theory, that's a bug.

For `block_program("XX")` this isn't a problem, because deleting a suffix of the current target is guaranteed to be useless (and will be caught by the tree cache anyway).

For `block_program("-XX")` we could conceivably miss a legal shrink, though I'm not sure how likely that is in practice.

**Comment by Zalathar** [comment]
I think this has already been fixed by the pending changes in #1836, but I wanted to bring it up explicitly.

**Comment by DRMacIver** [comment]
Whoops, so we do. Good point.

**Comment by Zalathar** [comment]
It occurs to me that if `"-XX"` could have succeeded in the rightmost position, then that same shrink can be found by ordinary block-minimisation on the third-last block.

So this bug should be completely benign for now.
