### ISSUE TITLE
CI should push fat binaries to rubygems.org for hypothesis-ruby

### ISSUE THREAD

**Issue by Kavec** [HypothesisWorks/hypothesis#1842]
My team at [Flexport](https://flexport.engineering/) would like to start using hypothesis-ruby internally, but it's a non-starter for me to insist that everyone installs Rust for something that is supposed to be 'opt-in, use it where it helps', even with how easy it is to get Rust up and running. What I do have, though, is backing and support to put in the effort to make hypothesis-ruby usable for our engineers long-term.

In theory this is something that could be addressed at the [Helix](https://github.com/tildeio/helix) level. They even have binary distribution on their [roadmap](https://usehelix.com/roadmap), but as far as I can tell activity on that project as stalled and I'm not confident that any change there would propagate back here soon enough to keep business buy-in. Since the business would rather roll our own than wait several months for results, enhancing (or replacing) Helix is out of scope for me. Using Rantly/others for property testing instead is a no-go due to ergonomics and/or performance issues. So too, of course, is rewriting the Conjecture engine in not-Rust— that just seems bizarre.

Which leaves the final option: work on the CI here and ensure the gem can be installed without the Rust toolchain. 

Before I start getting my hands dirty on this, @DRMacIver mentioned on IRC that the CI configuration is a bit bespoke. I see references to Travis CI, Circle CI, Azure Pipelines, AppVeyor.. is that all of them? What is the minimal set of CI configurations that need to be changed here? And, just to be safe, has anyone drafted some plans previously to get this done that I'm missing?

**Comment by Zac-HD** [comment]
Hi @Kavec!  Awesome to hear that Hypothesis would be valuable for you 😄 

For hypothesis-python, we currently use Travis, Appveyor, and CircleCI - but we're planning to move *everything* to Azure pipelines soon.  I haven't done much with the Ruby version but I think it might just be using Travis!

For this issue, the cleanest path might be to migrate the whole Ruby build to Azure pipelines and build+upload the fat binaries from there.

**Comment by Kavec** [comment]
Awesome, thanks! Moving everything to Azure pipelines sounds pretty sensible. I'll carve out some time and should be able to get to this within the next week or two!

**Comment by Zac-HD** [comment]
As noted in #2191, 

> Hypothesis for Ruby is a reasonable start on a port of Hypothesis to Ruby. It worked pretty well, but uses a core Rust implementation that is unfortunately not compatible with recent versions of Rust, due to its dependency on Helix (which now seems to be mostly unmaintained) and as a result is currently unsupported pending a rewrite of the bridging code between Rust and Ruby. We don't at present have the time or funding for this project, but it is likely not a massive undertaking if anyone would like to provide either of these. 
>
> Additionally there is a port of the core engine of Hypothesis, Conjecture, to Rust. It is not feature complete but in the long run we are hoping to move much of the existing functionality to Rust and rebuild Hypothesis for Python on top of it, greatly lowering the porting effort to other languages. Any or all of these could be turned into full fledged implementations with relatively little effort (no more than a few months of full time work), but as well as the initial work this would require someone prepared to provide or fund ongoing maintenance efforts for them in order to be viable.

So I'm closing this issue as Hypothesis for Ruby is dormant pending funding or new maintainers :confused:
