### ISSUE TITLE
Massive performance drop in test_blacklisted_characters

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#1864]
While testing some other changes, I stumbled across the fact that `test_blacklisted_characters` now takes a very long time to run.

This can be seen in https://travis-ci.org/HypothesisWorks/hypothesis/jobs/504749908, and seems to be linked to #1846 in some way.

**Comment by Zalathar** [comment]
Sadly I haven't had a chance to track this down more precisely, or to figure out whether it's a real bug or a test bug.

**Comment by Zalathar** [comment]
I've determined that the slowdown is in the `assert_no_examples` part of the test.

Looking through the `--hypothesis-verbosity=debug -s` output, it is doing more-or-less what it was doing before: It quickly finds all of the unique output values, and then spends the rest of its exploration budget generating increasingly-elaborate rejection-sampler sequences.

The difference is that instead of finishing in an instant, this process becomes slower and slower (inconsistently) as the test continues to run.

**Comment by Zalathar** [comment]
I traced the problem to `generate_novel_prefix` in `DataTree`:

https://github.com/HypothesisWorks/hypothesis/blob/73e41c3514e073a1c1249d5bfd7ab7b46f47c6ec/hypothesis-python/src/hypothesis/internal/conjecture/datatree.py#L256-L284

As the test continues to run, the `while True` loop takes more and more iterations to complete on average. It often requires hundreds or thousands of retries before it can find a novel prefix by chance.

The underlying cause is that this novelty-generator has no way to detect and avoid exhausted parts of the tree. So when novel prefixes are rare, it spins over and over until it gets lucky enough to stumble upon one.

**Comment by Zalathar** [comment]
This effect isn't specific to `characters`. I can reproduce it with this:

```python
def test_integers():
    assert_no_examples(st.integers(0, 5), lambda x: False)
```

Range sizes that are `(2 ** n) - 2` are the most severely affected.

**Comment by DRMacIver** [comment]
> The underlying cause is that this novelty-generator has no way to detect and avoid exhausted parts of the tree. So when novel prefixes are rare, it spins over and over until it gets lucky enough to stumble upon one.

This isn't quite true. Note that it detects exhausted parts of the tree up until the point where the first possible branch occurs. This means that when there is a long forced prefix it finds that without spinning. I had (apparently mistakenly) assumed that that would be enough and that the cases where there were multiple possible branches to take there but we still got high rejection rates would be relatively uncommon.

I think a fix that is *probably* sufficient for this case and is equivalent in result to the current is to always have the first non-forced block chosen uniformly at random from the set of available possibilities. Maybe something more sophisticated is needed in the general case.

**Comment by Zac-HD** [comment]
`@pytest.mark.skip` was added in 354258d4e2b0298ca6768727c8d41067c3b9ca64 so this isn't killing our CI, but the underlying problem is still there.
