### ISSUE TITLE
hypothesis cannot find any example for grammar

### ISSUE THREAD

**Issue by ligurio** [HypothesisWorks/hypothesis#1881]
hypothesis cannot find any example for grammar below and raise exception ```NoExample```.
```
start: palindrome
palindrome: palindrome | "a" palindrome "a" | "b" palindrome "b" | "c" palindrome "c" | "d" palindrome "d" | "e" palindrome "e" | "f" palindrome "f" | "g" palindrome "g" | "h" palindrome "h" | "i" palindrome "i" | "j" palindrome "j" | "k" palindrome "k" | "l" palindrome "l" | "m" palindrome "m" | "n" palindrome "n" | "p" palindrome "p" | "q" palindrome "q" | "r" palindrome "r" | "s" palindrome "s" | "t" palindrome "t" | "u" palindrome "u" | "v" palindrome "v" | "w" palindrome "w" | "x" palindrome "x" | "y" palindrome "y" | "z" palindrome "z"
```

Is it a bug of hypothesis?

[Source code for hypothesis.errors](https://hypothesis.readthedocs.io/en/latest/_modules/hypothesis/errors.html?highlight=NoExamples):
```
class NoExamples(HypothesisException):
    """Raised when example() is called on a strategy but we cannot find any
    examples after enough tries that we really should have been able to if this
    was ever going to work."""
```

hypothesis 4.9.0, Ubuntu 18.04 x86_64

**Comment by DRMacIver** [comment]
I think this is correct behaviour, isn't it? Your grammar doesn't have any valid examples because you've not allowed the empty string to be a palindrome.

**Comment by ligurio** [comment]
It looks strange for me, because it works with [EBNF fuzzer](https://github.com/ligurio/gromit/blob/master/process_ebnf.go), which actually do same as Hypothesis do.

**Comment by DRMacIver** [comment]
I think you've translated the EBNF wrong. https://github.com/ligurio/gromit/blob/master/ebnf/palindrome.ebnf starts with `letter | ...` while your palindrome definition starts with `palindrome | ...`

**Comment by ligurio** [comment]
Oh, it was my wrong translation from EBNF grammar. Now it works as expected. Thanks!
