### ISSUE TITLE
Failed tests when using pypubsub

### ISSUE THREAD

**Issue by jkbgbr** [HypothesisWorks/hypothesis#1897]
I use hypothesis testing on the model of an app that uses the pypubsub module for app-intern communication to detach the GUI and the model (MVC pattern).

I regularly run into failed tests due to a pypubsub exception that is thrown if the listener of a pubsub topic gets garbage collected. This may happen as the pypubsub module uses weakrefs (explained [here](https://pypubsub.readthedocs.io/en/v4.0.3/usage/usage_basic_tasks.html#id4), under Warning).
What happens is (my __guess__):
* pypubsub fails as the model runs wrapped in hypothesis and listeners get garbage collected,
* consequently hypothesis fails, as some tests can not be reproduced on a second try.

The error can be eliminated by simply commenting out a call to subscribe a certain method for a pubsub topic. This would be OK for development for now but would render some tests impossible at a later stage.

The full trackback is attched (slightly edited to obfuscate stuff): [trackback.txt](https://github.com/HypothesisWorks/hypothesis/files/3006904/trackback.txt).

Can someone possibly help me on this issue?

**Comment by Zac-HD** [comment]
Hi @jkbgbr - the Hypothesis problem here is that your test function *must* perform all the setup and teardown necessary to isolate each execution of the inner function.  If runs aren't isolated, Hypothesis can't reliably explore the search space, let alone find minimal examples.

So I would try setting up the subscriptions *inside* the test function.

**Comment by jkbgbr** [comment]
Hi @Zac-HD, thanks for the fast respone.

Subscribing / unsubscribing by hand is certainly an option, but makes maintenance really hard and therefore a practice not encouraged. OTOH as hypothesis - in my case at least - is a unit test tool, disabling all outbound communication should be OK.

So I cleared the hypothesis databases and in each tests using hypothesis I explicitly clear all topics after the tested objects are created using `pub.getDefaultTopicMgr().clearTree()`. 

Voilá, no issues.
