### ISSUE TITLE
test_removes_needless_steps fails only under coverage?

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1907]
```python-traceback
_________________________ test_removes_needless_steps __________________________
Traceback (most recent call last):
  File "/home/travis/build/HypothesisWorks/hypothesis/hypothesis-python/tests/cover/test_stateful.py", line 830, in test_removes_needless_steps
    run_state_machine_as_test(IncorrectDeletion)
  File "/home/travis/build/HypothesisWorks/hypothesis/hypothesis-python/.tox/coverage/lib/python3.6/site-packages/_pytest/python_api.py", line 729, in __exit__
    fail(self.message)
  File "/home/travis/build/HypothesisWorks/hypothesis/hypothesis-python/.tox/coverage/lib/python3.6/site-packages/_pytest/outcomes.py", line 113, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE <class 'AssertionError'>
```

Both [on Pipelines](https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=1875&view=logs&jobId=d1a131c4-77ff-5e6b-1472-1f9b988f8070&taskId=9188b80d-c627-5cf4-3df1-73e650170c8f&lineStart=296&lineEnd=297&colStart=1&colEnd=1) and [on Travis](https://travis-ci.org/HypothesisWorks/hypothesis/jobs/513687673#L962).  No idea why, since all the non-coverage runs of the same code passed and the coverage runs passed too before merging :confused: 

I also can't reproduce the problem locally.

**Comment by Zalathar** [comment]
I was able to see this locally, but only once so far.

(This was while I was on my #1904 branch, though that's probably coincidence.)

**Comment by rsokl** [comment]
I haven't been able to reproduce this locally, but it did hit me on #1878

**Comment by Zalathar** [comment]
I've been able to reproduce this several times now, always through `./build.sh check-coverage`.

For me, it seems to be a lot more common than can be explained by ordinary flakiness. Something suspicious is going on.

**Comment by DRMacIver** [comment]
My guess would be that the culprit is that [we run coverage tests with different settings than the main tests](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/tests/common/setup.py#L87), so it's going to be a function of those settings rather than the fact that it's actually running under coverage.

If you want a faster way to reproduce the problem, maybe edit those settings and rerun the test on its own?

**Comment by Zalathar** [comment]
I haven't succeeded in reproducing the issue outside of `check-coverage`.

I have found that `check-coverage` fails consistently for me, as long as pytest's `--failed-first` doesn't activate. (To get around this I cancel and re-start `check-coverage`.)

Commenting out `test_flatmap_with_invalid_expand` (#1905) seems to make the failure disappear. This makes no sense on its face, so there seems to be some kind of global-state interference happening somewhere.

**Comment by Zalathar** [comment]
If I undo #1906, that also seems to make the failure disappear.

So merging both of those PRs somehow got us into a state where `test_remove_needless_steps` fails consistently under `check-coverage`, despite neither PR being enough to trigger it in isolation.

**Comment by Zac-HD** [comment]
We've worked around this by just slapping on a `@settings(derandomize=True)`, but it would be nice to understand and fix the root cause at some point.

**Comment by Zalathar** [comment]
Indeed.

This has all the hallmarks of an ordinary flaky test, yet under the right circumstances it was failing consistently. If I get a chance, I’d like to figure out what was really happening.

**Comment by Zalathar** [comment]
Findings so far:

- The test is indeed generating 10 examples, none of which fail.
- Across multiple runs, the examples generated are *exactly the same*. This is suspicious.
- Across multiple runs, Python's `random.getstate()` is identical at the start of `test_removes_needless_steps`.

My current guess is that one of our tests sets the Python RNG to something deterministic, and then fails to properly restore it. This results in the top-level Python RNG unexpectedly being consistent across multiple runs for the remainder of the test suite.

(This is all assuming that a deterministic top-level Python RNG is unintended.)

**Comment by Zalathar** [comment]
Debugging notes:

An important local change I made was to always print the sub-test's output in `test_removes_needless_steps`, regardless of whether it succeeds or fails:

```python
    try:
        with capture_out() as o:
            with pytest.raises(AssertionError):
                run_state_machine_as_test(IncorrectDeletion)
    finally:
        print(o.getvalue())
```

I had to remove `@Settings(derandomize=True)` to undo #1912 and let me keep investigating the bug, and I replaced it with `@Settings(verbosity=Verbosity.debug)` to print details about what was generated.

I removed `-ff` from the coverage line in `tox.ini`.

I was able to print the Python random state inside the test as follows:

```python
import random
print(random.getstate())
```

**Comment by Zac-HD** [comment]
Related to #1295 then?

**Comment by Zalathar** [comment]
I assume it's something along those lines, though I haven't confirmed it yet.

I'll have to figure out a good way to pinpoint what's responsible for leaking a deterministic RNG state into the rest of the test suite.

(This theory neatly explains why I couldn't reproduce the issue when `-ff` kicked in, or in manual `pytest` even with a reduced `max_examples`.)

**Comment by Zalathar** [comment]
The trouble appears to start somewhere in `tests/cover/test_conjecture_engine.py`.

**Comment by Zalathar** [comment]
This looks like the culprit:

https://github.com/HypothesisWorks/hypothesis/blob/05623d2cb28ae5f57bab3e917e0cea22bf0b4f15/hypothesis-python/tests/cover/test_conjecture_engine.py#L337-L350

**Comment by Zalathar** [comment]
Replacing that with `deterministic_PRNG` didn't seem to make the original failure disappear, so maybe there are multiple culprits?

**Comment by Zalathar** [comment]
Here's the next culprit:

https://github.com/HypothesisWorks/hypothesis/blob/05623d2cb28ae5f57bab3e917e0cea22bf0b4f15/hypothesis-python/tests/cover/test_flakiness.py#L84-L125

For some reason, `random_module()` is not restoring the old random state after the test is complete.

I haven't tracked down why, but my guess is that the mechanism it uses isn't prepared to handle nested `@given`.

**Comment by Zalathar** [comment]
This is my gadget for finding where the global random state has become deterministic:

```python
def test_rng_detective():
    import random
    import sys
    with open("/Users/stuart/dev/hypothesis/rng-detective.txt", "a") as f:
        f.write("STATE %s:%d %r\n" % (__name__, sys._getframe().f_lineno, random.getstate()))
    sys.exit()
```

I put this in a test file, and then run `./build.sh check-coverage` twice. If the states match, pollution occurred before the detective ran. I can then bisect across and within test files to find the polluting tests.
