### ISSUE TITLE
Ensure compatibility with Django 2.2 and run it in CI

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1909]
[Django 2.2 has just been released](https://www.djangoproject.com/weblog/2019/apr/01/django-22-released/), which means we should start running against it in CI and add it to the list of supported versions in documentation.

That should be fairly simple, since most of the incompatible changes seem to be for third-party databases.  However we [have this test failure](https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=1880&view=logs&jobId=70e7c352-5680-5004-a987-5b5fc78e2b1a&taskId=36365705-09d6-5cbf-fdf3-d70278821097&lineStart=554&lineEnd=555&colStart=1&colEnd=1), which I think is because our example/test project is older than some current best practices.

**Comment by Zalathar** [comment]
The fact that Django 2.2 exists causes our existing `check-py36` to retroactively fail, because it installs `django>=1.11` and ends up with 2.2.
