### ISSUE TITLE
register custom strategies for NewTypes

### ISSUE THREAD

**Issue by PJCampi** [HypothesisWorks/hypothesis#1911]
Hey guys,

First off thanks for the great work with hypothesis! It's an extremely useful testing tool.

I read from previous open issues that you have added support for `NewType` in `from_type`. It is however currently not possible to register a custom strategy for a `NewType`. I get the same error as you fixed in `from_type`:
`hypothesis.errors.InvalidArgument: custom_type=%r must be a type`

I use hypothesis v. 4.14.2.

**Comment by Zac-HD** [comment]
What version of Python?  Can you provide example code?

**Comment by PJCampi** [comment]
I use python 3.7. 

An Example:

```
Name = NewType('Name', str)

register_type_strategy(Name, characters(whitelist_categories=('L',)))
```

**Comment by PJCampi** [comment]
I just made a pull request for this. I hope that's ok:
`https://github.com/HypothesisWorks/hypothesis/pull/1914`

I also had a test, which I did not know where to add. It very naive - I would have rather tested against the type of the strategy returned but from_type returns a deferred strategy which I didn't know how to forward:

```
def test_new_type():

    # type not registered
    MyNewType = typing.NewType('MyNewType', str)
    example = st.from_type(MyNewType).example()
    assert isinstance(example, str)

    # register type and check again
    strategy = st.characters(whitelist_categories='L')
    st.register_type_strategy(MyNewType, strategy)
    example = st.from_type(MyNewType).example()
    assert isinstance(example, str) and len(example) <= 1
```
