### ISSUE TITLE
Verify that our test suites aren't accidentally deterministic

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#1919]
As seen in #1907/#1918 and #1266/#1295, it's scarily easy to accidentally pollute the global RNG with a deterministic seed or state after a test ends.

This causes all subsequent tests in the suite to run with the same random state every time, which undermines the ability of `@given`-based tests to find novel bugs across different runs (similar to `derandomize=True`).

It would therefore be useful to find some way to automatically detect or prevent this mistake, so that it won't reoccur.

**Comment by Zalathar** [comment]
The technique I used in #1907 was to create a fake test that appends the current random state to a file, and then run the test suite twice to see if the same state was recorded.

I could then bisect across and within test files by moving this fake test around, to pinpoint trouble sites.

This is effective, but it's also a laborious manual process.

**Comment by Zac-HD** [comment]
This sounds to me like a case for a project-specific pytest plugin - easy to run something before and after every test, and I'm pretty sure there's an end-of-test-suite hook too that can emit the failure.

**Comment by Zalathar** [comment]
Quick sketch of a potential approach:

- Use a custom pytest plugin to read the random state after each test, and append it to a user-specified log file together with the test filename and test name.
- Run the entire test suite twice, ideally in parallel, writing random state to separate log files.
- Diff the two files, and fail if any lines match.

Because it requires extra test runs, this is probably not worth adding to the regular CI task list. But I could imagine it being some kind of daily or weekly recurring task that raises an alert if it fails.

**Comment by Zac-HD** [comment]
I was thinking that it would be sufficient to collect a set of `(test_id, state_before, state_after)` triples, and check that there are no tests with different `state_before`s and the same `state_after`.

That seems like the definition of a leak, and wouldn't require us to re-run anything.  Am I missing something again?

**Comment by Zalathar** [comment]
My definition of a leak is two independent test runs containing the same `(test_id, state_after)` tuple. Once that occurs, everything after that point will be unintentionally identical in both test runs.

Your definition is different enough that I'll need to think about it before I can have an opinion.

(At a glance, it seems like it will catch some instances, and miss others.)
