### ISSUE TITLE
Idea: Hypothesis command line interface (CLI)

### ISSUE THREAD

**Issue by moreati** [HypothesisWorks/hypothesis#1925]
A thought struck me while using [perf](https://perf.readthedocs.io/en/latest/). It would be nice to have a quick and dirty way to run Hypothesis against something. E.g.

```sh
python -m hypothesis --given "s=text()" "assert s == s.upper().lower()"
```
```sh
python -m hypothesis --setup "import foo" --given "x=integers();y=integers()" "assert foo.bar(x, y) == foo.bar(y,x)"
```

I've no idea how trivial or otherwise this would be to implement, but if there's interest I can try a prototype. Thoughts?

**Comment by Zac-HD** [comment]
I'd love to see this as an external package, e.g. `hypothesis-cli`, but would be nervous about committing to support any CLI without that external validation that it works for users (and has users) for the long haul.

The other angle I was thinking about for a CLI is a non-ugly way to drive nonPython code with Hypothesis, or even query a "hypothesis server" for a value matching some schema.  Shrinking would be really annoying to support though, and without it I don't think Hypothesis would stand out...

**Comment by DRMacIver** [comment]
> The other angle I was thinking about for a CLI is a non-ugly way to drive nonPython code with Hypothesis, or even query a "hypothesis server" for a value matching some schema. Shrinking would be really annoying to support though, and without it I don't think Hypothesis would stand out...

One fairly easy thing we could do here would be to use the lark support. Take a lark definition plus a test executable, and pass values from the former into the latter until there's a non-zero exit code.

**Comment by Zac-HD** [comment]
It's pretty easy ("just" an interface design question) if Hypothesis is driving the execution of the system under test, but an open-ended request/response protocol is a little trickier.  On the other hand it's also useful for web as well as CLI testing...

I have some notes for a json-schema implementation, which amount to: clients (1) request an input from some strategy, get response value; (2) optionally post pass/fail/skip status; (3) go to 1 with the same or a different strategy.  The server then starts in stateful supports-shrinking mode, and discards it each time the strategy changes or (2) gets skipped; when Hypothesis is done shrinking it just keeps repeating the minimal input.

---------------------

But for both that idea and the simpler CLI here, I think the way to go is an external implementation first.

**Comment by moreati** [comment]
> I'd love to see this as an external package, e.g. `hypothesis-cli`

Makes sense. First prototype at https://gist.github.com/moreati/50159ecc1074452ce340b96d8cc95030

**Comment by Zac-HD** [comment]
Looks good!  For backwards compatibility I'd be keen to put this behind a subcommand like `hypothesis cli --given ...` - that way we can easily add e.g. a web server version as `hypothesis serve -p 8080 ...` later.  ([*Namespaces are one honking great idea -- let's do more of those!*](https://www.python.org/dev/peps/pep-0020/#the-zen-of-python))

With that though, and tighter validation, I'd be happy to see a PR for this 😄

**Comment by moreati** [comment]
Thank you, glad you like it. As per earlier discussion I was going to continue with a third party package, proposed name `hypothit`, but I can do it here instead.

I'll try to make both `hypothesis <x> --given ...` and `python -m hypothesis <x> --given ...` work. However I'd like to find a more descriptive name for x than "cli".

**Comment by DRMacIver** [comment]
>  I was going to continue with a third party package, proposed name hypothit, but I can do it here instead.

I'd like to stick to a third party package for now. I'm definitely interested in eventually merging it upstream, but a third party package gives a bit more room for experimentation before we stabilise it.

**Comment by Zac-HD** [comment]
Closing this broad issue - let's open a new one to consider specific external packages for merging once they're ready 😄

**Comment by moreati** [comment]
I've made an initial release of [hypothit](https://pypi.org/project/hypothit/). I won't publicize for a few days, while I work on CI and documentation.
