### ISSUE TITLE
Improve `extra.numpy.array_shapes()`

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1928]
https://github.com/HypothesisWorks/hypothesis/blob/07f32bae6355bac2893eaf50a556f7957a8b2036/hypothesis-python/src/hypothesis/extra/numpy.py#L403

- [ ] The current list of arguments is pretty good, but it would be better if setting `min_dims` or `min_side` automatically chose an appropriate value for the maximum, instead of giving an error if it was greater than the current default.  The max args should therefore default to None, and be set inside the strategy if needed.
- [ ] We should validate that `max_dims` is not more than `32` (the limit set by Numpy).
- [ ] We should check that all the arguments are integers with `check_type`.

This would be a minor release, as the change is visible to users.  See our contributing guide for where to add your name to the list of authors and how to write a changelog!

**Comment by HimanshuJanbandhu** [comment]
Hi, I would like to take this issue.

**Comment by endolith** [comment]
Would it make sense to add an optional `max_size` parameter?  Often it's good to test long 1D arrays (to make sure it doesn't screw up with large amounts of data), and also small highly-dimensional arrays (to make sure it handles dimensions correctly), but large multi-dimensional arrays rapidly use up all available memory.

**Comment by Zac-HD** [comment]
Hmm, that's definitely a useful feature!  However I can't think of a way to cap the element count by construction without either skewing the distribution or making shrinking much less efficient 😕 

Instead of adding an argument, I think we should suggest limiting element count with `.filter(lambda shape: np.prod(shape) <= MAX_ELEMENTS)` in the docstring for `array_shapes`.

**Comment by pckroon** [comment]
If I may chip in: what I find missing in the signature is the ability to specify e.g. a shape that has up to length 3 in dimension 1, and lengths between 2 and 5 for all other dimensions (arbitrary many). 

I'm not sure whether this is in scope, and if it is, how to solve it. Simply passing a strategy from which lengths can be drawn would make this function completely redundant.

**Comment by Zac-HD** [comment]
> What I find missing in the signature is the ability to specify e.g. a shape that has up to length 3 in dimension 1, and lengths between 2 and 5 for all other dimensions (arbitrary many).

Personally I think this kind of thing is specific enough that it should be built by users:

```python
# Fixed length is easier, obviously - just `tuples(integers(...), integers(...), ...)`
odd_shapes = tuples(integers(0, 5), lists(integers(2, 5))).map(lambda x, ys: tuple(ys + [x]))
```

It's definitely important to be able to define strategies like this, but if we make the `array_shapes` strategy too general it becomes a whole other API to learn - and we already have a perfectly good way to customise strategies *including* tuples of integers.

**Comment by pckroon** [comment]
> Perhaps another documentation issue - maybe we should have a "Numpy recipes" page?
That would definitely solve it. I agree that it would be highly convenient to have an easy-to-use interface to create shapes for most use cases. It is something that should be explicitly decided though, rather than turning out to be an unfortunate side-effect :)

**Comment by Zac-HD** [comment]
Agreed!  If you have some specific (hopefully common) use-cases that are not well served by `array_shapes`, `broadcastable_shapes`, `st.lists(...)`, and `st.tuples(...)` in some simple combination, it would be great to discuss them and see if we can come up with a strategy that would be helpful :smile:

**Comment by pckroon** [comment]
Not yet, but maybe later :)
For now I just thought I had something to contribute to the discussion.

**Comment by endolith** [comment]
One strategy I was trying to create is `numeric_array_likes()`, which is all numeric dtypes (but with optional exclusion of inf/nan) or object arrays of other numeric types like decimal/fraction, in either array form or list of lists (also maybe matrices, masked/sparse arrays, etc.) to make sure that scipy functions work with the wide variety of possible numpy array_likes that people will throw at them.
