### ISSUE TITLE
Add `st.slices(sequence_size)` strategy

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1929]
Taking slices of an array index is really useful for Numpy, but not Numpy-specific - a `slices()` strategy could be useful for any standard library sequence type, to say nothing of other array libraries (not *all* of which depend on Numpy).

This issue proposes a simpler version of the [`slice_index`](https://github.com/rsokl/MyGrad/blob/62912d8bbb1c79ca3a72578a3e68720e4c29c594/tests/custom_strategies/__init__.py#L212) strategy from @rsokl's MyGrad library (see #1829), to be called `slices`.  At least for the first version, we will only support a single argument - an integer length of the sequence this slice could index.  The documentation could recommend using `builds(slice, ...)` for users who need to control specific values.

The implementation should shrink to selecting fewer elements and earlier elements, and smaller and positive step sizes.  It should only ever select zero elements if `start == stop`, i.e. not because the `step` value has the wrong sign.  I'd probably use `@composite` for the first draft.

**Comment by danieljwest** [comment]
Taking a shot at working on this
