### ISSUE TITLE
Support `slice` in `st.from_type()`

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1932]
The `slice` builtin is actually a type - so it would be nice to support it in `st.from_type()`.

This would involve adding it to the mapping in `hypothesis.searchstrategy.types`, as `slice: builds(slice, none() | integers(), none() | integers(), none() | integers())`, and adding a test to `tests/cover/test_type_lookup.py`.  Finally, you'll need to add your name to the list of authors in CONTRIBUTING.rst and write a changelog in `hypothesis-python/RELEASE.rst`!  (see other PRs or the contributing guide for how, or just ask :smile:)

**Comment by mboekhold** [comment]
Hey @Zac-HD , I'd like to take this, can I get some guidance submitting this PR?

**Comment by Zac-HD** [comment]
Check out `CONTRIBUTING.rst` in this repo to get started - that and the notes above should cover most of it.  I'm happy to answer specific questions if you have some.

(I should warn you that our `good first issue` tag means "good first contribution *to Hypothesis*", which can be pretty challenging as a new open-source contributor.  If you get a draft pull request together I'd be happy to help though :smile:)

**Comment by mboekhold** [comment]
I'll give it a try smile, just making sure I'm looking in the right place, If i understand correctly, the mapping is done in from_typing_type, which looks in the _global_type_lookup.items dict?, So I need to add it in the _global_type_lookup dict?

**Comment by Zac-HD** [comment]
The lookup is done in `hypothesis._strategies.from_type`, but you're right in thinking that you need to add it to `hypothesis.searchstrategy.types._global_type_lookup`.  Just add it to the bottom of the list, just above the "pull requests welcome" comment!

https://github.com/HypothesisWorks/hypothesis/blob/a0a03770e0d53dc96158266d3fff78f03746d0a1/hypothesis-python/src/hypothesis/searchstrategy/types.py#L188-L191

FYI: check out the [GitHub markdown guide](https://guides.github.com/features/mastering-markdown/) - using "`" backticks for names from code can make things easier to read by distinguishing code from prose :smile:

**Comment by mboekhold** [comment]
I put up a draft PR, not sure what I'm doing wrong though

**Comment by Zac-HD** [comment]
It's a good start - `pip install black` and run `black .` to fix the formatting. Then add a test, changelog, and author entry as mentioned above.

**Comment by mboekhold** [comment]
What is the test case, look up the type and see if it succeeds `st.from_type(slice).example()` ?
