### ISSUE TITLE
Don't print blob after failing stateful test

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1941]
Take the following internal function in `hypothesis.stateful`:

https://github.com/HypothesisWorks/hypothesis/blob/8d73c4f96fa0ba5a0211685383c2de156d7fa8e6/hypothesis-python/src/hypothesis/stateful.py#L88-L90

If it fails, this may [print a blog for the `@reproduce_failure` decorator](https://hypothesis.readthedocs.io/en/latest/reproducing.html#reproduce-failure), even though this cannot be used on stateful tests.  We would therefore like to replace `@settings` with `@Settings(settings, print_blob=PrintSettings.NEVER)`.

You'll also need to write a `hypothesis-python/RELEASE.rst` file (for a patch release), and add your name to the list in `CONTRIBUTING.rst`.  Please feel free to ask for tips or open a WIP pull request once you have a basic prototype, and we can help you polish it up 😄

**Comment by Zalathar** [comment]
I was looking through `test_stateful.py` and noticed that as of e160dc6 we have tests to ensure that `@reproduce_failure` *does* work with stateful tests, thanks to #1609.

So now I'm confused. Does that invalidate this issue entirely?

**Comment by Zac-HD** [comment]
... I *wrote* that.  Why did I open this issue?  :disappointed: :man_facepalming:
