### ISSUE TITLE
README for PyCon 2019 Sprints

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1956]
Hi!  If you're reading this, there's a good chance that you're wondering how to get involved with the Hypothesis sprint at PyCon 2019.

We'll be running three sets of activity, for different levels of experience:

1. To get started, you can run through [my hands-on tutorial from earlier this week](https://github.com/Zac-HD/escape-from-automanual-testing) and get a hand if you're stuck anywhere.  Note that the last excercise in each file is designed to be a lot harder - feel free to skip it!

2. If you're already comfortable with Hypothesis, or finish the tutorial (target time: ~half a day), we think the biggest remaining problem is that there are projects that would like to use Hypothesis, but don't know where to start!  So here's a concrete guide:

   1. Find a project that would like to use Hypothesis - perhaps by asking around at lunch, or searching the issue tracker of projects you use.  Make sure that the project actually wants Hypothesis tests before continuing! 
   2. Write a test for round-trip logic, or one that just calls a function without any assertions in the test.  The easiest way though is to `git grep parametrize` and look for `@pytest.mark.parametrize` decorators that do *not* pass an expected output for each case - those are very easy to replace with `@hypothesis.given`!
   3. Check that their test requirements include Hypothesis, so it can run in CI, and then open your pull request!

3. We have some fun issues for confident through to expert Pythonistas - come talk to Zac and Ryan (usually in Room 15) for tips and some suggestions on where to start.

So welcome, thank you, and good luck!

**Comment by Zac-HD** [comment]
Congratulations to @mjsir911 for Hypothesis 4.21.1, the first release from the PyCon 2019 sprints... and all before lunch on day one!

**Comment by luizirber** [comment]
I've been porting some basic strategies for generating biological sequence data [from an old PR][0] into https://github.com/luizirber/hypothesis-bio/
I used hypothesis-{csv,networkx,jsonschema} as templates.

No PyPI release yet, but getting there! =]
[0]: https://github.com/dib-lab/khmer/pull/1324

**Comment by Zac-HD** [comment]
Congratulations to @mjsir911 for Hypothesis 4.22.0, the *second* release from the PyCon 2019 sprints... and his second written and released in a single day!  I believe that's an all-time record for a new contributor :rocket:

**Comment by Zac-HD** [comment]
Congratulations to @arendsee for Hypothesis 4.22.1, his first-ever Hypothesis release and the third from the PyCon 2019 sprints :shipit::tada:

**Comment by Zac-HD** [comment]
Congratulations to @danieljwest for Hypothesis 4.23.0, his first and the sixth from the PyCon 2019 sprints!

For those keeping track, that's three releases from new contributors at the mentored sprints (not counted above), four from new contributors, and two from maintainers.  And only day two of four :open_mouth:

**Comment by Zac-HD** [comment]
Congratulations to everyone who participated!  Over the last week, we've had five (!) feature releases, patched a bunch of minor bugs and docs issues, and introduced several people and projects to property-based testing.  I'm already looking forward to next time!
