### ISSUE TITLE
Crash on CPython 3.8-dev: AttributeError: 'code' object has no attribute 'co_posonlyargcount' 

### ISSUE THREAD

**Issue by jab** [HypothesisWorks/hypothesis#1959]
My project runs [daily hypothesis tests](https://travis-ci.org/jab/bidict/builds) with different versions of Python and the latest available hypothesis version. 6 days ago (in [build #1964](https://travis-ci.org/jab/bidict/builds/526507904)), the tests started failing for CPython 3.8-dev due to an uncaught error triggered by hypothesis/internal/compat.py (line 410, with hypothesis 4.18.3): `"AttributeError: 'code' object has no attribute 'co_posonlyargcount'`. Every 3.8-dev build since then has failed similarly, including today's which pulled hypothesis 4.21.1. Builds have been succeeding for all other Python versions I'm testing against, and no changes have landed in my code during this time. I noticed that [hypothesis's .travis.yml](https://github.com/HypothesisWorks/hypothesis/blob/master/.travis.yml) doesn't test against CPython 3.8-dev, and didn't immediately see an issue already opened for this, so figured I'd report it in case it's worth looking into. Thanks!

**Comment by Zac-HD** [comment]
Thanks for reporting this @jab!

In short, #1944 by @pganssle added PEP570 (positional-only argument) support for 3.8; which in turn breaks support for earlier 3.8 alphas that do not include this feature.  We decided that the simpler and more obvious code was worth breaking the alphas, and there should be another 3.8 out later today which will fix your builds.  Sorry for any trouble this has caused you - and please do believe that I appreciate the report!
