### ISSUE TITLE
Add example of using .filter to get unique objects

### ISSUE THREAD

**Issue by techdragon** [HypothesisWorks/hypothesis#1964]
This is basically the same as #419 however, rather than requesting the change be reverted, I'm just looking for some mechanism to ensure that unique django model objects can be generated.

If I want to test something that _relies_ on the fact that two users are different. Then the simple example from #419 of:
```python
user1 = data.draw(hypothesis_models(User))
user2 = data.draw(hypothesis_models(User))
``` 
Is a major problem. From the look of things so far, unless i _explicitly_ pass values using `just()` into `from_model()` in order to _manually_ ensure the uniqueness of the two objects, and thus forego most of the benefits of having hypothesis generating values for me, I cant write the test I need.

I've been trying to work around this with some kind of composite strategy construction, but so far haven't succeed. So either there is some "not entirely obvious trick" that needs better documentation, and/or there needs to be a better way to say "hey hypothesis, can i get another django object, one thats different from the last one please".

**Comment by Zac-HD** [comment]
You probably want `hypothesis.assume(user1 != user2)`?

**Comment by Zac-HD** [comment]
Or if you really are generating the users inside the test, `user2 = data.draw(hypothesis_models(User).filter(lambda u: u != user1))` would also work.

**Comment by techdragon** [comment]
@Zac-HD I've just re-read the documentation for filter, and it would probably be very helpful to add an example like this to the documentation so that this usage is more obvious to new users. It probably warrants a mention in the Django documentation as well.

**Comment by Zac-HD** [comment]
After roughing out a draft, I think showing this example in `.filter()` docs would on balance encourage bad habits, specifically needless use of `data()`.  `assume(...)` is a better and more general option - and just as efficient - or you could explicitly get unique users with `lists(from_model(User), unique=True)`.
