### ISSUE TITLE
Add hyperlinks to unlinked cross-references in docs

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1968]
I'm writing this one up for @djarecka, so per our usual policy it's hers for a week - after that we'll accept other pull requests or requests to reserve it again.

We would like our docs to be easy to explore, and that means hyperlinks.  However, not all references to other strategies (or other functions, or standard library types) are cross-references.  Compare for example [`datetimes()`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.datetimes) (lots of links) with [`dictionaries()`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.dictionaries) (unlinked *lists*).

These links should use [Sphinx "roles"](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html), typically `:func:` (or `:class:`, or `:obj:` for any other object).  For example:

```
:func:`hypothesis.note`  # renders "hypothesis.note()"
:func:`~hypothesis.strategies.builds`  # renders "builds()"
:obj:`@given <hypothesis.given>`  # renders "@given"
:class:`python:slice`  # renders "slice" with link upstream (grep "intersphinx" for details)
```

**Comment by djarecka** [comment]
Hi @Zac-HD , sorry but really didn't have time last week after I came back to Boston. Will try to do it, but of course if anyone wants to work on it, it's fine :)

**Comment by Zac-HD** [comment]
No worries, if you want to claim it for another week that's fine by me! 

(it's just to avoid that awkward period where *maybe* the person has vanished, but maybe not - so long as you check in regularly you can take however long you need)

**Comment by Zac-HD** [comment]
Reserving this one for @SamBackwell, for the usual one week period 😄

**Comment by KathyReid** [comment]
@SamBackwell let me know if you want to work through this one when we catch up :-) 
Useful [cheat sheet here](https://thomas-cokelaer.info/tutorials/sphinx/rest_syntax.html).

**Comment by serahrono** [comment]
Happy to work on this one.
