### ISSUE TITLE
Add Numpy strategy for `multiple_shapes` which are mutually broadcastable

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#1969]
The `broadcastable_shapes(shape)` strategy is great, but sometimes you need *several* shapes, all of which are broadcastable against any of the others - for example to describe the [loop dimensions of generalised ufuncs](https://docs.scipy.org/doc/numpy/reference/c-api.generalized-ufuncs.html).  This may not be needed often, but be critical when it is!

I therefore propose to add the following strategy:

```python
Shape = Tuple[int, ...]

def multiple_shapes(
    inputs,
    base_shape=(),
    min_dims=0,
    max_dims=None,
    min_side=1,
    max_side=None,
):
    # type: (int, Shape, int, int, int, int) -> Tuple[Tuple[Shape, ...], Shape]
    ...
    # Returns a namedtuple of (input_shapes, result_shape)
```

This strategy will be defined in the first release as generating an `len(inputs)`-tuple of mutually-broadcastable array shapes, and the expected result shape as the second element of a named tuple.

In future releases, `inputs` may be a gufunc signature string describing core dimensions, with the other arguments interpreted as describing the loop dimensions (if any).  This plan replaces #1784.

**Comment by brianwa84** [comment]
FYI we have something like this in TFP:
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/internal/hypothesis_testlib.py#L489

**Comment by Zac-HD** [comment]
Oh, cool!  I didn't know that Google was using Hypothesis... though I'd strongly recommend upgrading to a newer version, beyond the usual bugfixes and new features we have a couple of perfomance improvements along the lines of "things that were quadratic are now n-log-n or linear" which are *very nice*.  

(reconfiguring some of those strategies for data locality would probably help shrink time a lot too if that's been a problem for you, but updating Hypothesis would be an easier win.  feel free to contact me to discuss)

We're probably going to take a slightly different approach here to support future generation based on ufunc signatures, where the shape-to-broadcast-to is bounded but not fixed.  Plus some use and abuse of internal APIs to get as close to ideal shrinking as we can, I hope!

**Comment by brianwa84** [comment]
I've been working on the upgrade. :) I admit I'm curious how you knew our
version was out of date. Is there a timeout= arg in there somewhere? :)

Brian Patton | Software Engineer | bjp@google.com

**Comment by Zac-HD** [comment]
Ooh, exciting to hear that there'll be an update 😄 

I didn't *know* so much as have a very likely guess: I know roughly how the Google monorepo works, and that someone was experimenting with Hypothesis a year or so ago, so I was comfortable betting that "update please" is good advice 😉... and the file you linked has some comments up near the settings config which I didn't think were out of date.
