### ISSUE TITLE
lists() generates fewer very long long lists than expected

### ISSUE THREAD

**Issue by florian-venn** [HypothesisWorks/hypothesis#1984]
A test like
```python
@given(binary(max_size = 10000))
def test(b):
	assert len(b) < 100
```
will almost allways pass. I would suggest at least adding a warning when setting max_size to a value that is not well covered.

**Comment by Zalathar** [comment]
Variable-size `binary` delegates to `lists` under the hood, so presumably lists would have the same difficulty.

#1961 is probably relevant.

**Comment by Zac-HD** [comment]
> #1961 is probably relevant.

Almost certainly not, actually!  That one only triggers when there are few values for each element (or no elements), while there are 256-per-element for `binary()`.  

This is simply that the average size of examples is smaller than @florian-venn expects; and in turn that's tuned to balance typical running times against bug-finding (with published studies finding that most bugs are findable with surprisingly small inputs).

**Comment by DRMacIver** [comment]
>  (with published studies finding that most bugs are findable with surprisingly small inputs).

This is true but somewhat misleading unfortunately. It's true that there is typically *some* small input that finds a bug (that's why test-case reduction works) but often the probability of triggering the bug rises dramatically as the size of the input increases.

**Comment by Zac-HD** [comment]
https://github.com/HypothesisWorks/hypothesis/blob/6ac1eefd78831074c9042e87b937fefab5fe8e76/hypothesis-python/src/hypothesis/searchstrategy/collections.py#L75-L78

Changing `min_size + 5` to `min_size + 10` would probably be enough to fix this issue, though you should check by running the code above!

If you are a first-time contributor, don't forget to add your name to the list in `CONTRIBUTING.rst`, and create `hypothesis-python/RELEASE.rst` with the following contents:

```
RELEASE_TYPE: patch

This patch makes Hypothesis more likely to generate longer lists and
larger collections, within whatever length bounds you might specify.

Thanks to Your Name Here for the fix!
```

**Comment by Zac-HD** [comment]
Unfortunately the patch I suggested above is not enough to fix this issue unless we make the average size of lists large enough to cuase a substantial performance hit :sob:.  Thanks very much to @joy-rosie who worked on and benchmarked the patch at EuroScipy.

I think the solution we will actually end up going with - though no word on timing since it's both a major change and unfunded - is via swarm testing (#1637) based on #1986.
