### ISSUE TITLE
Data generation is extremely slow in CI environment

### ISSUE THREAD

**Issue by lexotero** [HypothesisWorks/hypothesis#2009]
## Description 

When running some of our unit tests, sometimes we get the following error:

```
Data generation is extremely slow: Only produced 8 valid examples in 1.23 seconds [...]
```

The test that causes the error:

```python
    @given(
        lists(
            elements=lists(
                elements=text(alphabet=string.uppercase + string.lowercase + string.digits, min_size=2),
                min_size=2
            ),
            min_size=2
        ),
    )
    def test_something_with_random_data_check_works(self, random_data):
        [...]
```

Could you please help me finding out why is this running so slowly? What could have changed in the machine that would make `hypothesis` run slower?

## Versions

- Centos 7
- Python 2.7.5
- Hypothesis 3.66.1
- Pytest 4.1.0

## What have we checked?

- Setting `max_size` for the `lists` and `text` elements doesn't fix the problem.
    - Using `max_size=100` for the `text` elements.
    - Using `max_size=30` for the `lists` elements.
- The environment hasn't changed recently.
- The server produces enough entropy.
    - The machine is capable of producing 1GiB of random data in `~5s`, using Python `random` module.
    - We have `haveged` installed and we get sensible numbers with `cat /proc/sys/kernel/random/entropy_avail` (`~1200`)
- Running the test with `strace` shows that the amount of time spent in system calls is negligible.

**Comment by Zac-HD** [comment]
Hmm, this is pretty strange.  Has anything changed lately?

While it looks like your whole stack is fairly old, I'd especially encourage you to update Hypothesis - we only support the latest version, and it really is much improved.  This should be quite painless, and indeed trivial if you do not currently have any `HypothesisDeprecationWarning`s.

**Comment by lexotero** [comment]
> Hmm, this is pretty strange. Has anything changed lately?

Not that we could find. The tests we are running didn't change. The code tested is the same. Requirements and CI system the same...

> While it looks like your whole stack is fairly old, I'd especially encourage you to update Hypothesis - we only support the latest version, and it really is much improved. This should be quite painless, and indeed trivial if you do not currently have any `HypothesisDeprecationWarning`s.

Unfortunately we cannot update the stack at the moment. We **can update** `Hypothesis` to the latest version that supports Python 2.7, which I think is the latest 4.24.3.

I will update `Hypothesis` and let you know if the test stops failing. Thanks for your help.

**Comment by lexotero** [comment]
> I will update `Hypothesis` and let you know if the test stops failing. Thanks for your help.

No luck I am afraid. Running the same test with `hypothesis==4.24.3` produces the same rate of errors.

We've been playing with `max_size` and we get the test passing "reliably" with:

```python
    @given(
        lists(
            elements=lists(
                elements=text(alphabet=string.uppercase + string.lowercase + string.digits, max_size=100, min_size=2),
                max_size=10,
                min_size=2
            ),
            max_size=10,
            min_size=2
        ),
    )
```
If we increase the size of the lists to `16`, we start getting frequent failures. 

```python
    @given(
        lists(
            elements=lists(
                elements=text(alphabet=string.uppercase + string.lowercase + string.digits, max_size=100, min_size=2),
                max_size=16,
                min_size=2
            ),
            max_size=16,
            min_size=2
        ),
    )

```

**Comment by Zac-HD** [comment]
> Running the same test with `hypothesis==4.24.3` produces the same rate of errors.

OK, good that we can eliminate that at least!  If you can stick to fairly recent versions I would suggest doing so - we often have performance improvements along with new features.

FYI Hypothesis will continue supporting Python 2 until 2020-01-01 (or a few days later), after which new releases support Python 3 and we will backport on a paid basis only.  Of course the previous version will remain available from PyPI and continue to work!  

More generally I would encourage you to plan your upgrade for this year, as the whole Python community is preparing to drop Python 2 by 2020 - I've helped with a few upgrades, and the combination of `future`, `six`, `modernize`, and `pyupgrade` actually makes it pretty painless :smile: 

---------------------

Having now played around with this strategy a bit, I think the main problem is simply that when the outermost list is long, the data can get very large!  Checking with `--hypothesis-show-statistics`, I get `Typical runtimes: 0-156 ms`, and the extremes could be even longer.  This is because a list of lists of strings is essentially three-dimensional, so each additional step can have a very large if fairly uncommon effect.

Concrete advice then: reduce the length of the outer list, or use the relevant entry to your `suppress_health_check` setting - cases like this where large inputs are useful are exactly why we have it!

Since our strategy caching seems to be working correctly, there's not much we can do upstream.

**Comment by lexotero** [comment]
> > Running the same test with `hypothesis==4.24.3` produces the same rate of errors.
> 
> OK, good that we can eliminate that at least! If you can stick to fairly recent versions I would suggest doing so - we often have performance improvements along with new features.
> 
> FYI Hypothesis will continue supporting Python 2 until 2020-01-01 (or a few days later), after which new releases support Python 3 and we will backport on a paid basis only. Of course the previous version will remain available from PyPI and continue to work!
> 
> More generally I would encourage you to plan your upgrade for this year, as the whole Python community is preparing to drop Python 2 by 2020 - I've helped with a few upgrades, and the combination of `future`, `six`, `modernize`, and `pyupgrade` actually makes it pretty painless smile

We already have plans to upgrade our stack for this project. We've done so with other projects but we didn't use `modernize`, I will take a look. Anyway it wasn't really painful.

> Having now played around with this strategy a bit, I think the main problem is simply that when the outermost list is long, the data can get very large! Checking with `--hypothesis-show-statistics`, I get `Typical runtimes: 0-156 ms`, and the extremes could be even longer. This is because a list of lists of strings is essentially three-dimensional, so each additional step can have a very large if fairly uncommon effect.
> 
> Concrete advice then: reduce the length of the outer list, or use the relevant entry to your `suppress_health_check` setting - cases like this where large inputs are useful are exactly why we have it!
> 
> Since our strategy caching seems to be working correctly, there's not much we can do upstream.

Many thanks for taking the time to review this. We got to the same conclusion, but we were puzzled by the fact that this test was running successfully for more than a year. We have already suppressed the health check so now it just carries on without any problem.

Thanks again!
