### ISSUE TITLE
Labeled assertions and/or Contextual Notes

### ISSUE THREAD

**Issue by techdragon** [HypothesisWorks/hypothesis#2010]
I was refactoring some tests using Django models for better performance and came across a bit of a quality of life issue as the tests got longer to minimise the time I spent generating data. I was adding more assertions into a single "test" and I wanted a way to leave a note about what each of the assertions was meant to test. But I didn't want a dozen notes to wind up in the output if one assertion failed, I only cared about the note for the assertion failed. 

So I cooked up a quick and dirty "contextual note" context manager, and figured I should post it as an issue so either note could be enhanced or someone can warn me before I do something stupid by using broken code 😄 

```python
from hypothesis import Verbosity, settings
from hypothesis.reporting import report
from hypothesis.control import _current_build_context
from hypothesis.errors import InvalidArgument
from contextlib import contextmanager

@contextmanager
def context_note(value):
    # type: (AnyStr) -> None
    try:
        yield
    except:
        """Report this value in the final execution."""
        context = _current_build_context.value
        if context is None:
            raise InvalidArgument("Cannot make notes outside of a test")
        context.notes.append(value)
        if context.is_final or settings.default.verbosity >= Verbosity.verbose:
            report(value)
        raise
```

Is there anything obviously wrong I've missed, and/or is this something we could add to `note` itself so as to not introduce a potentially unnecessary variant of the note function?

Usage in a test is like this
```python
    ...
    with context_note("This should pass and not appear"):
        assert True
    with context_note("This will fail and we should only see this note in the output"):
        assert False
```

**Comment by Zac-HD** [comment]
As a more readable alternative, why not:

```python
	assert not True, "This should pass and not appear"
    # Or, if you specifically need note() and not exception text:
    if not False:
        note("This will fail and we should only see this note in the output")
        raise AssertionError
```

It's clear what this does without having to look up documentation, and on our end we don't have to write any or maintain the code 😄

If you want to keep using your `context_note` function though, it will work right up until we change the internal implementation details it depends on (

**Comment by techdragon** [comment]
@Zac-HD While that is more readable, it doesn't quite cover my situation/usage, my example was probably too simple to really show what I wrote this for. So I think there's been a bit of miscommunication here, can you reopen this? 

While converting over some Django tests from `unittest` (which has the setup function) to Hypothesis which doesn't have a direct equivalent to the "one data setup, multiple tests" pattern. For performance reasons I'm folding up classes full of "setup + small operation/call and assert + another small operation/call and another assert ... etc"  and I wound up with one example where a single hypothesis Test class contained 35 assertions gathered from what was 25 different tests under `unittest`. If I A: wanted to use the note feature and B: failed one of the later assertions I could end up with _dozens_ of irrelevant notes in the test output that are only informative with respect to assertions that didn't raise the error that caused the test to fail.

My goal was to be able to compartmentalise the note to a "pseudo-subtest", so I could leave useful notes in the test output for future test failures during refactoring, etc, because without the compartmentalisation, the notes feature became too noisy as the size of the test grew for performance reasons.

**Comment by Zac-HD** [comment]
I would expect the following to be equivalent though:

```
with context_note(...):
    assert <condition>
# can be converted to 
if not <condition>:
    note(...)
    assert False
```

You'll only ever see one note, that associated with the failing condition.

**Comment by techdragon** [comment]
@Zac-HD 
```python
if not <condition>:
    note(...)
    assert False
```
As I understand things, that would only be reliable when the condition itself can be considered reliable, like looking up a property/attribute/value on something and performing a simple comparison. When the <condition> is something like
```python
self.assertEqual(
    len(auth_backend.get_all_tenant_permissions(self.user)),
    Permission.objects.all().count()
)```
I want to catch any "inner failures" produced while performing the comparison, and effectively set the scope of the note to the "complex condition" itself.

**Comment by Zac-HD** [comment]
Right, for something like that I think a downstream helper is probably the best answer.

Shipping functionality for this case feels a bit off-topic to me, and unlikely to promote good practices.  (your use-case may be the best option available, but I wouldn't describe it as elegant)

**Comment by techdragon** [comment]
@Zac-HD I do agree it doesn't feel elegant. Id much rather have smaller individual tests :smile: But the realities of constructing performant tests using Django models and Hypothesis force compromises sometimes. Even with heavily 'merged' tests I'm spending a significant percentage of time in data generation (~40%). So i'll just keep this in my personal toolbox.
