### ISSUE TITLE
mypy-0.710 in strict mode does not think that hypothesis reexports its object

### ISSUE THREAD

**Issue by daa** [HypothesisWorks/hypothesis#2017]
``mypy-0.710`` introduced new behaviour for treating reexported modules and objects - they are not counted as reexported if they are not imported in special form ``import smth as smth``. This behaviour is switched on with new flag ``--no-implicit-reexport`` which is switched on in strict mode. Such change causes following errors when trying to typecheck code using ``hypothesis``:
```
error: Module 'hypothesis' has no attribute 'given'
error: Module 'hypothesis.strategies' has no attribute 'floats'
```
And so on.

**Comment by Zac-HD** [comment]
Given that those names *do* appear in the `__all__` for their respective modules, I consider this a Mypy bug in the [handling of their `implict_reexport`](https://mypy.readthedocs.io/en/latest/config_file.html#miscellaneous-strictness-flags) option.  As a workaround, can you set `implicit_reexport = False` for Hypothesis?

**Comment by daa** [comment]
I've done that already. Just wanted to inform you. I agree that ``mypy`` behaviour is not obvious and that proposes solution to import something as something makes code looking unnatural,  And by the way thank you for the library!

**Comment by Zac-HD** [comment]
Thanks! With a decent workaround in placr and an issue opened upstream, I think we can close this one. And I'm glad you like it!
