### ISSUE TITLE
Extend special casing of sampled_from in unique collections

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#2036]
As of #2030 we have a special case for `lists(sampled_from(...), unique=True)` that uses a custom strategy. Unfortunately this special casing is trivial to defeat. e.g.  `lists(sampled_from(...).map(lambda x: x), unique=True)` should behave the same way but doesn't. It would be good to extend this support to include arbitrary chains of maps and filters over `sampled_from`. 

There are a couple of possible ways to do this, but I think the easiest would be to extend the base `SampledFrom` strategy to have a `transform` function which takes an element of the sample and either transforms it or raises an `UnsatisfiedAssumption` (or returns a special value). The special case unique list strategy could then call this transformed function directly.

**Comment by dfarrel1** [comment]
Going to take a stab at this one!

**Comment by Zac-HD** [comment]
Untested prototype: https://github.com/HypothesisWorks/hypothesis/compare/master...Zac-HD:transformed-samples

**Comment by Zac-HD** [comment]
We probably also want to add a special case for the `st.dictionaries()` strategy, which currently doesn't get any advantages at all if `keys=st.sampled_from(...)`.
