### ISSUE TITLE
compact log output when using sampled_from()

### ISSUE THREAD

**Issue by techdragon** [HypothesisWorks/hypothesis#2039]
I've been working on a better domain_name strategy and ran face first into a limitation in the code that prints the output of hypothesis tests when using the pytest plugin for statistics in test results. (I haven't found the code responsible for printing the output yet so I'm not sure if its in hypothesis, the pytest plugin, or possibly pytest itself) 

It seems that once the length of a list or tuple used in a `sampled_from()` strategy passes some length, I haven't had time to determine the threshold yet, the output will switch from one item after the other like this:

```python
sampled_from(['a', 'b', 'c', 'd', 'e', 'f'])` 
```

over to a more verbose style like this

```python
sampled_from(['a', 
'b', 
'c', 
'd', 
'e', 
'f', 
'g', 
'h', 
'i', 
'j', 
'k', 
'l', 
'm', 
'n'])
```

**Comment by Zac-HD** [comment]
The relevant pretty-printing code is in `hypothesis.vendor`, if that's what you're asking? I'm not sure why this would be a problem though.

**Comment by techdragon** [comment]
@Zac-HD Specifically the issue in my case was not really from any day to day usage, but from my work on a "better" `domains()` strategy. The code already has a todo entry for improving the strategy. https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/provisional.py#L62

My not yet complete, first attempt, is passing a list of over 250 items into the `sampled_from()` call, which gets transformed into huge 'gaps' in the test results output to my terminal. It's not specifically a 'problem' as everything works, nothing is lost, etc. But every time I have to carefully scroll past a wall of text like this in my terminal...
```
 '.cm',
 '.cn',
 '.co',
 '.cr',
 '.cu',
 '.cv',
 '.cw',
 '.cx',
 '.cy',
 '.cz',
 '.de',
 '.dj',
 '.dk',
 '.dm',
 '.do',
 '.dz',
 '.ec',
 '.ee',
 '.eg',
 '.es',
 '.et',
 '.eu',
 '.fi',
 '.fj',
 '.fk',
 '.fm',
 '.fo',
 '.fr',
 '.ga',
 '.gd',
 '.ge',
 '.gf',
 '.gg',
 '.gh',
 '.gi',
```
_...abbreviated for sanity..._

It just feels more and more annoying... so I just wanted to roll up my sleeves and 'fix' it.

**Comment by techdragon** [comment]
Already making progress! I've got a minimal example/test case that highlights the behaviour I'm talking about. 
```python
>>> from hypothesis.vendor.pretty import pprint
>>> pprint([str(_x) for _x in range(14)])
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13']
>>> pprint([str(_x) for _x in range(15)])
['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14']
```

**Comment by techdragon** [comment]
After digging in a bit more, it seems like things are functioning as designed. So I'm wondering if this is a case of poor defaults, if this really is actually the desired behaviour, or if this isn't the desired behaviour just what the desired behaviour was. The code does appear to have been written to do exactly what it is currently doing, none of the comments really talk about the format of the outputs, they stick pretty solidly to the logic of the various classes and function.

The current code will switch once the string length from of the list/tuple (with extra spaces added by hypothesis' printing code) is longer than 79 characters (the default `max_width`). After this it switches to one item per line and this will continue until the list/tuple is more than 1000 items long ( as defined by `MAX__SEQ_LENGTH`, which is a hard coded value) at which point it will be abbreviated with a `...`. I'm sure this is desirable under some circumstances, from the look of it, it was designed to gracefully handle breaking up nested dictionaries onto multiple lines, but it feels very disruptive (at least to me) when used for flat lists/tuples like I'm working with ...

So I'd love some feedback on the idea of changing this. I don't want to just suggest a drastic change to code that appears to have had no major changes since it was first written by @DRMacIver 3 years ago without a better understanding of the bigger picture. 

Any thoughts @Zac-HD, or anyone else ?

**Comment by Zac-HD** [comment]
We didn't actually write this, just "vendored" (copy-pasted) from IPython!  

So if you have a proposed change, I'd basically take willingness to write the PR (with our help of course) as evidence that it's worth doing. The only functional constraint I can think of is that we really value the repr-eval-repr round trip, so reformatting would be fine but truncating less so. David may have other ideas though!

**Comment by techdragon** [comment]
@Zac-HD Glad to hear its open for changes. I think the only issues with the existing truncation behaviour is that it isn't configurable, and maybe that its a hard _truncate as stop_ not a slightly friendlier _truncate entries from the middle to fit desired length_. My "goal" would be to try and add an improvement so that we get smarter behaviour based on if the sequence is flat or nested. Flat sequences (no nested lists/tuples) can probably just be allowed to remain 'inline' and just let the normal terminal/console/shell line wrapping handle things. 

If I've understood the logic correctly, the least disruptive option might be to make the `SampledFromStrategy` class a little more in control of how its output is being printed, by adding a `__repr__` method that can toggle  between a new 'don't break flat lists' behaviour and the existing behaviour, which would need a proxy class/type for the flat list/tuples to associate them with a new flat sequence equivalent of `_seq_pprinter_factory` to prevent the breaks being inserted.

So unless theres a visible red flag in that approach, I'll try to put together a PR.

**Comment by DRMacIver** [comment]
> We didn't actually write this, just "vendored" (copy-pasted) from IPython!

Worth noting that it's diverged a bit since then. We have a bunch of patches which like a monster I failed to upstream (mostly formatting and test suite compatibility with pypy. Maybe some hooks that get used in stateful testing? I can't remember for sure), and they've done a bunch of work since that we've not backported. So I think at this point it should be considered its own thing and maybe even moved out of the vendor directory.

> If I've understood the logic correctly, the least disruptive option...

One other thing to consider might also be to change our behaviour for pretty-printing of lists to something that is of in-between levels of compactness. Rather than putting everything all on one line or all on separate lines we could have it so that it inserts breaks when the line is getting a bit too long.

I don't really have a sense of how much work that's likely to be, and I'm not wed to it as a solution, so please take this more as backseat patching than a strong opinion!

**Comment by techdragon** [comment]
@Zac-HD / @DRMacIver I've got my first pass a a solution, it's missing some important things like tests, python 2 support, etc. But before I got on with writing that stuff, I wanted to validate a detail of the approach I took. 

I originally suggested modifying `SampledFromStrategy.__repr__()` but that wont work with how things currently work. The typical use case will produce an instance of `LazyStrategy` that wraps the strategy actually being used, and as currently written `LazyStrategy.__repr__()` builds the output based on the strategy's wrapper function name, and introspection of the arguments passed to the function wrapper.

As a consequence, I switched switched from modifying `SampledFromStrategy.__repr__()` to `SampledFromStrategy.__init__()`. The approach is basically the same, except it is happening at class construction rather than `__repr__()` call time. I'm using a proxy object `FlatTuple`/`FlatList` which have been associated with a different printer factory function inside `pretty.py` than the one used by plain `tuple`/`list` objects. When the conditions are correct (we pass in a flat sequence type) we make a new proxy object from the original, and set the value of `self.elements` in our `SampledFromStrategy` instance, to the new proxy object instead of unmodified original value and we get our customised behaviour.

I could work on making `LazyStrategy.__repr__()` smarter if we want to keep this logic to a 100% cosmetic level, but that felt like it would have much wider potential impacts compared to confining my changes to `SampledFromStrategy.__init__()`.

Thoughts/Feedback?

**Comment by techdragon** [comment]
@DRMacIver @Zac-HD - Since actual code is more useful than long explanations. My current, no tests and Python 3 only, minimum working implementation is here in diff form for easy reading 😃 https://github.com/HypothesisWorks/hypothesis/compare/master...techdragon:WIP-improving-the-pprint-output-of-sampled_from 

Let me know what you think and if this looks like a suitable solution, I'll get the other stuff sorted and turn this into an acceptable PR 😄

**Comment by Zac-HD** [comment]
Closing this as it's not applicable to the proposed domains() strategy, and wrapping a strategy in composite or similar is generally a clean way to shortening the repr.
