### ISSUE TITLE
hypothesis.strategies.lists fails for elements=None and max_size=0

### ISSUE THREAD

**Issue by lockshaw** [HypothesisWorks/hypothesis#2046]
According to the documentation [here](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.lists),

> If max_size is 0 then elements may be None and only the empty list will be drawn

However, when `elements=None` and `max_size=0`, an uncaught excaption is raised:
```python
>>> import hypothesis
>>> hypothesis.strategies.lists(elements=None, max_size=0).example()
Traceback (most recent call last):
...
hypothesis.errors.InvalidArgument: Expected SearchStrategy but got elements=None (type=NoneType)
```

**Comment by Zac-HD** [comment]
Ah, a docs bug! Tbat should read 

> If max_size is 0, only the empty list will be drawn.

You can instead use the `nothing()` strategy, which will always lead to empty lists, or with max_size=0 literally any strategy will work.

**Comment by elizabethwilliams8** [comment]
Got this!
