### ISSUE TITLE
Add support for generating NetworkX graphs

### ISSUE THREAD

**Issue by thedrow** [HypothesisWorks/hypothesis#2056]
[NetworkX](https://github.com/networkx/networkx) is a graph library for Python.
When we implement graph algorithms it can be useful to have multiple graphs to test with.

We provide support for NumPy and other libraries.
Can we add NetworkX to the list?

**Comment by Zac-HD** [comment]
There is a third-party extension for this - https://pypi.org/project/hypothesis-networkx/ - and it's listed on the community page in our docs. 

We would be open to merging it in to the main repo if @pckroon agreed, but it's not something that we push for when the external version works just fine 😁

**Comment by thedrow** [comment]
I didn't know about it.
Thanks!

**Comment by pckroon** [comment]
> We would be open to merging it in to the main repo if @pckroon agreed, but it's not something that we push for when the external version works just fine 😁

Once you have the idea this becomes relevant (because too many people need it, or too few can find it) this is fine with me. For now I don't really see a need or reason though.
