### ISSUE TITLE
ImportError: cannot import name 'list' from 'hypothesis.strategies'

### ISSUE THREAD

**Issue by TejasAvinashShetty** [HypothesisWorks/hypothesis#2057]
I get this error "ImportError: cannot import name 'list' from 'hypothesis.strategies'" on running "from hypothesis.stategies import list" hypothesis. [anaconda env file](https://www.dropbox.com/s/176vv31rd3xr6ev/tejashpjuly19.yml?dl=0). What version of hypothesis should I install which does not have this problem from [here](https://anaconda.org/search?q=hypothesis). 
[my installation ](https://anaconda.org/anaconda/hypothesis) 
[possible answer to reinstall again from here](https://anaconda.org/conda-forge/hypothesis)
On running conda list I get
hypothesis                4.23.6                   py37_0    anaconda

**Comment by rsokl** [comment]
The name of the strategy is plural: lists

**Comment by TejasAvinashShetty** [comment]
Yeah It works Thanks @rsokl :rofl:

**Comment by TejasAvinashShetty** [comment]
Closing issue
