### ISSUE TITLE
Logging random seed

### ISSUE THREAD

**Issue by lycantropos** [HypothesisWorks/hypothesis#2070]
Is there any way of getting random seed used during each examples generating cycle and logging it (like it happens in case of error)? My problem is following: locally I'm getting no errors, but on CI it exits after timeout (some sort of infinite loop)  and there is no way for me to reproduce this, so if there is a solution for making seeds visible right before examples generating -- it will help for sure.

**Comment by Zac-HD** [comment]
Hypothesis actually seeds the global random state, so that shouldn't do anything unless you're using the `random_module` strategy. Maybe try the `derandomize=True` setting?

**Comment by lycantropos** [comment]
@Zac-HD: what this setting does? from [docs](https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.derandomize) I couldn't understand the mechanism, it uses the same seed for the whole tests session or what?

**Comment by Zac-HD** [comment]
For each test, it uses a seed determined by hashing that test.
