### ISSUE TITLE
Use `blacken-docs`

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2072]
We use Black for our code, so why not use it for the code examples in our docs?

This should look a lot like [our pyupgrade call](https://github.com/HypothesisWorks/hypothesis/blob/8269d65f702ea564f04939ba1a5ce4eca3507554/tooling/src/hypothesistooling/__main__.py#L235), but including all `*.rst` files in the repo too.

**Comment by GrigoriosGiann** [comment]
Hello, I'll start looking into this 😄
