### ISSUE TITLE
Role of example in a test which using pytest.fixture

### ISSUE THREAD

**Issue by ke-zhang-rd** [HypothesisWorks/hypothesis#2075]
I have a question about role of example(example in the context of hypothesis) which came to my mind after read 'However, each fixture will run once for the whole function, not once per example.' in [here](https://hypothesis.readthedocs.io/en/latest/supported.html#testing-frameworks)

Maybe I'm wrong, Initially, I think 

1) example is a independent test, many example of course means **many** tests

2) A typical fixture role is setup config/env argument as fixed work at the beginning of **each** test.

This will lead to in a max_example != 1, each example instead of whole function may need run fixture once. Also this make finializer of fixture make sense. 
I also realize there is way go around by returning a tuple of callable things in fixture but I try to avoid that.

I was wondering what do you think?

**Comment by Zac-HD** [comment]
See #377 - we'd like to make function-scoped fixtures work the obvious way but there's no good way to do so.
