### ISSUE TITLE
Improve argument validation for `st.lists()`

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2083]
In [`validation.py`](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/internal/validation.py), we have a `check_valid_size` function, which should pass its `name` argument through to `check_type` to be included in the error message.

In the `check_type` function, we should unpack length-one tuples of types before checking if it's a tuple for message purposes; otherwise this leads to messages like "one of int" (because `integer_types` == `(int,)` on Python 3 but `(int, long)` on Py2).

Fix those, add yourself to the list of authors in `CONTRIBUTING.rst`, and create `hypothesis-python/RELEASE.rst` with the following contents:

```
RELEASE_TYPE: patch

This patch improves the error messages from invalid size arguments to
collection strategies such as :func:`~hypothesis.strategies.lists`.

Thanks to Your Name Here for the fix!
```

**Comment by tgrainge** [comment]
Hey Zac, taking a look at this now.
