### ISSUE TITLE
from_regex generates unexpected new lines 

### ISSUE THREAD

**Issue by bschoeni** [HypothesisWorks/hypothesis#2089]
executing following:

>>> import hypothesis
>>> g=hypothesis.strategies.from_regex(r'^[A-Z][a-z]$')
>>> g.example()

yields many results with an unwanted trailing newline

'Op'
'Xz\n'
'At\n'
'Jx\n'
'Aa'
'Qs'
'Kl\n'
'Vz'
'Xh'
'Aa'
'Cf\n'

**Comment by Zac-HD** [comment]
This is the expected behaviour, as those strings are matched by the regex used to generate them.

To match end-of-string without accepting new lines, you can use [`\A` instead of `$`](https://docs.python.org/3/library/re.html#regular-expression-syntax).

**Comment by theoden-dd** [comment]
It should only match if [MULTILINE](https://docs.python.org/3/library/re.html#re.MULTILINE) flag is on. However, thanks for the [\Z](https://docs.python.org/3/library/re.html#index-34) instead of $.

**Comment by Zac-HD** [comment]
> It should only match if [MULTILINE](https://docs.python.org/3/library/re.html#re.MULTILINE) flag is on.

You are incorrect: `$` matches before an optional trailing newline regardless of mode.

```python
>>> re.search("^abc$", "abc\n")
<re.Match object; span=(0, 3), match='abc'>
>>> re.search("^abc$", "xyz\nabc\n", flags=re.MULTILINE)
<re.Match object; span=(4, 7), match='abc'>
```

`re.MULTILINE` simply treats each line as a separate string for matching purposes.
