### ISSUE TITLE
How to find hypothesis-profile？

### ISSUE THREAD

**Issue by LuanShiZhiJian** [HypothesisWorks/hypothesis#2090]
I met a problem while reading the doc(https://hypothesis.readthedocs.io/en/latest/settings.html ) and try to run pytest command parameters(“pytest tests --hypothesis-profile profile-name”). Now the question is how to find hypothesis-profile or create it？ 

Is there an example for reference? Would you please advise?

**Comment by Zac-HD** [comment]
You'll need to [register a profile with that name](https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.register_profile), with `settings.register_profile()`, before you can load it from the commandline.  Hope that helps!
