### ISSUE TITLE
load_profile switching

### ISSUE THREAD

**Issue by machielg** [HypothesisWorks/hypothesis#2098]
I have two test case classes, one uses a custom profile and the other needs to use the default profiles. I load the profile in the setupClass method of my CustomSettingsTest and I'm loading profile 'default' in the DefaultSettingsTest

If I run either of the test classes alone they work, but when I first run the DefaultSettingsTest then in the CustomSettingsTest the settings are still the default ones.

When debugging the code it seems the _current_profile has been changed, but the default_variable.value is still set at the default values.

By the way, it only goes wrong when using the @given() annotation, perhaps that gives some hint to the source of the issue.

I can provide the code that fails

**Comment by Zac-HD** [comment]
Can you link or paste the code, so I can see exactly what's happening?

**Comment by machielg** [comment]
https://gist.github.com/machielg/5b78e9ac6640cd674aec6df23ae846a5

**Comment by Zac-HD** [comment]
Ah, I see what's happening.

The settings profile mechanisms change *global* state, not per-class state, and your setup methods are all being run before any of the test methods are run.  No matter how many classes you ran like this, every test would have the same (random?) profile active.

Instead, you can use the settings object as a decorator on your test method, for example:

```python
    @settings.get_profile('foo')
    @given(just('bar'))
    def test_bar(self, bar):
        self.assertIsNone(settings().deadline)
```

which is exactly why we provide the `get_profile` method 😄

**Comment by machielg** [comment]
What’s the difference between switching profiles once per class and for each method? With this decorator approach I have to set the profile dozens of times for each test method. I was hoping to put the profile selection in a base class that I can simply inherit from.

**Comment by Zac-HD** [comment]
`load_profile` has global effect, and so whichever runs last applies to all test methods because all classes are set up before any are run.

Using a settings object as a decorator ensures that those settings are used for the corresponding method.

**Comment by machielg** [comment]
I fixed it by putting the load_profile in both the setupClass and body of the class. It would be nice if there was some more friendly way of doing this, perhaps annotating a class with a profile name which hypothesis could apply?

My work around:
```
class FooTestCase(unittest.TestCase):
    settings.load_profile('foo')

    @classmethod
    def setUpClass(cls) -> None:
        super().setUpClass()
        settings.load_profile('foo')
```

```
class DefaultTestCase(unittest.TestCase):
    load_default_profile()

    @classmethod
    def setUpClass(cls) -> None:
        super().setUpClass()
        load_default_profile()
```
