### ISSUE TITLE
Feature Request: make the HealthCheck.too_slow threshold configurable

### ISSUE THREAD

**Issue by roganartu** [HypothesisWorks/hypothesis#2100]
# Problem
The threshold for triggering the `too_slow` healthcheck is hardcoded to 1s:
https://github.com/HypothesisWorks/hypothesis/blob/e62b854b9737bb16fc3e330d1cb42d19ac1ad2d0/hypothesis-python/src/hypothesis/internal/conjecture/engine.py#L306-L323

This forces anyone who may have a legitimate case for tolerating longer generation times to completely disable this healthcheck for the given test, which is a less than ideal tradeoff.

# Context
I have some tests that are flaky when I don't disable this healthcheck. The strategies successfully generate some examples, just not quite enough for whatever reason. From the numbers of generated examples I see, I suspect that being able to bump this threshold from 1s to 2-3s would completely resolve these occasional failures. My test run times aren't appreciably longer with this healthcheck disabled.

The strategies that are causing this failure mode are somewhat complex due to their nature and the goals of the tests. I might be doing something, and I'd be happy to try and provide some more context and maybe an example strategy if it sounds like I'm using Hypothesis in a way it's not designed.

Specifically, I'm writing a client for a rest API that has all returned objects documented, including field types and optionality. The custom strategies build JSON objects that match this spec, which involves conditionally adding fields as follows:
```
result = draw(st.fixed_dictionaries({<all required fields>}))
if draw(st.booleans(), label=f"model - include foo?"):
    result["foo"] = st.floats()
...
```
The goal obviously being to make sure the client doesn't bork on any valid combination of the documented fields.

**Comment by Zac-HD** [comment]
I'd be happy to comment on your strategies, if you have some spec/strategy pairs that you can share.  You might also want to check out `hypothesis-jsonschema` or a similar extension package, or #1913 which will make these definitions easier and more efficient!

I'm not really comfortable making the `too_slow` health check configurable - every setting we add means Hypothesis is more complicated, meaning more error-prone as well as harder to teach, document, or learn.  I suspect your data may simply be larger than most users', and would recommend just turning off the relevant healthcheck if I can't see a way to speed it up.
