### ISSUE TITLE
Request for adding Schemathesis to "Projects extending Hypothesis"

### ISSUE THREAD

**Issue by Stranger6667** [HypothesisWorks/hypothesis#2119]
Hello, dear Hypothesis team :)

Last couple of week I and my colleagues are developing a tool based on `hypothesis` and `hypothesis-jsonschema` that works for Open API schemas - [Schemathesis](https://github.com/kiwicom/schemathesis)

It was inspired by the project already listed in the docs - `swagger-conformance`. Unfortunately, the project is not active for more than one year and doesn't have Open API 3.0 support that we needed. So we decided to write our own tool and then discovered `hypothesis-jsonschema` that solved a lot of our tasks immediately :) @Zac-HD thank you very much for `hypothesis-jsonschema`.

Schemathesis has features that are provided by `swagger-conformance` but also deeper integration with `pytest` + Open API 3 support (via `hypothesis-jsonschema`).
We want to integrate it into our CI pipeline and plan put more effort into the project :) I think it could be useful for other people as well, but I am not sure what will be the best way to add its mention to the "Projects extending Hypothesis" list, because `swagger-conformance` is already there and the Schemathesis description will be very similar to it. What do you think? Can we have them both somehow?

Regards

**Comment by Zac-HD** [comment]
Hey @Stranger6667!  `schemathesis` looks great, and I'm delighted that `hypothesis-jsonschema` has been useful for you :heart: 

It looks like you're at least comparable to `swagger-comformance`, easier to use in code, and much more actively maintaineed too.  So I'd be happy if you basically replaced that paragraph in our docs with a similar one about `schemathesis`, and end it with something like "`schemathesis` was inspired by the earlier `swagger-comformance` library."

**Comment by Stranger6667** [comment]
Thanks, Zac!
Will do soon :) We will also appreciate any feedback on how we can do Schemathesis better :)
