### ISSUE TITLE
Config option to skip pytest_report_header

### ISSUE THREAD

**Issue by blueyed** [HypothesisWorks/hypothesis#2155]
With pytest's tests I am seeing the following line all the time.
I think it would be nice if it could be disabled (made quiet):

> hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/user/Vcs/pytest/.hypothesis/examples')

There's `--hypothesis-verbosity` already, but it appears to have a different purpose?

I think a config/ini option would be good (instead of a cli argument/param).

**Comment by Zac-HD** [comment]
Hmm, maybe we could have it disabled by default, but show it if either the pytest or Hypothesis verbosity was set at above default?

https://github.com/HypothesisWorks/hypothesis/blob/50c059c38c693d15f32eb9d928b7a6be3814579d/hypothesis-python/src/hypothesis/extra/pytestplugin.py#L74-L81

**Comment by blueyed** [comment]
That would be a good start / compromise I think.
Could use "verbosity > 1", i.e. with `-vv` then only maybe.
(Note that I'm not sure how useful that information is in general, and would not have hypothesis installed by default in pytest probably, since it does not appear to get used still really)

**Comment by blueyed** [comment]
Thanks!

**Comment by Zac-HD** [comment]
No problem!

**Comment by Zac-HD** [comment]
While I'm thinking about it actually, do you know of a way to check whether a test uses specifically function-scoped fixtures? We'd like to emit a warning for that from our pytest plugin; more in #377.
