### ISSUE TITLE
We should use `_`-prefixes for all private modules

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2175]
Distinguishing internal names like this makes it much easier for users to tell whether an API is supported or not.  It also integrates well with e.g. tab-completion tools, documentation tools like Sphinx, and so on.  TBH I've thought we should do this for a while, and been putting it off because the implementation is somewhere between tedious and annoying.

Moving `strategies.py` to `_strategies.py` and re-exporting only the public names is a useful precedent - if any users were negatively affected, they didn't bother to tell us.  It also demonstrates that we can proceed incrementally; it doesn't need to be a stop-the-world release.

**Comment by Zac-HD** [comment]
And it's probably a good idea to `_`-prefix non-user-facing names in general, like `SearchStrategy.do_draw`/`_do_draw`, but I'm not touching that at the moment.  If we get all the module names prefixed and sort out the public module namespaces we can consider methods and attributes then.

**Comment by DRMacIver** [comment]
Counterproposal: We already have the `hypothesis.internal` namespace. Why not just move all internal modules under there?

**Comment by Zac-HD** [comment]
Or, if users are unlikely to ever notice, why do this at all when we could be working on features or bugfixes instead?
