### ISSUE TITLE
How to concatenate various strategies in one input data

### ISSUE THREAD

**Issue by mitzkia** [HypothesisWorks/hypothesis#2176]
Sorry if this was already a question. 
Sorry if the title is misleading. 
My goal would be to create an input in "@given" time.

In my one of the use cases I would like to create such input data: "text() text() ...". 
Which is a several appended text() values resulted in one string type.

For now I can only achieve it with the following (ugly) code:
```
text(alphabet=sampled_from([\"'{}' \".format(''.join([random.choice(string.ascii_letters + string.digits) for i in range(15)]))]), min_size=2)"
```

In my other use-case I would like to create such result: "text() integers()". So there are several cases where it would be used.

My question is there an easier (native) way to create such input values?

I have also tried the following (but it returns with and error): 
```
@given(text(alphabet=sampled_from([text()]))).
```

```
self = lists(elements=just(text())).map(u''.join), ls = [text()]

    def pack(self, ls):
>       return u"".join(ls)
E       TypeError: sequence item 0: expected str instance, LazyStrategy found

ls         = [text()]
self       = lists(elements=just(text())).map(u''.join)

/home/micek/.local/lib/python3.8/site-packages/hypothesis/searchstrategy/strings.py:83: TypeError
```

Thanks for your help

**Comment by Zac-HD** [comment]
Can you give a list of example inputs that you would like to generate?  I really don't understand what you're trying to do.

Some ideas:

- If you want to create tuples where the first value is a string and the second is (say) an integer, `st.tuples(st.text(), st.integers())` will do that.
- If you want strings of any length, `st.text()` can do that natively.  The `alphabet` argument has to be a collection of single characters (length-one strings), or a strategy that generates those (such as `st.characters()`).
- st.sampled_from()` takes a sequence of values; if you want to combine strategies that's `st.one_of()`.

As general advice, it would probably help to pay close attention to what needs to be a *strategy*, and what should be a *value* - most of your problems are probably coming from that.

-------------

```python
@given(text(alphabet=sampled_from([text()])))
# should probably be
@given(lists(elements=text()).map("".join))
```

I *think* below you're trying to generate strings which consist of `repr`s of strings separated by a space?  

```python
text(alphabet=sampled_from(["'{}' ".format(''.join([random.choice(string.ascii_letters + string.digits) for i in range(15)]))]), min_size=2)
```

- The outer `text()` is the wrong choice for that, as everything in the alphabet must be of length one.  Instead, we'll generate a list of parts and then join them.
- Please never use `random` when defining Hypothesis strategies - `st.sampled_from()` would be fine here, or we can use it as an `alphabet`!

```python
st.lists(
	st.text(
		alphabet=string.ascii_letters + string.digits,
		min_size=15,
		max_size=15,
	).map(repr),
	min_size=2,
).map(" ".join)
```

```
# generated by `s.example()`:
"'H00000000000000' '000000000000000'"
"'P0044X000XXX000' 'XXXX04X040X00XX'"
"'lTtrgKmTrtTrgmK' 'TrtKTtgTTTgrTgr' 'rTmKKmKmTggTrmg' 'TgTmKrgggrggtmt' 'mKrrKttmTKmtrgg' 'tgggmmTrTTtrgTm' 'gTtmKgKgTrmmrrK' 'rmTgmTtrtKmTTgt' 'gKrrmrKmtTrKmgt' 'tTTgmrTmKrrTgTm' 'mgrmgTTmgKKKrtT' 'mmmrrttTrtrTTmg' 'TtKTrmmgtrmggKT' 'KmKTrTrmrtKTtrm'"
"'Z0JbJib000J000J' 'FbF00JJF0FFJJiu' 'JFu0F0ub0J0J00b' 'bJFiiiu0bubiu0b' 'FbJbbu0bF0b0ii0' 'bFiiubi0u0bui00'"
"'j02yI006N3Aj0m7' 'UIAXEjrm1x0KaTc'"
```

**Comment by mitzkia** [comment]
Thank you very much for your help, clean explanation and of course for the examples, they helped me a lot.
I have just started to learn Hypothesis and related terminologies (my opinion it is awesome :) )
Back to my issue, you have realized what was my plan with the strategies.
During my original test I does not pay attention on lists() strategy, and it can do the trick for me


My understanding in step-by-step:
* This form will help to mix any kind of strategies in one final list strategy (found in Hypothesis unit tests): 
```
@given(lists(text() | integers() | booleans()))
```
* map(repr) will help to get the printable representation of the generated strategies
```
@given(lists(text(alphabet=string.printable, min_size=1).map(repr) | integers().map(repr) | booleans().map(repr)))
```
* map(" ".join) will convert the whole results into one string type
```
@given(lists(text(alphabet=string.printable, min_size=1).map(repr) | integers().map(repr) | booleans().map(repr)).map(" ".join))
```

And that is what I am looking for.

Thanks again

**Comment by mitzkia** [comment]
One final question :)
In my last example how can I set that I would like to get at least one from each strategies:
```
@given(lists(text(alphabet=string.printable, min_size=1).map(repr) | integers().map(repr) | booleans().map(repr)).map(" ".join))
```

I would like to got at least 1 text, 1 integer and 1 boolean, with the OR operator it does not guaranteed.

Thanks

**Comment by Zac-HD** [comment]
Yep, that's all correct!  Note that `lists(text() | integers() | booleans())` is the same as `lists(elements=one_of(text(), integers(), booleans()))` if the parentheses make it clearer.  `integers().map(str)` is a strategy that draws an integer, calls `str` on it, and returns the result :smile: 

To get one of each, the best way is probably a filter:

```python
lists(
	elements=one_of(text(), integers(), booleans()), 
	min_size=3,
).filter(
	lambda ls: set(type(x) for x in ls) == {str, int, bool}
)
```

This tells Hypothesis to start with lists of at least three elements (the smallest that can be valid), and then throw away any that do not have the required types before giving it to the user.  I hope that makes sense!

If you have any further questions, I recommend using the [`python-hypothesis` tag on StackOverflow](https://stackoverflow.com/questions/tagged/python-hypothesis) where others can answer, and more importantly find previous questions.

**Comment by mitzkia** [comment]
Thanks a lot for the answer (it helped), and I will check also the StackOverflow questions.
