### ISSUE TITLE
Attempting to draw interactively from not-a-strategy should raise InvalidArgument

### ISSUE THREAD

**Issue by rsokl** [HypothesisWorks/hypothesis#2178]
Attempting to draw interactively from a non-strategy object raises an attribute error in an attempt to call `is_empty()` on the object.

E.g.
```python
 import hypothesis.strategies as st
 from hypothesis import given

@given(st.data())
def test_draw_bad(data):
    data.draw("apple")
```
```python
>>> test_draw_bad()
AttributeError: 'str' object has no attribute 'is_empty'
```

This should raise `InvalidArgument`

**Comment by Zac-HD** [comment]
And we should check that `@composite` dors a typecheck too.
