### ISSUE TITLE
4.44.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [HypothesisWorks/hypothesis#2203]
<pre>+ /usr/bin/python3 setup.py test
running test
Searching for attrs&gt;=19.2.0
Reading https://pypi.org/simple/attrs/
Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl#sha256=08a96c641c3a74e44eb59afb61a24f2cb9f4d7188748e76ba4bb5edfa3cb7d1c
Best match: attrs 19.3.0
Processing attrs-19.3.0-py2.py3-none-any.whl
Installing attrs-19.3.0-py2.py3-none-any.whl to /home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-4.44.0/hypothesis-python/.eggs
writing requirements to /home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-4.44.0/hypothesis-python/.eggs/attrs-19.3.0-py3.8.egg/EGG-INFO/requires.txt

Installed /home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-4.44.0/hypothesis-python/.eggs/attrs-19.3.0-py3.8.egg
running egg_info
writing src/hypothesis.egg-info/PKG-INFO
writing dependency_links to src/hypothesis.egg-info/dependency_links.txt
writing entry points to src/hypothesis.egg-info/entry_points.txt
writing requirements to src/hypothesis.egg-info/requires.txt
writing top-level names to src/hypothesis.egg-info/top_level.txt
reading manifest file &apos;src/hypothesis.egg-info/SOURCES.txt&apos;
reading manifest template &apos;MANIFEST.in&apos;
writing manifest file &apos;src/hypothesis.egg-info/SOURCES.txt&apos;
running build_ext
Exception ignored in: &lt;_io.FileIO name=&apos;/usr/share/zoneinfo/zone.tab&apos; mode=&apos;rb&apos; closefd=True&gt;
Traceback (most recent call last):
  File &quot;/usr/lib/python3.8/site-packages/pytz/__init__.py&quot;, line 515, in &lt;module&gt;
    common_timezones = [l.split()[2]
ResourceWarning: unclosed file &lt;_io.TextIOWrapper name=&apos;/usr/share/zoneinfo/zone.tab&apos; mode=&apos;r&apos; encoding=&apos;UTF-8&apos;&gt;
Traceback (most recent call last):
  File &quot;setup.py&quot;, line 82, in &lt;module&gt;
    setuptools.setup(
  File &quot;/usr/lib/python3.8/site-packages/setuptools/__init__.py&quot;, line 145, in setup
    return distutils.core.setup(**attrs)
  File &quot;/usr/lib64/python3.8/distutils/core.py&quot;, line 148, in setup
    dist.run_commands()
  File &quot;/usr/lib64/python3.8/distutils/dist.py&quot;, line 966, in run_commands
    self.run_command(cmd)
  File &quot;/usr/lib64/python3.8/distutils/dist.py&quot;, line 985, in run_command
    cmd_obj.run()
  File &quot;/usr/lib/python3.8/site-packages/setuptools/command/test.py&quot;, line 229, in run
    self.run_tests()
  File &quot;/usr/lib/python3.8/site-packages/setuptools/command/test.py&quot;, line 247, in run_tests
    test = unittest.main(
  File &quot;/usr/lib64/python3.8/unittest/main.py&quot;, line 100, in __init__
    self.parseArgs(argv)
  File &quot;/usr/lib64/python3.8/unittest/main.py&quot;, line 124, in parseArgs
    self._do_discovery(argv[2:])
  File &quot;/usr/lib64/python3.8/unittest/main.py&quot;, line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File &quot;/usr/lib64/python3.8/unittest/main.py&quot;, line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File &quot;/usr/lib/python3.8/site-packages/setuptools/command/test.py&quot;, line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File &quot;/usr/lib/python3.8/site-packages/setuptools/command/test.py&quot;, line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File &quot;/usr/lib64/python3.8/unittest/loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-4.44.0/hypothesis-python/tests/py3/test_asyncio.py&quot;, line 32, in &lt;module&gt;
    class TestAsyncio(TestCase):
  File &quot;/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-4.44.0/hypothesis-python/tests/py3/test_asyncio.py&quot;, line 65, in TestAsyncio
    def test_foo(self, x):
  File &quot;/usr/lib64/python3.8/asyncio/coroutines.py&quot;, line 111, in coroutine
    warnings.warn(&apos;&quot;@coroutine&quot; decorator is deprecated since Python 3.8, use &quot;async def&quot; instead&apos;,
DeprecationWarning: &quot;@coroutine&quot; decorator is deprecated since Python 3.8, use &quot;async def&quot; instead
error: Bad exit status from /var/tmp/rpm-tmp.pPB64W (%check)
</pre>

**Comment by Zac-HD** [comment]
We already have Python 3.8 running in CI, and the relevant test is skipped on that version:

https://github.com/HypothesisWorks/hypothesis/blob/b1a557ca4f333e74332056246941c19d560b5427/hypothesis-python/tests/py3/test_asyncio.py#L62-L68

Note that [invoking `setup.py` directly is deprecated](https://setuptools.readthedocs.io/en/latest/setuptools.html#test-build-package-and-run-a-unittest-suite), and our test suite is not intended to support this.  I think the problem is mostly that you're running them with `unittest` rather than `pytest`.

**Comment by Zalathar** [comment]
Be aware that skipping the test doesn't actually stop the deprecation warning, since the decorator is called eagerly.

(You can see the warning in our CI build logs for 3.8; it just isn't treated as fatal.)

**Comment by kloczek** [comment]
pytest is failing as well.

<pre>[tkloczko@barrel hypothesis-hypothesis-python-4.44.0]$ pytest
<b>========================================================================== test session starts ==========================================================================</b>
platform linux -- Python 3.8.0, pytest-4.6.6, py-1.8.0, pluggy-0.12.0
rootdir: /home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-4.44.0, inifile: pytest.ini
plugins: expect-1.1.0
<b>collected 0 items / 1 errors                                                                                                                                            </b>

================================================================================ ERRORS =================================================================================
<font color="#CC0000"><b>_____________________________________________________________________ ERROR collecting test session _____________________________________________________________________</b></font>
Traceback (most recent call last):
  File &quot;/usr/lib/python3.8/site-packages/_pytest/config/__init__.py&quot;, line 440, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local(&apos;/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-4.44.0/hypothesis-python/tests/conftest.py&apos;)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/usr/lib/python3.8/site-packages/_pytest/config/__init__.py&quot;, line 446, in _importconftest
    mod = conftestpath.pyimport()
  File &quot;/usr/lib/python3.8/site-packages/py/_path/local.py&quot;, line 701, in pyimport
    __import__(modname)
  File &quot;/usr/lib/python3.8/site-packages/_pytest/assertion/rewrite.py&quot;, line 304, in load_module
    exec(co, mod.__dict__)
  File &quot;/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-4.44.0/hypothesis-python/tests/conftest.py&quot;, line 27, in &lt;module&gt;
    from hypothesis.internal.detection import is_hypothesis_test
ModuleNotFoundError: No module named &apos;hypothesis&apos;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/usr/lib/python3.8/site-packages/py/_path/common.py&quot;, line 377, in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
  File &quot;/usr/lib/python3.8/site-packages/py/_path/common.py&quot;, line 429, in gen
    for p in self.gen(subdir):
  File &quot;/usr/lib/python3.8/site-packages/py/_path/common.py&quot;, line 418, in gen
    dirs = self.optsort([p for p in entries
  File &quot;/usr/lib/python3.8/site-packages/py/_path/common.py&quot;, line 419, in &lt;listcomp&gt;
    if p.check(dir=1) and (rec is None or rec(p))])
  File &quot;/usr/lib/python3.8/site-packages/_pytest/main.py&quot;, line 667, in _recurse
    ihook = self.gethookproxy(dirpath)
  File &quot;/usr/lib/python3.8/site-packages/_pytest/main.py&quot;, line 482, in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
  File &quot;/usr/lib/python3.8/site-packages/_pytest/config/__init__.py&quot;, line 424, in _getconftestmodules
    mod = self._importconftest(conftestpath.realpath())
  File &quot;/usr/lib/python3.8/site-packages/_pytest/config/__init__.py&quot;, line 463, in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
_pytest.config.ConftestImportFailure: (local(&apos;/home/tkloczko/rpmbuild/BUILD/hypothesis-hypothesis-python-4.44.0/hypothesis-python/tests/conftest.py&apos;), (&lt;class &apos;ModuleNotFoundError&apos;&gt;, ModuleNotFoundError(&quot;No module named &apos;hypothesis&apos;&quot;), &lt;traceback object at 0x7fde2929fe00&gt;))
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
<font color="#CC0000"><b>======================================================================== 1 error in 0.09 seconds ========================================================================</b></font>
</pre>

**Comment by Zac-HD** [comment]
Start with `pip install .`, or use `tox` - our tests [run against an installed version](https://hynek.me/articles/testing-packaging/).
