### ISSUE TITLE
RFC: Undeprecating `find`

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#2236]
We've marked `find` as deprecated because, I quote:

```
`find(s, f)` is deprecated, because it is rarely used but takes ongoing work to maintain as we upgrade other parts of Hypothesis.
```

I don't think either of these parts are really true.

1.  `find` has a smallish base of users, but they're quite enthusiastic about it. It's probably used more often than, say, `hypothesis.extra.django`, or many of our niche strategies.
2. It really doesn't involve much maintenance at all. #2235 is pretty much the first time we've touched it in years other than to deprecate it, and it will reduce any future maintenance even further because it's now using exactly the same machinery as everything else.

Against that, find is a convenient tool for exploring Hypothesis, and is often useful in its own right, and having to rephrase interactive experimentation with it in terms of given style tests is kinda a pain.

**Comment by Zac-HD** [comment]
Fine by me - I think the case for deprecation was basically that it was too different from `@given` for both maintainers and users (i.e. had a different data distribution), which is clearly no longer true :smile:
