### ISSUE TITLE
@example does not allow partial example

### ISSUE THREAD

**Issue by diorge** [HypothesisWorks/hypothesis#2271]
This is a potential new feature I suppose.

I had a use case where a test takes two parameters defined by a hypothesis strategy in given. I want to make an example where I have a fixed value for one of the parameters, but I don't really care what the other parameter is.

Minimal case:

```python
@given(text(), integers(max_value=0))
@example(some_integer=0)
def test_something(some_string, some_integer):
    r = call_something(some_string, some_integer)
    assert r == -1
```

In this test the behavior should be the same for any some_integer < 1, but I want to specifically test the case where some_integer == 0. This behavior does depend on the value of some_string, but I still need it to exist so I can pass to the function.

Using the code above will raise a `TypeError: No value provided for argument some_string`. The ideal in my case would be to use the strategy to build some_string then use the some_integer as 0 when testing the provided example.

The workaround is to have a dummy some_string in the example, but this loses the property of "the behavior should be the same regardless of some_string's value".

**Comment by DRMacIver** [comment]
I'm afraid this isn't going to be a feature we can support.

The fundamental problem is that Hypothesis supports testing with mutable data, and is currently quite careful to support this with `@example` by ensuring we never call the same test twice with the same example argument, which this would break.

The other issue, which isn't fundamental per se but is hard to work around, is that even if we somehow were able to fix that, the current `@given` argument juggling code is kinda a nightmare and this would exacerbate that in a fairly big way.

My recommendation would be to extract your test function as a helper and write two `@given` tests - one which takes the full set of arguments and one that takes a specialised form.
