### ISSUE TITLE
one_of shows duplicate strategies for from_type(Hashable)

### ISSUE THREAD

**Issue by leaprovenzano** [HypothesisWorks/hypothesis#2291]
hypothesis: 4.56.1
python : 3.7.4

----

following on from https://github.com/HypothesisWorks/hypothesis/pull/2274 `from_type(typing.Hashable)` is no longer erroring for me. (again thanks to @Zac-HD for all the help!) . That said... I am finding some more odd stuff with `from_type` particularly around generics & abcs. I will try and post separate issues and link them since I don't want to muddle things up.

This one is more of a question....

```python
from typing import Hashable
from hypothesis import strategies as st

strat = st.from_type(Hashable)
print(strat.branches)
```
```
[none(),
 just(NotImplemented),
 dates(),
 times(),
 timezones(),
 just(Ellipsis),
 nested_dtypes(),
 builds(BytesIO, binary()),
 complex_numbers(),
 binary(),
 complex_numbers(),
 floats(),
 complex_numbers(),
 builds(StringIO, text())]
```

as you can see above `complex_numbers()` appears 3 times in the branches.  This strategy is double wrapped in a deferred strategy so to get to the inner i think its `strat.wrapped_strategy.wrapped_strategy`.

**QUESTION** :Is this going to cause issues with shrinking?  Shouldn't `one_of` resolve dupes in all cases? Or is this not a problem?

I tried doing 
```python
st.deferred(lambda : st.deferred( lambda : st.one_of([st.integers(), st.integers()])))
```
 and saw that in that case branches were properly reduced to:
 ```[integers()]```
so maybe it's just something going on with `from_type`....  or maybe just a repr issue...

I also have some suggestions about the content of this strategy but again i will post those in another issue since it's a broader thing around strategy content on abcs.

**Comment by Zac-HD** [comment]
Thanks so much for continuing to investigate and report on this!

That is indeed odd... it shouldn't harm shrinking, but might be less efficient than it needs to be. I'll need to check if this is handled in one_of (and just a display bug), or whether it's a real problem. 

Looking forward to hearing your suggestions 😊

**Comment by Zac-HD** [comment]
Turns out that this is because strategies are hashable, but don't define a `__hash__` method - so it's just by identity!  While the deduplication code in `one_of` is already vital (for e.g. recursive strategies), it could clearly be a lot better!

**Comment by leaprovenzano** [comment]
> Turns out that this is because strategies are hashable, but don't define a `__hash__` method - so it's just by identity! While the deduplication code in `one_of` is already vital (for e.g. recursive strategies), it could clearly be a lot better...

oh wow ok!  that makes sense.  I wasn't sure if i'd introduced a bug somewhere with  that `from_type(Hashable.__origin__)` stuff ... was trying to trace it and couldn't quite figure it out. will be interested to see the fix.

**Comment by Zac-HD** [comment]
https://github.com/HypothesisWorks/hypothesis/compare/master...Zac-HD:hashable-strategies shows a current draft... which doesn't *quite* work.  Hashing really doesn't play nicely with lazy instantiation and instances which are distinguished by mutable attributes... and we have those *everywhere*.  So it's easy to make it work a little, but intractable to make it worthwhile.

Given that this is a minor performance issue but doesn't affect correctness at all, I'm inclined to leave things as they are :confused:

**Comment by DRMacIver** [comment]
> master...Zac-HD:hashable-strategies shows a current draft... which doesn't quite work. Hashing really doesn't play nicely with lazy instantiation and instances which are distinguished by mutable attributes... and we have those everywhere. So it's easy to make it work a little, but intractable to make it worthwhile.

Also we'd still need to implement `__eq__`, and `__eq__` for recursive objects is hard and fiddly.
