### ISSUE TITLE
Should deferred validate definition as a callable in __init__?

### ISSUE THREAD

**Issue by leaprovenzano** [HypothesisWorks/hypothesis#2295]
Was looking around in strategies and noticed this:

https://github.com/HypothesisWorks/hypothesis/blob/c12c8a9ab1a3eb1d42ca59517999a5fbd58898a3/hypothesis-python/src/hypothesis/strategies/_internal/deferred.py#L27-L46

**Question** : is there any reason we don't validate that `definition` as function  in the constructor?

Would stop me from being able to do something silly like this and still get through test collection...

```Python
from hypothesis import given
from hypothesis.strategies import deferred

@given(deferred('boop!'))
def test(x):
    ...
```

**Comment by Zac-HD** [comment]
Hmm, I'd expect this to be validated even earlier, in the strategy function! Do the tests still pass if you move the check there? If so, I'll be happy to accept a PR after checking the git history in case there's some reason to write a better test instead 😉

https://github.com/HypothesisWorks/hypothesis/blob/c12c8a9ab1a3eb1d42ca59517999a5fbd58898a3/hypothesis-python/src/hypothesis/strategies/_internal/core.py#L2260-L2291

**Comment by leaprovenzano** [comment]
cool i'll have a pr up in a sec...

**Comment by Zac-HD** [comment]
Closing this issue because the current location of the check turns out to be required in order to raise the error at test time, rather than collection time.
