### ISSUE TITLE
Let defaults exist

### ISSUE THREAD

**Issue by SoniEx2** [HypothesisWorks/hypothesis#2305]
There is absolutely no reason something like

```
@hypothesis.given(foo=st.text())
def test_re(foo, pat=re.compile("...")):
    pass
```

(or other expensive compilation step instead of regex compilation) shouldn't be allowed to work.

**Comment by rsokl** [comment]
You can do:

```python
@hypothesis.given(foo=st.text(), pat=st.just(re.compile("...")))
def test_re(foo, pat):
    pass
```

**Comment by SoniEx2** [comment]
doesn't play nice with `@hypothesis.example`

**Comment by rsokl** [comment]
```python
expensive = re.compile("...")

@example(foo="moo", pat=expensive)
@hypothesis.given(foo=st.text(), pat=st.just(expensive))
def test_re(foo, pat):
    pass
```

> There is absolutely no reason [...]

There are plenty of reasons why this might not be supported. For example, up until a few days ago Hypothesis supported Python 2. The stdlib tooling for function signatures evolved wildly from Python 2 to early versions of Python 3 and then through Python 3.5. The overhead for normalizing these utilities across versions to ensure that the UX is consistent was expensive.

**Comment by SoniEx2** [comment]
couldn't it simply ignore the existence of defaults? this is what I mean by "absolutely no reason"

**Comment by rsokl** [comment]
Then you have the hairy error handling of scenarios like:

```python
@given(a=st.integers()
def a_confusing_bad_test(a, b=st.integers())
    # b is going to behave really badly
```

**Comment by SoniEx2** [comment]
or ignore them if they're not relevant/not explicitly passed in.

**Comment by DRMacIver** [comment]
In the interests of enforcing good behaviour, I've blocked @SoniEx2. This is a temporary ban that will be lifted in a week.

This was an extremely unhelpful way to file a bug report (and we've got perfectly good reasons for not supporting this feature), and I didn't think people should have to deal with it.
