### ISSUE TITLE
Add a strategy for `ipaddress` address objects, deprecate provisional strategy for IP addr strings

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2306]
Now that Hypothesis is Python-3-only (:tada:), there are some useful things we can rely on having available - like [the `ipaddress` module](https://docs.python.org/3/library/ipaddress.html)!  I think that we should:

- Add a strategy `ip_addresses(*, v=None, network=None)`.  `v` may be either `4` or `6`; `network` may be an `IPv4Network` or `IPv6Network` object (or string - I think the ergonomics justify handling the cast internally).
- Deprecate `hypothesis.provisional.ip{4,6}_addr_strings()` in favor of `ip_addresses(v=...).map(str)`
- Register strategies for `IPv{4,6}{Address,Network,Interface}` by entering them in the `_global_type_lookup` mapping in `hypothesis.strategies._internal.types`

**Comment by DRMacIver** [comment]
> Deprecate hypothesis.provisional.ip{4,6}_addr_strings() in favor of st.from_type(IPv{4,6}Address).map(str), using hypothesis._settings.note_deprecation

I'm pretty strongly against this. We shouldn't have `from_type` be our primary interface to any strategies.

We could certainly switch to providing strategies for the `IPAddress` classes and deprecate in favour of using those, but they should be available without going through `from_type`.

**Comment by Zac-HD** [comment]
Makes sense... I've described an API I think makes sense above, and since it's no longer a good first issue (IMO), I've untagged it and will write a draft soon.

**Comment by DRMacIver** [comment]
> Add a strategy ip_addresses(*, v=None, network=None). v may be either 4 or 6; network may be an IPv4Network or IPv6Network object (

I wonder if it's worth making these separate functions to avoid the issue of what happens when you pass `v=6, network=IPv4Network(...)`?

**Comment by Zac-HD** [comment]
```python
    if v not in (None, network.version):
        raise InvalidArgument("v=%r is incompatible with network=%r" % (v, network))
```

No `IPv4Address` is ever `in` an `IPv6Network` (or vice-versa) even if the address is in range, so they're strictly incompatible and raising an error is the obvious and only sensible response.

I did look at splitting it into a pair of strategies, but the `ipaddress` module is really designed to promote version-blind code - that is, to make ip6-compatible code handle ip4 addresses too - and it seemed rather a shame to go against that.  For example the [version-blind constructors](https://docs.python.org/3/library/ipaddress.html#convenience-factory-functions) are at the top of the docs!

**Comment by DRMacIver** [comment]
> No IPv4Address is ever in an IPv6Network (or vice-versa) even if the address is in range, so they're strictly incompatible and raising an error is the obvious and only sensible response.

It is, but it's better to avoid functions with interacting arguments (as promoted by our API guide).

That being said, I'm happy to accept the version blind API argument as reason for an exception.

**Comment by Zac-HD** [comment]
After #2309, https://github.com/Zac-HD/hypothesis/compare/convert-hints...ipaddress-strategies :rocket:
