### ISSUE TITLE
How to change a setting for all tests in my suite?

### ISSUE THREAD

**Issue by halloleo** [HypothesisWorks/hypothesis#2310]
I know I can change a setting for *one* test via

```
@given(integers())
@settings(max_examples=500)
def test_this_thoroughly(x):
    pass
```

But if I have lots of tests 

`test_this_thoroughly`,   
`test_that_thoroughly`,  
`test_this_over_here_thoroughly`,  
`test_that_over_there_thoroughly`,  
.  
.  
.  

how can I change the max_example setting for *all* of them?

**Comment by Zac-HD** [comment]
https://hypothesis.readthedocs.io/en/latest/settings.html#default-settings

**Comment by halloleo** [comment]
Thanks @Zac-HD . I tried 

    ht.settings.default.max_examples = 10

but get the error "_settings objects are immutable_....". Looks like there is no way to change one individual global setting property... 

The other thing I found in the doco were [profiles](https://hypothesis.readthedocs.io/en/latest/settings.html#settings-profiles), but it feels like a bit over the top to create a new named profile, register and load it, just to change one global setting like the `max_examples` property...

What's the shortest way to do this?

**Comment by Zac-HD** [comment]
Profiles are the only way to do this.

The heaviness is actually deliberate - it ensures that it's possible to grep for every place where the default settings are changed!

**Comment by halloleo** [comment]
Ok, so the briefest way is:

settings.register_profile('base', max_examples=200, verbosity=ht.Verbosity.verbose)
settings.load_profile('base')

Right? Do you think it would be worth it to have this as an example?
