### ISSUE TITLE
Cannot unpack non-iterable MultipleResults object

### ISSUE THREAD

**Issue by vxgmichel** [HypothesisWorks/hypothesis#2311]
Hi !

I ran into a problem with the falsifying examples produced by stateful testing with multiple results. 

Consider the following state machine:
```python
from hypothesis.stateful import Bundle, RuleBasedStateMachine
from hypothesis.stateful import rule, multiple, initialize


class DatabaseComparison(RuleBasedStateMachine):

    values = Bundle("values")

    @initialize(target=values)
    def produce(self):
        return multiple(1, 2, 3)

    @rule(v=values)
    def check(self, v):
        assert v == 1


TestDBComparison = DatabaseComparison.TestCase
```
It legitimately fails with the following info:
```
E       AssertionError: assert 3 == 1

test_hypo.py:16: AssertionError
---------------------- Hypothesis --------------------
Falsifying example:
state = DatabaseComparison()
v1, v2, v3 = state.produce()
state.check(v=v3)
state.teardown()
```
Let's put the falsifying example into a dedicated test:
```python
def test_reproduce():
    state = DatabaseComparison()
    v1, v2, v3 = state.produce()
    state.check(v=v3)
    state.teardown()
```
The problem is that the test fails with the following error:
```
    def test_reproduce():
        state = DatabaseComparison()
>       v1, v2, v3 = state.produce()
E       TypeError: cannot unpack non-iterable MultipleResults object

test_hypo.py:24: TypeError
```
This can be fixed with the following change:
```python
def test_reproduce_fixed():
    state = DatabaseComparison()
    v1, v2, v3 = state.produce().values
    state.check(v=v3)
    state.teardown()
```
Which does produce the right error:
```
E       assert 3 == 1

test_hypo.py:16: AssertionError
```

**Comment by Zac-HD** [comment]
Definitely a bug - fortunately it's easy to fix, just adding an `__iter__` method to

https://github.com/HypothesisWorks/hypothesis/blob/47f82a1cc02aec5ee4d95a21df5a6eecc4aa1047/hypothesis-python/src/hypothesis/stateful.py#L355-L357

pasting your test case above into `hypothesis-python/tests/cover/test_stateful.py`.

Would you like to open a PR, and we can eliminate the workaround for `hypothesis-trio`?

**Comment by vxgmichel** [comment]
@Zac-HD 
> Would you like to open a PR, so python-trio/hypothesis-trio#5 doesn't need a workaround?

Done: #2312 :)
