### ISSUE TITLE
from_type(Hashable) does not appear to generate FrozenSet[Hashable] or Tuple[Hashable, ...] values

### ISSUE THREAD

**Issue by brandtbucher** [HypothesisWorks/hypothesis#2324]
It does not appear that that `from_type(Hashable)` generates recursive `FrozenSet[Hashable]` and `Tuple[Hashable, ...]` values.

Is it difficult to add built-in support for generating these? Currently, I need to register a custom recursive strategy, but it would be great for it to work out-of-the-box with `infer`!

**Comment by Zac-HD** [comment]
That's working as intended - when inferring strategies we tend to stick to scalars or non-recursive collections for performance reasons. It's easy to define your own, though:

```python
... = st.recursive(
    st.from_type(Hashable), 
    lambda s: st.frozensets(s) | st.lists(s).map(tuple)
)
```
