### ISSUE TITLE
Add `hypothesis-geometry` package to "External Strategies"

### ISSUE THREAD

**Issue by lycantropos** [HypothesisWorks/hypothesis#2325]
I've recently published a [`hypothesis-geometry` package](https://pypi.org/project/hypothesis-geometry/) for generating geometric objects like concave/convex planar contours, and I guess it can be helpful to the community, what should I do to add it to ["External Strategies" docs section](https://hypothesis.readthedocs.io/en/latest/strategies.html#external-strategies)?

(Also as a maintainer of [`hypothesis_sqlalchemy` package](https://pypi.org/project/hypothesis-sqlalchemy/) I think it will make given list more consistent if we rename it there to `hypothesis-sqlalchemy`).

**Comment by Zac-HD** [comment]
Just add a dot-point to https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/docs/strategies.rst#external-strategies

And yes, replacing that underscore with a dash would be nice 😅
