### ISSUE TITLE
Limit unsuccessful shrinks as well as successful

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#233]
When the chances of shrinking successfully are very low, shrinking can get stuck doing unsuccessful shrinks, which can make shrinking very unproductive. There should be a limit here too. See #231

**Comment by Zac-HD** [comment]
Ping @DRMacIver - is this still an issue in Hypothesis 3.x?  If so it should probably get some attention now that we might try to shrink multiple bugs in a single test.

**Comment by DRMacIver** [comment]
> Ping @DRMacIver - is this still an issue in Hypothesis 3.x? If so it should probably get some attention now that we might try to shrink multiple bugs in a single test.

I'm not sure. We could do some investigative work. In principle yes, it's absolutely still an issue, but in practice I think the modern shrinker is probably much better about not wasting effort than it was when I wrote this issue, so it might not be that useful.

**Comment by Zac-HD** [comment]
Closing this issue as 'no fix needed', because the modern shrinker is far less prone to getting stuck.  In particular, a full shrink pass either makes some progress (at most 500 times), or no progress is made and shrinking stops (treating the current example as minimal).

If this happens very slowly for your case, please open an issue and we'll try to make it faster.

**Comment by DRMacIver** [comment]
> Closing this issue as 'no fix needed', because the modern shrinker is far less prone to getting stuck. In particular, a full shrink pass either makes some progress (at most 500 times), or no progress is made and shrinking stops (treating the current example as minimal).

Technically this was *always* true. The big difference between the modern and the classic shrinker in this regard is that its hit rate is vastly better, so the number of failed attempts it makes is rarely more than about an order of magnitude more than the number of successful attempts it makes. Previously shrinking would still never get stuck, but it would sometimes take a very long time to realise that it was done.

(I agree with the closure, I'm just nitpicking about the reasons)
