### ISSUE TITLE
Public API to define strategies with reusable values

### ISSUE THREAD

**Issue by mvaled** [HypothesisWorks/hypothesis#2331]
When building complex data structure one way to do it is using `.map()`, `.flatmap()`, `composite` and other ways of composing a bigger strategy from simple ones.

I was reading the source code of many of the basic strategies like, for instance, `integers`. They are decorated with `defines_strategy_with_reusable_values` which basically states the promise that the generated values are immutable and safe to cache. But other API-level functions like `builds` are decorated with `defines_strategy` which makes no such promise. In general it depends on the callable if it returns or not an immutable value.

This issue proposes promoting (somehow) to the API a way for strategy creators to pledge the generation of immutable data.  This is only worthy if it were to have an impact in performance.

---

To have some context assume you have a simple data structure:

```python
@dataclass(frozen=True)
class Range(Generic[TOrd]):
    lowerbound: TOrd
    upperbound: TOrd

    # A bunch of methods to do diff, member test, etc...
```

`TOrd` is just a type variable bound to a generic protocol supporting `__le__` and `__lt__`.  An instance of `Range` represents a semi-open range `lowerbound <= x < upperbound`.

The following function creates a strategy to create instances of `Range[datetime]`:

```python
def datetime_ranges(dates=None):
    if dates is None:
        dates = strategies.datetimes()

    def _build_range(args):
        d1, d2 = args
        assume(d1 != d2)
        lower, upper = min(d1, d2), max(d1, d2)
        return Range(lower, upper)

    return strategies.tuples(dates, dates).map(_build_range)
```
Since `Range` is immutable I could inform hypothesis that it can cache and reuse the values generated by this strategy.  But, IFAIK, there's no a public API for this.

**Comment by Zalathar** [comment]
As far as I can tell, `has_reusable_values` is only used by a small number of our NumPy and Pandas strategies, to 
check whether it's OK to use the `elements` argument as the `fill` argument when no explicit `fill` argument is supplied.

In other words, users can always get equivalent behaviour by passing a suitable `fill` argument explicitly. So there is currently no benefit to exposing `has_reusable_values` in the public API.

**Comment by mvaled** [comment]
Hi @Zalathar,

> As far as I can tell, `has_reusable_values` is only used by a small number of our NumPy and Pandas strategies, to check whether it's OK to use the `elements` argument as the `fill` argument when no explicit `fill` argument is supplied.
>
> In other words, users can always get equivalent behaviour by passing a suitable `fill` argument explicitly. So there is currently no benefit to exposing `has_reusable_values` in the public API.

So, having `integers` defined like:

```python
@cacheable
@defines_strategy_with_reusable_values
def integers(min_value: int = None, max_value: int = None) -> SearchStrategy[int]:
    ...
```

has no impact in actually reusing values across tests.  

If that's so, then this issue is going the way of not being worthy.
