### ISSUE TITLE
mypy does not infer correct types of strategies

### ISSUE THREAD

**Issue by ShadowLNC** [HypothesisWorks/hypothesis#2349]
When I run `mypy` on the following code:

```py3
from hypothesis import strategies

strategies.fixed_dictionaries(
    {
        "settings": strategies.fixed_dictionaries(
            {
                "unit": strategies.sampled_from(["hours", "days", "weeks", "months", "years"]),
                "value": strategies.integers(min_value=0),
            }
        ),
        "type": strategies.just("elapsed"),
    }
)
```

I get the following error for both `fixed_dictionaries` calls:
```
Argument 1 to "fixed_dictionaries" has incompatible type "Dict[str, object]"; expected "Dict[str, SearchStrategy[<nothing>]]"
```

Omitting either entry from one of the dictionaries resolves the issue (for the given dictionary), so it seems when both entries are present, `mypy` is incorrectly inferring the dictionary type. I don't know if this is a bug within Hypothesis, or mypy.

Python 3.8.0
mypy 0.761
Hypothesis 5.5.0
On Ubuntu 64 bit with kernel 5.3.0-24-generic.

**Comment by Zac-HD** [comment]
Looks like `mypy` just can't or doesn't infer the value type of your dicts, and so the error is when it can't tell that they're strategies when passing it to `fixed_dictionaries()`.

It's pretty verbose, but if you don't want to just `# type: ignore` it you can annotate each dict:

```python
from hypothesis.strategies import *
from typing import *

inner: Dict[str, SearchStrategy] = {
    "unit": sampled_from(["hours", "days", "weeks", "months", "years"]),
    "value": integers(min_value=0),
}
outer: Dict[str, SearchStrategy] = {
    "settings": fixed_dictionaries(inner),
    "type": just("elapsed"),
}

s = fixed_dictionaries(outer)
reveal_type(s)  # note: Revealed type is SearchStrategy[builtins.dict[builtins.str*, Any]]
```

----------------

If you don't mind considerably more verbosity, you can also specify the contents of each dict and it *will* flow through to the strategy:

```python
inner: Dict[str, SearchStrategy[Union[int, str]]] = ...
outer: Dict[str, SearchStrategy[Union[str, Dict[str, Union[int, str]]]]] = ...
# note: Revealed type is SearchStrategy[builtins.dict[builtins.str*, Union[builtins.str, builtins.dict[builtins.str, Union[builtins.int, builtins.str]]]]]
```

In principle you should even be able to use the per-key `TypedDict` (new in 3.8), though I'm not sure what `mypy` would infer for the strategy if you did - we might need to pull out a few `@typing.overload` cases for precision.

--------------

I'm going to open an upstream issue to see if we can make your example code work like the first fix I suggested - you'd get an `Any` but at least not an error!

**Comment by ShadowLNC** [comment]
Thanks for the update - feel free to close this if you wish, since it's a mypy issue.
