### ISSUE TITLE
Travis builds failing due to pyenv install issue

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2350]
See #2347, https://travis-ci.org/HypothesisWorks/hypothesis/jobs/649261770#L726-L739

**Comment by DRMacIver** [comment]
This looks like https://github.com/pypa/virtualenv/issues/1515 which should be fixed in the latest release of virtualenv. Are we not using the latest and/or does this probelm go away when we clear caches?

**Comment by Zac-HD** [comment]
We are definitely using the latest release, and the problem does not go away when clearing caches :sob: 

(in fact we're pinning to `20.0.1`, but [override that with `build.sh`](https://github.com/HypothesisWorks/hypothesis/blob/a4a9de64c855432b1d86a03bcdb14bd2a3b5bbcf/build.sh#L42))

**Comment by Zac-HD** [comment]
Working now :man_shrugging:
