### ISSUE TITLE
Package `enum` requirement for Python2.7

### ISSUE THREAD

**Issue by alekseik1** [HypothesisWorks/hypothesis#2360]
Hello! Hypothesis seem to rely on `enum` package. However, it is not a part of standard library for Python2.7.
I get following error on Travis build:
```
ImportError: Failed to import test module: test_converter
262 Traceback (most recent call last):
263  File "/opt/python/2.7.15/lib/python2.7/unittest/loader.py", line 254, in _find_tests
264    module = self._get_module_from_name(name)
265  File "/opt/python/2.7.15/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
266    __import__(name)
267  File "/home/travis/build/alekseik1/ifg-py/tests/test_converter.py", line 4, in <module>
268    from hypothesis import given
269  File "/home/travis/build/alekseik1/ifg-py/.tox/py27/lib/python2.7/site-packages/hypothesis/__init__.py", line 27, in <module>
270    from hypothesis._settings import (
271  File "/home/travis/build/alekseik1/ifg-py/.tox/py27/lib/python2.7/site-packages/hypothesis/_settings.py", line 31, in <module>
272    from enum import Enum, IntEnum, unique
273 ImportError: No module named enum
```
I tried to install `enum34` as suggested [here](https://stackoverflow.com/questions/26828206/importerror-no-module-named-enum) but it didn't help.
I use `tox` package for testing and my tests pass if running on locale machine (_not_ Travis CI). However, these tests fail on Travis. [Here](https://travis-ci.org/alekseik1/ifg-py/jobs/653757131/config) is my Travis config.

I think that a proper `enum` dependency should be added in `setup.py` file for Hypothesis. Could you please investigate this?

**Comment by DRMacIver** [comment]
It looks like you're trying to install a recent version of Hypothesis on a version of Python which is unsupported - Hypothesis 5.x no longer supports Python 2. This should be handled automatically with the `python_requires` configuration. Are you perhaps running an old version of pip too?
