### ISSUE TITLE
4.x version docs on RTD

### ISSUE THREAD

**Issue by dmitry-mukhin** [HypothesisWorks/hypothesis#2362]
For those unlucky of us who are still stuck with Python 2, it would be nice to have latest 4.x documentation live on RTD.

**Comment by Zac-HD** [comment]
Done, and available at e.g. https://hypothesis.readthedocs.io/en/hypothesis-python-4.57.1/changes.html

**Comment by dmitry-mukhin** [comment]
thanks!
