### ISSUE TITLE
st.composite swallows type annotations

### ISSUE THREAD

**Issue by MaxG87** [HypothesisWorks/hypothesis#2365]
I am using Python 3.8 and Hypothesis 5.5.4.

I make heavy use of `st.composite`. I noticed that using `draw` inside a composite strategy swallows the type annotations. Please consider the following MWE:

```python
from typing import Callable, TypeVar

from hypothesis import strategies as st

_T = TypeVar("_T")
DRAW_TYPE = Callable[[st.SearchStrategy[_T]], _T]


@st.composite
def my_strategy(draw: DRAW_TYPE) -> None:
    bool_strategy: int = st.booleans()  # correctly complains about type mismatch
    draw_: int = draw  # incorrectly expects Callable[[SearchStrategy[Any]], Any]
    draw_from_nonsense = draw(range(100))  # incorrectly expects SearchStrategy[Any]
    ret_val: int = draw(st.booleans())  # incorrectly does not complain
```
If I run `mypy` on it, I get:
```bash
/tmp/mwe.py:11: error: Incompatible types in assignment (expression has type "SearchStrategy[bool]", variable has type "int")
/tmp/mwe.py:12: error: Incompatible types in assignment (expression has type "Callable[[SearchStrategy[Any]], Any]", variable has type "int")
/tmp/mwe.py:13: error: Argument 1 has incompatible type "range"; expected "SearchStrategy[Any]"
Found 3 errors in 1 file (checked 1 source file)
```

I would expect the Hypothesis framework to provide support for `mypy` to pick up correct type annotations. This would greatly increase type safety.

**Comment by Zac-HD** [comment]
Unfortunately this will not be possible until [`PEP 612` is implemented](https://www.python.org/dev/peps/pep-0612/); I've been [active in the discussions](https://mail.python.org/archives/list/typing-sig@python.org/thread/UDHSH4EVVIDKNLRX2YGCIUCBGZ5ALRKC/) so it *will* work eventually but basically we just have to wait now.  Sorry!
