### ISSUE TITLE
Allow overriding the default database setting with an env var

### ISSUE THREAD

**Issue by dhirschfeld** [HypothesisWorks/hypothesis#2367]
Using an environment variable to control the default location of the `database` is a lighter-weight solution than forcing a user to write a conftest.py and passing in the profile name as an extra command-line arg.

It seems this could be fairly easily supported by modifying the below code:
https://github.com/HypothesisWorks/hypothesis/blob/ed7db589cc0ea44254b543475192635019adc87f/hypothesis-python/src/hypothesis/_settings.py#L406-L417

Perhaps something as simple as the below would work?
```python
settings._define_setting(
    "database",
    default=os.environ.get("PY_HYPOTHESIS_DATABASE", not_set),
    show_default=False,
    description="""
An instance of hypothesis.database.ExampleDatabase that will be
used to save examples to and load previous examples from. May be ``None``
in which case no storage will be used, ``":memory:"`` for an in-memory
database, or any path for a directory-based example database.
""",
    validator=_validate_database,
)
```

If so, would such a change be considered for merge if I were to put in a PR?

**Comment by Zac-HD** [comment]
We'd encourage you to [use settings profiles](https://hypothesis.readthedocs.io/en/latest/settings.html#default-settings), where you can set your own default (including from an environment variable).  Most people end up defining profiles like "normal", "fast" (lower max_examples), and "CI" (print_blob and maybe turn up verbosity).

Supporting environment variables as well as profiles would mean dealing with many more combinations of features, and we just don't have the resources to do so 😕
