### ISSUE TITLE
Compatibility with pytest style tests for Django

### ISSUE THREAD

**Issue by alicederyn** [HypothesisWorks/hypothesis#2382]
Hey all,

I hit the known issue that Hypothesis is not compatible with pytest style tests for Django, and out of curiosity looked to see if I could monkey-patch in support. I believe I have done so, in a way that may be mergeable properly into Hypothesis proper? Thought I would share it in case there's interest.

First, I needed a way to add setup/teardown to a function in the same way you can for a class via `setup_example` and `teardown_example`. I did that by checking for an `example_fixture` property. Were I modifying Hypothesis, I'd put that logic in `new_style_executor`, but it isn't currently passed the test function, so I monkey-patched it into the constructor for `StateForActualGivenExecution`:

```python
original_sfage_init = hypothesis.core.StateForActualGivenExecution.__init__

def patched_sfage_init(self, test_runner, search_strategy, test, settings, random, had_seed):
    if callable(test) and hasattr(test, 'example_fixture'):
        original_test_runner = test_runner

        def test_runner_with_fixture(data, function):
            s = test.example_fixture()
            next(s)
            try:
                original_test_runner(data, function)
            finally:
                next(s, None)

        test_runner = test_runner_with_fixture
    return original_sfage_init(
        self, test_runner, search_strategy, test, settings, random, had_seed
    )

hypothesis.core.StateForActualGivenExecution.__init__ = patched_sfage_init
```

Now I just need a pytest hook to install the logic from DjangoTestCase as a fixture when both `django_db` and `hypothesis` marks are found. This works because transactions can be nested; Django uses savepoints to roll back inner transactions. I'm using private methods on DjangoTestCase because it's a monkey-patch but you can achieve the same goal using public methods with a bit more effort:

```python
def django_example_fixture():
    atomics = DjangoTestCase._enter_atomics()
    yield
    DjangoTestCase._rollback_atomics(atomics)

@pytest.hookimpl(hookwrapper=True)
def pytest_pyfunc_call(pyfuncitem):
    django_db_mark = pyfuncitem.get_closest_marker('django_db')
    hypothesis_mark = pyfuncitem.get_closest_marker('hypothesis')
    if django_db_mark and hypothesis_mark:
        # Need to run each hypothesis test in a sub-transaction
        pyfuncitem.obj.hypothesis.inner_test.example_fixture = django_example_fixture
    yield
```

What do people think? Worth trying to turn this into a PR?

**Comment by DRMacIver** [comment]
Oh, neat, thanks. I would have assumed this was impossible without a more general function level fixtures fix. If we can make this work that would definitely be worth doing, and a pull request for that would be gratefully accepted, thank you!

**Comment by Zac-HD** [comment]
Closing this in favor of https://github.com/pytest-dev/pytest-django/issues/912, since I think `pytest-django` is a better place to solve the problem 🙂

**Comment by alicederyn** [comment]
Sorry I never got around to working on this by the way!

**Comment by Zac-HD** [comment]
No worries! There are more important things in life than volunteering to write open source code 😊
