### ISSUE TITLE
Default max_size strategy argument value is ambiguous

### ISSUE THREAD

**Issue by edigaryev** [HypothesisWorks/hypothesis#2386]
If you read through the [latest documentation](https://hypothesis.readthedocs.io/en/latest/index.html) from start without skipping anything, the first `max_size` argument explanation is happens to be in [`hypothesis.strategies.binary(*, min_size=0, max_size=None)`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.binary) strategy documentation.

It says:

>Generates bytes.

>min_size and max_size have the usual interpretations.

`max_size` has a `None` default value, which can be interpreted differently by different people:

* will it generate 0 bytes (to run faster)?
* will it generate some good-enough amount of bytes (to meet the middle ground)?
* will it generate a lot of bytes (to cover lots of different cases)?

It would be nice if this would be made more clear.

**Comment by Zac-HD** [comment]
Thanks for bringing this to our attention!  `max_size=None` means that there is no maximum size, but we should definitely document this clearly the first time it appears (i.e. `binary()`, as you say).

It would also be good to check that `min_value` / `max_value` are explained the first time *they* appear...
