### ISSUE TITLE
AssertionError: assert nan >= 0 hypothesis/internal/conjecture/floats.py in float_to_lex(f)

### ISSUE THREAD

**Issue by bicici** [HypothesisWorks/hypothesis#2389]
AssertionError: assert nan >= 0 hypothesis/internal/conjecture/floats.py in float_to_lex(f)

    203 def float_to_lex(f):
    204     if is_simple(f):
--> 205         assert f >= 0
    206         return int(f)
    207     return base_float_to_lex(f)

from
hypothesis/strategies/_internal/numbers.py in <module>
     80     ]
     81     + [math.inf, math.nan] * 5,
---> 82     key=flt.float_to_lex,
     83 )
     84 NASTY_FLOATS = list(map(float, NASTY_FLOATS))

from
_pytest/assertion/rewrite.py in exec_module(self, module)
    150         else:
    151             state.trace("found cached rewritten pyc for {}".format(fn))
--> 152         exec(co, module.__dict__)
    153 
    154     def _early_rewrite_bailout(self, name, state):

**Comment by bicici** [comment]
209         try:
--> 210             code = pytest.main(pytest_args)
    211         except SystemExit as exc:
    212             code = exc.code

site-packages/_pytest/config/__init__.py in main(args, plugins)
    103     try:
    104         try:
--> 105             config = _prepareconfig(args, plugins)
    106         except ConftestImportFailure as e:
    107             exc_info = ExceptionInfo(e.excinfo)

site-packages/_pytest/config/__init__.py in _prepareconfig(args, plugins)
    256                     pluginmanager.register(plugin)
    257         return pluginmanager.hook.pytest_cmdline_parse(
--> 258             pluginmanager=pluginmanager, args=args
    259         )
    260     except BaseException:

site-packages/pluggy/hooks.py in __call__(self, *args, **kwargs)
    284                     stacklevel=2,
    285                 )
--> 286         return self._hookexec(self, self.get_hookimpls(), kwargs)
    287 
    288     def call_historic(self, result_callback=None, kwargs=None, proc=None):

site-packages/pluggy/manager.py in _hookexec(self, hook, methods, kwargs)
     91         # called from all hookcaller instances.
     92         # enable_tracing will set its own wrapping function at self._inner_hookexec
---> 93         return self._inner_hookexec(hook, methods, kwargs)
     94 
     95     def register(self, plugin, name=None):

site-packages/pluggy/manager.py in <lambda>(hook, methods, kwargs)
     85             methods,
     86             kwargs,
---> 87             firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
     88         )
     89 

site-packages/pluggy/callers.py in _multicall(hook_impls, caller_kwargs, firstresult)
    201         for gen in reversed(teardowns):
    202             try:
--> 203                 gen.send(outcome)
    204                 _raise_wrapfail(gen, "has second yield")
    205             except StopIteration:

site-packages/_pytest/helpconfig.py in pytest_cmdline_parse()
     88 def pytest_cmdline_parse():
     89     outcome = yield
---> 90     config = outcome.get_result()
     91     if config.option.debug:
     92         path = os.path.abspath("pytestdebug.log")

site-packages/pluggy/callers.py in get_result(self)
     78             ex = self._excinfo
     79             if _py3:
---> 80                 raise ex[1].with_traceback(ex[2])
     81             _reraise(*ex)  # noqa
     82 

site-packages/pluggy/callers.py in _multicall(hook_impls, caller_kwargs, firstresult)
    185                         _raise_wrapfail(gen, "did not yield")
    186                 else:
--> 187                     res = hook_impl.function(*args)
    188                     if res is not None:
    189                         results.append(res)

site-packages/_pytest/config/__init__.py in pytest_cmdline_parse(self, pluginmanager, args)
    834     def pytest_cmdline_parse(self, pluginmanager, args):
    835         try:
--> 836             self.parse(args)
    837         except UsageError:
    838 

site-packages/_pytest/config/__init__.py in parse(self, args, addopts)
   1042             kwargs=dict(pluginmanager=self.pluginmanager)
   1043         )
-> 1044         self._preparse(args, addopts=addopts)
   1045         # XXX deprecated hook:
   1046         self.hook.pytest_cmdline_preparse(config=self, args=args)

site-packages/_pytest/config/__init__.py in _preparse(self, args, addopts)
    990             # Don't autoload from setuptools entry point. Only explicitly specified
    991             # plugins are going to be loaded.
--> 992             self.pluginmanager.load_setuptools_entrypoints("pytest11")
    993         self.pluginmanager.consider_env()
    994         self.known_args_namespace = ns = self._parser.parse_known_args(

site-packages/pluggy/manager.py in load_setuptools_entrypoints(self, group, name)
    297                 ):
    298                     continue
--> 299                 plugin = ep.load()
    300                 self.register(plugin, name=ep.name)
    301                 self._plugin_distinfo.append((plugin, DistFacade(dist)))

site-packages/importlib_metadata/__init__.py in load(self)
     93         """
     94         match = self.pattern.match(self.value)
---> 95         module = import_module(match.group('module'))
     96         attrs = filter(None, (match.group('attr') or '').split('.'))
     97         return functools.reduce(getattr, attrs, module)

importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

importlib/_bootstrap.py in _gcd_import(name, package, level)

importlib/_bootstrap.py in _find_and_load(name, import_)

importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

importlib/_bootstrap.py in _gcd_import(name, package, level)

importlib/_bootstrap.py in _find_and_load(name, import_)

importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

importlib/_bootstrap.py in _gcd_import(name, package, level)

importlib/_bootstrap.py in _find_and_load(name, import_)

importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

importlib/_bootstrap.py in _load_unlocked(spec)

site-packages/_pytest/assertion/rewrite.py in exec_module(self, module)
    150         else:
    151             state.trace("found cached rewritten pyc for {}".format(fn))
--> 152         exec(co, module.__dict__)
    153 
    154     def _early_rewrite_bailout(self, name, state):

site-packages/hypothesis/__init__.py in <module>
     24 from hypothesis._settings import HealthCheck, Phase, Verbosity, settings
     25 from hypothesis.control import assume, event, note, reject, target
---> 26 from hypothesis.core import example, find, given, reproduce_failure, seed
     27 from hypothesis.internal.entropy import register_random
     28 from hypothesis.utils.conventions import infer

importlib/_bootstrap.py in _find_and_load(name, import_)

importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

importlib/_bootstrap.py in _load_unlocked(spec)

site-packages/_pytest/assertion/rewrite.py in exec_module(self, module)
    150         else:
    151             state.trace("found cached rewritten pyc for {}".format(fn))
--> 152         exec(co, module.__dict__)
    153 
    154     def _early_rewrite_bailout(self, name, state):

site-packages/hypothesis/core.py in <module>
     33 import attr
     34 
---> 35 import hypothesis.strategies as st
     36 from hypothesis._settings import (
     37     HealthCheck,

importlib/_bootstrap.py in _find_and_load(name, import_)

importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

importlib/_bootstrap.py in _load_unlocked(spec)

site-packages/_pytest/assertion/rewrite.py in exec_module(self, module)
    150         else:
    151             state.trace("found cached rewritten pyc for {}".format(fn))
--> 152         exec(co, module.__dict__)
    153 
    154     def _early_rewrite_bailout(self, name, state):

site-packages/hypothesis/strategies/__init__.py in <module>
     15 
     16 from hypothesis.strategies._internal import SearchStrategy
---> 17 from hypothesis.strategies._internal.core import (
     18     DataObject,
     19     _strategies,

importlib/_bootstrap.py in _find_and_load(name, import_)

importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

importlib/_bootstrap.py in _load_unlocked(spec)

site-packages/_pytest/assertion/rewrite.py in exec_module(self, module)
    150         else:
    151             state.trace("found cached rewritten pyc for {}".format(fn))
--> 152         exec(co, module.__dict__)
    153 
    154     def _early_rewrite_bailout(self, name, state):

site-packages/hypothesis/strategies/_internal/core.py in <module>
    106 from hypothesis.strategies._internal.lazy import LazyStrategy
    107 from hypothesis.strategies._internal.misc import JustStrategy
--> 108 from hypothesis.strategies._internal.numbers import (
    109     BoundedIntStrategy,
    110     FixedBoundedFloatStrategy,

importlib/_bootstrap.py in _find_and_load(name, import_)

importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

importlib/_bootstrap.py in _load_unlocked(spec)

site-packages/_pytest/assertion/rewrite.py in exec_module(self, module)
    150         else:
    151             state.trace("found cached rewritten pyc for {}".format(fn))
--> 152         exec(co, module.__dict__)
    153 
    154     def _early_rewrite_bailout(self, name, state):

site-packages/hypothesis/strategies/_internal/numbers.py in <module>
     80     ]
     81     + [math.inf, math.nan] * 5,
---> 82     key=flt.float_to_lex,
     83 )
     84 NASTY_FLOATS = list(map(float, NASTY_FLOATS))

site-packages/hypothesis/internal/conjecture/floats.py in float_to_lex(f)
    203 def float_to_lex(f):
    204     if is_simple(f):
--> 205         assert f >= 0
    206         return int(f)
    207     return base_float_to_lex(f)

AssertionError: assert nan >= 0

**Comment by bicici** [comment]
to fix, on line 82 of hypothesis/strategies/_internal/numbers.py
    key=flt.base_float_to_lex,  
    #key=flt.float_to_lex,

**Comment by Zac-HD** [comment]
Can you show us the code that caused this exception?

This is an internal interface, and unfortunately we can't comment out the key argument without causing other problems, but if you show us how you triggered it we'll be able to work something out.

**Comment by bicici** [comment]
I tested again later and even "import hypothesis" caused the same problem.

When float_to_lex is called without an argument on line 82, causes the error.

**Comment by Zac-HD** [comment]
Line 82 does not call the function, it passes it as an argument to `sorted`.

Please show us a Python script that causes this error so we can investigate.

**Comment by bicici** [comment]
I already pasted the relevant code snippet. There should be some call in it. The larger context is:
import numpy
numpy.test('fast', verbose=1)

**Comment by bicici** [comment]
Ok, this appears to be related to the local python installation, which passed most of the the tests but experienced this error. I tested on another python instance and "import hypothesis" worked. Thank you.

**Comment by Zac-HD** [comment]
Ah, yep, sounds like there's an installation issues somewhere. Thanks for reporting a possible bug through, and for following up with more information so quickly!
