### ISSUE TITLE
[Question/Discussion] Using strategies in mocks

### ISSUE THREAD

**Issue by davidmascharka** [HypothesisWorks/hypothesis#2391]
I'm interested in using some custom strategies to produce exemplars for mocking and am wondering whether there's a supported way to do that. Currently I'm doing something like:

``` python
class MyClass:
    def __init__(self, stuff: np.ndarray, things: np.ndarray, more_stuff: np.ndarray):
        # ...


@st.composite
def my_class_strat(draw):
    stuff = draw(hnp.arrays(...))
    things = draw(hnp.arrays(...))
    more_stuff = draw(hnp.arrays(...))
    return MyClass(stuff, things, more_stuff)
```

but I also have need for a mock object that can return `MyClass` objects:

``` python
class MockObject:
    def build_my_class(self) -> MyClass:
        # just need to generate a `MyClass`
```

What I'd really like is to be able to use the strategy I've defined to generate an exemplar in `build_my_class` similar to calling `my_class_strat.example()`. Currently I need to duplicate the generation process using NumPy's random module which incurs some maintenance overhead of keeping both paths up to date with changes.

Using `.example()` directly raises a `HypothesisException`, which I understand. My other thoughts were whether it's possible to construct a `DataObject` and pass that into the Mock or initialize it in the Mock's `__init__` and draw from the strategy directly in the `build_my_class` function. Is functionality like this supported somehow? I pinged @rsokl separately and he suggested posting here to keep the conversation around since he's wanted to do something similar in the past.

**Comment by Zac-HD** [comment]
Would [`st.functions(returns=my_class_strat())`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.functions) work?  For example

```python
@given(
    ...,
    factory=st.functions(returns=...),
)
def test_(..., factory):
    mymock = Mock()
    mymock.build_my_class = factory
    ...
```

**Comment by Zac-HD** [comment]
Closing this because I think `functions()` is exactly what you're looking for, and I haven't heard anything else. Happy to continue the conversation though!

**Comment by davidmascharka** [comment]
Hmm ideally I'd like to use this even where I don't have a `given` decorator; for example, if I'm using `MyMock` in a long-running integration test. Would the recommendation there be to still use `@given` and use `@settings(max_examples=1)` or is there some other workaround?

**Comment by Zac-HD** [comment]
Yep, still use `@given`, it's the core of Hypothesis and everything else relies on the underlying engine to work.
