### ISSUE TITLE
strategies.integers doesn't accept empty ranges or float bounds

### ISSUE THREAD

**Issue by jwg4** [HypothesisWorks/hypothesis#2442]
Hi, `integers.strategies` works a little differently from `range` in that it throws an error if either of min_value or max_value are not integers (or None), or if min_value > max_value.

1. This breaks the principle of least surprise, since `range` has well established behavior in these cases.
2. Perhaps more importantly, it makes it much harder to write integer strategies where the bounds are calculated based on some other values. For example, I want x to be no greater than y/2, where y can change:
- `integers (1, y // 2)` fails if y is 1.
- `integers (1, y / 2)` fails if y is odd.

The first case is probably more of a pain than the second case, since using `int()` everywhere fixes the second case. However, it might be nice for these checks to be removed and the general ranges just work. Or perhaps there's a natural situation where one or both of these cases would indicate an error, and therefore these checks are important to keep around?

**Comment by rsokl** [comment]
>integers.strategies works a little differently from range in that it throws an error if either of min_value or max_value are not integers

`range` raises a `TypeError` when it is passed floats..

>or if min_value > max_value

`integers()` does not describe a sequence of integers, which is what `range` is doing. Where it may make sense for `start > stop`, it certainly doesn't make sense for `min_value > max_value`

**Comment by jwg4** [comment]
Why doesn't it make sense for `integers (a, b)` to be the same as `nothing` if a is greater than b?

**Comment by rsokl** [comment]
Because then your test will raise an `UnsatisfiableError` with a vague error message.

**Comment by jwg4** [comment]
It seems that the UnsatisfiableError is exactly the reason this could be
allowed - it's unlikely that, if you do this by mistake, the mistake will
be hidden from you.

My wider point is that, while I can imagine clear reasons that you might
want min_value and max_value of this form to be considered meaningful, I
honestly can't imagine a reasonable situation where you might write them
and rely on the error - apart from a very unlucky typo perhaps?

**Comment by rsokl** [comment]
So are you taking issue with the specific error being raised by `integers()`?

**Comment by jwg4** [comment]
If `integers()` itself doesn't throw an error, you can use it in building a
complex strategy which avoids `UnsatisfiableError`.

**Comment by Zac-HD** [comment]
> It seems that the `UnsatisfiableError` is exactly the reason this could be allowed - it's unlikely that, if you do this by mistake, the mistake will be hidden from you.

Yes, *until* you compose it with anything else - for example `lists(integers(2, 1))` would only ever generate the empty list, `integers(2, 1) | text()` would only ever generate strings, and there are many cases where this kind of thing leads to valid tests which silently do far less than expected.

Better to fail fast and loudly, IMO.
