### ISSUE TITLE
test_array_values_are_unique_high_collision fails on i586

### ISSUE THREAD

**Issue by mcepl** [HypothesisWorks/hypothesis#2447]
While building the official hypothesis packages for openSUSE/Factory with new GCC10, we have constantly failing test on i586:
```
[   15s] + py.test-3.8 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v tests -k 'not test_prints_statistics_given_option_under_xdist'
[   16s] ============================= test session starts ==============================
[   16s] platform linux -- Python 3.8.2, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3
[   16s] cachedir: .pytest_cache
[   16s] hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/tmp/tmp5kapecde/examples')
[   16s] rootdir: /home/abuild/rpmbuild/BUILD/hypothesis-hypothesis-python-5.11.0, inifile: pytest.ini
[   16s] plugins: hypothesis-5.11.0, flaky-3.6.1
...
[ 1318s] _________________ test_array_values_are_unique_high_collision __________________
[ 1318s] Traceback (most recent call last):
[ 1318s]   File "/home/abuild/rpmbuild/BUILD/hypothesis-hypothesis-python-5.11.0/hypothesis-python/tests/numpy/test_gen_data.py", line 365, in test_array_values_are_unique_high_collision
[ 1318s]     nps.arrays(
[ 1318s]   File "/usr/lib/python3.8/site-packages/hypothesis/core.py", line 1102, in wrapped_test
[ 1318s]     raise the_error_hypothesis_found
[ 1318s]   File "/home/abuild/rpmbuild/BUILD/hypothesis-hypothesis-python-5.11.0/hypothesis-python/tests/numpy/test_gen_data.py", line 374, in test_array_values_are_unique_high_collision
[ 1318s]     assert (arr == 0.0).sum() <= 1
[ 1318s] AttributeError: 'bool' object has no attribute 'sum'
[ 1318s] ---------------------------------- Hypothesis ----------------------------------
[ 1318s] Falsifying example: test_array_values_are_unique_high_collision(
[ 1318s]     arr=array([nan]),
[ 1318s] )
[ 1318s] =============================== warnings summary ===============================
```
This is with numpy 1.18.4-68.2 and with new gcc10. Truth to be told, I cannot imagine, how Boolean value could ever have ``.sum()`` method, but that’s probably lack of my imagination.

[Complete build log with all details ](https://github.com/HypothesisWorks/hypothesis/files/4662913/_log.txt)

**Comment by Zac-HD** [comment]
Huh... this is pretty odd.  The problem here is that `np.array([nan]) == 0.0` returned a Python `bool` instead of a Numpy `array` of `dtype=np.bool_`, and obviously that wasn't going to work.  You have have discovered a problem compiling Numpy for `i586`!

The test in question is pretty standard, though we could replace `.sum()` with `.count_nonzero()`:

https://github.com/HypothesisWorks/hypothesis/blob/aa64ed7343de03227ce65e829835eca6df0d6870/hypothesis-python/tests/numpy/test_gen_data.py#L364-L374

**Comment by Zac-HD** [comment]
Closing this as not a Hypothesis issue; for some reason `numpy.array([numpy.nan]) == 0` is returning a `bool` instead of an `array` on your machine :confused:

**Comment by bnavigator** [comment]
> The test in question is pretty standard, though we could replace `.sum()` with `.count_nonzero()`:

 `.count_nonzero()` would require the operator to be turned around and compared to the length of the array. But this works too:
 
```python
assert np.asarray(arr == 0.0).sum() <= 1 
```
