### ISSUE TITLE
load_profile doesnt work when used inside fixture

### ISSUE THREAD

**Issue by jay746** [HypothesisWorks/hypothesis#2452]
I was experiment with features of hypothesis. I came across a problem that if i load_profile inside a fixture of conftest.py and make that fixture as module scoped, ideally it would be called per test and hence i should have a loaded profile configuration, but it doesnt.
import pytest

conftest.py is something like that
```

from hypothesis import settings
settings.register_profile("test", max_examples=30, print_blob=True)
settings.register_profile("test2",  max_examples=60, print_blob=False)
settings.load_profile("test")

@pytest.fixture(scope="module", autouse=True)
def do_something(request):
    settings.load_profile("test2")
```

Here i see that i am getting max_examples=30 when running test instead of 60.

**Comment by jay746** [comment]
@Zac-HD , Can you suggest something on this problem?

**Comment by Zac-HD** [comment]
No suggestions sorry, unless you count "don't do that with fixtures".

I'm unlikely to get to investigate for a while either, working with fixtures is not much fun and it doesn't seem like a common problem.  What's the project this would be useful for?

**Comment by DRMacIver** [comment]
I think the fixture is actually irrelevant here and the problem is more fundamental: Settings on tests inherit the defaults that were active when they were imported. We'd have to rethink a lot about how our settings system works to change that.

**Comment by jay746** [comment]
@Zac-HD,
I have a file let's call A.py which import B.py and inside B.py, I see that we have load_profile done. I am not in position in change configuration of content of A or B.
But I wanted some settings to be modified as per my need.
Hence the idea of conftest.py
But as A sourcing B conftest initial setting won't matter. Hence thought of fixtures.
Let me know if you have something better for this situation.
@DRMacIver , thanks for your feedback. Is there anyway to modify setting just before running a test.

**Comment by Zac-HD** [comment]
@jay746, I'm not interested in providing support for non-open-source projects, nor to a brand-new account with no history - we give away Hypothesis but that does not entitle you to ongoing assistance for free (though I do consult on this kind of thing, if your company wants to pay).

I already told you I don't have any suggestions and it's not a priority for me, and David has told you that tests use the settings which were active at import-time.  Repeated @-mentions are pretty rude, in this context.
