### ISSUE TITLE
@seed decorator appears to give different results depending on whether running locally or on travis

### ISSUE THREAD

**Issue by paddyroddy** [HypothesisWorks/hypothesis#2458]
I have a test like this which I envoke with `pytest -v .`. When I run it locally it passes fine. But when I run it on Travis CI I'm having to iterate to find out what `rtol` passes the test. Other tests that I have which are very similar pass fine so I'm quite confused by this. I assumed that `@seed` would ensure that the results are the same regardless of where I run it. Can you please advise?

```
@pytest.fixture(scope="module")
def lim_lat_lon_decomposition() -> SlepianDecomposition:
    region = Region(theta_min=THETA_0, theta_max=THETA_1, phi_min=PHI_0, phi_max=PHI_1)
    earth = Earth(L, region=region)
    return SlepianDecomposition(earth)

def valid_lim_lat_lon_ranks() -> SearchStrategy[int]:
    """
    must be less than L
    """
    return integers(min_value=0, max_value=L - 1)

@seed(30)
@settings(max_examples=8, deadline=None)
@given(rank=valid_lim_lat_lon_ranks())
def test_decompose_region_and_harmonic_sum_agree_lim_lat_lon(
    lim_lat_lon_decomposition, rank
) -> None:
    """
    tests integrate_region and harmonic_sum are in agreement for a
    limited latitude longitude region
    """
    f_p = lim_lat_lon_decomposition.decompose(rank, method="integrate_region")
    g_p = lim_lat_lon_decomposition.decompose(rank, method="harmonic_sum")
    assert_allclose(f_p, g_p, rtol=20.7)
```

**Comment by Zac-HD** [comment]
- Very hard to work this out without seeing the `valid_lim_lat_lon_ranks()` strategy
- Are you running the same version of all libraries locally and in CI?
- Using the `print_blob=True` setting / `@reproduce_failure` decorator might also help.

**Comment by paddyroddy** [comment]
have added the strategy, yeah I am running the same versions.

Will give `print_blob=True`/`@reproduce_failure` a go thanks

**Comment by Zac-HD** [comment]
I would guess that the problem is somewhere in the library you're testing, and due to a difference in library dependency, Python version, or operating system.  Could be wrong, but Hypothesis *really* isn't doing much here.

Also try turning up the verbosity, so that you can check whether the problem is *Hypothesis providing different examples*, or *the same examples causing different behaviour*.

**Comment by paddyroddy** [comment]
okay yeah I see what you mean. Hypothesis is basically just picking an index from an array and I was just wondering whether the `rank` chosen was different but it's more likely that my code is working slightly differently on Travis for some reason.

Thanks and great library btw!

**Comment by Zac-HD** [comment]
Glad you like it, and best of luck and skill with the debugging!
