### ISSUE TITLE
Zip strategies

### ISSUE THREAD

**Issue by sherpal** [HypothesisWorks/hypothesis#2459]
# Proposal
This is a proposal for adding a method "zip" to strategies, allowing to take the cartesian product of two strategies.

# Implementation
The implementation would be straightforward:
In `hypothesis-python/src/hypothesis/strategies/_internal/strategies.py`, the following would be required (existing lines are ascribed with "existing comment":
```python
[...]
from typing import Any, Callable, Generic, List, *Tuple*, TypeVar  # existing
[...]

class SearchStrategy(Generic[Ex]):  # existing

  [...]

  def zip(self, other: SearchStrategy[T]) -> "SearchStrategy[Tuple[Ex, T]]:
    """
    Given this strategy and another strategy for type T, returns a strategy for type `(Ex, T)`
    """
    return self.flatmap(lambda ex: other.map(lambda t: (ex, t)))
```

(docstring should be filled to be up to your standards)
Tests should be written for that.

## Alternative

An other possibility (which I dislike but is perhaps more "pythonic") si to have a top-level function `zip_strategies` (`zip` begin already existent) implemented like so:

```python
U = TypeVar("U")

def zip_strategies(left: SearchStrategy[T], right: SearchStrategy[U]) -> SearchStrategy[Tuple[T, U]]:
    """
    Given two strategies for generating respectively elements of type T and elements of type U, returns a strategy
    for type (T, U).
    If you think in terms of sets, this returns the cartesian product T x U.
    :param left: first strategy to zip
    :param right: second strategy to zip
    :return: strategy for tuples.
    """
    return left.flatmap(lambda t: right.map(lambda u: (t, u)))

```

# Why?

Since Python has no syntax sugar for monads, it's sometimes a pain to compose deep flatmap operations. Zip is a common operation (at least to me) and it would reduce a lot of boilerplate for the users.

**Comment by Zac-HD** [comment]
Sounds like [the `st.tuples()` strategy](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.tuples)?  e.g.

```pycon
>>> st.tuples(st.integers(), st.text()).example()
(123, "abc")
```

**Comment by sherpal** [comment]
Oooh Yes indeed! Sorry about that then :D

**Comment by Zac-HD** [comment]
No worries!
