### ISSUE TITLE
Misleading output after DeadlineExceeded

### ISSUE THREAD

**Issue by inglesp** [HypothesisWorks/hypothesis#2465]
After raising `DeadlineExceeded`, Hypothesis reports the arguments that are passed to the test function that cause the deadline to be exceeded.

However, it calls this a falsifying example:

```
Falsifying example: test_roundtrip(
    self=<__main__.DemoTests testMethod=test_roundtrip>, n=0,
)
```

which (to me) suggests that the the reported arguments cause my assertions to fail.

This can be reproduced with the following:

```
Falsifying example: test_roundtrip(
    self=<__main__.DemoTests testMethod=test_roundtrip>, n=0,
)
```

**Comment by Zac-HD** [comment]
> \[`Falsifying example:`\] (to me) suggests that the the reported arguments cause my assertions to fail.

Hypothesis doesn't actually distinguish between *failures* and *errors* in the way that `unittest` does - we're more like `pytest` where any exception being raised indicates a failure.

So I think that varying our output based on e.g. the exception type would probably confuse about as many people as it helped, as well as being prone to edge cases for internal reasons where we assume we're printing a particular string.
