### ISSUE TITLE
Generate negative indices from the `slices()` strategy

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2468]
For example, `slices(size=3)` should be able to generate `slice(-3, -1)` as an equivalent form of `slice(0, 2)`.  We should also sometimes draw `step=None` if `step=1` would be allowed.  It would also be nice to support slicing length-zero sequences, i.e. `if size == 0:  return builds(slice, none(), none(), none() | integers().filter(bool))`.

Both would be helpful for downstream users - see e.g. https://github.com/Quansight/ndindex/issues/46.

**Comment by kir0ul** [comment]
Oh damn, was working on that one too :slightly_frowning_face:

**Comment by Zac-HD** [comment]
Sorry @kir0ul :confused:
