### ISSUE TITLE
Example of assumptions in documentation fails.

### ISSUE THREAD

**Issue by ancostas** [HypothesisWorks/hypothesis#2479]
Hi there,

I'm starting to use your library and am a bit frustrated by the lack of diversity I'm seeing in the test data being generated. While investigating, it seems like even examples in the docs are failing?
```python
from hypothesis import assume, given, strategies as st

@given(st.lists(st.integers()))
def test_sum_is_positive(xs):
    assume(len(xs) > 10)
    assume(all(x > 0 for x in xs))
    print(xs)
    assert sum(xs) > 0
```

which yields:
```python-traceback
tests/test_calculator_equivalence.py:59 (test_sum_is_positive)
@given(st.lists(st.integers()))
>   def test_sum_is_positive(xs):
E   hypothesis.errors.FailedHealthCheck: It looks like your strategy is filtering out a lot of data. Health check found 50 filtered examples but only 0 good ones. This will make your tests much slower, and also will probably distort the data generation quite a lot. You should adapt your strategy to filter less. This can also be caused by a low max_leaves parameter in recursive() calls
E   See https://hypothesis.readthedocs.io/en/latest/healthchecks.html for more information about this. If you want to disable just this health check, add HealthCheck.filter_too_much to the suppress_health_check settings for this test.
```

Am I doing something obviously wrong?

**Comment by Zalathar** [comment]
It looks like the docs for `assume` are trying to say “even if you do this questionable thing, Hypothesis will still try hard to give somewhat useful results”, but in a way that isn’t very clear.

In general, Hypothesis works better when strategies are set up to always produce valid data, or to produce data that is mostly valid with a few corner cases to be filtered out. When a large proportion of values need to be filtered, Hypothesis either keeps working (but slower and less effectively), or eventually throws up its hands and gives up.

**Comment by Zalathar** [comment]
In any case, if the docs are telling people to try something that doesn’t actually work right now, then we should make the docs more accurate to reality.

(It’s also possible that there’s some subtle bug making test data less diverse than expected, but that would require more investigation.)

**Comment by Zac-HD** [comment]
I suspect that we actually have a problem here, because the healthcheck fails for much smaller lengths when we assume positive integers.  @DRMacIver, maybe something in the engine changes has made our support for this less effective?
