### ISSUE TITLE
setuptools 49.2.0 will warn if distutils is imported first

### ISSUE THREAD

**Issue by mattip** [HypothesisWorks/hypothesis#2490]
xref pypa/setuptools#2261, numpy/numpy#16851

We are trying to understand why pytest-xdist is failing to run after updating setuptools to 49.2.0. I think one problem might be [this import](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/extra/pytestplugin.py#L16). I think it would be best to `import setuptools` just before that. Although I think setuptools will move quickly to rectify that warning since it is causing much anguish across different projects, so maybe just weather the storm and wait for the next version.

**Comment by Zac-HD** [comment]
Oh... dear.

Even if it's fixed quickly I think the net effect is that I no longer trust *stdlib `distutils`* to be free from packaging-related pain around versioning, so I'm inclined to replace it (with e.g. a regex) entirely :grimacing:
