### ISSUE TITLE
Feature Request: make builds() understand __wrapped__ functions

### ISSUE THREAD

**Issue by pschanely** [HypothesisWorks/hypothesis#2495]
Per [the docs](https://hypothesis.readthedocs.io/en/latest/details.html#inferred-strategies), the hypothesis `builds` function uses python's [`getfullargspec`](https://docs.python.org/3/library/inspect.html#inspect.getfullargspec) to determine parameters. Sadly, this means that some traditional ways of wrapping functions will hide the real parameters.

An example:
```python
from hypothesis import given, infer
from functools import wraps

def logged(f):
    @wraps(f)
    def wrapper(*a, **kw):
        print('I was called')
        return f(*a, **kw)
    return wrapper

class Foo:
    @logged
    def __init__(self, i: int):
	    pass

@given(foo = infer)
def test_foo_test(foo: Foo):
    assert True

test_foo_test()
```

This yields the follow error:
```
TypeError: __init__() missing 1 required positional argument: 'i'
```

I suspect that using inspect's [`signature`](https://docs.python.org/3/library/inspect.html#inspect.signature) function would help here, but that might be a pretty invasive change?

**Comment by Zac-HD** [comment]
IMO this is clearly justified; cases where `signature`'s default `follow_wrapped=True` is counterproductive do exist but are very rare.

#2218 even has "consider replacing uses of `inspect.getfullargspec` with `inspect.signature`" as one of the remaining checklist items - and while I didn't get around to that as part of our more general dropping-python-2 code modernisation, it shouldn't be that big a deal to do so now.

**Comment by Zac-HD** [comment]
Aaaaand, it breaks a lot of subtle things: https://github.com/HypothesisWorks/hypothesis/compare/master...Zac-HD:signature-upgrade

There might be something small and crucial that I missed, but :man_shrugging: I'm leaving it for now.
