### ISSUE TITLE
`tests/quality/test_shrink_quality::test_find_large_union_list` is often failing

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2497]
```python-traceback
__________________________ test_find_large_union_list __________________________
[gw1] linux -- Python 3.6.11 /home/vsts/work/1/s/hypothesis-python/.tox/quality/bin/python
Traceback (most recent call last):
  File "tests/quality/test_shrink_quality.py", line 191, in test_find_large_union_list
    def test_find_large_union_list():
  File "tests/common/utils.py", line 41, in inner
    func(*args, **kwargs)
  File "tests/quality/test_shrink_quality.py", line 203, in test_find_large_union_list
    assert len(result) == 1
AssertionError: assert 5 == 1
 +  where 5 = len([{0, 1, 2, 3}, {-3, -1}, {-2, 4}, {-4}, {5}])
```

I've ended up having to skip it to make unrelated changes pass, and hence this issue.

**Comment by DRMacIver** [comment]
It's weird that this is happening, because I cannot make this test fail locally. I wonder if it's Python version specific?

**Comment by Zac-HD** [comment]
Trawling through some recent CI logs, I can see cases on [Cpython 3.6 on Windows](https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=4006&view=logs&j=43648f57-b6a4-59cd-6d2a-4d6bac961825&t=ba2c1e68-ba88-53eb-cd33-909a1b1084c9) and [3.6 on Linux](https://dev.azure.com/HypothesisWorks/Hypothesis/_build/results?buildId=4019&view=logs&j=fe0cbed7-2adb-5350-73d2-0786743da7e3&t=f562fc5c-c12f-5d69-3ad0-9fda2ed7cdc0), and I'm also seeing it locally under Cpython 3.7 on Windows.  Pretty sure I've seen it once or twice in our 3.8 and 3.9 linux builds too.

**Comment by felixonmars** [comment]
I got this today with Python 3.8.4 on Linux, looks exactly the same.
