### ISSUE TITLE
composite stategies conflict with pylint

### ISSUE THREAD

**Issue by radeklat** [HypothesisWorks/hypothesis#2498]
When creating composite strategies, the `@composite` decorator provides the decorated function with a `draw` function. However, this function is then called without a parameter, which `pylint` detects and reports as:

```text
No value for argument 'draw' in function call (no-value-for-parameter, E1120)
```

This is clearly a false positive but potentially difficult to discover/fix in pylint. I checked their issue tracker and there are similar issue opened for over a year. I tried to fix this error by providing a default value of `None` (which would never be used). But that triggered an error in `hypothesis`:

```text
tests/unit/test_composite_strategy.py:44: in <module>
    def composite_strategy(draw: Optional[Callable[[SearchStrategy], Any]] = None) -> SearchStrategy[str]:
.venv/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py:1771: in composite
    def composite(f: Callable[..., Ex]) -> Callable[..., SearchStrategy[Ex]]:
.venv/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py:185: in cached_strategy
    result = fn(*args, **kwargs)
.venv/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py:1785: in composite
    raise InvalidArgument("A default value for initial argument will never be used")
E   hypothesis.errors.InvalidArgument: A default value for initial argument will never be used
```

## Example

```python
from hypothesis import given
from hypothesis.strategies import composite

@composite
def composite_strategy(draw):
    return draw(sampled_from(["a", "b"]))

@given(composite_strategy())  # this triggers pylint error because value for draw is not provided
def test_composite_strategy(example):
   assert example is not None
```

## Request/Suggestion

Would it be possible to create some kind of default value that `hypothesis` would accept but not trigger the error? For example a singleton importable from the library, that could be then tested with `is` operator. Example:

```python
from hypothesis import given
from hypothesis.strategies import composite, DRAW

@composite
def composite_strategy(draw: Callable[[SearchStrategy], Any] = DRAW) -> SearchStrategy[str]:
    ...

@given(composite_strategy())
def test_composite_strategy(examples):
   ...
```

where `DRAW` could be for example:

```python
def _draw(*agrs, **kwargs):
    raise AssertionError("This function should never be called.")

DRAW = _draw
```

and could be tested with:

```python
if (draw is DRAW):
   ... # This is OK default value
```

## Workaround

I currently disable the errors in all places where composite strategies are used with:

```python
# pylint: disable=no-value-for-parameter; `draw` provided by `@composite`
```

**Comment by DRMacIver** [comment]
> Would it be possible to create some kind of default value that hypothesis would accept but not trigger the error? For example a singleton importable from the library, that could be then tested with is operator. Example:

Unfortunately, it would not, because `composite` accepts functions with arbitrary arguments, and you can't put arguments without defaults after arguments with defaults.

There's basically nothing we can do about this problem - it's a longstanding issue where pylint incorrectly assumes that decorators not change the signature of the function they decorate, and that assumption basically has to be fixed on the pylint side.

**Comment by Zac-HD** [comment]
Hopefully fixable upstream via e.g. https://github.com/PyCQA/astroid/pull/820, but as David says it's not really our problem *and* there's nothing we can do about it here.

**Comment by radeklat** [comment]
I was afraid that's going to be the case. And I would also prefer it to be fixed in `pylint`/`astroid`. I'll stick with disables for now then. Thank you both for replying so quickly :)
