### ISSUE TITLE
unittest.IsolatedAsyncioTestCase support ?

### ISSUE THREAD

**Issue by asmodehn** [HypothesisWorks/hypothesis#2514]
This is related to a few other issues #52, #292, #968, #1257 and maybe more...

I wanted to mention that using python's 3.8 [`unittest.IsolatedAsyncioTestCase`](https://docs.python.org/3/library/unittest.html#unittest.IsolatedAsyncioTestCase) and hypothesis 5.14.0, I get:
```
hypothesis.errors.FailedHealthCheck: Tests run under @given should return None, but test_mycoro_test returned <coroutine object MyTestClass.test_mycoro_test at 0x....> instead.
```
I m not sure how this should be fixed (`unittest` or `hypothesis` side), but I was wondering if there was a known workaround for this.
Also it would be nice if the proper way to run async tests were documented in https://hypothesis.readthedocs.io/en/latest/quickstart.html?#running-tests

I haven't had a look at more recent unittest version just yet.
Thoughts ?

**Comment by Zac-HD** [comment]
I think this is basically a case of #59 - our oldest open issue!

The workaround is, in general, to insert a decorator between your async test and Hypothesis to convert it to a sync test.  This is exactly the purpose of `unittest.IsolatedAsyncioTestCase` of course, but unfortunately they're not currently compatible - `@given(...)` is decorating the method, not the class.

For what it's worth `pytest-asyncio` inserts a shim that handles this for you, using [this shim we provide](https://hypothesis.readthedocs.io/en/latest/details.html#custom-function-execution).  I don't think `unittest` can slip a shim in so easily, but would be delighted if I'm wrong!

**Comment by Zac-HD** [comment]
Note that adding special-case support for this wouldn't necessarily hit the problem we have with async functions in general - if we see `unittest.IsolatedAsyncioTestCase` we *already know*  it has to be `asyncio`, not `trio` or `curio` or any other framework.

**Comment by Zac-HD** [comment]
On further thought, I actually *don't* want to support this automatically, because it would break some important internal interfaces - and some of those are exposed for e.g. fuzzing mode and the aforementioned shims.

What we *can* do, I think, is make the error message explain what you need to do here: instead of using `IsolatedAsyncioTestCase`, you need to insert an async-to-sync decorator between your async test method and the `@given` decorator, or use `pytest-asyncio`.

**Comment by Zac-HD** [comment]
And when digging in to fix it, turns out to be handled by https://github.com/HypothesisWorks/hypothesis/pull/3056 🙂
