### ISSUE TITLE
Tidy up defines_strategy code in core.py

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#2516]
A small clean up ticket for whomever is in the mood (which might be future me). In reviewing #2515 I noticed that the `defines_strategy` code is a little bit of a mess.

I think we should inline all of the following definitions to their use site:

```
defines_strategy = base_defines_strategy(False)
defines_strategy_with_reusable_values = base_defines_strategy(True)
defines_strategy_without_laziness = base_defines_strategy(False, try_non_lazy=True)
```

We should also make `force_reusable_values` a keyword only argument defaulting to `False`.

None of this is public API, so no deprecation is needed for anything, it's just a light tidy up.

**Comment by darkpaw** [comment]
looking at this for pycon-au 2020 sprints
