### ISSUE TITLE
False positive on "Examples routinely exceeded the max allowable size"

### ISSUE THREAD

**Issue by eric-czech** [HypothesisWorks/hypothesis#2518]
I have a composite strategy that looks like this for generating Xarray datasets:

```python
import numpy as np
import xarray as xr
from hypothesis import strategies as st
from hypothesis.extra.numpy import integer_dtypes, floating_dtypes

@st.composite
def sample_dataset(draw):
    n = draw(st.integers(0, 10))
    # Draw a mixture of 1D or 2D arrays with identical length along
    # first axis (second axis may be absent or have size 0)
    n_1d = draw(st.integers(1, 5))
    n_2d = draw(st.integers(0, 5))
    n_cols = draw(st.tuples(*[st.integers(0, 5)] * n_2d))
    shapes = n_1d * [(n,)] + [(n, nc) for nc in n_cols]
    n_arrs = len(shapes)
    dtypes = draw(st.tuples(*[integer_dtypes() | floating_dtypes()]*n_arrs))
    # Split first dimension assignment into two groups and assign second
    # dimension with unique names since variables have differing lengths
    dims = [
        (f'dim-0-{i%2}',) if i < n_1d else (f'dim-0-{i%2}', f'dim-1-{i}')
        for i in range(n_arrs)
    ]
    # Return dataset with at most 10 small arrays (each with <=10 rows, <=5 cols)
    ds = xr.Dataset({
        f'x{i:02d}': (dims[i], np.empty(shapes[i], dtype=dtypes[i]))
        for i in range(n_arrs)
    }, attrs={'n': n})
    return ds
```

The basic idea for this sampling is to produce a variety of tiny 1D or 2D arrays for some later tests, but I am constantly getting this error:

> hypothesis.errors.FailedHealthCheck: Examples routinely exceeded the max allowable size. (20 examples overran while generating 8 valid ones). Generating examples this large will usually lead to bad results. You could try setting max_size parameters on your collections and turning max_leaves down on recursive() calls.

What is this "size" measuring exactly?  I don't understand how to make the examples smaller.  Could this be a bug related to how numpy/xarray are measured or am I misunderstanding something?

Thanks.

**Comment by Zac-HD** [comment]
The underlying 'size' is measured in bytes drawn from our underlying source of randomness... you're almost certainly triggering this based on filling out arrays of values - if you count the distribution of number-of-elements you're generating, there's a lot of it up the very large end.

The simplest advice would be to reduce the number of or size of your arrays.

More complex advice would probably depend on your specific tests, or is related to shrinking rather than generating examples.

**Comment by eric-czech** [comment]
Thanks @Zac-HD, to your points:

> The underlying 'size' is measured in bytes drawn from our underlying source of randomness

Good to know.  Looking at that code then, it should only be drawing at most 8 integers and 10 numpy data types per example.  If I remove the data type draws and assign a single data type, this warning goes away.  Given that I'm not even using hypothesis to draw the elements of the arrays, just that small number of ints and dtypes, how could that end up resulting in so many underlying bytes being drawn?  Maybe the bug is related to how dtypes are generated?

> you're almost certainly triggering this based on filling out arrays of values

By arrays, do you mean numpy arrays?  The line `np.empty(shapes[i], dtype=dtypes[i])` wouldn't use hypothesis at all to fill the array elements and if you mean the tuples I'm generating, is 10 elements somehow a lot?

> The simplest advice would be to reduce the number of or size of your arrays.

I'm not sure how to meaningfully reduce the number of things being drawn in this case -- it seems like there's something else going on with this one.

**Comment by DRMacIver** [comment]
Are you sure this strategy is the culprit? I just tried running it with a trivial `@given` that just accepts it as the argument, and this never seems to fail the health check. Could you post a full reproducible example?

**Comment by eric-czech** [comment]
I'm certain, here's a full test:

```python
import numpy as np
import xarray as xr
from hypothesis import strategies as st, given, settings
from hypothesis.extra.numpy import integer_dtypes, floating_dtypes


@st.composite
def sample_dataset(draw):
    n = draw(st.integers(0, 10))
    # Draw a mixture of 1D or 2D arrays with identical length along
    # first axis (second axis may be absent or have size 0)
    n_1d = draw(st.integers(1, 5))
    n_2d = draw(st.integers(0, 5))
    n_cols = draw(st.tuples(*[st.integers(0, 5)] * n_2d))
    shapes = n_1d * [(n,)] + [(n, nc) for nc in n_cols]
    n_arrs = len(shapes)
    dtypes = draw(st.tuples(*[integer_dtypes() | floating_dtypes()]*n_arrs))
    # Split first dimension assignment into two groups and assign second
    # dimension with unique names since variables have differing lengths
    dims = [
        (f'dim-0-{i%2}',) if i < n_1d else (f'dim-0-{i%2}', f'dim-1-{i}')
        for i in range(n_arrs)
    ]
    # Return dataset with at most 10 small arrays (each with <=10 rows, <=5 cols)
    ds = xr.Dataset({
        f'x{i:02d}': (dims[i], np.empty(shapes[i], dtype=dtypes[i]))
        for i in range(n_arrs)
    }, attrs={'n': n})
    return ds


@given(sample_dataset())
@settings(max_examples=25)
def test_fn_1(ds):
    print(ds)
```

And execution:

```bash
cat sgkit/tests/test_example.py > /tmp/issue.txt
pytest -v --cov=sgkit --cov-report=term-missing --ignore=validation -k test_example >> /tmp/issue.txt 2>&1
```

[issue.txt](https://github.com/HypothesisWorks/hypothesis/files/4987309/issue.txt)


It doesn't happen 100% of the time on that example for me but it does happen the large majority of the time.  I'd give you a seed to reproduce but for some reason that isn't working.  I've tried the seed as a pytest argument or as an annotation on the test function but neither makes the health check failure reproducible.

-----

Environment:

```bash
> conda list | grep -E 'pytest|hypothesis|python'
hypothesis                5.21.0                     py_0    conda-forge
pytest                    5.4.3            py37hc8dfbb8_0    conda-forge
python                    3.7.6           cpython_h8356626_6    conda-forge
```

**Comment by Zac-HD** [comment]
I was able to trigger the healthcheck once in ~50 runs, though like you the seed didn't manage to reproduce it.

If the actual performance you're seeing is acceptable, the best solution is probably just to use the `suppress_health_check=[HealthCheck.too_large]` setting - this is pretty close to standard for array-oriented code - and/or use smaller or fewer arrays.

**Comment by andreas-vester** [comment]
Just in case somebody stumbles upon this one:
``HealthCheck.too_large`` has been renamed to ``HealthCheck.data_too_large``.

You can now suppress this via ``@settings(suppress_health_check=[HealthCheck.data_too_large])``
