### ISSUE TITLE
Difference between types with type arguments and without them

### ISSUE THREAD

**Issue by sobolevn** [HypothesisWorks/hypothesis#2537]
I have this code:

```python
def associativity_law(
    mappable: MappableN[_FirstType, _SecondType, _ThirdType],
    first: Callable[[_FirstType], _NewType1],
    second: Callable[[_NewType1], _NewType2],
) -> None:
    assert mappable.map(first).map(second) == mappable.map(
        compose(first, second),
    )
```

Then, I use this code to generate values based on this annotation:

```python
@given(st.data())
def test_assoc(data: st.DataObject):
    st.register_type_strategy(
        MappableN[_FirstType, _SecondType, _ThirdType],  # just `MappableN` does not work
        st.one_of(
            st.builds(Result.from_value),
            st.builds(Result.from_failure),
        ),
    )
    x = data.draw(st.builds(associativity_law))
    assert x is None
```

So, the thing is that just `MappableN` does not work when trying to use it as a type in `st.register_type_strategy`. Output for the broken case:

```
E           hypothesis.errors.ResolutionFailed: Could not resolve returns.interfaces.mappable.MappableN[~_FirstType, ~_SecondType, ~_ThirdType] to a strategy; consider using register_type_strategy

.venv/lib/python3.8/site-packages/hypothesis/strategies/_internal/types.py:229: ResolutionFailed
```

I guess, that using `MappableN[_FirstType, _SecondType, _ThirdType]` to register a type is incorrect, because types should be used like this.

**Comment by sobolevn** [comment]
So, my fix for this problem (very straight-forward):

```python
origin_handler = _global_type_lookup.get(origin)
    if origin_handler:
        return origin_handler if isinstance(origin_handler, st.SearchStrategy) else origin_handler(thing)
```

I have patched the code here: https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/strategies/_internal/types.py#L183

Does this look like something in the right direction?

**Comment by Zac-HD** [comment]
Yeah, I think that would work - we'll just need some user-defined generic types to test with.

It's still possible that I'll look at the results and decide that this is the wrong approach, but I think it's unlikely if this does solve your problem without breaking anything else.

**Comment by sobolevn** [comment]
I will send a PR shorly.

**Comment by sobolevn** [comment]
This is only the case for `python3.7+`. `python3.6` handles this correctly.
