### ISSUE TITLE
Indicate when a failing example comes from an @example

### ISSUE THREAD

**Issue by asmeurer** [HypothesisWorks/hypothesis#2553]
It would be helpful if hypothesis indicated it in the error message when a failing example case comes from an @example decorator.

**Comment by Zac-HD** [comment]
The relevant code will be https://github.com/HypothesisWorks/hypothesis/blob/1bb062f7e0d6ccb6381487cbdd481e1825bf5562/hypothesis-python/src/hypothesis/core.py#L363

Once you've changed this to read e.g. `"Failing example from @example decorator:"`, run the tests - if any fail, update them and you're good to go.  If the all pass, we'll need to write a new test which fails before and passes after this change (and I'll help work out where).

**Comment by asmeurer** [comment]
It would also be nice if it included the line number, but maybe that's not easy to figure out.

**Comment by Zac-HD** [comment]
> It would also be nice if it included the line number, but maybe that's not easy to figure out.

We'd have to start inspecting the call stack, which is kinda ugly and doesn't work at all for people who are using a wrapper to load examples from a file or similar :confused: Sorry!
