### ISSUE TITLE
target() doesn't work with int input

### ISSUE THREAD

**Issue by asmeurer** [HypothesisWorks/hypothesis#2562]
If you call `target()` with an `int` input, you get an error like `hypothesis.errors.InvalidArgument: Expected float but got observation=1 (type=int)`. It's rather unpythonic for a function that takes float inputs to not also work with ints.

**Comment by Zac-HD** [comment]
I'd be happy to take integer input, so long as `x == float(x)`.  Some risk of late-occuring errors if the integer can grow very large, but the usability wins probably make up for that.

**Comment by theakaterina** [comment]
I'm looking at this (as part of the PyCon sprints!)
