### ISSUE TITLE
`_global_type_lookup` has invalid type

### ISSUE THREAD

**Issue by sobolevn** [HypothesisWorks/hypothesis#2563]
I have this perfectly working code:

```python
from typing import Callable
from hypothesis.strategies._internal import types

print(types._global_type_lookup[Callable])
# outputs: <function resolve_Callable at 0x1107674c0>
```

But, `mypy` is not happy:

```
returns/contrib/hypothesis/laws.py:51: error: Invalid index type "_SpecialForm" for "Dict[type, Any]"; expected type "type" 
```

The same is applied to `st.register_type_strategy(Callable, factory)`
Outputs: `error: Argument 1 to "register_type_strategy" has incompatible type "_SpecialForm"; expected "Type[Any]"`

Looks like a typing bug to me.

**Comment by Zac-HD** [comment]
I guess `mypy` has special handling for builtin generics; but since we don't actually provide type annotations for our internals - or support direct downstream use like this! - I'm closing this as wontfix.  Hopefully a `# type: ignore` comment is a good enough workaround :confused:
