### ISSUE TITLE
Problems with hypothesis entrypoints

### ISSUE THREAD

**Issue by sobolevn** [HypothesisWorks/hypothesis#2564]
Currently I am testing out this new cool `entrypoints` feature. #2556 
And it does not work correctly for me.
I specify an entrypoint and nothing happens. The entrypoint function is not getting called.

I am following this example: https://github.com/HypothesisWorks/hypothesis/commit/4ca04cf85b1389f0233dc652a5a74f15d2922c05#diff-94fd9cebb412c332ed91ff584ee7c2f3R129-R155

The problem is best shown by this piece of code:

```python
# module.py

print('Module imported!')

def _hypothesis_setup_hook():
    print('func called')
```

Then I add it to the `setup.py` the same way it is shown in the docs.
Now, let's try to call `run()` function:

```python
>>> for entry_point in pkg_resources.iter_entry_points("hypothesis"):
...     print(entry_point)
...     entry_point.load()
```

Output:

```
_ = mymodule:_hypothesis_setup_hook
Module imported!
<function _hypothesis_setup_hook at 0x100f20ca0>
```

When I change this code to actually execute a function, it works:

```python
>>> for entry_point in pkg_resources.iter_entry_points("hypothesis"):
...     entry_point.load()()  # calling it now
```

Outputs:

```
Module imported!
func called
```

**Comment by Zac-HD** [comment]
Whoops.  I'll want to keep it working for modules, but add `if callable(hook): hook()` to handle the function case.
