### ISSUE TITLE
`st.builds()` generates only text for all `TypeVar`s

### ISSUE THREAD

**Issue by sobolevn** [HypothesisWorks/hypothesis#2572]
I rely on `.builds()` to generate test cases for my *very* annotated function. And I know that there's a bug in it.

Here's the source code: https://github.com/dry-python/returns/pull/543/files#diff-e06c48cc820df2c8762959046a397024R45-R55
Here's the bug context: https://github.com/dry-python/returns/pull/510
TLDR: I need at least one `None` with `Maybe` to catch this bug.

The sad thing is that `hypothesis` is unable to find this bug.
Let's see the simplest reproduction:

```python
from hypothesis import strategies as st, event, given, settings
from typing import Generic, TypeVar, Callable

T = TypeVar('T')
V = TypeVar('V')
U = TypeVar('U')

class MyGeneric(Generic[T]):
    def __init__(self, arg: T) -> T:
        self.arg = arg

def law(
    container: MyGeneric[T],
    first: Callable[[T], V],
    second: Callable[[V], U],
) -> None:
    f = first(...)
    s = second(...)
    assert f is not None  # I hope that at least one assert will fail!
    assert s is not None
    event('Generated first: {0} and second: {1}'.format(f, s))


@given(st.data())
@settings(max_examples=1000)
def test_draw_law(data):
    def factory(thing):
        like = (lambda: None) if len(
            thing.__args__,
        ) == 1 else (lambda *args, **kwargs: None)

        return st.functions(
            like=like,
            returns=st.from_type(thing.__args__[-1]),
            pure=True,
        )

    st.register_type_strategy(Callable, factory)
    st.register_type_strategy(MyGeneric, st.builds(MyGeneric))

    # I hope that his will fail!
    data.draw(st.builds(law))

# But, the test passes :(
```

Here's the full list of things that were generated: https://gist.github.com/sobolevn/593a10232550777fc222def248f647df
There are mostly text entries with just some ints. No `None`, no lists, etc.

Looks like this line is in charge: https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/strategies/_internal/types.py#L228

I think that we can improve it! 
Is there any specific reason why it is `st.text()`?

Related https://github.com/dry-python/returns/pull/543

**Comment by sobolevn** [comment]
One more thing: I cannot even fix this with a custom strategy: `st.register_type_strategy(TypeVar, st.just(1))` does not work.

**Comment by Zac-HD** [comment]
We can definitely improve this - `st.text()` is an arbitrary choice.  To avoid very slow tests we probably want to stick to builtin non-collection types, but that's easy enough: replace

```python
if getattr(thing, "__constraints__", None):
    return st.shared(
        st.sampled_from(thing.__constraints__), key="typevar=%r" % (thing,)
    ).flatmap(st.from_type)
# Constraints may be None or () on various Python versions.
return st.text()  # An arbitrary type for the typevar
```

with 

```python
# Sample from the constraints types if not None or (); or for unconstrained
# typevars limit ourselves to builtin scalars because generating many collections
# can cause substantial slowdowns.
builtin_scalar_types = [NoneType, bool, int, float, str, bytes]
type_strat = st.sampled_from(thing.__constraints__ or builtin_scalar_types)
return st.shared(type_strat, key="typevar=%r" % (thing,)).flatmap(st.from_type)
```

Plus `RELEASE.rst`, tests, you know the drill by now :wink:

**Comment by sobolevn** [comment]
> To avoid very slow tests we probably want to stick to builtin non-collection types, but that's easy enough

I understand the reasoning, but I would love to see at least one mutable type there. Because that's where bugs happen!

> One more thing. I cannot even fix this with a custom strategy

@Zac-HD do you think that this is an issue too? It looks like one to me, but maybe there's something behind this decision I don't know.

Would work on it later today 👍

**Comment by Zac-HD** [comment]
> I understand the reasoning, but I would love to see at least one mutable type there. Because that's where bugs happen!

Makes sense - I think adding List and Dict would be OK with max_size=2.

> do you think that [not being able to fix it by registering a strategy] is an issue too? It looks like one to me, but maybe there's something behind this decision I don't know.

I think the rationale would have been if registering didn't work on some older version(s) of Python; and there's a good chance that we no longer need to worry about this.  If converting `TypeVar` handling from an if-clause to a registered generic type works, let's do it :+1:
