### ISSUE TITLE
`.from_type` / `.builds` and coroutines

### ISSUE THREAD

**Issue by sobolevn** [HypothesisWorks/hypothesis#2576]
I have a defined test, that looks like this:

```python
def identity_law(container: SomeCustomType) -> None:
    assert container == container
```

Then, I used `st.builds(identity_law)` to run this test multiple time with hypothesis-generated data.

Currently I have this task: I need to generate the same thing, but from an async function. Here's how it looks like:

```python
async def idempotence_law(container: SomeCustomType) -> None:
    assert await container == await container
```

But, it does seem to me that I don't have any possibility to do that.
So, should `.builds()` support coroutines and coroutine functions? 
Is it even possible?

Original issue: https://github.com/dry-python/returns/issues/571
Also related (anyio integration is broken): https://github.com/agronholm/anyio/issues/154

**Comment by Zac-HD** [comment]
It *does* suport them in the sense that `builds(some_async_function, *args)` will return awaitable objects for you.

It does not, and IMO should not, automatically await things for you - too many ways for that to go wrong or subtly break things, and you can `.map(run_in_loop)` or whatever for yourself / in the helper function.

**Comment by sobolevn** [comment]
Thanks! I agree with " IMO should not, automatically await things for you"

> you can .map(run_in_loop)

Should we put this in the docs? 🙂 
AFAIK, there's no such section right now.

**Comment by Zac-HD** [comment]
> Should we put this in the docs?

I think the details probably vary enough by framework that we're better off keeping it general, and the "use `.map` to transform a generated value" trick is already covered.
