### ISSUE TITLE
PyCon Australia Sprints meta-issue

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2588]
If you're reading this issue, chances are that you're interested because of the PyConline AU sprints!  Thanks for considering a contribution to Hypothesis :heart_eyes: 

## General links

- [helpful tips for first-time sprinters](https://treyhunner.com/2019/04/making-the-most-of-the-pycon-sprints/)
- user docs: https://hypothesis.readthedocs.io/en/latest/
- tutorial: https://github.com/Zac-HD/escape-from-automanual-testing
- contributor docs: [CONTRIBUTING.rst](https://github.com/HypothesisWorks/hypothesis/blob/master/CONTRIBUTING.rst) and [guides/](https://github.com/HypothesisWorks/hypothesis/tree/master/guides)
- papers: [please cite this one](https://joss.theoj.org/papers/10.21105/joss.01891), [testing scientific code (pdf)](http://conference.scipy.org/proceedings/scipy2020/pdfs/zac_hatfield-dodds.pdf), [generating minimal counterexamples (pdf)](https://drmaciver.github.io/papers/reduction-via-generation-preview.pdf)

And please feel free to chat below or in the event Discord channel.

## Possible sprint issues

Beginners: ~~#2479, #2581, #2562, #2516, move list of authors in `CONTRIBUTING.rst` to new file `AUTHORS.rst`~~

Medium-sized issues: ~~#2585, #2553,~~ #2552

Django-related: #1116, #2382

**Comment by pr4deepr** [comment]
I can have a look at  [#2479](https://github.com/HypothesisWorks/hypothesis/issues/2479)?

**Comment by Zac-HD** [comment]
Go for it!

**Comment by Zac-HD** [comment]
Thanks so much to everyone who joined us today! I know I had a lot of fun, plus more open PRs than we've had for quite a while, and hole you did too. Until next time!
