### ISSUE TITLE
`hypothesis --version` does not work

### ISSUE THREAD

**Issue by sobolevn** [HypothesisWorks/hypothesis#2604]
When I use `pip install hypothesis` in a clear env and run `hypothesis --version`, this happens:

```python
» hypothesis --version
Traceback (most recent call last):
  File "/Users/sobolev/Documents/github/returns/.venv/bin/hypothesis", line 6, in <module>
    from hypothesis.extra.cli import main
  File "/Users/sobolev/Documents/github/returns/.venv/lib/python3.7/site-packages/hypothesis/extra/cli.py", line 35, in <module>
    from hypothesis.extra import ghostwriter
  File "/Users/sobolev/Documents/github/returns/.venv/lib/python3.7/site-packages/hypothesis/extra/ghostwriter.py", line 57, in <module>
    import black
ModuleNotFoundError: No module named 'black'
```

Looks like `black` is treated as a required dependency right now.

After installing `black`:

```
» hypothesis --version
hypothesis, version 5.33.0
```

**Comment by Julian-O** [comment]
Looking at `setup.py`, it looks like if you want to call the command line, you should install the `[cli]` extra, which installs black and click. See [more here](https://hypothesis.readthedocs.io/en/latest/extras.html?highlight=cli#hypothesis-cli)

**Comment by sobolevn** [comment]
@Julian-O yes. But, `click` is handled differently: https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/extra/cli.py#L41

**Comment by Julian-O** [comment]
Interesting. Would it be appropriate to catch an import error where you do now import black, with a similar warning?
