### ISSUE TITLE
Floats with min_value and nan

### ISSUE THREAD

**Issue by KraxelHuber** [HypothesisWorks/hypothesis#2608]
`hypothesis.strategies.floats(min_value=0, allow_nan=True, allow_infinity=False)` gives me an error: `Cannot have allow_nan=True, with min_value or max_value`.

Why is that?
What is best practice in order to produce positive `floats` with `nan` allowed?

**Comment by Zac-HD** [comment]
It's because we maintain the invariant that all generated floats will be >= min_value, and nan would not be.

You can use `floats(min_value=0) | just(nan)` to say "either positive floats, or nan".

**Comment by KraxelHuber** [comment]
Your suggestion is working. :-)

However, in my opinion, this is not as intuitive as it should be. If I set `allow_nan=True`, then I expect `nan` to be included no matter what `min_value`.

Thanks anyway :-)

**Comment by Zac-HD** [comment]
I'm glad it's working for you 😊
