### ISSUE TITLE
Rewrite the Stateful Testing documentation

### ISSUE THREAD

**Issue by Julian-O** [HypothesisWorks/hypothesis#2616]
Background: I am a beginner to Hypothesis. I attended the PyConAu 2020 sprint. I tried reading the `Stateful Testing` page in the documentation and found it very hard going. I am trying to give back to OSS, so I thought I would tackle this problem by learning about the feature, working out what was confusing me, and rewriting it based on that experience to be simpler for newbie eyes like mine.

My goals include 

* separating the concept of bundles and that `@rule` is like `@given` except its calling different functions not just different parameters. I think bundles are currently introduced too early, giving too many concepts at once.

* playing down the state machine aspect, because I constantly got confused about whether it for code-under-test that was a state machine, for code-under-test that was supposed to call a state machine, or that the test code itself was a state machine (even though no states are defined - just transitions).

I have not finished my first rewrite. I expect to get a bit of feedback when I do - there is a risk I haven't followed the project standards or that I have misunderstood some details of the feature. 

Right now, though, I want to avoid burrowing off on my own, coming up with a massive change, and then being told I had wasted everyone's time. So this is not a PR, but more of a check-in to see if the maintainers were happy with me to proceed in this direction.

Attached is some progress. I am not looking for detailed feedback. (Even I can see that there is a section of code that is marked up wrongly.) I am looking for high level feedback:  is there a good chance that when this is finished it will be folded in? am I on a wild goose chase? is this entire feature being rewritten anyway so I am wasting my time?

[stateful.zip](https://github.com/HypothesisWorks/hypothesis/files/5204544/stateful.zip)

**Comment by Zac-HD** [comment]
If you could show us a proposed outline, and explain why you've chosen that structure, I think we'd be able to give more useful feedback.

Once you're at the point of getting formatting and copyediting right, just open a PR and we can let readthedocs render it for us.

**Comment by Julian-O** [comment]
[Let me start by ensuring this isn't seen as an attack on the existing documentation. I think Hypothesis has a very high standard of documentation overall. This particular page appears thorough and accurate. I just want to rearrange it slow down the rate of new concepts being introduced.]

The current structure
---------------------

- Briefly sell the benefits, mention basic feature.
- Warn the terminology is confusing.
	- Why it is called what it is.
	- That it is misleading.
	- That you don't need to use [complex concept].
	- Reassure.
	- Yes, it is powerful.
- Warn people off.
- Introduce RulesBasedStateMachine
	- Includes docstring which talks about Bundles.
- Introduce	Bundles.
- Introduce Rules.
- Example of testing an (off-screen) database, using rules and bundles
	- Re-introduces* concept the Example database, but now as code to be tested. [* Assuming the reader has seen this before.]
	- Introduces (weird!) rules that just populate bundles.
	- Introduces duplicating functionality in the test case for comparison.
	- Introduces using multiple bundles
- Integration with UnitTest.
- Shows how failures are printed as ready-to-run code.
- Shows how to adjust settings.
- Explore Rules, and their restrictions. Include docstrings.
- Introduce consumes, and multiple.
- Introduce Initialize
	- Give example
- Introduce Preconditions
	- Give example
- Introduce Invariants
	- Give example
	- Warn about limits
- Introduce run_state_machine_as_test, but warn against it, and explain it isn't required,
	
The proposed structure
---------------------

- Explain when you should want to use stateful testing.
- Mention basic features.
- Television Example - introduce some code to test.
- Introduce RulesBasedStateMachine by name, but not the docstring.
- Warn that terminology is confusing.
	- That it is misleading.
	- That you don't need to use [complex concept.]
	- Reassure.
	- Why it is called what it is.
	- Yes, it is powerful, when you need it.
	- You might not need it.
- Introduce Rules.
- Example code to test Television example.
	- No rules that just populate bundles.
	- No duplicating functionality.
	- No concept of bundles at all.
	- Does have invariants.
- Introduce invariants.
- Integration with UnitTest.
- Shows how failures are printed as ready-to-run code.
- Shows how to adjust settings.
- [TODO] Consider reinforcing benefits of stateful testing here, now that they see how easy it can be.
- Explain rules can have parameters (strategies), analogous to @given.
- Introduce Bundles as a specific strategy.
- Introduce targets, multiple and consumes as part of Bundles explanation
- [TODO] Explain restrictions of Rules and Bundles interacting
- UserDatabase - introduce some code to test.
- Explain how we need to use Bundles, consume, targets and multiple.
- Show example testing code.
- Introduce preconditions.	
- Another example problem here.
	- I want an example that has very clear need for preconditions 
	- Ideally something recognisable as a classic state machine, so they can go "Ahh! That's why it is called that."
	- Perhaps a state diagram for clarity.
	- Still drawing a blank on what the example should be.
- Demonstrate preconditions (and compare to assume)
- Demonstrate multiple bundles.
- Demonstrate initialise and tearDown.

Other notes:

- I plan to exclude mention of `run_state_machine_as_test`.

- Where do I include the signatures of the various classes and functions 
  - I want them *after* the concepts mentioned in the doc-strings are covered. 
	  - Will consider copy-editing doc-strings to make this work.
  - Are they all even necessary? Hover-text may suffice.

**Comment by Julian-O** [comment]
> Once you're at the point of getting formatting and copyediting right, just open a PR and we can let readthedocs render it for us.

Absolutely. I didn't do that initially to avoid people thinking it was ready for merging and/or getting bogged down in detailed comments. It is still early draft.

**Comment by Julian-O** [comment]
Idea for an example: Tic-Tac-Toe (Noughts and Crosses) AI that can play a perfect game, to replace the television remote control.

- 9 rules, representing where the human player's places their cross next.
- Preconditions to prevent moving in a position that already has a nought or cross, or moving after the computer wins.
- Invariant: That the player has NOT won. If the player won, it is a bug.
- Good demonstration of stateful_step_count - there is never a need to test more than 5 player moves.

**Comment by Zac-HD** [comment]
Hey @Julian-O - I think the best way forward for this might be for you to write up some examples or walkthroughs as blog posts, which will be useful as standalone documents, and then we can look at how to integrate parts into our docs after that :slightly_smiling_face:
