### ISSUE TITLE
array_shape generating repeated data with huge max_side value

### ISSUE THREAD

**Issue by jay746** [HypothesisWorks/hypothesis#2617]
Before question, i really appreciate hypothesis. It's awesome.
My query on array_shape. I was experimenting with big values, I see that after max_value=10M, higher percentage of repeated data with output (1,1,1,1) coming.

Hypothesis Version: 5.34.1
code for reproduction:
`@settings(max_examples=10)
@given(shape=array_shapes(min_dims=4, max_dims=4, max_side=10))
def test_num(shape):
    print("Result Shape: ", shape)`

For same result using command:  pytest --hypothesis-seed 123

output:
max_side=10
Result Shape:  (1, 1, 1, 1)
Result Shape:  (5, 1, 1, 1)
Result Shape:  (5, 7, 5, 9)
Result Shape:  (5, 2, 1, 1)
Result Shape:  (5, 2, 7, 7)
Result Shape:  (1, 1, 1, 1)
Result Shape:  (7, 1, 1, 1)
Result Shape:  (7, 10, 6, 8)
Result Shape:  (1, 3, 1, 1)
Result Shape:  (1, 3, 3, 7)

max_side=10M
Result Shape:  (1, 1, 1, 1)
Result Shape:  (878516, 1, 1, 1)
Result Shape:  (878516, 4490878, 1462750, 6832384)
Result Shape:  (4472031, 1, 1, 1)
Result Shape:  (4472031, 1806911, 640113, 6360651)
Result Shape:  (8995978, 1, 1, 1)
Result Shape:  (8995978, 9434143, 5573353, 5717646)
Result Shape:  (1, 1, 1, 1)
Result Shape:  (2678691, 1, 1, 1)
Result Shape:  (2678691, 2265889, 5657557, 9411381)

max_side=20M
_Result Shape:  (1, 1, 1, 1)
Result Shape:  (1, 1, 1, 1)_
Result Shape:  (17469, 17492106, 3402, 9642029)
_Result Shape:  (1, 1, 1, 1)_
Result Shape:  (45986, 232, 97, 188)
_Result Shape:  (1, 1, 1, 1)_
Result Shape:  (59337, 9318, 4335096, 11763974)
_Result Shape:  (1, 1, 1, 1)_
Result Shape:  (31256, 10, 53823, 37016)
_Result Shape:  (1, 1, 1, 1)_

**Comment by Zac-HD** [comment]
This is a kinda weird outcome, but down to some of the heuristics we use to generate diverse (i.e. bug-finding) inputs without totally blowing out runtime.  I hope that helps - it wasn't so much a question as an observation.

**Comment by jay746** [comment]
After ~11 examples i see quite good randomized output, but as you mentioned this is due to heuristics used. Thanks for answer.
