### ISSUE TITLE
`hypothesis.seed()` docs should state it is a decorator and show usage examples

### ISSUE THREAD

**Issue by edrdo** [HypothesisWorks/hypothesis#2618]
When the derandomize option is set to True in state machines, hypothesis derives a fixed seed for the RNG based on some kind of signature of the test class (as I understood).

For some experiments I wish to obtain deterministic results (given that derandomize=True) but also be able to specify the seed. Browisng through the  code in the repository, it seems there is a **_hypothesis_internal_use_seed** setting associated to the test class (?) that could suit that purpose. At least the following fragment gives that impression: https://github.com/HypothesisWorks/hypothesis/blob/f26b6e088a4cea3bd83e69dc60244c5580df368d/hypothesis-python/src/hypothesis/stateful.py#L192 

How can I "plug" in  **_hypothesis_internal_use_seed**. I could not find any examples. Any help would be appreciated

**Comment by Zac-HD** [comment]
https://hypothesis.readthedocs.io/en/latest/reproducing.html#reproducing-a-test-run-with-seed

**Comment by edrdo** [comment]
`hypothesis.seed()` does not have any effect on rule-based state machine testing when `derandomize=True`. Note that I do not want to reproduce a test run, I want to run the same tests deterministically but several times with different seeds.

As mentioned [in the documentation](https://hypothesis.readthedocs.io/en/latest/settings.html#available-settings) for `derandomize` we have that _"If True, seed Hypothesis’ random number generator using a hash of the test function, so that every run will test the same set of examples until you update Hypothesis, Python, or the test function."._ 

I don't know if `_hypothesis_internal_use_seed` is the way to go, but if it is how do I "glue" it? If not, what's the alternative?

**Comment by Zac-HD** [comment]
Derandomize is an alternative to forcing a particular seed - I think in your case the best option is to stick with derandomize, and just increase the max_examples setting. Running for longer is equivalent to running with multiple seeds!

**Comment by edrdo** [comment]
Yes, of course! I understand that increasing max_examples suits the standard use-case.

For my (research) work however, I want to have a fixed value for max_examples and run the same tests with N different seeds (e.g. to compute the average number of bugs detected for a fixed number of examples) and I need to control/know what these seeds are for reproducing tests results later.

Given that it does seem to be possible to set the seed when `derandomize=True` 
I tried using `derandomize=False` together with `hypothesis.seed()` but again it does not seem to have any effect: tests run non-deterministically and I get different results each time.  I have tried just that using  [this variation of the standard DatabaseComparison example](https://gist.github.com/edrdo/2e7ecc1a8af6f67b1255b8314803398d) (with a deliberate bug inserted). 

The hypothesis version installed is 5.3.1.2 and I run the tests using pytest 5.4.3.

**Comment by edrdo** [comment]
**Update**: given that `hypothesis.seed()` seems to be useless regardless of the  value of the `derandomize`setting, I ended up figuring out how to use ` _hypothesis_internal_use_seed`. 

In [my updated example](https://gist.github.com/edrdo/2e7ecc1a8af6f67b1255b8314803398d) I simply define the `_hypothesis_internal_use_seed` field in the state machine class (see line 14). This allows me to set the seed of my choice and get deterministic tests.

IMHO, it seems to make sense for future releases to deprecate the `derandomize` parameter and have a `seed` parameter instead in connection with state machines. The idea would be to set a particular seed through this parameter or none at all in which case  it would the seed would be picket at random.

**Comment by Zac-HD** [comment]
Ah, I see what's happening now: our documentation isn't particularly clear that `@hypothesis.seed(...)` is a *decorator*, which can be used on a class or a function (and works by setting the `_hypothesis_internal_use_seed`).

We should clearly state that in the docs, and add some usage examples like

```python
@seed(42)
@given(...)
def test(...):
    ...

@seed(42)
class Model(RuleBasedStateMachine):
    ...
```
