### ISSUE TITLE
Inconsistent Python version support listed on homepage vs. docs

### ISSUE THREAD

**Issue by mprostock** [HypothesisWorks/hypothesis#2664]
Just a minor thing, not really an "issue" but you might want to fix or "harmonize" this anyways:

https://hypothesis.works/products/
lists

- Python Versions **2.7** and **3.4/3.5** as supported

https://hypothesis.readthedocs.io/en/latest/supported.html#python-versions
lists

- CPython **3.6+** as supported

**Comment by Zac-HD** [comment]
@DRMacIver - how about we merge the website into this monorepo so that future grepping catches such issues too?

**Comment by Zac-HD** [comment]
Now fixed 🎉
