### ISSUE TITLE
'Unsatisfiable' error when generating a dataframe from `rows` and `columns` without a `fill` value

### ISSUE THREAD

**Issue by snthibaud** [HypothesisWorks/hypothesis#2678]
According to the documentation, absent values should be filled based on the column dtype, but that does not happen. I created the following minimal example of the problem. Any ideas?

```python
from hypothesis.extra.pandas import data_frames, indexes, column
from hypothesis.strategies import sampled_from, text

print(
    data_frames(
        columns=[column(c, text(), dtype=str) for c in ['a', 'b']],
        rows=sampled_from([{'a': 'x'}]),
        index=indexes(dtype=int, min_size=1)
    ).example()
)
```
The error is:

```python-traceback
  File ".../python3.8/site-packages/hypothesis/core.py", line 763, in run_engine
    raise Unsatisfiable(
hypothesis.errors.Unsatisfiable: Unable to satisfy assumptions of hypothesis example_generating_inner_function.
```

**Comment by Zac-HD** [comment]
Hey @snthibaud - that's a great bug report :smile: 

It looks like the problem is in providing both rows and columns - [if you provide both, they are validated against each other](https://hypothesis.readthedocs.io/en/latest/numpy.html#hypothesis.extra.pandas.data_frames).  If you *just* use columns, the following example works:

```python
from hypothesis.extra.pandas import data_frames, indexes, column
from hypothesis import given, strategies as st


@given(
    data_frames(
        columns=[
            column("a", st.just("x"), dtype=str),  # note: more specific elements
            column("b", st.text(), dtype=str),
        ],
        index=indexes(dtype=int, min_size=1),
    )
)
def test(df):
    pass
```

We should try to provide a more specific error message for this case though!

**Comment by snthibaud** [comment]
Hello Zac,

Thank you! What exactly is meant by 'validated' here?

I read this phrase in the same section:
> Any values missing from the generated rows will be provided using the column’s fill.

So I assumed that 'a' would be the specified string 'x' and column 'b' would be filled by some other text (provided by text() ).

I actually need a Dataframe with columns depending on each other (and I cannot specify all columns for all rows).
Does my bug report still stand? :innocent:

**Comment by snthibaud** [comment]
When quoting that line I noticed the word 'fill' and it turns out to be a keyword to the 'column' function!
With this subtle change, it does work as I intended:

```
from hypothesis.extra.pandas import data_frames, indexes, column
from hypothesis.strategies import sampled_from, text

print(
    data_frames(
        columns=[column(c, fill=text(), dtype=str) for c in ['a', 'b']],
        rows=sampled_from([{'a': 'x'}]),
        index=indexes(dtype=int, min_size=1)).example())
```
Thanks for your help! :smile:

**Comment by Zac-HD** [comment]
Aha, that would do it!  We can definitely provide a better error message though, so I'm keeping the issue open for that :grin:
