### ISSUE TITLE
hypothesis-ruby no longer can compile native extensions (conjecture-rust)

### ISSUE THREAD

**Issue by amw-zero** [HypothesisWorks/hypothesis#2681]
Attempting to install hypothesis-ruby via `gem install hypothesis-specs` leads to several Rust compiler errors. The source of them is the [Helix](https://github.com/tildeio/helix) binding layer that allows Ruby to call the conjecture-rust library, and Helix has officially been deprecated.

There are potentially different ways to solve this, but I worked on a PR which removes Helix and pulls in [Rutie](https://github.com/danielpclark/rutie) for the Rust binding layer. The [PR is here](https://github.com/HypothesisWorks/hypothesis/pull/2680).

**Comment by Zac-HD** [comment]
Fixed by #2680 🎉
