### ISSUE TITLE
[Feature] Add setting to turn of unreliable test timings error

### ISSUE THREAD

**Issue by alanhdu** [HypothesisWorks/hypothesis#2684]
In our internal codebase, we have some fairly complicated strategy generators (for fairly complicated data structures). This works rather well, but we end up getting a fair number of `hypothesis.error.Flaky` errors, which all come down to warnings about unreliable test timings:

> Unreliable test timings! On an initial run, this test took 282.91ms, which exceeded the deadline of 200.00ms, but on a subsequent run it took 10.40 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.

Unfortunately, we have not figured out the source of this highly variable test timings (TBH, I'm not actually sure how to track down where this variability comes from). The documented way to disable this warning is to set `deadline=None` -- however, that opens us towards having really slow tests. Is there a way (intead) to disable this warning around unreliable test timings? In other words, to not fail a test as flaky if the "flakiness" is just due to the test timings?

**Comment by Zac-HD** [comment]
The simple - and only - answer is to change the `deadline` setting; either to `deadline=None` to disable it entirely **or** just increasing it to e.g. `deadline=500`.

If the slower version of your test is within an expanded deadline, you won't get the `Flaky` error - we don't care about variable timings *per se*, only if an input violates the deadline on some calls but not others.  Caches are easily the most common cause of this, FYI.
