### ISSUE TITLE
Considering an alternative to dpcontracts?

### ISSUE THREAD

**Issue by raratiru** [HypothesisWorks/hypothesis#2685]
The [docs](https://hypothesis.readthedocs.io/en/latest/extras.html?highlight=contracts#hypothesis-dpcontracts), along with several Hypothesis pycon talks, refer to [dpcontracts](https://pypi.org/project/dpcontracts/).

Hypothesis + Contracts is is a powerful and promising combination which clearly requires a significant investment in lines of code, hence the question: Is that project still alive? 

Their last commit is dated November 20 2018, and [a relevant issue in their repo](https://github.com/deadpixi/contracts/issues/26) is unanswered since September.

**Comment by raratiru** [comment]
It seems that the river currently flows "the other way around":

[Deal](https://github.com/life4/deal) is a design-by-contract library, that incorporates Hypothesis in its operations.

**Comment by Zac-HD** [comment]
There's also some interest from `icontract`, in #2697 :slightly_smiling_face:

**Comment by raratiru** [comment]
Thank you for the answer and also for this May 2019 PyCon presentation of Hypothesis. 

When the possibility of "negative numbers" appeared as a "hey, you did not think of them, did you?" issue, I understood "what Hypothesis is all about" while laughing to tears! 

Thanks to covid quarantine etc, I feel excited discovering tools that really shine in keeping alive the business value of an idea, in each building block that renders it, "from concept to app".

Before `Deal`, i bumped into `icontract` but I could not find Hypothesis... here it is, though, great news!
