### ISSUE TITLE
from_regex generates unintended colon

### ISSUE THREAD

**Issue by theoden-dd** [HypothesisWorks/hypothesis#2689]
`st.from_regex(r'^(606282\d{10}(\d{3})?)|(3841\d{15})$')` generated `'6062820000000000:'`, `'6062820000000000Ā'`, etc.

Please fix or explain why the colon is correct for the generated string.

As far as I can understand this RE must always generate digits-only strings.

**Comment by theoden-dd** [comment]
It's all about regexes: `r'^((606282\d{10}(\d{3})?)|(3841\d{15}))$'`

Don't forget the parenthesis around the alternatives pipe!

**Comment by Zac-HD** [comment]
> Don't forget the parenthesis around the alternatives pipe!

A-ha, that would do it - I also couldn't see the problem :sweat_smile:

(the `from_regex(..., fullmatch=True)` argument might also be useful)
