### ISSUE TITLE
use of pytest 'capfd' (function scoped) fixture with hypothesis

### ISSUE THREAD

**Issue by jay746** [HypothesisWorks/hypothesis#2704]
Query:

I have a pytest test which take input from hypothesis and 'capfd' fixture. I get warning as below:

```
/vnv_syn_new/lib/python3.6/site-packages/hypothesis/extra/pytestplugin.py:173:
    HypothesisDeprecationWarning: test_temp.py::test_cafd_check uses the 'capfd' fixture, which is reset between function calls but not between test cases generated by `@given(...)`.  
    You can change it to a module- or session-scoped fixture if it is safe to reuse; if not we recommend using a context manager inside your test function.
    See https://docs.pytest.org/en/latest/fixture.html#sharing-test-data for details on fixture scope.
```

snapshot to reproduce it.

```python
from hypothesis import given, settings
from hypothesis.extra.numpy import array_shapes
@given(
    input_shape=array_shapes(min_dims=1, max_dims=4, max_side=10)
)
@settings(max_examples=2)
def test_cafd_check(input_shape, capfd):
    print(input_shape)
    out,err=capfd.readouterr()
    #need capfd for further use
```

Can someone please suggest how to fix this warning?

**Comment by Zac-HD** [comment]
The reason for this warning is that the `capfd` fixture persists between all of Hypothesis' invocations of the wrapped function, which is probably not what you intended (if it is, you can use a non-function-scoped fixture without any warnings).

Instead, I'd suggest using [the `redirect_stdout` and `redirect_stderr` context managers from the standard library](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout):

```python
from contextlib import redirect_stderr, redirect_stdout

@given(...)
def test_foo(...):
    with redirect_stderr(outfile), redirect_stdout(outfile):
        ...
```

This ensures that the redirection and buffer are reset for each test invocation.
