### ISSUE TITLE
Circular dependencies when registering strategies with entry point

### ISSUE THREAD

**Issue by mristin** [HypothesisWorks/hypothesis#2710]
I am not 100% sure, but there seems to be a bug when I want to register my module with Hypothesis entry point (https://hypothesis.readthedocs.io/en/latest/strategies.html#registering-strategies-via-setuptools-entry-points). Namely, I set up the entry point:

```
entry_points={
    "hypothesis": ["_ = icontract_hypothesis:_hook_into_icontract"],
},
```

The function `_hook_into_icontract` depends on `hypothesis.strategies` which I suspect to cause circular dependencies when the entry point is effectuated:

```
Traceback (most recent call last):
  ...
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/hypothesis/__init__.py", line 53, in <module>
    run()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/hypothesis/entry_points.py", line 62, in run
    hook = entry.load()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/runner/work/icontract-hypothesis/icontract-hypothesis/icontract_hypothesis/__init__.py", line 402, in <module>
    ) -> hypothesis.strategies.SearchStrategy[T]:
AttributeError: module 'hypothesis' has no attribute 'strategies'
```

The full error can be retrieved at: https://github.com/mristin/icontract-hypothesis/pull/5/checks?check_run_id=1585794209

**Comment by mristin** [comment]
Strangely enough, I do not observe this bug on my Windows machine, but only on the remote GitHub CI servers.

**Comment by Zac-HD** [comment]
Huh.  This *shouldn't* happen, because we're very careful to load entry points only [at the end of `__init__.py`](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/__init__.py)...

Maybe you're importing `icontract-hypothesis` before Hypothesis itself, and that's grabbing things in odd orders?

**Comment by mristin** [comment]
The bug appears when I doctest `icontract_hypothesis/__init__.py` module. This happens only on Linux (remote, GitHub) and not on my machine.

So I suppose doctest needs to import `icontract_hypothesis` (A), which in turn imports hypothesis, which in turn imports another *instance* of `icontract_hypothesis` module (B)? It seems that the hook is effectuated by the second instance (B) which is imported first and then the first instance (A) of `icontract_hypothesis` fails.

As I hook into `icontract` as well, I inspected the `id` of the hook function and they were different, but both having `__module__` set to `icontract_hypothesis`.

In my understanding, calling Python `import` twice would not reload the module, so there should be no two instances of `icontract_hypothesis` module, but I might be wrong?

**Comment by Zac-HD** [comment]
Maybe related to [use of `importlib`](https://github.com/mristin/icontract-hypothesis/blob/611293947e31dca08f327cb118dfabd4cf58a9a8/icontract_hypothesis/pyicontract_hypothesis/_general.py) vs. `import` statement?  I don't have any particular insight here, sorry.

**Comment by mristin** [comment]
> Maybe related to use of importlib vs. import statement?

Yes, I also suspect that the double `importlib` calls (one from `doctest`, another one from Hypothesis) cause this behavior. I fixed it by using a global switch in the third module that was hooked into (`icontract`) which then finally worked.

**Comment by Zac-HD** [comment]
Thanks for updating us!  The import system can indeed get pretty complicated 😃
