### ISSUE TITLE
Re-running `./build.sh documentation` uses stale Python source files

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#2734]
While tweaking some documentation for #2733, I noticed that if I run `./build.sh documentation`, and then make some changes to our `.py` files and rebuild the documentation, those new changes are not picked up by the documentation build.

(This is most noticeable if I make some local code changes that trigger a warning in the docs compiler, build the docs, and then try to fix the warning. The subsequent build continues to complain about errors that no longer exist in my current source.)

I haven't investigated this deeply, but it seems that a snapshot of Hypothesis gets installed in `site-packages` of the venv, but isn't updated by subsequent builds.

**Comment by Zalathar** [comment]
Looks like the snapshot gets installed as part of the basic tooling environment setup in `build.sh` itself.

For example, if I run `./build.sh tasks`, then edit source, then run `./build.sh documentation`, the edits do not appear in the documentation.

**Comment by Zalathar** [comment]
https://github.com/HypothesisWorks/hypothesis/blob/cebd49096013bdbe2b6e062f350db4d4cb7ea3e2/build.sh#L44

Possibly caused by e2e0cf9 installing `hypothesis-python/` without `-e`?

(Removing this line entirely doesn't seem to affect the docs build, though it might be needed for something else.)

**Comment by Zac-HD** [comment]
Ah, from memory I was working with `sphinx-programoutput` but eventually gave up on it... apparently without removing all the setup. So if it seems tgat line can safely be removed, we should do just that.
