### ISSUE TITLE
Register numba RNG

### ISSUE THREAD

**Issue by willprice** [HypothesisWorks/hypothesis#2737]
I've just been developing some random generators written in numpy but I had to convert them to numba for speed reasons, however I got tripped up since hypothesis is not numba aware and I cannot register its RNG since they don't expose a `get_state` or `set_state` method, but instead only allow you to explicitly set the seed via `np.random.seed` https://numba.pydata.org/numba-doc/latest/reference/numpysupported.html#random

Any suggestions on how to enable hypothesis to test stochastic numba-JITed code?

Thanks for the wonderful library and documentation. Hypothesis is a stellar example of a python library executed to a very high standard. Happy New Year

**Comment by Zac-HD** [comment]
Thanks for your kind feedback - and happy new year!

Following [our Numpy shim](https://github.com/HypothesisWorks/hypothesis/blob/cebd49096013bdbe2b6e062f350db4d4cb7ea3e2/hypothesis-python/src/hypothesis/internal/entropy.py#L25-L34), I think the best available option would be to create a shim which passes through the `seed()` method and makes `getstate()` and `setstate()` into no-ops.

**Comment by willprice** [comment]
Great, thanks for the advice and speedy response!

I used

```python
import random
import numpy as np
from hypothesis import register_random
from numba import jit


@jit(nopython=True, cache=True)
def numba_seed(seed):
    np.random.seed(seed)
    random.seed(seed)


class NumbaRandomWrapper:
    def __init__(self):
        def noop(*args, **kwargs):
            pass

        self.seed = numba_seed
        self.getstate = noop
        self.setstate = noop


def register_numba_rng_for_hypothesis():
    register_random(NumbaRandomWrapper())
```

and import and run `register_numba_rng_for_hypothesis` at the top of each test and this seems to work.

**Comment by Zac-HD** [comment]
Nice!  You should only need to run that once per test process, e.g. from `conftest.py`, to have it work for everything 🙂

**Comment by willprice** [comment]
Ah, that's a good point, I hadn't thought of that. Thanks for the tip!
