### ISSUE TITLE
How to type composite strategies

### ISSUE THREAD

**Issue by felixdivo** [HypothesisWorks/hypothesis#2748]
I want to type some `@hypothesis.strategies.composite` annotated example providers/strategies/... ;) but ["Writing downstream type hints"](https://hypothesis.readthedocs.io/en/latest/details.html#writing-downstream-type-hints) in the docs did not help me enough.

A small dummy Example:

```python
import hypothesis.strategies as st

DrawType = Callable[[SearchStrategy[List[int]]], List[int]]

@st.composite
def list_that_starts_with_1(draw: DrawType) -> SearchStrategy[List[int]]:
    return [1] + draw(st.lists(st.integers()))
```

Is this how it is intended? My point besides that: It could be documented by an example in the aforementioned docs and maybe a generic `DrawType` could be added for use in custom strategies?

**Comment by Zac-HD** [comment]
Yep, you're correct - in general it's `Callable[[SearchStrategy[T]], T]` and in your case `T = List[int]` 😄 

I don't think we need to add a `DrawType` alias to our API, but should note this in the docs.  Thanks for reporting it!

**Comment by felixdivo** [comment]
Okay, thanks! However, the above example function is actually returning a `List[int]` and not a `SearchStrategy[List[int]]`, so the type checker complains. Whats going wrong here? Is `SearchStrategy[T] <: T`, i.e. is `SearchStrategy[T]` a subtype of `T`? Then mypy would require a down-cast.

**Comment by rsokl** [comment]
The resulting function does not return lists when called. It returns a search strategy which will generate lists:

```python
>>> list_that_starts_with_1()
list_that_starts_with_1()

>>> type(list_that_starts_with_1())
hypothesis.strategies._internal.lazy.LazyStrategy
```

PyRight gets it right:

![image](https://user-images.githubusercontent.com/29104956/104240180-aabf7b00-5429-11eb-834c-086a4909fb71.png)

**Comment by felixdivo** [comment]
Ah well. Seems like Mypy just does not get it. Not even with this very explicit version:

```python
@st.composite
def list_that_starts_with_1(draw: DrawType) -> SearchStrategy[List[int]]:
    a: List[int] = [1]
    b: List[int] = draw(st.lists(st.integers()))
    return a + b
```

Which returns: `error: Incompatible return value type (got "List[int]", expected "SearchStrategy[List[int]]")`

Nothing to be done here.

**Comment by Zac-HD** [comment]
The return type of your function should just be `List[int]`; it's then wrapped in SearchStrategy by the decorator.

**Comment by rsokl** [comment]
Unfortunately, that doesn't play nice with either pyright or PyCharm :/   (i.e. they infer that the function produces values, not search-strategies)

**Comment by rsokl** [comment]
Closing this. @Zac-HD is correct that the (unwrapped) function does indeed return `List[int]` and that is what mypy likes to see. It is unfortunate that the type-checkers used by IDEs get bummed out by this
