### ISSUE TITLE
Using hypothesis programmatically

### ISSUE THREAD

**Issue by roiDaniela** [HypothesisWorks/hypothesis#2752]
I want to call a function several times in my code swhich will find counterexample between 2 functions, is it possible to do this with  hypothesis? Thanks

**Comment by Zac-HD** [comment]
Yes, you can call functions decorated with `@given` just like you would anything else:  for example

```
@given(x=st.integers())
def check(f, g, x):
    assert f(x) == g(x)

check(f=math.sin, g=math.cos)  # fails, obviously
```

**Comment by roiDaniela** [comment]
Hello, I mean that I will use it in standrad run and not a test run
