### ISSUE TITLE
Can't write a test with examples but no strategies

### ISSUE THREAD

**Issue by jwg4** [HypothesisWorks/hypothesis#2764]
Hi, I would like to write a test which uses hypothesis but doesn't use any strategies, only examples. Why? Well, I am using hypothesis for my tests in general, and I'm used to structuring tests like this. I am going to have a strategy for the test one day, but not yet. But I already have at least one example, which I want to keep around. So I feel I would like to do this.

However:
```
from hypothesis import example, given
from hypothesis.strategies import nothing


@given(nothing())
@example("asdf asdf foo")
@example("qwerty")
def test_a_specific_thing(s):
    assert True


@example("asdf asdf foo")
@example("qwerty")
def test_another_specific_thing(s):
    assert True
```

(In my real use-case the examples would be some more complicated thing, too complicated to easily write a strategy. A string is enough to show how this works)

Neither of these work. The first fails because it thinks the condition is 'unsatisfiable'. The second fails because "fixture 's' not found".

Is there a way of doing this? Should there be a way?

**Comment by rsokl** [comment]
My first recommendation would be to using a pytest-style parameterized test

```python
import pytest

@pytest.mark.parameterize("s", ["qwerty",  "asdf asdf foo"])
def test_another_specific_thing(s):
    assert True
```

I often introduce Hypothesis as a means for replacing these examples with more sophisticated descriptions of test cases (i.e. strategies), so reverting back to them makes sense.

But if you really want to stick to Hypothesis-style tests, you can leverage the `just` strategy

```python
from hypotheses import given, example
from hypothesis.strategies import just

@example("asdf asdf foo")
@given(just("qwerty"))
def test_another_specific_thing(s):
    assert True
```

**Comment by jwg4** [comment]
Thanks very much for this, I appreciate the quick reply. I'll use the just
strategy, which should work perfectly, as I mentioned I'm used to using
hypothesis across the board.

**Comment by rsokl** [comment]
My pleasure! 😄

**Comment by Zac-HD** [comment]
You could also do 


```python
from hypothesis import Phase, example, given, settings
from hypothesis.strategies import nothing


@example("asdf asdf foo")
@example("qwerty")
@settings(phases=set(Phase) - {Phase.generate})  # Just delete this when you have a strategy
@given(nothing())
def test_a_specific_thing(s):
    assert True

```

but TBH I'd reach for `@pytest.mark.parametrize()` and then refactor later.
