### ISSUE TITLE
Test failures with python310

### ISSUE THREAD

**Issue by jonringer** [HypothesisWorks/hypothesis#2767]
Trying to fix python3.10 package set for nixpkgs in https://github.com/NixOS/nixpkgs/pull/110507; and hypothesis is a fundamental python test dependency.  However, I'm getting some failures when running the test suite.

```
FAILED tests/cover/test_annotations.py::test_given_edits_annotations[1] - Ass...
FAILED tests/cover/test_annotations.py::test_given_edits_annotations[2] - Ass...
FAILED tests/cover/test_annotations.py::test_given_edits_annotations[3] - Ass...
FAILED tests/cover/test_lookup.py::test_same_typevars_same_type - TypeError: ...
FAILED tests/cover/test_lookup.py::test_inference_on_generic_collections_abc_aliases[typ0]
FAILED tests/cover/test_lookup.py::test_timezone_lookup[tzinfo] - zoneinfo._c...
FAILED tests/cover/test_lookup.py::test_generic_collections_only_use_hashable_elements[typ0]
FAILED tests/cover/test_lookup.py::test_generic_collections_only_use_hashable_elements[typ1]
FAILED tests/cover/test_lookup.py::test_generic_collections_only_use_hashable_elements[typ2]
FAILED tests/cover/test_lookup.py::test_hashable_type_unhashable_value - zone...
FAILED tests/cover/test_lookup.py::test_compat_get_type_hints_aware_of_None_default
FAILED tests/cover/test_lookup_py38.py::test_simple_typeddict - hypothesis.er...
FAILED tests/cover/test_lookup_py38.py::test_typeddict_with_optional - hypoth...
FAILED tests/cover/test_lookup_py38.py::test_typeddict_with_optional_then_required_again
FAILED tests/cover/test_type_lookup.py::test_can_generate_from_all_registered_types[ZoneInfo]
```

Full output: https://gist.github.com/jonringer/01640e6389af1bcd80e1ef2335224f01
Just failures: https://gist.github.com/jonringer/4269358c4cc01e2e7140898bbe038b16

python packages in testing environment:
```
setuptools-51.3.3.drv
attrs-20.3.0.drv
pytest-6.2.1.drv
pexpect-4.8.0.drv
sortedcontainers-2.3.0.drv
mock-4.0.2.drv
flaky-3.7.0.drv
pytest-xdist-2.1.0.drv
coverage-5.3.drv
```

The last two tests
```
FAILED tests/cover/test_unittest.py::test_subTest_no_self[err0] - ValueError:...
FAILED tests/cover/test_unittest.py::test_subTest_no_self[err1] - ValueError:...
```
Are likely unrelated to python3.10, as I also get this when running the python3.8 tests

EDIT:
confirmed the last two tests were failing because $HOME wasn't a writable directory.

EDIT (again):
Updated info after realizing that I ran hypothesis 5.30

**Comment by Zac-HD** [comment]
Thanks for the report Jon!  We'll aim to fix these and add Python 3.10-dev to our CI :smile:

**Comment by jonringer** [comment]
just realized that the source to hypothesis was still pointing to the 5.30 release, re-packaging and going to update the error list

**Comment by jonringer** [comment]
Post updated to reflect hypothesis==6.0.2, python3.10a3, and direct dependencies

**Comment by Zac-HD** [comment]
Several tests are failing on `zoneinfo.ZoneInfo("UTC")` - this is probably a bug in the language-level configuration of CPython, where it now needs to be informed of where to look for timezone data on the system (or have the `tzdata` package installed).

The remaining test failures all look like CPython regressions:

- Three are failing with `hypothesis.errors.ResolutionFailed: Could not resolve ForwardRef('int') to a strategy` - I believe this is a regression in CPython where the stdlib `typing.get_type_hints()` has broken.
- Another three are failing because the `-> None:` function return-type annotation is now represented as `NoneType` instead of `None` (another CPython regression)
- `test_same_typevars_same_type` is broken due to *another* upstream change; no detailed diagnosis yet
- `test_compat_get_type_hints_aware_of_None_default` is again broken due to an upstream change in type annotation handling (this time in the `__signature__` attribute)

**Comment by jonringer** [comment]
hmmm, isn't this fun :)

**Comment by Zac-HD** [comment]
The *good* news is that it looks like all of the CPython regressions are related to [PEP 563 delayed evaluation of annotations](https://www.python.org/dev/peps/pep-0563/), so there can be a single focussed effort to fix them now that I've written nice upstream bug reports.

My advice for NixPkgs is therefore to try again after the [release of CPython 3.10-alpha5 next week](https://www.python.org/dev/peps/pep-0619/), or alpha6 if it's not fixed that fast, and to consider either [TZPATH configuration](https://docs.python.org/3/library/zoneinfo.html#data-sources) or installing [the `tzdata` package](https://pypi.org/project/tzdata/).

**Comment by jonringer** [comment]
> The _good_ news is that it looks like all of the CPython regressions are related to [PEP 563 delayed evaluation of annotations](https://www.python.org/dev/peps/pep-0563/), so there can be a single focussed effort to fix them now that I've written nice upstream bug reports.

Great :)

Glad this got attention long before the release deadline, so there's ample time for it to be remedied.

> and to consider either [TZPATH configuration](https://docs.python.org/3/library/zoneinfo.html#data-sources) or installing [the `tzdata` package](https://pypi.org/project/tzdata/).

I only just now noticed that we don't for python3.9+

Anyway, thanks for the fast turn around ;)
