### ISSUE TITLE
Failure Reproduction query 

### ISSUE THREAD

**Issue by jay746** [HypothesisWorks/hypothesis#2771]
Query regarding failure reproduction.
I see there are 2 types of reproduction steps thrown by hypothesis.
A) it provides @example (which can be used as decorator) 
B) if test failing due to health check then it will provide @seed 

As @example need to be added as decorator to test, it becomes difficult to modify a file and check-in always when it fails.

Is there anyway I can ask hypothesis to print @seed and @example always in case of failure.
(Maybe enabling any switch in @settings) 
So that @examples gives idea about the data on which it's failing.
And @seed can be used as argument to test as --hypothesis-seed @seed , hence no update in test file required.

Thanks in advance for your help.

**Comment by Zac-HD** [comment]
Have you read https://hypothesis.readthedocs.io/en/latest/reproducing.html ?

I suspect that `@reproduce_failure()` and the `print_blob` setting are what you're looking for.

**Comment by jay746** [comment]
Thanks for reply.
Yes I had gone through this page you mentioned.
But @reproduce_failure() following issues:

A) the reproduce string is valid only at given machine where test ran, same string might not reproduce issue on different machine for same test . Or not valid for change in python version/hypothesis.
B) this again needs to be added as decorator which makes life difficult as involves in modification in file.

- hence I was looking for @seed print which doesn't need any change in file. It can be used on the fly and can be passed to colleagues to reproduce at his side.

**Comment by Zac-HD** [comment]
A) Any particular seed might also have different behaviour on different versions on Hypothesis, and just like `@reproduce_failure()` that's deliberate.  If `@example()` varies across machines that's a bug in your test though.

B) Yep.

You might consider using a shared [`RedisDatabase`, or defining your own shared database](https://hypothesis.readthedocs.io/en/latest/database.html).

**Comment by jay746** [comment]
Thanks for reply 🙂
Just to clear my doubt, few of query:

A) let's assume if python version and hypothesis version remains same, then @seed given by hypothesis reproduce, is this valid for any other machine as well?

B) if yes then is there any way to ask hypothesis to print @seed always when failure happens.

C) in case of flaky behaviour why don't print @example along with @seed
