### ISSUE TITLE
Check for required conjecture-rust releases when a hypothesis-ruby change depends on Rust changes

### ISSUE THREAD

**Issue by amw-zero** [HypothesisWorks/hypothesis#2779]
The production hypothesis-ruby gem depends on the [released conjecture-rust crate](https://crates.io/crates/conjecture). Currently, if a change is made to hypothesis-ruby that depends on a change in conjecture-rust, the CI build does not check that a corresponding release is made for conjecture-rust. This allows a hypothesis-ruby release that can be broken (which happened to the 0.5.0 release) because the depended-on Rust code is not present in the releases conjecture-rust version. 

We should update our tooling to check for this situation and ensure that a corresponding conjecture-rust release is made so that it and the hypothesis-ruby release form an atomic step.

**Comment by Stranger6667** [comment]
Closing this based on [this comment](https://github.com/HypothesisWorks/hypothesis/pull/2775#issuecomment-767980724) as #2775 is merged :tada:
