### ISSUE TITLE
Data generation is extremely slow problem in 6.0.3 version

### ISSUE THREAD

**Issue by rkhass** [HypothesisWorks/hypothesis#2782]
**Description**
--

When running our unit tests, we get the error in `hypothesis 6.0.3`:
```
Data generation is extremely slow: ...
```

But when I fix the version: `hypothesis==6.0.2`, no error appears.
Probably the performance of new version has changed.

This error doesn't appear on my machine, only in CI env (that we didn't change)

Very similar behavior I found here https://github.com/HypothesisWorks/hypothesis/issues/2009 

**Versions**
--
* Python: 3.8

**Comment by Zac-HD** [comment]
Can you share a test that was passing before, and now fails?  #2768 had some refactoring and improved type annotations, so it's pretty strange that you're seeing this problem!

**Comment by rkhass** [comment]
I have researched more. Actually it's not a problem of versions.
It looks like the performance of the machine has changed slightly and execution takes longer now. That's why this issue has arisen. 

(Actually when I downgraded the version it helped me, but it happened by an accident)
So I think this issue can be closed.
