### ISSUE TITLE
Get Rust deploys to `crates.io` working

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2789]
This is our first-ever automatic release of Rust code from GitHub Actions, and so as you'd expect we're hitting a few rough patches.

Most recently, the release job https://github.com/HypothesisWorks/hypothesis/runs/1777268760 *almost* entirely worked - pushing 984cec5aea2f9c7e7200e9055547629e31851ecd and the appropriate tag; only the upload to `crates.io` failed for reasons that aren't clear to me.

Opening this as an issue because I don't want any further discussion lost on PRs; see #2775 and #2788 for the work so far.  @Stranger6667 and @amw-zero I think this is mostly your show, but since I hold the keys do let me know if I can help at all 🙂

**Comment by amw-zero** [comment]
Good call on the separate issue.

The last error for this was:

> error: api errors (status 200 OK): invalid upload request: invalid length 22, expected a keyword with less than 20 characters at line 1 column 1275

The keyword "property-based-testing" is 22 chars.

I shortened the keyword here: https://github.com/HypothesisWorks/hypothesis/pull/2790

**Comment by amw-zero** [comment]
Note: I had to create a new release version just for this, since only the deploy failed and the RELEASE.md  file for conjecture-rust 0.5.0 was already removed and appended to the changelog.

**Comment by amw-zero** [comment]
From @Zac-HD:

> Should we also suggest upstream that the error message would be clearer if it included the too-long keyword? I saw it but didn't make the connection.

Why am I feeling shy all of a sudden? 😆 

That would honestly be really helpful. I had to eyeball which keywords looked long and then hand-count them.

**Comment by Zac-HD** [comment]
I'm happy to report it (in a few days) if you'd prefer 😊

**Comment by amw-zero** [comment]
<img width="1365" alt="Screen Shot 2021-01-27 at 10 21 36 AM" src="https://user-images.githubusercontent.com/4043433/106012478-75ea2f80-6089-11eb-88e5-29d9f89294ba.png">

**Comment by Zac-HD** [comment]
And https://crates.io/crates/conjecture plus https://rubygems.org/gems/hypothesis-specs/versions/0.6.0 🎉✨✨

Thanks, @amw-zero 😇

**Comment by Zac-HD** [comment]
OK, no need for an upstream report as https://github.com/rust-lang/cargo/issues/4300 already exists.
