### ISSUE TITLE
Class with parameter of type of another class

### ISSUE THREAD

**Issue by BogaertsCeline** [HypothesisWorks/hypothesis#2851]
While making sure hypothesis predict the right values for custom classes. I came across a problem.
I have a class `Ranges` with parameters with a type of the `RangInt` class. `RangeInt` has soms constraints about the type. In this example, Hypothesis predict of the type int but ignore the constraints.
Is this my problem or is it something wrong in the library?
(This code must be run on separate files)
```
from pydantic import BaseModel, ConstrainedInt
import pytest
import hypothesis.strategies as st
from hypothesis import given, settings

class RangInt(ConstrainedInt):
    ge = 0
    le = 10

class Ranges(BaseModel):
    rangeIng:RangInt

for constrained_int_type in [RangInt]:
    st.register_type_strategy(
        constrained_int_type, 
        lambda T: st.integers(
            min_value=T.gt + 1 if T.gt is not None else T.ge,
            max_value=T.lt - 1 if T.lt is not None else T.le,
        ),
    )


def gen_test():
    yield from (RangInt, Ranges)


@pytest.mark.parametrize("model", gen_test())
@settings(deadline=900)
@given(data=st.data())
def test_RangInt(data, model) -> None:
    instance = data.draw(st.from_type(model))
    assert isinstance(instance, model)
```

**Comment by Zac-HD** [comment]
Your solution looks good!

Once https://github.com/samuelcolvin/pydantic/pull/2097 ia merged this will be totally automatic, too 😁

**Comment by BogaertsCeline** [comment]
I don't think this issue has something to do with issue #2097. The class `RangIng` works properly but the `Pydantic Error` is on the class `Ranges`. It looks like the parameter `RangeIng` is of the type `int` but the constraints are on the type `RangesInt` are not included. 
The error :
`
   pydantic.error_wrappers.ValidationError: 1 validation error for Ranges
  rangeIng
     ensure this value is greater than or equal to 1 (type=value_error.number.not_ge; limit_value=1)
`

**Comment by Zac-HD** [comment]
Not Hypothesis issue 2097 which you linked to,  samuelcolvin/pydantic#2097 - which will indeed fix this.  Trust me, I wrote the code and the tests; it just needs to be merged and released!
