### ISSUE TITLE
Improve handling of empty arrays in `element_of()`

### ISSUE THREAD

**Issue by amw-zero** [HypothesisWorks/hypothesis#2852]
Currently, if you try and call `element_of([])`, it triggers a panic in conjecture-rust:

> thread '<unnamed>' panicked at 'assertion failed: status == Status::Invalid || status == Status::Overflow'

This is a common mistake, since often you will create Arrays via the `arrays` Possible, and that can return empty Arrays.

I'm not sure if `element_of([])` should just return nil, or if we can just improve the error messaging to say something like:

"Attempting to find the element of an empty Array. This is not defined."

**Comment by Zac-HD** [comment]
In the Python version, `sampled_from([])` raises `InvalidArgument("Cannot sample from a length-zero sequence.")`.  [Our API style guide explains:](https://github.com/HypothesisWorks/hypothesis/blob/master/guides/api-style.rst#argument-handling)

> If a combination of arguments make it impossible to generate anything, raise `InvalidArgument` instead of `return nothing()`. Returning the null strategy is conceptually nice, but can lead to silently dropping parts from composed strategies and thus unexpectedly weak tests.

In Ruby, I'd probably make the message `"An empty sequence has no elements."` to match the different function names.

**Comment by amw-zero** [comment]
Perfect, thanks for sharing those API guidelines.

**Comment by Zac-HD** [comment]
Closing this because, sadly, nobody is maintaining Hypothesis for Ruby.

(readers: if you would like to volunteer, we'd love to have you!)
