### ISSUE TITLE
@settings not applied in presence of other decorators

### ISSUE THREAD

**Issue by Rik-de-Kort** [HypothesisWorks/hypothesis#2856]
Morning.
First example fails with `DeadlineExceeded`, second example succeeds. Both have `settings(deadline=None, max_examples=5)`, but the ordering is different. It appears the settings don't get applied at all in the first test.

````python
from hypothesis import strategies as st, given, settings

from time import sleep


def some_setup(func):
    def wrapped(*a, **kw):
        return func(*a, **kw)
    return wrapped


@given(x=st.integers())
@some_setup
@settings(deadline=None, max_examples=5)
def test_fails(x):
    sleep(1)
    assert True


@given(x=st.integers())
@settings(deadline=None, max_examples=5)
@some_setup
def test_succeeds(x):
    sleep(1)
    assert True



````

I've verified that removing `max_examples` doesn't change the result. It just takes 2 minutes longer. I'm not sure exactly why it happens, seems like there's some crucial indirection that's happening with `self` when `@settings` is at the bottom. Using `wrapt` to turn the setup decorator into a more transparent object also solves the problem, like so:

````python
from hypothesis import strategies as st, given, settings

import wrapt
from time import sleep

@wrapt.decorator
def some_setup_wrapt(wrapped, instance, args, kwargs):
    return wrapped(*args, **kwargs)

@given(x=st.integers())
@some_setup_wrapt
@settings(deadline=None, max_examples=5)
def test_succeeds_wrapt(x):
    sleep(1)
    assert True
````

Perhaps there's some way we can detect this situation and advise using `wrapt`?

Environment info:
Python 3.7.9 on Windows
Hypothesis 6.1.1
Pytest 6.2.2

**Comment by rsokl** [comment]
I don't think that users should expect the following to work:

```python
@settings(...)
def func():
    ...
    
@given(...).
def test():
   func()
```

This is effectively what your `test_fails` example does, since your original `some_setup` decorator does not expose the function that it wraps.. I don't think that it this is a situation that can be detected easily.

**Comment by Zac-HD** [comment]
Decorating `def wrapped()` with [`@functools.wraps(func)`](https://docs.python.org/3/library/functools.html#functools.wraps) from the standard library would also work - the key is that you need to copy the attributes of the wrapped function to the wrapper.
