### ISSUE TITLE
Pytest 6.2 warns about the deprecated --strict flag

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#2863]
As of pytest 6.2, the `--strict` flag is deprecated and issues a warning. Because we include this flag in our `pytest.ini` (and various other places), all of our pytest invocations produce this annoying warning, making it harder to understand the test results.

(The `--strict-markers` flag was introduced in [pytest 4.5](https://docs.pytest.org/en/stable/changelog.html#pytest-4-5-0-2019-05-11) as an alias for the existing `--strict` flag, in the hope that `--strict` could be eventually repurposed into a catch-all strict mode flag.)

In #2862 I tried to fix this by replacing `--strict` with `--strict-markers` in our repo. This *almost* worked, except that `check-pytest43` now fails because pytest 4.3 it doesn't understand `--strict-markers` and errors out.

Before going too far down the rabbit hole of trying to fix that, I thought I'd open an issue for discussion of what we should actually do about this whole situation.

**Comment by Zalathar** [comment]
I understand that we want to try to support older pytest versions, but is there any particular reason to stick with 4.3?

Back in January of 2020, pytest appears to have [stopped active maintenance](https://docs.pytest.org/en/stable/py27-py34-deprecation.html) of pytest 4.**6** in favour of best-effort community maintenance.

**Comment by Zalathar** [comment]
For context, the last time we bumped our pytest requirement was #2126 in late 2019.

**Comment by Zalathar** [comment]
I think I've figured out how to make pytest 4.3 not see `--strict-markers` in `pytest.ini`, so I might end up reopening #2862 after all.

**Comment by Zac-HD** [comment]
I'm perfectly happy to bump our minimum Pytest version to 4.6 and move on - according to the general rule "we support whatever upstream still supports, plus older things if they're still in widespread use *and doing so is not inconvenient to us volunteers*".  Since 4.3 is now inconvenient as well as EOL upstream, it's time to drop support.

On the other hand, if you can make old versions ignore new flags we might as well add `--strict-config` too!

**Comment by Zalathar** [comment]
At this point the workaround is easier than dropping support (since I've already written the workaround), but I wouldn't object to dropping support anyway.

**Comment by Zac-HD** [comment]
I'm voting to drop support for <4.6; it's about time and it saves us the slightly-awkward workaround.
