### ISSUE TITLE
Easier way to check `RuleBasedStateMachine` invariants only when fully initialized

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2868]
When using [stateful testing](https://hypothesis.readthedocs.io/en/latest/stateful.html), `@invariant()` methods are currently checked between every `@initialize()` method as well as between `@rule()` methods - which is awkward if your invariants require the machine to be initialized (see #2860 for discussion).

Instead of requiring users to use `@precondition()` decorators and track the "fully initialized" state themselves, I propose that we should add a new argument to the invariant decorator:

```python
def invariant(*, check_before_initialized=True):
```

to make disabling this behaviour on a per-invariant basis more convenient.

Contra #2860, I think we should retain the existing (always check invariants) behaviour by default - our [API style guide](https://github.com/HypothesisWorks/hypothesis/blob/master/guides/api-style.rst) emphasises avoiding things that can lead to "unexpectedly weak tests".  I'm open to suggestions for a better parameter name, with the goal that it should be very obvious than `@invariant(argname=True)` is checked both before and after while `False` is only checked after.

**Comment by Zalathar** [comment]
If anything I’m leaning the other way at the moment.

I’m struggling to imagine a realistic use case checking invariants during init. Even in cases where it *would* be useful, we’d still check invariants after all initializers complete successfully, so the worst case is that we fail slightly later than we otherwise would have.

**Comment by Zac-HD** [comment]
After #2883 is merged, I'll open a PR for this issue from https://github.com/Zac-HD/hypothesis/compare/multiple-preconditions...init-then-invariants.
