### ISSUE TITLE
@given production hangs halfway through the test with recursive json strategy

### ISSUE THREAD

**Issue by cmorley191** [HypothesisWorks/hypothesis#2869]
I'm testing a json-related algorithm, so I've been trying variations of [the example recursive json strategy provided in the official documentation](https://hypothesis.readthedocs.io/en/latest/data.html?highlight=recursive#recursive-data).

```
json = recursive(
    none() | booleans() | floats() | text(printable),
    lambda children: lists(children, min_size=1),
    | dictionaries(text(printable), children, min_size=1)
)
```

**Using this generator as a `@given` in a test causes the test to hang** after testing half of the max_examples (e.g., with 100 max_examples, the test will hang after running example 50 or 51; with 30 max_examples, the test will hang after running example 15 or 16, etc.). The only way I have gotten the test to complete is with a max_examples of 10 or fewer. The test does not hang during execution of the test function, so I can only assume it is hanging during the generation of the next example.

No error messages are printed. The test simply executes forever.

**Steps to reproduce**

Here is a minimal example test file of this issue. Simply run this file with pytest (`py -m pytest test_file.py`)

```
from hypothesis import given, settings
from hypothesis.strategies import none, integers, floats, booleans, text, lists, dictionaries, recursive
from string import printable

json = recursive(
    none() | booleans() | floats() | text(printable),
    lambda children: lists(children, min_size=1)
    | dictionaries(text(printable), children, min_size=1)
)

test_count = 1
with open('test_status.txt', 'w') as f:
    # clear the file
    pass

@settings(max_examples=30)
@given(json)
def test_json(x):
    global test_count
    with open('test_status.txt', 'a') as f:
        f.write(f'Running test {test_count}\n')
        test_count += 1
    assert True
```

I've added the `test_status.txt` stuff so you can see when it hangs (in this case, after running test 15). This issue will still occur without that extra code, when you just have:

```
from hypothesis import given, settings
from hypothesis.strategies import none, integers, floats, booleans, text, lists, dictionaries, recursive
from string import printable

json = recursive(
    none() | booleans() | floats() | text(printable),
    lambda children: lists(children, min_size=1)
    | dictionaries(text(printable), children, min_size=1)
)

@given(json)
def test_json(x):
    assert True
```

I am using version 6.3.0 of hypothesis

**Comment by cmorley191** [comment]
This issue appears to occur for any recursive strategy that is extended with lists or dictionaries.

For example, these strategies will also cause the hanging behavior:

```json = recursive(none(), lambda children: lists(children))```

```json = recursive(none(), lambda children: dictionaries(integers(), children))```

Am I using recursive incorrectly? It doesn't seem like I am, from reading the documentation

**Comment by Zac-HD** [comment]
You're using `recursive()` correctly, and indeed when I run this example it completes 100 examples in around 3.7 seconds!

- What versions of Python, Pytest, and Hypothesis are you using?
- Try adding ` -s --hypothesis-verbosity=verbose` and/or `--hypothesis-show-statistics` to your command-line arguments

Those simpler strategies are *really* strange; even if things are slow they shouldn't hang!  Obvious question, but the example tests exactly as written (with `pass` or `assert True` as the body) are hanging for you, not just those recursive strategies?

**Comment by rsokl** [comment]
`test_json` doesn't hang for me 

![image](https://user-images.githubusercontent.com/29104956/108632463-17706100-743d-11eb-9cee-dfa82d26174e.png)

**Comment by cmorley191** [comment]
Solved. I was on python 3.7.0, hypothesis 6.3.0 and pytest 5.4.3. Upgrading to the latest pytest 6.2.2 resolved the issue.

Silly of me to not check that. Thanks for the quick responses!

**Comment by Zac-HD** [comment]
Huh... weird that pytest 5.4.3 did something different here, but I don't think that's *our* bug in any case (and would guess a plugin interaction).

@rsokl - check out https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-time
