### ISSUE TITLE
Question: Is there a ForkingTestCase alternative?

### ISSUE THREAD

**Issue by adnion** [HypothesisWorks/hypothesis#2870]
ForkingTestCase was removed in 2016
https://hypothesis.readthedocs.io/en/latest/changes.html#v3-0-0

I run
`mpirun -n 2 python -m pytest --with-mpi --hypothesis-seed 1234 tests.py`
and for many test cases or big arrays I get segmentation faults.
For small runs it only fails occasionally.
Each individual test runs fine with this setup.

**Comment by Zac-HD** [comment]
Not at the moment - we removed `ForkingTestCase` because the underlying engine changed and it just hasn't been implemented for the new engine yet.

We'd be happy to accept a PR implementing this, even if it leaves e.g. Windows support for a future contributor :slightly_smiling_face:

**Comment by adnion** [comment]
I just looked at the code for `ForkingTestCase` https://github.com/HypothesisWorks/hypothesis/blob/hypothesis-python-2.0.0/src/hypothesis/testrunners/forking.py
I don't understand how it was supposed to work. I'll search for another solution.
