### ISSUE TITLE
Should I check in .hypothesis/ ?

### ISSUE THREAD

**Issue by hexagonrecursion** [HypothesisWorks/hypothesis#2873]
At the time of writing https://hypothesis.readthedocs.io/en/latest/database.html does not contain any advice on whether `.hypothesis/` should be checked into the source control or added to `.gitignore`. I do not know whether checking it into the source control is:
* a great idea
* a horrible idea
* a security hazzard
* a useless waste of space

**Comment by Zac-HD** [comment]
See https://hypothesis.readthedocs.io/en/latest/database.html#hypothesis.database.DirectoryBasedExampleDatabase
