### ISSUE TITLE
Refactor hypothesis.strategies._internal.core._from_type

### ISSUE THREAD

**Issue by Melevir** [HypothesisWorks/hypothesis#2875]
As for now, `from_type` seems quite straightforward but very long and sometimes hard to read.

I was thinking about refactoring the function to something like that:

```python
def _from_type(thing: Type[Ex]) -> SearchStrategy[Ex]:
    ordered_resolvers = [
        Resolver(condition=is_not_type_instance, resolver=not_type_instance_resolver),
        Resolver(condition=is_not_type, resolver=not_type_resolver),
        Resolver(condition=lambda t: True, resolver=global_types_dictionaty_resolver),
        Resolver(
            condition=[python_version_gte(3, 9), is_typing_type],
            resolver=is_not_type_instance_resolver,
        ),
        Resolver(
            condition=has_nonempty_strategiest_in_global_dictionary,
            resolver=nonempty_strategiest_in_global_dictionary_resolver,
        ),
        Resolver(condition=is_enum, resolver=sample_from_enum_resolver),
        # ...
    ]

    default_resolver = from_sublassess_resolver
    for resolver in ordered_resolvers:
        if resolver.condition(thing):
            type_candidate = resolver.resolver(thing)
            if type_candidate:
                return type_candidate
    return default_resolver(thing)
```

Profits:

- `_from_type` became much shorter and self-explanatory;
- the logic is much easy to understand for newcomers contributors (like me);
- conditions and resolvers live in separate modules, no common state between them (conditions and resolvers most likely to be pure);
- resolvers conditions and ordering is much readable, so there should be fewer bugs like #2872.

If the proposition is approved, I'll try to implement the refactoring.

**Comment by Zac-HD** [comment]
I'd be happy to refactor it a bit, but let's keep control flow nice and explicit:

```python
def _from_type(thing: Type[Ex]) -> SearchStrategy[Ex]:
    if is_not_type_instance(...):
        return not_type_instance_resolver(thing)
    if is_not_type(...):
        return not_type_resolver(thing)
    res = global_types_dictionary_resolver(thing)
    if res is not None:
        return res
    if python_version_gte(3, 9) and is_typing_type(thing):
        return is_not_type_instance_resolver(thing)
    if has_nonempty_strategiest_in_global_dictionary(...):
        return nonempty_strategiest_in_global_dictionary_resolver(thing)
    if is_enum(...):
        return sample_from_enum_resolver(thing)
    return default_resolver(thing)
```

I'd keep most of the current comments, though I'd expect the refactoring would allow you to split them between explaining the ordering (in `_from_type()`) and explaining the content of each step (in the helper functions).

And thanks for sticking around to help out 💖

**Comment by Melevir** [comment]
It seems quite important for me that the function should be as declarative as possible. That will make adding more logic to the function in the future less tempting.

Why don't you like the looping-over-resolvers idea?

**Comment by rsokl** [comment]
A couple of issues is that it makes stack traces harder to follow, and it also means that we don't get meaningful test code-coverage metrics on `_from_type`.

**Comment by Zac-HD** [comment]
Closing this issue because while we'd be happy to accept a lightweight refactoring of this function, I also wouldn't mind if we don't get around to it.
