### ISSUE TITLE
How to test that output is not affected by changing dependency versions?

### ISSUE THREAD

**Issue by mboratko** [HypothesisWorks/hypothesis#2881]
Thanks for developing Hypothesis!

As a feature request, it seems one thing that might be possible (particularly with the Ghostwriter functionality) is simply checking for version dependency compatibility issues. Essentially, the idea would be that we automatically generate some tests for various functions / modules and, rather than specify the exact output, simply check that the overall behavior is identical to a known working version of the dependency.

For example, I imagine this working as follows: we depend on `numpy==0.1`, run `hypothesis write --compatibility numpy our_module`. It then scans the code, looking for instances that `numpy` is used. Say it finds some function `func(a,b)` which seems to depend on numpy, then it generates some test cases (using the same strategy as other Ghostwriter functionality) and simply saves the outputs for these test cases in the `.hypothesis` directory. We could then save this test in a file, using some annotation such as `@hypothesis.compatibility(numpy)`, which would then look up the input/output used and simply verify that it does the same thing - whether that be checking for return values, throwing exceptions, etc.

Apologies if something like this is already implemented, if so I'd appreciate a pointer to the relevant documentation!

**Comment by Zac-HD** [comment]
Hmm, this is an interesting idea!

I don't think the workflow you described is a good fit for Hypothesis - saving known behaviour to replay later is more about generating traditional unit tests than property-based testing.  You could certainly use Hypothesis to generate the behaviour-to-save, but after that our shrinking etc. wouldn't come into it at all 😢 

On the other hand, some recent experiments in [cross-branch testing](https://buttondown.email/hillelwayne/archive/cross-branch-testing/), [`diffbehaviour`](https://crosshair.readthedocs.io/en/latest/diff_behavior.html), and [this tweet](https://twitter.com/pschanely/status/1350864341667606528) (ping @pschanely) suggest that we might be able to hack together a way to import multiple copies of your code with different dependency versions - and then run a possibly-ghostwritten standard Hypothesis test to check they're equivalent.

Said import hack isn't really in-scope for Hypothesis, but I'd be happy to recommend it as a complementary tool - much like `pytest`.

**Comment by pschanely** [comment]
This is an interesting use case that I imagine would help a lot of people.

CrossHair's [`diffbehavior`](https://crosshair.readthedocs.io/en/latest/diff_behavior.html) command needs to have both the new and old code imported in the same python process; in a more typical scenario, this can be hacked together by checking out the old code and importing it under a different directory name, which python will just interpret as a new top-level package. Needles to say, that trick wouldn't work for a project's dependencies.

That said, with a bunch of caveats, I think it's possible to do import tricks to try a get multiple versions of a dependency loaded. While I wouldn't be able to tackle that kind of work right away, I'd be happy to collect "thumbs up" reactions on a CrossHair feature request if it's an approach you'd use. Cheers!
