### ISSUE TITLE
`mypy --no-implicit-reexport` infers `st.one_of(...) -> Any` in 6.3.3+

### ISSUE THREAD

**Issue by sobolevn** [HypothesisWorks/hypothesis#2884]
My CI failed, because of the `mypy` check.
For some reason the latest version did change the typing of `st.one_of`. 

```
returns/contrib/hypothesis/containers.py:58: error: Returning Any from function declared to return "SearchStrategy[Any]"
```

Source: https://github.com/dry-python/returns/blob/master/returns/contrib/hypothesis/containers.py#L58

Link to the job: https://github.com/dry-python/returns/pull/839/checks?check_run_id=200189528

**Comment by Zac-HD** [comment]
I'd expect this to be linked to https://github.com/HypothesisWorks/hypothesis/compare/hypothesis-python-6.3.2...hypothesis-python-6.3.3, where the implementation of `st.one_of()` was moved... though that really, really shouldn't have changed the inferred type.

Can you check 6.3.2 and 6.3.3 to confirm that it's one of those updates, and also report your Python and mypy versions?

**Comment by sobolevn** [comment]
Yes, sure!

Currently I have:
- python from 3.7 to 3.9
- mypy 0.812
- hypothesis 6.3.2 https://github.com/dry-python/returns/blob/d31626d4358dd75b7fe43208d317cbf9ababe95a/poetry.lock#L564

And it works.

Now, let's update hypothesis to 6.3.3

```
(.venv) ~/Documents/github/returns  master ✔                                         
» hypothesis --version
hypothesis, version 6.3.2

(.venv) ~/Documents/github/returns  master ✔                                         
» mypy returns
Success: no issues found in 112 source files

(.venv) ~/Documents/github/returns  master ✔                                         
» pip install -U 'hypothesis==6.3.3'
Collecting hypothesis==6.3.3
  Downloading hypothesis-6.3.3-py3-none-any.whl (358 kB)
     |████████████████████████████████| 358 kB 1.6 MB/s 
Requirement already satisfied, skipping upgrade: attrs>=19.2.0 in ./.venv/lib/python3.8/site-packages (from hypothesis==6.3.3) (20.3.0)
Requirement already satisfied, skipping upgrade: sortedcontainers<3.0.0,>=2.1.0 in ./.venv/lib/python3.8/site-packages (from hypothesis==6.3.3) (2.3.0)
Installing collected packages: hypothesis
  Attempting uninstall: hypothesis
    Found existing installation: hypothesis 6.3.2
    Uninstalling hypothesis-6.3.2:
      Successfully uninstalled hypothesis-6.3.2
Successfully installed hypothesis-6.3.3
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the '/Users/sobolev/Documents/github/returns/.venv/bin/python -m pip install --upgrade pip' command.

(.venv) ~/Documents/github/returns  master ✔                                         
» mypy returns                      
returns/contrib/hypothesis/containers.py:58: error: Returning Any from function declared to return "SearchStrategy[Any]"
Found 1 error in 1 file (checked 112 source files)
```

**Comment by Zac-HD** [comment]
Huh, I *think* that this is because I moved the definition of `one_of()` from `core.py` to `strategies.py`, but it's imported into `__init__` via `core`.  Changing the import, for that and the other moved functions, might be enough to fix it... though I maintain that it *shouldn't* have broken.

What's worse is that we already have an automated test for this (note `"Any"` in params is `SearchStrategy[Any]` in the test) - https://github.com/HypothesisWorks/hypothesis/blob/d76b28402d3e96ab3f224864ca2a05d40c3fda38/whole-repo-tests/test_type_hints.py#L51-L86 - and it's continued passing the whole time.  I'm therefore reluctant to make further changes without also understanding enough to be confident that the test, or new test, would actually warn us in future.

**Comment by sobolevn** [comment]
Looks like a job for me! 😆

**Comment by sobolevn** [comment]
Ok, here's what's happening. 

`dry-python/returns` has [`--no-implicit-reexport`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport) option enabled. While `hypothesis` does not use this option: https://github.com/HypothesisWorks/hypothesis/blob/master/mypy.ini#L1 That's the main reason we see a different type inference.

`hypothesis@6.3.2` has `one_of` defined in [`core.py`](https://github.com/HypothesisWorks/hypothesis/blob/hypothesis-python-6.3.2/hypothesis-python/src/hypothesis/strategies/_internal/core.py#L353) and re-exported in [`strategies/__init__.py`](https://github.com/HypothesisWorks/hypothesis/blob/hypothesis-python-6.3.2/hypothesis-python/src/hypothesis/strategies/__init__.py#L44) via [`__all__`](https://github.com/HypothesisWorks/hypothesis/blob/hypothesis-python-6.3.2/hypothesis-python/src/hypothesis/strategies/__init__.py#L103)

`hypothesis@6.3.3` has `one_of` defined in [`strategies.py`](https://github.com/HypothesisWorks/hypothesis/blob/hypothesis-python-6.3.3/hypothesis-python/src/hypothesis/strategies/_internal/strategies.py#L696). But! It is still re-exported via `core.py` in [`strategies/__init__.py`](https://github.com/HypothesisWorks/hypothesis/blob/hypothesis-python-6.3.3/hypothesis-python/src/hypothesis/strategies/__init__.py#L43) (which just has runtime-only import, which is treated as implicit re-export by mypy).

Related https://github.com/python/mypy/issues/7042

What are the possible solutions?

1. Enable `no-implicit-reexport` for `hypothesis, because this check has proven to be a good idea for libraries. Then I can fix all violations
2. Only fix this particular case without any other changes - it will be easier but less reliable

**Comment by Zac-HD** [comment]
> 1. Enable `no-implicit-reexport` for `hypothesis, because this check has proven to be a good idea for libraries. Then I can fix all violations

Given that you've volunteered to fix the violations, I'm happy to go with this!

(presuming that it doesn't require unexpectedly ugly code beyond the changed imports)

**Comment by sobolevn** [comment]
> Found 149 errors in 14 files (checked 95 source files)

😆 😭

**Comment by sobolevn** [comment]
I confirm that it works now: https://github.com/dry-python/returns/pull/847
