### ISSUE TITLE
Bug in hypothesis 6.7.0

### ISSUE THREAD

**Issue by ofekkir** [HypothesisWorks/hypothesis#2901]
Hi,

I suspect there might be a bug in hypothesis version '6.7.0':

https://github.com/HypothesisWorks/hypothesis/blame/master/hypothesis-python/src/hypothesis/strategies/_internal/numbers.py#L369

I suggest that code black always asserts.
What am I missing?
Thanks

**Comment by Zac-HD** [comment]
Have you actually observed a failure? This check is for https://en.m.wikipedia.org/wiki/Signed_zero

**Comment by ofekkir** [comment]
Thanks!
In a second look, I think it has to do with Pydantic hypothesis plugin, deployed in version 1.8

**Comment by Zac-HD** [comment]
For future reference, bug reports should always include a *complete reproducing example* (code which we can run to see whatever you saw), and an explanation of what you expected to see instead. 

Which would still bw useful in this cases - I have no idea what's going on!

**Comment by ofekkir** [comment]
Thanks, will do.
