### ISSUE TITLE
FR: Support strategies.data in example decorator

### ISSUE THREAD

**Issue by rhofour** [HypothesisWorks/hypothesis#2902]
The documentation clearly says this isn't supported yet, but it doesn't seem like it would be impossible to support.

Right now I have a test case that relies heavily on data and when I get a failure I see something like this:

```
Draw 1: {(0, 1), (0, 3), (2, 0), (4, 2), (3, 0), (2, 3), (0, 2), (9, 1)}
Draw 2: [0, 0, 0, 0, 0, 0, 0, 4]
Draw 3: [0, 2, 1, 1]
```

I expected I would be able to simply copy this into an example, but then learned this isn't possible. Is there any reason this couldn't be done?

**Comment by Zac-HD** [comment]
What would the user API look like?

It's *possible* to support something like this, but so far we haven't found it worth the complexity of implementation and explanation.

**Comment by rhofour** [comment]
I could see a few possibilities here for the API (using the same example failure from above):

```
@example(draws=[
  {(0, 1), (0, 3), (2, 0), (4, 2), (3, 0), (2, 3), (0, 2), (9, 1)},
  [0, 0, 0, 0, 0, 0, 0, 4],
  [0, 2, 1, 1]
]
```
I think this is the simplest way to do it, but it's not very readable and I imagine would get broken unnecessarily by changes the test like re-ordering two independent draws.

Instead, I think requiring the draws to have names and then using those in the API would lead to a better interface. Something like this:
```
@example(draws={
  "foo": {(0, 1), (0, 3), (2, 0), (4, 2), (3, 0), (2, 3), (0, 2), (9, 1)},
  "bar": [0, 0, 0, 0, 0, 0, 0, 4],
  "baz": [0, 2, 1, 1]
]
```

I can't speak to the complexity of implementation, but I'd think the explanation shouldn't be much more complicated than the existing behavior.

**Comment by Zac-HD** [comment]
- What if there's already an argument named `draws`?
- How do we convert the values to a `data` object with a callable `.draw()` method which returns each value in turn?  (OK, it's just fiddly)
- What about tests which draw values but reuse names?

Overall - I can see where you're coming from, but I think sticking with "use copy-paste to write a traditional example-based unit test for this" is still the best option overall.
