### ISSUE TITLE
The URL strategy does not include query strings nor fragments

### ISSUE THREAD

**Issue by P403n1x87** [HypothesisWorks/hypothesis#2908]
The RFC 3986 describes the query and fragment component of URIs. The URL provisional strategy doesn't seem to implement these components. It would be good to have these added as well for more comprehensive testing.

**Comment by Zac-HD** [comment]
That's the main reason it's provisional! We'd be happy to accept a PR adding fragments and/or query strings.

**Comment by paxcodes** [comment]
Should we keep this issue open since query strings still need to be generated?

**Comment by Zac-HD** [comment]
I'm happy to accept a PR adding query strings if you (or anyone else) wants to write one, but with the mentored sprints over I'm also happy to leave the provisional strategies as they are.
