### ISSUE TITLE
Make database-key customisation accessible downstream

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#2911]
There are some circumstances where the same test function should have varying Hypothesis database keys: in our own codebase, this includes `@pytest.mark.parametrize(...)`:

https://github.com/HypothesisWorks/hypothesis/blob/3d5761ed9254b39260f39cf52bad1293ccf733ab/hypothesis-python/src/hypothesis/extra/pytestplugin.py#L204-L207

where we are careful to distinguish by test ID, and stateful testing where there is a single shared wrapper function:

https://github.com/HypothesisWorks/hypothesis/blob/6b5167cf761f5f07e14d5448f4ffebbb98466e2d/hypothesis-python/src/hypothesis/stateful.py#L181-L184

and ultimately this comes down to [`hypothesis.internal.reflection.function_digest()`](https://github.com/HypothesisWorks/hypothesis/blob/4e036e3d27261e80e4fb5a8d83e9a0e6c01193eb/hypothesis-python/src/hypothesis/internal/reflection.py#L88-L91).

However, Hypothesis internals aren't the only place where this could be helpful - @Stranger6667 has also requested such an API for use with [Schemathesis](https://schemathesis.readthedocs.io/en/stable/), so that it can distinguish between API endpoints fuzzed with the same function.

I'm inclined to keep this as a private/internal API, and just convert the current single-bytestring attribute into a list-of-bytestrings which can be appended to.  Alternatively, we could just say that Schemathesis should overwrite the attribute (perhaps concatenating any previous value), which would be totally backwards compatible as a non-change.  Thoughts?

**Comment by Stranger6667** [comment]
Indeed, keeping this API as a private one would be sufficient! Schemathesis already uses some internal Hypothesis attributes, so it should be alright to use this one as well. Thank you for the provided details :)
