### ISSUE TITLE
Re-using Hypothesis strategies to generate "one-off" test/example data?

### ISSUE THREAD

**Issue by gwerbin** [HypothesisWorks/hypothesis#2912]
Hello Hypothesis devs! Thank you for the active development on such an incredibly useful tool!

I am writing a test suite that makes extensive use of Hypothesis for generating fake database data. The test suite is divided into sections:

1. Purely-functional unit tests & small integration tests that use `unittest.mock` to return data without hitting a real database
2. An end-to-end test that uses a local database server, which is populated with fake data for the test suite to use

Section 1 depends extensively on Hypothesis, which makes it super easy to make assertions about invariants and other properties of the system.

Section 2 could theoretically use Hypothesis to repeatedly generate new fake data, re-populate the database for every test, and use its usual shrinkage and search-for-failure mechanisms. But because some of the end-to-end testing will eventually involve larger chunks of data, I don't want to make a slow, SSD-abusing test suite if I can avoid it.

However, I *would* like to take advantage of all the Hypothesis strategies I already wrote for the functional tests, in order to generate a few sets of "static" fake data that I can then bundle with the test suite. Is it possible to somehow generate a single draw from an Hypothesis strategy "off-line"?

As a workaround, I could write a script that runs a unittest test, saves a single generated Hypothesis example to disk, then immediately triggers a failure. But I'm not sure if this is even sensible with respect to whatever algorithms Hypothesis uses internally for example generation.

**Comment by Zac-HD** [comment]
:wave: glad you're enjoying it!  (https://stackoverflow.com/questions/tagged/python-hypothesis is also good for questions)

Three decent options:

- Just make end-to-end tests faster, e.g. by turning down the `max_examples` setting and running the database in memory (or on a RAMdisk).
- Write the test as usual, and append the generated data to a list / save it to disk / etc from inside the test body
- Use the `.example()` method of strategies to generate some examples interactively in a REPL.

I am a big fan of shrinking and the various heuristics - as well as integrations such as https://hypofuzz.com/ - so I'd try to get the first working, and then use the second approach (which you mention as a workaround) if that's impractical.

**Comment by gwerbin** [comment]
Thanks for the quick reply! I will probably end up doing both, and if I come up with a tidy reusable way of generating static/one-off examples I'll update this reply with a Gist showing how I did it.
