### ISSUE TITLE
Coroutine tests do not work

### ISSUE THREAD

**Issue by lordi** [HypothesisWorks/hypothesis#292]
I've tried the solution mentioned in #52 but without success, is this a regression?

The code below raises the following exception:

```python-traceback
hypothesis.internal.conjecture.data.StopTest: 11
```

Test case:

```python
import functools
import unittest
from unittest import TestCase

import aiohttp
import asyncio
from hypothesis import given
import hypothesis.strategies as st


class DummyTestCase(TestCase):

    timeout = 5

    def setUp(self):
        self.loop = asyncio.new_event_loop()
        asyncio.set_event_loop(self.loop)

    def tearDown(self):
        self.loop.close()

    def execute_example(self, f):
        coro = asyncio.coroutine(f)
        future = asyncio.wait_for(coro(),
                                  timeout=self.timeout)
        return self.loop.run_until_complete(future)

    @given(st.text())
    def test_foo(self, x):
        r = yield from aiohttp.request(x, 'http://localhost')
        assert r.status == 200, 'yay!'

if __name__ == '__main__':
    unittest.main()
```

**Comment by kxepal** [comment]
Indeed it so. As workaround, you can stick with more "classic" scheme to run coroutine-tests:
```
    @given(st.text())
    def test_foo(self, meth):
        @asyncio.coroutine
        def go():
            r = yield from aiohttp.request(meth, 'http://localhost')
            assert r.status == 200, r.status
        return self.loop.run_until_complete(go())
```

This will works fine, but require a bit more boilerplate for each test.

**Comment by lordi** [comment]
Thanks for the workaround, and thanks for hypothesis in general :)

**Comment by DRMacIver** [comment]
Hm. I think the root cause of the problem is that StopTest is inheriting from BaseException rather than Exception (to make it harder to accidentally catch) and that the asyncio loop does not correctly propagate this back. See https://github.com/python/asyncio/pull/305

So you're right that it's a regression, but I'm not sure what to do about it. The best solution is probably going to be to come up with a revised version of the execute_example implementation that handles this case. I'm not that familiar with asyncio, but I'll have a think about how that might best work.

**Comment by DRMacIver** [comment]
The following execute\_example change should work:

```python
    def execute_example(self, f):
        error = None

        def g():
            nonlocal error
            try:
                yield from f()
            except BaseException as e:
                error = e
        coro = asyncio.coroutine(f)
        future = asyncio.wait_for(coro(),
                                  timeout=self.timeout)
        self.loop.run_until_complete(future)
        if error is not None:
            raise error
```

Given that this is fixable, my inclination is to claim that the problem is on the asyncio end and not do anything on the Hypothesis side to try to work around its behaviour. I'm open to compelling arguments to the contrary though.

**Comment by DRMacIver** [comment]
Hm. Now that solution isn't working for me. I could have sworn it did, but maybe I did something wrong. Sorry.

**Comment by kxepal** [comment]
It's quite hackyto use in real world in anyway  (:
The https://github.com/python/asyncio/pull/305 patches indeed solves the issue. I'll give them ping back about Hypothesis use case.

**Comment by DRMacIver** [comment]
OK, here's a version that *actually* works without the stupid mistakes I made in the above:

```python
    def execute_example(self, f):
        error = None

        def g():
            nonlocal error
            try:
                x = f()
                if x is not None:
                    yield from x
            except BaseException as e:
                error = e
        coro = asyncio.coroutine(g)
        future = asyncio.wait_for(coro(),
                                  timeout=self.timeout)
        self.loop.run_until_complete(future)
        if error is not None:
            raise error
```

**Comment by Zac-HD** [comment]
#1343 added a mechanism for test runners to handle this automatically, as in python-trio/pytest-trio#44.

Since the `execute_example` form does still work, anyone who would like a pytest-style rather than unittest-style experience is encouraged to contribute a similar feature to e.g. `pytest-asyncio`.
