### ISSUE TITLE
Should hypothesis.extra.numpy.arrays accept SearchStrategy[int] type for shape parameter?

### ISSUE THREAD

**Issue by rjmorris** [HypothesisWorks/hypothesis#2935]
I'm updating dependencies for an old project, and I'm now getting a mypy error for the following decorator:

```
import hypothesis.extra.numpy
import hypothesis.strategies as st
from hypothesis import given

@given(hypothesis.extra.numpy.arrays(
    hypothesis.extra.numpy.scalar_dtypes(),
    st.integers(min_value=0, max_value=100)
))
def test_check_type(arr):
    ...
```

The error is:

```
Argument 2 to "arrays" has incompatible type "SearchStrategy[int]";
expected "Union[int, Tuple[int, ...], SearchStrategy[Tuple[int, ...]]]"
```

Looking at the definition of `arrays()` in the hypothesis source code, I see that the type hint for the `shape` parameter is `Union[int, Shape, st.SearchStrategy[Shape]]`, where `Shape` is defined as `Tuple[int, ...]`. And the type hint for the return value of `st.integers()` is `SearchStrategy[int]`, so I believe the error message mypy reports is consistent with the type hints.

However, `arrays()` runs fine when a `SearchStrategy[int]` is provided as the `shape` parameter. The documentation for the `shape` parameter says:

> shape may be an integer >= 0, a tuple of such integers, or a strategy that generates such values.

The phrase "such values" in "a strategy that generates such values" is a little ambiguous. Does it mean:

> a strategy that generates a tuple of such integers

or

> a strategy that generates an integer > 0 or a tuple of such integers

The first is what the type hint in the source code implies, but the second is consistent with the runtime behavior and was my interpretation before reading the source code.

I suspect the type hint for the `shape` parameter is incorrect and that `SearchStrategy[int]` should be added, so it would look like this:

```
shape: Union[int, Shape, st.SearchStrategy[int], st.SearchStrategy[Shape]],
```

Or is my assessment incorrect? Are the type hints correct but my code needs to be updated?

**Comment by rsokl** [comment]
Your assessment is correct; the proper type hint does seem to be:

```python
shape: Union[int, Shape, st.SearchStrategy[int], st.SearchStrategy[Shape]],
```

I will push a patch for this.

**Comment by rjmorris** [comment]
Great, thanks for fixing this!

**Comment by rsokl** [comment]
Thanks for taking the time to write up the issue!
