### ISSUE TITLE
Ability to measure deadlines using CPU cycles instead of wall time

### ISSUE THREAD

**Issue by crypdick** [HypothesisWorks/hypothesis#2944]
Depending on traffic, it looks like Bitbucket's CI allocates different amount of CPU cycles to users. This results in large variability in wall times for the same code, resulting in flaky tests, and we're constantly pushing hotfixes to increase deadlines and get tests passing again.

It would be great if we could use a more robust unit of measure than absolute wall time.

**Comment by Zac-HD** [comment]
Sure, that would be great - is it even possible to get this data foe Python though?

More generally, I'd recommend setting `deadline=None` in your CI; it's clearly causing more trouble in flaky tests than it's worth. You can always run with deadlines enabled locally to check for unexpectedly slow tests!

**Comment by crypdick** [comment]
You might be right. As for getting this data, this package may be a good start, although it seems inactive: https://github.com/paulsmith/hwcounter

**Comment by Zac-HD** [comment]
Unfortunately checking CPU counters will have the same problem on shared hosts - you'd have to be on a real virtual machine before that helped... at which point the "wall-clock" only counts your own usage anyway.

I think the best solution is to set `deadline=None` on hosts with such variable performance, using settings profiles.
