### ISSUE TITLE
[General Quesion] `sampled_from` chooses the same Enum element every time

### ISSUE THREAD

**Issue by segevmalool** [HypothesisWorks/hypothesis#2945]
Hello!

I'm using `sampled_from` to sample from an Enum, and it seems to choose the same element every time. This behavior does make sense based on the shrinking strategy documented... 

I would like to increase the testing scope to include multiple Enum values. How can I do this?

Solutions attempted:
1. Specify phases settings omitting Phase.shrink
2. Converting enum to list

**Comment by segevmalool** [comment]
A similar thing happens with `from_type` with a subclass of pydantic `BaseModel`. The Enum value seems to always be the same!!!

**Comment by rsokl** [comment]
```python
from enum import Enum

from hypothesis import given
import hypothesis.strategies as st

class Color(Enum):
    RED = 1
    GREEN = 2
    BLUE = 3

@given(st.sampled_from(Color))
def test(x):
    print(x)
```

```python
>>> test()
Color.RED
Color.BLUE
Color.RED
Color.GREEN
```

**Comment by segevmalool** [comment]
Similar to your example, but executing with pytest. @rsokl 

I will mock up a minimal example.

**Comment by segevmalool** [comment]
Oh now that I am creating this example, this might be related to my use of `Union` from typing...

**Comment by rsokl** [comment]
Feel free to open a new issue if you feel that the documentation or behavior of the library was misleading here.
