### ISSUE TITLE
[Bug?] `Sequence[int]` produces unexpected `binary` strategy

### ISSUE THREAD

**Issue by mristin** [HypothesisWorks/hypothesis#2950]
Hi,
Please apologize if this bug has been already reported (or maybe is not even a bug, but a misunderstanding on my side).

Having installed Hypothesis 6.10.1, I try:

```
>>> import hypothesis.strategies
>>> from typing import Sequence
>>> strategy = hypothesis.strategies.from_type(Sequence[int])

>>> strategy
one_of(binary(), lists(integers()))

>>> strategy.example()
b'\x00'
>>> strategy.example()
b''
>>> strategy.example()
b'\x00'
>>> strategy.example()
[0]
>>> strategy.example()
[0]
```

Whenever a binary string is generated, the downstream code breaks as it expects a sequence of integers.

The issue does not occur if I use `List[int]` instead.

**Comment by mristin** [comment]
I implemented a quickfix in https://github.com/mristin/icontract-hypothesis/pull/36. Perhaps it can help you narrow down the cause.

**Comment by Zalathar** [comment]
According to #2269 this is intended and correct.

Byte strings are `Sequence`s, and their elements are integers, so code that accepts `Sequence[int]` should be able to handle them.

**Comment by Zac-HD** [comment]
Strange though it might seem, `b"\x00\x01"` is in fact a sequence of integers, so I consider this the correct behaviour.

I do wish that the element were length-one bytestrings, by analogy to unicode strings, but these are the semantics that the language has given us!  I think it's reasonable for you to exclude this in icontract, but I think it's important for Hypothesis to remain consistent with `mypy` on this.

You can check that elements of a bytestring are integers (in the range [0 .. 255] of course) with e.g. `b'abc'[1] == 98`, or `list(b'Hello, World!') == [72, 101, 108, 108, 111, 44, 32, 87, 111, 114, 108, 100, 33]`.  Or with Mypy:

```python
from typing import Sequence

x: Sequence[int] = [1, 2, 3]
y: Sequence[int] = b"This passes too."
z: Sequence[int] = [1.0]  # error: List item 0 has incompatible type "float"; expected "int"
```

**Comment by mristin** [comment]
Hi @Zalathar and @Zac-HD ,
Thanks a lot for clarification! This makes all sense now :-).
