### ISSUE TITLE
[Bug?] `.filter` ignored on `just` strategy

### ISSUE THREAD

**Issue by mristin** [HypothesisWorks/hypothesis#2964]
Hi,
I hope this has not been reported before. I checked the issues and read the [changelog] ~but could not find anything related~ and this seems to be related to issue https://github.com/HypothesisWorks/hypothesis/issues/2036.

[changelog]: https://hypothesis.readthedocs.io/en/latest/changes.html

I noticed an unexpected difference in the behavior when `.filter` is applied on `just` strategy between Hypothesis 5.43.3 and Hypothesis 6.12.0 (the former ran on my machine, while the remote CI machine had 6.12.0 installed).

With Hypothesis 5.43.3 (expected behavior):
```python
import hypothesis.strategies
import hypothesis.strategies._internal.strategies

strategy = hypothesis.strategies.just(1).filter(lambda x: x > 10)
assert str(strategy) == "just(1).filter(lambda x: x > 10)"
assert type(strategy) == hypothesis.strategies._internal.strategies.FilteredStrategy
```

With Hypothesis 6.12.0 (unexpected behavior):

```python
import hypothesis.strategies
import hypothesis.strategies._internal.misc

strategy = hypothesis.strategies.just(1).filter(lambda x: x > 10)
assert str(strategy) == "just(1)"
assert type(strategy) == hypothesis.strategies._internal.misc.JustStrategy
```

This bug (?) is relevant for [icontract-hypothesis] when we test instance methods automatically where pre-conditions need to be applied on `self`. I'd expect the health check to be raised rather than the pre-conditions to be silently ignored.

[icontract-hypothesis]: https://github.com/mristin/icontract-hypothesis

**Comment by Zac-HD** [comment]
This changed in #2688, [version 5.43.7](https://hypothesis.readthedocs.io/en/latest/changes.html#v5-43-7).  The preconditions *aren't* silently ignored - so our bug is limited to an incorrect `__repr__` for `just()` strategies, which I'll fix momentarily.  The return type is not part of our public/stable API though - note the `_internal`! - and so to keep your check working you'll need to add a special case for `_transformations` on a `SampledFromStrategy`.

**Comment by mristin** [comment]
Thanks a lot, @Zac-HD!

Just to confirm: I tried this in my Python console with Hypothesis 6.12.0 and indeed, the filter is applied:

```
>>> import hypothesis.strategies as st
>>> st.just(1).filter(lambda x: x > 10)
just(1)
>>> strat = st.just(1).filter(lambda x: x > 10)
>>> strat.example()
Traceback (most recent call last):
  ...
hypothesis.errors.Unsatisfiable: Unable to satisfy assumptions of hypothesis example_generating_inner_function.
```
