### ISSUE TITLE
`min_size` and `max_size` for tuple

### ISSUE THREAD

**Issue by sayandip18** [HypothesisWorks/hypothesis#2967]
This is a feature proposal.

`hypothesis.strategies.lists` takes `min_size` and `max_size` arguments. But, `hypothesis.strategies.tuples` does not take any such arguments, making it difficult to generate tuples of varying lengths. Having these arguments for tuples will make it easier.

**Comment by Zac-HD** [comment]
`tuples()` is designed for fixed-length tuples where you have a different strategy at each index (a "product type").

To generate variable-length tuples where all elements come from the same strategy, use `lists(...).map(tuple)`.
