### ISSUE TITLE
`test_advanced_integer_index_can_generate_any_pattern` seen running for several minutes

### ISSUE THREAD

**Issue by Zalathar** [HypothesisWorks/hypothesis#3010]
Spotted in the merge build log:

```
============================= slowest 20 durations =============================
668.54s call     hypothesis-python/tests/numpy/test_gen_data.py::test_advanced_integer_index_can_generate_any_pattern
27.09s call     hypothesis-python/tests/numpy/test_gen_data.py::test_can_generate_data_compound_dtypes
```

Wonder if that's a CI glitch, or something weird on our end.

_Originally posted by @Zalathar in https://github.com/HypothesisWorks/hypothesis/pull/3007#issuecomment-854673084_

**Comment by Zalathar** [comment]
Looking at the actual test, we have `deadline=None` and a `find_any` nested within `@given`, so occasionally taking a long time seems quite plausible if the outer layer picks something that's hard for the inner layer to satisfy.

https://github.com/HypothesisWorks/hypothesis/blob/ffb2d41e80ceae280f4d978e1dd4b92e20b39efe/hypothesis-python/tests/numpy/test_gen_data.py#L1025-L1048

**Comment by rsokl** [comment]
Ouch.. that's on me. Although I am quite surprised that it can take _ten minutes_ for the test to complete. I will try to find time to improve this.

**Comment by Zalathar** [comment]
> Ouch.. that's on me. Although I am quite surprised that it can take _ten minutes_ for the test to complete. I will try to find time to improve this.

It's a rare occurrence, and in this case it happened under coverage which makes things even slower.

We currently don't have a split between cover/nocover for numpy tests. I've already been thinking about introducing one, since they're pretty highly represented on the “slowest 20 tests” list, and since we don't have such a split there are surely a bunch of numpy tests that aren't needed for coverage.

**Comment by Zalathar** [comment]
(I just ran it locally a few times, and anecdotally it mostly took <1 sec, and then on one occasion took 150 seconds. I'm trying to get this to happen again so that I can get it to print out a seed to reproduce this reliably.)

**Comment by Zalathar** [comment]
OK, I found a seed that makes the test take unusually long (95 seconds for me):

```python
@seed(307021230796026307077224773369287953152)
```

The troublesome target in this case seems to be:

```python
target = np.array([[5, 0], [8, 6]])
```

**Comment by Zalathar** [comment]
From printing out the target in every case, it seems that most examples are looking for `np.array([0])`, with a few slightly-less trivial targets mixed in. It's unusual for one to be as complicated as `[[5, 0], [8, 6]]`.

**Comment by rsokl** [comment]
> We currently don't have a split between cover/nocover for numpy tests. I've already been thinking about introducing one

I think that this is a good idea and would be happy to help when I can scrounge up some time (just finished moving, so things are a bit hectic right now)

**Comment by Zac-HD** [comment]
I'd consider adding `@example(...)` cases to ensure we get a good variety of shapes.

We can probably also make this *way* faster for the hard cases with careful use of `target()`.
