### ISSUE TITLE
Pass strategies to Hypothesis Pandas column name

### ISSUE THREAD

**Issue by safwan-samsudeen** [HypothesisWorks/hypothesis#3012]
Consider a test case where you test a function which splits the column names of a dataframe based on underscores, and capitalizes each word. 

To randomize the column name, you currently have to do this.
```py
from hypothesis import given, strategies as st
from hypothesis.extra.pandas import data_frames, column

from src import format_column_names

@given(df=dataframes([
    column(name=st.from_regex('[A-Z_]').example(), elements=st.integers())
]))
def test_format_column_names(df):
    print(df.columns)
    result = format_column_names(df)
    # Test that the result is as expected...
```

This doesn't seem to work - the column name is always a constant value.
```
$ py.test - s
======================================== test session starts =========================================
platform darwin -- Python 3.8.10, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /Users/safwan/Dropbox/Projects/rama-reporting-automation
plugins: anyio-2.2.0, hypothesis-6.13.11
collected 1 item                                                                                     

test.py Index(['N'], dtype='object')
Index(['N'], dtype='object')
Index(['N'], dtype='object')
Index(['N'], dtype='object')
Index(['N'], dtype='object')
Index(['N'], dtype='object')
Index(['N'], dtype='object')
Index(['N'], dtype='object')
Index(['N'], dtype='object')
Index(['N'], dtype='object')
Index(['N'], dtype='object')
...
```

I think Hypothesis kind of caches the DF, so the column names aren't recreated every time. What I ideally want is for this to to produce dataframes with different column names each time, created from the strategy. Like this:
```py
from hypothesis import given, strategies as st
from hypothesis.extra.pandas import data_frames, column

from src import format_column_names

@given(df=dataframes([
    column(name=st.from_regex('[A-Z_]'), elements=st.integers()) # Pass in the strategy instead of an example.
]))
def test_format_column_names(df):
    print(df.columns)
    result = format_column_names(df)
    # Test that the result is as expected...
```

**Comment by Zac-HD** [comment]
Yep, that's because the `.example()` method is only run once at import-time (which emits a warning FYI; it's only meant for interactive use).

Instead, you should probably be using `@st.composite` to define a custom strategy:

```python
@st.composite
def dataframes_with_name_format(draw, names):
    col = column(name=draw(names), elements=st.integers())
    return draw(dataframes([col])

@given(df=dataframes_with_name_format(st.from_regex('[A-Z_]')))
def test_format_column_names(df): ...
```

**Comment by safwan-samsudeen** [comment]
No, I meant this to be a feature request. Sorry, this is my first GitHub issue, not sure about how to label it and all that.

**Comment by Zac-HD** [comment]
Ah, my apologies for the misunderstanding.

Unfortunately supporting strategies for `name` instead of the `@st.composite()`-or-`.flatmap(...)` workaround would cause several problems (e.g. uniqueness of column names).  It would also violate our style guide which mandates that [arguments should not be "a value or a strategy for generating that value"](https://github.com/HypothesisWorks/hypothesis/blob/master/guides/api-style.rst#argument-handling), and this isn't a common enough request to justify the extra boilerplate for the fixed-column-names usecase.

So I am also sorry to turn down your feature request :broken_heart:
