### ISSUE TITLE
Generating custom objects from their type hints with constraints

### ISSUE THREAD

**Issue by davidmascharka** [HypothesisWorks/hypothesis#3014]
I've been doing a deep dive in trying to generate some objects based on their type hints and haven't found a really satisfactory way to do this. Here's a simplified version of a problem that I care about:

I have a `CustomList` class whose length and dtype are specifiable, for type hinting. The idea is that I can have type checking verify that lists are the same lengths and compatible dtypes when I want to perform some operation on them, and I may not have a known length ahead of time (else I'd use a `Tuple` with a concrete number of elements). I don't want to use a variadic `Tuple[dtype, ...]` because that won't let me check the lengths, so I created a custom class:

``` python
from typing import cast, Any, Generic, Iterator, TypeVar


LengthT = TypeVar("LengthT")
DtypeT = TypeVar("DtypeT")

class CustomList(list, Generic[LengthT, DtypeT]):
    """Custom list class which can express its length."""
    def __new__(cls, *args: Any, **kwargs: Any) -> "CustomList":
        return cast(CustomList[LengthT, DtypeT], list(*args, **kwargs))

    def __iter__(self) -> Iterator["CustomList"]:
        return cast(Iterator["CustomList"], super().__iter__())
```

When I use it, I might have some object that looks like:

``` python
@attr.s
class Directory:
    student_names: CustomList[Literal["NUM_STUDENTS"], str] = attr.ib()
    student_addresses: CustomList[Literal["NUM_STUDENTS"], str] = attr.ib()
    faculty_names: CustomList[Literal["NUM_FACULTY"], str] = attr.ib()
    faculty_offices: CustomList[Literal["NUM_FACULTY"], int] = attr.ib()
```

Here my type checker is able to verify that my `student_names` and `student_addresses` are the same length, and my `faculty_names` and `faculty_offices` are the same length. What I really want to be able to do is have Hypothesis automatically generate a `Directory` object for me with `st.builds`. I've gotten to a solution that works well when I have known-length lists, but that particular solution doesn't work for the above case where I have some string literal length. I've also got a working solution for this case above, but it's particularly nasty, and I was wondering whether you might have ideas for improvement.

### Solution for known-length lists
Registering a strategy for `CustomList` isn't too difficult. I came up with:
``` python
@st.composite
def custom_list_strategy(draw, annotation) -> CustomList:
    """Construct a CustomList from a type annotation."""
    length, dtype = annotation.__args__
    length = draw(st.from_type(length))  # Literal[number] -> number; e.g. Literal[7] -> 7
    return draw(st.lists(st.from_type(dtype), min_size=length, max_size=length))

st.register_type_strategy(CustomList, custom_list_strategy)
```

which works great for cases like the following:

``` python
@attr.s
class Thing:
    first: CustomList[Literal[3], int] = attr.ib()
    second: CustomList[Literal[7], float] = attr.ib()


>>> st.from_type(Thing).example()
Thing(first=[0, 0, 0], second=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
```

However, it fails when I don't have a number for the list length (e.g. `CustomList[Literal["NUM_STUDENTS"], str]`) since we resolve `Literal["NUM_STUDENTS"] -> "NUM_STUDENTS"` and get an `InvalidArgumentException` in the `st.lists()` call.

### Solution for arbitrary lists
This is what I've come up with as a "solution" which technically works but is pretty gnarly and undoubtedly error-prone:

``` python
CUSTOM_LIST_LENGTHS = {}

def generate_named_lengths(attrs_class):
    """Generate literal values for the named type-annotated lengths in the provided object.
    
    This function must be used to populate a global state dictionary before custom objects
    are generated. This state dictionary _must_ be imported from this file and mutated to work.
    
    NOTE: This function has side-effects on the global CUSTOM_LIST_LENGTHS dictionary
    """
    for annotation in attrs_class.__annotations__.values():
        if "CustomList" in str(annotation.__origin__):  # it's our custom type
            length, _ = annotation.__args__  # dtype unused
            length = length.__args__[0]  # Literal["NAME"] -> "NAME"
            if length not in CUSTOM_LIST_LENGTHS:
                CUSTOM_LIST_LENGTHS[length] = random.randint(0, 100)  # TODO: make configurable
    return CUSTOM_LIST_LENGTHS

@st.composite
def custom_list_strategy(draw, annotation) -> CustomList:
    """Construct a CustomList from a type annotation."""
    length, dtype = annotation.__args__
    length = draw(st.from_type(length))
    if isinstance(length, str):
        length = CUSTOM_LIST_LENGTHS[length]
    return draw(st.lists(st.from_type(dtype), min_size=length, max_size=length))

st.register_type_strategy(CustomList, custom_list_strategy)
```

Here the process is to first provide `generate_named_lengths` the object to generate, which mutates our global `CUSTOM_LIST_LENGTHS` dictionary; this is then used in the `custom_list_strategy`. We can't fill the dictionary directly from the strategy or Hypothesis throws a `Flaky` error. This does work:

``` python
>>> generate_named_lengths(Directory)
{'NUM_STUDENTS': 3, 'NUM_FACULTY': 28}

>>> st.from_type(Directory).example()
Directory(
    student_names=['0', '', ''], 
    student_addresses=['', '', ''], 
    faculty_names=['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''], 
    faculty_offices=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
)
```

but it's quite horrible. For one, we have to pre-populate the dictionary `CUSTOM_LIST_LENGTHS` and then we also have to remember to clear it and re-populate, else we'll keep using the same number of elements. I was thinking I could at least wrap this in a decorator, but I'm wondering whether you have better ideas on how we might be able to automatically generate compatible objects based on some constraints like this. This is all in effort to reduce boilerplate where we've already specified the type annotations and don't want to create a custom strategy for every new object (e.g. `directory_strategy`, `class_strategy`, `graduating_class_strategy`, etc. which would all be constructible with just a `CustomList` strategy and `builds()`).

Thank you!

**Comment by Zac-HD** [comment]
I think you're after [`st.shared()`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.shared), which gives us a nice per-test-case cache automatically:

```python
@st.composite
def custom_list_strategy(draw, annotation) -> CustomList:
    """Construct a CustomList from a type annotation."""
    length_literal, dtype = annotation.__args__
    length = length_literal.__args__[0]  # Literal["NAME"] -> "NAME"
    if not isinstance(length , int):
        length = draw(st.shared(st.integers(0, 10), key=length)
    return draw(st.lists(st.from_type(dtype), min_size=length, max_size=length))

**Comment by davidmascharka** [comment]
Hmm I knew I had looked at `st.shared` in the past and thought there was some fail-case for it in my usage, but after a quick pass it seems to actually be working perfectly. I'm trying to make sure that I can generate mutually-consistent shapes across different objects; for example:

``` python
@attr.s
class OneThing:
    some_attrribute: CustomList[Literal["FOO"], int] = attr.ib()
    another_attribute: CustomList[Literal["BAR"], float] = attr.ib()

@attr.s
class AnotherThing:
    more_attributes: CustomList[Literal["FOO"], float] = attr.ib()
    one_more: CustomList[Literal["BAZ"], int] = attr.ib()
```

where I'm guaranteed that when I generate instances of `OneThing` and `AnotherThing` all of the lists typed as length-FOO will be the same. Are there usages where this wouldn't be the case? Perhaps alternatively, where can I read more about how this is working? This is fantastic!

**Comment by Zac-HD** [comment]
Yeah, that will work.  [Here's the implementation](https://github.com/HypothesisWorks/hypothesis/blob/670c3e6096d889d983e4233f96f9464fc032aef9/hypothesis-python/src/hypothesis/strategies/_internal/shared.py#L36-L43) - it just ensures that there's a per-test-case dict of shared items, draws the first time for each key, and looks it up in the dict thereafter.

**Comment by davidmascharka** [comment]
Would it be possible to place constraints on the generation? Say I want to force `FOO` to be a length of 7 in one of my tests, would that be something I can do here?

**Comment by Zac-HD** [comment]
I can't think of a convenient way to do so - this sounds like a case for writing some custom functions-which-return-strategies, and passing `FOO=st.just(7)` to them.

**Comment by davidmascharka** [comment]
For anybody interested, the solution to my problem ended up being to modify my original strategy to include constraints:

``` python
def custom_list_strategy(draw, annotation, constraints={}) -> CustomList:
    ...
    if length in constraints:
        length = constraints[length]
    else:
        length = st.shared(st.integers(0, 100), key=length)  # if you want custom behavior, add constraints
    length = draw(length)
    # ...
```

combined with a function that returns a strategy:

``` python
def constrained_list_strategy(
    annotation, constraints: Mapping[Hashable, Union[int, st.SearchStrategy]]
) -> st.SearchStrategy:
    constraints = {
        name: st.shared(value, key=name) if isinstance(value, st.SearchStrategy) else st.just(value)
        for name, value in constraints.items()
    }
    return custom_list_strategy(annotation, constraints=constraints)
```

then we add a context-manager that sets/resets the strategy used:

``` python
class set_constraints(ContextDecorator):
    def __init__(self, constraints):
        self._constraints = constraints

    def __enter__(self):
        st.register_type_strategy(
            CustomList, functools.partial(constrained_list_strategy, constraints=self._constraints)
        )
        return self

    def __exit__(self):
        st.register_type_strategy(CustomList, custom_list_strategy)
```

then we can do:
``` python
with set_constraints({"FOO": 7}):
    # do stuff

# or
@set_constraints({"FOO": st.integers(3, 9)})
@given(st.from_type(OneThing), st.from_type(AnotherThing))
def test_stuff():
    # whatever
```
