### ISSUE TITLE
how to resolve the error when using tmpdir fixture which is function scoped?

### ISSUE THREAD

**Issue by siraj-samsudeen** [HypothesisWorks/hypothesis#3017]
I am very new to Hypothesis and PBT. I have a simple class called TableLogger which takes either a list, dict or a pandas dataframe and logs it as a CSV. I am just pasting a part of the code which test a simple list. I am trying to use hypothesis here, but I get error about function-scoped fixture - I guess it is because of the `use_temp_dir` fixture which by default is function-scoped and this can't be changed as per pytest documentation. 

May I understand the wisdom behind this error and what is the right way to proceed to make it work?

```py
class TestTableLogger:
    @pytest.fixture(autouse=True)
    def use_temp_dir(self, tmpdir):
        os.chdir(tmpdir)
        yield

    @pytest.fixture()
    def logger(self, use_temp_dir, scope='class'):
        return pdu.TableLogger(prefix='test')

    @given(input=st.lists(st.integers()))
    def test_log_list_with_hypothesis(self, logger, input):
        logger.log(input)

    def test_log_list(self, logger):
        input = [1, 2, 3]
        expected_output = pd.DataFrame({
            'Column Name': [1, 2, 3],
        })
        result_file_name = logger.log(input, 'list')
        pdt.assert_frame_equal(pd.read_csv(result_file_name), expected_output)


class TableLogger:
    def __init__(self, prefix=None, log_dir='logs'):
        self.prefix = prefix + "_" if prefix else ""
        self.log_dir = log_dir or '.'
        try:
            os.mkdir(self.log_dir)
        except FileExistsError:
            pass

    def log(self, value, file_name):
        if isinstance(value, list):
            value = pd.DataFrame(value, columns=['Column Name'])
        elif isinstance(value, dict):
            value = pd.DataFrame({
                'Column Name': value.keys(),
                'Value': value.values()
            })
        elif not isinstance(value, pd.DataFrame):
            raise TypeError(
                f'Expected value to be a list, dict, or a DataFrame, found "{type(value)}" instead')
        file_name_full = f'{self.log_dir}/{self.prefix}{file_name}.csv'
        value.to_csv(file_name_full, index=False)
        return file_name_full

```

here is the error we get
`hypothesis.errors.FailedHealthCheck: pandas_utils_test.py::TestTableLogger::test_log_list_with_hypothesis uses the 'logger' fixture, which is reset between function calls but not between test cases generated by `@given(...)`.  You can change it to a module- or session-scoped fixture if it is safe to reuse; if not we recommend using a context manager inside your test function.`

After reading the links given in the error message, I tried this but I get the same error - can someone explain why?
```py
@pytest.fixture(autouse=True, scope='class')
def use_temp_dir(self, tmpdir_factory):
    os.chdir(tmpdir_factory.mktemp('test_table_logger'))
    print(os.getcwd())
    yield
```

**Comment by Zac-HD** [comment]
Perhaps one of your other fixtures is function-scoped, e.g. `logger` via `tmpdir`?

**Comment by Zalathar** [comment]
> ```python
> 
>     @pytest.fixture()
>     def logger(self, use_temp_dir, scope='class'):
>         return pdu.TableLogger(prefix='test')
> ```

It looks like this `scope='class'` is supposed to be inside the `@pytest.fixture()`, not inside the parameters of `logger`.

So you might have accidentally ended up with `logger` being a function-scoped fixture.

**Comment by siraj-samsudeen** [comment]
> Perhaps one of your other fixtures is function-scoped, e.g. `logger` via `tmpdir`?

thanks Zac. yes tmpdir is function-scoped and as per pytest, it can't be changed to class or session scope unless I am willing to rewrite the fixture myself which I am not yet confident about. Is there any way to get around this?

**Comment by siraj-samsudeen** [comment]
> > ```python
> >     @pytest.fixture()
> >     def logger(self, use_temp_dir, scope='class'):
> >         return pdu.TableLogger(prefix='test')
> > ```
> 
> It looks like this `scope='class'` is supposed to be inside the `@pytest.fixture()`, not inside the parameters of `logger`.
> 
> So you might have accidentally ended up with `logger` being a function-scoped fixture.

Sorry Zalathar,  yes it was a mistake from our side, unintentional. I moved the scope declaration to the fixture, but then the problem is still there since the tmpdir fixture is function-scoped.

**Comment by Zac-HD** [comment]
I think that in this case, you can safely ignore the `function_scoped_fixture` health check.
