### ISSUE TITLE
RFE: move from `codemod` to `fastmod`

### ISSUE THREAD

**Issue by kloczek** [HypothesisWorks/hypothesis#3024]
Looks like `hypothesis` still is using `codemod`.
I hade some issues with packaging of that module and fount that it is archived and no longer maintained.
I've contacted former maintainer of that module over email I just received answer on my question about status of that module. He told me that `codemod` is no longer maintained and whatever still is using it should migrate to use `fastmod` https://github.com/facebookincubator/fastmod.

**Comment by Zac-HD** [comment]
Looks like Facebook / Instagram use the same term for unrelated tools: Hypothesis is using the [LibCST](https://github.com/Instagram/LibCST) package, not the `codemod` which preceeds `fastmod`.
