### ISSUE TITLE
Getting a "Flaky: Inconsistent data generation! Data generation behaved differently...  error"

### ISSUE THREAD

**Issue by mattip** [HypothesisWorks/hypothesis#3028]
In trying to get pypy + windows64 + numpy to pass tests on the conda feedstock.
https://github.com/conda-forge/numpy-feedstock/pull/238 we consistently see this error. It starts at the ` numpy\core\tests\test_numeric.py::TestClip::test_clip_property` [test](https://github.com/numpy/numpy/blob/main/numpy/core/tests/test_numeric.py#L2337) with the decorator
```
    @given(data=st.data(), shape=hynp.array_shapes())
    def test_clip_property(self, data, shape):
```

[here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=347740&view=logs&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=66e4a587-a723-53e9-873c-6c9a2c5971ea&l=20928) is the end of the stack trace in a CI run.

**Comment by Zac-HD** [comment]
OK... this is pretty weird, nothing [in that test](https://github.com/numpy/numpy/blob/3d83143c2c2f877ee921c4c7c6746d836c459839/numpy/core/tests/test_numeric.py#L2337-L2397) looks like it should be caching anything to me.  

The first thing I'd try is updating to the latest version of Hypothesis; `hypothesis-5.28.0` is coming up on a year old and we might have fixed it since then.  If not, maybe the indirection about dtypes is to blame?  Taking that out of the test:

```python
    @given(
        data=st.data(),
        arr=hynp.arrays(
            dtype=hynp.integer_dtypes() | hynp.floating_dtypes(),
            shape=hynp.array_shapes()
        )
    )
    def test_clip_property(self, arr):
        ... 
        # Generate shapes for the bounds which can be broadcast with each other
        # and with the base shape.  Below, we might decide to use scalar bounds,
        # but it's clearer to generate these shapes unconditionally in advance.
        in_shapes, result_shape = data.draw(
            hynp.mutually_broadcastable_shapes(
                num_shapes=2,
                base_shape=arr.shape,
                # Commenting out the min_dims line allows zero-dimensional arrays,
                # and zero-dimensional arrays containing NaN make the test fail.
                min_dims=1
  
            )
        )
        amin = data.draw(
            hynp.from_dtype(arr.dtype)  # can probably use .filter() here to exclude scalar nan, instead of assume()
            | hynp.arrays(dtype=dtype_strategy, shape=in_shapes[0])
        )
        amax = data.draw(
            hynp.from_dtype(arr.dtype)
            | hynp.arrays(dtype=dtype_strategy, shape=in_shapes[1])
        )
        ...
```

Meta-observations: it looks like Hypothesis would be more helpful here if we showed the input (or actions so far) when raising a Flaky failure, as well as enabling [our usual traceback trimming logic](https://github.com/HypothesisWorks/hypothesis/blob/05b4c56b2b87f5e787f5195718af4cab5bf96790/hypothesis-python/src/hypothesis/internal/escalation.py#L90-L96) for Flaky even though it's raised from inside Hypothesis.

**Comment by mattip** [comment]
> The first thing I'd try is updating to the latest version of Hypothesis; hypothesis-5.28.0 is coming up on a year old and we might have fixed it since then

See conda-forge/hypothesis-feedstock#600. It turns out the version was getting pinned on PyPy because there was a dependency on `black`, which depends on `typed_ast`, which is not supported by PyPy. So once that gets merged, we can try again with a newer `hypothesis`

**Comment by h-vetinari** [comment]
This seems to [persist](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=350018&view=logs&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=66e4a587-a723-53e9-873c-6c9a2c5971ea&l=20801) on win+pypy also with
```
 hypothesis:         6.14.1-pyhd8ed1ab_1      conda-forge
```

**Comment by Zac-HD** [comment]
Looks like it's passing now ([CI logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=351357&view=logs&j=e5cdccbf-4751-5a24-7406-185c9d30d021&t=66e4a587-a723-53e9-873c-6c9a2c5971ea&l=3626)), so I'm going to close this issue.  Kinda unsatisfying not to pin down the exact cause, but after trimming Flaky tracebacks, using the latest Hypothesis, and improving the test in Numpy it all seems to work 🤷‍♂️

**Comment by Zac-HD** [comment]
Behold a deterministic sub-second repro, which raises `Flaky` on PyPy 3.7, but passes on CPython 3.7:

```python
from hypothesis import Verbosity, given, seed, settings, strategies as st

@seed(0)  # you can vary this, but it doesn't change much
@settings(database=None, verbosity=Verbosity.debug)
@given(st.data())
def test(data):
    # Magic numbers identified using an outer PBT loop; x-1 does not repro
    data.conjecture_data.draw_bits(4)                 # Just enough to set cache state?
    data.conjecture_data.draw_bits(33, forced=2**32)  # Super suspicious!

if __name__ == "__main__":
    test()
```
```bash
$ python -V
Python 3.7.12 | packaged by conda-forge | (44db2626, Nov 15 2021, 12:57:47)
[PyPy 7.3.7 with MSC v.1916 64 bit (AMD64)]
```

@mattip, between this 2^32 effect and [the changelog entry](https://doc.pypy.org/en/latest/release-v7.3.4.html#changelog)

> - Optimize instances of maps with integer and float fields by storing them unboxed in a float array (on 32bit machines this is only done for float fields). The float array is stored in one of the storage slots of the instance. Once a field proves to be type-unstable we give up on type-specializing this class and revert all instances once we touch them the next time to the default representation.

I'm pretty sure this is in fact a PyPy bug.  Unfortunately fast+deterministic is the best I can do at the moment; I just don't have the free time to work out a minimal or Hypothesis-free repro 😢

**Comment by mattip** [comment]
cc @cfbolz. Fwiw, I ran the test on a linux nightly and could not reproduce the failure.
```
$pypy -V
Python 3.8.12 (cb981a4f6dff, Nov 21 2021, 01:43:00)
[PyPy 7.3.8-alpha0 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
```

**Comment by mattip** [comment]
Seems like it is windows-only, the exact same conda version on linux works fine
```
$ python -V
Python 3.7.12 | packaged by conda-forge | (44db2626, Nov 15 2021, 12:53:46)
[PyPy 7.3.7 with GCC 9.4.0]

```

**Comment by Zac-HD** [comment]
OK, I got nerd-sniped so here's a truly minimal repro:

```python
from array import array

arr = array("I", [0])
arr[0] = 2 ** 32  # On PyPy 3.7 under Windows, this fails to raise an OverflowError (!)
```

Closing because at this point it's clearly not a Hypothesis bug; thanks again to @projectgus for helping to minimize and good luck to @mattip in fixing it!

**Comment by mattip** [comment]
Thanks. Once again proving the value of using hypothesis. I filed an issue https://foss.heptapod.net/pypy/pypy/-/issues/3604, fix is on the way.

**Comment by projectgus** [comment]
Nice work @Zac-HD! (but apologies for nerd-sniping you :grin: ).
