### ISSUE TITLE
How to migrate off the timeout feature?

### ISSUE THREAD

**Issue by axch** [HypothesisWorks/hypothesis#3031]
Hi all, and thanks for the great testing software!  My coworkers and I use it every day.

I wanted to ask about how to migrate off the timeout feature that was deprecated in the 3.x series and removed in 4.x.  It's past time our project upgraded, but not having timeouts is stopping us.  Please redirect me if this is not a good forum to ask such a question.

The specific context is this.  I'm part of the team that maintains [TensorFlow Probability](https://github.com/tensorflow/probability).  The core of TFP is a library of some 100 probability distribution objects (Gaussian, Poisson, StudentT, etc) and means of composing them (e.g., change of variables), each of which has a bunch of methods that we test to obey various relationships.  Our test suite uses Hypothesis to search for counterexamples to each of those ~100 distributions satisfying each of ~20 properties.  The setup looks like this:

```
class SomeTest(object):

  @parameterized(<all Distribution class names in TFP>)
  @hp.given(hps.data())
  def testSomething(self, dist_name, data):
    dist = construct a distribution of the class named dist_name
    ....
```

Note that we use `@parameterized` to generate a separate test method and therefore an independent Hypothesis search for each distribution type.  This gives us at least two important benefits: (i) we can run these separate searches in parallel on different machines, and (ii) Hypothesis' failure reproduction strings don't break from adding a new distribution type to our library.

Now the issue.  These distribution classes vary widely in how long it takes to construct and test one.  When we run with a large example limit, the 60-second soft timeout from Hypothesis 3 becomes binding, and the number of examples attempted varies form 3 to 800+ depending on the distribution being tested and the specific test method.  In the case of the compound distributions, the time needed to construct and test an example can also vary widely from one example to another, depending on how deeply nested a given example turns out to be.

Thus, the soft timeout feature in Hypothesis 3.x fits our testing needs fairly well---the variation in coverage is unfortunate, but hitting the hard timeout imposed by our build tool would be worse, and this way we have reasonable confidence that at least a consistent amount of computation is going into testing our library across the board.  Plus, coverage automatically increases when we (or the underlying platform) make performance improvements.

Unfortunately, Hypothesis 4+ removes the timeout feature, and we're not sure how to proceed.  Is the only option really to maintain a 20 x 100 matrix of example limits for each test and each distribution?  Would we have a way to detect when a performance improvement has made it reasonable to increase one of the example limits?  Is there even a convenient way to read such a matrix?  I haven't yet found a way to have the `@hp.settings` decorator be able to read the distribution name chosen by `@parameterized` for a given method.

We would appreciate any suggestions.

**Comment by Zac-HD** [comment]
👋 I'm glad you find Hypothesis useful, and think you'll like the new version even more!

This is a pretty unusual use-case, so I don't think having a public API for it makes sense - most people with time-based test budgets are in more of a [fuzzing](https://hypofuzz.com/) than a unit-testing workflow.  Your best option is probably to monkey-patch in a deadline check via [`hypothesis.internal.conjecture.engine.ConjectureRunner.should_generate_more()`](https://github.com/HypothesisWorks/hypothesis/blob/3759eeb055fd79198bad7047dd6f11a70d1d10f5/hypothesis-python/src/hypothesis/internal/conjecture/engine.py#L589-L615).


<details>
  <summary>I also had a much worse idea, don't do this</summary>
  
There's an ugly workaround available via [our `fuzz_one_input` hook](https://hypothesis.readthedocs.io/en/latest/details.html#use-with-external-fuzzers), though you'd lose most of the nice heuristics and feedback in our engine.  It would also need substantial work to get a nice combination of shrinking, generation-time performance, and actually respecting the timeout.

```python
class SomeTest:

    @parameterized(<all Distribution class names in TFP>)
    def testSomething(self, dist_name):

        @hp.settings(phases=[hp.Phase.reuse, hp.Phase.shrink], deadline=None)
        @hp.given(hps.data())
        def inner(data):
            dist = construct a distribution of the class named dist_name
            ...

		start = time.perf_counter()
        while time.perf_counter() - start < 60:
            inner.hypothesis.fuzz_one_input(random_bytes(8_000))
        	inner()  # replay, shrink, raise any failing example(s); 
                     # that's a noop iff DB is empty else 2x-100x slowdown
```

</details>

If you need anything else, this sounds like exactly the kind of tricky project [I consult](mailto:zac@hypofuzz.com?subject=Hypothesis%20consulting%20enquiry) on 😉
