### ISSUE TITLE
What does HealthCheck.data_too_large actually mean?

### ISSUE THREAD

**Issue by danielknell** [HypothesisWorks/hypothesis#3032]
I am finding the docs around this one really confusing and ambiguous... i get what the others mean but `data_too_large` always has me a bit confused 😵‍💫.

> Check for when the typical size of the examples you are generating exceeds the maximum allowed size too often.

https://hypothesis.readthedocs.io/en/latest/healthchecks.html#hypothesis.HealthCheck.data_too_large

too large how? is it defined somewhere? i have looked in the settings and theres nothing about max example size, nor does it seem to be anything in the docs...

Is it about the range of values that can be generated or the actual memory size in bytes? if i have a hypothetical strategy that generates a billion `00` bytes or a billion `01` bytes thats going to result in only 2 possible examples, but a gig of memory footprint, will it trigger the error? (ignoring the fact there seems to be a threshold of 20 times to trigger an error).

the code causing the healtcheck to fail mentions overruns but i cant find any details on that in the docs either? is it a low level conjecture thing?

is it just to save the testsuite from chewing through ram or is there a deeper meaning?

**Comment by Zac-HD** [comment]
It's a low-level conjecture thing, basically "your strategy wanted more random bits than we had available", so *mostly* the range of values but in a way that depends on *how* they get generated.

We should improve the docs and the error message though, thanks for pointing that out!

**Comment by danielknell** [comment]
I am glad to help, if we can find a helpful description I am happy to PR the docs.

so my hypothetical above choosing between two huge constants wouldn't trigger it as it's a single bit of randomness.

but if I tried to generate a billion booleans it would as (to overly simplify) the RNG would run out of randomness?

**Comment by Zac-HD** [comment]
Correct - we cap at `8192` bytes internally to avoid very slow generation+shrinking performance.

**Comment by danielknell** [comment]
Would something like this work?

> Check for when the typical size of the examples you are generating too often exceeds the maximum amount of random data hypothesis is able to generate.
