### ISSUE TITLE
[Feature request] st.optional strategy for None or something

### ISSUE THREAD

**Issue by mdavis-xyz** [HypothesisWorks/hypothesis#3033]
I find myself often needing a strategy that generates something, or `None`.

e.g. for a function like `def foo(x: Optional[MyClass])`.

I would like a convenience function to do this for me with a little bit less writing.

I propose a new strategy `hypothesis.strategies.optional`like:

```
def optional(s: SearchStrategy) -> SearchStrategy
    return st.one_of(st.none(), s)
```

Yes I know it doesn't save much. But neither does `Optional[MyClass]` vs `Union[NoneType, MyClass]`. It's one of those things that gets used so often we should probably have a shorthand for it.

I'm willing to write this myself. Just checking what other people think.

**Comment by Zac-HD** [comment]
I think that we should ship [one-- and preferably only one --obvious way to do it](https://www.python.org/dev/peps/pep-0020/); and we already have `st.none() | s` and `one_of(st.none(), s)` and `st.from_type(Optional[MyClass])`.  If it's useful for you though, I'd encourage you to copy that helper function into your own test utils code!
