### ISSUE TITLE
Collecting the falsifying examples (pandas dataframes)

### ISSUE THREAD

**Issue by Michael-git96** [HypothesisWorks/hypothesis#3038]
I am using hypothesis to test a function which takes in a pandas dataframe. Running pytest I can see that hypothesis found a falsifying example however when it prints the dataframe, I cannot see all the columns as it is quite a large dataframe. Does hypothesis store this falsifying example anywhere so that I can read it into python?

**Comment by Zac-HD** [comment]
No, [Hypothesis' database of examples](https://hypothesis.readthedocs.io/en/latest/database.html) isn't in a format that you can read from - just enough to replay the test later.

However, your test function can be whatever Python code you want - for example, start by saving a copy of your dataframe before making any assertions.

**Comment by Michael-git96** [comment]
Thank you for your reply @Zac-HD, I have done what you suggested and it works well!

Another thing I noticed, is that I can see that Hypothesis has taken a lot of time trying to shrink the falsifying example. Is there a way to turn the shrinking off? Would be useful for tests which have inputs which are a fixed size.

**Comment by Michael-git96** [comment]
@Zac-HD , I am not sure if I should start a new issue, but I also noticed that this warning is coming up hundreds of times:
![image](https://user-images.githubusercontent.com/66077454/127040001-bcaf2507-eb94-4f3c-8b84-7e813877d92a.png)

I think it may be linked to the NumPy version I am using but I do not use np.complex in my code anywhere so I think it is coming from hypothesis.

**Comment by Zac-HD** [comment]
> Is there a way to turn the shrinking off? Would be useful for tests which have inputs which are a fixed size.

You can [disable shrinking via the `phases` setting](https://hypothesis.readthedocs.io/en/latest/settings.html#controlling-what-runs), but note that shrinking does "normalise" fixed-size data too - e.g. replacing numbers with zero, even if it can't reduce the collection size.

> this warning is coming up hundreds of times

`git grep "np.complex"` returns no results, so this isn't in Hypothesis.  Try running with `-Werror` so you get a traceback pointing to the location?
