### ISSUE TITLE
Doc typo for json recursive example

### ISSUE THREAD

**Issue by mdavis-xyz** [HypothesisWorks/hypothesis#3042]
The [documentation example for json](https://hypothesis.readthedocs.io/en/latest/data.html?highlight=max_size#recursive-data) is:

```
json = recursive(
    none() | booleans() | floats() | text(printable),
    lambda children: lists(children, 1)
    | dictionaries(text(printable), children, min_size=1),
)
```

This part: `lists(children, 1)` throws an error. 

> TypeError: lists() takes 1 positional argument but 2 were given

I think the second arg should be a kwarg. Is it supposed to be min_size=1? Or should it be omitted entirely? (Since an empty list is valid json.)

**Comment by Zac-HD** [comment]
Ah, that's a new problem since we made the arguments keyword-only.  Either `min_size=1` or ommiting them (to allow empty collections, which are indeed valid JSON) will work.

We should update the docs by simply deleting the `, 1` in each strategy.
