### ISSUE TITLE
Strategy to test all values

### ISSUE THREAD

**Issue by r-barnes** [HypothesisWorks/hypothesis#3049]
I'm looking for a way to make hypothesis do the following:

```python
@given(device=st.test_every_value_of(["cpu", "gpu"])
def test_a_thing(self, device):
  do_something_with_device(device)
```

But I haven't found a strategy like `st.test_every_value_of`.

What's a good way of doing this?

**Comment by rsokl** [comment]
You are looking for `st.sampled_from`: https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.sampled_from

```python
@given(device=st.sampled_from(["cpu", "gpu"])
def test_a_thing(self, device):
  do_something_with_device(device)
```

**Comment by r-barnes** [comment]
The documentation for `st.sampled_from` reads

> Returns a strategy which generates any value present in elements.

Should this read "any and all values present in elements"?

**Comment by rsokl** [comment]
Well it doesn't guarantee that it will test all values. Hypothesis, by default, will generate 100 test cases based on the strategies that you specify. This can be configured. Thus if your `st.sampled_from` contains a sequence with more than 100 elements, or if you are using it in conjunction with other strategies, it might not exhaustively test all of the items. This is the nature of how Hypothesis works.

If you want to ensure that a sequence of items are being exhaustively tested, then I recommend that you use `pytest.mark.parameterize`.

```python
import pytest

@pytest.mark.parameterize("device", ["cpu", "gpu"])
def test_a_thing(self, device):
  do_something_with_device(device)
```  
  
https://docs.pytest.org/en/6.2.x/parametrize.html

**Comment by rsokl** [comment]
And note that pytest's parameterize fixture can be used alongside hypothesis' `@given`. Thus you can write a test that will exhaustively iterate through test cases, and hypothesis will generate (default 100) test cases for each one of those instances.
