### ISSUE TITLE
`Cargo.lock` and `.gitignore`

### ISSUE THREAD

**Issue by sobolevn** [HypothesisWorks/hypothesis#3061]
I have [`rust-analyzer`](https://github.com/rust-analyzer/rust-analyzer) installed in my IDE, so when it opens it prepares the environment. 

In the end `conjecture-rust/Cargo.lock` is generated. And it is not clear to me what to do with it:
1. Commit it
2. Ignore it with `.gitignore`, it looks like it is already ignored in `ruby/`, but not in `rust/`: https://github.com/HypothesisWorks/hypothesis/blob/3d5761ed9254b39260f39cf52bad1293ccf733ab/hypothesis-ruby/.gitignore#L5

Which PR should I submit? 🙂

**Comment by Stranger6667** [comment]
Libraries should ignore `Cargo.lock`, in bindings it is more like a binary/application as it is needed to generate some outcome.

**Comment by Stranger6667** [comment]
However, disregard the last part of my comment on bindings.

**Comment by Stranger6667** [comment]
Here is a [guide](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) on this matter
