### ISSUE TITLE
Run tests for `hypothesis.extra.array_api` against *any* implementation

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#3085]
#3065 comes with a lovely test suite for our new `hypothesis.extra.array_api` module, with easy parameterization across implementations - but currently that's just for `numpy.array_api` and our own internal mock instance (which is built on standard Numpy).

It would be lovely to have some way to run these tests against other implementations of the Array API too!

Obvious ideas include an environment variable of some kind, and using the entry-points described in https://github.com/data-apis/array-api/issues/244 to run against everything that's installed.  (but we'd still want the env var, for libraries which haven't adopted the entrypoint yet)  This isn't urgent and so we left it out of #3065 for size, but would be very nice to have.

**Comment by honno** [comment]
Just as we'd want to try multiple namespaces for our own test suite, so would developers of array-consuming libraries testing with Hypothesis—would it be reasonable to have a "generalised" Array API strategies that fuzz all available array/tensor libraries in the users env?

**Comment by Zac-HD** [comment]
> Would it be reasonable to have a "generalised" Array API strategies that fuzz all available array/tensor libraries in the users env?

IMO whatever we'd want to do for that should just be an option on https://github.com/data-apis/array-api-tests - happy to have close integration/colaboration, but it's not really about testing *Hypothesis* at that point.

**Comment by rsokl** [comment]
> would it be reasonable to have a "generalised" Array API strategies that fuzz all available array/tensor libraries in the users env?

Do you mean fuzz *against* all available libraries, or fuzz *using* all available libraries? If you mean the latter, e.g.:

```python
@given(all_arrays(dtype="float"))
def test_something_in_dask(x):
    # x : np.ndarray | torch.Tensor | mygrad.Tensor | <any other available array/tensor in my env>
``` 

I would vote "no" on that, for a few reasons. 

One big reason is: this test would become less and less incisive (and I believe the strategy would shrink less effectively) as I add more libraries to my environment; this is assuming that  `all_arrays` is somethings akin to `st.one_of(np_arrays(..), torch_tensors(...), mygrad_tensors(...))` and assuming that I keep `max_examples` the fixed. It would be a shame for a library's tests to get "weaker" as its maintainers aim to be increasingly thorough by testing against more array implementations. 

That being said, it might be worth documenting a recipe that enables maintainer to construct this sort of uber strategy themselves (and we can include appropriate warnings – "hey, this is a convenient way to do some shallow fuzzing using a bunch of implementations")

If that is not what you meant then.... well just ignore all of that  😅

**Comment by honno** [comment]
Yep I meant fuzz using all available libraries. What you say makes sense, thanks!

+1 for a recipe in the docs. When I'm testing an array-consuming library I would appreciate a "shallow" `all_arrays()`-ish strategy, if just to smoke the methods I'm testing. Such a recipe could first include an `array_modules()` strategy that calls `st.one_of(numpy.array_api, ...)`—if entry points goes through, it might even be something appropriate for `extra.array_api`.

**Comment by Zac-HD** [comment]
I think I'd prefer to make the "combination strategies" explicitly constructed; but I'd be fine with a pretty slim wrapper around `make_strategy_namespace()`, usable like:

```python
xps = array_combination_namespace(*array_modules)

xps.arrays(**kw)  # returns one_of([make_strategy_namespace(mod).arrays(**kw) for mod in array_modules])
```

**Comment by honno** [comment]
[Entry points went through](https://data-apis.org/array-api/latest/purpose_and_scope.html#discoverability)! In https://github.com/HypothesisWorks/hypothesis/pull/3136#issuecomment-961547613 @Zac-HD suggested two options for next steps:
> 1. [Run tests for `hypothesis.extra.array_api` against *any* implementation #3085](https://github.com/HypothesisWorks/hypothesis/issues/3085), ensuring that we run our own selftests against all installed implementations.  I'm happy to rely on entry points for this; I'd prefer to ask array implementors to support it rather than checking a custom env var.
> 
>  2. Also [Run tests for `hypothesis.extra.array_api` against *any* implementation #3085](https://github.com/HypothesisWorks/hypothesis/issues/3085), in the comments, we should think about ways make testing against multiple array-api modules easy for our users.  For example we could add an `installed_array_modules()` function which loads them via the entry point and add `*args` to `make_strategies_namespace(xp)` pretty easily - the challenge is to work out the maximum feasible level of mixing (e.g. `xp1.arrays(xp2.float32, ...)` is probably bad?).

In any case, having `extra.array_api` able to hook into entry points somehow will let us practically do point 1 and give us options for point 2. Zac had tried a module-level `__getattr__` idea in https://github.com/HypothesisWorks/hypothesis/pull/3065#issuecomment-914086577 so they might like to do this. Otherwise, feel free to task me with giving this a go, and/or if it's more complicated than we can discuss this in a separate issue. Also, NumPy upstream can be used to actually see it works now.

**Comment by honno** [comment]
@Zac-HD would you like me to have a stab at adding entry points support for `extra.array_api` by way of a module-level `__getattr__()` e.g. so we could have something like `extra.array_api.pytorch`. Wasn't sure if you already had something cooked, and I can still have a go regardless if you'd like.

And following on from that, I could try using it for `tests/array_api/`.

**Comment by Zac-HD** [comment]
Let's take a more incremental approach than we've done before 😂 

1. New function `installed_array_modules() -> Dict[str, module]` which loads modules from entry points.  This is "just" a convenience wrapper over `importlib.metadata`, but worth it IMO since the API changed in 3.10.
2. Use this to parametrize our tests over all installed array modules.

After that we can think about whether it makes sense to add multi-module support to `make_strategies_namespace`.

IMO we *should not* do the `__getattr__` plan though; per https://github.com/HypothesisWorks/hypothesis/pull/3065#issuecomment-914086577 I just couldn't get it to fail gracefully (i.e. with a useful error message when used via `import`), and that's a hard requirement for me.

**Comment by honno** [comment]
We got the internal entry point hook down, so now we need to

- [ ] Parametrize modules for `tests/array_api/`

I'll explore how to do this nicely in the next few days but imagine the PR will be for next year.

Wouldn't be helpful until CuPy gets entrypoints anyway (easily monkey patched for local testing tho), as beyond NumPy there's no other implemented-enough array module to use yet. Also @Zac-HD would you know yet if CuPy be possible on CI? It only _feasibly_ runs on Nvidia GPUs... I've been using a remote VM for dev haha.

**Comment by Zac-HD** [comment]
I don't know, but it's good to have even if we can't run it in CI - I can run locally, and also ask if Nvidia will sponsor us some CI time to maintain good CuPy support.

**Comment by honno** [comment]
> Parametrize modules for `tests/array_api/`

I'm going to start working on this next week... was demotivated by an old PC and the 1st spec release lagging (should be soon™) haha. Just wondering if @Zac-HD and folks had any ideas/preferences/notes in how to actually parametrize array modules for all tests in this folder.

My initial idea was having every test function have an argument/fixture that holds both `xp` and `xps`, e.g. `xp_and_xps == (np.array_api, xp.make_strategies_namespace(np.array_api)`, which with some hacking in a `tests/array_api/conftest.py` would be parametrized against available entry points (and if none found, parametrize once with the mock).

Also, was thinking each test item should ideally have names like
```
tests/array_api/test_foo.py::test_bar[numpy]
tests/array_api/test_foo.py::test_bar[dask]
tests/array_api/test_foo.py::test_bar[cupy]
tests/array_api/test_foo.py::test_multiple_cases[numpy-case0]
tests/array_api/test_foo.py::test_multiple_cases[numpy-case1]
tests/array_api/test_foo.py::test_multiple_cases[dask-case0]
tests/array_api/test_foo.py::test_multiple_cases[dask-case1]
tests/array_api/test_foo.py::test_multiple_cases[cupy-case0]
tests/array_api/test_foo.py::test_multiple_cases[cupy-case1]
etc.
```
Anywho, if/when I come up with a solution I'll be sure to make a PR and we can go from there. Just wanted to make sure I wasn't missing something obvious heh.

**Comment by Zac-HD** [comment]
Yeah, that sounds about right to me!  Some small tweaks:

Let's define a `HYPOTHESIS_TEST_ARRAY_API` env var - if it's not set, we do the current behaviour of testing against the mock and against `numpy.array_api` (if that's available?).  You can then set the var to the import name of another array API implementation to test that (erroring if it's not installed), or to the special value `all` to test everything installed via the entry point (and error if there are none).

I think the specific thing you want to write in `conftest.py` is the [`pytest_generate_tests` hook](https://docs.pytest.org/en/6.2.x/reference.html#pytest.hookspec.pytest_generate_tests), which gives you rather powerful custom parametrization.  In particular you can have separate not-actually-fixtures for `xp` and `xps`, without getting the cross-product of them - just as if you had a single `@parametrize("xp,xps", [...])` decorator on every function with `xp` and `xps` in its signature.  See also [stackoverflow](https://stackoverflow.com/questions/49076378/pytest-generate-tests-based-on-arguments), [this blog post](https://medium.com/opsops/deepdive-into-pytest-parametrization-cb21665c05b9) 😄
