### ISSUE TITLE
A unique strategy

### ISSUE THREAD

**Issue by vincent-lg** [HypothesisWorks/hypothesis#3094]
Hi,

I would like to have guarantee uniqueness of data in some tests.  That is, if I use `@given`, some of the generated data should remain unique for this function.  I was thinking along something like:

```python
@given(username=st.unique(st.text(min_size=1)))
def test_create(username):
    # `username` should be unique for this `create` function.
```

Does it sound silly?  Does it already exist?  I couldn't find a quick way to do it, though I guess one could try using `st.shared` like `st.UUID` already does.

If you do have a workaround to suggest, I'm interested!

Just a thought!  Thanks for this great work.

**Comment by rsokl** [comment]
Are you saying , e.g.,

```python
@given(username=st.unique(st.text(min_size=1)))
def test_create(username):
    ...

@given(username=st.unique(st.text(min_size=1)))
def test_create2(username):
    ...
```

that if I call

```python
>>> test_create()
>>> test_create2()
```

then the values drawn from `st.text` in service of `test_create` should be guaranteed to be distinct from those drawn in service of `test_create2`? Or are you simply saying that you want to ensure that you want to ensure that values drawn in service of `test_create()` (called only once) are unique from one another?

**Comment by vincent-lg** [comment]
I was thinking of the second use case, uniqueness would be guaranteed in `test_create`, but `test_create2` would have values that overlap.  At least for my use case, I only need this "uniqueness" strategy to be guaranteed in a test function, not beyond it.

**Comment by rsokl** [comment]
**Short answer:**

It sounds like you are interested in doing stateful testing, in which case I recommend checking out [Hypothesis' support for stateful testing](https://hypothesis.readthedocs.io/en/latest/stateful.html).

Hypothesis does not expose state/relationships between values drawn - **across examples** - from a strategy, thus `st.unique` would not be something that would suite the library.

**Long answer:**

Hypothesis' strategies are only configurable on a per-example basis. Here, an "example" is a set of values drawn from `@given` to run the body of your test once. To be a bit more concrete, calling `test_create()` will cause `@given` to execute the body of `test_create` using 100 independent examples, and no documented/configurable relationship among values across draws. 

Note that even the `st.uuids` strategy only discusses uniqueness in the context of `st.lists(st.uuids())`, which is to say that, if a single example consists of drawing a list of multiple UUIDs, then those UUIDs will be unique from one another. It does not say that the UUIDs will be unique across examples.

Under the hood of Hypothesis, there *is* some sense of progression/adaptation among subsequent examples (i.e. the process is adaptive / isn't memoryless), but the specifics of that behavior is not exposed to the user nor is it configurable. Thus a strategy like `st.unique` would not be something that we would want to

If your really want unique examples across executions of your test, you could do

```python
from hypothesis import given, settings
import hypothesis.strategies as st

@settings(max_examples=1)
@given(st.lists(st.text(min_size=1), min_size=100, max_size=100, unique=True))
def test_create_wrapper(x):
    for example in x:
        test_create(x)
``` 

And this will also run `test_create` 100 times, but with unique inputs across runs. But I doubt that Hypothesis will be as effective at searching for fail cases if you use it in this way.

**Comment by rsokl** [comment]
**Short answer:**

It sounds like you are interested in doing stateful testing, in which case I recommend checking out [Hypothesis' support for stateful testing](https://hypothesis.readthedocs.io/en/latest/stateful.html).

Hypothesis does not expose state/relationships between values drawn - **across examples** - from a strategy, thus `st.unique` would not be something that would suite the library.

**Long answer:**

Hypothesis' strategies are only configurable on a per-example basis. Here, an "example" is a set of values drawn from `@given` to run the body of your test once. To be a bit more concrete, calling `test_create()` will cause `@given` to execute the body of `test_create` using 100 independent examples, and no documented/configurable relationship among values across draws. 

Note that even the `st.uuids` strategy only discusses uniqueness in the context of `st.lists(st.uuids())`, which is to say that, if a single example consists of drawing a list of multiple UUIDs, then those UUIDs will be unique from one another. It does not say that the UUIDs will be unique across examples.

Under the hood of Hypothesis, there *is* some sense of progression/adaptation among subsequent examples (i.e. the process is adaptive / isn't memoryless), but the specifics of that behavior is not exposed to the user nor is it configurable. Thus a strategy like `st.unique` would not be something that we would want to

If your really want unique examples across executions of your test, you could do

```python
from hypothesis import given, settings
import hypothesis.strategies as st

@settings(max_examples=1)
@given(st.lists(st.text(min_size=1), min_size=100, max_size=100, unique=True))
def test_create_wrapper(x):
    for example in x:
        test_create(x)
``` 

And this will also run `test_create` 100 times, but with unique inputs across runs. But I doubt that Hypothesis will be as effective at searching for fail cases if you use it in this way.
