### ISSUE TITLE
DataFrame examples are nearly unreadable

### ISSUE THREAD

**Issue by inglesp** [HypothesisWorks/hypothesis#3114]
I have a test that takes a couple of Pandas DataFrames as input.  When the test fails, the examples in the output can be very hard to make sense of:

```
Falsifying example: test_always_increasing(
    df_a=            A
    2021-01-01  1, df_b=            A
    2021-01-01  0
    2021-01-02  0,
)
```

If I add the following line in my test setup:

```
pd.DataFrame._repr_pretty_ = lambda self, p, cycle: p.text(f"\n{self}\n")
```

then the output is much clearer:

```
Falsifying example: test_always_increasing(
    df_a=
            A
2021-01-01  1
,
    df_b=
            A
2021-01-01  0
2021-01-02  0
,
)
```

Would you accept a patch that always sets `pd.DataFrame._repr_pretty_`?  (Assuming Pandas is installed and that `pd.DataFrame._repr_pretty_` isn't already set...)

**Comment by Zac-HD** [comment]
I'd be happy to accept such a patch, though I'm unsure whether it would be better located in the pandas extra or our pretty-printing logic... probably the former?

**Comment by inglesp** [comment]
Hey @Zac-HD, I'm sorry I never got around to fixing this myself.  Thanks!

**Comment by Zac-HD** [comment]
No worries! I happened to be poking around in the pretty-printer last week, and at that point it was (ahem) pretty easy to fix 😎
