### ISSUE TITLE
Bad shrinking with complex strategy involving mutually_broadcastable_shapes

### ISSUE THREAD

**Issue by asmeurer** [HypothesisWorks/hypothesis#3151]
I have a test that generates several mutually broadcastable shapes and an `axes` keyword argument that generates a tuple of axes on the result shape. I have the strategies built using `shared` and `flatmap`. 

My test fails with certain axis arguments, but, the resulting failure case does not shrink properly at all. Here is a simplified test showing the problem:

```py
>>> from hypothesis.strategies import integers, shared, tuples
>>> from hypothesis import given
>>> from hypothesis.extra.numpy import mutually_broadcastable_shapes
>>> mbs = shared(integers(1, 32).flatmap(lambda i: mutually_broadcastable_shapes(num_shapes=i)))
>>> axes = mbs.flatmap(lambda bs: tuples(*(integers(-i, max(0, i-1)) for i in range(len(bs.result_shape)))))
>>> @given(mbs, axes)
... def test(broadcastable_shapes, axis):
...     shapes, result_shape = broadcastable_shapes
...
...     if len(shapes) > 1:
...         assert set(result_shape) == {result_shape[i] for i in axis}
>>> test()
Falsifying example: test(
    broadcastable_shapes=BroadcastableShapes(input_shapes=((), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (2, 1)), result_shape=(2, 1)),
    axis=(0, 0),
)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in test
  File "/Users/aaronmeurer/anaconda3/envs/ndindex/lib/python3.8/site-packages/hypothesis/core.py", line 1202, in wrapped_test
    raise the_error_hypothesis_found
  File "<stdin>", line 6, in test
AssertionError
```

Here's proof that the multiple `()`s are unnecessary (the inputs could be shrunk in other dimensions as well).

```py
>>> test.hypothesis.inner_test((((), (2, 1)), (2, 1)), (0, 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 6, in test
AssertionError
```

CC @honno

**Comment by Zac-HD** [comment]
I'm not particularly surprised by imperfect shrinking of examples from such a complicated and non-local strategy, though obviously it would be nice to do better.  See https://github.com/HypothesisWorks/hypothesis/blob/master/guides/strategies-that-shrink.rst and #1099 and #1187; ultimately I don't have much to suggest here.

**Comment by asmeurer** [comment]
I see. I tried replacing generating the number of shapes and using `flatmap` with always generating 32 shapes then drawing some of them. This feels kind of clunky. Is there a better way to draw a subset of elements from a list? But it does seem to work for my toy example. I'll test it on my actual code tomorrow.

```py
>>> @composite
... def mbs2(draw):
...     shapes = draw(mutually_broadcastable_shapes(num_shapes=32)).input_shapes
...     shapes = draw(lists(sampled_from(shapes), min_size=0, max_size=32, unique_by=id))
...     result_shape = np.broadcast_shapes(*shapes)
...     return shapes, result_shape
>>> @given(mbs2(), axes)
... def test2(broadcasted_shapes, axis):
...     shapes, result_shape = broadcasted_shapes
...     if len(shapes) > 1:
...         assert set(result_shape) == {result_shape[i] for i in axis}
>>> test2()
Falsifying example: test2(
    broadcasted_shapes=([(), (1,)], (1,)), axis=(),
)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in test2
  File "/Users/aaronmeurer/anaconda3/envs/ndindex/lib/python3.8/site-packages/hypothesis/core.py", line 1202, in wrapped_test
    raise the_error_hypothesis_found
  File "<stdin>", line 5, in test2
AssertionError
```

**Comment by Zac-HD** [comment]
Unfortunately "clunky" is about as good as it gets when you're dealing with this kind of unusually-low-level stuff, and `lists(sampled_from(), ..., unique_by=id)` is the best way to get a subset of elements (it's even special-cased to linear instead of quadratic scaling).

**Comment by honno** [comment]
If useful, note that `mutually_broadcastable_shapes()` (both for NumPy and Array API) are already hard coded to not generate shapes with more than 32 dims.

Generally I'd recommend playing around with the [`minimal()`](https://github.com/HypothesisWorks/hypothesis/blob/5c48ce7a6b037a543778aa57f160a49b481d27f7/hypothesis-python/tests/common/debug.py#L36) util if you're going to spend significant time on bettering minimising behaviour. Mind it's an internal test suite util (i.e. not in `hypothesis` package), so you'll have to pull the Hypothesis source and install things locally (or copy the relevant `debug.py` code).

Here's how I'd test your `mbs()`
```python
# ./hypothesis-python/tests/test_custom_mbs.py
import numpy as np

from hypothesis import strategies as st
from hypothesis.extra import numpy as nps
from hypothesis.extra.numpy import BroadcastableShapes
from tests.common.debug import minimal


@st.composite
def mbs(draw):
    shapes = draw(nps.mutually_broadcastable_shapes(num_shapes=32)).input_shapes
    shapes = draw(st.lists(st.sampled_from(shapes), min_size=0, max_size=32, unique_by=id))
    result_shape = np.broadcast_shapes(*shapes)
    return BroadcastableShapes(shapes, result_shape)


def test_minimize():
    shapes, result_shape = minimal(mbs(), lambda S: len(S.input_shapes) > 1)
    assert shapes == [(), (1,)]
    assert result_shape == (1,)
```
Note that `minimal()` has a second optional argument, which throws any examples that doesn't meet a condition e.g. scenarios where `len(input_shapes) == 0` , like you used in your `test()` example.

**Comment by asmeurer** [comment]
> If useful, note that mutually_broadcastable_shapes() (both for NumPy and Array API) are already hard coded to not generate shapes with more than 32 dims.

I'm generating `num_shapes`, not `num_dims`. I'm testing a function that takes an arbitrary number of shapes.

**Comment by asmeurer** [comment]
Is it possible to generalise the idea here? It seems like https://github.com/HypothesisWorks/hypothesis/issues/1099 and https://github.com/HypothesisWorks/hypothesis/blob/master/guides/strategies-that-shrink.rst#keep-things-local are basically describing the exact same problem, namely, picking an integer `n` and then flatmapping it into a collection with of size `n`. This can shrink poorly, but, at least based on my example, instead drawing all `max_n` examples then picking a subset does shrink well. It's not clear to me if this will hold in general or if I just got lucky here. But assuming it is generally better, would it be possible to attempt to detect such situations and internally rewrite them? One concern might be that if `n` is much smaller than `max_n`, then you would end up generating a lot that you don't need, so it may need to be done lazily to work, or otherwise have some guards (in my case, generating 32 extra shapes each time isn't a big deal).

I only have a very vague idea of how the hypothesis internals work, so I may be completely off base here.

(an unrelated aside: I just realized I forgot to include `shared` in my reproducing example. It doesn't affect the shrinking behavior as far as I can tell, but omitting it makes the test nonsensical as written)

**Comment by Zac-HD** [comment]
> One concern might be that if n is much smaller than max_n, then you would end up generating a lot that you don't need, so it may need to be done lazily to work, or otherwise have some guards (in my case, generating 32 extra shapes each time isn't a big deal).

This is pretty much it - while your case is small, we might also have very large items or a recursive structure where we can only afford wide+shallow or narrow+deep instances.  It's also inefficient for shrinking, since we have to shrink all of the parts that are present-but-ignored instead of just deleting them.  Overall, I think the status quo is good even if it's imperfect in this specific case.

**Comment by Zac-HD** [comment]
Closing because I don't think we have a solution for this beyond #1187 and the workarounds discussed above.
