### ISSUE TITLE
`st.floats()` generates sub-normal floats

### ISSUE THREAD

**Issue by honno** [HypothesisWorks/hypothesis#3153]
Found on upstream that `st.floats(width=32)` can generate `1.e-45` i.e. a number not representable with a 32-bit float. May be relevant to #2907. I was using CuPy then, so here's a reproducible example with 64-bit floats i.e. Python's builtin and what `st.floats()` defaults to.

```python
# ./hypothesis/hypothesis-python/tests/test_float_bounds.py
import sys

from hypothesis import given, settings
from hypothesis import strategies as st


@given(st.floats(0, sys.float_info.min * 2, allow_nan=False).filter(lambda n: n != 0))
@settings(max_examples=10_000)
def test_sys_bounds_low_max(n):
    assert abs(n) >= sys.float_info.min
...
FAILED tests/test_float_bounds.py::test_sys_bounds_low_max - assert 1e-323 >= 2.2250738585072014e-308
```

~~This might be expected behaviour now that I'm aware of #2976.~~ This is known behaviour to quote from #3152

> It turns out that we can generate subnormal values; it's just that we do so with negligible probability because they only occur for one-in-2^11 possible exponents.

(so I suppose let's wait and see where that PR goes first :sweat_smile:)

**Comment by honno** [comment]
To confirm, NumPy's float64 bounds look the same as Python's builtin float.
```python
>>> sys.float_info.min
2.2250738585072014e-308
>>> np.finfo(np.float64).smallest_normal
2.2250738585072014e-308
>>> 1.1125369292536007e-308 >= sys.float_info.min
False
```

I seemingly can't reproduce this bug with say
```python
@given(st.floats(width=64, allow_nan=False).filter(lambda n: n != 0))
@settings(max_examples=10_000)
def test_64_sys_bounds(n):
    assert abs(n) >= sys.float_info.min
```
so I'll need to try again later :confused: Note `np.finfo(np.float64).smallest_normal` returns a `np.float64` scalar as opposed to a builtin `float`.

**Comment by Zac-HD** [comment]
Working as intended, see #3152 for details.
