### ISSUE TITLE
Stop generating flat indices in `xps.indices()`

### ISSUE THREAD

**Issue by honno** [HypothesisWorks/hypothesis#3166]
The Array API was updated to remove flat indexing in https://github.com/data-apis/array-api/pull/272 i.e. providing a single-axis indexing expression to a higher-dimensional array. This means `xps.indices()` should be updated accordingly.

Already tried fixing this but got caught up with other things. Just writing an issue to keep track and jump-the-gun if others find this problem, but should get to soon.

**Comment by Zac-HD** [comment]
(updated link to point to upstream repo, not our own issue with the same number)
