### ISSUE TITLE
Drop support for Python 3.6 at end of life (2021-12-23)

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#3174]
See https://devguide.python.org/#status-of-python-branches - following #2615 and #2218, we'll want to...

-  [ ] Check `git grep -nE "# pragma: no (branch|cover)|[pP]y(thon)? ?3|sys\.version" -- . ':!*changes.rst'` to see all of the locations we've tagged for version compatibility reasons (and a few false-positives)
- [ ] Bump target versions for `shed` (upstream)

And while we're thinking about end-of-year releases, unlike the last few years I *do not* intend to release a major version: `git grep -A2 note_deprecation\( -- hypothesis-python/src/` shows that our only active deprecations are from [6.19.0](https://hypothesis.readthedocs.io/en/latest/changes.html#v6-19-0) and [6.21.2](https://hypothesis.readthedocs.io/en/latest/changes.html#v6-21-2); too new and too few to justify a major version.

**Comment by sobolevn** [comment]
Can I take this? 🙂 

It would be so satisfying to remove all typing-related hacks we use for `3.6`!

**Comment by Zac-HD** [comment]
Go for it! I'll review and merge 😁

**Comment by sobolevn** [comment]
Do we want to drop `pypy3.6` as well?

**Comment by Zac-HD** [comment]
Yep.  The PyPy devs have already dropped support, so we were just keeping it until the CPython EOL.
