### ISSUE TITLE
Conditional `mock_xp` assignment is awkward for build systems

### ISSUE THREAD

**Issue by coogor** [HypothesisWorks/hypothesis#3178]
Hi, 
I build hypothesis for openSUSE Tumbleweed, and see errors in importing mock_xp which should be in:
https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/extra/array_api.py

[  793s] ____________ ERROR collecting array_api/test_argument_validation.py ____________
[  793s] ImportError while importing test module '/home/abuild/rpmbuild/SOURCES/hypothesis-python-6.30.0/tests/array_api/test_argument_validation.py'.
[  793s] Hint: make sure your test modules/packages have valid Python names.
[  793s] Traceback:
[  793s] /usr/lib/python3.6/site-packages/_pytest/python.py:578: in _importtestmodule
[  793s]     mod = import_path(self.fspath, mode=importmode)
[  793s] /usr/lib/python3.6/site-packages/_pytest/pathlib.py:524: in import_path
[  793s]     importlib.import_module(module_name)
[  793s] /usr/lib64/python3.6/importlib/__init__.py:126: in import_module
[  793s]     return _bootstrap._gcd_import(name[level:], package, level)
[  793s] <frozen importlib._bootstrap>:994: in _gcd_import
[  793s]     ???
[  793s] <frozen importlib._bootstrap>:971: in _find_and_load
[  793s]     ???
[  793s] <frozen importlib._bootstrap>:955: in _find_and_load_unlocked
[  793s]     ???
[  793s] <frozen importlib._bootstrap>:665: in _load_unlocked
[  793s]     ???
[  793s] /usr/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
[  793s]     exec(co, module.__dict__)
[  793s] tests/array_api/test_argument_validation.py:20: in <module>
[  793s]     from tests.array_api.common import xp, xps
[  793s] tests/array_api/common.py:19: in <module>
[  793s]     from hypothesis.extra.array_api import make_strategies_namespace, mock_xp
[  793s] E   ImportError: cannot import name 'mock_xp'

Full log:
https://build.opensuse.org/package/live_build_log/home:DocB:branches:devel:languages:python/python-hypothesis:test/openSUSE_Tumbleweed/x86_64

Any ideas?

**Comment by honno** [comment]
Eek, sorry about that. So I'm pretty ignorant RE building Hypothesis, but it looks like you (understandably) skip importing NumPy, which we check for before creating the `mock_xp` variable.

Can you ignore `tests/array_api` for now? Generally that stuff is unstable and barely used right now.

(It'd be nice if we could support `pytest.importorskip` to cascade with the Array API stuff, hmm...)

**Comment by Zac-HD** [comment]
I think this is simpler - you're trying to run array_api tests on Python 3.6, but they require 3.8 or later.

@honno, I think we just want to add a collection-skip in conftest.py, here https://github.com/HypothesisWorks/hypothesis/blob/31578c7b54a7484626afc405182906cbc4825b04/hypothesis-python/tests/conftest.py#L36-L37
