### ISSUE TITLE
Using Strategies Outside of Given

### ISSUE THREAD

**Issue by jacobseiler** [HypothesisWorks/hypothesis#3199]
I've been using the `data` strategy for the past few months to run and generate complex random examples for my code to be tested against.  The general pattern I am using is something along the lines of...

```python
# test_code.py

def generate_example(hypothesis_data: DataObject) -> int:
    # In practice, strategy is more involved.
    return hypothesis_data.draw(integers())

@given(data())
def test_something(data: DataObject) -> None:
    example: int = generate_example(data)

    # Perform some testing and ensure that ``example`` conforms to the expected values.
    assert isinstance(example, int)
```

I am reaching a point where I now want to use `hypothesis` as the work-horse to generate a large number of random examples which I can then save to disk and perform further analysis and benchmarking.

Specifically, I would like to call `generate_example` from an outside module.  I am however running into the issue of constructing the `hypothesis_data` object without using a `@given` decorator within a testing framework.  I would love to use something along the lines of...

```python
# generate.py

from test_code import generate_example

num_examples: int = 1e6
examples: List[int] = [generate_example(data()) for _ in range(num_examples)]

# Save examples or perform further analysis.
```

Is it possible to do this?  Or am I just completely abusing the purpose of `hypothesis`...

PS I love everything about `hypothesis` :D

**Comment by Zac-HD** [comment]
Hey Jacob!  Glad you're enjoying Hypothesis 😁 

This isn't really what Hypothesis is designed for, but you can get around that with a helper function like 

```python
def generate_examples(strategy, n_examples):
    examples = []

    @settings(max_examples=n_examples, derandomize=True, database=None)
    @given(strategy)
    def helper(x):
        examples.append(x)

    helper()
    return examples()
```

Just remember that custom strategies can produce examples which are only valid *while* the test is running, or have side effects of various kinds.
