### ISSUE TITLE
Support `floats(allow_infinity=False, exclude_max=True)`?

### ISSUE THREAD

**Issue by gjoseph92** [HypothesisWorks/hypothesis#3208]
Related to https://github.com/HypothesisWorks/hypothesis/issues/3207, to solve my actual problem of `floats` producing the largest finite float, I wanted to do something like:
```python
    west = draw(
        st.floats(
            allow_nan=False,
            allow_infinity=False,
            exclude_max=True,
            # ^ hoping this would treat the `max_value` as `sys.float_info.max`, then exclude it
        )
    )
    east = draw(
        st.floats(
            min_value=west,
            allow_nan=False,
            allow_infinity=False,
            exclude_min=True,
        )
    )
```
But of course I got `Cannot exclude max_value=None`.

In this specific case of `allow_infinity=False, {min|max}_value=None`, you could argue that `exclude_{min|max}=True` has pretty unambiguous meaning: make the min/max value the second-smallest/largest-finite float value. Since when `exclude_{min|max}=False` the min/max is implicitly the smallest/largest-finite float value, it seems reasonable that when it's True, you'd simply exclude that value as usual.

Doing this is fine, just a little more work/learning than I'd prefer:
```python
        st.floats(
            max_value=sys.float_info.max,
            allow_nan=False,
            allow_infinity=False,
            exclude_max=True,
        )
```

**Comment by Zac-HD** [comment]
> In this specific case of `allow_infinity=False, {min|max}_value=None`, you could argue that `exclude_{min|max}=True` has pretty unambiguous meaning: make the min/max value the second-smallest/largest-finite float value.

I do follow your logic here, and I agree that this is the natural interpretation of that combination of arguments... but it still feels a bit too magical to me.  Especially for a testing framework like Hypothesis, it's important to catch *misunderstandings* as well as *misuses*, and it's quite plausible to me that people would think that "`exclude_max` has no effect if I don't pass a `max_value`".

I think this is a case we should handle with tighter validation and clearer error messages, so I'll move back to #3207.
