### ISSUE TITLE
`st.functions()` should infer `returns` from the return-type annotation

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#3217]
Currently, [`returns` defaults to `none()`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.functions), even for functions with a return-type annotation where we 'should know better'.

So let's set `returns=...` (see #3188) as the default and then, if the user doesn't pass a strategy, we'll use `from_type()` on the return type annotation or `none()` if unannotated.

(if `from_type()` fails, we'll want to emit a deprecation warning and fall back to `None`; otherwise this might be a breaking change)

**Comment by bibajz** [comment]
Hello @Zac-HD, I really appreciate `hypothesis` and would like to contribute to it!

I have taken a stab at this issue - https://github.com/bibajz/hypothesis/commit/7cabc1aa2f90027c4fdff046d3164fe16d050b54

Have I understood it correctly? Is there anything you would want to add / change?

Thank you,
Libor

**Comment by Zac-HD** [comment]
Hey Libor - thanks for helping out!  You've gotten it exactly right, but - and this is embarrassing - it turns out that the only change we need is actually to update the first line of the docstring, so that our docs show the actual signature!  The feature itself was implemented in #2446, but that PR missed the docs 😓

**Comment by bibajz** [comment]
Got it! To be frank, I was wondering what is this issue about, since the functionality seemed to be already there :D

So, you want to:
1. change the docstring
2. keep the the default `returns` argument as `None`, but add the `HypothesisDeprecationWarning` in the condition, ie:

```
    if returns is None:
        hints = get_type_hints(like)
        if hints.get("return") is None:
            warnings.warn(
                HypothesisDeprecationWarning(
                    "No returns strategy supplied and unable to infer the "
                    "return type of like, falling back to generating None",
                ),
                stacklevel=2
            )
            returns = none()
        else:
            returns = from_type(hints["return"])
```

Is this correct?

**Comment by bibajz** [comment]
Eh, my bad, the `HypothesisDeprecationWarning` is supposed to be issued **irrespective** of the success/failure of type inference, so like this:

```
    if returns is None:
        warnings.warn(
            HypothesisDeprecationWarning(
                "No returns strategy supplied.  Trying to infer strategy from like, "
                "otherwise falling back to generating None",
            ),
                stacklevel=2
            )
        returns = from_type(hints.get("return", type(None)))
```

Now correct? :D
