### ISSUE TITLE
`st.builds` only builds one instance of an object when using optional values with pydantic

### ISSUE THREAD

**Issue by Poogles** [HypothesisWorks/hypothesis#3218]
I'm trying to test an object with many optional pydantic values. I don't seem to be able to get object generation to produce any more than one example of an object?

A test example of the behaviour...

```py
from pydantic import BaseModel
from typing import Optional


class Test(BaseModel):
    name: Optional[str]


def test_example():
    count = 0

    @given(test=strategies.builds(Test))
    @settings(max_examples=500)
    def inner(test):
        nonlocal count
        count += 1

    inner()
    assert count != 1
```

Expected behaviour would be 500 examples, current behaviour here is the assertion fails with 1 = 1. Remove the `Optional` and the test passes as expected with count of 500. I'm not sure if I've missed something here and this behaviour is expected when using nullable values?

The example is formatted as a nested function as I'm looking to use functional fixtures from the higher scope within the test. These functional pytest fixtures are however not required to recreate the behaviour. A shorter example would be...

```py
from pydantic import BaseModel
from typing import Optional


class Test(BaseModel):
    name: Optional[str]


@given(test=strategies.builds(Test))
@settings(max_examples=10000000000)
def test_example(test):
    pass
```

Which completes in under a tenth of a second so I presume also exhibits the same behaviour of only outputting one example?

**Comment by Zac-HD** [comment]
Hmm. My best guess is that pydantic magically sets a default value of this argument to None, confusing the Optional (ie nullable) type for an optional argument.

If I'm right, `builds(Test, name=hypothesis.infer)` will work as expected.

**Comment by Poogles** [comment]
Thanks for taking a look, that does work around the issue which is great. I'll lave the issue open as the problem remains though.

**Comment by Zac-HD** [comment]
Unfortunately this is something that Pydantic just gets wrong, and there's no way that we can work around the surprising behavior in Hypothesis without breaking uses which we *do* want to support 😕

**Comment by Ierezell** [comment]
Hi, I'm sorry to bump this thread but I have the same problem without `Optional`. 

I have a pydantic model generated from a protobuf. 

```python
from typing import List, Dict

from pydantic import BaseModel, Field


class Entity(BaseModel):
    start: int = Field(default_factory=int)
    stop: int = Field(default_factory=int)
    type: str = Field(default_factory=str)
    text: str = Field(default_factory=str)
    value: str = Field(default_factory=str)


class EntityInput(BaseModel):
    utterance: str = Field(default_factory=str)

    class PatternsEntities(BaseModel):
        name: str = Field(default_factory=str)
        regex: str = Field(default_factory=str)

    patternEntities: List[PatternsEntities] = Field(default_factory=list)

    class SynonymsEntities(BaseModel):
        name: str = Field(default_factory=str)
        synonyms: List[str] = Field(default_factory=list)

    synonymEntities: List[SynonymsEntities] = Field(default_factory=list)


class EntityList(BaseModel):
    class Entity(BaseModel):
        start: int = Field(default_factory=int)
        stop: int = Field(default_factory=int)
        type: str = Field(default_factory=str)
        text: str = Field(default_factory=str)
        value: str = Field(default_factory=str)

    entities: List[Entity] = Field(default_factory=list)


class EntityOutput(BaseModel):
    entities_per_lang: Dict[str, EntityList] = Field(default_factory=dict)


class PatternsEntities(BaseModel):
    name: str = Field(default_factory=str)
    regex: str = Field(default_factory=str)


class SynonymsEntities(BaseModel):
    name: str = Field(default_factory=str)
    synonyms: List[str] = Field(default_factory=list)
```

and when I use it in a test : 

```python
@given(instance=st.builds(EntityInput))
@settings(deadline=None, max_examples=500)
def test_entities_entities(instance: EntityInput, client: TestClient):
    response = client.get("/")

    assert response.status_code == 200
    print(instance.dict())
    response = client.post("/inference", json=instance.dict())
    print(response.json())
    assert response.status_code == 200
```

I only get once
```python
{'utterance': '', 'patternEntities': [], 'synonymEntities': []}
```

I can use `utterance=hypothesis.infer` which will indeed generate many utterances but will keep all the lists empty. 

I there any solution for that ? 

I don't know how to make pydantic model work other than re-explicitely redefine all by hand (then I will just use all the nice feature of hypothesis). 

Thanks in advance,
Have a great day

**Comment by Ierezell** [comment]
Hi @Zac-HD, Thanks for the fast reply ! :) 

Is there any way to have automated infer or is it not supported at all?
I don't mind modifying my pydantic file, changing typings, using pydantic defaults or fancy methods. 

Thanks for your help.
