### ISSUE TITLE
Feature request: Timeseries strategy

### ISSUE THREAD

**Issue by fleimgruber** [HypothesisWorks/hypothesis#3220]
I am reading into and playing around with Hypothesis for the scientific stack. Are there plans or would you be open to include timeseries strategies? A timeseries in this context would be a monotonically increasing series of `datetime` (or even `pandas.Timestamp`) values. The timeseries could be further distinguished in equidistant, i.e. constant time delta between successive values, or non-equidistant. What do you think in general about that feature? Or is this already possible by defining global constraints for a set of generated strategy values?

I guess we could also take the general discussion to IRC. I assume #hypothesis irc channel moved to libera.chat? Maybe it would be good to update the [docs](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/docs/community.rst#community)?

**Comment by Zac-HD** [comment]
I think we already have these features, but perhaps a short writeup for https://hypothesis.works/articles would be useful?

- for evenly-spaced, `st.builds(pd.date_range, ...)`
- for unevenly-spaced, `pdst.indexes(...).map(lambda idx: idx.sort_values())`

I'm honestly not sure about IRC; I've never really used it sorry!

**Comment by Zac-HD** [comment]
> But there usually are more requirements, e.g. start and end dates should be aligned at the natural interval boundaries, so for a time resolution of 15 minutes, the stamps should be xy:00:00, xy:15:00, xy:30:00, etc.

I'd use `.map(lambda d: d.replace(minutes=15 * (d.minutes // 15), seconds=0, microseconds=0))` on the elements strategy for this.

> Maybe if that is needed one should generate a set of possible timestamps (e.g. via pd.date_range) and then let Hypothesis choose random subsets of these?

Also a reasonable approach!

Closing this because I think we've solved your problem; I'd be happy to accept a writeup describing this but don't think we need to add new code.

**Comment by fleimgruber** [comment]
Thanks for your support!
