### ISSUE TITLE
Breakpoints ignored when debugging in vscode

### ISSUE THREAD

**Issue by tekumara** [HypothesisWorks/hypothesis#3226]
In VS Code a breakpoint on the assert line will not be hit, eg:

```python
from hypothesis import given
from hypothesis import strategies as st

from  statistics import mean

@given(st.lists(st.floats(allow_nan=False, allow_infinity=False), min_size=1))
def test_mean(xs):
    assert min(xs) <= mean(xs) <= max(xs)
```

Hypothesis version: 6.26.1
Vscode version: 1.64.0 (commit 5554b12acf27056905806867f251c859323ff7e9)
OS: Darwin x64 21.3.0

**Comment by Zac-HD** [comment]
What makes you think this is a bug in Hypothesis, rather than VS Code?

**Comment by tekumara** [comment]
This also happens in PyCharm and pdb. IIUC any debugger that uses `sys.settrace` will have its breakpoints ignored because Hypothesis resets `sys.settrace` to [install its own tracer](https://github.com/HypothesisWorks/hypothesis/blob/09e5035edbb68fafb1012c0e910da31d1bc3b370/hypothesis-python/src/hypothesis/core.py#L691).

However from reading the  [docs](https://hypothesis.readthedocs.io/en/latest/settings.html?highlight=debugger#controlling-what-runs) I was expecting this wouldn't be the case if `sys.settrace` is already in use:

> This relies on [sys.settrace()](https://docs.python.org/3/library/sys.html#sys.settrace), and is therefore automatically disabled on PyPy or if you are using [coverage](https://pypi.org/project/coverage/) or a debugger.

**Comment by Zac-HD** [comment]
https://github.com/HypothesisWorks/hypothesis/blob/b4addaf771a2acd3cd879dba3998d95fcb0ac0b5/hypothesis-python/src/hypothesis/core.py#L679-L697

Looking at the context for this line, we only set our own trace function if (1) the `explain` phase is enabled, and (2) `sys.gettrace() is None`.  Looking [at the `pdb` source code](https://github.com/python/cpython/blob/3.10/Lib/pdb.py#L1095-L1113), they don't even check if there's already a trace function - and would clobber it if there was.

Do you have the explain phase enabled?  Does the problem occur with it disabled?

**Comment by tekumara** [comment]
Huh, thanks for sharing that snippet, it looks like this isn't about `sys.settrace` after all. I have the default settings, which don't include `Phase.explain`. When I debug into the snippet (which works with vscode) I see it's skipping over that block and not setting the hypothesis tracer.

When using `pytest --trace` to enable pdb, the breakpoint does work (I was using `python -m pdb` and then `import pytest; pytest.main()` before which doesn't seem to hit breakpoints even without hypothesis).

So that narrows it down to something vscode & hypothesis specific. So I've raised https://github.com/microsoft/debugpy/issues/837

**Comment by Zac-HD** [comment]
I'm confident that this is not a bug in Hypothesis then - thanks for the detailed investigation and following up upstream!
