### ISSUE TITLE
DataFrames: columns strategy running out of entropy?

### ISSUE THREAD

**Issue by fleimgruber** [HypothesisWorks/hypothesis#3227]
This is a follow up on https://github.com/HypothesisWorks/hypothesis/issues/3220#issuecomment-1016340306 (approach from last paragraph that was deemed reasonable) which I tried in https://stackoverflow.com/a/70921159/1841459, but found Stackoverflow comments inferior to Github issues - please let me know if you want to continue on Stackoverflow regardless.

For the concrete question: I do not understand why for this snippet the column values are mostly all zero (empirically) although the search space of possible strategies is much more reduced than in previous examples:

```python
from datetime import datetime
import math

import hypothesis.strategies as st
from hypothesis.extra.pandas import columns, data_frames
import pandas as pd

time_start = datetime(2022, 4, 1, 8, 0, 0)
time_stop = datetime(2022, 4, 2, 8, 0, 0)
r = pd.date_range(start=time_start, end=time_stop, freq="15T")

def build_indices(sequence):
    first = 0
    if len(sequence) % 2 == 0:
        mid_ceiling = len(sequence) // 2
        mid_floor = mid_ceiling - 1
    else:
        mid_floor = math.floor(len(sequence) / 2)
        mid_ceiling = mid_floor + 1
    second = len(sequence) - 1
    return first, mid_floor, mid_ceiling, second

first, mid_floor, mid_ceiling, second = build_indices(r)

a = st.integers(min_value=first, max_value=mid_floor)
b = st.integers(min_value=mid_ceiling, max_value=second)

def indexer(sequence, lower, upper):
    return sequence[lower:upper]

dfs = data_frames(
    index=st.builds(lambda lower, upper: indexer(r, lower, upper), lower=a, upper=b),
    columns=columns("A B C".split(), dtype=int),
)
dfs.example()
```
note that the things left for hypothesis to choose are the integer strategies `a` and `b`.

**Comment by Zac-HD** [comment]
Like for Numpy arrays, we almost always generate *sparse* dataframes, by picking a fill value and then setting particular other locations to other values.  Zero, being the simplest element, is also the most common fillvalue.

StackOverflow is probably a better place for usage-like questions that other people might search for, though questions and this--might-be-a-bug reports are welcome on GitHub too.  We don't have a firm policy, since most people probably wouldn't read it anyway, and this one would be fine on either :sweat_smile:

**Comment by fleimgruber** [comment]
@Zac-HD thanks for checking back and the explanations!

So the entropy issue you mentioned in https://stackoverflow.com/a/70921159/1841459 or this fillvalue behavior can lead to the observed results. So the next question would be how users should configure this for more uniformly distributed test examples. I tried by changing the last bits to

```
dfs = data_frames(
    index=st.builds(lambda lower, upper: indexer(r, lower, upper), lower=a, upper=b),
    columns=columns("A B C".split(), elements=st.integers(min_value=1, max_value=10)),
)
```
which mostly results in `1` values in the columns instead of zeros.

**Comment by Zac-HD** [comment]
If you don't want the sparse behaviour, I'd turn to `st.builds(pd.DatafFrame, ...)`.  In practice sparse dataframes tend to find more bugs per minute than dense though!

**Comment by fleimgruber** [comment]
Thanks for the suggestion and the hint about BPM. Then I guess it is a case by case decision whether to do something like
```python
import hypothesis.strategies as st
import pandas as pd

N = 3
st.builds(
    pd.DataFrame,
    data=st.dictionaries(
        st.sampled_from(["a", "b", "c"]),
        st.lists(st.integers(), min_size=N, max_size=N),
        min_size=1,
        max_size=3,
    ),
    index=st.just(range(1, N + 1)),
).example()
```
or using the `hypothesis.extra.pandas` tools. For making the correct decision I will need to experiment more, get more comfortable with property based testing in general and apply it to real problems. Last question: Do you know a code base to study for use cases of `hypothesis.extra.pandas`? Or would you suggest reading the Hypothesis source?

**Comment by Zac-HD** [comment]
Yeah, that looks good to me.  I think that my final tip is that we haven't found that sparsity harms bug-finding at all - if it did, we wouldn't use it!  The key details is to avoid ever excluding things that could be possible - e.g. is your function *really* never going to be called with NaN?  Or zero rows? etc.

Unfortunately I don't know of any open-source codebases to study - I think Pandas itself uses this but only for a small number of tests.  [here's a github search which tries to filter out homework-cheating spam](https://github.com/search?l=&p=8&q=hypothesis.extra.pandas+extension%3Apy+-user%3Ahongyujiang+-user%3Acsmyang+-user%3Akodybeattie+-user%3Amartinyang0416+-user%3Ayangkian+-path%3Acsc108a3+-path%3Apyta+-path%3Abridges%2Fpyta+-path%3Aa1%2Fpyta+-path%3Aa2%2Fpyta+-path%3Aa3%2Fpyta+-path%3A2018summer+-path%3A2018fall+-path%3Asrc%2Fta_lib+-repo%3Ahypothesisworks%2Fhypothesis&ref=advsearch&type=Code), there's at least some useful stuff in there.

**Comment by fleimgruber** [comment]
Thanks for feedback and the tip, I can see how thorough testing needs to include all the corner cases and things not usually thought of.

Thanks as well for the canned github search, will have a look into it!
