### ISSUE TITLE
tests passing unexpectedly for nested `builds` 

### ISSUE THREAD

**Issue by peterbplanetly** [HypothesisWorks/hypothesis#3233]
The test below passes for me every time, even though I'm pretty sure it shouldn't. I would expect hypothesis to try at least some input with a non-`None` `child.age`. Perhaps I am doing something wrong with `builds`, however I couldn't see any reason why this shouldn't work from the docs.

This matters because it leads to tests silently passing, without actually doing anything useful. 

```py
class Child(pydantic.BaseModel):
    name: str
    age: Optional[int]


class Parent(pydantic.BaseModel):
    child: Child


@hypothesis.strategies.composite
def child_strategy(draw):
    return draw(
        hypothesis.strategies.builds(
            Child,
            name=hypothesis.strategies.sampled_from(["harry", "cloe", "paul", "anna"]),
        )
    )


@hypothesis.given(hypothesis.strategies.builds(Parent, child=child_strategy()))
def test_i_should_fail(parent):
    assert parent.child.age is None
```

**Comment by honno** [comment]
This seems to be a bug(?) with Pydantic, see https://github.com/HypothesisWorks/hypothesis/issues/3218#issuecomment-1012344510

**Comment by Zac-HD** [comment]
Yep. Hypothesis is working as intended here, the problem is that Pydantic treats Optional as "as a default argument" as well as "may be None".

**Comment by peterbplanetly** [comment]
thanks for the insight! interesting & unfortunate..

**Comment by peterbplanetly** [comment]
https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.builds

> You can also tell builds to infer a strategy for an optional argument by passing the special value [hypothesis.infer](https://hypothesis.readthedocs.io/en/latest/details.html#hypothesis.infer) as a keyword argument to builds,

@Zac-HD so, if i understand correctly, in general (irrespective of pydantic) hypothesis `builds` will only fuzz non-optional arguments? what is the reason for that? why not also fuzz the other arguments? what makes arguments with a default value "special"?

**Comment by Zac-HD** [comment]
Because `st.builds()` just calls whatever callable you pass it - the only *special* thing is that if you omit a required argument, `builds()` will try to infer it from the type annotation.  Maybe doing that without an explicit `=infer` was a mistake!

You may find `st.from_type()` and `st.register_type_strategy()` a better fit for what you're trying.
