### ISSUE TITLE
Disable the generation of .hypothesis/ file 

### ISSUE THREAD

**Issue by abdelatiff** [HypothesisWorks/hypothesis#3242]
I want to disable the generation of .hypothesis/ file while running my tests, i've found an option just to ignore the database folder coming from examples, but i want to disable the whole directory form being generated and i didn't found any settings option or parameters that do this.

Any advice 

Thank you

**Comment by Zac-HD** [comment]
The location of the `.hypothesis` directory can be set by the `HYPOTHESIS_STORAGE_DIRECTORY` environment variable, and if you set it in a non-writable location then it won't be written.

I'd encourage you to add `.hypothesis` to your `.gitignore` or similar instead though, there are a few caches in there which really help with performance and ongoing user experience.

**Comment by rsokl** [comment]
The [`settings` object](https://hypothesis.readthedocs.io/en/latest/settings.html#available-settings) also has a `database` argument, which you can set to `None`. 

```python
@settings(database=None)
@given(st.integers())
def my_test(x): ...
```
This will prevent `.hypothesis` directory from being run when `my_test` is called. This is useful when you are running tests as part of a demonstration or tutorial.

**Comment by Zac-HD** [comment]
@rsokl, no, `.hypothesis` might also be created to memoize some internal calculations for `st.text()`, for example.

**Comment by rsokl** [comment]
Ah, whoops! Sorry about that. I had used `deadline=None` in some cases to the desired effect. Didn't realize things like `st.text()` could make it manifest regardless!

**Comment by abdelatiff** [comment]
Thank you guys for these informations, but the solution didn't work i jutst put `HYPOTHESIS_STORAGE_DIRECTORY` like this 
`export HYPOTHESIS_STORAGE_DIRECTORY="$HOME/.cache/`
but the .hypothesis  folder still being generated in my current folder and contains these informations: 
![tempsnip](https://user-images.githubusercontent.com/82164256/156124649-65c91146-655d-4307-b40a-fab3f1eadb87.png)
