### ISSUE TITLE
Deadline or timeout for shrinkage

### ISSUE THREAD

**Issue by SmokinCaterpillar** [HypothesisWorks/hypothesis#3243]
Currently there can only be a deadline defined for single examples (https://hypothesis.readthedocs.io/en/latest/settings.html). It would be cool to have the same for shrinkage as well.

We often need to build complex nested examples, which usually works well, unless something breaks and hypothesis needs to do shrinkage. Then shrinkage takes several minutes.

Could there some `@settings` like `deadline_shrinkage` that basically stops shrinkage after `deadline_shrinkage` seconds (milliseconds?) and just shows the smallest example it found up until that point?

**Comment by Zac-HD** [comment]
We do have an internal non-configurable timeout for shrinking, but I wouldn't want to expose this as a user setting. Turning the shrink phase off entirely might auit you though?

Also, if you can share the slow complex strategy I suspect it can be made considerably faster!
