### ISSUE TITLE
Statefull: parameters are getting from the same bundle

### ISSUE THREAD

**Issue by angel-popov** [HypothesisWorks/hypothesis#3249]
I have a rule that consumes from two bundles, but generated test consumes parameters from the one bundle.
rule looks like:
```   
    @rule(b1=consumes(b1), b2=consumes(b2),
          targets=(b1,b2))
    def just_check(self, b1, b2):
        assert b1=="b1"
        assert b2=="b2"
        return multiple("b1","b2")
```
but in falsifying example, we see that b1 and b2 are getting from v2. 
Expected is b1 to be from v1, and b2 to be from v2
```Falsifying example:
state = Minimal()
v1, v2 = state.init_patient()
state.just_check(b1=v2, b2=v2)
state.teardown()
Traceback (most recent call last):
  File "/home/apopov/work/care/APSSimulator/p2p/src/tmpmodel.py", line 18, in just_check
    assert b1=="b1"
```

The example that I am running is:
```
from hypothesis import settings, Verbosity
from hypothesis.stateful import Bundle, RuleBasedStateMachine, rule, initialize, consumes, run_state_machine_as_test, multiple


class Minimal(RuleBasedStateMachine):
    b1=Bundle("b1")
    b2=Bundle("b2")
    def __init__(self):
        super().__init__()

    @initialize(targets=(b1,b2))
    def init_patient(self):
        return multiple("b1","b2")

    @rule(b1=consumes(b1), b2=consumes(b2),
          targets=(b1,b2))
    def just_check(self, b1, b2):
        assert b1=="b1"
        assert b2=="b2"
        return multiple("b1","b2")
        
run_state_machine_as_test(Minimal, settings=settings(verbosity=Verbosity.verbose))
```
The execution was done with version:6.39.1 from pypi,

**Comment by Zac-HD** [comment]
No, these parameters are getting the values from *different* bundles - but the rule is adding results to *both* of the bundles.

```python
    @rule(targets=(b1,b2))
    def just_check(self):
        return multiple("v1", "v2", "v3")
```

will add `"v1"` and `"v2"` and `"v3"` to *both* the `b1` and `b2` bundles.

It might help to look at the reproducing example, and think of `b1` and `b2` as "sets of variables which can be used as arguments".  We just assign `v1, v2, v3 = self.just_check()` - and *all three* of those variables are added to *both of* the `targets` bundles.

**Comment by angel-popov** [comment]
Thanks for quick response, It makes sense that way,
