### ISSUE TITLE
How to avoid "The database setting is not configured" warning

### ISSUE THREAD

**Issue by javierggt** [HypothesisWorks/hypothesis#3254]
Hi,

I am getting the following warning from my unit tests running pytest:
```
HypothesisWarning: The database setting is not configured, and the default location is unusable - falling back to an in-memory database for this session.
```
This happens because I am running in a directory where I have no write access (why that is the case is besides the point) and hypothesis tries to create a directory `.hypothesis/examples`.

None of my tests use hypothesis, and I have more than 30 separate packages, so I am a bit reluctant to go and explicitly disable hypothesis in each and every one of them, especially when I don't need it enabled at all.

I have tried running pytest with the following options, which I think should be reasonable solutions, but none works:
- `--hypothesis-verbosity=quiet` option. I still get the warning.
- `--hypothesis-profile=no_database` option. I get the `Profile 'no_database' is not registered` error.
- `-Wignore:"The database setting is not configured"`. I still the get the warning because pytest does not recognize it as a warning (it does not show up in the warnings summary at the end).

Is there a way to not have this warnings in my tests?

**Comment by Zac-HD** [comment]
https://hypothesis.readthedocs.io/en/latest/settings.html#settings-profiles
