### ISSUE TITLE
PEP 604 not supported - exception when writing union types X | Y

### ISSUE THREAD

**Issue by MPalarya** [HypothesisWorks/hypothesis#3255]
hypothesis is not recognizing the new bar-annotation for union types as a valid type on python 3.10+
resulting in an exception, see minimal reproduction example below -

```python
from typing import Optional, Union
from dataclasses import dataclass

@dataclass
class A:
    x: str | None

@dataclass
class B:
    x: Union[str, None]

@dataclass
class C:
    x: Optional[str]

>>> st.from_type(A).example()
hypothesis.errors.InvalidArgument: thing=str | None must be a type

>>> st.from_type(B).example()
B(x='\U00076342v¯\\\x8cî£\x00\x7f±b')

>>> st.from_type(C).example()
C(x='鏀\U00109e07h\x81ø\x9a\x9c\U0010a5e3\x8e=û')
```

**Comment by Zac-HD** [comment]
Thanks for reporting this - #2979 has been open for nearly a year now, we definitely want it to work but nobody has yet volunteered to work on it.  

(If you'd be interested in contributing, I'm happy to help out!)
