### ISSUE TITLE
Trying to resolve or register 'metadata' like `typing.Annotated` should be an error

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#3280]
Based on the [`typing` module docs](https://docs.python.org/3/library/typing.html), here's a list of 'metadata types'.  We should raise an explicit error if the user attempts to register or resolve them.
- [x] `Annotated` - #3082 handled the cases where we want to resolve it; but we still need to ban registering it or attempting to resolve bare `Annotated`
- [x] `ClassVar`
- [x] `Final`
- [x] `TypeAlias`
- [x] `Concatenate` and `ParamSpec` can never be registered or resolved
  - [x] and the `Callable` resolver should give a specific error message if it sees these types
- [x] `TypeGuard` can never be registered, returns `st.booleans()` for any inner type.
  - [x] resolving a callable with a TypeGuard return annotation should be an explicit error (per the PEP and because we can't actually produce such callables)
- [x] `Self` type (ban)
- [x]  `Never` (like `NoReturn`)
- [x] `TypeVarTuple`
- [x] `Unpack`
- [x] `LiteralString` can be banned for now; we can revisit later.
- [x]  `Required` and `NotRequired` (ban registration, resolve as inner type or error if bare).  They are already [implemented in `typing_extensions`](https://github.com/python/typing/blob/45895708e2afcef001650f7565e119a9d650f3d7/typing_extensions/CHANGELOG#L20) [and `mypy`](https://mypy-lang.blogspot.com/2021/12/mypy-0930-released.html)

(replaces #2978 to omit rambling discussion while we worked out what to do)

**Comment by Cheukting** [comment]
I will first add all the types that we straightly ban if having no args in the `NON_RUNTIME_TYPES` then will look at the individual ones seperately.

**Comment by Cheukting** [comment]
The only task that #3331 does not cover is the resolver for `Required` and `NotRequired`

**Comment by Zac-HD** [comment]
Opened a new issue just for that remaining task, since it's quite different to banning the unresolvable types 👍 

Thanks again Cheuk!
