### ISSUE TITLE
Does `from_type()` handle `typing.Protocol` properly?

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#3281]
Back in #2979, I wanted to check that [`typing.Protocol`](https://docs.python.org/3/library/typing.html#typing.Protocol) was handled properly.  Per https://github.com/HypothesisWorks/hypothesis/compare/master...Zac-HD:from-protocol-error I think that we just can't handle non-runtime-checkable protocols at all (since, well, we're checking at runtime).

- [x] Ensure that we have a good error message for non-runtime-checkable protocols, c.f. https://github.com/HypothesisWorks/hypothesis/compare/master...Zac-HD:hypothesis:from-protocol-error
- [x] Handle checkable protocols.  Options include making them work, ensuring the error message is good, writing up a more detailed issue for later action.
- [x] If we don't already test the items above, write tests for them.

**Comment by rsokl** [comment]
> we just can't handle non-runtime-checkable protocols at all (since, well, we're checking at runtime)

We aren't really checking at runtime, are we? We are drawing values that satisfy the protocol at runtime (although I imagine `from_type` might then do an `assert` to check the type at the end). We could always *make* the protocol be runtime checkable!

```python
from typing import runtime_checkable

Prot = runtime_checkable(Prot)
```

> Options include making them work

There could be some pretty interesting work to be done here. I have a [soft](https://github.com/pydata/xarray/issues/6462) [spot](https://github.com/carbonplan/xarray-schema/issues/31) [for](https://github.com/microsoft/pyright/issues/1956) [protocols](https://github.com/mit-ll-responsible-ai/hydra-zen/blob/5de7899cdf3037316675d3cdafa8da26f717155c/src/hydra_zen/typing/_implementations.py#L87-L112), so maybe we could chat some time about this! 😄

**Comment by Cheukting** [comment]
> Options include making them work

I wonder how we can make them work? Getting all classes that fit the given Protocol?

**Comment by Zac-HD** [comment]
> I wonder how we can make them work? Getting all classes that fit the given Protocol?

*If and only if they're runtime-checkable*, we can check whether each already-registered type satisfies the protocol, yep.

(Using [`gc.get_objects()`](https://docs.python.org/3/library/gc.html#gc.get_objects) to find every such defined type would be going a bit too far even for me.)

**Comment by Cheukting** [comment]
@Zac-HD I would like a bit more of an explanation about what do you mean by `already-registered type`? So it is provided by the user? 

Maybe I misunderstand what is the difference between runtime-checkable and non-runtime-checkable? AFAIK (reading https://docs.python.org/3/library/typing.html#typing.Protocol) the runtime-checkable can be checked with `isinstance` but otherwise what are the differences?

**Comment by Zac-HD** [comment]
Already-registered types are the keys in `_global_type_lookup`, whether set in that module or supplied by calls to `st.register_type_strategy()`.

https://github.com/HypothesisWorks/hypothesis/blob/74f1da82e633180e96c7f10f8caa3a5d92d3cd8f/hypothesis-python/src/hypothesis/strategies/_internal/types.py#L476-L478

The way that `st.from_type()` works is, roughly: (1) a pile of special cases for generics/annotated types/etc, (2) check if the type is in  `_global_type_lookup` or if any of the registered types are subclasses of the thing we're trying to resolve, (3) try to use `st.builds()`.

The catch is that (1) doesn't apply, (2) can only work for runtime-checkable protocols because of the subclass check, and (3) doesn't work because you can't instantiate a protocol.  Mostly I just want to make sure that (1) gives a good message for non-runtime-checkable protocols.

**Comment by Rik-de-Kort** [comment]
I don't think this has been tested properly. Here's an example:

```python
import typing

from hypothesis import given, strategies as st

@typing.runtime_checkable
class NoMethods(typing.Protocol):
    x: float

@given(st.from_type(NoMethods)
def test_can_handle_methodless_protocols(data):
    assert data.x is not None
```

Fails with message:
`FAILED test.py::test_can_handle_methodless_protocols - TypeError: Protocols with non-method members don't support issubclass()`

<details>
<summary>Full test output</summary>
============================================================ test session starts ============================================================
platform linux -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/rik
plugins: hypothesis-6.91.0
collected 1 item

test.py F                                                                                                                             [100%]

================================================================= FAILURES ==================================================================
___________________________________________________ test_can_handle_methodless_protocols ____________________________________________________

    @given(st.from_type(NoMethods))
>   def test_can_handle_methodless_protocols(no_methods):

test.py:10:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
venv/lib/python3.11/site-packages/hypothesis/core.py:642: in process_arguments_to_given
    s.validate()
venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/strategies.py:417: in validate
    self.do_validate()
venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/lazy.py:135: in do_validate
    w.validate()
venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/strategies.py:418: in validate
    self.is_empty
venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/strategies.py:136: in accept
    recur(self)
venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/strategies.py:132: in recur
    mapping[strat] = getattr(strat, calculation)(recur)
venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/deferred.py:65: in calc_is_empty
    return recur(self.wrapped_strategy)
venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/deferred.py:35: in wrapped_strategy
    result = self.__definition()
venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/core.py:1212: in <lambda>
    lambda thing: deferred(lambda: _from_type(thing)),
venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/core.py:1385: in _from_type
    strategies = [
venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/core.py:1385: in <listcomp>
    strategies = [
venv/lib/python3.11/site-packages/hypothesis/strategies/_internal/core.py:1391: in <genexpr>
    and issubclass(k, thing)
<frozen abc>:123: in __subclasscheck__
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

other = <class 'BaseExceptionGroup'>

    def _proto_hook(other):
        if not cls.__dict__.get('_is_protocol', False):
            return NotImplemented

        # First, perform various sanity checks.
        if not getattr(cls, '_is_runtime_protocol', False):
            if _allow_reckless_class_checks():
                return NotImplemented
            raise TypeError("Instance and class checks can only be used with"
                            " @runtime_checkable protocols")
        if not _is_callable_members_only(cls):
            if _allow_reckless_class_checks():
                return NotImplemented
>           raise TypeError("Protocols with non-method members"
                            " don't support issubclass()")
E           TypeError: Protocols with non-method members don't support issubclass()

/usr/lib/python3.11/typing.py:2066: TypeError
========================================================== short test summary info ==========================================================
FAILED test.py::test_can_handle_methodless_protocols - TypeError: Protocols with non-method members don't support issubclass()
============================================================= 1 failed in 0.26s =============================================================
</details>
