### ISSUE TITLE
`floats` not testing min and max values

### ISSUE THREAD

**Issue by aperezlebel** [HypothesisWorks/hypothesis#3283]
Hello,

From reading the [docs](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.floats), I would expect `hypothesis.strategies.floats` to test for edge cases (e.g `min_value` or `max_value` when `exclude_min=False` or `exclude_max=False`).

However, I noticed these values are not tested. For example the following test never fails although it generates 100 examples.

```python
from hypothesis import given
from hypothesis.strategies import floats


@given(x=floats(-1, 1, exclude_max=False, exclude_min=False))
def test_floats(x):
    assert x != 1
    assert x != -1
```

Is this an expected behavior?

Versions:
```
hypothesis    6.41.0          pyhd8ed1ab_0          conda-forge
pytest        7.1.1           py310hff52083_1       conda-forge
python        3.10.4          h2660328_0_cpython    conda-forge

```

**Comment by Zac-HD** [comment]
It's a known and undesired behaviour, but as we describe in #2942 and #2907 it's also pretty tricky to improve.  That said, I'd be delighted to offer suggestions and review if you're interested in improving the situation 🙂
