### ISSUE TITLE
Django database access within @given()

### ISSUE THREAD

**Issue by Dresdn** [HypothesisWorks/hypothesis#3300]
I'm not quite sure if this should be reported here, so apologies if so. The short of it is, I'm trying to build a strategy to use in a `given()` by defining a field using either a pytest fixture or data created by a fixture. Looking at it, I might be running into a chicken and egg type situation.

Here's shortened code to help illustrate what I'm trying to accomplish. The idea is that creating a `Company` object involves a lot of operations and since it's not really what is under test, I'd like to just re-use an existing instance that's created within a `@pytest.fixture(autouse=True)`

```python
@pytest.fixture()
def company(db):
   """Example fixture that could be used within @given(django.from_model(...)) below."""
    return Company.objects.get(name="foo")

def asset_strategy():
    company = Company.objects.get(name="foo")
    return django.from_model(
        Asset,
        owner=django.from_model(User),
        company=st.just(company),
    )

@pytest.mark.django_db()
class TestAsset(django.TestCase):

    @given(asset_strategy())  # or somehow use the company fixture in defining a strategy here
    def test_model_properties(self, instance: Asset):
        assert isinstance(instance.company, Company)
```

Ultimately this is throwing a pytest-django `RuntimeError: Database access not allowed` error, but I feel like I'm just not initializing Hypothesis correctly. From what I can tell, the reason being is that I feel the database error is occurring because Hypothesis is calling the `asset_strategy()` before pytest can set up the database connection and execute any autouse fixtures.

Any thoughts on how best to proceed?

**Comment by Zac-HD** [comment]
Hmm.  Keep in mind that I'm not a Django expert, but I think the main problem is that you can't use fixtures from strategies like this - only if you construct the strategy *in your test* and then draw from it with `st.data()`, at which point you're really just using a value, not a fixture.

More concretely, I think you want to do something like:

```python
def asset_strategy(company_name="foo"):
    return django.from_model(
        Asset,
        owner=django.from_model(User),
        company=st.builds(Company.objects.get, name=st.just(company_name)),
    )
```

And for more complex logic, you'll probably want to turn to the `@st.composite` decorator - e.g. if you wanted to pick an owner *from `User`s associated with the company*.

**Comment by Dresdn** [comment]
That's extremely helpful. Thank you @Zac-HD!
