### ISSUE TITLE
Regression in register_type_strategy

### ISSUE THREAD

**Issue by pejter** [HypothesisWorks/hypothesis#3304]
The nested type support is a [long standing issue in mypy](https://github.com/python/mypy/issues/731) and until it's implemented the recommended solution is to use typing.Any in place of nested types. We do exactly that and then use hypothesis to register a type strategy for Any in order to test it with `st.recursive()`

[Fix tests for Python 3.11](https://github.com/HypothesisWorks/hypothesis/commit/8cf60be0286fac00e676fc584551ecb5381465fa) breaks that by adding typing.Any to `NON_RUNTIME_TYPES`

I think it's important to preserve the ability to register typing.Any, since it's a popular issue in typed code to have Any as even the stdlib does that for the json.dumps input object.

**Comment by Zac-HD** [comment]
Oh, this is an unfortunate situation! Can you please share some example code for a regression test?

**Comment by pejter** [comment]
Anything registering on typing.Any will break it, but here is a simple example:
```python
from typing import Any
import hypothesis.strategies as st

st.register_type_strategy(Any, st.none())
```
and here is a real world one we're doing, for illustration:
```python
LLONG_MIN = -9223372036854775807
ULLONG_MAX = 18446744073709551615

json = st.recursive(
    st.none()
    | st.binary()
    | st.booleans()
    | st.integers(min_value=LLONG_MIN, max_value=ULLONG_MAX)
    | st.floats(allow_nan=False)
    | st.characters(blacklist_categories=["Cs"]),
    lambda children: st.lists(children) | st.dictionaries(st.text(printable), children),
)


class TestWorker(unittest.TestCase):
    def setUp(self) -> None:
        st.register_type_strategy(Any, json)
...
```

**Comment by Zac-HD** [comment]
My concern is mostly that this is pretty fragile - it'll tend to go badly when you have more than one recursive type in your codebase, for example, and registering locally isn't a perfect defence against all our internal caches.

I wonder if we can find a design that solves the problem of recursive types in a more principled way - e.g. adding an `any_means_recursion: bool` flag to `st.from_type()`, or something along those lines.

----------

For your real-world example, some more context to motivate this would also be useful, so that I can feel out the space of alternative solutions - I do understand the immediate regression, and will revert that patch if absolutely necessary to support your workflow, but I think there's a good chance we can come up with something better 🙂

**Comment by Zaharid** [comment]
I have a test file defining

```
@dataclasses.dataclass
class Db:
    metadata: Mapping[str, Any]
    flags: Set[Flag]
    rows: List[Row]
    size: MemOptions = MemOptions.SMALL
    attributes: Attributes = Attributes.READ | Attributes.WRITE
```

where the type annotations have runtime significance for the functionality. I would like to generate tests  with random samples from that type, but I don't really care what is in the `metadata` field so I had set

```
register_type_strategy(Any, booleans())

def invert_db(db):
    db = dataclasses.asdict(db)
    db['flags'] = list(map(dataclasses.asdict, db['flags']))

    def invert_row(row):
        # row = dataclasses.asdict(row)
        row['values'] = list(row['values'])
        return row

    db['rows'] = list(map(invert_row, db['rows']))
    db['metadata'] = dict(db['metadata'])
    db['size'] = db['size'].name
    db['attributes'] = list(
        m
        for m in Attributes.__members__
        if Attributes.__members__[m] in db['attributes']
    )
    return db


dbstrat = builds(Db).map(invert_db)


@given(dbstrat)
def test_arbitrary_valid(db):
    parse_input(db, Db)

```

This was working fine (even if one can argue it was somewhat brittle) until the update in hypothesis made it throw an error.

**Comment by Zac-HD** [comment]
The recommended approach would be:

```python
metadata_strat = st.dictionaries(st.text(), st.booleans())
dbstrat = builds(Db, metadata=metadata_strat).map(invert_db)

# and optionally,
st.register_type_strategy(Db, dbstrat)
```

Your current approach is *super* brittle and was never intended to work at all 😬

**Comment by pejter** [comment]
If recursive typing would be a thing we'd use something like this one, that would be then used as the return type of a few internal serialization functions.
```python
Serializable = Union[
    KeyTypes,
    dict[KeyTypes, "Serializable"],
    list["Serializable"],
    tuple["Serializable"],
    bytes,
]
```
However we have some more constraints on these types then simply their identity, like the size of integers or the allowed characters for strings. So tests with hypothesis are written like the example I pasted above to make sure the types are handled correctly and nothing breaks as long as the returned values are within our constraints.
If we could recursively type we would define those restrictions only on the specific types with `register_type_strategy`, but because we've replaced those nested types with Any we also would like to have Any defined or handled in some way that tests the nested nature of these types.

**Comment by Zac-HD** [comment]
@pejter - can you show me an actual example type, along with how you construct and register a strategy for it?

**Comment by pejter** [comment]
Sorry for the late response, lots of other stuff happening and this got put on pause.
The actual types we have are like this, with every Any being nested, serializable user data without a known structure:
```python
@dataclass
class TelemetryMetric:
    tele_data: dict[str, Any] = field(default_factory=dict)
    time_data: dict[str, Any] = field(default_factory=dict)
    sensor_type: str = field(default="unknown")


@dataclass
class SubmissionHeader:
    receipt: str = field(repr=False)
    timeout: float
    metadata: dict[str, Any] = field(default_factory=dict)
    metrics: defaultdict[str, int] = field(
        default_factory=cast(Callable[[], defaultdict[str, int]], partial(defaultdict, int)),
    )
    telemetry: TelemetryMetric = field(default_factory=TelemetryMetric)

    def __post_init__(self) -> None:
        if not isinstance(self.metrics, defaultdict):
            if not isinstance(self.metrics, Mapping):
                raise TypeError("metrics must be a Mapping type")
            self.metrics = defaultdict(int, self.metrics)
        if not isinstance(self.telemetry, TelemetryMetric):
            if not isinstance(self.telemetry, Mapping):
                raise TypeError("telemetry must be a TelemetryMetric or a Mapping type")
            self.telemetry = TelemetryMetric(**self.telemetry)  # pylint: disable=not-a-mapping


class SubmissionState(Enum):
    SUCCESS = b"SUCCESS"
    TIMEOUT = b"TIMEOUT"
    DROPPED = b"DROPPED"
    UNKNOWN = b"UNKNOWN"
```
and then an excerpt from our testing code (the constants are above in my previous comment):
```python

class TestWorker(unittest.TestCase):
    def setUp(self) -> None:
        st.register_type_strategy(Any, json)
        st.register_type_strategy(float, st.floats(allow_nan=False))
        st.register_type_strategy(int, st.integers(min_value=LLONG_MIN, max_value=ULLONG_MAX))
        st.register_type_strategy(str, st.characters(blacklist_categories=["Cs"]))

    @given(
        header=infer,
        payload=json | st.from_type(SubmissionState),
    )
    def test_serde_common(self, header: SubmissionHeader, payload: Any):
        data = self.worker.serialize(header, payload)
        frame = zmq.Frame(data)
        received_header, received_payload = self.worker.deserialize(frame)
        assert received_header == header
```

As I've written previously I'd love to use hypothesis to construct this for me and avoid having to create everything in these types from scratch just to get the nested data everywhere.

**Comment by Zac-HD** [comment]
The intended use of `register_type_strategy()` is as *global* state.  If you're defining non-global arguments, the preferred idiom is to define reusable pieces as globals, and assemble any test-specific combinations within `@given()`.  For example:

```python
user_data = st.dictionaries(st.text(), json)
st.register_type_strategy(
    TelemetryMetric,
    st.builds(TelemetryMetric, tele_data=user_data, time_data=user_data),
)
st.register_type_strategy(
    SubmissionHeader,
    st.builds(
        SubmissionHeader,
        timeout=st.floats(allow_nan=False),
        metadata=user_data,
        telemetry=...,  # "infer from the type annotation" (since we registered it above)
    ),
)

class TestWorker(unittest.TestCase):
    @given(header=..., payload=json | st.from_type(SubmissionState))
    def test_serde_common(self, header: SubmissionHeader, payload: Any):
        pass
```

I also worry about cache pollution from the repeated-registration pattern you're using; it seems very likely to me that at least some of your tests aren't getting quite what you expected.  If we're going to have implicit state, keeping it reasonably static helps a lot!
