### ISSUE TITLE
hypothesis examples from pytest fixtures ?

### ISSUE THREAD

**Issue by asmodehn** [HypothesisWorks/hypothesis#3315]
I have used hypothesis for a while now, but I recently encountered a situation where I dont see an obvious solution

I use pytest fixtures to read json files and pass the data from the file in various tests, validating the code along the way, at least on documented examples.

I would like to use these as examples in tests decorated with `hypothesis.given`, to make sure that data is always tested, even on environment that are not doing example generation.

However it seems that the `example` decorator operate at a stage where pytest collect tests and rewrite modules.
Whereas fixture are evaluated afterwards, when the test is running... which is already to late to add the example to the test.
I tried a few things without success so far.

Has anyone done something similar ?
What would be the best way to go about this ?

This is related to the interop between hypothesis tests and pytest parametrization/fixture structure... and I m thinking there are likely quite a few hurdles and implementation details to consider...

**Comment by asmodehn** [comment]
I attempted to write a small example:
```py
import json

from hypothesis import given, settings, Verbosity, Phase
from string import printable
from hypothesis import strategies as st

import pytest

json_strategy = st.recursive(  # no nan as it breaks equality test
    st.none() | st.booleans() | st.floats(allow_nan=False) | st.text(printable),
    lambda children: st.lists(children, max_size=5)
    | st.dictionaries(st.text(printable), children, max_size=5),
    max_leaves=20,
)


@pytest.fixture
def example_json():
    with open(
        os.path.join(os.path.dirname(os.path.realpath(__file__)), f"example.json")
    ) as f:
        return json.load(f)


@given(data=json_strategy)
@settings(verbosity=Verbosity.verbose, phases=[
    # specific phases, skipping generation.
    Phase.explicit, Phase.reuse
    # This could be in a profile passed at runtime
])

# what I would like to do, somehow...
# @example(example_json())
# => no test generation but test is run for the example


def test_parse_json(data):
    # testing dump.load bijection
    d = json.loads(json.dumps(data, allow_nan=False))
    assert d == data


if __name__ == "__main__":
    pytest.main(["-sv", __file__])

```

**Comment by honno** [comment]
Not super familiar with `@example()` nor `pytest` fixtures, but yeah AFAIK `@example()` is meant to only take in a literal example, not "evaluate" magical things like `pytest` fixtures.

> I attempted to write a small example

For this specific example at least, you could make `example_json` a variable rather than a fixture (IMO generally I wouldn't use fixtures for such static data). Maybe this helps for your actual use case too?

```python
with open(...) as f:
    example_json = json.load(f)

@given(data=json_strategy)
@example(example_json)
@settings(...)
def test_parse_json(data):
    # testing dump.load bijection
    d = json.loads(json.dumps(data, allow_nan=False))
    assert d == data
```

**Comment by asmodehn** [comment]
Thanks for the idea.
I had considered it, but given the (at least in my usecase) large number of tests, reading that data in a fixture and scope it for a session to cache it for instance, make some sense to organize tests and speed things up.

I actually found another possible solution: have an extra fixture, that depend on that "data fixture", and in there, call the decorator to modify the test function.

I'd consider this a bit of a hack though, or maybe it is a useful usecase where the function_scoped_fixture healthcheck should be disabled. So there, in case it helps anyone:

```py
@given(data=json_strategy)
@settings(suppress_health_check=[HealthCheck.function_scoped_fixture],
        verbosity=Verbosity.verbose, phases=[
    # specific phases, skipping generation.
    Phase.explicit, Phase.reuse
    # This could be in a profile passed at runtime
])

def test_parse_json(data, extra_fix):
    # testing dump.load bijection
    d = json.loads(json.dumps(data, allow_nan=False))
    assert d == data


@pytest.fixture
def extra_fix(example_json):
    # dynamically calling decorator before test run
    example(data=example_json)(test_parse_json)
    return
```

This somehow works:

```
parse.py::test_parse_json Trying explicit example: test_parse_json(
    data={'List': ['a', 1, None],
     'Null': None,
     'key': 'value',
     'number': 3.1415,
     'some': {'other': {'thing': 42}}},
    extra_fix=None,
)
PASSED
```

I'll close the issue since the issue is now solved, but if there are other possibilities, I'll be happy to learn about it.
