### ISSUE TITLE
Teach the Ghostwriter about `@staticmethod` and `@classmethod` methods

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#3318]
The [Hypothesis Ghostwriter](https://hypothesis.readthedocs.io/en/latest/ghostwriter.html) currently only writes tests for functions, because they're a natural starting point for property-based tests and the primary design goal is to *make it incredibly easy to get started*.

It's also usually unclear what properties you could guess for classes or instances, but in conversation at PyCon today we worked out that there are a few special cases in which we can test something after all:

- [ ] a `@staticmethod` is just like a function (albeit glued onto a class), so we could treat it just like we do any other function, replacing the dot with triple-underscore for name-based analyses.
- [ ] `@classmethod`s are similar in that they don't require a pre-build instance.  In addition to the "fuzz" tests which just check for internal errors, we can also:
  - [ ] assert that `from_*` classmethods return an instance of the class (by strong convention) 
  - [ ] and assert that the matching `to_*` method (if one exists) inverts this.

**Comment by Zac-HD** [comment]
Go for it!  Just expect to also need a while to read through the module, there's A Lot Of Code.  You might also find it helpful to read "callers to callees" rather than "top to bottom", starting with the `equivalent` function?  Also remember that you don't need to understand the whole thing to make useful changes to it!  (yay tests 😁)

**Comment by Cheukting** [comment]
It got more complicated when using with CLI as `.` is always interperted as module. I guess the triple underscore you mean here? so someone should type `A___class_func` instead of `A.class_func`?

**Comment by Zac-HD** [comment]
- triple-underscore is for [this part of the `magic()` ghostwriter](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/extra/ghostwriter.py#L933-L952), where it's trying to detect round-trips based on the name.
  - Actually, we don't need to replace the dot, we just need to make sure that we include the class name *as well as* the method name.  (otherwise if we had two classes with a `from_dict()` classmethod in the same module, we'd only test one of them!)
  - Similarly, we'll need to improve the 'magic discovery' for a module, so that it checks classes for testable methods
  - Based on a quick glance, I think the current system seems fine for test names.
- Yep, the CLI seems a bit tricky; we can revisit that in a future PR.
- FYI, [here's how to syntax-highlight code blocks on GitHub](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks); I tend to use `python` and `python-traceback` a lot (and they don't have to be fully valid to highlight well, either, so the latter works for pytest outputs)

**Comment by Cheukting** [comment]
Ah sorry, I actually know the syntax highlighting but am too lazy to use it. My bad

**Comment by Cheukting** [comment]
For the CLI stuff actually I was working on it so don't mind including it
