### ISSUE TITLE
Dependencies between @given arguments

### ISSUE THREAD

**Issue by tonyfm15** [HypothesisWorks/hypothesis#3340]
Is it possible to have some `@given` arguments depend on other `@given` arguments? For example, let's say I have a test and I want to generate two integers `M` and `N`, where `N` must be less than `M`. What I want to do is something like the following:

```
@given(M=integers(0, 10), N=integers(0, M))
```

Of course, I could generate `M` in `@given` and then generate `N` in the body of the test but this
1. Bloats the test body with setup code that I'd rather have in the decorators.
2. Makes tests flaky since the randomness is partially handled by `@given` and partially handled by whatever module I use to generate `N`.

I commonly encounter this when using the `arrays` strategy since I frequently want to generate multiple arrays with the same (but random) shape. So I would like to generate some integers for array dimensions and then generate `arrays` using those integers.

**Comment by Zac-HD** [comment]
The answer to the precise question you asked is that no, you can't define *arguments to `@given()`* which depend on each other.  Fortunately, though, there are ways to solve your problem - the best here is probably to have both arguments depend on a common `st.shared()` strategy, like:

```python
shared_shape = st.shared(<shape_strategy>)

@given(
    a = arrays(shape=shared_shape, ...),
    b = arrays(shape=shared_shape, ...),
)
def test(a, b): ...
```

For more complex cases, you can write an `@st.composite` strategy with implicit dependencies (and then tuple-unpack that inside your test function), or in the worst case fall back to `st.data()`.  [`hypothesis write numpy.matmul`](https://zhd.dev/ghostwriter/) will demonstrate the latter form, if you're interested.
