### ISSUE TITLE
Type error in Pylance

### ISSUE THREAD

**Issue by denisrosset** [HypothesisWorks/hypothesis#3348]
This is with `Pylance language server 2022.5.1 (pyright e0e07d31)`, Python `3.10` and hypothesis `6.46.5`

Edit: the analysis mode is strict:
```json
    "python.analysis.typeCheckingMode": "strict",
```

The following snippet:
```python
from typing import Tuple

import hypothesis.strategies as st

def my_hyp() -> st.SearchStrategy[Tuple[int, int]]:
    return st.tuples(st.integers(0, 10), st.integers(0, 10))
```

fails to typecheck with:
```
Type of "tuples" is partially unknown
  Type of "tuples" is "Overload[() -> SearchStrategy[Tuple[()]], (a1: SearchStrategy[Ex@tuples]) -> SearchStrategy[Tuple[Ex@tuples]], (a1: SearchStrategy[Ex@tuples], a2: SearchStrategy[T@tuples]) -> SearchStrategy[Tuple[Ex@tuples, T@tuples]], (a1: SearchStrategy[Ex@tuples], a2: SearchStrategy[T@tuples], a3: SearchStrategy[T3@tuples]) -> SearchStrategy[Tuple[Ex@tuples, T@tuples, T3@tuples]], (a1: SearchStrategy[Ex@tuples], a2: SearchStrategy[T@tuples], a3: SearchStrategy[T3@tuples], a4: SearchStrategy[T4@tuples]) -> SearchStrategy[Tuple[Ex@tuples, T@tuples, T3@tuples, T4@tuples]], (a1: SearchStrategy[Ex@tuples], a2: SearchStrategy[T@tuples], a3: SearchStrategy[T3@tuples], a4: SearchStrategy[T4@tuples], a5: SearchStrategy[T5@tuples]) -> SearchStrategy[Tuple[Ex@tuples, T@tuples, T3@tuples, T4@tuples, T5@tuples]], (*args: SearchStrategy[Any]) -> SearchStrategy[Tuple[Unknown, ...]], (*args: Unknown) -> TupleStrategy]"
```

I'd be happy to push this myself to the `pylance` issues if I'm advised to!

**Comment by Zac-HD** [comment]
Ah, if you've got the same error from Numpy then it probably does make sense to treat it as a pyright issue - do you want to open that upstream, and tag me?

**Comment by rsokl** [comment]
I don't think that there is a problem with pyright here.  This is fixed by updating both line 110 and 116 to:

```python
def tuples(*args: SearchStrategy[Any]) -> SearchStrategy[Tuple[Any]]:  # noqa: F811
```

**Comment by rsokl** [comment]
Specifying `Tuple` is indeed a partially unknown annotation. pyright-strict wants you to tell it "I *explicitly* mean that it is a tuple of arbitrary length and contents. 

And, for some reason, pyright-strict expects that the actual implementation (line 116)  to also include annotations, even though this seems to be redundant with the lowest overload. I haven't taken the time to see if mypy wants the same.

@Zac-HD  I can try to fix this sometime today

**Comment by Zac-HD** [comment]
Thanks!  Yeah, let's also use pos-only args - they are in fact positional-only, so.

**Comment by rsokl** [comment]
For the record, the same issue occurs in `one_of`. I am doing a general tune up in #3349
