### ISSUE TITLE
.hypothesis directory is created with InMemoryExampleDatabase

### ISSUE THREAD

**Issue by 7omb** [HypothesisWorks/hypothesis#3350]
Hypothesis creates a `.hypothesis` directory although `InMemoryExampleDatabase` is specified in pytests `conftest.py`. You can find a minimal example here: https://github.com/7omb/hypothesis_in_memory_db. If you run the example with `make test` it seems to use the in-memory db:

```
hypothesis profile 'inmemory' -> database=InMemoryExampleDatabase({})
```

Is this a bug or just a misconfiguration on my side?

**Comment by Zac-HD** [comment]
Not a bug, we also cache a few other things like unicode tables.  (If `.hypothesis/database/` exists, *that's* a bug)
