### ISSUE TITLE
Feature request: strategy for 'matched' iterables

### ISSUE THREAD

**Issue by wmayner** [HypothesisWorks/hypothesis#3352]
I think it would be useful to have a strategy like `iterables()`, but that produces several iterables that are yield the same items but are _not_ identical, perhaps called `matched_iterables()`.

This would allow consuming the same iterable more than once, for instance once in the test code and once in the code to be tested, and then checking that the results of are equal. For example, suppose I wanted to test my version of `map`:

```python
from hypothesis import strategies as st

def my_map(function, iterable):
    for x in iterable:
        yield function(x)

# The `num` keyword argument would allow controlling the number of matched iterables produced
@given(st.matched_iterables(st.integers(), num=2))
def test_my_map(iterables):
    i1, i2 = iterables
    func = lambda x: x*2
    expected = list(map(func, i1))
    actual = list(my_map(func, i2))
    assert expected == actual
```

This is difficult to do on the user side; since some iterables cannot be cloned and some are infinite, in the general case it's impossible to _e.g._ first cast to a list with `iterable = list(iterable)` and then `return tuple(iter(iterable) for i in range(num)`.

For now, I'm just using the following, based on `lists()`:
```python
@st.composite
def matched_iterables(draw, elements, num=2):
    iterable = draw(st.lists(elements))
    return tuple(iter(iterable) for i in range(num))
```
But of course this doesn't cover the full range of cases.

Related to #3045.

**Comment by Zac-HD** [comment]
I much prefer the composition approach here:

```python
from functools import partial
from itertools import tee

@given(
    st.iterables(st.integers()).map(partial(tee, n=2))
)
def test(it):
     ...
```

**Comment by wmayner** [comment]
Perfect, thank you!
