### ISSUE TITLE
Feature request: strategy for 'anything'

### ISSUE THREAD

**Issue by wmayner** [HypothesisWorks/hypothesis#3353]
It would be nice to have a strategy for returning any value from the basic builtin strategies, as shown in #3045. For example, this would be useful when testing a function that shouldn't rely on any particular property of the elements in an iterable. I'm new to this approach to testing, however, so if this sort of thing is somehow an antipattern, please let me know :)

**Comment by rsokl** [comment]
This is already possible using the `everything_except` pattern documented [here](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.from_type)

```python
from hypothesis.strategies import from_type

def everything_except(*excluded_types):
    return (
        from_type(type)
        .flatmap(from_type)
        .filter(lambda x: not isinstance(x, excluded_types))
    )
```

e.g. `everything_except()` is a strategy that can draw from all types whose strategies that are registered with Hypothesis. `everything_except(int, str)` will draw everything except string and int values.

A word of warning. This strategy can often produce "health check" failures in Hypothesis, as some of the strategies take a relatively long time to draw their values.

**Comment by wmayner** [comment]
Nice, I hadn't seen that. Thanks and sorry for the superfluous issue.

**Comment by Zac-HD** [comment]
No worries, we're happy to help!
