### ISSUE TITLE
Whitelist specific function-scoped fixtures in settings?

### ISSUE THREAD

**Issue by hoodmane** [HypothesisWorks/hypothesis#3358]
I have some function scoped-fixtures which are really cheap (they take an expensive module-scoped fixture and reset some logs and other state). I also have some really expensive function-scoped fixtures.

It would be nice to be able to specifically whitelist cheap function-scoped fixtures in the settings without giving up the protection for anyone who tries to use the expensive ones.

**Comment by Zac-HD** [comment]
It's not about how long they take, it's that *they don't run between examples* - so eg the logs and other state *won't* be reset. If that's OK then you can make the fixtures have a wider scope; if not then it doesn't matter how fast they are.

**Comment by hoodmane** [comment]
Ah great, thanks for the explanation.

**Comment by hoodmane** [comment]
So just to clarify, if I really do need them to run every time I have to make it into a context manager:
```py
@given(blah)
@...
def some_test(args):
	with function_scoped_fixture_stuff():
		# do test
```

**Comment by Zac-HD** [comment]
Yep, that's right.
