### ISSUE TITLE
Typo in Details documentation

### ISSUE THREAD

**Issue by jenstroeger** [HypothesisWorks/hypothesis#3363]
Section [The Hypothesis pytest plugin](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/docs/details.rst#the-hypothesis-pytest-plugin) shows a bullet list without the third bullet, which is squashed with the second:

https://github.com/HypothesisWorks/hypothesis/blob/4248a48615fb18943bf45503bb6326f672709edb/hypothesis-python/docs/details.rst?plain=1#L703-L706

Line 705 is missing a `-`, I believe.

**Comment by jenstroeger** [comment]
@Zac-HD, I don’t know if you want a PR for this. My only contributions to Hypothesis these days seem to be one-byte documentation changes 😁

**Comment by Zac-HD** [comment]
PRs welcome, the bits are cheap! In this case we don't even need release notes because we're not touching the source code.

**Comment by jenstroeger** [comment]
PR https://github.com/HypothesisWorks/hypothesis/pull/3365. I wasn’t sure if you need [conventional commit message](https://www.conventionalcommits.org/) or not; the history in the [`master` branch](https://github.com/jenstroeger/hypothesis/commits/master) indicates not.

**Comment by Zac-HD** [comment]
Thanks for the fix! 

While I like the idea of conventional commits, requiring them would pretty much close off the project to new OSS contributors by requiring a higher level of familiarity with git; the tradeoff (or partial adherence) didn't seem worth it.
