### ISSUE TITLE
Cached test generation

### ISSUE THREAD

**Issue by Jookia** [HypothesisWorks/hypothesis#3366]
On my system at least, test generation is taking up the majority of my testing. It would be good to have some kind of cache strategy that draws a set of examples. I tried this but it gave errors about flaky tests and data generation.

**Comment by Zac-HD** [comment]
See https://hypothesis.readthedocs.io/en/latest/reproducing.html#providing-explicit-examples and https://hypothesis.readthedocs.io/en/latest/settings.html#settings-profiles:

```python
# conftest.py or similar
import os
from hypothesis import Phase, settings

settings.register_profile("examples_only", phases=[Phase.explicit])

if "RUN_ALL_TESTS" not in os.environ:  # or whatever logic you want
    settings.load_profile("examples_only")
```
```python
# test_whatever.py
from hypothesis import example, given, strategies as st

@example(x=0)
@example(x=1)
@example(x=2)  # list as many inputs as you like, you get the idea
@given(x=st.integers())
def test_foo(x):
    ...
```

**Comment by Jookia** [comment]
That doesn't really change that generating examples is slow.
