### ISSUE TITLE
Hypothesis should handle test skips

### ISSUE THREAD

**Issue by arunanshub** [HypothesisWorks/hypothesis#3388]
## Issue Description

Hypothesis currently stops generating additional values if `pytest.skip(...)` or `unittest.SkipTest` is raised. What I've found is, it is not entirely Hypothesis' fault since the test runner "thinks" that there are no more values to test for.

## Code to Reproduce Issue

```python
import pytest
from hypothesis import given
from hypothesis import strategies as st


@given(st.integers(min_value=0, max_value=10))
def test_foo(value: int):
    if value in [1, 2, 3]:
        return pytest.skip("currently not implemented")
    # do something here
    assert isinstance(value, int)
```

## Present workaround

I'm using `hypothesis.reject()` as a way to skip the invalid cases, however I don't think `hypothesis.reject()` is a part of the public API.

```diff
import pytest
from hypothesis import given, reject
from hypothesis import strategies as st


@given(st.integers(min_value=0, max_value=10))
def test_foo(value: int):
    if value in [1, 2, 3]:
-       return pytest.skip("currently not implemented")
+       return reject()
    # do something here
    assert isinstance(value, int)
```

## Suggestion

I believe there should be a function in Hypothesis that marks the test as "skipped", instead of "rejected".

**Comment by Zac-HD** [comment]
`hypothesis.reject()` or `hypothesis.assume(False)` would both work here.
