### ISSUE TITLE
`event` can't accept tuples/lists

### ISSUE THREAD

**Issue by ymotongpoo** [HypothesisWorks/hypothesis#3393]
As reported at [StackOverflow](https://stackoverflow.com/q/72843753/515508), I tried to take the statistics of generated list values with `event`.

```python
@dataclass(frozen=True)
class Foo:
    x: int
    y: str

    def __hash__(self):
        return hash((self.x, self.y))

@given(lists(builds(Foo, integers(), text()), max_size=3))
def test_foo(l):
    t = tuple(l)
    event(t)
```

The code above raised an TypeError saying:

```
self = <WeakKeyDictionary at 0x105c17430>, key = ()

    def __getitem__(self, key):
>       return self.data[ref(key)]
E       TypeError: cannot create weak reference to 'tuple' object

../../../.pyenv/versions/3.10.4/lib/python3.10/weakref.py:416: TypeError
```

Because the tuple is builtin and I couldn't resolve this weakref issue easily. @Zac-HD suggested to use 'str' instead of tuples, but it would be great if `event` can accepts tuples and other hashable objects.

**Comment by Zac-HD** [comment]
Fixed by https://github.com/HypothesisWorks/hypothesis/pull/3392 / https://hypothesis.readthedocs.io/en/latest/changes.html#v6-48-3 😁

**Comment by ymotongpoo** [comment]
Thank you for the quick fix!

**Comment by Zac-HD** [comment]
No problem!  If you run into anything else, please do open another issue 😎
