### ISSUE TITLE
Chance of generating unnormalized unicode string is vanishingly low

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#341]
The following test will fail with unsatisfiable:

``` python
from unicodedata import normalize
from hypothesis import given, assume
from hypothesis.strategies import text

@given(text())
def test_unicode_normalization(s):
    assume(s != normalize("NFC", s))
```

This is because basically all unicode text Hypothesis generates is normalized by default.

This is suboptimal and probably means that a tonne of potential bugs are being missed.

**Comment by Zac-HD** [comment]
I imagine that many of these bugs would be related to canonicalization of data, right?

If so, normalising in non-NFC ways might also uncover some interesting issues without a deeper rebuild of the text strategy.  Small example:

```python
from unicodedata import normalize
from hypothesis import build, strategies as st

@st.composite
def text_denormal(draw, *args, normalise_by=('NFC', 'NFK', 'NFKC', NFKD'), **kwargs):
    if normalise_by is None: 
        # Maybe just insert some non-normalised characters here?
        return st.text(*args, **kwargs)
    return normalise(draw(st.sampled_from(normalise_by)), 
                     draw(st.text(*args, **kwargs)))
```

**Comment by Zac-HD** [comment]
This is a symptom of the more general weakness that Hypothesis generates all unicode strings as a list of individual codepoints, so we can't do multi-codepoint nasty things like combined glyphs, non-normalised strings etc. at rates higher than chance.

The current API where `text()` takes a strategy for the alphabet makes this hard to fix, but we can probably think of something creative...

**Comment by Zac-HD** [comment]
Turns out that sampling from categories then codepoints boosts the chance of drawing a letter followed by a combining mark enough that this now just works :rocket:

**Comment by Zac-HD** [comment]
I'm closing this in favor of #1401, which has substantially more commentary on the problem of weighting the probability of generating characters (by Unicode category or other divisions) and how we might fix it.
