### ISSUE TITLE
Getting time statistics for each example

### ISSUE THREAD

**Issue by allenlawrence94** [HypothesisWorks/hypothesis#3418]
I use hypothesis to test optimization problems - still quite new to it - and I'm wondering if there's a way to record how long each example takes to solve. It's not uncommon that the time it takes to solve an optimization problem is very sensitive to it's inputs, so being able to view time statistics for each example would be invaluable. I have used the deadline feature to isolate individual problem examples, but this is a less than ideal workflow (especially when you don't know what the deadline should be) and it doesn't paint the full picture when the solve time is volatile (i.e., the example is "flaky").

Pytest's `--durations` shows the time spent on the entire test rather than on individual examples.

Let me know if hypothesis or other packages support anything like this, thanks!

**Comment by Zac-HD** [comment]
Not directly - I'd implement this using a context manager within the test function 🙂 

If you're searching for especially slow inputs, I'd [consider using `hypothesis.target(elapsed_time)`](https://hypothesis.readthedocs.io/en/latest/details.html#targeted-example-generation).  It's a pretty dumb optimization algorithm ('try random variations on the pareto frontier'), but often works better than unguided random generation.
