### ISSUE TITLE
How to structure a Stateful test right?

### ISSUE THREAD

**Issue by thepabloaguilar** [HypothesisWorks/hypothesis#3428]
Hello, first of all thanks a lot for your work on this lib! I'm preparing a presentation about Property Tests for my local Python community, so I've built an FastAPI application which basically mimic transition card state (like in JIRA) and also have wrote a stateful tests but seeing the output from verbose mode it seems there's something wrong! Could you help me figuring out, please?

Models:
```python
from enum import Enum
from uuid import UUID

from pydantic import BaseModel


class CardState(Enum):
    TODO = 'TODO'
    DEVELOPMENT = 'DEVELOPMENT'
    QA = 'QA'
    DONE = 'DONE'


class Card(BaseModel):
    id: UUID
    name: str
    state: CardState
```

FastAPI application:
```python
from typing import Final
from types import MappingProxyType
from uuid import uuid4, UUID

from fastapi import FastAPI, HTTPException
from fastapi import status
from pydantic import BaseModel

from checking_properties.model import Card, CardState

app = FastAPI(title='Checking Properties')

_DB: dict[UUID, Card] = dict()

_POSSIBLE_TRANSITIONS: Final = MappingProxyType({
    CardState.TODO: {CardState.DEVELOPMENT},
    CardState.DEVELOPMENT: {CardState.QA, CardState.TODO},
    CardState.QA: {CardState.DEVELOPMENT, CardState.DONE},
    CardState.DONE: set(),
})


class CreateCardRequest(BaseModel):
    name: str


@app.post(
    '/v1/cards',
    status_code=status.HTTP_201_CREATED,
    response_model=Card,
)
def create_card(request: CreateCardRequest) -> Card:
    card = Card(
        id=uuid4(),
        name=request.name,
        state=CardState.TODO,
    )

    _DB[card.id] = card

    return card


class ChangeCardStateRequest(BaseModel):
    desired_state: CardState


@app.patch('/v1/cards/{card_id}/state', response_model=Card)
def change_card_column(
    card_id: UUID,
    request: ChangeCardStateRequest,
) -> Card:
    if card_id not in _DB:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail='card not found',
        )

    card = _DB[card_id]
    if request.desired_state not in _POSSIBLE_TRANSITIONS[card.state]:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail='invalid transition',
        )

    card.state = request.desired_state

    return card
```

Test file:
```python
from typing import Callable

from fastapi import status
from fastapi.testclient import TestClient
from hypothesis import strategies as st
from hypothesis import settings, Verbosity, HealthCheck
from hypothesis.stateful import (
    Bundle,
    rule,
    consumes,
    initialize,
    RuleBasedStateMachine,
)

from checking_properties.app import app
from checking_properties.model import Card, CardState


def require_state(required_state: CardState) -> Callable[[Card], bool]:
    return lambda card: card.state == required_state


class CardTransition(RuleBasedStateMachine):
    app_client: TestClient

    cards = Bundle('Cards')

    def __init__(self) -> None:
        super().__init__()
        self.app_client = TestClient(app)

    @initialize(target=cards)
    def create_card(self) -> Card:
        response = self.app_client.post('/v1/cards', json={
            'name': 'Property Test'
        })
        response.raise_for_status()

        return Card(**response.json())

    @rule(
        target=cards,
        card=consumes(cards).filter(require_state(CardState.TODO)),
        to_state=st.sampled_from([CardState.DEVELOPMENT])
    )
    def todo_transitions(self, card: Card, to_state: CardState) -> Card:
        response = self.app_client.patch(f'/v1/cards/{card.id}/state', json={
            'desired_state': to_state.value,
        })
        response.raise_for_status()

        return Card(**response.json())

    @rule(
        target=cards,
        card=consumes(cards).filter(require_state(CardState.DEVELOPMENT)),
        to_state=st.sampled_from([CardState.QA, CardState.TODO])
    )
    def development_transitions(self, card: Card, to_state: CardState) -> Card:
        response = self.app_client.patch(f'/v1/cards/{card.id}/state', json={
            'desired_state': to_state.value,
        })
        response.raise_for_status()

        return Card(**response.json())

    @rule(
        target=cards,
        card=consumes(cards).filter(require_state(CardState.QA)),
        to_state=st.sampled_from([CardState.DEVELOPMENT, CardState.DONE])
    )
    def qa_transitions(self, card: Card, to_state: CardState) -> Card:
        response = self.app_client.patch(f'/v1/cards/{card.id}/state', json={
            'desired_state': to_state.value,
        })
        response.raise_for_status()

        return Card(**response.json())

    @rule(
        card=cards.filter(require_state(CardState.DONE)),
        to_state=st.sampled_from(list(CardState))
    )
    def done_transitions(self, card: Card, to_state: CardState) -> None:
        response = self.app_client.patch(f'/v1/cards/{card.id}/state', json={
            'desired_state': to_state.value,
        })

        assert response.status_code == status.HTTP_400_BAD_REQUEST


CardTransition.TestCase.settings = settings(
    max_examples=100,
    verbosity=Verbosity.debug,
    suppress_health_check=[HealthCheck.filter_too_much],
)
TestCardTransition = CardTransition.TestCase
```

A piece from the output:
```text
tests/test_app/test_transition_card_properties.py::TestCardTransition::runTest Reusing examples from database
Generating new examples
Trying example:
state = CardTransition()
v1 = state.create_card()
state.teardown()
4 bytes [[1, 0]] -> Status.VALID, 
Trying example:
state = CardTransition()
v1 = state.create_card()
state.teardown()
12 bytes [[1, [57388, 1, [0, [0, 0], [0, 0, 0]]]]] -> Status.INVALID, 
Trying example:
state = CardTransition()
v1 = state.create_card()
state.teardown()
12 bytes [[1, [35893, 1, [0, [0, 0], [0, 0, 0]]]]] -> Status.INVALID, 
Trying example:
state = CardTransition()
v1 = state.create_card()
state.teardown()
12 bytes [[1, [1876, 1, [0, [0, 0], [0, 0, 0]]]]] -> Status.INVALID, 
Trying example:
state = CardTransition()
v1 = state.create_card()
state.teardown()
12 bytes [[1, [3562, 1, [0, [0, 0], [0, 0, 0]]]]] -> Status.INVALID, 
Trying example:
state = CardTransition()
v1 = state.create_card()
state.teardown()
12 bytes [[1, [45218, 1, [0, [0, 0], [0, 0, 0]]]]] -> Status.INVALID, 
Trying example:
state = CardTransition()
v1 = state.create_card()
state.teardown()
19 bytes [[1, [61215, 1, [250, [2, [46, 1], 2, 1, [29, 1], 0, [42, 1], [59, 1]]]]]] -> Status.INVALID, 
Trying example:
state = CardTransition()
v1 = state.create_card()
state.teardown()
10 bytes [[1, [1882, 1, [175, [1, 0], 0]]]] -> Status.INVALID, 
Trying example:
state = CardTransition()
v1 = state.create_card()
v2 = state.todo_transitions(card=v1, to_state=<CardState.DEVELOPMENT: 'DEVELOPMENT'>)
state.teardown()
19 bytes [[1, [35487, 1, [78, [3, 0], 0]], [37222, 1, [[0, 1, 3, 0], 0]]]] -> Status.INVALID, 
Trying example:
state = CardTransition()
v1 = state.create_card()
state.teardown()
13 bytes [[1, [15479, 1, [86, [0, [3, 0]], [0, 0, 0]]]]] -> Status.INVALID, 
Trying example:
state = CardTransition()
v1 = state.create_card()
state.teardown()
```

It has so many `Status.INVALID` 😞 

Thanks in advance!

**Comment by Zac-HD** [comment]
While having quite a few `INVALID` statuses is OK (it's an internal thing; if this was a problem you'd get a warning, healthcheck, or error), the core problem is that you're filtering much too heavily.  I'd try to solve this by having a separate bundle for cards in each status, and `st.one_of()`ing them together when you want "any card".

Good luck with the talk!  And if you're testing web apps, check out https://github.com/schemathesis/schemathesis too 🙂

**Comment by thepabloaguilar** [comment]
Thanks for your answer @Zac-HD, I've created three more initializer functions for the other states and now it seems working better while generating the examples!

**Comment by chenlijun99** [comment]
Hi @Zac-HD. I'm facing the same problem, but I don't understand why filtering causes the test to be started and then aborted. From your suggestion in this other issue https://github.com/HypothesisWorks/hypothesis/issues/3448#issuecomment-1229222153 it appears to me that Hypothesis should try to draw rules until a valid one is found. But here, it seems that you're saying that when a example is filtered out, this results in `Status.INVALID` and the test is aborted.

**Comment by Zac-HD** [comment]
Well, what is Hypothesis meant to do when we hit an `assume(False)`?

- For `some_strategy.filter(f)`, if `f(x)` is falsey we can always just try getting another `x` from `some_strategy` - at least a few times before giving up (it's important to avoid pathological slowdowns due to near-futile retries)
- For `assume(x)`, if `x` is falsey then we have to retry... whatever led to that, which usually means aborting the test and trying with different arguments.

I suppose for stateful testing we could just abort the current rule, but it's tricky to reason about side effects and what should happen in cases like 'assume triggers inside a precondition'.  Whatever we do, it could only give a small/niche performance improvement and would risk breaking a lot of existing code.

**Comment by chenlijun99** [comment]
Thanks for the reply. Sorry, I didn't make it clear that I was specifically referring to the better suggestion, i.e:
> Ensure that self.lst is available in class scope, and use x=st.integers().filter(lambda x: x not in lst). This is much more efficient because Hypothesis can retry without restarting the whole stateful test, but might require some further modifications to e.g. call self.lst.clear() at setup or teardown.

> we can always just try getting another x from some_strategy - at least a few times before giving up

Just to be sure, is this the current behavior of Hypothesis or is it a "possible future improvement that could be implemented"? I actually imagined that this is already what Hypothesis does.

> I suppose for stateful testing we could just abort the current rule, but it's tricky to reason about side effects and what should happen in cases like 'assume triggers inside a precondition'. Whatever we do, it could only give a small/niche performance improvement and would risk breaking a lot of existing code.

I totally agree. In fact, I've avoided using `assume()` altogether for stateful tests and instead use `@precondition`.

**Comment by Zac-HD** [comment]
Yes, that's the current behaviour.

**Comment by chenlijun99** [comment]
> we can always just try getting another x from some_strategy - at least a few times before giving up

By "giving up" you mean that the test is aborted with `Status.INVALID` or that Hypothesis switches to try another rule without aborting the current stateful test?

BTW, I managed to reduce a bit the number of `Status.INVALID` by adding preconditions that fail when the strategy will never succeed due to filtering in the current state. I guess that helps Hypothesis a bit.

**Comment by Zac-HD** [comment]
We have a maximum number of retires per whole test case; I don't remember whether we have rule-level retries from filtered strategies but would guess not. The specific line we draw for "this much filtering is too much" is inherently arbitrary, since it binarizes a continuous thing, but you have to draw it somewhere and there's pathological performance if you allow much more.

**Comment by chenlijun99** [comment]
Thanks for the clarification. This makes me think that for my use case of "drawing random values that are within a list", maybe it is better to just use the `data()` strategy and inside the rules use `data.draw(sampled_from(lst))`, rather than generating potential values that could be in the list and then filtering away those that are not.
I wish I could use `Bundle`, but I need to access the list inside invariants and preconditions. Obviously I could keep the `Bundle` and have also a corresponding "plain attribute" and then keep them in sync, but that would be quite cumbersome.

Anyway, many thanks for all your answers!

**Comment by Zac-HD** [comment]
> This makes me think that for my use case of "drawing random values that are within a dynamic list", maybe it is better to just use the `data()` strategy and inside the rules use `data.draw(sampled_from(lst))`, rather than generating potential values that could be in the list and then filtering away those that are not.

Yes, `data.draw(sampled_from(lst))` is the right (and higher-performing) idiom for this.
