### ISSUE TITLE
Small Number of Tests Running for Jax

### ISSUE THREAD

**Issue by simonetgordon** [HypothesisWorks/hypothesis#3435]
In our project [Ivy](https://github.com/unifyai/ivy/commits/master), we import the Array-API Standard test suite which uses hypothesis for testing. We run the array-api tests for each of our backend frameworks (PyTorch, Numpy, Jax and Tensorflow) in separate yml files on the CI. We have noticed that a relatively small number of examples are tested for Jax compared to the others e.g. currently, for Tensorflow there are 3000+ test examples running:

` 309 failed, 3032 passed, 275 skipped, 183 deselected, 5 warnings in 5041.71s (1:24:01)`

Whereas for Jax, most are being deselected :

`201 passed, 11 skipped, 3587 deselected, 67 warnings in 2801.07s (0:46:41)`

I can't find anything in the docs about test deselection. We're a bit puzzled as we handle the testing of each of the frameworks in the same way. Do you have any insight into why we're experiencing this?

**Comment by Zac-HD** [comment]
I don't think this is a Hypothesis issue; I'd ask over on https://github.com/data-apis/array-api-tests

(@honno fyi)
