### ISSUE TITLE
How am I supposed to test my custom strategies?

### ISSUE THREAD

**Issue by TomNicholas** [HypothesisWorks/hypothesis#3436]
In #3433 I wrote a custom strategy that is complicated enough that I want to test that the strategy is creating what I expect it to. The strategy itself also has a bunch of arguments that I want to test for certain values.

What are the best practices for testing your own custom strategies? I can't find any tips about this in the docs, and some things that I naively thought were good ideas raised warnings, e.g.

```python
class TestMyCustomStrategy:
    def test_invalid_args(self):
        with pytest.raises(ValueError):
            my_strategies.chunks(shape=0).example()
```
```
NonInteractiveExampleWarning: The `.example()` method is good for exploring strategies, but should only be used interactively.
We recommend using `@given` for tests - it performs better, saves and replays failures to avoid flakiness, and reports minimal examples. (strategy: chunks(shape=0))

```

**Comment by honno** [comment]
In terms of testing validation, I'd just use `st.data()` like so

```python
@pytest.mark.parametrize("kwargs", [{"shape": 0}, ...])
@given(data=st.data())
def test_invalid_args(draw, kwargs):
    with pytest.raises(ValueError):
        draw(my_strat( **kwargs))
```

**Comment by honno** [comment]
In terms of testing your strategy generates interesting examples, there's an undocumented util `hypothesis.find(<strat>, <predicate>)`, which should be pretty useful. e.g. `hypothesis.find(st.integers(0, 10), lambda n: n == 5)` will run without errors, but `hypothesis.find(st.integers(0, 10), lambda n: n == 55)` will raise `UnsatisfiableError`.

(I've only done such testing in the internal test suite, where there are equivalent utils to `find()`, so haven't really used it per say.)

**Comment by TomNicholas** [comment]
> In terms of testing validation, I'd just use st.data()

Okay fair enough, so basically just always draw instead of testing a single `.example()`, even in tests of the strategies.

> there's an undocumented util `hypothesis.find(<strat>, <predicate>)`

Oh that's cool! I could definitely use that! Any reason not to make it public / document it?

> Just using your internal strategies and asserting things you know should be true, can be powerful.

This is definitely powerful on it's own though, thanks!

**Comment by Zac-HD** [comment]
> > In terms of testing validation, I'd just use st.data()
> 
> Okay fair enough, so basically just always draw instead of testing a single `.example()`, even in tests of the strategies.

Yep, and as a perf optimization you can use e.g. `@settings(max_examples=5)`.  Internally we just disable the warning, but it's not something I'd recommend.

> > there's an undocumented util `hypothesis.find(<strat>, <predicate>)`
> 
> Oh that's cool! I could definitely use that! Any reason not to make it public / document it?

It used to have a separate backend and was therefore deprecated, and apparently when we fixed that we didn't un-deprecate it 😅   So... no reason at all.

**Comment by Zac-HD** [comment]
Closing because it's not an ongoing Hypothesis issue, but feel free to keep commenting below 😀
