### ISSUE TITLE
In `reflection.py`, `__module__` is a `str` or `None`, so an `AttributeError` is always triggered

### ISSUE THREAD

**Issue by rhaps0dy** [HypothesisWorks/hypothesis#3441]
[This line](https://github.com/HypothesisWorks/hypothesis/blob/45b6484d29e592369d245789873282e1782aada6/hypothesis-python/src/hypothesis/internal/reflection.py#L68) will always raise an `AttributeError`, and thus the function's `__module__` never gets included in the hash.

In fact, the Python documents say it can be a `str` or `None`, so `.encode()` may sometimes also raise an AttributeError. That's fine I suppose. 
https://docs.python.org/3/reference/datamodel.html?highlight=__module__

**Comment by Zac-HD** [comment]
Well spotted!  I'll fix this next time we change database keys - we explictly don't promise they're stable, but this doesn't seem like an urgent change 🙂

**Comment by Zac-HD** [comment]
On further thought, I don't think we really care which module an otherwise-identical test is defined in - if it moves, or is invoked via a different path, we'd still want to use the same cached information and examples.  Let's just delete this pointless clause entirely.

**Comment by rhaps0dy** [comment]
I agree and think that's the correct move!

FWIW the reason I discovered this bug is that I was trying to create the opposite behaviour (in my fork): if a test has the same name and path, even if it changes source, it should have the same key.

Should we add a comment to the relevant code to remember to delete this bit whenever the DB keys get updated?

**Comment by rhaps0dy** [comment]
Oh wait, I didn't get this at first, but the DB keys won't change at all if this clause is removed entirely, so there's no need to add just a measly comment!

**Comment by Zac-HD** [comment]
Yeah,  I'll just add a clean up commit to the next PR I merge 😊
