### ISSUE TITLE
Sampled_from is very slow on large inputs

### ISSUE THREAD

**Issue by gampleman** [HypothesisWorks/hypothesis#3450]
Hi 👋 

<details>
<summary>Background</summary>
At work we're trying to build a strategy that generates inputs that could potentially come from our UI (this makes reproducing failures much easier). Our UI allows users to pick elements from a large-ish database of inputs (about 1k elements). These input objects are themselves relatively complex entities with perhaps 80 fields in various forms of nesting.

Originally I wrote a strategy that just generated these input objects randomly. But then that found bugs, but I couldn't be sure that these were things actually possible in the system as a whole, since it wasn't possible to actually select those values in our UI.

So I wrote a strategy that reads in the DB of possible values, then replicates some of the UI logic and picks combinations out of the list.
</details>

I used `st.sampled_from(my_large_list_of_inputs)` and noticed the tests ran pretty intolerably slow (running with `--hypothesis-show-statistics` tells me 99% spent in data generation).

Switching in this implementation:

```python
def fast_sampled_from(list: List[T]) -> st.SearchStrategy[T]:
    return st.integers(min_value=0, max_value=len(list) - 1).map(lambda idx: list[idx])
```

Would make the tests run quickly again.

1. It would be nice to improve this.
2. I would like to understand what am I giving up with my version? Is it going to shrink worse?

**Comment by Zac-HD** [comment]
Hi Jakub - it's taken me a while to dig into this, but I still can't reproduce it or see how it could happen (without using a pretty heavy filter, which would stop your `fast_sampled_from` working at all).  In fact the internals of `st.sampled_from()` are pretty similar to exactly that, with just some extra one-time validation and efficient-in-the-worst-case handling for map and filter methods!

Happy to re-open this if you can provide a reproducing example, of course.

<details>
<summary>test script and output</summary>

```python
from hypothesis import given, strategies as st
from time import perf_counter

@given(st.sampled_from(range(1000)))
def test_samp(x):
    pass

def fast_sampled_from(xs):
    return st.integers(min_value=0, max_value=len(xs) - 1).map(lambda idx: xs[idx])

@given(fast_sampled_from(range(1000)))
def test_fast(x):
    pass

def time(func):
    for _ in range(5):
        start = perf_counter()
        func()
        end = perf_counter()
        print(f"{func.__name__} took {end-start:.3f} seconds")

time(test_samp)
time(test_fast)
```
```
$ python repro.py 
test_samp took 0.067 seconds
test_samp took 0.067 seconds
test_samp took 0.093 seconds
test_samp took 0.063 seconds
test_samp took 0.073 seconds
test_fast took 0.092 seconds
test_fast took 0.070 seconds
test_fast took 0.063 seconds
test_fast took 0.091 seconds
test_fast took 0.069 seconds
```

</details>
