### ISSUE TITLE
More context for inconsistent-result failure?

### ISSUE THREAD

**Issue by ihnorton** [HypothesisWorks/hypothesis#3452]
Whilst debugging a test which is flaky due to inconsistent timing (eg 30 ms vs 2.5s -- looks a bit like #3369), I tried adding some `hypothesis.note` annotations, but was initially led astray because I did not realize that `hp.note` printouts are only given for the _falsifying_ example -- which may not be the slow/interesting one (for example if the slow run is always first due to some setup delay).

I've reduced this down, I think, to the following example (modified from one of the tests):

<details summary="code">

```
#%%
import time, random
import hypothesis as hp
import hypothesis.strategies as st
import pytest

def test_mm():
    once = [True]

    vrb = hp.Verbosity.normal

    @hp.settings(deadline=500, verbosity=vrb)
    @hp.given(st.integers())
    def test_flaky_slow(i):
        hp.note(f"** Testing {once}")

        if once[0]:
            once[0] = False
            hp.note(f"giVE me theee MESsaGE you! {i}")
            time.sleep(1)

    test_flaky_slow()
```

</details>

Here I get:

<details summary="log">

```
>           raise Flaky(
                f"Hypothesis {text_repr} produces unreliable results: "
                "Falsified on the first call but did not on a subsequent one"
            ) from exception
E           hypothesis.errors.Flaky: Hypothesis test_flaky_slow(i=0) produces unreliable results: Falsified on the first call but did not on a subsequent one
E           Falsifying example: test_flaky_slow(
E               i=0,
E           )
E           ** Testing [False]
E           Unreliable test timings! On an initial run, this test took 1005.13ms, which exceeded the deadline of 500.00ms, but on a subsequent run it took 0.00 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.

../../../../opt/conda/envs/pydev/lib/python3.10/site-packages/hypothesis/core.py:713: Flaky
==================================================================== short test summary info ====================================================================
FAILED test_me.py::test_mm - hypothesis.errors.Flaky: Hypothesis test_flaky_slow(i=0) produces unreliable results: Falsified on the first call but did not on ...
```

</details>

I would like to see the `give me thee message` output somewhere, for the _other test invocation_ (`On an initial run, this test took 1005.13ms`). In my original case I had multiple `hp.note` calls with sub-step timings to help understand the reason for the inconsistency.

I've since realized that I can get all the output I want (and more) with `verbosity=verbose`, but for routine CI use, it would be helpful to have the context of both sides of an inconsistent failure reported.  (I normally have pytest capture filtering enabled to flag stray `print` statements)

(Thank you for creating Hypothesis!)

**Comment by Zac-HD** [comment]
Unfortunately I think the best option here is just to use the existing `verbosity=vebose` - any other system would be redundant with that, and more complicated overall 😕
