### ISSUE TITLE
Creating a custom search strategy from a generator [Question]

### ISSUE THREAD

**Issue by badge** [HypothesisWorks/hypothesis#3466]
I started playing around with Hypothesis earlier this week and it's been very useful for validating our Pydantic models, however I hit a snag because I'd like to use real world addresses with Hypothesis (as part of larger models). Naturally, Hypothesis doesn't come with a search strategy for real world addresses!

I hacked together the following bit of code to test my theory (I want to pull data from the db in chunks instead of querying a single random row at a time, hence the structure of the generator), and it works, but only because I've included a redundant `draw` call in my composite strategy. I've trawled through the docs and can't see anything about _entirely_ custom strategies, and subclassing `SearchStrategy` is verboten. Is there any better/approved way of defining a strategy based on a (n infinite) generator?

```python
from hypothesis import given
from hypothesis.strategies import composite, integers

ADDRESSES = [
    ("123 Fake Street", "Houston", "TX", "77002"),
    ("456 Fake Street", "Houston", "TX", "77002"),
    ("789 Fake Street", "Houston", "TX", "77002"),
    ("1000 Fake Street", "Houston", "TX", "77002"),
]

class AddressGenerator:
    
    def __init__(self):
        # Start by pulling addresses from the database
        self._it = iter(ADDRESSES)
    
    def __next__(self):
        # Get the next address; if that fails, get
        # more addresses and then return them
        try:
            return next(self._it)
        except StopIteration:
            self._it = iter(ADDRESSES)
            return next(self._it)

generator = AddressGenerator()

@composite
def real_addresses(draw):
    _ = draw(integers())
    return next(generator)

@given(real_addresses())
def test_addresses(address):
    print(address)

test_addresses()
```

**Comment by honno** [comment]
> I want to pull data from the db in chunks instead of querying a single random row at a time, hence the structure of the generator

(hi Matthew!) If you want to test with real data (i.e. addresses from your db), do you need Hypothesis? I would just iterate over every address to test whatever consumes `address`. If your concern is speed/rate-limits/etc., I would just write a query which randomly samples your records. I might be missing something here?

---

What comes to mind when you want to test your code handling addresses is 1) parsing, where you could say pass a regex specification to `st.from_regex()`

```python
@given(street_address=st.from_regex("[0-9]{1,3}[abc]? [A-Z][a-z']*", fullmatch=True))
def test_street_address_parsing(street_address):
    ....
```

and 2) treating relational components correctly, say with real states and cities

```python
STATES_TO_CITIES = {
    "TX": ["Houston", "Austin", ...],
    "NY": ["New York", ...],
    ...
}

@given(data=st.data())
def test_relational_things(data: st.DataObject):
    state = data.draw(st.sampled_from(STATES_TO_CITIES.keys()))
    city = data.draw(st.sampled_from(STATES_TO_CITIES[state]))
    ...
```

**Comment by badge** [comment]
@honno hello Mr. Barber! Thanks for the reply, it all makes sense. The wider context of the problem is that I _do_ want to use Hypothesis for all the non-real-world data we have (because it has myriad variations and generating sensible tests for them all is tricky). Previously we were using pytest's [parametrized fixtures](https://docs.pytest.org/en/7.1.x/how-to/fixtures.html#using-marks-with-parametrized-fixtures). So the real address strategy would be used in a wider context such as:

```python
class MonthlyBill(BaseModel):
    
    bill_month: dt.date
    bill_value: float
    bill_volume: float

class AddressDetail(BaseModel):
    
    address_line_1: str
    city: str
    state: str
    zipcode: str
    utility_account_number: int
    monthly_bills: Optional[List[MonthlyBill]]
    

simple_address = st.builds(AddressDetail)

@st.composite
def addresses(draw):
    address_line_1, city, state, zipcode = draw(real_addresses())
    address = draw(simple_address)
    address.address_line_1 = address_line_1
    address.city = city
    address.state = state
    address.zipcode = zipcode
    return address
```

We have a few such models which need real address data; I was kinda hoping to avoid writing composite strategies for all of them. On reflection, getting four separate strategies from a single generator for the four address parts and making sure they stayed in sync would probably be a nightmare/impossible anyway, so I guess I have to, in which case the generator works fine as it is.

**Comment by honno** [comment]
Ah never really used `st.builds()` things, I see your problem now. I would then say query your DB for all addresses or a random/diverse sample first, then pipe that into `st.sampled_from()`.

```python
Address = tuple[str, str, str, str]

addresses: list[Address] = ...  # result of your query

addresses_strat: st.SearchStrategy[Address] = st.sampled_from(addresses_sample)
```

Then you utilise [`st.shared()`](https://hypothesis.readthedocs.io/en/latest/data.html?highlight=shared#hypothesis.strategies.shared) so you can draw components of the addresses separately but in sync with another.

```python
shared_addresses_strat: st.SearchStrategy[Address] = st.shared(addresses())

address_detail_strategy: st.SearchStrategy[AddressDetail] = st.builds(
    AddressDetail,
    address_line_1=shared_addresses_strat.map(lambda a: a[0]),
    city=shared_addresses_strat.map(lambda a: a[1]),
    state=shared_addresses_strat.map(lambda a: a[2]),
    zipcode=shared_addresses_strat.map(lambda a: a[3]),
)
```

But yeah given the relational aspect of things, it might be better ditching `st.builds()` and create your own strategy as you have done.

```python
addresses: list[Address] = ...  # result of your query

@st.composite
def addresses(draw: st.DrawFn) -> AddressDetail:
    address_line_1, city, state, zipcode = draw(st.sampled_from(addresses_sample))
    utility_account_number = draw(st.integers())
    monthly_bills = st.none() | st.builds(MonthlyBill)
    return AddressDetail(address_line_1, city, state, zipcode, utility_account_number, monthly_bills)
```

**Comment by Zac-HD** [comment]
One other thing which is **really important:**  you need to make sure that if Hypothesis makes the same choices, your test (or custom strategy) will do the same thing.  This is *essential* for avoiding flakiness and allowing shrinking to work.

Concretely, you need to use `sampled_from()` rather than iterating a generator so that Hypothesis is choosing test data at all, and if you're downsampling you need to take a *deterministic* sample of your full data (e.g. using a fixed random seed).

**Comment by badge** [comment]
@honno @Zac-HD thanks for the detail guys–this is awesome and much appreciated! 🙏🏻
