### ISSUE TITLE
[FEATURE] Dependent Strategies

### ISSUE THREAD

**Issue by fscarlato** [HypothesisWorks/hypothesis#3470]
Is it possible to write something like this?

ForAll users And ForAll posts, ForAll messages created by the user: test something.

```
@given(
   user=users
   post=posts(user),
   msg = messages(user)
)
def test(user,post,msg):
   # Do something with the user and the user's post
```

Where posts(users) returns a strategy that builds a post with the user generated by the first strategy.
The same for messages(user)

I know this is not legal python, since keywords can't refer previous keywords, but  how can i achieve this with hypothesis?

**Comment by honno** [comment]
You might want to use `[st.data()`](https://hypothesis.readthedocs.io/en/latest/data.html?highlight=data#hypothesis.strategies.data), e.g.

```python
def @given(user=users, data=st.data())
def test_something(user, data):
    post = data.draw(posts(user))
    msg = data.draw(messages(user))
```

**Comment by rsokl** [comment]
You can also leverage the `shared` strategy to help achieve something closer to the form-factor you are looking for: https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.shared
