### ISSUE TITLE
Use @example with RuleBasedStateMachine?

### ISSUE THREAD

**Issue by jab** [HypothesisWorks/hypothesis#3501]
Read through https://hypothesis.readthedocs.io/en/latest/stateful.html and am trying `RuleBasedStateMachine` for the first time.[1] One thing I don't see in those docs (nor in https://hypothesis.readthedocs.io/en/latest/reproducing.html#hypothesis.example) is how to use something like `@example()` to make sure a particular sequence of states + state transitions is tested.

Is that just undocumented, or not currently supported?

[1] https://github.com/jab/lfu-cache/blob/main/test_lfu.py in case of interest - this was lots of fun thanks to Hypothesis :)

**Comment by Zac-HD** [comment]
`RuleBasedStateMachine` is designed to be reproducible, albeit not via the `@example()` decorator - on failure, it should print a little program that you can copy-paste into a standard test function (to avoid running at import-time)  🙂 

See [the docs on state machines](https://hypothesis.readthedocs.io/en/latest/stateful.html#rule-based-state-machines), ctrl-f for `Note how it’s printed out a very short program that will demonstrate the problem.`
