### ISSUE TITLE
Hypothesis fails with ForwardRefs and recursive pydantic models

### ISSUE THREAD

**Issue by apirogov** [HypothesisWorks/hypothesis#3519]
I would like to use hypothesis to generate instances of pydantic models, but it looks like it cannot handle recursive models with ForwardRefs.

(Quite) minimal example triggering the problem:

```python
from pydantic import BaseModel
from typing import Optional, Union
from hypothesis import given, strategies as st

class Dummy(BaseModel):
    x: Optional[Union[int, Dummy]]

Dummy.update_forward_refs()


@given(st.builds(Dummy))
def test_dummy(obj):
    print(obj.json(indent=2))
```

When running this with pytest, it fails with:
```
E           hypothesis.errors.ResolutionFailed: Could not resolve ForwardRef('Optional[Union[int, Dummy]]') to a strategy; consider using register_type_strategy

.../site-packages/hypothesis/strategies/_internal/types.py:442: ResolutionFailed
```

**Extra info:**
* Python 3.8
* pydantic 1.10.2
* hypothesis 6.58
* pytest 7.0.1

**Comment by Zac-HD** [comment]
Thanks for the report - I cut this down further to:

```python
import typing
from pydantic import BaseModel
from hypothesis.internal import compat

class Dummy(BaseModel):
    x: "typing.Union[int, Dummy]"

Dummy.update_forward_refs()
print(typing.get_type_hints(Dummy))
print(compat.get_type_hints(Dummy))
```
```
{'__slots__': typing.Tuple[str, ...], 'x': typing.Union[int, __main__.Dummy]}
{'__slots__': typing.Tuple[str, ...], 'x': ForwardRef('typing.Union[int, Dummy]'), 'data': typing.Any, 'return': <class 'NoneType'>}
```

digging even further, I think this is because Hypothesis prioritizes the annotations in a `.__signature__` attribute over the results of `typing.get_type_hints()`.  That still seems correct in general, but arguably we *shouldn't* do so when the new value is a ForwardRef and there's an existing non-forward-ref annotation.

**Comment by rsokl** [comment]
With #3521

```python
from pydantic import BaseModel
from typing import Optional, Union
from hypothesis import given, strategies as st

class Dummy(BaseModel):
    x: Union[int, "Dummy"]

Dummy.update_forward_refs()


@given(st.builds(Dummy))
def test_dummy(obj):
    print(obj)

test_dummy()
```
```
x=0
x=22658
x=Dummy(x=0)
x=Dummy(x=16792)
x=Dummy(x=0)
x=0
x=0
x=2271479883078318998
x=Dummy(x=0)
x=Dummy(x=Dummy(x=0))
...
```

**Comment by apirogov** [comment]
Thanks for the quick fix! :)

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Planner kept re-emitting patches that already failed (reuses_unappliable_anchor).

Relevant files:
- hypothesis/tests/cover/test_lookup.py: path components match issue terms, test file; bm25 rerank score=70.757; matched issue terms: hypothesis, fails, forwardrefs, recursive, i, would
- hypothesis/tests/cover/test_type_lookup.py: path components match issue terms, test file; bm25 rerank score=45.433; matched issue terms: hypothesis, fails, recursive, pydantic, generate, instances
- hypothesis/tests/nocover/test_build_signature.py: path components match issue terms, test file; bm25 rerank score=24.051; matched issue terms: hypothesis, pydantic, models, use, import, typing
- hypothesis/src/hypothesis/strategies/_internal/recursive.py: filename appears in issue text, path components match issue terms; bm25 rerank score=14.433; matched issue terms: hypothesis, recursive, use, import, typing, strategies
- brand/hypothesis.gpl: filename appears in issue text; bm25 rerank score=0.590; matched issue terms: hypothesis, import, 1, 0
- hypothesis/src/_hypothesis_globals.py: path components match issue terms; bm25 rerank score=4.157; matched issue terms: hypothesis, import, test, 2, pytest, not

Attempts:
Attempt 1: success=False
File: hypothesis/strategies/_internal/types.py
Result: patch_apply_failed
Error:
Search/replace edit failed: edit 1 target file was not found: hypothesis/strategies/_internal/types.py.

Attempt 2: success=False
File: src/hypothesis/strategies/_internal/types.py
Result: patch_apply_failed
Error:
Search/replace edit failed: edit 1 target file was not found: src/hypothesis/strategies/_internal/types.py.

Attempt 3: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Token usage: 33791/80000
