### ISSUE TITLE
Improve our dev cycle by making CI faster

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#3524]
I split things up into smaller pieces in #3517 which did drop some serial time, but we're still taking ~25 minutes for CI which is pretty annoying.  Some ideas to investigate:

- Cache the tox env so that we can drop ~90s off the install step (current config tries but doesn't?)
- Get someone to pay for larger runners for Hypothesis so we can use more cores (maybe Microsoft or Github?)
- Make tests faster and/or move them out of `tests/cover/`
- Use pytest-cov to make the actual coverage job faster via xdist compatibility
- Work out why Windows tests take twice as long as the others?
- Something else clever?

**Comment by jobh** [comment]
If you're feeling adventurous, limiting the tests to only run those that touch the changed code (I found https://github.com/tarpas/pytest-testmon but there may be others)

(this is just a drive-by idea, not recommendation since I haven't tried it)

**Comment by Zac-HD** [comment]
I like the idea, but get very nervous about getting fancy when we have so much memoization all over the place.  Coverage also has nontrivial performance overhead, and conflicts with some features of the explain phase too.

**Comment by jobh** [comment]
It's boring work, but modifying or moving just the top-7 slowest test might save ~120s or so. `check-coverage`:

```
1  29.18s call     hypothesis-python/tests/numpy/test_gen_data.py::test_efficiently_generates_all_unique_array
2  23.35s call     hypothesis-python/tests/numpy/test_from_dtype.py::test_infer_strategy_from_dtype
3  22.62s call     hypothesis-python/tests/cover/test_stateful.py::test_multiple_precondition_bug
4  18.01s call     hypothesis-python/tests/cover/test_searchstrategy.py::test_example_raises_unsatisfiable_when_too_filtered
5  17.92s call     hypothesis-python/tests/cover/test_validation.py::test_does_not_error_if_min_size_is_bigger_than_default_size
6  10.69s call     hypothesis-python/tests/cover/test_regex.py::test_fullmatch_generates_example[[ab]*-aBb]
7  9.08s call     hypothesis-python/tests/cover/test_sampled_from.py::test_efficient_lists_of_tuples_first_element_sampled_from
```

Of the two I have looked into so far, no,3 can be safely moved to nocover (#3856) and no.1 is a performance anomaly with 100x potential (#3857). I'm not planning to look into more immediately, but there seem to be plenty opportunity for small gains here.

**Comment by Zac-HD** [comment]
Windows tests are slow mostly because they're running all the tests in a single worker; splitting out cover/nocover/rest like we do for Linux would make them ~3x faster.  

`coverage` job I think moving to `pytest-xdist` + `pytest-cov` (postdating our current setup!) would also be a ~2x speedup for very little work.
