### ISSUE TITLE
Hypothesis-like in Go

### ISSUE THREAD

**Issue by morganhein** [HypothesisWorks/hypothesis#3526]
Not sure if this fits your bill for listing other languages with hypothesis implementations in the README, but there is a library that is **heavily inspired** by hypothesis here for Go: https://github.com/flyingmutant/rapid

I am not affiliated with the project, just spreading awareness.

**Comment by Zac-HD** [comment]
Thanks for letting us know!  It doesn't fit our "literally Hypothesis implementations" list, but I'll keep this in mind when we update our "PBT in every language" blog post 🙂
