### ISSUE TITLE
Document reject() function.

### ISSUE THREAD

**Issue by jenstroeger** [HypothesisWorks/hypothesis#3535]
I noticed that e.g. the [Getting started with Hypothesis](https://hypothesis.works/articles/getting-started-with-hypothesis/) article demonstrates the use of `hypothesis.reject()`. However, I wasn’t able to find more documentation on that function, likely because there is none:

https://github.com/HypothesisWorks/hypothesis/blob/226028dcf62b7c7a239574af6f5d69559be0febc/hypothesis-python/src/hypothesis/control.py#L23-L24

Would it make sense/be possible to elaborate?

Thank you!

**Comment by rsokl** [comment]
I think a reasonable description would be:

```
"""
Discards an example by raising `UnsatisfiableAssumption`.

Hypothesis won’t count it towards the ‘budget’ of examples it is allowed to run.
"""

I'll add documentation to this function.

**Comment by jenstroeger** [comment]
Great, thank you @rsokl!

**Comment by Zac-HD** [comment]
The reason you won't see it anywhere in the docs is that I'd prefer to point people to `assume(False)` - since this is exactly equivalent and I'd rather have only one (obvious) way to do it.

See https://github.com/HypothesisWorks/hypothesis/issues/2943 for steps to get this fixed in the article though 😓

**Comment by jenstroeger** [comment]
That makes sense, thanks @Zac-HD 

Perhaps for the sake of making your intent clear it might make sense then to implement `reject()` by calling [`assume()`](https://github.com/HypothesisWorks/hypothesis/blob/679ce871888ccd956077161807f8297708f088a4/hypothesis-python/src/hypothesis/control.py#L27-L36):
```python
def reject() -> bool:
    return assume(False)
```
That would also raise the `UnsatisfiedAssumption` at the cost of an extra function call… 🤔 Anyway. All good 👍🏼
