### ISSUE TITLE
@examples for GenericStateMachine?

### ISSUE THREAD

**Issue by Daenyth** [HypothesisWorks/hypothesis#354]
I don't see any section in the documentation that shows how to pass specific examples to a GenericStateMachine test. What's the right way to do this? I suppose I could write a test case that instantiates it and calls execute_step manually, but that seems like boilerplate that I shouldn't need.

**Comment by Daenyth** [comment]
Doing it as a manual test means I don't get the nice example-printing at the end, but instead get a much more complicated stack trace that's harder to debug than if the normal state runner just found this series of events

**Comment by DRMacIver** [comment]
Yeah, there's no support for example in stateful testing. Calling execute\_step manually in a test is probably about as good as you're going to get right now. I'm open to suggestions of a better API but I'm not sure what it would look like.

I'm not sure what the benefit of the example printing would be in the manual test though. It mostly prints out exactly what's written down in the test.

**Comment by Daenyth** [comment]
The benefit of printing the steps is that the person reading the test failure has one output style to understand - whether it was a specific example step or a generated series of steps the output would be the same. That's not the case if I call it manually.

I think an api like this would be relatively useful:

```python
run_state_machine_as_test(FormMappingStateMachine,
                          settings=settings(),
                          examples=[...])
```

Alternately:

```python
@examples=([...])
class MyStateMachine(GenericStateMachine):
    ...
```

Maybe both?

**Comment by Daenyth** [comment]
If you approve of that API I might try a small PR for that, based on glancing at the GenericStateMachine code I think it should be straightforward

**Comment by Zac-HD** [comment]
`GenericStateMachine` is so flexible that I think instantiating and manually driving the class is probably the best way to write explicit examples.  `@example(...)` is simply not supported for stateful tests.
