### ISSUE TITLE
Add practical Pythonic examples

### ISSUE THREAD

**Issue by adamatan** [HypothesisWorks/hypothesis#3544]
# Why do we need more examples?

The [documentation at the examples directory states](https://github.com/HypothesisWorks/hypothesis/tree/master/hypothesis-python/examples):

>  Right now it's a bit small and fairly algorithmically focused. Pull requests to add more examples would be greatly appreciated, especially ones using e.g. the Django integration or testing something "Businessy".

Documentation is essential for in-depth review. However, examples are essential for quick onboarding and for understanding the usage of a package or a feature.

The two existing examples contain fairly complicated algorithms. Understanding them takes a few minutes, which is too much for developers who just want to understand how to use `Hypothesis`, or a specific testing feature.

## The Plan

1. Add a few example files focused on self-contained, quick onboarding code. The examples will cover simple classes with plain business logic rather than algorithms. The examples will generally follow the [quick start guide](https://hypothesis.readthedocs.io/en/latest/quickstart.html#an-example) and the [Details and advanced features](https://hypothesis.readthedocs.io/en/latest/details.html) sections of the documentation.
2. Enumerate the examples to create a learning path.
3. Test the examples using GH actions.

## Feedback

I'd appreciate any feedback on my plan and actual code! Feel free to comment here.

**Comment by Zac-HD** [comment]
Sounds fantastic - thanks @adamatan!

More broadly I'd love to restructure the docs a bit to explicitly follow https://diataxis.fr/, but it's not yet been the highest-priority thing for me to do personally and nobody else has volunteered either.  As you develop a learning path, it might be useful to keep the idea of explanations vs how-to guides in mind?

**Comment by adamatan** [comment]
Hi @Zac-HD , thanks for the quick reply. I wasn't familiar with Diátaxis and it was a good read.

The first examples I intend to write should help the newcomer onboarding, and reach a "A-HA!" moment as quickly as possible. The first goal is to help the user run a minimalistic example. The second goal is to help them appreciate the power of auto-generated examples.
Within the Diátaxis frame of thought, it fits into the tutorial section.

This is what I have in mind for the first example. WDYT?

```python
from hypothesis import given
from hypothesis import strategies as st


# Our tested class
class Product():

    def __init__(self, price: float) -> None:
        assert price >= 0
        self.price: float = price

    def get_discount_price(self, discount_percentage: float):
        assert 0 <= discount_percentage <= 100
        return self.price * (discount_percentage / 100)


# The @given decorater generates examples for us!
@given(
    price=st.floats(min_value=0),
    discount_percentage=st.floats(min_value=0, max_value=100)
)
def test_a_discounted_price_is_not_higher_than_the_original_price(price, discount_percentage):
    product = Product(price)
    assert product.get_discount_price(discount_percentage) <= product.price

```

**Comment by Zac-HD** [comment]
Looks good!

**Comment by jenstroeger** [comment]
@adamatan in general I agree that examples will be a great, illustrating help!

In your code snippet [above](https://github.com/HypothesisWorks/hypothesis/issues/3544#issuecomment-1385102889), it looks to me like `Product` is the class under test (i.e. the production code that ships) and as such shouldn’t contain test assertions (because [`assert` can be removed](https://docs.python.org/3/using/cmdline.html#cmdoption-O)). To make the test more realistic, I’d use proper `if` checks and raise a `ValueError` and then have Hypothesis throw _any_ float value at it (because the function contract is `price: float`).

**Comment by Zac-HD** [comment]
More precisely it's fine for production code to contain assertions (testing in production is a real discipline!), just not to use them for validating user input.  Put another way, asserts should be used to catch your own mistakes, not your customers 😁

**Comment by Zac-HD** [comment]
That looks good to me!  I'll aim to do a final review and merge tonight 🙂

**Comment by Zac-HD** [comment]
I'd suggest just opening PRs directly, since we've already discussed the general principle you don't need an issue for each one 🙂
