### ISSUE TITLE
Ghostwriter unaware of imports for regex strategies

### ISSUE THREAD

**Issue by JensHeinrich** [HypothesisWorks/hypothesis#3549]
Not sure if this is a bug or a missing feature, but when using the ghostwriter on the following code

```project/minimal_example.py
import re
from typing import NewType

from hypothesis.strategies import register_type_strategy
from hypothesis import strategies as st


TestType = NewType('TestType', str)

register_type_strategy(TestType, st.from_regex(re.compile(".+")))

def something(t: TestType):
    pass
```

the following broken code is generated

```py
# This test code was written by the `hypothesis.extra.ghostwriter` module
# and is provided under the Creative Commons Zero public domain dedication.

import project.minimal_example
from hypothesis import given, strategies as st

# TODO: replace st.nothing() with an appropriate strategy


@given(x=st.nothing())
def test_fuzz_TestType(x):
    project.minimal_example.TestType(x=x)


@given(t=st.from_regex(re.compile(r".+", re.UNICODE)))
def test_fuzz_something(t):
    project.minimal_example.something(t=t)
```

Maybe calling `_imports_for_object` from `_imports_for_strategy` for `from_regex` strategies would be a solution, but I have no idea how to add that case inside the `LazyStrategy` branch.

**Comment by Zac-HD** [comment]
PR comments over on the PR, but if you have more general comments on the Ghostwriter I'd love to hear about what you're using it for, any praise or complaints, how it's affected your dev cycle...

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Same patch produced the same failure twice.

Relevant files:
- hypothesis/src/hypothesis/extra/ghostwriter.py: filename appears in issue text, path components match issue terms; bm25 rerank score=53.346; matched issue terms: ghostwriter, imports, regex, strategies, not, if; bm25 rerank score=56.921; matched issue terms: ghostwriter, imports, regex, strategies, not, if
- hypothesis/src/hypothesis/strategies/_internal/core.py: path components match issue terms; bm25 rerank score=40.957; matched issue terms: imports, regex, strategies, not, if, missing; bm25 rerank score=43.451; matched issue terms: imports, regex, strategies, not, if, missing
- hypothesis/src/hypothesis/core.py: path components match issue terms; bm25 rerank score=35.898; matched issue terms: ghostwriter, strategies, not, sure, if, bug
- hypothesis/src/hypothesis/internal/conjecture/providers.py: path components match issue terms; bm25 rerank score=26.866; matched issue terms: strategies, not, if, bug, but, when; bm25 rerank score=26.622; matched issue terms: strategies, not, if, bug, but, when
- hypothesis/src/hypothesis/internal/entropy.py: path components match issue terms; bm25 rerank score=24.714; matched issue terms: ghostwriter, strategies, not, if, but, when
- hypothesis/src/hypothesis/control.py: path components match issue terms; bm25 rerank score=20.718; matched issue terms: strategies, not, if, but, when, using; bm25 rerank score=20.282; matched issue terms: strategies, not, if, but, when, using

Attempts:
Attempt 1: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Attempt 2: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Token usage: 27743/80000
