### ISSUE TITLE
Add compat with pytest-capturelog for note()-style logging capture?

### ISSUE THREAD

**Issue by Daenyth** [HypothesisWorks/hypothesis#356]
Using hypothesis with code that has logging statements makes it very difficult to use those log calls to debug.

Having the ability to have logging output captured in the style of `note()` would be extremely useful. The [pytest-capturelog](https://pypi.python.org/pypi/pytest-capturelog) plugin collects the logging output into the test failure message. It would be really nice to have some kind of cross-compatibility with them so that it can group captured logs by example rather than at the test-function level

**Comment by Zac-HD** [comment]
As of pytest 3.3, log capturing is built in - meaning that logs are probably being captured (for all examples, eek) more often, *and* there's a standard thing that we can be compatible with in the pytest plugin (in hypothesis.extra)

**Comment by Zac-HD** [comment]
This may be as simple as disabling logging for all but the final example of a test.
