### ISSUE TITLE
#3540 causes `RecursionError` in particular draw pattern  

### ISSUE THREAD

**Issue by rsokl** [HypothesisWorks/hypothesis#3560]
#3540 introduces a change that causes a `RecursionError` in [MyGrad's test suite](https://github.com/rsokl/MyGrad/actions/runs/4002289112/jobs/6869371400).

This is a weird bug. It seems to be specific to drawing from an array-based strategy that spans multiple lines *and* that includes an identity mapping (I said it was weird!).

The following tests pass (note the xfail)

```python
import pytest

import hypothesis.extra.numpy as hnp
import hypothesis.strategies as st
from hypothesis import given

@given(st.data())
def test_one_line_identity_passes(data):
    x = data.draw(hnp.arrays(shape=(2,), dtype=float).map(lambda x: x))


@pytest.mark.xfail(raises=RecursionError, strict=True)
@given(st.data())
def test_multiline_identity_fails(data):
    x = data.draw(
        hnp.arrays(
            shape=(2,),
            dtype=float,
        ).map(lambda x: x)
    )


@given(st.data())
def test_multiline_non_identity_passes(data):
    x = data.draw(
        hnp.arrays(
            shape=(2,),
            dtype=float,
        ).map(lambda x: 1 * x)
    )
    
    
@given(st.data())
def test_multiline_non_array_passes(data):
    x = data.draw(
        st.lists(
            st.integers(
                1,
                5,
            )
        ).map(lambda x: x)
    )
```

**Comment by Zac-HD** [comment]
Wow, finally sniped this and feel kinda stupid: the following call can recurse, but *doesn't copy the stack used for cycle-detection.*

https://github.com/HypothesisWorks/hypothesis/blob/48165d90f6afc1c0cd618ae0659f02a88b579f8b/hypothesis-python/src/hypothesis/vendor/pretty.py#L359-L361

Bleeding obvious once you see it, and it's a single-line fix🤦‍♂️

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Context collection made no progress after 1 attempts.

Relevant files:
- hypothesis/src/hypothesis/core.py: path components match issue terms; bm25 rerank score=58.170; matched issue terms: particular, draw, introduces, change, s, test
- tooling/src/hypothesistooling/__main__.py: matched GitHub code search; bm25 rerank score=35.702; matched issue terms: causes, pattern, change, s, test, https
- hypothesis/src/hypothesis/strategies/_internal/regex.py: path components match issue terms; bm25 rerank score=18.340; matched issue terms: particular, draw, pattern, s, https, github; bm25 rerank score=19.971; matched issue terms: particular, draw, pattern, s, https, github
- hypothesis/src/hypothesis/provisional.py: path components match issue terms; bm25 rerank score=17.174; matched issue terms: draw, pattern, change, s, test, https; bm25 rerank score=17.324; matched issue terms: draw, pattern, change, s, test, https
- hypothesis/src/hypothesis/strategies/_internal/strings.py: path components match issue terms; bm25 rerank score=14.532; matched issue terms: draw, pattern, change, s, https, github; bm25 rerank score=14.501; matched issue terms: draw, pattern, change, s, https, github
- hypothesis/src/hypothesis/strategies/_internal/random.py: path components match issue terms; bm25 rerank score=13.783; matched issue terms: draw, https, github, com, i, was; bm25 rerank score=13.002; matched issue terms: draw, https, github, com, i, was

Attempts:
No patch attempts were made.

Token usage: 17382/80000
