### ISSUE TITLE
Automatically create `.gitignore` in `.hypothesis/`

### ISSUE THREAD

**Issue by mhils** [HypothesisWorks/hypothesis#3566]
First off, thank you for building hypothesis! 🍰 I have a small feature suggestion inspired by mypy:
When running mypy, it creates a `.mypy_cache/` directory with a `.gitignore` file as follows:
```gitignore
# Automatically created by mypy
*
```

It would be awesome if hypothesis did the same with `.hypothesis/`. This way projects using hypothesis wouldn't all need to manually add the directory to their `.gitignore`. 😃

**Comment by Zac-HD** [comment]
See https://github.com/HypothesisWorks/hypothesis/issues/2339#issuecomment-581683484:

> Hmm.  I like the idea, but there are a couple of challenges:
>
> 1. We don't actually create the `.hypothesis` directory until we write something to it.  Adding a check to every place that this can happen would be pretty tedious, and if we cache more data we might forget to ensure a `.gitignore` too.  Writing it every time is not a good solution, as that overwrites user edits.
> 2. While we recommend ignoring the `.hypothesis` directory entirely, the on-disk example DB format *can* be shared via version control.  This is unstable in the face of changing code and Hypothesis versions, so the `@example` decorator is a much better workflow... but while we could drop this I'd want to think twice first.  (this matters because gitignores in subdirectories override those elsewhere)
> 3. What about ignore files for other VCS?  (I think "on request" would be fine)
> 4. What about other files, e.g. a README?  ("could be helpful, but (1) applies")
>
> So it seems like a useful change, but would probably involve a fair bit of refactoring and perhaps something like a cache manager object.

and 

> The [other] problem is that our generated `.gitignore` would override any module-level "do not ignore the example db" entry.  I think given the rarity of someone actually wanting to [commit the db to git], we *could* change it and document the change, but it's not a high priority for me.

**Comment by mhils** [comment]
Thanks for the swift reply and sorry for missing the original issue! Seems like I need to work on my search skills. :)

> * While we recommend ignoring the `.hypothesis` directory entirely, the on-disk example DB format _can_ be shared via version control.  This is unstable in the face of changing code and Hypothesis versions, so the `@example` decorator is a much better workflow... but while we could drop this I'd want to think twice first.  (this matters because gitignores in subdirectories override those elsewhere)

A simple workaround here would be to not overwrite an existing `.gitignore` file, which allows folks to empty their `.gitignore` to include `.hypothesis/` if desired.


> We don't actually create the `.hypothesis` directory until we write something to it.  Adding a check to every place that this can happen would be pretty tedious, and if we cache more data we might forget to ensure a `.gitignore` too.  Writing it every time is not a good solution, as that overwrites user edits.

FWIW I did a hacky test implementation in [`configuration.storage_directory`](https://github.com/HypothesisWorks/hypothesis/blob/48165d90f6afc1c0cd618ae0659f02a88b579f8b/hypothesis-python/src/hypothesis/configuration.py#L30), but that's obviously not ideal. I guess the refactor is the annoying part here.

**Comment by Zac-HD** [comment]
Closing this because I don't think anyone will volunteer to do or pay for this pretty tricky refactoring.
