### ISSUE TITLE
How to customize the traceback of test failure in Hypothesis

### ISSUE THREAD

**Issue by hello-fri-end** [HypothesisWorks/hypothesis#3583]
Hypothesis will print a list of parameters that the test function was called with, including the test function itself, is there a way we can hide the trackback from Hypothesis in the case if it was an internal or falsifying example error, and only print the result and the parameters in a pretty format? I couldn't find anything related to this in the documentation

**Comment by Zac-HD** [comment]
Hypothesis computes a string representation of the minimal failing example - this includes the test name and is not configurable.

However, we're not responsible for displaying that or a traceback!  Instead, we add it to the [PEP-678 `__notes__` attribute](https://peps.python.org/pep-0678/), and allow python/unittest/pytest/whatever-you-use to display as you wish.  You could insert your own code to modify the string representation at this stage, I suppose, though I'm not clear on why you'd want to.

**Comment by hello-fri-end** [comment]
Thanks!

**Comment by hello-fri-end** [comment]
I was wondering if it is possible to style the traceback using a library like `rich`. E.g here's what the output looks like with the pytest-rich plugin
![screenshot](https://user-images.githubusercontent.com/43880587/220588247-367bfdc5-c10a-449d-b0ed-2324885c34b7.png)
The plugin, however, doesn't do anything for the hypothesis traceback printed by pytest. Is there any way the same result can be achieved for the hypothesis traceback?

**Comment by Zac-HD** [comment]
https://github.com/Textualize/rich/issues/2238 needs to be fixed in Rich, unfortunately.

**Comment by hello-fri-end** [comment]
> [Textualize/rich#2238](https://github.com/Textualize/rich/issues/2238) needs to be fixed in Rich, unfortunately.

Oh, hope they work on it soon 🙏
