### ISSUE TITLE
Example of how to store example database persistently on CI

### ISSUE THREAD

**Issue by asmeurer** [HypothesisWorks/hypothesis#3586]
The examples database docs talk about the examples database somewhat abstractly https://hypothesis.readthedocs.io/en/latest/database.html. It mentions that you can persist things on CI but doesn't really give all the details on how. 

It would be useful to have a concrete example of how such a thing can be set up on GitHub Actions. Or even better, if it's possible, it would be nice to just have a pre-made thing in the GitHub Actions marketplace that just does it for you. (docs for other CI providers would be nice too, but I think the vast majority of people are using GitHub Actions these days)

**Comment by Zac-HD** [comment]
I'd be happy to include the example configuration given in https://github.com/Zac-HD/hypofuzz/issues/14#issuecomment-1423910866 as part of https://github.com/HypothesisWorks/hypothesis/pull/3576 😄

**Comment by asmeurer** [comment]
That's complicated enough that I would suggest making a pre-made action file that does all that which people can just pull in (see https://docs.github.com/en/actions/using-workflows/reusing-workflows).

**Comment by agucova** [comment]
@asmeurer I tend to disagree, it's a three-step workflow that exposes meaningful user preferences. Having said that, creating a workflow is easy enough, that I wouldn't mind adding it at all.

@Zac-HD what do you think?

**Comment by Zac-HD** [comment]
[By default, the db is in your current working directory](https://hypothesis.readthedocs.io/en/latest/database.html), but you can configure this to use whatever location you wish - or an alternative such as Redis to avoid the filesystem entirely.

**Comment by Zac-HD** [comment]
We now have a complete example configuration listed under https://hypothesis.readthedocs.io/en/latest/database.html#hypothesis.database.GitHubArtifactDatabase, which doesn't just persist the database between CI runs but also pulls it down for local replay 😁
