### ISSUE TITLE
from_regex with "\d" produces unexpected characters

### ISSUE THREAD

**Issue by luebbert42** [HypothesisWorks/hypothesis#3590]
Python: 3.10.6
Hypothesis:  6.68.2

When I use "\d" with  from_regex I am getting unexpected characters. with r"[0-9]" it works like expected. What am I doing wrong?

```
from hypothesis import strategies as st
regex_strategy = st.from_regex(r"\d", fullmatch=True)
for n in range(0, 20):
   regex_strategy.example()

'𝟹'
'௯'
'𑱙'
'᧘'
'𞋵'
'௧'
'८'
'𐴶'
'𐒡'
'০'
'೨'
'9'
'𑵐'
'𖭘'
'𑜸'
'៣'
'𝟵'
'꯸'
'𑃳'
'᪇'
```

**Comment by Zac-HD** [comment]
Per https://docs.python.org/3/library/re.html#regular-expression-syntax, this is the intended behavior:

> `\d`
> For Unicode (str) patterns:  Matches any Unicode decimal digit (that is, any character in Unicode character category [Nd]). This includes [0-9], and also many other digit characters. If the [ASCII](https://docs.python.org/3/library/re.html#re.ASCII) flag is used only [0-9] is matched.

**Comment by luebbert42** [comment]
wow, didn't know that. I have to challenge my peers with that. Thanks a lot for the very quick response! :-)

**Comment by Zac-HD** [comment]
np!  In your peers' defense, other languages including Javascript _only_ support the ASCII-only semantics, so it's reasonable to be confused here 🙂
