### ISSUE TITLE
Combining `@composite` with `@example`

### ISSUE THREAD

**Issue by jacopok** [HypothesisWorks/hypothesis#3591]
The [documentation for the `data()` strategy](https://hypothesis.readthedocs.io/en/latest/data.html#drawing-interactively-in-tests) states:

> This is similar to [@composite](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.composite), but even more powerful as it allows you to mix test code with example generation. The downside of this power is that [data()](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.data) is incompatible with explicit [@example(...)](https://hypothesis.readthedocs.io/en/latest/reproducing.html#hypothesis.example)s - and the mixed code is often harder to debug when something goes wrong.

 This implies that `@composite` is compatible with `@example`, i.e., that I should be able to do something like

```python
from hypothesis import strategies as st
from hypothesis import given, example

@st.composite
def two_numbers(draw):
    first = draw(st.integers())
    second = draw(st.integers())
    return first, second

@given(two_numbers())
@example(two_numbers(1, 1))
def test_my_numbers(two_numbers):
    first, second = two_numbers
    assert isinstance(first, int)
    assert isinstance(second, int)
```

However, this is not working as written (the `two_numbers` strategy cannot take the examples as arguments), and I am struggling to see what the syntax could be to accomplish the goal of having a specific example of the combined strategy tested every time.

I looked for this syntax both in the [`@example`](https://hypothesis.readthedocs.io/en/latest/reproducing.html#providing-explicit-examples) and [`@composite`](https://hypothesis.readthedocs.io/en/latest/data.html#composite-strategies) documentation and could not find it - so, is this indeed possible, as suggested by the snippet above?

If so, I think the syntax should be clarified in an example in either of those places.

Thanks!

**Comment by Zac-HD** [comment]
I think you were confusing `two_numbers()` the *strategy*, and `two_numbers` the *argument to the test function*.  I've renamed to clarify that:

```python
from hypothesis import strategies as st
from hypothesis import given, example

@st.composite
def two_numbers_strategy(draw):
    first = draw(st.integers())
    second = draw(st.integers())
    return first, second

@given(two_numbers_strategy())
@example((1, 1))  # this should be a value, not a strategy
def test_my_numbers(two_numbers):
    first, second = two_numbers
    assert isinstance(first, int)
    assert isinstance(second, int)
```

**Comment by jacopok** [comment]
Ah, so I just needed to pass it a tuple - makes a lot of sense in hindsight!

Maybe it would still be worth it to make a similar example explicitly in the documentation?
I won't reopen the issue myself, but this would have been quite helpful for me.
