### ISSUE TITLE
Slow (?) performance of composite strategy

### ISSUE THREAD

**Issue by andreasdoll** [HypothesisWorks/hypothesis#3593]
Hello

Thanks for this interesting library!

I use ``@composite`` to create a search strategy for a custom class. I was a bit surprised to see slow (?) data generation and wonder whether this is normal or something is wrong.

A minimal example is:

```python
from time import time
from hypothesis.strategies import composite, floats

@composite
def strategy(draw):
    a = draw(floats(min_value=1E4, max_value=1E5))
    return a
       
t0 = time()
strategy().example()
print(f"Took {round(time()-t0, 2)}s")
```

This takes (on my reasonable modern computer)  0.11 seconds. _Is that normal?_
I've tested with ``python 3.11``, ``hypothesis 6.68.2`` on ``Win 10``, but ``python 3.8 - 3.10`` don't seem to be quicker (by observing the actual test time).

Note that in my tests I'm using ``@given(strategy())`` and not ``example()``.

In my actual test I draw two floats, one integer, ``assume`` one statement and return my instantiated object.
Having ~50% of invalid sample (by ``assume``) this takes ~0.6 seconds to create 98 samples. Moving the object instantiation into the test (by returning the drawn numbers from ``strategy()``) doesn't reduce the generation time.

**Comment by Zac-HD** [comment]
The `.example()` method internally generates a whole list by running the test many times, and then returns random samples from that until it runs out.

So contra @honno, this is in fact the runtime to generate many test cases with `@given()`!  He's right that you should measure performance directly on the workload you care about though 🙂
