### ISSUE TITLE
Improve ghostwritten equivalence tests which use `st.iterables()` (with `itertools.tee()`?)

### ISSUE THREAD

**Issue by dmcooke** [HypothesisWorks/hypothesis#3595]
Pretty much by definition, an equivalence test between two functions has the same arguments passed to each function (or, observably-equivalent arguments).  However, the iterables generated by `strategies.iterables()` are one-shot iterators, and so can't be passed twice and be expected to generate the same values. The iterators would need to be recreated.

Testing equivalence using iterators is likely best done with a separate test, where new (independent) iterators are created to pass to each function.  It may look like this:

````
   @given(st.lists(st.integers()))
   def test_iterator_equivalent_f1_f2(values):
      result1 = f1(iter(values))
      result2 = f2(iter(values))
      assert result1 == result2
````

(Testing that a function that takes iterables can also take a one-shot iterator (if not documented that it can't) is a good thing, though: it's a property that's often overlooked.)

**Comment by Zac-HD** [comment]
This sounds pretty fiddly, but it'd be nice to [use `itertools.tee()` here](https://docs.python.org/3/library/itertools.html#itertools.tee)!  My question is then... what do we do about unions?  e.g. `f(x: T | Iteratble[T])` is a fairly common kind of signature, but neither your list-based approach nor `tee()` would work without adding some `if isinstance(...)` checks to the test.  Adding those seems fine though.

On the other hand, we should probably continue to ignore the problem of reusing mutable arguments; it's not _always_ a problem like iterator state would be, and it's fair to leave this to the user to resolve if necessary.

**Comment by Zac-HD** [comment]
Closing this because I think it just isn't worth the implementation complexity, in maintainability of the ghostwriter and to a lesser degree opportunity cost 😕
