### ISSUE TITLE
Needless inefficiency when using character whitelisting and/or lack of correct information.

### ISSUE THREAD

**Issue by michael-delarue-axomic** [HypothesisWorks/hypothesis#3601]
When I use hypothesis-csv to generate examples, it seems that it fails often due to filtering of text generation.  I get the following information for example. 

```
tests/test_inventory_diff.py::test_diff_should_sort_with_the_same_setup_as_sort:

  - during reuse phase (0.08 seconds):
    - Typical runtimes: ~ 76ms, ~ 85% in data generation
    - 1 passing examples, 0 failing examples, 0 invalid examples

  - during generate phase (116.37 seconds):
    - Typical runtimes: 75-166 ms, ~ 100% in data generation
    - 4 passing examples, 0 failing examples, 995 invalid examples
```

Trying to work out what's going on I turned on event statistics and get the following types of things (with the actual settings I want it can be much worse). 

```
tests/test_inventory_diff.py::test_diff_should_sort_with_the_same_setup_as_sort:

  - during reuse phase (0.01 seconds):
    - Typical runtimes: ~ 11ms, ~ 56% in data generation
    - 1 passing examples, 0 failing examples, 0 invalid examples

  - during generate phase (6.95 seconds):
    - Typical runtimes: 1-76 ms, ~ 89% in data generation
    - 99 passing examples, 0 failing examples, 337 invalid examples
    - Events:
      * 30.28%, Retried draw from text(characters(whitelist_categories=(), whitelist_characters='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'), min_size=1).filter(not_yet_in_unique_list) to satisfy filter

  - Stopped because settings.max_examples=100

```

Which suggests to me that, because a CSV is made up of multiple different character strings there's any invalid string makes the whole CSV example invalid. Obviously, if there's some other reason for the failure then I guess my bug is the fact that information is missing.  

I would like ("expect"???), instead, for "whitelist_characters" to, instead of filtering and producing an invalid value, use some level of clever wrapping of random values so that at in the worst case, say, 95% of the time it passed which would make the overall generation of an object with multiple strings pass most of the time. 

[Related post on the community list](https://groups.google.com/g/hypothesis-users/c/4GVW2P7wQak).

**Comment by Zac-HD** [comment]
There's not _that_ much we can do without a reproducing example, and `hypothesis-csv` is a third-party extension.

> Which suggests to me that, because a CSV is made up of multiple different character strings there's any invalid string makes the whole CSV example invalid. Obviously, if there's some other reason for the failure then I guess my bug is the fact that information is missing.

Only 30.28% of draws (including ultimately-invalid draws) needed to retry drawing from the `text()` strategy, which is much less than the 337 / (99 + 337) invalid examples - so I'm pretty sure it's not the text strategy that's the problem here.

To surface more information I'd try using `verbose` or even `debug` verbosity.  Unfortunately the flexibility and power of strategies also make it pretty tricky to do much automated debugging to help out here!
