### ISSUE TITLE
UniqueSampledListStrategy introduced in 6.17.4 produces biased samples

### ISSUE THREAD

**Issue by MaigoAkisame** [HypothesisWorks/hypothesis#3603]
In hypothesis 6.17.4 ([changelog](https://hypothesis.readthedocs.io/en/latest/changes.html#v6-17-4)), a new strategy was adopted to make the sampling of arrays with unique elements more efficient (see [these lines](https://github.com/HypothesisWorks/hypothesis/pull/3076/files#diff-c56f048e926cce76dc6cd811924136f5c97e0f68f59625869b4ab01f1dbe10e0R291-R304) in PR#3076).
More concretely, for arrays with <= 256 possible values, `UniqueSampledListStrategy` is used instead of `UniqueListStrategy`.

However, I'm seeing biased output when generating integer arrays of length 5 with unique or non-unique elements from 0 to 9.
The unique array [0, 9, 8, 7, 6] occurs much more frequently than others.
Even the non-unique array is affected: most of the time it ends up being [0, 0, 0, 0, 0].

Here's a minimum example to demonstrate the problem:
```
import hypothesis.strategies as st
import numpy as np

from hypothesis import given, settings
from hypothesis.extra.numpy import arrays


@given(
    a=arrays(np.int64, 5, elements=st.integers(min_value=0, max_value=9)),
    b=arrays(np.int64, 5, elements=st.integers(min_value=0, max_value=9), unique=True),
)
@settings(max_examples=10)
def dummy_test(a, b):
    print(a, b)


dummy_test()
```

With 6.17.3, this program generates much more diverse examples than 6.17.4.
If we change the range from [0, 9] to [0, 256], the problem disappears.

I've found the problem may be related to the conjecture engine consuming an [all-zero buffer](https://github.com/HypothesisWorks/hypothesis/blob/e6c6810c85ca097ee4147ed08509b19df6a664be/hypothesis-python/src/hypothesis/internal/conjecture/engine.py#L612) at the beginning of a run.
`UniqueListStrategy` is able to reject the arrays generated by the all-zero buffer, while `UniqueSampledListStrategy` lets them through.

I haven't looked further into the implementation of `UniqueListStrategy`, `UniqueSampledListStrategy`, and the conjecture engine.
But I'd like to confirm: is it intended behavior or a bug for one certain array to occur much more frequently than others?

**Comment by Zac-HD** [comment]
Thanks for your report!  This is not intended, and I'd like to fix it.

My first idea is to use rejection sampling for `UniqueSampledListStrategy` _iff_ you sampled the first element, i.e. parsed from an all-zero section of the buffer.  That should restore a more diverse distribution, while still being efficient in almost all cases.

**Comment by MaigoAkisame** [comment]
Thank you! May I know how soon this change will be released?

I'm updating the hypothesis dependency in my codebase.
If the change will be available in a few days, I'll wait for the new release.
Otherwise, I'll just grab the current version.

**Comment by Zac-HD** [comment]
No ETA, sorry, it'll happen when someone volunteers to write the patch, so I'd suggest grabbing the current version.

**Comment by MaigoAkisame** [comment]
Good, thanks!

**Comment by Zac-HD** [comment]
Unfortunately, on further investigation I think there's nothing we can do about this - we're caught in a dilemma and the current behavior seems like the best compromise possible.

1.  Hypothesis does not generate data uniformly at random, but instead uses a complicated heuristic distribution tuned to catch bugs (and some runtime feedback, etc.).  Relevantly here, we include runs of all-zero bits from the underlying layer, which improves recursive and other tree-shaped structures - conceptually, it's nice to have some minimal leaves and different-length branches.  This is why you see `[0, 0, 0, 0, 0]` for non-unique lists, and `[0, 9, 8, 7, 6]` for unique lists.
2. Given that we're going to generate *some* list of elements more often than you'd expect, `[0, 9, 8, 7, 6]` doesn't seem that much worse than `[0, 1, 2, 3, 4]`.  I'd *prefer* the latter - it's the natural minimal example, if we weren't doing this weird performance trick - but it doesn't seem that much worse than the former.  More importantly, I just can't see any way to get it without causing substantial slowdowns.

Drawing from `UniqueSampledListStrategy` currently takes O(1) setup plus O(N) work to generate a list of N elements (chosen from K).  The best option I could work out would instead take O(K) setup plus O(N x log(K)) to generate, which is *substantially* worse.  Apologies for any confusion or churn this caused.

**Comment by MaigoAkisame** [comment]
Thank you! I think I'll treat this as a feature rather than a bug then.
