### ISSUE TITLE
Add an `allow_negative_zero` flag to `FloatStrategy`

### ISSUE THREAD

**Issue by MaigoAkisame** [HypothesisWorks/hypothesis#3606]
This is a follow-up to #3603.

I've found that with the changes in 6.17.4, float numbers generated are often +0.0 and -0.0.

This has crashed one of my tests, which tests the "serialization of the minimum value in a float array":
When the input array contains both +0.0 and -0.0 (other elements are positive), the minimum value may be either +0.0 and -0.0 depending on the exact settings of SIMD (single instruction, multiple data). While +0.0 and -0.0 compare equal, their serialized forms differ in the sign bit.

I would like to propose adding a `allow_negative_zero` flag to `FloatStrategy` to explicitly disallow -0.0 from being generated.
This is necessary even if #3603 is resolved: -0.0 may still occur even though the probability is infinitesimal.

**Comment by Zac-HD** [comment]
I would suggest using a filter or map instead, for example `st.floats().map(lambda x: x if x else 0.0)`: the proposed `allow_negative_zero` flag is of fairly niche interest, _and_ it's quite practical to handle outside of the strategy itself.
