### ISSUE TITLE
Compatibility of hypothesis with Python3.11x

### ISSUE THREAD

**Issue by tnachan-splunk** [HypothesisWorks/hypothesis#3612]
Hi Folks,
According to the [PyPi Doc](https://pypi.org/project/hypothesis/) the latest support of hypothesis is for Python 3.10.
Does it also supports python 3.11x?
if not is there any plan to support it?

**Comment by Zac-HD** [comment]
We already support Python 3.11, and just need to update the classifiers so that it says so on PyPI 😅

**Comment by tnachan-splunk** [comment]
Thank you @Zac-HD  for the confirmation !
