### ISSUE TITLE
How to set max_improvements when doing targeted property-based testing

### ISSUE THREAD

**Issue by jat9292** [HypothesisWorks/hypothesis#3613]
Hello, maybe I am missing something, but I noticed that there is a default `max_improvements` parameter in the Optimiser class https://github.com/HypothesisWorks/hypothesis/blob/09e5035edbb68fafb1012c0e910da31d1bc3b370/hypothesis-python/src/hypothesis/internal/conjecture/optimiser.py#L34 which limits the hill climbing steps when doing the targeted testing to only 100 steps of improvement. Alas, I am using hypothesis for doing tests with an unbounded function on several thousands steps, I would like to change this value to a bigger one. What would be the best and easiest way to do it? It is possible to do it without forking the whole hypothesis repo to use a custom Optimiser?  
Thank you for your understanding.

EDIT : Actually I found that the number of optimization steps is adaptative with an exponential schedule, so my issue might not be relevant anymore if I am correct? https://github.com/HypothesisWorks/hypothesis/blob/e6c6810c85ca097ee4147ed08509b19df6a664be/hypothesis-python/src/hypothesis/internal/conjecture/engine.py#L862

**Comment by Zac-HD** [comment]
These internal functions are not user-configurable, but should indeed automatically adapt to your use case 🙂
