### ISSUE TITLE
hypothesis-python does not pin numpy, resulting in import error downstream

### ISSUE THREAD

**Issue by pllim** [HypothesisWorks/hypothesis#3625]
We use hypothesis with older numpy (1.20) in an older release branch. We started seeing failure when hypothesis 6.74 was released. If hypothesis-python is no longer compatible with older numpy, it should pin numpy minversion accordingly.

Example log: https://github.com/astropy/astropy/actions/runs/4812578157/jobs/8568004842?pr=14696

Example traceback:

```
astropy/time/tests/test_precision.py:13: in <module>
    from hypothesis.extra.numpy import array_shapes, arrays
hypothesis/extra/numpy.py:15: in <module>
    from numpy.typing import DTypeLike, NDArray
E   ImportError: cannot import name 'NDArray' from 'numpy.typing' (numpy/typing/__init__.py)
_ ERROR collecting astropy/time/tests/test_precision.py _
```

**Comment by Zac-HD** [comment]
Thanks for the report @pllim - we'll restore compatibility with older Numpy versions, and add a CI job based on the declared minimum version to prevent future regressions, within the next few days.

**Comment by pllim** [comment]
Thank you for the quick response! There is no rush on our end. We pinned that job to hypothesis 6.72.3 because turns out 6.72.4 also has the incompatible import.
