### ISSUE TITLE
Should strategies registered with `register_type_strategy` apply to subclasses?

### ISSUE THREAD

**Issue by jcrist** [HypothesisWorks/hypothesis#3634]
I'm trying to register a custom function strategy on a base class and have that strategy apply to all subclasses of the base class. Unfortunately, it seems like this isn't currently possible - the custom strategy only seems to match on the exact type, rather than on subclasses.

The following contrived example illustrates the issue:

```python
import hypothesis
import hypothesis.strategies as st
import warnings

warnings.simplefilter("ignore", hypothesis.errors.NonInteractiveExampleWarning)


class Base:
    pass


class Subclass(Base):
    pass


def strategy(cls):
    print("CUSTOM STRATEGY CALLED")
    return st.just(cls())


st.register_type_strategy(Base, strategy)


print("On Subclass:")
st.from_type(Subclass).example()

print("On Base:")
st.from_type(Base).example()
```

```
$ python test.py
On Subclass:
On Base:
CUSTOM STRATEGY CALLED
```

Is this intentional? Given this part of the `from_type` docstring I'd expect `strategy` to be called for both `Base` and `Subclass`:

```
3. If ``thing`` has one or more subtypes in the merged lookup, return
   the union of the strategies for those types that are not subtypes of
   other elements in the lookup.
```

**Comment by Zac-HD** [comment]
No, we can't use registered strategies (or functions-returning-strategies) to generate an instance of the subtype.  

It happens that this would work for you because your classes all have compatible signatures and you defined your `strategy` function to use `cls()`, but consider:

```python
class OtherSubclass(Base):
    def __init__(self, x):
        self.x = x

st.from_type(OtherSubclass).example()  # this can't possibly work!
```

---------

> If `thing` has one or more subtypes in the merged lookup, return the union of the strategies for those types that are not subtypes of other elements in the lookup.

This means that if you register a strategy for `Subclass`, we can give you an instance of `Subclass` to satisfy your request for an instance of `Base`!

```python
# Imagine here that `Base` has a required argument, so that we can't automatically `st.builds()` it.
st.register_type_strategy(Subclass, st.builds(Subclass, x=st.none()))

got = st.from_type(Base).example()
assert isinstance(got, Base)  # great, satisfied the contract
assert isinstance(got, Subclass)  # ...by providing a subclass!
```

**Comment by jcrist** [comment]
> This means that if you register a strategy for Subclass, we can give you an instance of Subclass to satisfy your request for an instance of Base!

Thanks! That clarifies that sentence for me, makes sense.

> we can't use registered strategies (or functions-returning-strategies) to generate an instance of the subtype.

I can understand why you can't use registered strategies to generate an instance of the subtype, but a registered function-returning-a-strategy should work, no? The function has full access to the type to customize the strategy in any way necessary, not unlike the existing `strategies.builds` function. Suppose I implement my own function similar to `strategies.builds`, then register that function for a base class - every subclass seen would generate its own strategy customized to fit that subclass. Can't the existing default behavior be viewed as something similar to?

```python
st.register_type_strategy(object, st.builds)
```

In my actual case I'm wanting to write my own customized version of `strategies.builds` to handle generating strategies for all subclasses of a particular dataclass-like-type. It'd be nice if this could work with the existing extension mechanism, rather than forcing registering a strategy manually for every subclass. In short, I'd like this to work:

```python
def my_builds(cls):
    """My custom function that is _like_ `strategies.builds`, but customized in a few ways for a particular base class"""
    ...

st.register_type_strategy(MyBaseClass, my_builds)
```
