### ISSUE TITLE
`register_type_strategy` doesn't work with lowercase builtin `list` type

### ISSUE THREAD

**Issue by kasbah** [HypothesisWorks/hypothesis#3635]
Using `register_type_strategy` doesn't seem to work with the built in `list` type available since python 3.9 (in fact `typing.List` is deprecated). 

hypothesis==6.75.1
pytest==7.3.1
Python 3.10.10

```python
from typing import get_args, Type, List
from hypothesis import strategies as st, given, infer


def _shorter_lists(list_type: Type) -> st.SearchStrategy:
    # doesn't get called unless using capital L List
    print("_shorter_lists called")
    sub_type = get_args(list_type)[0]
    return st.lists(st.from_type(sub_type), max_size=2)

# will make our test fail
st.register_type_strategy(list, _shorter_lists)

# will pass if uncommented, notice capital L
# st.register_type_strategy(List, _shorter_lists)


@given(infer)
def test_example(example: list[int]):
    assert len(example) <= 2

```

**Comment by Zac-HD** [comment]
```diff
--- a/hypothesis-python/src/hypothesis/strategies/_internal/types.py
+++ b/hypothesis-python/src/hypothesis/strategies/_internal/types.py
@@ -315,7 +315,8 @@ def is_generic_type(type_):
     # We check for `MyClass[T]` and `MyClass[int]` with the first condition,
     # while the second condition is for `MyClass`.
     return isinstance(type_, typing_root_type + (GenericAlias,)) or (
-        isinstance(type_, type) and typing.Generic in type_.__mro__
+        isinstance(type_, type)
+        and (typing.Generic in type_.__mro__ or hasattr(type_, "__class_getitem__"))
     )
```

This is enough to find the registered strategy for `list`... _as well as_ for `typing.List`.  

We'll need to do something to ensure that these are treated as a single lookup key, since resolving to different strategies for each will raise `ResolutionFailed`, but then I think it'll probably work?  My main concern is that we'll be left with a more complicated user experience on Python < 3.9, when builtins aren't yet parametrizable.

**Comment by FMorgan-111** [comment]
RepoPilot v2 could not complete an automatic fix.

Reason: Same patch produced the same failure twice.

Relevant files:
- hypothesis/src/hypothesis/strategies/_internal/core.py: path components match issue terms; bm25 rerank score=51.178; matched issue terms: register, type, strategy, doesn, t, work
- hypothesis/src/hypothesis/strategies/_internal/types.py: path components match issue terms; bm25 rerank score=44.905; matched issue terms: register, type, strategy, t, work, builtin
- hypothesis/tests/common/utils.py: path components match issue terms, test file; bm25 rerank score=28.887; matched issue terms: register, type, strategy, t, work, list
- hypothesis/tests/nocover/test_type_lookup.py: path components match issue terms, test file; bm25 rerank score=11.887; matched issue terms: register, type, strategy, t, 3, typing
- hypothesis/src/hypothesis/strategies/__init__.py: path components match issue terms; bm25 rerank score=4.999; matched issue terms: register, type, strategy, hypothesis, import, strategies
- hypothesis/src/hypothesis/entry_points.py: path components match issue terms; bm25 rerank score=3.105; matched issue terms: register, type, strategy, hypothesis, import, get

Attempts:
Attempt 1: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Attempt 2: success=False
File: unknown
Result: patch_apply_failed
Error:
Patch preflight check failed:
error: No valid patches in input (allow with "--allow-empty")


Token usage: 19927/80000
