### ISSUE TITLE
6.75.3: test_explanations fails

### ISSUE THREAD

**Issue by mtelka** [HypothesisWorks/hypothesis#3642]
I'm trying to run nocover tests for hypothesis 6.75.3 using Python 3.9.16 and I found that six tests fails (all other nocover tests pass):
```
=========================== short test summary info ============================
FAILED tests/nocover/test_baseexception.py::test_explanations[True-SystemExit]
FAILED tests/nocover/test_baseexception.py::test_explanations[True-GeneratorExit]
FAILED tests/nocover/test_baseexception.py::test_explanations[False-SystemExit]
FAILED tests/nocover/test_baseexception.py::test_explanations[False-GeneratorExit]
FAILED tests/nocover/test_scrutineer.py::test_explanations[trivial] - assert ...
FAILED tests/nocover/test_scrutineer.py::test_explanations[multiple-bugs] - a...
```
Full test log:
[hypothesis.log](https://github.com/HypothesisWorks/hypothesis/files/11488877/hypothesis.log)

Steps to reproduce:
```
$ mkdir /tmp/hypo/
$ cd /tmp/hypo
$ wget https://github.com/HypothesisWorks/hypothesis/archive/refs/tags/hypothesis-python-6.75.3.tar.gz
$ tar xf hypothesis-python-6.75.3.tar.gz
$ cd hypothesis-hypothesis-python-6.75.3/hypothesis-python/
$ PYTHONPATH=$(pwd)/src pytest tests/nocover --verbose -k test_explanations
```
I see similar issue reported in #3055 but without any suggestion how to solve the problem.

**Comment by Zac-HD** [comment]
Looks like a clash with `pytest-benchmark`, which 🤷‍♂️ I guess just breaks the Hypothesis test suite at the moment.  Since we don't use that package, closing this as not-our-problem / wontfix.

I'd accept a low-impact PR that made things work, but honestly I think that should probably go upstream to `pytest-benchmark` instead because our `conftest.py` truly doesn't have a time attribute, and I don't see why you'd assume otherwise.

**Comment by mtelka** [comment]
I just confirmed that the following patch solved the problem:
```
--- hypothesis-hypothesis-python-6.82.3/hypothesis-python/tests/conftest.py.orig
+++ hypothesis-hypothesis-python-6.82.3/hypothesis-python/tests/conftest.py
@@ -81,6 +81,10 @@
     def freeze():
         frozen[0] = True
 
+    # https://github.com/ionelmc/pytest-benchmark/issues/241
+    time.__module__ = 'time'
+    time.__name__ = 'perf_counter'
+
     monkeypatch.setattr(time_module, "time", time)
     monkeypatch.setattr(time_module, "monotonic", time)
     monkeypatch.setattr(time_module, "perf_counter", time)
```

**Comment by jobh** [comment]
@mtelka 
> I just confirmed that the following patch solved the problem:

A cleaner solution and more complete solution is to use `functools.wraps` to mimic the real functions (untested):
```
from functools import wraps

     [...]
     monkeypatch.setattr(time_module, "time", wraps(time_module.time)(time))
     monkeypatch.setattr(time_module, "monotonic", wraps(time_module.monotonic)(time))
     [... etc for the other monkeypatches]
```
and so on for the other monkeypatches.

**Comment by Zac-HD** [comment]
Our internal `@proxies` decorator would work here I think!

**Comment by jobh** [comment]
> Our internal `@proxies` decorator would work here I think!

It looks like it's a bit too picky,
```
> proxies(time.time)(...)
ValueError: no signature found for builtin <built-in function time>
```
...and even if we skip `replace_sig` it still fails
```
AttributeError: 'builtin_function_or_method' object has no attribute '__code__'
```

So, probably just `@wraps` instead of modifying `@proxies`, since there's no value to add for builtin functions, right?
