### ISSUE TITLE
`test_min_magnitude_respected` is flaky

### ISSUE THREAD

**Issue by honno** [HypothesisWorks/hypothesis#3647]
Assumedly in #3574 I introduced some flakiness to this test case, where on CI it sometimes fails the too slow health check. I've only seen this error on `check-coverage` jobs ([#3574](https://github.com/HypothesisWorks/hypothesis/actions/runs/4925028773/jobs/8798778594), [#3645](https://github.com/HypothesisWorks/hypothesis/actions/runs/5053311410/jobs/9067036704?pr=3645)), e.g.: `hypothesis.errors.FailedHealthCheck: Data generation is extremely slow: Only produced 9 valid examples in 1.03 seconds (0 invalid ones and 19 exceeded maximum size).`

I'm not quite sure what the fix here is. The internal usage of `hypothesis.internals.floats.float_of()` in `st.complex_numbers().constrained_complex()` seems to have minimal overhead—checking out to the repo before the #3574 changes

```python
>>> strat = st.integers(-5, 5).map(lambda x: 10**x).flatmap(lambda mag: st.complex_numbers(min_magnitude=mag)))
>>> @given(strat)
... def foo(_):
...     pass
>>> %timeit foo()  # x3 times
361ms
360ms
359ms
```

doesn't look much different to at `HEAD` when we get similar times

```python
>>> %timeit foo()  # x3 times
363ms
360ms
361ms
```

The `strat` is what's used in `test_min_magnitude_respected`

https://github.com/HypothesisWorks/hypothesis/blob/661af850bbfcb091a820eb16c84f56048c8e21c8/hypothesis-python/tests/cover/test_complex_numbers.py#L65C1-L73

Maybe the strategy producing `mag` has a rare example which causes a significant slow down to `float_of()`?

**Comment by Zac-HD** [comment]
Maybe?  But mostly I attribute this to "there are many reasons for free CI machines to randomly be slower than usual", since they're running on very cheap / low-priority VMs somewhere.

Let's just suppress the `too_slow` healthcheck for these flaky tests and move on.
