### ISSUE TITLE
`test_mutually_broadcastable_shapes_only_singleton_is_valid ` is flaky

### ISSUE THREAD

**Issue by honno** [HypothesisWorks/hypothesis#3648]
Spotted on a [`checkpy37-oldestnumpy` job](https://github.com/HypothesisWorks/hypothesis/actions/runs/5054191808/jobs/9068860182?pr=3646) we get `Data generation is extremely slow: Only produced 9 valid examples in 1.03 seconds (0 invalid ones and 5 exceeded maximum size).`

The test itself doesn't even use any NumPy functions (AFAIK!!), given its concerned with the shape-related strategies that are NumPy-agnostic.

https://github.com/HypothesisWorks/hypothesis/blob/661af850bbfcb091a820eb16c84f56048c8e21c8/hypothesis-python/tests/numpy/test_gen_data.py#LL872C1-L902C62

... but if its not related to the NumPy version, then it'd be mad coincidence to of been seen failing on the oldestnumpy job.

(Documenting for prosperity's sake as assumedly we'll close the PR it was found in.)

**Comment by Zac-HD** [comment]
Moderately confident that this is a coincidence - recall that py37 is also the slowest Python version we use, and the oldnumpy job is one of only two py37 CI jobs we run - so let's just suppress as per https://github.com/HypothesisWorks/hypothesis/issues/3647#issuecomment-1564219900.
