### ISSUE TITLE
`test_can_generate_unique_columns` is flaky

### ISSUE THREAD

**Issue by honno** [HypothesisWorks/hypothesis#3649]
In a [`py11-check-niche` job](https://github.com/HypothesisWorks/hypothesis/actions/runs/5053311410/jobs/9067036370?pr=3645) we have `tests/pandas/test_data_frame.py::test_can_generate_unique_columns` failing with `Data generation is extremely slow: Only produced 9 valid examples in 1.01 seconds (92 invalid ones and 0 exceeded maximum size).`

For reference

https://github.com/HypothesisWorks/hypothesis/blob/661af850bbfcb091a820eb16c84f56048c8e21c8/hypothesis-python/tests/pandas/test_data_frame.py#L245-L253

The `filter_too_much` suppression makes sense with the hard-to-satisfy `pdst.column(elements=st.integers(0, 9), fill=None, unique=True)`, but I wonder if sometimes its just going to generate such a number of rejected example that the test warrants a `too_slow` suppression too.

**Comment by Zac-HD** [comment]
Yeah, let's just suppress.  See also https://github.com/HypothesisWorks/hypothesis/issues/3647#issuecomment-1564219900.
