### ISSUE TITLE
Warn (or fail) when inferred strategy is the trivial default object

### ISSUE THREAD

**Issue by jobh** [HypothesisWorks/hypothesis#3653]
Given the following two tests:

```python
from hypothesis import given
import numpy as np

@given(x=...)
def test_int(x: int):
    assert x==0

@given(x=...)
def test_int8(x: np.int8):
    assert x==0
```

The first one fails (as it should!), but the second succeeds. In this contrived example, it is harmless; but for the unsuspecting user, it may cause belief that a method is properly tested when in reality the input is always zero.

The inferred strategy for `int` is `st.integers()`. For `np.int8`, it is `st.builds(np.int8)`. I'm not asking for full support for `np.int8` and other arbitrary data types, but would it be possible to warn (or even fail) if the inferred strategy is to just return default-valued objects? That way, the user would be informed and could specify it properly when necessary.

**Comment by Zac-HD** [comment]
I think emitting a warning when `st.from_type(thing)` resolves to a non-registered zero-argument `st.builds(thing)` would be reasonable, even though that won't catch all cases where we only generate a single value (and in fact doesn't guarantee that it always generates a single value!).  Implementation of that will go here, warning if `kwargs` is empty:

https://github.com/HypothesisWorks/hypothesis/blob/661af850bbfcb091a820eb16c84f56048c8e21c8/hypothesis-python/src/hypothesis/strategies/_internal/core.py#L1222

We can _also_ add proper handling for these numpy classes without too much trouble, via the `from_dtype()` functionality.  IMO it makes sense to do both; the latter just after we handle `enum`s here:

https://github.com/HypothesisWorks/hypothesis/blob/661af850bbfcb091a820eb16c84f56048c8e21c8/hypothesis-python/src/hypothesis/strategies/_internal/core.py#L1185-L1188

**Comment by jobh** [comment]
Thanks @Zac-HD , that sounds very reasonable. I would say it is the simple cases that are most dangerous since there is less expectation that it would "just work" for more complex examples.

Btw: It looks like this line may also be affected?

https://github.com/HypothesisWorks/hypothesis/blob/661af850bbfcb091a820eb16c84f56048c8e21c8/hypothesis-python/src/hypothesis/strategies/_internal/core.py#L1212

**Comment by jobh** [comment]
I can create a PR if you want, if you also point me to a line showing how to emit a warning I think I have enough information

**Comment by Zac-HD** [comment]
Yep, well spotted; we'd want a warning there too.

```python
warnings.warn(
    "Some long message here",
    HypothesisWarning,
)
```

should be all it takes; along with updating tests to expect the new warnings (instead of crashing on them).  We may also want to define a new `class SmallSearchSpaceWarning(HypothesisWarning):` (name suggestions welcome) in `hypothesis.errors`, so that people can set up custom filters to apply only to it.  

As for the warning message, I'd go with something like

> from_type(thing) resolved to builds(thing), because {we couldn't get the signature / it has no (non-varargs) arguments}.  Use `st.register_type_strategy()` to resolve to a strategy which can generate more than one value, or silence this warning.

using `hypothesis.internal.reflection.repr_call()` to show the from_type() and builds() reprs.
