### ISSUE TITLE
RecursionError in from_type for recursive types with default arguments

### ISSUE THREAD

**Issue by jobh** [HypothesisWorks/hypothesis#3655]
While addressing https://github.com/HypothesisWorks/hypothesis/issues/3653, I wanted to remove the limitation that we only infer parameter strategies if they have a default value:

https://github.com/HypothesisWorks/hypothesis/blob/661af850bbfcb091a820eb16c84f56048c8e21c8/hypothesis-python/src/hypothesis/strategies/_internal/core.py#L1218

However, that makes `test_lookup:test_resolving_recursive_type` and others fail with RecursionError (due to infinite recursion).

This indicates that recursive types with default arguments do not work, and indeed this is the case:
```
from hypothesis import strategies as st
import typing

class C_ok:
    def __init__(self, nxt: typing.Optional["C_ok"]):
        pass

class C_fails:
    def __init__(self, nxt: typing.Optional["C_fails"]=None):
        pass

print(st.from_type(C_ok).example())
print(st.from_type(C_fails).example())
```
```
<__main__.C_ok object at 0x7f55ff6a7d90>
Traceback (most recent call last):
  File "[...]", line 13, in <module>
    print(st.from_type(C_fails).example())
[...thousands of lines snipped...]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by Zac-HD** [comment]
This is (a) a nice idea, and (b) indeed pretty tricky to get right!  

I think we can probably use a `contextvars`-global cache rather than passing a stack around, and indeed have to for mutually-recursive strategies to work, but there are a _lot_ of weird edge cases to handle...
