### ISSUE TITLE
`type[strategies.SearchStrategy[str]]` causes Mypy error in composite strategies

### ISSUE THREAD

**Issue by SRv6d** [HypothesisWorks/hypothesis#3661]
Given the following strategy:

```python
@strategies.composite
def comment_line(draw: strategies.DrawFn) -> strategies.SearchStrategy[str]:
    comment_indicators = ("#", "%")

    indicator = draw(strategies.sampled_from(comment_indicators))
    # The value may consist of any ASCII character except for \n.
    value = draw(
        strategies.text(
            alphabet=strategies.characters(
                min_codepoint=0, max_codepoint=127, blacklist_characters=["\n"]
            ),
            min_size=1,
        )
    )

    return indicator + value
```

Mypy will complain that the return type of `str` does not match the annotated type `SearchStrategy[str]`.
```
error: Incompatible return value type (got "str", expected "SearchStrategy[str]")  [return-value]
```

**Comment by rsokl** [comment]
The proper way to type `comment_line` is:

```python
@strategies.composite
def comment_line(draw: strategies.DrawFn) -> str:
```

`@composite` is typed in such a way that it will produce a function that returns `SearchStrategy[str]`

**Comment by SRv6d** [comment]
Appreciate it. I inferred from [the docs](https://hypothesis.readthedocs.io/en/latest/details.html#writing-downstream-type-hints) that custom strategies had to be typed with a return type of `SearchStrategy`.

> @composite is typed in such a way that it will produce a function that returns SearchStrategy[str]

Although this is technically stated here
> The composite decorator works by converting a function that returns one example into a function that returns a strategy that produces such examples - which you can pass to [@given](https://hypothesis.readthedocs.io/en/latest/details.html#hypothesis.given), modify with .map or .filter, and generally use like any other strategy.

I did not really grasp it on first or second read.
