### ISSUE TITLE
tests/cover/test_lookup.py::test_resolving_mutually_recursive_types{,_with_defaults} fail randomly when running the test suite w/ xdist

### ISSUE THREAD

**Issue by mgorny** [HypothesisWorks/hypothesis#3671]
Well, you're not going to like this but I'm getting quasi-random test failures from the following two tests when running the large subset of the test suite in parallel:

```
FAILED tests/cover/test_lookup.py::test_resolving_mutually_recursive_types - RecursionError: maximum recursion depth exceeded
FAILED tests/cover/test_lookup.py::test_resolving_mutually_recursive_types_with_defaults - RecursionError: maximum recursion depth exceeded
```

This seems to be very flaky. It has been happening to us with PyPy3 before but I've assumed it's PyPy-specific. With 6.76.0, it suddenly started happening with CPython 3.11 as well. Curiously enough, I can reproduce it reliably when running a very specific set of tests:

```
python -m pytest -n 12 tests/cover tests/pytest tests/quality
```

but if I change tested files even a little, it stops happening.

Full log with tracebacks: [dev-python:hypothesis-6.76.0:20230606-074652.log](https://github.com/HypothesisWorks/hypothesis/files/11662376/dev-python.hypothesis-6.76.0.20230606-074652.log)

I realize this is going to be very hard to reproduce, and I'll be glad to try anything you may suggest while I still can.

**Comment by jobh** [comment]
I'm not able to reproduce — but that is hardly surprising, from your description.

I would be curious if it may be related to borderline recursion limits, if perhaps the tests are executed at different stack depths depending on the specific pytest-xdist workload. One way to rule this out would be to add f.x.

```
sys.setrecursionlimit(5000)
```
 near the top of `tests/cover/test_lookup.py`.

**Comment by mgorny** [comment]
@jobh, indeed that seems to help. Could you add it or should I make a pull request?

**Comment by mgorny** [comment]
(that said, I'm not 100% sure if it just doesn't change some other random factor but I'm happy enough that the issue disappears for now)

**Comment by jobh** [comment]
@mgorny I'm not sure if this is the right fix, but it certainly helps with narrowing down the problem.

On my local runs, a limit of 300 is sufficient (already a lot), and the default is 1000. I wonder what makes it grow so much.

**Comment by Zac-HD** [comment]
Hmm, we do try to handle recursion-depth problems internally, but maybe need to repeat this trick somewhere else to handle strategy resolution?

https://github.com/HypothesisWorks/hypothesis/blob/fc566bf820a4b418a6cf54a15defbe9b44aaca5d/hypothesis-python/src/hypothesis/internal/conjecture/engine.py#L183-L197

**Comment by jobh** [comment]
@Zac-HD That was my concern, that the new recursion guard in strategy resolution didn't do its job. But it seems that it's "just" the new test having deeper effective nesting than any of the old. I.e., it could happen without recursion, at (guess/estimate) 30 deep strategies.

The error happens in strategy validation, starting here:
https://github.com/HypothesisWorks/hypothesis/blob/fc566bf820a4b418a6cf54a15defbe9b44aaca5d/hypothesis-python/src/hypothesis/core.py#L619

...but I don't know if bumping the limit here will just move the problem to elsewhere (draw time)?

To answer your previous question @mgorny , I don't have time to follow up further now I'm afraid.

**Comment by jobh** [comment]
... except possibly to add a skip to the two failing tests as a short term measure

**Comment by mgorny** [comment]
> ... except possibly to add a skip to the two failing tests as a short term measure

We're already skipping them on our end via `--deselect`, so there's no need to do that.

**Comment by mgorny** [comment]
Thanks! I have reenabled the tests in Gentoo for 6.80.0 and I have seen no problems so far.

**Comment by Zac-HD** [comment]
Thanks for confirming!  Here's hoping that everything _keeps_ working 😁
