### ISSUE TITLE
Custom shrink priority/weight/objective function.

### ISSUE THREAD

**Issue by RuRo** [HypothesisWorks/hypothesis#3677]
If my understanding is correct, hypothesis generally tries to produce the "simplest" failing example. Unfortunately, the default definition of "simplest" used by hypothesis doesn't always lead to actually good examples.

For example, consider the following fake algorithm:
```python
import random


def flaky_algorithm(param, num_steps):
    state = random.Random(param)  # deterministic, but non-trivial behaviour

    total = 0
    for _ in range(num_steps):
        total += 1

        # Simulate a rare edge case that only occurs about 5% of the time
        if state.random() < 0.05:
            total += 1  # oops, this is a mistake

    return total
```

Pretend, that this is some complicated iterative algorithm. It has an arbitrary parameter `param` and a variable number of iterations `num_steps` that we would like to execute. The algorithm has a subtle implementation error that causes it to fail in some rare condition that occurs about 5% of the time (here I simulate the rare failure condition with a PRNG).

We can then test this algorithm something like this:

```python
@given(
    param=st.integers(),
    num_steps=st.integers(1, 1_000),
)
@settings(max_examples=1_000_000, derandomize=True)
@seed(42)
def run(param, num_steps):
    assert flaky_algorithm(param, num_steps) == num_steps
```

Here, hypothesis finds a "minimal" falsifying example of `param=0, num_steps=36`. Unfortunately, such an example is actually quite hard to reason about, because the erroneous edge case actually only occurs on the 35th iteration. Compare this with the falsifying example of `param=31, num_steps=1` which only requires "simulating" a single step (though at the cost of using a slightly more "complicated" parameter value).

Of course, hypothesis doesn't know anything about the meanings of these 2 numbers, and so it has no way of knowing that `(31, 1)` is a simpler example than `(0, 36)`.

Is there some way to give hypothesis a hint about which parameters should be simplified first? Maybe a parameter priority or relative weighting of some kind, or a custom objective function that must be maximized when simplifying an example? If not, then this issue is a feature request for it.

P.S. I tried using `hypothesis.target`, but the target only seems to affect the search phase, not shrinking/example selection.

**Comment by Zac-HD** [comment]
We don't support any kind of custom shrinking priority or functionality, since this emerges from shortlex optimization on the underlying sequence of choices used to generate the input (fewer choices is better, then smaller of equal length).

However, in this case if you want `num_steps` to be prioritized over `param`, you can pass them to the test in this order!

Since we shrink to local optima, a random seed is basically an adversarial setting and it's not clear how much it would help in this exact case - but that's how I'd do it.

**Comment by jobh** [comment]
@RuRo - additionally to what Zac says, it may in some cases help to use `one_of` as a hint, passing simpler strategies before the full one, e.g.
```
num_steps=st.one_of(st.integers(1, 10), st.integers(1, 1_000))
```

**Comment by RuRo** [comment]
Both switching the order of arguments around and using `one_of` didn't seem to work reliably for me (not any better than just trying different seeds).

Is there some way to interact with hypothesis on a more programmatic level? For example, I noticed that hypothesis doesn't print all the failing cases it finds even when `report_multiple_bugs=True`. Can I somehow obtain a list of all the failing argument sets?

Additionally, is there some way to force hypothesis to continue searching for more examples? I have specified `max_examples=1_000_000`, but hypothesis only tries around 50 different argument sets before choosing one (not very good) example and calling it a day. I see in the documentation that "we might call your test function fewer times if we find a bug early" but there is no mention on how to avoid this.

I saw the documentation about the `execute_example` hook. But I don't see any way to actually do anything useful with it. It seems that its main purpose is setting up the appropriate execution context.

**Comment by Zac-HD** [comment]
> Both switching the order of arguments around and using `one_of` didn't seem to work reliably for me (not any better than just trying different seeds).

Unfortunately this is the nature of shrinking a random seed; as I mention above it's basically the worst possible case for the shrinker.

> Is there some way to interact with hypothesis on a more programmatic level? For example, I noticed that hypothesis doesn't print all the failing cases it finds even when `report_multiple_bugs=True`. Can I somehow obtain a list of all the failing argument sets?

- You can wrap your test function in a custom decorator ("under" `@given()`), and observe the test cases and exception-if-any that way.
- `report_multiple_bugs=True` tells Hypothesis to report multiple _distinct_ errors, e.g. if your test raised a `ValueError` for some inputs and a `TypeError` for others.
- You can use [the `verbosity=Verbosity.verbose` setting](https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.verbosity), or `--hypothesis-verbosity=verbose` CLI argument, which will print each test case as we try them.

> I see in the documentation that "we might call your test function fewer times if we find a bug early" but there is no mention on how to avoid this.

We do not provide any way to continue testing after finding a minimal failing example.  While tempting, we think it's a mistake: better to fix either the test or the code, and then re-run the test.

> I saw the documentation about the `execute_example` hook. But I don't see any way to actually do anything useful with it. It seems that its main purpose is setting up the appropriate execution context.

Setting up the appropriate execution context _is_ a useful thing to do with this hook

**Comment by jobh** [comment]
Given that the RNG (and perhaps also the real code that it mimics) is not amenable to shrinking, I think you may have to enumerate and test the cases you know to be simpler to reason about explicitly and separately, something like

```
@pytest.mark.parametrize("num_steps", range(1, 5))
@given(param=st.integers())
[...]

@given(param=st.integers(), num_steps=integers(5, 1_000))
[...]
```

**Comment by RuRo** [comment]
@jobh I think that explicitly `parametrize`ing over some subset that should be prioritized is the best solution presented so far. Thanks!

I still think that a proper programmatic interface for interacting with hypothesis would be extremely useful for these kinds of situations. But at this point, I've mostly solved my current issue, and it seems that there is little interest in supporting such functionality.
