### ISSUE TITLE
`st.from_regex()` should handle new regex features from Python 3.11

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#3684]
> [Atomic grouping (`(?>...)`) and possessive quantifiers (`*+`, `++`, `?+`, `{m,n}+`) are now supported in regular expressions.](https://docs.python.org/3/whatsnew/3.11.html#re)

Unfortunately `st.from_regex()` will crash on patterns containing the quantifiers, and possibly also atomic grouping.  We should add handling for these new cases, and tests to check that they work.

Our tests [did _eventually_ notice](https://github.com/HypothesisWorks/hypothesis/actions/runs/5393648273/jobs/9793687131?pr=3680#step:6:515) we weren't handling some valid patterns, but it took almost a year of running on Python 3.11, which is _way_ longer than we'd like.  Improving e.g. `tests/nocover/test_regex.py::test_fuzz_stuff` so that any similar future issues can be fixed earlier would also be good.

**Comment by Cheukting** [comment]
I want to work on this @Zac-HD

**Comment by Zac-HD** [comment]
Fixed by #3699
