### ISSUE TITLE
Hypofuzz entrypoint causes test_lazy_import to fail

### ISSUE THREAD

**Issue by jobh** [HypothesisWorks/hypothesis#3686]
If hypofuzz is installed, test_lazy_import fails due to `pytest` being in `sys.modules`.

**Comment by jobh** [comment]
These kind of issues are obviously not caught in CI, since the set of potential entrypoints is unknowable. I don't know it there's anything to fix here, maybe a comment somewhere in the test about the potential for false positives?

**Comment by Zac-HD** [comment]
Hmm, maybe we should have an environment variable or something which disables plugins?  Useful for testing ourselves, and also for end-user debugging I guess 🤔
