### ISSUE TITLE
Getting Flaky inconsistent error while using RuleBasedStateMachine

### ISSUE THREAD

**Issue by chahalprabh92** [HypothesisWorks/hypothesis#3690]
My test is to create a policy using (API), but API does not allow duplicate rule name. 
so hypothesis when retries API is bound to give Duplicate name not allowed.

If add logic in my code to delete the policy first if same rule name is generated then I hit `Flaky: Inconsistent data generation!`

I have also tried `assume(False)` nothing is working. 

Reproducible code

```python
import string
from hypothesis import assume
import pytest
import unittest
from hypothesis import strategies as st, reject
from hypothesis.stateful import RuleBasedStateMachine, precondition, rule


used_names = set()


@st.composite
def unique_name_strategy(draw):
    name_strategy = st.text(min_size=5, max_size=31, alphabet=string.ascii_letters + string.digits)
    while True:
        name = draw(name_strategy)
        if name not in used_names:
            used_names.add(name)
            return name


class TestsEdlp(RuleBasedStateMachine):
    def __init__(self) -> None:
        super().__init__()

    rule_names = []
    tries = 0


    def rule_creation(self, rule_name):
        print("in rule creation")

        if rule_name in self.rule_names:
            self.rule_names.remove(rule_name)

        if len(rule_name)> 0 :
            self.rule_names.append(rule_name)
            self.tries += 1
            return True
        else:
            return False


    @precondition(lambda self: self.tries < 10)
    @rule(rule_name=unique_name_strategy() )
    def create_dlp_rule(self, rule_name):
        print(f"in function create rule {rule_name} tries: {self.tries}")
        is_success = self.rule_creation(rule_name=rule_name)
        assert is_success

TestsEdlp: unittest.TestCase = TestsEdlp.TestCase
```

gives

```
FAILED duplicate_name.py::TestsEdlp::runTest - hypothesis.errors.Flaky: Inconsistent data generation! Data generation behaved differently betwee...
```

Can anyone please guide me on how to handle this?

**Comment by Zac-HD** [comment]
Without a https://stackoverflow.com/help/minimal-reproducible-example we can't help.

**Comment by chahalprabh92** [comment]
> Without a https://stackoverflow.com/help/minimal-reproducible-example we can't help.

hi @Zac-HD 
I have added Reproducible code, Please let me know if that helps
or do I need to add anything more?
Thanks
Prabhleen Singh

**Comment by Zac-HD** [comment]
Ah, I see: the problem is that your strategy for unique names doesn't allow Hypothesis to generate the same name in two different runs of your test function, which _must_ be allowed - otherwise, we can't try variations or discover a minimal failing example (among other problems).  This may also require some work to reset the state of your API for each input Hypothesis tries.

A better unique-names strategy would be:

```python
@st.composite
def unique_name_strategy(draw, name_strategy=st.text(string.ascii_letters + string.digits, min_size=5, max_size=31)):
    used_names = draw(st.shared(st.builds(set), key="used names"))
    name = draw(name_strategy.filter(lambda x: x not in used_names)
    used_names.add(name)
    return name
```
The `st.shared()` strategy will only generate one set for each input, so we get just the right amount of persistence.

**Comment by chahalprabh92** [comment]
Thank you so much!

**Comment by chahalprabh92** [comment]
@Zac-HD 
I tried with your mentioned approach but still getting duplicated names generated.

`
@st.composite
def unique_name_strategy(draw, name_strategy=st.text(string.ascii_letters + string.digits, min_size=5, max_size=31)):
    used_names = draw(st.shared(st.builds(set), key="used names"))
    name = draw(name_strategy.filter(lambda x: x not in used_names))
    used_names.add(name)
    print(f"used names {used_names}")
    return name


class TestsEdlp(RuleBasedStateMachine):
    def __init__(self) -> None:
        super().__init__()

    rule_names = []
    tries = 0

    def rule_creation(self, rule_name):
        print(f"in rule creation {rule_name}")

        if rule_name in self.rule_names:
            print("duplicate rule name")
            return False

        if rule_name:
            self.rule_names.append(rule_name)
            self.tries += 1
            return True
        else:
            return False

    #    @precondition(lambda self: self.tries < 10)
    @rule(rule_name=unique_name_strategy())
    def create_dlp_rule(self, rule_name):

        print(f"in function create rule {rule_name} tries: {self.tries}")
        is_success = self.rule_creation(rule_name=rule_name)
        assert is_success


TestsEdlp: unittest.TestCase = TestsEdlp.TestCase`

output 
`duplicate_name.py:45: AssertionError
---------------------------------------- Captured stdout call ----------------------------------------
used names {'00000'}
in function create rule 00000 tries: 0
in rule creation 00000
used names {'00000'}
in function create rule 00000 tries: 0
in rule creation 00000
duplicate rule name
used names {'00000'}
in function create rule 00000 tries: 0
in rule creation 00000
duplicate rule name
used names {'00000'}
in function create rule 00000 tries: 0
in rule creation 00000
duplicate rule name
used names {'00000'}
in function create rule 00000 tries: 0
in rule creation 00000
duplicate rule name`



Can you please help me getting name that is generated only once.

**Comment by Zac-HD** [comment]
Looks like you're not resetting the `rule_names` class variable between examples; that's what `@initialize()` rules are for.

See also https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by chahalprabh92** [comment]
if I init rule_names inside __init__
as self.rule_names
then I lose track of already created rule_names between examples
Hypothesis tries with the same rule_name again in my case it is for e.g rule_name 00000, As in my case, the DB will already have this rule_name so the second time the API fails as Hypothesis says Inconsistent Data generation. Is there any way to handle such a case or Add and then Delete is the only way?

**Comment by Zac-HD** [comment]
> then I lose track of already created rule_names between examples

Yes.  Hypothesis _requires_ that you reset whatever you're testing so that each example is entirely independent.  Said another way, executing the same example twice must have the same result; `Flaky` is the error you get when we notice that this expectation is violated.

Databases usually support some kind of transactions, and you might be able to find example test code.  Otherwise, yeah, you'll need to somehow clear the database before or after each example.

**Comment by chahalprabh92** [comment]
> Hypothesis _requires_ that you reset whatever you're testing so that each example is entirely independent. Said another way, executing the same example twice must have the same result; `Flaky` is the error you get when we notice that this expectation is violated.
> 
> Databases usually support some kind of transactions, and you might be able to find example test code. Otherwise, yeah, you'll need to somehow clear the database before or after each example.

Thanks Zac, I am able to solve the problem. By adding delete all rules in teardown function.
