### ISSUE TITLE
How can create a frozendict?

### ISSUE THREAD

**Issue by viditjain99** [HypothesisWorks/hypothesis#3692]
I have a complex object and one of the nested objects require a frozendict as an attribute. How can I create it using Hypothesis?

**Comment by Zac-HD** [comment]
Use https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.dictionaries or https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.fixed_dictionaries

**Comment by viditjain99** [comment]
I explicitly need to create a `frozendict` object via `builds()`. Both the above strategies return a `dict` object. Is there any other way?

**Comment by rsokl** [comment]
Use .map on the aforementioned strategies to convert the dict to a frozendict

**Comment by Zac-HD** [comment]
@rsokl actually both strategies can directly produce other mapping types; dictionaries() accepts the type as an argument and fixed_dictionaries() matches the type of the mapping you pass it.
