### ISSUE TITLE
Incorrect example count when using max_examples with database fixture

### ISSUE THREAD

**Issue by markizmandic** [HypothesisWorks/hypothesis#3697]
I am using Hypothesis for property-based testing with Pytest. In my tests, I have configured max_examples=50 to limit the number of examples generated.
To isolate each test run, I am using a Pytest fixture api_client which creates a fresh database session and test client per test invocation. At the end of the fixture, the session is closed and the database is dropped.
In the test function, I have a global counter example_count that increments on each test run. However, the final count does not match the configured max_examples amount.
I have validated that the tests work correctly without Hypothesis, so the issue seems isolated to using max_examples with the database fixture.
I would appreciate any guidance on what could cause the example count to be inconsistent when using Hypothesis test parameterization along with database fixtures. Potential factors I have considered are session/db handling and scoping, but I have not determined the root cause.
Let me know if you need any other details on the test setup and I can provide a minimal repro. Thanks for any insights you can provide!

**Comment by Zac-HD** [comment]
See https://hypothesis.readthedocs.io/en/latest/settings.html#hypothesis.settings.max_examples :

> Once this many satisfying examples have been considered without finding any counter-example, Hypothesis will stop looking.  Note that we might call your test function fewer times [...] or more if we discard some examples due to use of `.filter()`, `assume()`, or a few other things that can prevent the test case from completing successfully.

Unfortunately the name is a bit misleading, but it'd be hard for all our current users to change it now 😅
