### ISSUE TITLE
Tests fail for some projects: ValueError: option names {'--hypothesis-profile'} already added

### ISSUE THREAD

**Issue by yurivict** [HypothesisWorks/hypothesis#3703]
For example, in the [Pydantic](https://github.com/pydantic/pydantic/issues/4535) project.

hypothesis-6.80.0
Python-3.9
OS: FreeBSD 13.2

**Comment by kxepal** [comment]
Hi! Can retest for FreeBSD, but actually what the real shell command stands behind this error? This could help a lot. 
And side note: how to reproduce this issue? We also build hypothesis and pydantic from ports but never faced such kind of issue.

**Comment by yurivict** [comment]
```cd /usr/ports/devel/py-pydantic && make test``` fails.

**Comment by Zac-HD** [comment]
Hi @yurivict - unfortunately as volunteers we don't have the resources to support downstream-packaged versions of Hypothesis.  Can you provide a minimal reproducing example that works with libraries installed from PyPI?

**Comment by Zac-HD** [comment]
Closing this because there's nothing I can do without a reproducing example.
