### ISSUE TITLE
Capture args and kwargs along with test results

### ISSUE THREAD

**Issue by neelabalan** [HypothesisWorks/hypothesis#3705]
Here's a simple example with which I'm trying to work with. I'd like to log all parameters passed in `test_add_property` along with the corresponding test result in a CSV file to have a look at what parameters were tried as part of testing. I understand that I can set the `--hypothesis-verbosity` command line argument to view the results but there ain't an option to export the results to CSV format and also I couldn't find any related documentation to get the args/kwargs as the test runs. I'm trying to achieve somehing similar to `pytest-csv` but with the args and kwargs used to run the test.

```python
from hypothesis import given
from hypothesis import strategies as st


def add(a, b):
    return a + b


@given(
    st.floats(allow_nan=False, allow_infinity=False),
    st.floats(allow_nan=False, allow_infinity=False, min_value=1e-6),
)
def test_add_property(a, b):
    assert add(a, b) == a + b
```

**Comment by imranhashmi226** [comment]
I am too also trying to export the parameters which were part of testing, I am trying with _pytest-html_ so that I can attach in extras and can keep it for further analysis of test cases.

**Comment by imranhashmi226** [comment]
```python
from hypothesis import given
from hypothesis import strategies as st


@given(st.integers(1, 100), st.floats(0.5, 4))
def test_something_with_integers(value, valuefloat):
    assert valuefloat
    assert value

```

This doesn't dump the arguments as CSV but the output is captured in the report with below command line argument

`pytest -s --capture=sys --hypothesis-verbosity=verbose .\tests\test_sample.py --html=hypothesis_test_report.html`


![image](https://github.com/HypothesisWorks/hypothesis/assets/49776033/6024b8d9-ecde-451c-a0c6-e59fc8275e34)

**Comment by Zac-HD** [comment]
As Imran suggests, you can parse the output; or for programmatic reporting you can add something like:

```python
@given(...)
@log_arguments_to_called_function
def test_add_property(a, b):
    assert add(a, b) == a + b
```

For `pytest-html` you could insert this automatically via a pytest hook; in general there are too many possibilities for us to support all of them upstream when users or other libraries can implement their own helpers.  Just a note of caution: the number of reports, and the size of each report, might be _very_ large for some tests!
