### ISSUE TITLE
Generating random/unique values with strategies.randoms() on test rerun?

### ISSUE THREAD

**Issue by noddycode** [HypothesisWorks/hypothesis#3723]
Is there a way to allow hypothesis to shrink/rerun failing tests using the randoms strategy while still supplying unique values? For example:

```py
import random
import string
import time

from hypothesis import given, settings, Verbosity, strategies
from hypothesis.strategies import composite


@composite
def sample_strat(draw):

    # rand = random.Random(time.time())
    rand = draw(strategies.randoms(note_method_calls=True, use_true_random=True))

    rand_str = "".join(rand.sample(string.ascii_letters, rand.randint(5, 50)))
    print(rand, rand_str)

    return rand_str


@given(test_sample1=sample_strat())
@settings(max_examples=1000, verbosity=Verbosity.debug)
def test_sample_test(test_sample1):
    assert False
```

In this script, when hypothesis hits a failure, it seeds `rand` with 0 on each run, producing the same value for `test_sample1` on each run, which makes sense when trying to reproduce an error. However, I'm using `use_true_random=True` because the value generated by `sample_strat` _must_ be unique for every test run. Is there a way for an instance of the `randoms` strategy to shrink towards a similar value while still being unique? e.g. `WAcqGFztEwLnVisMgZjSJxXCBvkpr` -> `WWAcqGFztEwLnVisMgZjSJxXCBvkpr`.

I realize this kind of goes against the point of using the same values for testing to detect flakiness, and I understand if something like this is not doable with hypothesis. My backup will likely be to use a randoms instance with a randomly seeded `Random` instance as a prefix, but I wanted to check that this wasn't built into hypothesis first.

**Comment by Zac-HD** [comment]
> because the value generated by `sample_strat` must be unique for every test run.

This is explicitly unsupported: Hypothesis _must_ be able to replay the same test inputs have have your test execute the same behavior - this is crucial for both shrinking and flake-detection.

If you can't support that I guess true randomness is your workaround, but I'd be pretty worried about flakes...
