### ISSUE TITLE
killing test execution after deadline

### ISSUE THREAD

**Issue by crhf** [HypothesisWorks/hypothesis#3726]
Currently, hypothesis checks if deadline is exceeded only *after* the test has finished, as in core.py:

```
start = time.perf_counter()
result = self.test(*args, **kwargs)
finish = time.perf_counter()
internal_draw_time = sum(data.draw_times[initial_draws:])
runtime = datetime.timedelta(
    seconds=finish - start - internal_draw_time
)
if runtime >= current_deadline:
    raise DeadlineExceeded(runtime, self.settings.deadline)
```

As a result, test execution can vastly exceed the deadline. I can get:

> Test took 140160.81ms, which exceeds the deadline of 200.00ms

I really want to control the timeout of test execution, probably by terminating it after the deadline. Is that supported, or will it?

**Comment by Zac-HD** [comment]
The challenge here is that it means you have to run the test code _in another process_, which is hard to do in a performant and widely-compatible way (see e.g. https://github.com/HypothesisWorks/hypothesis/issues/165).

However, you can set this up for your own projects with [custom function execution](https://hypothesis.readthedocs.io/en/latest/details.html#custom-function-execution) logic 🙂
