### ISSUE TITLE
example.xfail() defaults don't match pytest's defaults, no option to set strict parameter

### ISSUE THREAD

**Issue by nickfraser** [HypothesisWorks/hypothesis#3737]
Caveat: I'm new to both `pytest` and `hypothesis`. As such, it's possible that this is the expected behaviour, but it is simply unintuitive to me. So far my searches in issues and documentation have not yielded any meaningful results, so I'm hoping to be illuminated if this is indeed the expected behaviour. Any pointers to the relevant sections in the documentation are much appreciated.

Consider the following test suite, `test_xfail.py`:

```python
import pytest
from hypothesis import given, strategies as st, example

@given(x=st.integers())
@example(x=0).xfail()
def test_zero_hy(x):
    assert x != 0

@given(x=st.integers())
@example(x=0).xfail()
def test_one_hy(x):
    assert True

@pytest.mark.xfail
@given(x=st.integers())
@example(x=0)
def test_zero_pt(x):
    assert x != 0

@pytest.mark.xfail
@given(x=st.integers())
@example(x=0)
def test_one_pt(x):
    assert True
```

with the following versions installed:
```
platform linux -- Python 3.9.18, pytest-7.4.2, pluggy-1.3.0
hypothesis profile 'default-with-verbose-verbosity' -> verbosity=Verbosity.verbose, database=DirectoryBasedExampleDatabase('/home/nfraser/workspace/hyp_xfail_test/.hypothesis/examples')
rootdir: /home/nfraser/workspace/hyp_xfail_test
plugins: hypothesis-6.84.3
```

Note, I also tried python versions `3.10.12` & `3.11.5` with the same results.

Running the following (with nothing else in the directory except the above file):

```bash
rm -rf .hypothesis/ .pytest_cache/ __pycache__/ && pytest | tail -n 4
```

Note, I removed all other folders to prevent what appears to be another issue from occurring (I'll save that for a separate issue).

```bash
=========================== short test summary info ============================
FAILED test_xfail.py::test_zero_hy - assert 0 != 0
FAILED test_xfail.py::test_one_hy - AssertionError: Expected an exception fro...
=================== 2 failed, 1 xfailed, 1 xpassed in 0.19s ====================
```

I would've expected the results to be `2 xfailed, 2 xpassed`. As far as I can tell, the unexpected pass from `test_one_hy` results in a fail (as if `strict=True`, [ref](https://docs.pytest.org/en/7.4.x/reference/reference.html#pytest.mark.xfail)), but I'm not sure why the expected fail, fails. Finally, it would be nice to support the `strict` argument for example.xfail for `test_one_hy`.

Note, for brevity I've not provided a full log, but I can if that would be useful.

**Comment by nickfraser** [comment]
Some extra information:

If I add the ` --hypothesis-verbosity=verbose` to my command above, explicitly:

```bash
rm -rf .hypothesis/ .pytest_cache/ __pycache__/ && pytest --hypothesis-verbosity=verbose
```

I see the following output related to `test_zero_hy`:

```
-----------------------Hypothesis--------------------------------
Trying explicit example: test_zero_hy(
    x=0,
)
Trying example: test_zero_hy(
    x=0,
)
x = 0

    @given(x=st.integers())
    @example(x=0).xfail()
    def test_zero_hy(x):
>       assert x != 0
E       assert 0 != 0

test_xfail.py:8: AssertionError

Trying example: test_zero_hy(
    x=55,
)
Trying example: test_zero_hy(
    x=5548580897629562706,
)
Trying example: test_zero_hy(
    x=16532,
)
Trying example: test_zero_hy(
    x=20680,
)
Trying example: test_zero_hy(
    x=30,
)
Trying example: test_zero_hy(
    x=-31766,
)
Trying example: test_zero_hy(
    x=0,
)
x = 0

    @given(x=st.integers())
    @example(x=0).xfail()
    def test_zero_hy(x):
>       assert x != 0
E       assert 0 != 0

test_xfail.py:8: AssertionError

Trying example: test_zero_hy(
    x=70,
)
Trying example: test_zero_hy(
    x=786818658,
)
Trying example: test_zero_hy(
    x=0,
)
x = 0

    @given(x=st.integers())
    @example(x=0).xfail()
    def test_zero_hy(x):
>       assert x != 0
E       assert 0 != 0

test_xfail.py:8: AssertionError
```

Is it possible that the `x=0` example is being generated from my strategy for `x` _as well_ as being set explicitly by the example decorator? Or to put another way, in order to get the expected behaviour, do I need to ensure that my strategies within given *never* produce the expected failing example?

**Comment by nickfraser** [comment]
More follow-up, modifying `test_zero_hy` as follows:

```python
@given(x=st.integers(min_value=1))
@example(x=0).xfail()
def test_zero_hy(x):
    assert x != 0
```

Results in this test being reported as passed. Explicitly, making the modification above to the original test results in the following output:

```bash

**Comment by Zac-HD** [comment]
Thanks for your report!  We clearly have some room to improve the documentation and UX here.  

Concretely, we could explicitly document that we always use the equivalent of Pytest's `strict=True` (and `run=True`); and make the mention of pytest.mark.parametrize a cross-ref to the pytest docs.  

We should also show a code sample which demonstrates that the test will fail if the strategies happen to generate the same inputs as an xfailed explicit example.  We can also check when we report a minimal failing (generated) example whether it has the same repr as any of the xfailed examples, and add a clarifying note if this is the case.

**Comment by nickfraser** [comment]
Thanks for the quick response @Zac-HD! Thanks also for helping me understand the behaviour I'm seeing.

> We should also show a code sample which demonstrates that the test will fail if the strategies happen to generate the same inputs as an xfailed explicit example. We can also check when we report a minimal failing (generated) example whether it has the same repr as any of the xfailed examples, and add a clarifying note if this is the case.

That would be excellent, thank you!

> Concretely, we could explicitly document that we always use the equivalent of Pytest's `strict=True` (and `run=True`)

Actually, this doesn't appear to be the case. Consider again my original example, but with `strict=True` and `run=True` and the first test modified to avoid checking the explicit example, [here](https://gist.github.com/nickfraser/4903acfbc91548de744cba785646f041).

Running:

```bash
rm -rf .hypothesis/ .pytest_cache/ __pycache__/ && pytest | tail -n 5
```

results in:

```
=========================== short test summary info ============================
FAILED test_xfail.py::test_one_hy - AssertionError: Expected an exception fro...
FAILED test_xfail.py::test_one_pt
==================== 2 failed, 1 passed, 1 xfailed in 0.21s ====================
```

Again, I would've expected `2 failed` & `2 xfailed` if the same behaviour as `pytest` was expected. Is this the expected behaviour?

PS: same package versions as before.

**Comment by Zac-HD** [comment]
> I would've expected `2 failed` & `2 xfailed` if the same behaviour as `pytest` was expected. Is this the expected behaviour?

Yep, it's expected - let me annotate the comparison:

```python
@given(x=st.integers().filter(bool))  # many passing inputs
@example(x=0).xfail()                 # one xfailed input
def test_zero_hy(x):
    assert x != 0

@pytest.mark.xfail(strict=True)
@given(x=st.integers().filter(bool))  # these don't get executed
@example(x=0)                         # because this fails the test
def test_zero_pt(x):
    assert x != 0
```

The key fact is that what Hypothesis sees as many test cases, Pytest sees as only _one test_.  If we gave `@example(...).xfail()` the `XFAIL` status, I think that would mislead people about what happened to all the (passing) generated examples.  Conversely, when we have an unmarked explicit example fail (`test_zero_pt`), we're not actually checking that any of the generated examples pass!

I really appreciate the detailed back-and-forth here, it's really helping to iron out what we need the docs to convey.

**Comment by nickfraser** [comment]
Thanks for the detailed response, this helps me understand the behaviour and the reasoning behind it.

> If we gave `@example(...).xfail()` the `XFAIL` status, I think that would mislead people about what happened to all the (passing) generated examples.

Makes sense. If you're taking votes on future functionality, I'd love the ability to control how the status of each test case (from hypothesis's perspective) are reduced into a single status (from pytest's perspective), perhaps with the `@settings` decorator or similar.

> I really appreciate the detailed back-and-forth here, it's really helping to iron out what we need the docs to convey.

Likewise - this has been one of my most pleasant exchanges in a Github issues section. Thank you for taking the time to explain this to all to me.

**Comment by Zac-HD** [comment]
> I'd love the ability to control how the status of each test case (from hypothesis's perspective) are reduced into a single status (from pytest's perspective)

Say more?  This is probably out of scope just because we prefer as little configuration as possible, but there might be a compelling case I'm missing.  I think that `@example(...).xfail()` is the only thing where there's any ambiguity here, since "some but not all examples (unexpectedly) fail" basically _has_ to be a failure to Pytest too.

**Comment by Zac-HD** [comment]
That all makes perfect sense to me!    However, I'm inclined to keep the current behavior rather than accepting your proposal:

- the status quo of "write two tests then" can be a bit tedious, but it's hard to make mistakes and easy to interpret later
- people have different intuitions about cases like `[PASS, ..., XFAIL, XPASS] => ???`, so whatever we do would inevitably surprise _someone_ - and could lead to tests that don't check anything at all
- adding more config options is cognitive load on all users, so I prefer to avoid configurability at almost all costs
- what do we do if `pytest` is _not_ being used?  We don't require it, but changing the behavior seems weird...
- what if the test is _also_ decorated with `@pytest.mark.xfail`, or calls `pytest.xfail()` internally?

...not because I think it's a bad idea for your particular use-case, but because it would get very complicated to support everyone else's use-cases at the same time 🙂

**Comment by nickfraser** [comment]
All good points @Zac-HD, that all makes sense. Thanks again for explaining this all to me and for updating the documentation. 👍
