### ISSUE TITLE
Can hypothesis only generate data that pass validation of Pydantic

### ISSUE THREAD

**Issue by xlyanca** [HypothesisWorks/hypothesis#3739]
hypothesis can work well with Pydantic to generate data based on model defined by Pydantic.
But it cannot well handle the validation failure that Pydantic raises. Taking below code for example. The model PasswordPolicy defines two properties, and they are in range of integer 0 and integer 128. Also min_lower_case_letter should be less than max_lower_case_letter, and it's validated by the model. 
I'm wondering, is there a way to let hypothesis **only generate data that can pass validation of the model,** without triggering the exception. At present, if the data generated by hypothesis is not well validated, it will raise exception and break off the running.

```python
from hypothesis import given, strategies as st, settings
from pydantic import BaseModel, conint, validator


class PasswordPolicy(BaseModel):
    min_lower_case_letter: conint(gt=0, le=128)
    max_lower_case_letter: conint(gt=0, le=128)

    @validator("max_lower_case_letter")
    def check_max(cls, v, values):
        if v < values["min_lower_case_letter"]:
            raise ValueError("max_lower_case_letter must be larger than min_lower_case_letter")
        return v


@given(st.builds(PasswordPolicy))
@settings(max_examples=10)
def test_pydantic(policy):
    assert 0 <= policy.min_lower_case_letter <= 128
    assert policy.min_lower_case_letter <= policy.max_lower_case_letter

```
Run it with Pytest it raises exception
```bash
dev71:~/projects/new_restapi/demo/backup$ pytest --log-cli-level DEBUG --log-file-level DEBUG -s -vv
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.12, pytest-7.2.2, pluggy-1.0.0 -- /home/xyan/projects/venv/venv_rest_api_new/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.10.12', 'Platform': 'Linux-5.19.0-41-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.2.2', 'pluggy': '1.0.0'}, 'Plugins': {'metadata': '2.0.4', 'hypothesis': '6.84.3', 'xdist': '3.3.1', 'html': '3.2.0', 'reportportal': '5.1.5'}}
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/xyan/projects/new_restapi/demo/backup/.hypothesis/examples')
rootdir: /home/xyan/projects/new_restapi/demo/backup, configfile: pytest.ini
plugins: metadata-2.0.4, hypothesis-6.84.3, xdist-3.3.1, html-3.2.0, reportportal-5.1.5
collected 1 item                                                                                                                                                                                                  

test_2.py::test_pydantic FAILED

==================================================================================================== FAILURES =====================================================================================================
__________________________________________________________________________________________________ test_pydantic __________________________________________________________________________________________________

    @given(st.builds(PasswordPolicy))
>   @settings(max_examples=10)

test_2.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for PasswordPolicy
E   max_lower_case_letter
E     max_lower_case_letter must be lager than min_lower_case_letter (type=value_error)

pydantic/main.py:342: ValidationError
============================================================================================= short test summary info =============================================================================================
FAILED test_2.py::test_pydantic - pydantic.error_wrappers.ValidationError: 1 validation error for PasswordPolicy
================================================================================================ 1 failed in 0.22s ================================================================================================
```

**Comment by xlyanca** [comment]
I also created a ticket on Pydantic, it seems the issue comes from hypothesis.
[https://github.com/pydantic/pydantic/issues/7420](https://github.com/pydantic/pydantic/issues/7420)

**Comment by Zac-HD** [comment]
In short:

- https://github.com/HypothesisWorks/hypothesis/issues/3356 will help with individual attributes (it seems from your Pydantic issue that this might be a problem?)
- Custom validator logic can be satisfied by using rejection sampling (i.e. converting the exception into a call to `hypothesis.reject()` or `.assume(False)`), or by writing a custom strategy.  Unfortunately the former is always slow - often to the point of failing entirely - while the latter can take considerable and sometimes tricky work.

Unfortunately there's not much more that we can do here.

**Comment by td-anne** [comment]
> * Custom validator logic can be satisfied by using rejection sampling (i.e. converting the exception into a call to `hypothesis.reject()` or `.assume(False)`), or by writing a custom strategy.  Unfortunately the former is always slow - often to the point of failing entirely - while the latter can take considerable and sometimes tricky work.
> 
> Unfortunately there's not much more that we can do here.

If I understand correctly, when `hypothesis.strategy.from_type` is attempting to generate an object from the type description, if an exception is raised, in particular if it's a validation error, one of three behaviours would be improvements on the current one:

* Hypothesis could catch the exception and report it as a difficulty generating examples rather than an apparent test failure - the current message does not make it obvious that the exception is coming from somewhere outside your test case.
* Hypothesis could automatically convert the exception into a `hypothesis.reject()`.
* Hypothesis could automatically convert the exception into a `hypothesis.reject()` and, if/when the health check fails, the reported problem could mention that the validation failures emanate from `from_type`.

In my case, I have a validation error that occurs when a Path attribute is empty (`.`); this won't be hard for hypothesis to avoid, but because the validator raises an exception I can't use `from_type` at all. Or rather, I have to register custom type strategies for my whole class(es) to work around this specific case.

**Comment by Zac-HD** [comment]
- I guess we could `.add_note(...)` the exception if it's coming from a top-level draw, that would be pretty reasonable.
- Unfortunately automatic-`reject()` tends to silently test a less-diverse set of inputs than people expect, and avoiding "some tests silently miss bugs" is one of our highest design priorities.

I think this just is a case where you need to register some strategies - although maybe `typing.NewType` would let you create a `NonEmptyPath` type and register just that?

**Comment by jobh** [comment]
We do in fact automatically reject on `ValidationError` for django models and forms, so it's not without precedent. I just wanted to point that out, not intending to argue for or against.
