### ISSUE TITLE
Static type check fails for proposed `everything_except()` recipe.

### ISSUE THREAD

**Issue by jenstroeger** [HypothesisWorks/hypothesis#3753]
Hello, following the example recipe given with the [`from_type()`](https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.from_type) strategy (I removed the `excluded_types: type | tuple[type]` arg to simplify the code), I noticed that said recipe fails to type check:
```python
# test.py

import typing

import hypothesis
import hypothesis.strategies as st

def everything_except() -> st.SearchStrategy[typing.Any]:
    return (
        st.from_type(type)
        .flatmap(st.from_type)
        .filter(lambda x: not isinstance(x, int))
    )
```
fails with this error:
```
test.py:1139:50: error: Cannot use a covariant type variable as a parameter  [misc]
```
A few observations:
- Note the line number — it’s always that line no matter where in the code I place this function.
- Placing a `# type: ignore[misc]` comment doesn’t work for _any_ line in the above test.
- Removing `flatmap()` passes the type checks.

Running that strategy seems to work, though:
```python
@hypothesis.given(data=everything_except())
def test_data(data: typing.Any) -> None:
    print(type(data), data)

test_data()
```
produces the expected output.

This is for hypothesis v6.86.1 and mypy v1.5.1. Please let me know if you need more information, or if you’re able to reproduce.

I’m going to dig around some more later today to try and find the cause of the failing type check. For the time being, I’m going to (have to) decorate the function with [`@no_type_check`](https://docs.python.org/3/library/typing.html#typing.no_type_check) to disable type checking.

**Comment by Zac-HD** [comment]
Huh, that line number points to https://github.com/HypothesisWorks/hypothesis/blob/f73dab79a02a3b1bffdec3668a194d6da692147c/hypothesis-python/src/hypothesis/strategies/_internal/core.py#L1139 and sure enough, if I change `Ex` -> `Ex_Inv` the error goes away.  Patch incoming!

You might also want to report a bug against `mypy` for the confusing location report though, claiming it's in `test.py` sure seems like a bug to me.

**Comment by jenstroeger** [comment]
Thank you for the instant fix @Zac-HD, I opened an issue with `mypy` also.

I’ll try again when the new Hypothesis release rolls out.

**Comment by Zac-HD** [comment]
Hypothesis 6.87.0 has the fix and [was released three hours ago](https://www.youtube.com/watch?v=SYZqC7EGMfM&t=1s) 😁

**Comment by jenstroeger** [comment]
Indeed it worked 👍🏼
