### ISSUE TITLE
`PermissionError` when Hypothesis database dir path is not accessible

### ISSUE THREAD

**Issue by Stranger6667** [HypothesisWorks/hypothesis#3764]
After [this change](https://github.com/HypothesisWorks/hypothesis/pull/3760/files#diff-1f3cf8c2d4ae4189b670880104a36693a072b4b696887c9ec1ea84d308dfebceR47), checking for whether the given location is usable may lead to `PermissionError`, if the location has e.g. `0o222` permissions. Previously, `os.path.exists` did not raise an exception there. [Found out about](https://github.com/schemathesis/schemathesis/actions/runs/6448431831/job/17505689595?pr=1803) it downstream in Schemathesis - I guess that the expected behavior for the cases when the directory is not accessible is to work with an in-memory database, but it does not happen due to `PermissionError`

**Comment by Stranger6667** [comment]
I also noted that it only affects Linux in Schemathesis's test suite

**Comment by Zac-HD** [comment]
I guess we should wrap a `try: ... / except OSError: return False` around https://github.com/HypothesisWorks/hypothesis/blob/5278b7cf4815857c0147389107060a8bf340d256/hypothesis-python/src/hypothesis/database.py#L47-L50

...and add a test for this specific case on Linux, too.  I'll fix that this week, if you don't beat me to it.

**Comment by JonathanPlasse** [comment]
I would like to take this on.
