### ISSUE TITLE
Should `hypothesis.extra.django.from_model` return a parametrized `SearchStrategy`?

### ISSUE THREAD

**Issue by Viicos** [HypothesisWorks/hypothesis#3771]
This is the current signature of `from_model`:

https://github.com/HypothesisWorks/hypothesis/blob/a331d3e072e436403b0ddc87222023295ca6e095/hypothesis-python/src/hypothesis/extra/django/_impl.py#L65-L68

I think the signature could be improved with something like:

```python
ModelT = TypeVar("ModelT", bound=dm.Model)

def from_model( 
     model: Type[ModelT], /, **field_strategies: Union[st.SearchStrategy, EllipsisType] 
 ) -> st.SearchStrategy[ModelT]: 
```

If this is the case, I can open a PR

**Comment by Zac-HD** [comment]
Sounds good to me - a PR would be much appreciated!
