### ISSUE TITLE
Add examples in batch

### ISSUE THREAD

**Issue by nilp0inter** [HypothesisWorks/hypothesis#3777]
It would be nice to have the option to add multiple explicit examples to a test case with only one decorator, something like this:

```python
my_explicit_cases = [
  (("ex1_a1", "ex1_a2"), {"k1": "ex1_v1"}),  # First example
  (("ex2_a1", "ex2_a2"), {"k1": "ex2_v1"})   # Second example
  # etc
]

@given(...)
@example().from_(my_explicit_cases)
def test_something(a, b, k1=None):
   ...
```

The benefit of this approach is that it would trivial to keep a list of cases in an external module or even as JSON/YAML file.

If this proposal seems reasonable to you, I can prepare a pull request.

Cheers!

**Comment by Zac-HD** [comment]
Thanks for writing up the proposal!  We've considered this a few times before, and decided not to include it for reasons including:

- individual decorators are much easier for tools to work with, whether that's typecheckers or Hypothesis' own patch-dumping logic
- there are a couple of reasonable API designs - passing tuples or dicts of arguments is more convenient but doesn't support xfail or via methods; passing a sequence of decorator objects begs the question of why you're wrapping them
- every new feature we support is a cognitive burden on all our users, especially learners.  We strongly prefer to have as small and orthogonal an interface as we can.
- it's easy to implement this downstream, as a helper function in your own tests: eg https://github.com/python/cpython/blob/67a91f78e4395148afcc33e5cd6f3f0a9623e63a/Lib/test/test_zoneinfo/test_zoneinfo_property.py#L73-L100
