### ISSUE TITLE
Question: specifying conditional assumption during generation with chaining multiple strategies

### ISSUE THREAD

**Issue by yarnabrina** [HypothesisWorks/hypothesis#3783]
I am trying to generate an arbitrary arithmetic expression for a dummy calculator package with the following:

```python
import hypothesis.strategies as st


def gen_arithmetic_expression() -> st.SearchStrategy:
    """Generate an arbitrary arithmetic expression of positive finite real numbers.

    Returns
    -------
    st.SearchStrategy
        updated strategy
    """
    gen_num = st.one_of(
        st.integers().map(str),
        st.floats(allow_nan=False, allow_infinity=False, allow_subnormal=False).map(
            lambda el: format(el, "f")
        ),
    )
    gen_cond_space = st.booleans().map(lambda el: " " if el else "")

    gen_binary_expr = st.tuples(
        gen_num, gen_cond_space, st.sampled_from(["+", "-", "*", "/"]), gen_cond_space, gen_num
    ).map("".join)

    gen_cond_paren_expr = st.tuples(st.booleans(), gen_binary_expr).map(
        lambda els: f"({els[1]})" if els[0] else els[1]
    )

    gen_general_expr = st.recursive(
        gen_cond_paren_expr,
        lambda children: st.tuples(
            children,
            gen_cond_space,
            st.sampled_from(["+", "-", "*", "/"]),
            gen_cond_space,
            children,
        ).map("".join),
    )

    return gen_general_expr

```

This is able to generate the arithmetic expressions in the form I want, but it is often leading to `ZeroDivisionError`. It is mostly being caused by `gen_binary_expr`, where I could not add a condition that the second number genration using `gen_num` should not generate `0` if `st.sampled_from(["+", "-", "*", "/"])` generate `/`. Since the input to my calculator function (and the test function) is an expression string, and not the individual objects, I could not use `assume` and skip these cases.

So, is there any way to control these generations conditionally?

(The same issue can also be caused by cases where one parenthesised expression evaluates to `0` exactly, and it's the second operand to division. But that's probably more difficult to skip during geeration, so ignoring that for now.)

**Comment by Zac-HD** [comment]
I think you'd want something like:

```python
        lambda children: st.tuples(
            children,
            gen_cond_space,
            st.sampled_from(["+", "-", "*", "/"]),
            gen_cond_space,
            children,
        ).filter(op_not_div_or_divisor_nonzero).map("".join),
```

although implementing `op_not_div_or_divisor_nonzero` in this paradigm means you need to be able to evaluate the subexpression.

More generally, I think you're going to hit operator-precedence problems where the generated string doesn't actually match the implicit tree.  The canonical way to fix that is to generate a syntax tree and then serialise it as a string as the final step - adding parens where necessary and not already included - but that _is_ a fair bit more work.

Alternatively, you can just `except ZeroDivisonError: hypothesis.reject()` and hope it doesn't happen too often!
