### ISSUE TITLE
Untyped decorator makes function untyped for strategies.composite decorator 

### ISSUE THREAD

**Issue by TomNicholas** [HypothesisWorks/hypothesis#3786]
I expected this to pass mypy - am I typing this incorrectly or is hypothesis not typing the `strategies.composite` decorator correctly?

```python
from __future__ import annotations

import hypothesis.strategies as st


@st.composite
def my_integers(
    draw: st.DrawFn,
) -> st.SearchStrategy[int]:
    return draw(st.integers())
```
```
error: Untyped decorator makes function "my_integers" untyped  [misc]
```
`hypothesis==6.88.3`, `mypy==1.7.0`

Came up in https://github.com/dask/dask/pull/9374

**Comment by TomNicholas** [comment]
Actually maybe I was just supposed to type it like this instead

```python
@st.composite
def my_integers(
    draw: st.DrawFn,
) -> int:
    return draw(st.integers())
```

**Comment by Zac-HD** [comment]
Yep, I think the latter is correct - although you could go a step further and
```python
def my_integers() -> SearchStrategy[int]:
    return st.integers()
```
This does look a little silly, but I often see uses of `@st.composite` which could be an undecorated function which defines some strategies for arguments and then returns `st.builds(...)`.

---------------------

I can't find an overload which makes typecheckers provide a more useful message, but I _can_ add a runtime warning easily enough 🙂
