### ISSUE TITLE
Add the ability to opt out of (into?) coverage reporting when collecting observability data

### ISSUE THREAD

**Issue by hgoldstein95** [HypothesisWorks/hypothesis#3821]
I'm experiencing significant slowdown (~10x at least) when collecting observability data vs. not. At first I thought the data collection itself was slow, but even a no-op `TESTCASE_CALLBACK` causes the performance degradation. I was able to narrow the issue down to **tracing**; if [this if-statement](https://github.com/hgoldstein95/hypothesis/blob/6a6c1cf553a99d82af5baf6eeed848d0968600e8/hypothesis-python/src/hypothesis/core.py#L977) is disabled, performance returns to normal.

I think this kind of performance hit is expected for coverage measurement, and that's fine in a lot of cases, but Tyche needs to operate in a pretty tight feedback loop. Can we add a flag that makes coverage measurement optional?

**Comment by Zac-HD** [comment]
https://github.com/HypothesisWorks/hypothesis/pull/3776 means collecting coverage info should be pretty fast on CPython 3.12+, but I'd be happy to add another environment variable and make the `_trace_obs` calculation a bit more complicated.  Want to open a PR?

**Comment by hgoldstein95** [comment]
Just made one! (Hopefully I did it right). #3826

**Comment by tybug** [comment]
Looks like this can be closed with the above pr 👍
