### ISSUE TITLE
Function name is reported as `_bootstrap_fixtures_and_run_test` in verbose reporting

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#3823]
When running with `--hypothesis-verbosity=verbose` (or debug), a thing that I'm sure literal dozens of people have ever done, you'll see lots of messages of the form `Trying example: _bootstrap_fixtures_and_run_test(`. This is presumably an internal wrapper function of ours. It would be nice if these still showed the test name as they're meant to.

**Comment by Zac-HD** [comment]
[Nope, not ours!](https://github.com/search?q=repo%3AHypothesisWorks%2Fhypothesis%20_bootstrap_fixtures_and_run_test&type=code)  I'd guess this is a pytest plugin of some kind injecting a wrapper.

**Comment by DRMacIver** [comment]
Oh, interesting. Looks like it's [pytest-trio's fault](https://github.com/python-trio/pytest-trio/blob/e930e6f6e8fb4d2a336dfa1313fb95c91c2c1725/pytest_trio/plugin.py#L396). I'll file a bug/make a PR there.
