### ISSUE TITLE
Observability output does not conform to json spec

### ISSUE THREAD

**Issue by tybug** [HypothesisWorks/hypothesis#3831]
We output things like `NaN` and `-Infinity` in our observability json reports. This is the same behavior as python's `json.{dumps, loads}`:

> If allow_nan is false (default: True), then it will be a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) to serialize out of range [float](https://docs.python.org/3/library/functions.html#float) values (nan, inf, -inf) in strict compliance of the JSON specification. If allow_nan is true, their JavaScript equivalents (NaN, Infinity, -Infinity) will be used.
> https://docs.python.org/3/library/json.html#json.dump

But it is not part of the [json spec](https://www.json.org/json-en.html), strictly speaking. Among other things, this means it will not be parsed by javascript's `JSON.parse` — a fact I discovered when running into this error with [tyche](https://github.com/tyche-pbt/tyche-extension):

```
Tyche: Could not parse JSON report.
SyntaxError: No number after minus sign in JSON at position 195
Invalid Object: {"type": "test_case", "run_start": 1704660101.9671109, "property": "sandbox.py::test_f", "status": "passed", "status_reason": "", "representation": "test_f(\n    n=-inf,\n)", "arguments": {"n": -Infinity}, "how_generated": "generated during unknown phase", "features": {}, "metadata": {"time_running_test": 7.910421118140221e-07, "time_drawing_args": 0.0001550419838167727, "time_interactive_draws": 0, "traceback": null}}
```

And a simple reproducing test case for the above:

```python
from hypothesis import *
from hypothesis.strategies import *

@given(floats())
def test_f(n):
    pass
```

In my opinion, we are doing the sane thing here by outputting these special floats raw. I definitely don't want to mess around with string-valued float infinities that need special markers to be parsed lest they be confused for the string "Infinity".

But I think we should note in the docs that we're conforming to a superset of json. Something like https://json5.org/, though the only superset features we're using there are the above float representations.

cc @hgoldstein95

**Comment by hgoldstein95** [comment]
Yeah, that makes sense to me. I upgraded our JSON parser in Tyche to address this.
