### ISSUE TITLE
Can one tune run time of RuleBasedStateMachine?

### ISSUE THREAD

**Issue by eivindjahren** [HypothesisWorks/hypothesis#3866]
RuleBasedStateMachine seems really powerful for our application, but running it can take quite a lot of time. Is there any way of tuning the number of examples, or set a timelimit?

**Comment by eivindjahren** [comment]
Figured out that it can be tuned with the @settings fixture.

**Comment by Zac-HD** [comment]
For usage questions, https://stackoverflow.com/questions/tagged/python-hypothesis offers a more-searchable way to find answers - and ensure that they'll be useful to other users, too 🙂
