### ISSUE TITLE
Bad pretty repr-printing for a strategy involving lambda that you repr(eval(repr(…)))

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis#387]
This is based on a discovery in CI for #383, based on the `test_pretty_repr.py` test. Consider the following snippet, based loosely on how that test works:

```python
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

import hypothesis.strategies as st

strategy_globals = dict(
    (k, getattr(st, k))
    for k in dir(st)
)

s = st.none().map(lambda: None)

r1 = repr(s)
r2 = repr(eval(repr(s), strategy_globals))

print(r1)  # none().map(lambda: None)
print(r2)  # none().map(lambda: <unknown>)

assert r1 == r2
```

Basically, if you have a strategy that includes a lambda function and you then `repr(eval(repr(…)))` it, the human-readable form of your lambda is lost. Sadness.

It’s two problems compounded together:

* In `test_pretty_repr.py`, we have a `Strategies` strategy that generates, well, strategies. The old weighting of `one_of()` will never include a lambda function in this output – I’ve generated about 15,000 strategies, and the word "lambda" never appears. The new weighting tips it so they start to appear, albeit infrequently, but that’s enough to get Hypothesis’s attention.

* Hypothesis uses `inspect.getsource` to look up the source of a lambda function. This works if you `repr()` the strategy example you get, but not if you `repr(eval(repr(…)))` the same object – we get an OSError and are unable to parse the source.

   Because `inspect` goes off to the file where an object is defined and tries to read it from there, it chokes on this function that magically appears at runtime – I suspect for the same reason you can’t use `inspect.getsource()` for a lambda you’ve defined in the REPL.

I think this is pretty unusual, so I’m not too fussed about it being broken in this scenario, but we are going to see more lambda-based strategies when we merge #383. Until we can fix it, I’m just going to ban lambda strategies from that test. We weren’t checking them anyway.

**Comment by DRMacIver** [comment]
Oh huh.  That makes sense, thanks. 

Annoyingly this is something the decompiler based solution would handle flawlessly. 

Anyway I'm entirely on board with your proposed interim solution

**Comment by Zac-HD** [comment]
Closing this as unlikely to see any substantial improvement in the status quo, though we'd love a PR.
