### ISSUE TITLE
 Empty dictionaries generated with st.dictionaries and st.just despite expected behavior

### ISSUE THREAD

**Issue by imAsparky** [HypothesisWorks/hypothesis#3909]
Hello Folks, 

Description
I'm consistently observing empty dictionaries being generated by Hypothesis, despite using the following strategy, which should ensure non-empty values:
```
@given(st.dictionaries(keys=st.just("tags"), values=st.just(["v1", "v2"])))
def test_empty_dictionaries(tags):
    print(f"TAGS {repr(tags)}")
    assert 1 == 2  # Fails as intended
```

Expected Behavior

All generated dictionaries should have the key "tags" with a value of the list:  ["v1", "v2"]

Actual Behavior

A significant number of empty dictionaries ({}) are being generated, interspersed with correctly populated dictionaries.

Reproducibility

    This issue occurs consistently across multiple clean environments and operating systems.
    I have not been able to isolate any specific library or configuration that causes the issue.

Tested Environments

    macOS 14.3.1
        Python 3.12.2
        Hypothesis 6.87.4
    Ubuntu 22.04 LTS
        Python 3.11.7, 3.12.1
        Hypothesis 6.98.17
    Windows 10
        Python 3.12.2
        Hypothesis 6.98.17

Additional Notes

    The incorrect behavior persists even when running the provided code snippet in complete isolation.
    I'm happy to provide further details or assist in debugging if needed.

Call for Help

Has anyone else encountered similar behavior? Any insights or suggestions from Hypothesis maintainers would be greatly appreciated!

Thank you in advance

**Comment by Zac-HD** [comment]
https://hypothesis.readthedocs.io/en/latest/data.html#hypothesis.strategies.dictionaries

Try passing `min_size=1`, or using the `fixed_dictionaries()` strategy if you want specific keys and values.  Or even `st.builds(lambda: {"tags": ["v1", "v2"]})` for this particular case.

**Comment by imAsparky** [comment]
G'day @Zac-HD The strategy I shared was where I got to debugging some tests.  It seemed to me it should work in this config, thank you  for the fast response and for setting me straight.
