### ISSUE TITLE
Test for compatibility with Numpy prerelease (2.0 is coming this month)

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#3950]
https://github.com/pydata/xarray/issues/8844#issuecomment-2048538094 points out that [this test](https://github.com/pydata/xarray/blob/07c7f969fe879af7a871374209957d5cd1ddb5aa/xarray/tests/test_strategies.py#L202-L222) is [failing](https://github.com/pydata/xarray/actions/runs/8638322254/job/23682526243?pr=8854#step:8:2530) on the [upcoming Numpy 2.0](https://github.com/numpy/numpy/issues/24300), and it looks like we're incompatible.

Specifically, `hypothesis.extra.array_api.make_strategies_namespace()` eventually calls `next_up()` on an instance of `numpy.float32`, and makes the failing asserting that this is an instance of builtin `float`.

- [ ] [Add a numpy-prerelease build to our CI system](https://numpy.org/devdocs/dev/depending_on_numpy.html#testing-against-the-numpy-main-branch-or-pre-releases); we can allow failures (as for pyodide) but it's good to know
- [ ] If that doesn't reproduce this problem, add a test which does
- [ ] Fix the incompatibility, so that we'll work out of the box when Numpy 2.0 is released

**Comment by keewis** [comment]
potential test case:
```python
from hypothesis import given
from hypothesis.extra.array_api import make_strategies_namespace
import numpy as np

try:
    import numpy.array_api
    xps = make_strategies_namespace(numpy.array_api)
except ImportError:
    xps = make_strategies_namespace(np)

dtypes = xps.floating_dtypes()
shapes = xps.array_shapes()
arrays = xps.arrays(dtype=dtypes, shape=shapes)


@given(arrays)
def test_array_strategy(arr):
    # or even just `pass`
    assert hasattr(arr, "dtype")
```

as [pointed out](https://github.com/pydata/xarray/issues/8844#issuecomment-2051276145) by @seberg, the cause might be the changed casting rules in `numpy` 2.0, where before `float32(3) + 0.0` would be casted to `float64` (and thus pass the check) while now the result is a `float32`.

**Comment by keewis** [comment]
I believe the issue is that the types in the return value of `np.finfo` changed:

`numpy<2`:
```python
finfo = np.finfo(np.float32)
type(finfo.smallest_normal)  # builtin float 
```

`numpy>=2`:
```python
finfo = np.finfo(np.float32)
type(finfo.smallest_normal)  # float32
```

One way to resolve this would be to simply pass `finfo.smallest_normal` through the builtin `float` constructor.

**Comment by keewis** [comment]
@rgommers, @seberg (or anyone else who knows more about this than me), is that inconsistency something we should expect? Or is it just that this was missed when working on compatibility in the main `numpy` namespace?

**Comment by rgommers** [comment]
I'm not sure that this was on purpose - it could be, but I don't remember. And while `float64` instances ducktype with builtin `float`, `float32` doesn't to the same extent:
```python
>>> isinstance(np.float64(1.5), float)
True
>>> isinstance(np.float32(1.5), float)
False
```

There were a lot of PRs that touched on `finfo`. https://github.com/numpy/numpy/pull/23088 is the one that jumps out most to me.

**Comment by seberg** [comment]
This is just indirect promotion changes, but looks fine to me. Finfo might have more precision than builtin float anyway.

**Comment by keewis** [comment]
to be clear (my edits may have been confusing): `numpy.finfo` never changed, it has always had the fields of the `finfo` struct with the same dtype as the input.

However, both `numpy.array_api` (in `numpy<2`) and `array_api_strict` return have the fields as `float`. So my question was: does the Array API require builtin `float` values for the fields of the `finfo` struct, or is any floating-point dtype fine? In other words, is `numpy.finfo` compliant or not?

**Comment by seberg** [comment]
Ah thanks for the clarification, I was indeed thinking you showed that NumPy changed, and not the strict array API namespace.
For that namespace, the change may be unintentional, although I think it may be for the better also there:  I might suggest to just convert to `float` here with a comment that you don't support long-doubles anyway?

(I don't recall the discussion but it doesn't seem ideal to specify a `float` return, since higher precision floats cannot adhere to it.  That would mean that a package which wants to adhere to it but also supports higher precision floats of whatever kind would be forced to export inconsistent types for `finfo`.)

**Comment by rgommers** [comment]
> I was indeed thinking you showed that NumPy changed

Same here. Okay, less concerned then:)



> (I don't recall the discussion but it doesn't seem ideal to specify a `float` return, since higher precision floats cannot adhere to it. That would mean that a package which wants to adhere to it but also supports higher precision floats of whatever kind would be forced to export inconsistent types for `finfo`.)

There is no way to do anything different aside from changing from a scalar to a 0-D array. Which would be a breaking change, that doesn't seem warranted. `float` was simply the common denominator between the various libraries.
