### ISSUE TITLE
New bitfield strategy

### ISSUE THREAD

**Issue by AdamWRichardson** [HypothesisWorks/hypothesis#3952]
Hi hypothesis team, thanks for all the great work you do!

I was doing some work recently which requires casting a class which represents some bitpacked data to and from an int so naturally wanted to use hypothesis to test this. I made a composite strategy using `integers` to test every combination of bitfields in a larger word and I was wondering whether there was any appetite for adding this to the repo for a wider audience?

Happy for this not to be the case if you believe it to be too niche but wanted to ask before preparing a PR.

**Comment by Zac-HD** [comment]
Hi Adam - I'm glad you found Hypothesis useful, and thanks for thinking of upstreaming you strategy!

My main questions are (1) about how many people would use this, and (2) whether a sufficiently-flexible strategy offers much of an advantage over hand-rolling it.  I often end up writing helpers which are great for a specific project, but where trying to generalize them across several projects would be more trouble than it's worth 😅   In that case, publishing a [third-party extension](https://hypothesis.readthedocs.io/en/latest/strategies.html#writing-an-extension) might be the best way forward.

**Comment by AdamWRichardson** [comment]
Both very good questions:

1) This does seem like a niche case, mostly for embedded devs (a subset) who are using python (a smaller subset) and wanting to do property based testing (the smallest subset imaginable)! So it may not be worth merging upstream, just thought I'd ask here on the off chance I'd get anyone interested.

2) Agreed, it API I have at the minute is very general and I wanted to gather some feedback about it but as per 1) I'd need people to use it.

Happy to publish a third-party extension rather than upsteam, if it becomes popular then maybe there'd be more interest in merging it later

**Comment by jobh** [comment]
:+1: It may be interesting to compare with the core `enum.Flags` strategy, which is basically a bitfield strategy with specialized ordering to prefer shrinking to named flags.

**Comment by Zac-HD** [comment]
Yeah, there's a different underlying implementation for sampling from a flag enum 😇
