### ISSUE TITLE
Easy way to skip all pytest hypothesis tests?

### ISSUE THREAD

**Issue by hoodmane** [HypothesisWorks/hypothesis#3953]
Some of my Hypothesis tests are pretty slow and when I want a basic health check to see that I haven't broken anything I prefer to run the manual tests. Is there a simple way to do this? Maybe I should be adding a hypothesis marker and passing `-m 'not hypothesis'`?

**Comment by Zac-HD** [comment]
Conveniently, Hypothesis automatically adds that marker, so your proposal will work out of the box!

**Comment by hoodmane** [comment]
Okay, I see now when I google `pytest hypothesis marker` it's the first hit:

> Finally, all tests that are defined with Hypothesis automatically have @pytest.mark.hypothesis applied to them. See [here for information on working with markers](https://docs.pytest.org/en/stable/example/markers.html#mark-examples).

I don't know how I missed that when I was searching for it before. Thanks!
