### ISSUE TITLE
Question: Possible to use a composite singleton?

### ISSUE THREAD

**Issue by Wyko** [HypothesisWorks/hypothesis#3954]
I'm using hypothesis throughout my tests, and I've created a composite that generates a certain object for me. Is it possible to use that generated object not in a full hypothesis-enabled test, but as input to a single test?

For example:
``` python
@st.composite
def list_of_ip_networks_and_addresses(draw):
    nets = draw(st.lists(ip_networks(), min_size=1, max_size=5))
    addresses = draw(st.lists(st.ip_addresses(v=4), min_size=1, max_size=5))
    return nets + addresses

def test_foo():
  lst_ips = list_of_ip_networks_and_addresses() # Draw one random example from composite
  ...
```

**Comment by Zac-HD** [comment]
You can do `list_of_ip_networks_and_addresses().example()` to get a random, not-really-representative example drawn from the strategy; if you're doing this a lot I'd suggest caching the strategy object to amortize the cost of creating it + generating a list of inputs to draw from.

**Comment by Wyko** [comment]
Thanks!
