### ISSUE TITLE
Ghostwriter: create @composite strategy from type

### ISSUE THREAD

**Issue by cleder** [HypothesisWorks/hypothesis#3964]
Writing composite strategies is a bit of a chore.
The `hypothesis.strategies.from_type` is great, but to customize it is a bit complex.

It would be great if one could generate composite strategies sourcecode from a type.
(this also may be a workaround for #2876 )

**Comment by Zac-HD** [comment]
Can you show some examples of what you think Ghostwriter could output, and how you'd build on that?

I'd expect `st.builds(T, ...)` to work pretty well in most cases; you only need `@st.composite` if there are dependencies between arguments.
