### ISSUE TITLE
Generation of incorrect values

### ISSUE THREAD

**Issue by amitiunin** [HypothesisWorks/hypothesis#3982]
I have a function that returns the list of objects that inherit from Pydantic BaseModel:
```python3
class Album(BaseModel):
    id: uuid.UUID
    title: str
    description: Optional[str] = None


def get_albums() -> list[Album]:
    return list(map(lambda item: Album.model_validate(item), albums))  # albums is a list of dicts
```

I've tested this function using the `from_type` strategy which was pretty straightforward. Now, I'd like to test the function behavior when a dictionary contains incorrect data which would fail the model validation. I wonder if a strategy that would generate such data could be implemented.

**Comment by Zac-HD** [comment]
Yes, you can easily generate nonconforming data using e.g. the `st.dictionaries()` strategy.
