### ISSUE TITLE
Missing dependencies should result in a more informative build failure

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#400]
See https://github.com/HypothesisWorks/hypothesis-python/issues/399

Currently if you try run the tests but don't have all the dependencies installed it will fail at a later point because it can't find pip. This is not a helpful way of communicating failure, and the build should fail earlier with a message explaining why.

It should also be more clear how to clean up when this happens. I *thought* "make clean" was sufficient, but it seems not to be.

**Comment by Zac-HD** [comment]
The build process has changed substantially in #1127.  We still have problems, but *different* problems.
