### ISSUE TITLE
Improve our internal coverage tests

### ISSUE THREAD

**Issue by tybug** [HypothesisWorks/hypothesis#4003]
Our `./build.sh check-coverage` job has a misconfiguration where it only checks that `hypothesis.internal.conjecture` is fully covered: https://github.com/HypothesisWorks/hypothesis/blob/259813ab310f38af2219de83dc2f79f6fb9c77ff/hypothesis-python/tox.ini#L204

This should be `--cov=hypothesis`, to ensure we have coverage over the entire codebase. 

And it turns out we don't! We should add coverage tests to get to 100% coverage here, then fix the `--cov` argument.

**Comment by jobh** [comment]
It looks like the problem is of recent date, https://github.com/HypothesisWorks/hypothesis/commit/b688f39236499b89dd8b6889f4f7bb37f755abad.

It's best to fix it quickly so the coverage gap doesn't grow too overwhelming. I can probably make a start over the weekend.

Good catch @tybug!

**Comment by tybug** [comment]
I can’t take too much credit, this was discovered independently at pycon 😄. Glad to hear this isn't years old, at least.

**Comment by jobh** [comment]
Reopened to track the three remaining coverage holes

- [ ] hypothesis/core.py:1109
- [ ] hypothesis/internal/entropy.py:130
- [ ] hypothesis/stateful.py:391
