### ISSUE TITLE
Use of hypothesis.internal.compat should be linted in CI

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis#404]
Picking up [a comment](https://github.com/HypothesisWorks/hypothesis-python/pull/401#issuecomment-267609353) from #401:

> I've fixed all the uses of bare range (we should see if we can lint that somehow), plus a few more besides in conjecture.

The hypothesis.internal.compat file contains compatibility wrappers for simultaneous Python 2/3 support. We should add linting that enforces the “raw” versions of these functions are never used in favour of their compatibility counterparts.

I don’t think this is the sort of functionality you get out of the box with something like flake8 or even pylint; I suspect we’d need to write a custom plugin for this.

**Comment by DRMacIver** [comment]
A thing that might work for this is that there may be (or if not we could write) be some sort of 2/3 compatibility linter to the tune of "Warning: This code has different semantics in Python 2 and Python 3" which we can then just not run on compat.py.

A really stupid trivial thing we could do here is run 2to3 over the code and see if it makes any diffs. I don't know if that's practical or has other problems.

**Comment by alexwlchan** [comment]
If you run 2to3 over the codebase, you don’t get any errors except from `setup.py`. (Doesn’t flag `compat.py` because it only looks for places where you call the function.)

2to3 is written in such a way that you can swap in your own set of fixers pretty easily. I’ve managed to whip up a quick prototype that converts `[x]range()` to `hrange()`, by tweaking the existing `xrange()` ~> `range()` fixer.

That said, I have no idea what the licensing situation for that would be – this check, for example, was written by Google and licensed to the PSF, but I’m not sure under what license.

**Comment by DRMacIver** [comment]
Hmm. Writing our own transformation rules to achieve this sounds a bit daft given that it's a hack in the first place.

Maybe we should just try to write something on top of e.g. [baron](https://github.com/PyCQA/baron)? Look for any function calls with forbidden names?

**Comment by Zac-HD** [comment]
Plain ol' human code review has been covering this just fine for 2+ years now, so I'm going to close the issue.  Not that a custom linter would be bad, but we've got better things to do with our time.
