### ISSUE TITLE
System.AccessViolationException with Hypothesis 6.108.x

### ISSUE THREAD

**Issue by CodeTex** [HypothesisWorks/hypothesis#4055]
## Description
When running pytest with Hypothesis versions 6.108.0, 6.108.1, or 6.108.2 on Python 3.11.9, I encounter a `System.AccessViolationException` error. This issue does not occur with Hypothesis versions below 6.108.0. The error suggests an attempt to read or write protected memory, indicating potential memory corruption. I recreated the entire venv just to check this and the error persisted.

## Environment
- Hypothesis version: 6.108.0/6.108.1/6.108.2
- pytest version: 8.2.2
- Python version: 3.11.9
- Operating System: Windows

## Steps to Reproduce
1. Install the specified versions of Hypothesis, pytest (no other pytest plugins used) from pypi and use the official Python dist.
2. Run the following pytest test case:

```python
from hypothesis import given
from hypothesis.strategies import text


def encode(input_string):
    count = 1
    prev = ""
    lst = []
    for character in input_string:
        if character != prev:
            if prev:
                entry = (prev, count)
                lst.append(entry)
            count = 1
            prev = character
        else:
            count += 1
    entry = (character, count)
    lst.append(entry)
    return lst


def decode(lst):
    q = ""
    for character, count in lst:
        q += character * count
    return q


@given(text())
def test_decode_inverts_encode(s):
    assert decode(encode(s)) == s
```

## Expected Behavior
The test should run without any exceptions, as it does with Hypothesis versions below 6.108.0.

## Actual Behavior
The test run results in an unhandled exception:

```sh
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr ptr, Int32 ofs)
   at Python.Runtime.ManagedType.TryFreeGCHandle(BorrowedReference reflectedClrObject, BorrowedReference type)
   at Python.Runtime.Runtime.NullGCHandles(IEnumerable`1 objects)
   at Python.Runtime.Runtime.TryCollectingGarbage(Int32 runs, Boolean forceBreakLoops)
   at Python.Runtime.Runtime.Shutdown()
   at Python.Runtime.PythonEngine.Shutdown()
   at Python.Runtime.Loader.Shutdown(IntPtr data, Int32 size)
```

**Comment by tybug** [comment]
From the stacktrace, it looks like this issue originates from a c# library being used to run the python code. This issue should be reported to that library instead.

**Comment by CodeTex** [comment]
Thanks for pointing me to the c# library! I forgot during the testing of this issue that a conftest was still loaded which imported a python module that was importing c# libraries with pythonnet.
Since this issue did not occur with earlier hypothesis versions while still importing the same c# libraries, I will have a look into those and see what may have caused it.

**Comment by CodeTex** [comment]
@tybug I found the error origin inside the pythonnet libary, specifically all versions >3.0.0 which is tracked in this issue: https://github.com/pythonnet/pythonnet/issues/1977

The solution, whilst keeping all libraries' versions, is simply setting the following environment variable: `PYTHONMALLOC` = "malloc"

Why this error is only triggering when running a test with hypothesis for me but nowhere in other tests or the application using the c# libraries is still unclear to me.
