### ISSUE TITLE
test.ghostwriter.py:test_obj_name fails because of tmp dir

### ISSUE THREAD

**Issue by MeggyCal** [HypothesisWorks/hypothesis#4062]
Hi, thank you for this amazing library! I am updating hypothesis for openSUSE Tumbleweed and with recent version 6.108.5 I encountered a test failure in `test.ghostwriter.py:test_obj_name`. It doesn't recognize `temp_script_file_with_py_function` and fails with:

```
click.exceptions.UsageError: Remember that the ghostwriter should be passed the name of a module, not a file.
```

When I revert https://github.com/HypothesisWorks/hypothesis/commit/769f5750b6bdbdccfd8b8b34c5f9b72196744421, the failure is gone.

It could be another specifics of openSUSE environment, we already have some skipped tests because of it. Just so you know that temp dir could cause problems in this scenario.

**Comment by tybug** [comment]
Thanks for the heads up! Looks like we just ran into the same error in #4063, which means it's likely a hypothesis-side problem: https://github.com/HypothesisWorks/hypothesis/actions/runs/10221479598/job/28284106572

**Comment by Zac-HD** [comment]
This was recently changed in #4050, and I think we should probably just revert those test changes😞

**Comment by Zac-HD** [comment]
Fixed in https://github.com/HypothesisWorks/hypothesis/commit/eb26d398f7ffcf9be85d69851e3d171f1bbd328a
