### ISSUE TITLE
Python 3.14: StructuralCoverageTag.__init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by nedbat** [HypothesisWorks/hypothesis#4067]
The coverage.py nightly Python test runs [started failing on Python 3.14](https://github.com/nedbat/coveragepy/actions/runs/10244490612/job/28337569171#step:7:366):

```
      def structural_coverage(label: int) -> StructuralCoverageTag:
          try:
              return STRUCTURAL_COVERAGE_CACHE[label]
          except KeyError:
  >           return STRUCTURAL_COVERAGE_CACHE.setdefault(label, StructuralCoverageTag(label))
  E           TypeError: StructuralCoverageTag.__init__() takes 1 positional argument but 2 were given
  ```

The other Python versions are fine.

**Comment by nedbat** [comment]
Note: the deadsnakes nightly 3.14 that I've been using had been broken for a few weeks, so if this is a bug in 3.14, it could have been introduced since July 11th.

**Comment by hynek** [comment]
The breakage seems to be related to *attrs* 24.1.0 release.

Based on https://github.com/python-attrs/attrs/issues/1326#issuecomment-2268700397 I would guess that removing the `dataclass_transform` should fix it??

**Comment by Zac-HD** [comment]
Thanks to both of you for the report and suggestions!  I'm looking into this now and should have a fix out soon.

I'm somewhat surprised that this hasn't failed in _our_ CI yet - we're running [3.14-dev](https://github.com/HypothesisWorks/hypothesis/blob/e3e33f877431ad4c0a74fbf5457120b4395d6b4b/tooling/src/hypothesistooling/__main__.py#L454), which [pyenv is currently building from cpython main](https://github.com/pyenv/pyenv/blob/9e7010b72f43cf4ea6c4a8798bb94efca0a9f8b7/plugins/python-build/share/python-build/3.14-dev).  Anyway, let's see if we can make this work.

**Comment by Zac-HD** [comment]
yeah, that's more like it: 
![image](https://github.com/user-attachments/assets/44d7fe99-cd5e-40f0-a57e-b3f0d51eca98)

(ok, with a repro in hand it's time to _fix_ this!)

**Comment by hynek** [comment]
it's beautiful 🥲

**Comment by Zac-HD** [comment]
https://github.com/HypothesisWorks/hypothesis/pull/4069/commits/cd8a71e35431d980736ff047bde6dba9099a5099 seems to have fixed it, so my best guess is that it's (probably something in combination with) `auto_attribs=True` and you might be able to repro from that?

It's after midnight here though, so I'm just going to get the fix released and then go to bed :swea

**Comment by hynek** [comment]
Yes, I've finally managed to compile Python 3.14 on my Mac and apparently *attrs* can't find annotation-only fields on 3.14 anymore. You don't have to do anything, I've got a lead, I just want to understand better what's happening.

**Comment by Zac-HD** [comment]
Ah, there's some other updates I wanted anyway in that PR, so might as well ship it 🙂

**Comment by hynek** [comment]
24.2.0 is out now, so you should be able to replace the whole thing with a single `@attr.frozen` or even `@attrs.frozen` since you depend on 22+ anyways.
