### ISSUE TITLE
Question: Write strategies to fuzz docstrings matching different styles (google, numpydoc, sphinx)

### ISSUE THREAD

**Issue by pawamoy** [HypothesisWorks/hypothesis#4077]
I have a function that can detect the style used in a docstring with different methods (regular expressions, actually parsing the docstring and return the style that matched the highest number of sections, parsing and returning the style that had the less parsing errors, etc.).

Now I would like to test the robustness of this function by generating tons of docstrings matching (or not) different styles, passing them to the function and checking its output.

ChatGPT gave me this:

```python
google_style = st.from_regex(r"Args:\s*\n(\s*\w+:\s*\w+\n)+\s*Returns:\s*\w+\n", fullmatch=True)
numpydoc_style = st.from_regex(r"Parameters\s*\n(\s*\w+ : \w+\n)+\s*Returns\s*\w+\n", fullmatch=True)
sphinx_style = st.from_regex(r":param \w+: \w+\n(:return: \w+\n)?", fullmatch=True)
```

Putting aside the missing sections/fields in each ("raises", "yields", etc.), would the `from_regex` strategy be the right approach, or would you recommend something else? :thinking:

**Comment by Zac-HD** [comment]
I'd probably use `google_style = st.builds(template_str.format, ...)` with a custom strategy defined the same way for each section - explicitly building it up from smaller parts.  There's also [our context-free-grammar support](https://hypothesis.readthedocs.io/en/latest/extras.html#hypothesis-lark), but I usually prefer explicit strategies because they're usually easier to understand and customize - or use subsections for another purpose.

**Comment by pawamoy** [comment]
Thank you @Zac-HD! I'll check out all this and report back once I have something working :slightly_smiling_face: Closing since there's nothing actionable for you here.

**Comment by pawamoy** [comment]
Well, in the end the troubles of generating valid docstrings (but somehow a bit arbitrary) are not worth the benefit of automated testing IMO :raised_eyebrow: I have manually tested my code on a lot of real docstrings and it seems to get things right 95%+ of the time. I expect users to report cases where it doesn't work and I'll tweak the code if possible.

Sorry for not giving back something useful :sweat_smile:
