### ISSUE TITLE
Filtering examples based on previous examples?

### ISSUE THREAD

**Issue by HiPhish** [HypothesisWorks/hypothesis#4088]
Hello,

I am experimenting with Hypothesis and I have been trying to use it to test a FizzBuzz implementation. My FizzBuzz is special in that I can pass a rule set like `[(3, 'Fizz'), (5, 'Buzz')]` to change which numbers to check for and which strings to display. I have identified a number of properties to test:

- If the number is not divisible by any of the rule numbers print the number
- The result must contain the text of each rule that matches
- The result must not contain the text of any rule that does not match
- The text strings must be in the same order they were in the rule set
- The result must not contain any strings which are not part of some rule

The first one is easy to test, the last two I don't know how to test, but that's not the point. Number 2 and 3 are easy to test, but I can get false failures if the text of one rule is the prefix of another rule. For example, if the rule set is `[(3, 'Ab'), (5, 'A')]` and the number is 6, then the result is `'Ab'`, which is the string of the first rule, but it also contains the string of the second rule, which causes the test to fail. But the result does not really contain the string of the second rule, it just happens that my rules have been chosen poorly.

The question is, how can I tell Hypothesis "when you generate a new rule look at all the previous rules and check that the new text is not contained in any previous one"? Here is my custom `rules` strategy:

```python
@st.composite
def rules(draw) -> Rule:
    """
    Returns a strategy which randomly generates FizzBuzz rules.

    :return: Rule with random number and string value
    """
    number = draw(st.integers(min_value=2))
    value = draw(st.text(ascii_letters, min_size=1)).title()
    return Rule(number, value)
```

And here is the test:

```python
@given(st.lists(rules(), min_size=1, max_size=5,
                unique_by=(lambda r: r.value, lambda r: r.number)),
       st.data())
def test_fizzbuzz_contains_no_mismatch(rules: list[Rule], data: st.DataObject):
    """If the number is not divisible the result does not contain the rule's text."""
    n = data.draw(st.integers()
                    .filter(lambda n: any(r.test(n) for r in rules)),
                  label='number')
    negatives = [r for r in rules if not r.test(n)]
    program = compile_rules(rules)
    result = program(n)
    assert [r for r in negatives if r.value in result] == []
```

The test ensures that all rules have distinct number *and* values, so we cannot get something like `[(3, 'Fizz'), (5, 'Fizz')]`, but it does not prevent `[(3, 'Fizz'), (5, 'Fi')]`. With the `filter` method I can only look at the current example, but not at any previous ones. Obviously this is a contrived toy example, but I want to know how to solve it so I can use the knowledge in a real-world scenario.

**Comment by Zac-HD** [comment]
```python
def distinct_rule_names(ls: list[tuple[int, str]]) -> bool:
    names = {n for _, n in ls}
    return all(
        not any(n.startswith(name) for n in (names - {name}))
        for name in names
    )

@given(st.lists(rules(), ...).filter(distinct_rule_names), ...)
```

**Comment by HiPhish** [comment]
Ouch, that's so obvious in hindsight. Thank you very much.
