### ISSUE TITLE
Test failures with numpy nightly

### ISSUE THREAD

**Issue by tybug** [HypothesisWorks/hypothesis#4102]
https://github.com/HypothesisWorks/hypothesis/actions/runs/10805436485/job/29972556235

```
  FAILED tests/numpy/test_from_type.py::test_resolves_NDArray_with_dtype_union - assert tuple[int, ...] is Any
  ERROR tests/ghostwriter/test_expected_output.py - ValueError: too many values to unpack (expected 2)
```

**Comment by jobh** [comment]
The first one
```
  FAILED tests/numpy/test_from_type.py::test_resolves_NDArray_with_dtype_union - assert tuple[int, ...] is Any
```
should be safe to just remove the `assert`. Numpy didn't previously implement shape-typing, and maybe it still doesn't (?) but it seems that it now signals the "any shape" type in a better way.
