### ISSUE TITLE
Our internals should handle `StopTest` and other marker exceptions even when wrapped in an `ExceptionGroup`

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#4106]
Hypothesis currently misbehaves if the marker exceptions we raise are wrapped up in an `ExceptionGroup`, e.g.:

```python
import trio
from hypothesis import given, strategies as st

@given(st.data())
def test(data):
    async def task(pred):
        return data.draw(st.booleans().filter(pred))

    @trio.run
    async def _():
        async with trio.open_nursery() as nursery:
            nursery.start_soon(task, bool)
            nursery.start_soon(task, lambda _: False)
```
```
  + Exception Group Traceback (most recent call last):
  |   ...
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   ...
    | hypothesis.errors.StopTest: 1
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   ...
    | hypothesis.errors.Frozen: Cannot call start_example on frozen ConjectureData
    +------------------------------------
```

In such cases I think it's pretty clear that we should treat an exception group _containing_ a `StopTest` as we would a `StopTest` itself.  I think it's also pretty clear that any `Frozen` exceptions inside an `ExceptionGroup` are causally downstream of some other exception, and can therefore be discarded so long as there's any other exception in the group too.

**Comment by jakkdl** [comment]
How picky are you about depending on `exceptiongroup` for newer python versions?
3.12.1 added `ExceptionGroup` support for `contextlib.suppress`, so if we wanna use `exceptiongroup.suppress` we need to bump the `install_requirement` to `python < 3.12.1`.
I count 9 instances of `suppress` usage.

Big `try: ... except: ...` blocks such as https://github.com/HypothesisWorks/hypothesis/blob/4d079f7a62a6fdabfb2f2a2b276cb0f721ea62de/hypothesis-python/src/hypothesis/core.py#L1037
Needs to have their exception handlers split out into separate functions. We're then left with the choice of using `exceptiongroup.catch` on all python versions to invoke them, or rolling our own handler in an `except ExceptionGroup`.

I don't think rolling our own is super ugly/complicated in either case, so am open to both options.

**Comment by jobh** [comment]
I suggest it may be simplest to unwrap the `exceptiongroup` around actual test execution, similar in effect to adding it to the end of `ensure_free_stackframes.__exit__` but in a new context manager. Then, everything outside - including the `suppress` calls - are unaffected.

(i.e., `with unwrap_exceptions(), ensure_free_stackframes(): return self.test(...)`)

**Comment by jakkdl** [comment]
Thanks @jobh! That made it much easier to get started on a PR :)
I've opened #4110, would love any reviews
