### ISSUE TITLE
Why is this strategy really slow?

### ISSUE THREAD

**Issue by galenseilis** [HypothesisWorks/hypothesis#4111]
I have implemented this test:

```python
import pytest
from hypothesis import given, strategies as st
from scipy.stats import poisson

@given(lam=st.floats(min_value=0, exclude_min=True), prob=st.floats(min_value=0, max_value=1, exclude_min=True, exclude_max=True))
def test_poisson_quantile_hypothesis(lam: float, prob: float) -> None:
    """Hypothesis test for poisson_quantile with a range of valid inputs."""
    result = poisson_quantile(lam, prob)
    assert isinstance(result, int)
    assert result >= 0
    assert poisson(lam).cdf(result) >= prob
```

I have run it for more than an hour without it finishing. The function `poisson_quantile` returns the quantile of a Poisson distribution with a given rate parameter and percentile. It runs reasonably fast, so I am doubtful it is the bottleneck. Indeed, my other tests for this function are pretty fast, but they do not use Hypothesis. Here is its definition:

```python
def poisson_quantile(lam: float, prob: float) -> int:
    """Compute a quantile for a Poisson distribution.

    Args:
        lam (float): Poisson rate parameter.
        prob (float): Coverage probability.

    Returns:
        q (float): Quantile of Poisson distribution.
    """
    if lam < 0:
        raise ValueError("{lam=} must be non-negative.")
    if prob <= 0 or prob >= 1:
        raise ValueError("{prob=} must be in the open interval (0,1).")
    dist = poisson(lam)
    q = 0
    cum_prob = 0
    while True:
        cum_prob += dist.pmf(q)
        if cum_prob >= prob:
            return q
        else:
            q += 1
```

Any ideas to help me learn why this test is extremely slow?

**Comment by tybug** [comment]
You have a (near-) infinite loop in `poisson_quantile ` when `lam` is very large: `assert poisson(4e16).pmf(i) == 0 for i in range(1000)`. I would recommend setting an upper bound on the `lam` strategy.

**Comment by galenseilis** [comment]
@tybug 

Thank you for the suggestion.

Below I set `max_value=10` and still found that it is taking a long time. Was this the right approach?

```python
@given(lam=st.floats(min_value=0, max_value=10, exclude_min=True), prob=st.floats(min_value=0, max_value=1, exclude_min=True, exclude_max=True))
def test_poisson_quantile_hypothesis(lam: float, prob: float) -> None:
    """Hypothesis test for poisson_quantile with a range of valid inputs."""
    result = poisson_quantile(lam, prob)
    assert isinstance(result, int)
    assert result >= 0
    assert poisson(lam).cdf(result) >= prob
```

**Comment by galenseilis** [comment]
> @tybug
> 
> Thank you for the suggestion.
> 
> Below I set `max_value=10` and still found that it is taking a long time. Was this the right approach?
> 
> ```python
> @given(lam=st.floats(min_value=0, max_value=10, exclude_min=True), prob=st.floats(min_value=0, max_value=1, exclude_min=True, exclude_max=True))
> def test_poisson_quantile_hypothesis(lam: float, prob: float) -> None:
>     """Hypothesis test for poisson_quantile with a range of valid inputs."""
>     result = poisson_quantile(lam, prob)
>     assert isinstance(result, int)
>     assert result >= 0
>     assert poisson(lam).cdf(result) >= prob
> ```

nvm, I think your suggestion fixed the problem. I suspect there was something weird happening with VSCode.

**Comment by galenseilis** [comment]
> @tybug
> 
> Thank you for the suggestion.
> 
> Below I set `max_value=10` and still found that it is taking a long time. Was this the right approach?
> 
> ```python
> @given(lam=st.floats(min_value=0, max_value=10, exclude_min=True), prob=st.floats(min_value=0, max_value=1, exclude_min=True, exclude_max=True))
> def test_poisson_quantile_hypothesis(lam: float, prob: float) -> None:
>     """Hypothesis test for poisson_quantile with a range of valid inputs."""
>     result = poisson_quantile(lam, prob)
>     assert isinstance(result, int)
>     assert result >= 0
>     assert poisson(lam).cdf(result) >= prob
> ```

Actually, I am not sure what is going on. It is usually fast now but there were a couple of times where it was still slow.
