### ISSUE TITLE
`RecursionError` in `InterestingOrigin.from_exception` with recursive `__context__`

### ISSUE THREAD

**Issue by jakkdl** [HypothesisWorks/hypothesis#4115]
```python
def test_recursive_exception():
    @given(st.data())
    def test_function(data):
        try:
            raise ExceptionGroup("", [ValueError()])
        except ExceptionGroup as eg:
            raise eg.exceptions[0] from None
    test_function()
```
causes an infinite recursion in `InterestingOrigin.from_exception`
https://github.com/HypothesisWorks/hypothesis/blob/879225d8836c657fe970ceb1a95df072e06352d4/hypothesis-python/src/hypothesis/internal/escalation.py#L110-L127

Due to `exception.__context__.exceptions[0] is exception`.
You can also do it without exceptiongroups, but idk if this would ever be encountered in the wild:
```python
def test_recursive_exception2():
    @given(st.data())
    def test_function(data):
        k = ValueError()
        k.__context__ = k
        raise k
    test_function()
```

Encountered during development of #4110

**Comment by Zac-HD** [comment]
We should clearly fix both of these - thanks for the report!

**Comment by jakkdl** [comment]
Since I wanted to reraise a group exception in #4110 I added a quick fix in the latest commit: https://github.com/HypothesisWorks/hypothesis/pull/4110/commits/14be2023f5c6db94383c6d668a249befd4c7d345#diff-790b2cc456c4882f3785f65d06add0d5ed8e472a5c48b9abcbfd56eb23fb952a

idk what you want the long-term fix to be, but I feel like this should have some standard-ish solution used in pytest and others that parses `__context__`.
