### ISSUE TITLE
check-py314-cover failing on local builds

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#4134]
Based on the failure in  #4133 I was looking into running check-py314-cover locally and I get a pile of failures, mostly in the resolution of forward refs:

```
:test_resolve_fwd_refs[Foo-Optional] - AssertionError: assert <class 'tests.cover.test_compat.Foo'> == typing.Optional[tests.cover.test_compat.Foo]
FAILED tests/cover/test_lookup.py::test_resolves_forwardrefs_to_builtin_types[bool] - hypothesis.errors.InvalidArgument: thing=ForwardRef('bool') must be a type
```

I also *don't* see the failures that I'm seeing in #4133 locally.

I suspect what's happening here is that it should also be failing on CI but has cached an older build of the 3.14 dev branch and the newest build would also break there, but I won't swear to it and don't want to mess with clearing the cache and causing a bunch of new build breakages.

It's theoretically possible that the difference might be that I'm running on OSX rather than Linux, but I can't imagine it causing these specific errors.

**Comment by Zac-HD** [comment]
Closed by https://github.com/HypothesisWorks/hypothesis/pull/4145
