### ISSUE TITLE
`st.from_type(type)` broken by 6.114.0 -- only returns `type`

### ISSUE THREAD

**Issue by rsokl** [HypothesisWorks/hypothesis#4144]
Before 6.114.0

```python
>>> [st.from_type(type).example() for _ in range(10)]
[datetime.time,
 re.Match,
 ExceptionGroup,
 ipaddress.IPv6Interface,
 str,
 numbers.Integral,
 numbers.Complex,
 fractions.Fraction,
 range,
 zoneinfo.ZoneInfo]
```

After:

```python
>>> [st.from_type(type).example() for _ in range(10)]
[type, type, type, type, type, type, type, type, type, type]
```

**Comment by Zac-HD** [comment]
Ah, we did change how generic types are resolved a little, but I bet we can fix it by reworking [this bit in particular](https://github.com/HypothesisWorks/hypothesis/pull/4131/commits/df28a74a8015471daa2f812be4422963bfb1b99c#diff-f6a209c019f3f6af11a027a0035e3fc736935d9920fd85da726f9abf4c325d6bL848-R857) - and writing some tests that our `everything_except()` recipe generates more diverse types.
