### ISSUE TITLE
Getting invalid data generation for `hypothesis.stateful.Bundle` since 6.112.3

### ISSUE THREAD

**Issue by lycantropos** [HypothesisWorks/hypothesis#4181]
Here's a script for reproduction
```python
from hypothesis import strategies as st
from hypothesis.stateful import Bundle, RuleBasedStateMachine, initialize, rule


class Class:
    def __init__(self, value):
        self.value = value


class Reproduction(RuleBasedStateMachine):
    my_bundle = Bundle('my_bundle')

    @initialize(target=my_bundle)
    def set_initial(self, /) -> str:
        return 'sample text'

    @rule(instance=st.builds(Class, my_bundle))
    def check(self, instance):
        assert isinstance(instance, Class)
        assert isinstance(instance.value, str)


TestCase = Reproduction.TestCase
```
let's save it as `check.py`, install latest `pytest` and after that call
```bash
> pytest check.py
```
gives
```bash
...
================================================================ short test summary info ================================================================
FAILED check.py::TestCase::runTest - AssertionError: assert False
 +  where False = isinstance(VarReference(name='my_bundle_0'), str)
 +    where VarReference(name='my_bundle_0') = <check.Class object at 0x7f25139c4470>.value
Falsifying example:
state = Reproduction()
my_bundle_0 = state.set_initial()
state.check(instance=Class(VarReference(name='my_bundle_0')))
state.teardown()

You can reproduce this example by temporarily adding @reproduce_failure('6.119.3', b'AAAAAAAAAAA=') as a decorator on your test case
=================================================================== 1 failed in 0.16s ===================================================================
```
by looking into git history my guess that it has something to do with changes in #4124.

Is this change in behavior expected?

**Comment by lycantropos** [comment]
It seems that after resolution of #4128 in #4129 I can fix this by using `my_bundle.flatmap(lambda value: st.builds(Class, st.just(value))`, but why simpler original version doesn't work?
Also declaring
```python
my_bundle = Bundle('my_bundle', draw_references=False)
```
helps, but it is not documented, what it does/should do? Is it for internal-use only?

**Comment by reaganjlee** [comment]
Yes `draw_references` is designed for internal-use. For the behavior change, I personally didn't expect this, but I don't really have strong opinions on the syntactics of each? Maybe having `my_bundle.flatmap(lambda value: st.builds(Class, st.just(value))` could be simpler internally, but I think @Zac-HD would probably have better thoughts

**Comment by lycantropos** [comment]
my main concern is backward-compatibility and [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), why does wordy `flatmap` work and simpler `map` does not, especially when it worked perfectly before

**Comment by reaganjlee** [comment]
Fwiw `map` is being name-spaced in [this PR](https://github.com/HypothesisWorks/hypothesis/pull/4084), but when looking at the [hypothesis docs](https://hypothesis.readthedocs.io/en/latest/data.html), this is actually definitely a regression that should be covered. I'll take a look, sorry about that!
