### ISSUE TITLE
Delete stale Hypothesis branches?

### ISSUE THREAD

**Issue by tybug** [HypothesisWorks/hypothesis#4184]
It makes me a bit sad to see "44 branches" on the main github landing page. [Most of these](https://github.com/HypothesisWorks/hypothesis/branches/all) are old (>4 years) and I think can be unambiguously deleted — but I don't want to go around performing permanent operations without saying something first. I think we should pare down to just two: `master` and `create-pull-request/patch`, for the weekly dependency updates.

IMO I wouldn't even have permission to create branches in the Hypothesis repo and all contributions by maintainers go through forks, to avoid this buildup in the future 😄

**Comment by Zac-HD** [comment]
I occasionally go through and delete anything which is unambiguously stale, some of these are WIPs that we might pick up again for old issues though.  I agree that working in forks is a good idea going forward.

**Comment by tybug** [comment]
yup makes sense!
