### ISSUE TITLE
Test teardown fails with `ERROR .hypothesis/tmp - FileNotFoundError: [Errno 2]`

### ISSUE THREAD

**Issue by enitrat** [HypothesisWorks/hypothesis#4200]
In our [CI Job](https://github.com/kkrt-labs/keth/actions/runs/12269297723/job/34232619504) in which we use `pytest` and `hypothesis`, we run our tests with           [uv run pytest -n logical --junitxml=junit.xml -o junit_family=legacy](https://github.com/kkrt-labs/keth/blob/54912a7c64448fc92a6745321aebce7f9cfb6a0b/.github/workflows/python_tests.yml#L32)

After 100% of tests are run, the process fails with error:

```
ERROR .hypothesis/tmp - FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/keth/keth/cairo/.hypothesis/tmp'
```

I'm not sure exactly where this could come from, as it isn't always systematic.

**Comment by Zac-HD** [comment]
Can you provide a minimal reproducing example?  GitHub code spaces can be good for multi-file setups.

**Comment by enitrat** [comment]
I'm not really sure how to produce a MRE - my first hypothesis (no pun intended) is that this happens when the GHA Caches are reaching the 10GB limit, and are saturated - perhaps the runner is not having enough space to keep the tmp files?

**Comment by ClementWalter** [comment]
The error message 

```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.4, pluggy-1.5.0
rootdir: /home/runner/work/keth/keth/cairo
configfile: pyproject.toml
plugins: asyncio-0.24.0, typeguard-2.13.3, hypothesis-6.122.3, xdist-3.6.1, profiling-1.8.1
asyncio: mode=strict, default_loop_scope=session
created: 64/64 workers
64 workers [525 items]

........................................................................ [ 13%]
........................................................................ [ 27%]
........................................................................ [ 41%]
........................................................................ [ 54%]
........................................................................ [ 68%]
........................................................................ [ 82%]
........................................................................ [ 96%]
.....................                                                    [100%]
==================================== ERRORS ====================================
_______________________ ERROR collecting .hypothesis/tmp _______________________
../.venv/lib/python3.10/site-packages/_pytest/runner.py:341: in from_call
    result: TResult | None = func()
../.venv/lib/python3.10/site-packages/_pytest/runner.py:389: in collect
    return list(collector.collect())
../.venv/lib/python3.10/site-packages/_pytest/main.py:523: in collect
    for direntry in scandir(self.path):
../.venv/lib/python3.10/site-packages/_pytest/pathlib.py:950: in scandir
    with os.scandir(path) as s:
E   FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/keth/keth/cairo/.hypothesis/tmp'
```

suggests that the error is in `pytest_make_collect_report`  and eventually in this classe's `collect`

```
@final
class Dir(nodes.Directory):
    """Collector of files in a file system directory.

    .. versionadded:: 8.0

    .. note::

        Python directories with an `__init__.py` file are instead collected by
        :class:`~pytest.Package` by default. Both are :class:`~pytest.Directory`
        collectors.
    """

    @classmethod
    def from_parent(  # type: ignore[override]
        cls,
        parent: nodes.Collector,
        *,
        path: Path,
    ) -> Self:
        """The public constructor.

        :param parent: The parent collector of this Dir.
        :param path: The directory's path.
        :type path: pathlib.Path
        """
        return super().from_parent(parent=parent, path=path)

    def collect(self) -> Iterable[nodes.Item | nodes.Collector]:
        config = self.config
        col: nodes.Collector | None
        cols: Sequence[nodes.Collector]
        ihook = self.ihook
        for direntry in scandir(self.path):
            if direntry.is_dir():
                path = Path(direntry.path)
                if not self.session.isinitpath(path, with_parents=True):
                    if ihook.pytest_ignore_collect(collection_path=path, config=config):
                        continue
                col = ihook.pytest_collect_directory(path=path, parent=self)
                if col is not None:
                    yield col

            elif direntry.is_file():
                path = Path(direntry.path)
                if not self.session.isinitpath(path):
                    if ihook.pytest_ignore_collect(collection_path=path, config=config):
                        continue
                cols = ihook.pytest_collect_file(file_path=path, parent=self)
                yield from cols
```

what is this `.hypothesis/tmp` file actually?

**Comment by Zac-HD** [comment]
As the name suggests, it's a temporary directory; probably [this one](https://github.com/HypothesisWorks/hypothesis/blob/60d070e86e417b58ac9151acf7bcaa45751af240/hypothesis-python/src/hypothesis/internal/charmap.py#L170-L178) as we're writing the unicode cache at startup.  We might be able to work around that, though there are tricky race conditions on various platforms - I don't think it's worth changing.

I'd actually describe this as a pytest bug; [the `scandir()` function](https://github.com/pytest-dev/pytest/blob/24e84f08f43216f95620135305cbebe9f646e433/src/_pytest/pathlib.py#L950-L972) could return an empty list if the path to scan does not exist.

Furthermore, to hit this you must be (attempting to) collect tests under the `.hypothesis/` directory, which is going to cost you startup time for no benefit.  Because [the `norecursedirs` config option](https://docs.pytest.org/en/stable/reference/reference.html#confval-norecursedirs) excludes `.*` by default, your pytest configuration must be overriding this setting - check that and try adding the defaults back in.  I'm planning to put a check for this into Hypothesis' pytest plugin.
