### ISSUE TITLE
The domain strategy is very slow

### ISSUE THREAD

**Issue by ben-alexander** [HypothesisWorks/hypothesis#4201]
I recognise that `domains` is provisional, however, it's in use by the `emails` strategy. I'd prefer to test over a set of valid RFC 3986 domains rather than defining a strategy to naively create some domains. `domains` takes on average 2.6s, which is significantly negatively impacting both the `emails` and `urls` strategies.

This small set of timings shows the differences, I've added instantiating a class as a baseline and the `text` strategy to demonstrate the additional overhead that `domains` is causing

```python
import timeit
from dataclasses import dataclass
from hypothesis import given, strategies as st
import hypothesis.provisional as p

@dataclass
class A:
    value: str

def baseline():
    A(value='test@example.com')
    
@given(st.text())
def text(value: str):
    A(value=value)
    
@given(p.domains())
def domains(value: str):
    A(value=value)

@given(p.urls())
def urls(value: str):
    A(value=value)

@given(st.emails())
def emails(value: str):
    A(value=value)
    
@st.composite
def fake_domain_strategy(draw: st.DrawFn) -> str:
    domain = draw(st.characters(min_codepoint=97, max_codepoint=122))
    return domain + '.com'

@given(fake_domain_strategy())
def fake_domain(value: str):
    A(value=value)

if __name__ == "__main__":

    b = timeit.timeit(baseline, number=1000)
    t = timeit.timeit(text, number=10)
    d = timeit.timeit(domains, number=10)
    u = timeit.timeit(urls, number=10)
    e = timeit.timeit(emails, number=10)
    f = timeit.timeit(fake_domain, number=10)

    print('Field    ', 'Time:   ', 'Compared to:', 'Time difference:')
    print('Baseline ', f'{b:.6f}', 'N/A')
    print('Text     ', f'{t:.6f}', 'baseline    ', f'{t - b:.6f}')
    print('Domains  ', f'{d:.6f}', 'baseline    ', f'{d - b:.6f}')
    print('URLs     ', f'{u:.6f}', 'domains     ', f'{u - d:.6f}')
    print('Emails   ', f'{e:.6f}', 'domains     ', f'{e - d:.6f}')
    print('Fake     ', f'{f:.6f}', 'domains     ', f'{f - d:.6f}')

```
results:
```
Field     Time:    Compared to: Time difference:
Baseline  0.000145 N/A
Text      0.303678 baseline     0.303533
Domains   2.720224 baseline     2.720079
URLs      3.560947 domains      0.840723
Emails    2.867589 domains      0.147365
Fake      0.060368 domains      -2.659856
```
The highlight is that the `domains` strategy regularly takes 2.6-2.7s

In the Time difference column I've attempted to strip out the "cost" of using `domains` to provide an estimate of the timings of `urls` and `emails` in comparison to `text`.

* `text` is 0.3s
* `urls` might be 0.8s if it weren't for domains
* `emails` might be 0.1s if it weren't for domains
* (badly) faking a domain takes the expected length of time, somwhere between not using Hypothesis and the `text` strategy

Looking at this through the profiler it doesn't look like anything in `provisional.py` is the issue, instead it's how the core engine is using the `domains` strategy. Being unfamiliar with the internals of Hypothesis this is quite hard to decipher and I'm hoping that someone in the project might have a quicker idea!

Maybe I'm doing something silly?

Thank you

**Comment by tybug** [comment]
Thanks for the report! Initial diagnosis is a lot of time spent in `SearchStrategy.validate()`. `DomainNameStrategy` is creating a lot of strategies in `do_draw`, and I expect caching those to speed things up.

**Comment by tybug** [comment]
#4202 has some immediate improvements. I think any further performance gains here will have to come from `from_regex` itself, which is a larger task.

**Comment by ben-alexander** [comment]
Thank you for the very quick response @tybug. It looks like it's sped up my tests by 20%, which is a nice win. I'll have to do some digging about why I didn't get the full ~40% benefit.

One thing I did notice is that changing the `label_regex`  to remove the need for `.filter(lambda label: len(label) < 4 or label[2:4] != "--")` when constructing `self.elem_strategy` made a difference.

If `label_regex` becomes `r"[a-zA-Z]([a-zA-Z0-9]{0,%d}\-?[a-zA-Z0-9])?"` then the `--` filter is unnecessary and if it becomes something like the following then I think you can get rid of the `len(label)` filter too

```python
label_regex = r"[a-zA-Z]([a-zA-Z0-9]{0,%d}\-?[a-zA-Z0-9])?" % (
    min(maximum_center_character_pattern_repetitions, 3)
)
```

The length condition isn't exactly the same, but it might defer going into the internals of the `from_regex` strategy for longer.

Note: I haven't run the Hypothesis test suite on this change, but I have tested the URLs generated by `provisional.urls()` against the RFC 3986 ABNF grammar and they're all passing.
