### ISSUE TITLE
Setting `settings` for a `RuleBasedStateMachine` is tricky

### ISSUE THREAD

**Issue by exarkun** [HypothesisWorks/hypothesis#455]
This works:

```python
class Foo(RuleBasedStateMachine):
    ...
Foo.TestCase.settings = settings(...)
```

However, I had to learn that by asking on the IRC channel.  Also, this *doesn't* work but might reasonably be expected to:

```python
class Foo(RuleBasedStateMachine):
    ...
class FooTests(Foo.TestCase):
    pass
FooTests.settings = settings(...)
```

**Comment by Daenyth** [comment]
As a user it would make sense for this to work:

```
@hypothesis.settings(...)
class Foo(RuleBasedStateMachine):
    ...
```

**Comment by Zac-HD** [comment]
This would be a good first issue:

- Add an early section to [`settings.__call__`](https://github.com/HypothesisWorks/hypothesis/blob/b4a064f0d922c04a53cc8a8b498260875110c2a4/hypothesis-python/src/hypothesis/_settings.py#L194) which checks `isinstance(test, stateful.GenericStateMachine)` and if so, just does `test.TestCase.settings = self` then returns.
- Add a test to `hypothesis-python/tests/cover/test_settings.py` which does this, and checks that the settings in the decorator apply while running the state machine.
- Add the file `hypothesis-python/RELEASE.rst` with your notes for a minor release (see other PRs for examples) and add your name to the list of authors in `CONTRIBUTING.rst`.

And feel free to ask me any questions you might have, or for help if you get stuck!
