### ISSUE TITLE
given prevents function local types from being garbage collected

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#493]
A class defined inside a function should be suitable to be garbage collected, but given prevents that. Consider the following test:

```python
 def test_local_types_are_garbage_collected():
      store = [None]

      def run_locally():
          class Test(object):
              @given(st.integers())
              def test(self, i):
                  pass
          store[0] = weakref(Test)
          Test().test()
      run_locally()
      del run_locally
      assert store[0] is not None
      gc.collect()
      assert store[0]() is None
```

This test fails, but passes if you remove the given and replace it with a normal method.

I *believe* the likely culprit is the strategy cache - I think the way we're constructing the arguments to the test function is causing something to hang on to a reference to self. This is probably a sign of a more general problem we should worry about if so.

**Comment by Zac-HD** [comment]
Trawling issues, I suspect that #833 is an example of the (hypothesised) more general problem.  The strategy cache remains the top suspect.
