### ISSUE TITLE
Continuous deployment cleanup task list

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#551]
Here are things I have noticed need doing in the deploy that I am not going to do until I've seen things actually *working*. Others should suggest more:

* [x] It's really really annoying that when a new file is encrypted literally every build job in literally every branch starts failing. The secret decryption should be moved to only run in the deploy task.
* [ ] The pypi repository should be configured outside of the secrets file (see e.g. #550).

**Comment by DRMacIver** [comment]
I'm going to leave the second one for a bit because I just cannot be arsed to do more build wrangling right now and it's not especially critical.

**Comment by Zac-HD** [comment]
Closed by #550?

**Comment by Zac-HD** [comment]
Obsoleted by new build system, which is working just fine with `.pypirc` in `secrets.tar`.

(we may someday extract a reusable build system from our custom... thing, but it's not really a cleanup issue)
