### ISSUE TITLE
Sparse scientific hypotheses (for scipy.sparse)

### ISSUE THREAD

**Issue by jnothman** [HypothesisWorks/hypothesis#639]
Scipy provides numerous sparse matrix formats, and there are pitfalls in accepting sparse matrices to some function, making it a great place for Hypothesis to step in and ensure quality. Beyond the sparse matrix format (csr, csc, bsr, coo, lil, dia, dok), where not all need to be supported for some applications (e.g. setting elements on the matrix in place is not possible with all), issues include:
* diverse dtypes
* support for 32bit vs 64bit indices (for `{csr_matrix,csc_matrix,bsr_matrix}.{indptr,indices}` and `coo_matrix.{row,col}`
* the presence of explicit zero-valued elements (particularly in CSR, CSC, COO)
* indices not being sorted in CSR, CSC, BSR
* the presence of duplicate indices in CSR, CSC, COO formats

It would be great to have a scipy.sparse strategy in hypothesis

**Comment by Zac-HD** [comment]
While I would still love to see this - and I'd be happy to help anyone who wants to write it - [our contributing guidelines now recommend developing new extras as independent packages](https://github.com/HypothesisWorks/hypothesis/blob/master/CONTRIBUTING.rst#pull-request-or-external-package).  Once complete and with some feedback from users, it can be merged just like `from_regex` was.
