### ISSUE TITLE
Hypothesis-Python Logo

### ISSUE THREAD

**Issue by mulkieran** [HypothesisWorks/hypothesis#692]
I had an idea for a hypothesis-python logo once. It involves a python with its tail wrapped around a rubber stamp. The rubber stamp has the word "REFUTED" on it. The stamp could either face out, so it is read backward, or could face in, but its effect be shown, so it can be read forward. Somewhere the logo would also say Hypothesis. I have nothing like the necessary artistic ability to achieve this, alas.

I was somewhat inspired by the pystache logo: https://github.com/defunkt/pystache.

**Comment by DRMacIver** [comment]
I like the specific idea, and I like the idea more generally of having a logo. I looked into getting one a while ago and it didn't go so well, which is why we're still using the glitched circle I created ages ago as a placeholder.

**Comment by DRMacIver** [comment]
(I also lack the relevant artistic skills. Or any artistic skills to speak of. [This](http://drmaciver.github.io/hypothesis-talks/images/correctness-diagrams/show-possible.png) is what happens when people let me draw things)

**Comment by Zac-HD** [comment]
I also like the idea, and like the snake-with-refuted-stamp concept.  I also prefer simple logos (2D and few colours) to more complex mascots, but don't want to start a bikeshed debate - if we have a concrete proposal, I'll be happy 😄

**Comment by alexwlchan** [comment]
![img_3052](https://user-images.githubusercontent.com/301220/27039398-c1a6b68c-4f85-11e7-8d73-a939a2324912.JPG)

Behold my artistic powers.

**Comment by Zac-HD** [comment]
Suggestions from sprints today: a bug-hunter or edge-case-detective.  

(I think any artist who draws us something is going to have a strong influence!)

**Comment by kingdion** [comment]
> I also prefer simple logos (2D and few colours)

I have photoshop and made some quick concepts of stuff you can do. I can do something more drawn when I get home if you aren't into these, they're more quick, 2d/clean concepts with pythonic colours. Thoughts?

Could also fit a catchphrase beneath it or something. 

![hypothesis](https://user-images.githubusercontent.com/21191511/29050499-affceb74-7c1f-11e7-8963-6e1b694f49e0.png)

**Comment by Zac-HD** [comment]
I really like the magnifying glass title - it makes a great banner.  

On the favicon-scale (tiny but recognisable squarish logo), maybe something with a black swan?  (just tossing out random suggestions; you're the artist here 😄)

**Comment by kingdion** [comment]
> On the favicon-scale (tiny but recognisable squarish logo), maybe something with a black swan? (just tossing out random suggestions; you're the artist here 😄) Potentially a (black) swan's neck like a question mark, with a squashed bug for the dot...

Here's a quick go at the swan idea. Can change anything you want.
Contact me over slack if you want to talk further for the instant communication? 

![hypothesis-01](https://user-images.githubusercontent.com/21191511/29203919-45ba527a-7eb7-11e7-9364-013d816bdb5d.png)

**Comment by mulkieran** [comment]
I like the black swan art, and appreciate all the effort. But I'll point out that the advantage of my snake with stamp is that the logo has a connection not only to the purpose of Hypothesis, but also to its name, "hypothesis". The black swan has the least connection to the purpose and the name, I think.

**Comment by Zac-HD** [comment]
I was thinking of a black swan *as* a counterexample - to the old proverb 'as rare as a black swan' (before European colonisation of Australia) - and also as a reference to ['black swan' events](https://en.wikipedia.org/wiki/Black_swan_theory).

**Comment by mulkieran** [comment]
Of course you were! But Hypothesis is quite good for not-so-rare events, too.

**Comment by DRMacIver** [comment]
Thanks for these @kingdion! They look like good starts.

RE the black swan event as a theme for a log, I'm sorta -1 on the idea. Partly because it's a bit too obscure, but I think it also doesn't properly fit for people who get the reference: Most of what Hypothesis finds *aren't* black swan events. It's more about thorough inspection of the common areas, and it ends to miss things that are truly rare.

**Comment by mulkieran** [comment]
I admit I also thought about the magnifying glass logo over the wkend and it struct me as terribly generic. Yes, Hypothesis does find bugs, very well, but it finds it in a particular way. The magnifying glass logo would seem more appropriate to something like findbugs (http://findbugs.sourceforge.net/), which does scrutinize the code line-by-line looking for bugs.

**Comment by Zac-HD** [comment]
@mulkieran, you like the black swan but not the magnifying glass?

@DRMacIver, I (and @kingdion) would appreciate a clear statement of what you *do* want in a logo, so we can at least start brainstorming again 😄

**Comment by mulkieran** [comment]
I worked up a story for the black swan that worked for me. But it might not be close enough to the true operation of Hypothesis to really be appropriate.

**Comment by DRMacIver** [comment]
> @DRMacIver, I (and @kingdion) would appreciate a clear statement of what you do want in a logo, so we can at least start brainstorming again 😄

Sorry, I didn't mean to neglect this.

Part of the problem is that I don't know. I am absolutely horrible at visuals (I literally have a condition that makes me unable to visualise), so I'm really really bad at answering questions like this.

Here are some general thoughts/constraints:

* I'd like it to be usable on its own without the accompanying text (but having a way to integrate it into the text is also nice).
* I'd like it not to be too Python specific because Hypothesis-for-not-Python really will be a thing honest and it would be nice to have a consistent logo across the versions.

Things that it would be nice if the logo evokes some of:

* randomness
* science
* safety
* assistance/assistants

(Side note: I made a joke a while ago that [Sinister](https://twitter.com/sinister_katze) should be the Hypothesis mascot because he's fuzzy and loves finding bugs. I don't think this is an actually good idea for a logo, but I am not averse to terrible puns as the justification for the logo)

In terms of the general operation of Hypothesis, the reason I don't really like the black swan concept is that Hypothesis should be thought of not as magically increasing your testing capability to some inhuman level. It's better thought of as the testing you would write anyway consistently performing at your peak. Hypothesis probably *won't* find anything you *couldn't* find by manual testing, but it will find things you *didn't* (because time constraints, you didn't get enough sleep last night, etc). It's a self-driving car, not a tardis.

**Comment by DRMacIver** [comment]
Oh a friend suggested when I told him about #811 that maybe the Hypothesis logo should be an [Ouroborous](https://en.wikipedia.org/wiki/Ouroboros). This fails literally everything I mentioned above, but I still kinda like the idea.

**Comment by Zac-HD** [comment]
I vote Ouroborous as the logo for *the Hypothesis-python test suite*, but not for Hypothesis itself 😄 

> Hypothesis should be thought of not as magically increasing your testing capability to some inhuman level. It's better thought of as the testing you would write anyway consistently performing at your peak. 

I disagree actually - it might not be literally superhuman, but the testimonials indicate that Hypothesis makes a qualitative difference to the testing capability even of strong teams!  (and you personally have a *very high* peak testing ability)

----------------

About the black swan specifically though, I think we disagree mostly about *how people will interpret it*, not the message we want the logo to send.

For me (and I hope others) the strongest association of a black swan is as the world's most famous [falsifying counterexample](https://en.wikipedia.org/wiki/Falsifiability) - the wikipedia article literally uses a black swan as the page image.  To quote it:

> Statements, **hypotheses**, or theories have falsifiability or refutability if there is the inherent possibility that they can be proven false. They are falsifiable if it is possible to conceive of an observation or an argument which could negate them.  ...  For example, the universal generalization that *'All swans are white'* is falsifiable since it is logically possible to falsify it by observing a single black swan. Thus, **the term falsifiability is sometimes synonymous to testability.**

Sounds relevant to me!  

Plus it's a pretty and distinctive thing to draw, easily recognizable at various scales, and certainly not associated with pythons 😄 

(The only way it could be better is if swans ate bugs, but alas they're mostly herbivores.  Maybe people will confuse that with ducks though?)

**Comment by Zac-HD** [comment]
An alternative idea: maybe something with a moth?  There's a huge variety of [styles](http://thefw.com/ridiculously-cute-moths/) and accessories moths can be drawn with.

The context is that the "First actual case of a bug being found" (exact quote) was recorded in 1947, when Grace Hopper [removed a moth from her hardware](https://www.wired.com/2013/12/googles-doodle-honors-grace-hopper-and-entomology/).

(I still prefer a swan, but mostly just want to get *something* done!)

**Comment by Zac-HD** [comment]
(this topic has moved to private discussions)

**Comment by whatevergeek** [comment]
hi! anyone got a back story on the dragonfly logo?
I'm planning to share hypothesis in a local meetup here in Singapore.
Just in case anyone asks... :-)

**Comment by Zac-HD** [comment]
#1519 has the newest logos (😍) FYI.

Backstory is that dragonflies are beautiful and active insectivores... That is, they hunt and kill bugs!
