### ISSUE TITLE
--hypothesis-show-statistics doesn't work with pytest-xdist

### ISSUE THREAD

**Issue by DRMacIver** [HypothesisWorks/hypothesis#700]
If you use the flag while running with xdist then you'll get no statistics. This is presumably because the tests are running in a different process than the collector, so the data isn't getting communicated back.

To reproduce e.g. run `pytest --hypothesis-show-statistics tests/cover/test_testdecorators.py`, which will use the default Hypothesis configuration and run with two child runners and show no statistics.

**Comment by Zac-HD** [comment]
Related to pytest-dev/pytest-xdist#79.  Our current code, which doesn't work with xdist, is:

https://github.com/HypothesisWorks/hypothesis/blob/fe60c8aae7fd8478ef08acfd9f8f852ec004c1e7/hypothesis-python/src/hypothesis/extra/pytestplugin.py#L107-L113

It looks like we'll need to write some special-case logic to pass the report string back to the master instance when running under `xdist`, and probably also to receive the data.  See e.g. [the hook docs](https://docs.pytest.org/en/documentation-restructure/how-to/writing_plugins.html#_pytest.hookspec.pytest_runtest_makereport) and [xdist/workermanage.py](https://github.com/pytest-dev/pytest-xdist/blob/master/xdist/workermanage.py) as starting points.
