### ISSUE TITLE
Support for hypothesis django testing with pytest

### ISSUE THREAD

**Issue by sliverc** [HypothesisWorks/hypothesis#733]
Currently to run Hypothesis Django integration it is required to subclass a unittest `hypothesis.extra.django.TestCase` class so each example runs in its own transaction. It would be great to have such an integration for pytest as well as an extension of [pytest-django](https://github.com/pytest-dev/pytest-django) so that following example would work.

```python
@given(models(User))
def test_user_test(db, user):
  assert User.objects.count() == 1
```

Maybe there is an easy way to do this already but I haven't been successful so far.

**Comment by DRMacIver** [comment]
I'd definitely like us to, but it's more or less blocked on better pytest integration, which is more or less blocked on [things on the pytest end](https://github.com/pytest-dev/pytest/issues/916). 

I suspect this will Just Work if and when we get better fixture support. Unfortunately I wouldn't hold your breath on that front. I spent about a week trying to work around this a while back and concluded that it would probably take another couple of weeks of solid work to make this function with pytest as it currently is, so this probably isn't going to happen any time soon unless someone wants to fund the development.

**Comment by Zac-HD** [comment]
Related to #59, #377.

**Comment by Zac-HD** [comment]
#1257 won't solve the fixtures problem, but would allow `pytest-django` (or an extension) to insert a wrapper between `@given` and the test function that runs each test case (ie inner function invocation by `@given`) in a database transaction.

**Comment by Zac-HD** [comment]
Closing this because there are two possible solutions:

- Transparently make function-scoped Pytest fixtures Hypothesis-example-scoped, i.e. #377 
- Ask `pytest-django` to handle this based on the `django_db` mark they add.  [Here's how `pytest-trio` handles it](https://github.com/python-trio/pytest-trio/blob/46f2ba7bf337d836e4b640a0d4ecf76411341366/pytest_trio/plugin.py#L340-L356).  In this case it's an upstream issue, though I'd be happy to advise anyone taking it on.

**Comment by OtherBarry** [comment]
For anyone else having this issue, I've posted an interim solution in pytest-django here: https://github.com/pytest-dev/pytest-django/issues/912#issuecomment-1091659189
