### ISSUE TITLE
Is there a way to relieve ram usage?

### ISSUE THREAD

**Issue by CodyKochmann** [HypothesisWorks/hypothesis#833]
I like to use hypothesis and iPython to both play with different ideas for strategies and to run various different tests against functions. After a while into the testing session or after a test that runs a lot of iterations, the ipython session ram usage really climbs up (I got to 12 gigs yesterday while playing with a couple functions). 

I'm not doing anything crazy. Just generic tests with generic strategies, there's just a lot of iterations. It kinda makes me believe that that's why there's a 5 minute internal limit in hypothesis on running tests since it takes roughly 5 minutes for hypothesis to reach 5-8 gigs in ram. 

The ram usage is understandable, complicated things are happening in order to not have duplicated tests and there's probably some caching going on as well. This issue is more to answer the question of "is there a way to relieve the ram usage after I'm done using a certain strategy?" Once ram gets to a certain point, ipython becomes unusable and forces me to exit out of the session to clear the ram. 

I've tried forcing garbage collection and not too much really changed in the ram so I'm curious if there's something internal to hypothesis that I need to call or `del` or reload to clean things up a bit.

**Comment by DRMacIver** [comment]
I don't think the level of memory usage you're experiencing is typical - certainly I've never seen Hypothesis memory usage go anywhere near that high - which means it's hard to answer the question without more data or, ideally, a reproducible example.

The two most likely places memory usage could be blowing up are either the strategy cache (in which case it's an easy problem to solve. There currently isn't any public API you can use to do that, but it wouldn't be hard to add one) or the example tracking (in which case it's much harder). If the memory isn't reclaimed when the test finishes running and after a GC call it's *probably* the former, but it's hard to say for sure.

**Comment by Zac-HD** [comment]
Closed by #874.  #868 (pending) further reduces memory use by 50% to 60%.

**Comment by DRMacIver** [comment]
I don't think it is. #874 fixes what is a significantly smaller part of the problem.

**Comment by Zac-HD** [comment]
Closed by #1567.
