### ISSUE TITLE
Better example shrinking in from_regex()

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#841]
`find(st.from_regex('a|'), lambda s: True) == 'a'`, but the empty string `''` would be a better shrink.

In principle, we should reorder the branches in the parsed regex so that shrinking the derived strategy finds the shortest possible string for any condition.  In practice this is infeasible.

Simply ordering branches by the length of the shortest matching string would be a good start, and a substantial improvement over the current shrinking even with a best-effort key function (I imagine that determining the length of the minimum match is not always easy).

For example, `find(from_regex('a+|(bb)*?'), bool)` would generate `bb` instead of `a` unless we  rewrite the parse tree to split repeaters into cases for zero, one, or more repetitions - which I think might actually be a worthwhile optimisation.

Fancier stuff than that is out of scope though, unless someone volunteers 😄

**Comment by Zac-HD** [comment]
I propose to basically ignore non-trivial references as being more trouble than they're worth for this kind of optimisation.  If there's cheap options I'll happily take them, but I have no desire to do anything that might prompt someone to reach for a SAT solver.

I considered special-casing a whole-pattern match for the empty string, but I think that stops being interesting basically as soon as you have a nontrivial second predicate (ie error condition to trigger).  In any case, a decent internal optimisation should always put empty matches first, so it falls naturally out of the more complex version.

- Literals are trivially shortlex orderable (even with our non-codepoint shrinking key for unicode).
- Sets, negated sets, and negated literals are trivially reducible to the minimal literal.  So far this is exact.
- For group-references, order as for the group - requires a lookup but not tricky.
- Order lookarounds and assertions first if they can match empty or last otherwise.
- Branches and repeats are ordered by the minimal match they allow.
- The cost of a pattern or subpattern is the sum of costs of minimal parts (ie all literals, cheapest branches, etc).

This is not a trivial set of rewriting rules, but I think covers most use-cases.  Where it gets interesting is the option things we could do to shrink better when the output must satisfy some unknown predicate.

- Most of the hacks come down to splitting units into branches, and lifting the result.  If we can then interleave them without changing what the pattern matches, as for example in `'a+|(bb)*?'` -> `'|a+?|(bb)+?'` (moving a match of zero times `bb` to the front).
- I have a hazy idea that something similar for overlapping character sets might also be desirable, but no example at the moment.

All this said I have no intention of implementing this in the near future, but I might try to offer it to a few professors as a student project...

**Comment by DRMacIver** [comment]
> My intuition is that splitting things into branches and lifting them as high as possible before ordering is useful

I believe the regex parser does this anyway based on some example output I've seen from it.

**Comment by Zac-HD** [comment]
`sre_parse.parse` does some optimisations - for example a branch between single-character literals becomes a set rather than a branch - but they're pretty weak.  In particular, the split and lift operations are entirely missing.  (This all ignores the actual matching machinery, which does much more but isn't relevant here)

Some examples which could be equivalent but aren't by default:  `c|(b|a)` could be `(a|b)|c` just by ordering branches; `a+|(bb)*` could be `a+|(|(bb)+)` and then `|a+|(bb)+` by splitting repeaters and lifting branches out of a subpattern.  Try it out!

**Comment by DRMacIver** [comment]
Ah, yes, right. That actually points to a way in which we have to be quite careful (both when doing this and it might also have some bad behaviour lurking currently). `|` is not a commutative or associate operator for Python regex because it affects the matching groups. Consider `aa|a` vs `a|aa` matching the string `"aa"` - the former returns a two character match, the latter a one character match.

Which is potentially also significant for group capturing, though I can't currently find an example where it changes something from contains a match to doesn't contain a match.

**Comment by Zac-HD** [comment]
Actually not much of a concern - for the parsed tree we only care about whether or not it matches the same set of strings, not what the resulting match object would be.

Because groups have already been parsed and assigned an ID, reordering and adding groups still works as long as we don't give new nodes a duplicate ID and avoid breaking referenced groups (by eg lifting branches out of a group that's referenced elsewhere).  An initial pass that records all keys used by group-reference nodes would work for this.

**Comment by Zac-HD** [comment]
I was just reminded to post [my presentation on this topic](https://zac-hd.github.io/slides/regex).

The main relevant points are generally in my big comment above, but in short: there *will* be edge cases we "shrink" incorrectly, especially with a predicate to satisfy.  The trick is to cover common cases without making the code impossible to read - or write!

**Comment by Zac-HD** [comment]
I've just spent a few days playing with [`greenery`](https://pypi.org/project/greenery/), a lovely library for analysing regex (true regular languages) as finite state machines.

My view is now that this is *definitely* possible, at least for true non-PCRE regular expressions, but would require several weeks of focused work for what is in the end a marginal gain.

I remain happy to advise anyone who really wants to take this on, but no longer think it's something Hypothesis should have on even an undated roadmap.
