### ISSUE TITLE
builds() and from_type() should introspect attrs-classes

### ISSUE THREAD

**Issue by Zac-HD** [HypothesisWorks/hypothesis#954]
There's heaps of metadata on the attributes, and we could certainly infer a strategy for attributes with an "instance_of" validator.  Even with python-attrs/attrs#249, special handling would still be valuable because we could filter by any other validators.

This issue brought to you by realizing that I wanted this feature in a project I'm playing with - in that case it's going to be faster to hard-code a strategy, but it would definitely be *used* as well as nice to have 😄

**Comment by CodyKochmann** [comment]
Ive had to reroute a few projects because I was using that type of layout but didn't have a clean way to test specifically this so definitely +1

**Comment by Zac-HD** [comment]
Some notes:

- `attrs` [supports extensions](http://www.attrs.org/en/stable/extending.html) by providing [`Attribute`](http://www.attrs.org/en/stable/api.html#attr.Attribute) objects.
- `attr.fields(SomeClass)` returns a tuple of `Attribute`s for `SomeClass`
- An `Attribute` may have a `default` of a value or a factory; and may also have a `type`.  These are easy to construct a strategy for.
- In the unlikely event that `default==NOTHING and type is None` but `convert` or `converter` (at most one may be non-None) is a callable with type annotations, we may be able to infer a strategy that way.
- Converters may also be wrapped in [`converters.optional`](http://www.attrs.org/en/stable/api.html#attr.converters.optional), which makes `None` a valid value.

This all becomes more "interesting" once we start to consider validators.

- Validators are always run in order when `__init__` is called.  However, we can improve filtering efficiency substantially by attempting to validate each field separately with some reject-and-retry logic rather than accepting or rejecting everything together.
- [Built-in validators](http://www.attrs.org/en/stable/api.html#validators) are great for introspection.  `optional` as for converters.  An `instance_of` validator is an older way of specifying `type`.  An `in_` validator is a perfect feeder for `sampled_from`.
- Multiple validators can be given as a list or wrapped in `and_`; each are run in order so we'd need to unwrap them.
- Validators run on the state-so-far, and may depend on multiple fields, so we can't generate each attribute in isolation.  Instead infer a strategy for each, then run validators in order with retry logic as mentioned above.

All together, this probably means we'll write a new module `hypothesis.searchstrategy.attrs` and function `from_attrs_class`, then `if isinstance(thing, type) and attr.has(thing)` `return from_attrs_class(thing, *args, **kwargs)` - as for `builds` itself and e.g. Django models, we want to allow users to set sub-strategies explicitly - at the top of `builds` (and `from_type`).
