### ISSUE TITLE
Run tests in CI with PYTHONOPTIMIZE=2

### ISSUE THREAD

**Issue by alexwlchan** [HypothesisWorks/hypothesis#987]
aka take #824, but actually finish it.

**Comment by Zac-HD** [comment]
This could be implemented efficiently by adding 

    PYTHONOPTIMIZE=2 $PYTEST tests/cover/test_testdecorators.py

here 

https://github.com/HypothesisWorks/hypothesis/blob/08896299c27aaec6dc232c641d5d93e52a858461/hypothesis-python/scripts/basic-test.sh#L58-L60

where it will only run on the deliberately slower but complete test runs.

**Comment by Zac-HD** [comment]
And since I read it and wondered, couldn't we just do `$PYTEST tests/nocover/` instead of 

https://github.com/HypothesisWorks/hypothesis/blob/08896299c27aaec6dc232c641d5d93e52a858461/hypothesis-python/scripts/basic-test.sh#L41-L43

**Comment by DRMacIver** [comment]
> And since I read it and wondered, couldn't we just do $PYTEST tests/nocover/ instead of

We could! It's a historical workaround for when the Hypothesis test suite used to regularly segfault pypy.
